antrea-io/antrea

.github/workflows/build_master.yml
.github/workflows/build_tag.yml
Makefile
build/yamls/antrea.yml
build/yamls/overlays/dev/kustomization.yml
docs/getting-started.md
docs/kind.md
test/e2e/README.md
test/e2e/infra/vagrant/push_antrea.sh

We push the master branch version as antrea/antrea:latest and every
Github tag as antrea/antrea:<TAG>.

Use Github workflows to push Antrea Docker image to dockerhub

---

ROADMAP.md

Update status of NetworkPolicy and Octant UI plugin.
Add network and NetworkPolicy troubleshooting to future items.

Update ROADMAP doc

---

README.md
docs/getting-started.md

Keeping it small and super fast to browse intentionally.

Move curated features list to README

---

pkg/agent/cniserver/ipam/ipam_delegator.go

When Antrea agent runs as a Pod, the IPAM plugin is always installed
in /opt/cni/bin, but kubelet can be configured to use different
paths to search for CNI plugins. This PR always adds /opt/cni/bin to
the CNI plugin searching paths to make sure the IPAM plugin installed
in the agent Pod can be found.
Fixes: #120

Always include /opt/cni/bin for searching the IPAM CNI plugin

---

pkg/agent/cniserver/pod_configuration.go

Pod Openflow entries were installed after configurating container IP
address, during which gratuitous ARP were sent but always dropped by
Openflow. This patch switches the order of them to ensure gratuitous ARP
be broadcast.
Besides, it fixes typo and removes comments redundant to the code or
logs.
Fixes #129

Fix GARP being dropped when adding container interface

---

CONTRIBUTING.md

Add information about the CLA in CONTRIBUTING.md

---

cmd/antrea-agent/agent.go
cmd/antrea-agent/options.go
pkg/agent/agent.go
pkg/ovs/ovsconfig/errors.go
pkg/ovs/ovsconfig/interfaces.go
pkg/ovs/ovsconfig/ovs_client.go
pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
test/integration/ovs/ovs_client_test.go

Merge VXLAN and Geneve funcs to shared ones.
Add TunnelType to specify the VXLAN or Geneve tunnel type.
Add IPSec PSK option.

Revise tunnel port creation of OVS client

---

ROADMAP.md
docs/configuration.md

Fixed a couple of typos noticed while going through some of the
documents.

Fix typo in documents

---

test/e2e/basic_test.go
test/e2e/connectivity_test.go
test/e2e/framework.go

* Implemented createNginxPod
* Refactored createPod
* Implemented createService
* Refactored randPodName

Refactor framework: createPod and createService

---

Makefile
pkg/agent/openflow/client_test.go

- Add `-race` in unit test to enable race detector
- Fix a unit test which has race issue
Resovles #147

Enable race detector in unit test

---

test/integration/agent/cniserver_test.go
test/integration/agent/openflow_test.go
test/integration/ovs/ovs_client_test.go

- Correct imports
- Removed un-needed casts
- Correct typos
Resolves #177

Fix broken integration test

---

pkg/controller/networkpolicy/networkpolicy_controller.go
pkg/controller/networkpolicy/networkpolicy_controller_test.go

For K8s NetworkPolicy, a rule with empty NetworkPolicyPeer is supposed
to match all addresses (default-allow), while a policy with no rule is
supposed to deny all addresses (default-deny).
This patch supports them by making the following changes:
1. Convert empty NetworkPolicyPeer to a matchAll peer, so that openflow
client can install a flow matching all addresses.
2. If ingress/egress isolation is specified explicitly and there's no
ingress/egress rule, append a deny-all rule in direction "In"/"Out", so
that Openflow client can install a flow matching no addresses.
Besides, it extracts a common method to reduce code redundancy and adds
unit tests for processNetworkPolicy.
Fixes #131

Fix default-allow and default-deny NetworkPolicies

---

Makefile
ROADMAP.md
build/images/Dockerfile.octant.ubuntu
build/yamls/antrea-octant.yml
docs/octant-plugin-installation.md

Add document and image for deploying octant and
antrea-octant-plugin.
Fixes #58

Add document and image to deploy antrea-octant-plugin

---

.github/workflows/go.yml
.github/workflows/integration.yml
.github/workflows/kind.yml
CONTRIBUTING.md
Makefile
build/images/Dockerfile.build.ubuntu
build/images/Dockerfile.octant.ubuntu
go.mod
hack/tidy-check.sh

Bump go version to 1.13

---

pkg/agent/controller/networkpolicy/cache.go
pkg/agent/controller/networkpolicy/reconciler.go
pkg/agent/controller/networkpolicy/reconciler_test.go

Support Except field of NetworkPolicy

---

docs/getting-started.md

Add a note about replacing other CNI with Antrea

---

pkg/agent/controller/networkpolicy/reconciler.go
pkg/agent/controller/networkpolicy/reconciler_test.go

Antrea doesn't support named port yet, but if a policy with named port
is defined, it's enforced as allowing all ports, which may introduce
security risk. Before we can support named port, it should only allow
known ports it can resolve.
Fixes #241

Fix policy with named port allowing all ports

---

pkg/controller/networkpolicy/networkpolicy_controller.go

In SyncAppliedToGroup, it could happen that some NetworkPolicies
refers it after the method queries the related NetworkPolicies. In this
case these policies won't be enqueued after updating AppliedToGroup's
span, which leaves them in a non consistent state.
This PR fixes it by moving the query after storing the updated
AppliedToGroup, so that both of the NetworkPolicies that referred it
before storing it and the ones after storing it can get the right span.
Fixes #233

Fix NetworkPolicy span not updated due to a race condition

---

cmd/antrea-agent/options.go
go.mod
pkg/agent/agent.go
pkg/agent/openflow/client.go
pkg/agent/openflow/client_test.go
pkg/agent/openflow/cookie/allocator.go
pkg/agent/openflow/cookie/allocator_test.go
pkg/agent/openflow/cookie/doc.go
pkg/agent/openflow/network_policy_test.go
pkg/agent/openflow/pipeline.go
pkg/agent/openflow/testing/mock_openflow.go
test/integration/agent/openflow_test.go

- Add a cookie allocator to mark flow by cookie id
- Add function `roundNum` to client.go to read roundNum from ovsdb
- Updated related mocks, unit tests and integration tests
Resolves #134

Implement cookie allocator to mark flow by cookie id

---

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go

Fix UT TestAddNetworkPolicyWithMultipleRules
Fix UT TestAddNetworkPolicyWithMultipleRules.
The test is used for checking the number of NetworkPolicy related objects when the NetworkPolicy carries multiple rules.

Fix UT TestAddNetworkPolicyWithMultipleRules

---

docs/getting-started.md

That's my proposal for this. It's one of the remaining open items for https://github.com/vmware-tanzu/antrea/issues/8.

Add animated gif demo to getting started

---

go.mod
go.sum

Bump up contiv/libOpenflow version to fix a race issue in creating MatchField.
The fix in contiv/libOpenflw is https://github.com/contiv/libOpenflow/pull/10
Fixes #285

Bump up contiv/libOpenflow version

---

pkg/ovs/openflow/ofctrl_bridge.go

Function GetFlowTableStatus will be invoked by monitoring goroutine
every minute to get OVS flow table information.
To protect both tableCache and ofTable from concurrent modifictation
and interation, change Mutex to RWMutex for tableCahe and ofTable.
Fixes: #304

Change Mutex to RWMutex for openflow tableCache

---

ci/jenkins/README.md
ci/jenkins/jobs/job-templates.yaml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml

Issue #254 
* README for introduction
* jobs in yaml for jenkins-job-builder

Jenkins jobs for antrea

---

pkg/antctl/client.go
pkg/antctl/command_definition.go
pkg/antctl/command_definition_test.go

Unified internal request path passing of the antctl client for both remote mode and local mode.
This change does not affect current command implementations.

Enhance argument passing of antctl client

---

hack/kind-linux.sh

Add workaround for Kind apiserver delegation issue

---

pkg/antctl/command_definition.go
pkg/antctl/command_definition_test.go

Issue #319
If the json output is like:
```
[
{
"f0": "v0",
"f1": "v1",
"f2": "v2"
},
{
"f0": "v3",
"f1": "v4",
"f2": "v5"
}
]
```
Then the expected table output will be like:
```
f0   f1   f2
v0   v1   v2
v3   v4   v5
```

Implement antctl table output formatter

---

pkg/antctl/command_definition.go

There used to be only one local flag, "output" and users cannot specify their own flags. This patch is to realize this feature.

Improve flag implementation in antctl

---

pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go

1. One lock is shared in globalConjMatchFlowCache, which is locked before
calculate the conjMatchFlowContext change, and unlocked after the
context status is updated.
2. Update conjMatchFlowContext after the Openflow entries are installed
successfully.
Fixes #332

Use Bundle to implement Network Policy on Antrea Agent

---

docs/design/cni-testing-initiative-upstream.md
hack/cni-testing-initiative-upstream.md

For #379 .
@McCodeman  lets merge this (into hack) and we can start iterating against it.

Testing upstream initiative working draft

---

pkg/controller/networkpolicy/networkpolicy_controller_test.go

Add UT for the recently added functions.
- ipStrToIPAddress()
- cidrStrToIPNet()

Add unit tests to NetworkPolicy util functions

---

pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go

Use a unique format to generate the key of a conjunctive match flow
in the global cache for both IP and IPNet. This could ensure the conjunctive
match flow context in Antrea agent is the same as the flow entry realized
on the OVS.
Fixes #386

Fix bug in NetworkPolicy implementation with OpenFlow

---

README.md
ROADMAP.md

Add IPsec encyption to supported features.
Remove NetworkPolicy, Octant, CLI, IPsec, Openflow Go binding from
under-development features.
Reorder ROADMAP items.

Update feature list in README.md and ROADMAP.md

---

ci/jenkins/jobs/projects.yaml

Enable named port NetworkPolicy e2e tests in CI

---

pkg/agent/cniserver/pod_configuration.go

Deleting veth devices and OVS port must be called after Openflows are
uninstalled. Otherwise there could be a race condition:
1. Pod A's ofport was released
2. Pod B got the ofport released above
3. Flows for Pod B were installed
4. Flows for Pod A were uninstalled
Because Pod A and Pod B had same ofport, they had overlapping flows,
e.g. the classifier flow in table 0 which has only in_port as the match
condition, then step 4 can remove flows owned by Pod B by mistake.
This patch moves UninstallPodFlows before releasing ofport to avoid the
race condition.
Fixes #430

Fix ofport reuse causing openflow being deleted

---

go.mod
go.sum

Update Go netlink from 1.0.0 to 1.1.0

---

ci/jenkins/jobs/job-templates.yaml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml

Job validator is used to validate if PR that changes jenkins jobs code is correct.

Add job validator

---

ci/jenkins/README.md
ci/jenkins/jobs/job-templates.yaml
ci/jenkins/jobs/macros.yaml

* Update jenkins README: Add jenkins jobs validator in "List of Jenkins jobs"
* job validator fix: no defaults, included_regions in ghprb

Jenkins jobs and README update

---

build/images/ovs/apply-patches.sh

We backport this patch to OVS 2.13.0:
https://github.com/openvswitch/ovs/commit/7cc77b301f80a63cd4893198d82be0eef303f731
It reduces down time for inter-Node traffic (overlay mode) when the
Agent Pod is restarted, by ensuring that the tunnel ports don't get
deleted on exit.

Add new "tunnel backer ports" patch to OVS image

---

build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/agent.yml
build/yamls/base/controller.yml

Add readiness HTTP probe configurations for Antrea agent and controller
Fixes #418, #419

Add health checks to antrea components

---

pkg/apiserver/storage/ram/store_test.go

The test was flaky because terminating watchers is asynchronous and it
could take some extra time to receive the terminated notification. The
extra time was set to 10 ms which turned out to be not safe enough, this
patch increases it to 100 ms.
Fixes #483

Fix flaky unit test TestRamStoreWatchTimeout

---

pkg/cni/client.go
pkg/cni/default.go
pkg/cni/default_windows.go

Set CNI server default address for Windows platform.

[Windows] Set CNI server default address for Windows platform

---

build/yamls/antrea-eks.yml

It is not updated correctly by previous commits.

Fix antrea-eks.yml

---

pkg/agent/agent.go
pkg/agent/controller/networkpolicy/cache.go
pkg/agent/controller/networkpolicy/networkpolicy_controller.go
pkg/agent/controller/networkpolicy/reconciler.go
pkg/controller/networkpolicy/networkpolicy_controller.go
pkg/monitor/monitor.go

* Added a few V0 logs for essential NetworkPolicy events like
creation/deletion of computed NetworkPolicy.
* Added NetworkPolicy context when logging rule that are being
installed.
* Adjusted a few logs that are in inconsistent style.
Fixes #516

Improve NetworkPolicy logging

---

.github/workflows/go.yml
Makefile
ROADMAP.md
build/yamls/antrea-eks.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf
ci/kind/kind-setup.sh
docs/ovs-pipeline.md
hack/.spelling_failures
hack/terraform-eks.sh
hack/verify-spelling.sh
test/e2e/infra/vagrant/playbook/roles/worker/tasks/main.yml

Add a script to check commonly misspelled English words.

Add spell check script to hack

---

build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/agent.yml
build/yamls/base/controller.yml

Mount /var/log/antrea/ to the controller and agent containers, and
change controller and agent log parameters to log to both the dir
and stderr.

Let controller and agent log to host dir

---

test/e2e/README.md
test/e2e/connectivity_test.go

Remove inconsistencies in logging and old notes from e2e README.

Improve logging for e2e tests

---

docs/kind.md
site/_data/master-toc.yml
site/docs/master/kind.md

* Updated docs ToC for kind to "Deploy to kind"
* Fixed issue reference in kind.md

Updated docs ToC, fixed kind.md issue ref

---

test/e2e/framework.go

The flakiness was caused by an incorrect check to establish readiness of
the Antrea Agents.
This fix also takes care of the very flaky upgrade tests, by making sure
that we wait for the rolling update to complete every time we change the
Antrea yaml.
Fixes #545

Fix flakiness in TestPodConnectivityAfterAntreaRestart

---

pkg/antctl/antctl.go
pkg/antctl/client.go
pkg/antctl/command_definition.go
pkg/antctl/command_definition_test.go
pkg/antctl/command_list.go
pkg/antctl/command_list_test.go
pkg/antctl/command_runtime.go
test/e2e/antctl_test.go

Just to check all commands can be executed but do not check the
results.

Validate all controller and agent commands in antctl test

---

pkg/ovs/openflow/interfaces.go
pkg/ovs/openflow/ofctrl_action.go
pkg/ovs/openflow/testing/mock_openflow.go
test/integration/ovs/ofctrl_test.go

- Implement openflow learn action control interface
- Add related tests in integration test

Implement openflow learn action control interface

---

docs/manual-installation.md
site/docs/master/manual-installation.md
site/index.html

* Updated index page to advertise release v0.5.1
* Fixed ordered lists in manual installation

Bumped advertised release to v0.5.1

---

docs/troubleshooting.md

"antctl get network-policy" shold be "antctl get networkpolicy"

Fix antctl command names in troubleshooting.md

---

cmd/antrea-agent/options.go
cmd/antrea-controller/options.go

The error message was opposite to the fact.

Fix wrong error message when positional arguments are provided

---

ci/jenkins/jobs/macros.yaml

Set timeout of sonobuoy jobs (conformance, networkpolicy) to 1800s.

Timeout for sonobuoy jobs

---

ci/jenkins/jobs/macros.yaml

Now it doesn't exit immediately when error happens.

set -ex for bash script

---

docs/getting-started.md
docs/os-issues.md

Document known issues on Photon OS and CoreOS

---

pkg/agent/querier/querier.go
pkg/monitor/agent.go
pkg/monitor/controller.go

1. Support conitinue updating CRD when error
occurs.
2. Fix Agent monitoring CRD creation issue by setting
agent CRD name.
3. Some code refactor for monitoring CRD part.
Issue: #619

Fix monitoring CRD issues

---

ci/jenkins/jobs/job-templates.yaml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml
ci/test-conformance-eks.sh

The tests will be hosted on http://jenkins.antrea-ci.rocks

Adding upstream conformance and network policy CI for Antrea

---

pkg/agent/cniserver/interface_configuration_windows.go
pkg/agent/cniserver/server.go

1. On Windows, CNI Add messages are sent for all containers in the same Pod, this is different from Linux. The lock in cniserver should work on the infrastructure container but not the workload container on Windows. Using the k8s_pod_namespace + k8s_pod_name as the key of the lock.
2. HNSEndpoint deletion is blocking by Windows HNS service sometimes. Add a timeout control in HNSEndpoint deletion to avoid cniserver gives no reponse because of the stuck.

[Windows] Resolve Windows cniserver blocking issue

---

pkg/antctl/command_definition.go

This is for the case rows of a single column table can be too long to
fit into one line. One example is the ovsflows outputs (every row is
an OVS flow string).

Do not add tailing spaces to rows in antctl single column output table

---

docs/antctl.md
docs/troubleshooting.md

This PR includes OVS tracing. If the OVS tracing PR #663 will take longer time to review and merge, I would move the tracing contents to that PR, to merge this one earlier.

Document antctl troubleshooting commands

---

pkg/agent/apiserver/handlers/agentinfo/handler.go
pkg/antctl/antctl.go

* Dump OVS flows of a flow Table should be "-T <TABLE>"
* NodeSubnet should be in agentinfo

Fix incorrect antctl example and output

---

ci/run-k8s-e2e-tests.sh
ci/test-conformance-eks.sh

Skip NodePort testcases for EKS

---

test/e2e/README.md

Tested locally on ubuntu 18.04 setup

Checking cluster status with kubectl locally

---

hack/windows/Install-OVS.ps1

At the moment the archive can only be downloaded over HTTP and not
HTTPS (because of how virtual hosting works with AWS S3). We are working
on getting HTTPS downloads to work for downloads.antrea.io. In the
meantime we verify that the SHA256 hash for the downloaded archive is
correct.

Use correct URL for Windows OVS binaries

---

test/integration/ovs/ofctrl_test.go

Fix integration test failure

---

.github/workflows/build.yml

The step should only be run for push events on the master branch, but the
branch ref used in the test was incorrect. It should be
'refs/heads/master' and not just 'master'.
Fixes #756

Fix conditional step in workflow for pushing latest Antrea images

---

ci/jenkins/jobs/macros.yaml
go.mod
test/e2e/README.md
test/e2e/infra/vagrant/push_antrea.sh
test/e2e/prometheus_test.go

Verifies that Prometheus integration works properly after changes.
Performs the following checks:
- Test controller metrics on both controller and Prometheus endpoints
- Test agent metrics on each agent, and on Prometheus

Test Prometheus integration in CI

---

test/e2e/bandwidth_test.go
test/e2e/fixtures.go
test/e2e/framework.go
test/e2e/main_test.go
test/e2e/performance_test.go

- Service bandwidth of intra-node traffic
- Service bandwidth of across nodes traffic
- Enhance service creation functions in e2e framework

Add service bandwidth benchmark

---

docs/os-issues.md

Fix networkd configuration section name in CoreOS documentation

---

build/yamls/antrea-windows.yml
build/yamls/windows/base/conf/antrea-agent.conf
docs/windows.md

Modify Windows document to add Geneve as a supported tunnel type.

[Windows] Add Geneve as a supported tunnel type

---

go.mod
go.sum

Update the ofnet to involve the fix https://github.com/wenyingd/ofnet/pull/12 in upstream.

Update ofnet version

---

pkg/agent/util/iptables/iptables.go

Add logging when iptables-restores fails

---

ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml

* /test-all shouldn't trigger whole-conformance test
* remove --e2e-parallel for whole-conformance test
* update antrea-bot message
* allocate 2.5 hr for whole-conformance test

whole-conformance test fix

---

ci/jenkins/jobs/macros.yaml

* delete ns after get-secret fails
* fix savelogs command not found issue
e.g. https://jenkins.antrea-ci.rocks/view/antrea-for-pull-request/job/antrea-conformance-for-pull-request/610/console

Update Jenkins CI on savelogs and ns deletion

---

pkg/antctl/raw/supportbundle/command.go

When Node name or label filter is provided, collect only Agent bundles
but not Controller bundles.
Revised the supportbundle command descriptions and corrected a few
mistakes in the descriptions.

Revise support bundle command and descriptions

---

docs/feature-gates.md
docs/getting-started.md
pkg/features/antrea_features.go

Includes a quick description of each feature, links to appropriate
documentation, feature stage, etc.
Fixes #892

Add documentation for feature gates

---

test/e2e/framework.go
test/e2e/traceflow_test.go

Traceflow e2e is in test/e2e/traceflow_test.go
* intra and inter nodes traffic.
* NetworkPolicies to allow all egress traffic and deny ingress traffic with label.

Add Traceflow e2e test

---

test/e2e/traceflow_test.go

Currently, Traceflow e2e test may fail because NetworkPolicies are not realized in time.
So a polling is added to ensure NetworkPolicy realization.

Polling for NetworkPolicy to be realized in Traceflow e2e

---

ci/cluster-api/vsphere/templates/cluster.yaml
ci/jenkins/jobs/macros.yaml

* Update cluster.yaml
* Add log tracing for workload cluster creation
This is an attempt to move CI back to VMC.

Update VMC Jenkins CI

---

pkg/apiserver/certificate/cacert_controller.go

Avoid warnings about POD_NAMESPACE not set when they are irrelevant

---

pkg/agent/controller/traceflow/packetin.go
pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go
pkg/agent/openflow/pipeline.go

This PR replaced hardcoded OVS table IDs with shared constants

Replace hardcoded OVS table IDs with constants

---

README.md

It seems that a password is required now.

Update Zoom link for community meeting

---

pkg/agent/controller/traceflow/traceflow_controller.go
pkg/controller/traceflow/controller.go
pkg/ovs/openflow/ofctrl_packetout.go

Fixed #945.
* PacketOut IPHeader error
* Replace unused "oldObj" with "_"

[Traceflow] Fix PacketOut Encoding error

---

ci/jenkins/README.md
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml
ci/test-conformance-eks.sh
ci/test-conformance-gke.sh

- Add env variable into Jenkins commands which are otherwise unresolved
- Update GKE cluster version to the latest supported

Fix environmental issues in Jenkins

---

.github/workflows/update_ovs_image.yml
build/images/Dockerfile.build.ubuntu
build/images/Dockerfile.ubuntu
build/images/base/Dockerfile
build/images/base/build_and_push.sh

Use an Antrea base image instead of Ubuntu

---

ci/jenkins/README.md
ci/jenkins/jobs/projects.yaml

- Updated the links to cloud CI with the latest ones using scripts managed by Antrea
- Bumped up GKE cluster version

[CI] Minor updates for cloud CI

---

test/e2e/traceflow_test.go

* IP as destination, UDP, intra node
* IP as destination, ICMP, inter nodes

[Traceflow][e2e] Add more e2e tests

---

Makefile
build/images/scripts/install_cni_chaining
build/yamls/antrea-aks-node-init.yml
build/yamls/antrea-aks.yml
docs/aks-installation.md

Azure CNI operates in L2 (bridge) mode when no network policy
is specified. With a help of antrea node init, we toggle the
mode from bridge to transparent (L3).
Verified reboot and auto scale of nodes.

feat: Enable Antrea in AKS managed service

---

pkg/antctl/raw/supportbundle/command.go

Instead use existing constants in "pkg/apis".

Do not hardcode Antrea apiserver ports in antctl

---

docs/network-policy.md

Add documentation for Tiering of NetworkPolicy in Antrea.
Related-Issue: #917

Add documentation for Tiers

---

docs/network-policy.md

Add agent conf parameter to enable Tiers in docs and a table of content for easier navigation.

Add agent conf parameter to enable Tiers in docs

---

docs/windows.md

Replace the download link of Start.ps1 with release asset link.

[Windows] Update Start.ps1 download link in doc

---

docs/traceflow-guide.md
pkg/antctl/raw/traceflow/command.go
pkg/antctl/raw/traceflow/command_test.go

* command implementation
* traceflow guide doc
This is an improvement with @tnqn 's comments on PR #932

[Antctl] Improve implementation of antctl traceflow

---

docs/feature-gates.md
docs/network-flow-visibility.md

This PR will be merged after PR#825 and PR#836.

Documentation for Flow Exporter feature

---

docs/feature-gates.md

Update ClusterNetworkPolicy feature gate requirement and add link to Traceflow doc feature.

Update feature-gates doc to reflect latest changes

---

Makefile
hack/release/prepare-assets.sh

* add missing antrea-aks.yml
* add missing '--cloud EKS' parameter for antrea-eks.yml
Also remove unnecessary '--proxy' in Makefile (added by default for
noEncap and networkPolicyOnluy modes).

Update Antrea cloud manifest generation in prepare-assets.sh

---

ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml

Add daily validation job for elk flow collector manifest

Modified CI for elk flow collector validation

---

pkg/apiserver/registry/system/supportbundle/rest.go
pkg/support/dump.go

Collect heap pprof data in support bundle to help triage memory-related issues.

Collect heap pprof data in supportbundle.

---

pkg/agent/controller/networkpolicy/priority.go
pkg/agent/controller/networkpolicy/priority_test.go
pkg/agent/controller/networkpolicy/reconciler.go

Revert priority updates if flow realization fails

---

pkg/ovs/ovsconfig/ovs_client.go
test/integration/ovs/ovs_client_test.go

In the Open vSwitch database, ofport value -1 means that the interface
could not be created due to an error. GetOFPort should verify whether
the ofport is valid and return an error if not, otherwise its consumers
would use the invalid ofport, leading to unexpected behaviors.
For #1113

Verify the ofport value in GetOFPort

---

.github/workflows/update_ovs_image.yml
build/images/Dockerfile.build.ubuntu
build/images/Dockerfile.ubuntu
build/images/base/Dockerfile
build/images/base/build_and_push.sh
build/images/ovs/Dockerfile
build/images/ovs/README.md
build/images/ovs/apply-patches.sh
build/images/ovs/build_and_push.sh
build/images/test/Dockerfile
ci/jenkins/README.md
hack/windows/Install-OVS.ps1

* Upgrade OVS dockerfile to 2.14.0
* Reorganize apply-patches.sh

Upgrade OVS to 2.14.0

---

pkg/agent/proxy/proxier.go

Reading the code, it seems that we never call syncProxyRules
directly. Instead we always invoke Run on the BoundedFrequencyRunner
object. But my understanding is that the BoundedFrequencyRunner will
serialize all the calls ("All runs will be async to the caller of
BoundedFrequencyRunner.Run, but multiple runs are serialized"). Given
that, and the fact that the data structures we are protecting are always
accessed through syncProxyRules, it seems that the mutex is not
necessary.
The change trackers (endpointsChangesTracker, servicesChangesTracker)
protect their own state using a mutex.

Remove unnecessary mutex in Antrea proxier code

---

.github/workflows/go.yml
.github/workflows/integration.yml
.gitignore
Makefile
codecov.yaml

Add code coverage reports for unit tests and integration tests.
Part of #1114.

Add code coverage report

---

docs/network-policy.md

Update old feature gate name for Antrea policies.

Update feature gate name in docs

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf
docs/feature-gates.md
docs/traceflow-guide.md

* UI now supports a Service as the destination
* In order to use Service as the destination, AntreaProxy should be
enabled

Update user guide for Traceflow

---

ci/jenkins/test-vmc.sh

* Append antrea-prometheus.yml to antrea.yml.
* Don't apply antrea-prometheus.yml before run e2e test.
Improves: #1218

[e2e] antrea-prometheus.yml in test-vmc.sh

---

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go

Add testing for networkpolicy metrics at agent in a unit test
- antrea_agent_networkpolicy_count
- antrea_agent_egress_networkpolicy_rule_count
- antrea_agent_ingress_networkpolicy_rule_count
A new unit test is added into newtorkpolicy_controller_test.
Fixes #799

Add testing for networkpolicy metrics at agent in a unit test

---

README.md

This is an attempt at refreshing the out-of-date features section in the
README. Instead of focusing on technical details, we want to provide
relevant information for someone looking for a CNI to use in their
clusters.
Fixes #1058

Update features section in README

---

.github/workflows/go.yml
.github/workflows/integration.yml
.github/workflows/kind.yml
Makefile
build/images/Dockerfile.build.coverage
build/yamls/patches/coverage/startAgentCov.yml
build/yamls/patches/coverage/startControllerCov.yml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml
ci/jenkins/test-vmc.sh
ci/kind/test-e2e-kind.sh
cmd/antrea-agent/bincover_run_main_test.go
cmd/antrea-controller/bincover_run_main_test.go
go.mod
go.sum
hack/generate-manifest.sh
plugins/octant/go.sum
test/e2e/basic_test.go
test/e2e/coverage/agent-arg-file
test/e2e/coverage/controller-arg-file
test/e2e/fixtures.go
test/e2e/framework.go
test/e2e/main_test.go

Add code coverage reports for e2e tests.
Part of #1114.

Add e2e code coverage

---

test/e2e/basic_test.go

Use "ip -6 route" for IPv6 network.

[IPv6] Fix TestReconcileGatewayRoutesOnStartup failure

---

test/e2e/framework.go

In some e2e tests that need to restart antrea-agent Pods, restarting
antrea-agent Pods is required and deleting Pods is used to trigger it.
However, DaemonSet.Status.NumberAvailable counts Pods even if they are
terminating. So waitForAntreaDaemonSetPods could succeed without waiting
for Pods being recreated if the process caught the termination signal
and delayed the termination.
This patch fixes it by making sure all antrea-agent Pods are not
terminating in waitForAntreaDaemonSetPods.
Fixes #1309

Ensure antrea-agent Pods not terminating in waitForAntreaDaemonSetPods

---

pkg/agent/agent.go

Use Node's internal address to decide if extra IPv6 overhead is needed.

[IPv6] Fix MTU config

---

docs/octant-plugin-installation.md

**Issue**
https://github.com/vmware-tanzu/antrea/issues/1333
Fixes #1333

Fixes #1333: Broken link in octant-plugin-installation.md doc

---

ci/jenkins/README.md
ci/test-conformance-aks.sh

In addition, updates GKE cluster version to latest used.

Fix version unsupported issue in AKS Jenkins job

---

docs/prometheus-integration.md
hack/make-metrics-doc.sh

Adds line breaks between metric rows to improve the readability of the
metric list.

Add line breaks in metrics list for readability

---

pkg/agent/proxy/proxier.go

When there is a Service/Endpoint update, do Endpoint
removal in the end of the procedure to avoid packets
circulation.
Fixes #1379.

Reorder Service&Endpoint handling order

---

cmd/antrea-agent/agent.go

since NewAntreaClientProvider never return error

remove unnecessary log

---

pkg/agent/controller/traceflow/traceflow_controller.go

TCP flags should be 2 when svc as dest in Traceflow

---

ci/jenkins/test-vmc.sh

Currently, [antrea-workload-cluster-for-gc](https://jenkins.antrea-ci.rocks/job/antrea-workload-cluster-for-gc/) (garbage collection) job of Antrea CI cleans clusters with age more than 1 hour. However, jobs regarding the whole-conformance test, including the upcoming matrix test job, usually need to run for more than 1 hour to complete. In this case, the garbage collection job deletes namespaces in which tests are still running. This patch extends the time limits for those jobs and thus fixes this bug.

Fix antrea-ci garbage cleanup too frequently bug

---

docs/contributors/github-labels.md
docs/contributors/issue-management.md

For routine maintenance tasks that need to be performed for the project,
e.g. upgrading some software dependency version. I expect most of these
tasks will have to do with infra & test infra.

Add kind/task Github label

---

test/e2e/fixtures.go
test/e2e/traceflow_test.go

Enable intra-Node e2e test for kind
Test case enhancement

Enhance Traceflow e2e test

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf
cmd/antrea-agent/config.go

Fix typo in antrea-agent configuration comments

---

build/images/ipfix-collector/Dockerfile
build/images/ipfix-collector/README.md
test/e2e/fixtures.go

As antrea/ipfix-collector:10282020.1

Provide IPv6 version of ipfix-collector Docker image

---

pkg/ovs/ovsconfig/default_windows.go
pkg/ovs/ovsconfig/ovs_client.go
pkg/ovs/ovsconfig/ovs_client_test.go

makes the type assertion explicit and adds a unit test for ovs version checks

OVS Error guard windows

---

pkg/ovs/ovsctl/ofctl.go

Show stderr when failing to set "noflood" config on port

---

docs/api.md
hack/.notableofcontents

In particular, include information about API deprecation and removal.
Closes #1404

Document Antrea API

---

site/docs/master/README.md
site/prepare-master-docs.sh

Not processed correctly because of the `<p>` HTML tag.

Fix image in README

---

docs/design/architecture.md
docs/design/ovs-pipeline.md
docs/design/policy-only.md
docs/design/windows-design.md
docs/kind.md

* fix some issues discovered while working on the website (incorrect
links in OVS pipeline documentation)
* fix some Markdown formatting to simplify generation of the website

Small documentation fixes

---

README.md

Preserve same time as DST for countries which have moved
out of DST.

Move community meeting to 5AM UTC

---

go.mod
go.sum
plugins/octant/go.mod
plugins/octant/go.sum

In ofnet wenyingd/ofnet@6fd225d8c8d1e2b7ae48e0ec852609cd92961a42, we fixed issue #1486.

Bump up ofnet to 6fd225d8c8d1

---

test/e2e/traceflow_test.go

After antctl supported Antrea-native policies, the command "get
networkpolicy" by the original NetworkPolicy name could return multiple
resources and no longer returns 404 for not found case. Therefore, the
util function waitForNetworkpolicyRealized should check if the stdout
contains the queried networkpolicy instead of relying on the exit code.
Fixes #1454

Fix flaky e2e test TestTraceflowIntraNode

---

pkg/agent/controller/noderoute/node_route_controller_test.go

* Improve comments in node_route_controller_test

[IPv6] Improve comment

---

test/e2e/basic_test.go

iproute2 is already available in the Antrea Docker image, so instead of
running ip directly on the Nodes over SSH, we can exec into the Antrea
Agent Pod (hostNetwork Pod) running on the Node.
Fixes #1514

Remove ip tools dependency for Nodes in e2e tests

---

test/e2e/antreapolicy_test.go
test/e2e/k8s_util.go
test/e2e/utils/anpspecbuilder.go
test/e2e/utils/cnpspecbuilder.go

Add e2e tests for validation of Antrea-native policies and Tiers

---

ci/jenkins/test-vmc.sh
ci/kind/test-e2e-kind.sh

* base-ubuntu:2.14.0 should be pulled instead of antrea-ubuntu:latest
* use ipfix-collector:latest in kind

[CI] Fix image in test-vmc.sh & ipfix version in Kind

---

docs/windows.md

Correct Windows pause image name shown in doc

[Windows] Correct Windows pause image name shown in doc

---

README.md

Fixes #989
I believe we now meet all the criteria. Feel free to double check my answers: https://bestpractices.coreinfrastructure.org/en/projects/4173

Display CII best practice badge in README

---

docs/assets/ovs-pipeline.svg
docs/design/ovs-pipeline.md

The flow changes are made in PR #1594.

Update OVS pipeline doc for the L2 forwarding flow changes

---

test/e2e/networkpolicy_test.go

Due to netdev datapath bug, sometimes datapath flows are not flushed after new openflows that change the actions are installed, causing client1 can still connect servers after creating a policy that disallows it. 
As a workaround, the test waits for 10 seconds so that the datapath flows will expire.
Fixes #1608

Fix flaky upgrade e2e test

---

ci/jenkins/test.sh

conformance skip regex may not work without ""

[CI] Fix Windows conformance test

---

test/e2e/fixtures.go
test/e2e/flowexporter_test.go

[Flow Exporter] Improve e2e tests

---

docs/antctl.md

Add descriptions of `antctl get netpol -T` and `antctl get netpol -S` to antctl.md.

Update antctl doc

---

build/yamls/flow-aggregator/patches/kustomization.configMap.tpl.yml
cmd/antrea-agent/options.go
hack/generate-manifest-flow-aggregator.sh
test/e2e/infra/vagrant/push_antrea.sh

Added and modified scripts to deploy flow aggregator and antrea by taking external flow collector as input.
In addition, we resolved a bug as part of this PR, when taking custom flowPollInterval value.

[Flow-aggregator] Automation for flow aggregator deployment

---

ci/jenkins/jobs/job-templates.yaml
ci/jenkins/jobs/projects.yaml
ci/jenkins/test-vmc.sh

* Let everyone to trigger builds with trigger phrase.
* Switch VMC Network after a few clusters are created. It is possible VMC runs out of IPs on a network. So it is better to switch between networks to avoid IP shortage.

[CI] Improve VMC Jenkins CI

---

CHANGELOG.md

Forgot to port this change to master earlier.

Update CHANGELOG for v0.11.1 release

---

docs/antrea-network-policy.md

Issue was fixed and therefore currently there are no known issues.

Remove known issue note from NetworkPolicy doc

---

CONTRIBUTING.md

Document our commitment to using inclusive naming in Antrea

---

pkg/agent/apiserver/handlers/ovstracing/handler.go
pkg/agent/apiserver/handlers/ovstracing/handler_test.go
pkg/agent/flowexporter/connections/conntrack_ovs.go
pkg/agent/openflow/client.go
pkg/agent/openflow/network_policy.go
pkg/agent/openflow/pipeline.go
pkg/ovs/openflow/ofctrl_action.go

Fixes #1384
See report at https://lgtm.com/projects/g/vmware-tanzu/antrea/alerts/?mode=list
After merging this, I will enable the lgtm.com status check for automated PR review

Address lgtm.com alerts based on CodeQL analysis

---

pkg/agent/agent.go

A rare case has been found that the "flow-restore-wait" config was still
true even though the delete call below was considered success. At the
moment we don't know if it's a race condition caused by "ovs-vsctl set
--no-wait" or a problem with OVSDB golang lib or OVSDB itself. To work
around it, we check if the config is true before deleting it and if it
is false after deleting it, and we will log warnings and retry a few
times if anything unexpected happens.
For #1600

Check the flow-restore-wait config and retry deleting it

---

pkg/agent/agent_windows.go
pkg/agent/util/net_windows.go

[Windows] Check interface operation results before return

---

ci/jenkins/mellanox/README.md
ci/jenkins/mellanox/common/clean_common.sh
ci/jenkins/mellanox/common/common_functions.sh
ci/jenkins/mellanox/common/run_ci_scripts.sh
ci/jenkins/mellanox/deploy/kubelet/kubelet.service
ci/jenkins/mellanox/deploy/kubelet/kubelet.service.d/10-kubeadm.conf
ci/jenkins/mellanox/jobs/00-functions.yaml
ci/jenkins/mellanox/jobs/antrea_trigger_ci.yaml
ci/jenkins/mellanox/scripts/start_ci.sh
ci/jenkins/mellanox/scripts/stop_ci.sh
ci/jenkins/mellanox/scripts/test.sh
ci/jenkins/mellanox/switchdev_setup.sh

Host the Mellanox CI scripts on the antrea project. The Mellanox
CI tests the hw-offload capabilities of the antrea project on a
setup with Mellanox NICs. It performs a basic E2E test between pods
on single node setup.

Add Mellanox CI scripts to the project

---

.github/workflows/build.yml
.github/workflows/go.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
SECURITY.md
ci/gh-actions/has-changes/README.md
ci/jenkins/mellanox/README.md
docs/aks-installation.md
docs/cookbooks/multus/README.md
docs/eks-installation.md
docs/getting-started.md
docs/gke-installation.md
docs/ipsec-tunnel.md
docs/network-flow-visibility.md
docs/versioning.md
docs/windows.md
hack/netpol/Makefile
hack/netpol/README.md

Remove all remaining references to the Antrea "master" branch

---

pkg/agent/openflow/pipeline.go
pkg/util/env/env.go
pkg/util/runtime/runtime.go
test/integration/agent/openflow_test.go

[Windows] Fix uplinkTable uninitialized when disable AntreaProxy

---

docs/antctl.md
docs/design/ovs-pipeline.md
docs/feature-gates.md
docs/octant-plugin-installation.md
docs/prometheus-integration.md
docs/troubleshooting.md
docs/windows.md
pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
pkg/agent/metrics/prometheus.go
test/integration/agent/cniserver_test.go

Capitalize K8s resource types and terms like "Windows".
Fix a few typos.

A few documentation fixes

---

pkg/antctl/raw/proxy/command.go
test/e2e/antctl_test.go

* Enabled TestAntctlProxy in IPv6 setup
* Added IPv6 proxy address: "::1"
* copyAntctlToNode() should run on Controller Pod rather than Agent one
* Polished proxy command implementation
* options.address is wrapped by "[]" if it is an IPv6 address
* Better formatting

[CI] Enable IPv6 TestAntctlProxy test and bug fix

---

pkg/agent/controller/networkpolicy/reconciler.go

In Antrea-native policy openflow rule installation, if there is a transient OVS connection issue and the installation fails, the priority should only be released if it is not shared by other Antrea-native policy rules that have already been installed on the Node. As of now the priority will be released and re-registered, which can lead to a different ofPriority compared to those already installed. This PR fixes this issue.

Fix unintended priority release when ovs rule install fails

---

test/e2e/antreapolicy_test.go

Cleanup netpol in testANPBasic after testcase execution

---

docs/feature-gates.md

Updating feature-gates.md for NodePortLocal with the requirements,
Service Annotation for Pod selection and Pod Annotation updated by Antrea Agent.

Antrea Feature Gates document update for NodePortLocal

---

docs/arm-support.md
docs/getting-started.md
hack/.notableofcontents

Document Antrea ARM support

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/agent-rbac.yml

Required for NPL controller to patch the Pods.
Also remove update permissions as they are no longer needed.
Co-authored-by: Antonin Bas <abas@vmware.com>

Add missing patch permissions for Pods

---

README.md
docs/troubleshooting.md

As suggested by Steven Wong at the 02/16/2021 Antrea Community meeting.

Add link to community information at the end of troubleshooting doc

---

docs/contributors/github-labels.md

Add new area labels for ops and Traceflow

---

pkg/agent/cniserver/interface_configuration_linux.go

In a v6-only cluster, every time a Pod is created, the following warning
is logged:
> Failed to find an IPv4 address, skipped sending Gratuitous ARP
We change the log level to Info.V(2), and we add a new warning if the
CNI result object does not include any IP address.

Reduce log level severity in advertiseContainerAddr when no v4 address

---

pkg/agent/openflow/client.go

Revise the flow cache key format for Services and Endpoints flows

---

test/e2e/antreapolicy_test.go
test/e2e/framework.go
test/e2e/framework_test.go
test/e2e/k8s_util.go
test/e2e/networkpolicy_test.go
test/e2e/nodeportlocal_test.go
test/e2e/security_test.go
test/e2e/tls_test.go

* Use formats like "NS/Pod" in antreapolicy_test
* Use regexp to replace field value in mutateAntreaConfigMap()
* Remove unnecessary parameters in functions

[CI] Refactor CI e2e

---

.github/workflows/netpol_cyclonus.yml
build/images/ethtool/Dockerfile
build/images/ethtool/README.md
build/images/ovs/README.md
build/images/perftool/Dockerfile
build/images/perftool/README.md

the base image version is inconsistent between Dockerfile and README
update all ubuntu 18.04 to ubuntu 20.04

update ubuntu 18.04 to ubuntu 20.04

---

ci/jenkins/test-vmc.sh

* Added -o UserKnownHostsFile=/dev/null to stop adding hosts into
.ssh/known_hosts due to ssh/scp operation. This avoids conflicts
when there are two ssh/scp operations at the same time, which may
results from two Jenkins builds.
* Use variables to reduce code redundancy about ssh/scp.
Fixed #1970

[CI] Use UserKnownHostsFile option in VMC Jenkins ssh/scp

---

test/e2e/infra/vagrant/push_antrea.sh

Improve support when additional K8s worker Nodes are created (not a
single one, which is the default). Instead of asking the user to set the
NUM_WORKERS environment variable to the correct value, we consider all
the hosts in the generated ssh-config file.

Improve push-antrea.sh script (Vagrant testbed)

---

build/yamls/antrea.yml
docs/antrea-network-policy.md
docs/api.md
docs/design/ovs-pipeline.md
docs/traceflow-guide.md
docs/troubleshooting.md

* Examples in existing documents are updated to use the new API.
* Include information about the API renaming and the procedure to
upgrade clients in the main api.md document.

Update documentation after API renaming

---

test/e2e/traceflow_test.go

Fix e2e issue introduced by https://github.com/vmware-tanzu/antrea/pull/2029#pullrequestreview-631984458

Fix Traceflow IPv6 e2e error

---

.github/workflows/kind.yml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf
build/yamls/base/conf/antrea-controller.conf
ci/kind/test-e2e-kind.sh
docs/antrea-network-policy.md
docs/feature-gates.md
hack/generate-manifest.sh
pkg/features/antrea_features.go

We graduate this Feature to Beta for the Antrea v1.0 release.
See #1725

Graduate AntreaPolicy Feature to Beta

---

test/e2e/traceflow_test.go

There seems to be an issue in the IPv6 testbed for inter-Node Pod-to-Pod
traffic when:
* traffic is v6 in v6
* the Pod-to-Pod traffic is non-TCP, i.e. this only seems to happen for
UDP and SCTP
* the Nodes are on 2 different ESX hosts, i.e. there is 2 levels of
Geneve encapsulation

Skip interNodeUDPDstIPTraceflowIPv6 temporarily

---

docs/feature-gates.md

Fix default and stage of AntreaProxy, AntreaPolicy and Traceflow in feature-gates.md
https://github.com/vmware-tanzu/antrea/releases/tag/v0.11.0

Fix default and stage of AntreaProxy, AntreaPolicy and Traceflow in feature-gates.md

---

docs/contributors/github-labels.md

* area/component/flow-aggregator
* area/flow-visibility
* area/flow-visibility/aggregation
* area/flow-visibility/elk
* area/flow-visibility/export
Fixes #2057

Add new Github labels for flow visualization

---

docs/kubernetes-installers.md
hack/.notableofcontents

* which installers have been tested and with which software versions
* how to use Antrea with these installers
The current list is not meant to be comprehensive by any means.
Fixes #2053

Add information about K8s installers

---

ADOPTERS.md

Worked on additional information in ADOPTERS.md

Add success stories and 'How to add yourself' to ADOPTERS.md

---

pkg/agent/cniserver/interface_configuration_windows.go
pkg/agent/util/net_windows.go
pkg/ovs/ovsconfig/ovs_client.go
pkg/ovs/ovsconfig/ovs_client_linux.go
pkg/ovs/ovsconfig/ovs_client_windows.go

Container MTU should be properly configured for better performance.
MTU cannot be configured with HNSEndpoint or API on Windows.
https://github.com/Microsoft/hcsshim/blob/4a468a6f7ae547974bc32911395c51fb1862b7df/internal/hns/hnsendpoint.go#L12

[Windows][Performance] Configure MTU in Windows container

---

README.md

Add a note to check calendar for localized meeting times.

Readme: Make meeting time clearer, invite to check calendar

---

ADOPTERS.md

- Added hint on max. line width and trailing spaces
- Removing Infrabuilder as Adopter, as we will rather list them as partner in future

Updating Adopters.md

---

ci/jenkins/README.md
ci/jenkins/test-vmc.sh
ci/jenkins/test.sh
test/e2e/antctl_test.go
test/e2e/antreapolicy_test.go
test/e2e/bandwidth_test.go
test/e2e/basic_test.go
test/e2e/batch_test.go
test/e2e/clustergroup_test.go
test/e2e/connectivity_test.go
test/e2e/fixtures.go
test/e2e/flowaggregator_test.go
test/e2e/framework.go
test/e2e/ipsec_test.go
test/e2e/legacyantreapolicy_test.go
test/e2e/legacyclustergroup_test.go
test/e2e/networkpolicy_test.go
test/e2e/nodeportlocal_test.go
test/e2e/prometheus_test.go
test/e2e/proxy_test.go
test/e2e/security_test.go
test/e2e/supportbundle_test.go
test/e2e/tls_test.go
test/e2e/traceflow_test.go
test/e2e/upgrade_test.go

* Enable TestPodConnectivitySameNode and TestPodConnectivityDifferentNodes
* Added windowsNodes, windowsNodeIdxes fields in ClusterInfo
* Involved at least a Windows Node when createBusyboxPodOnNode
* Refactored some e2e test code
* Removed unnecessary numWorkerNodes field
* Updated test.sh to support Windows e2e tests
* Updated CI doc
Related #2017

[CI][Windows] Support connectivity tests & enable e2e Jenkins jobs in Windows

---

CONTRIBUTING.md

Replace VMware CLA with DCO

---

README.md
hack/.md_links_config.json

Add FOSSA license scan report and status

---

ci/jenkins/test-vmc.sh

VMC Jenkins try to pull images from Dockerhub first then Harbor.
Harbor is not stable right now.

[CI] Support pulling images from Dockerhub

---

hack/windows/Helper.psm1

parameterize kubernetes download path

---

pkg/graphviz/traceflow.go

add captured packet info for live traffic as part of destination Node diagram.
sample screenshot:
1. pod to pod:
2. empty source to pod:

add live capturedpacket info to UI

---

hack/windows/Prepare-Node.ps1

Parameterize kubernetes download path (Prepare-Node.ps1)

---

docs/network-flow-visibility.md

Update network-flow-visibility doc by adding instructions on
1. how to deploy a stand-alone go-ipfix collector
2. how to pass the go-ipfix collector address to flow-aggregator config map

Add ipfix-collector deployment instructions to flow-visibility doc

---

ci/jenkins/test.sh
test/e2e/antreapolicy_test.go
test/e2e/legacyantreapolicy_test.go

[CI] Fix IPv6 e2e kubeconfig not found & simplify Jenkins log

---

site/_posts/2021-05-24-antrea-joins-cncf-sandbox-chinese.md

[Website] Add Chinese language blog post about Antrea joining CNCF

---

pkg/agent/openflow/pipeline.go
test/e2e/traceflow_test.go

Fix Traceflow issue on hairpin service

---

test/e2e/flowaggregator_test.go
test/e2e/framework.go

Currently, bandwith test is disabled in flow aggregator e2e test because it's flaky especially for intra-node flows. We found the root cause of it is the first and final records exported by flow exporter don't have desired `octectDeltaCount` because iperf traffic may not fill the entire export interval of the first and final records.
So in this commit, we check bandwidth using `octetDeltaCountFromSourceNode` for the records in the middle and calculate the average bandwidth using the `octetTotalCountFromSourceNode`, then compares with the iperf bandwidth. The difference should be lower than 15%.
Also I changed the iperf time to 12s and flow aggregator active timeout to 3.5s to make the tests more stable.
Sample output of updated bandwidth test:
```
=== RUN …
```

Fortify the bandwidth e2e test of flow aggregator

---

ci/jenkins/test-vmc.sh
ci/jenkins/test.sh

Use trap command to help clean up clusters when something goes wrong

[CI] Use trap in Jenkins jobs

---

ci/jenkins/test.sh

* docker prune more images (base-ubuntu, flow-aggregator)
We have left too many stale images in testbeds like:
```
projects.registry.vmware.com/antrea/flow-aggregator               v0.14.0-dev-638ee9dc   714d3fbfcacc        2 months ago        180MB
projects.registry.vmware.com/antrea/base-ubuntu                   <none>                 40ad33b03297        2 months ago        143MB
projects.registry.vmware.com/antrea/openvswitch                   <none>                 57f2639036a8        2 months ago        125MB
antrea/flow-aggregator                                            v0.14.0-dev-3761f8b5   8999e7864581        2 months ago        180MB
projects.registry.vmware.com/antrea/flow-aggregator               v0.14.0-dev-3761f8b5   8999e7864581        2 months ago        180MB …
```

[CI] Prune stale images in testbeds

---

pkg/agent/agent_windows.go
pkg/agent/util/net_windows.go

Otherwise it would fail with "The parameter is incorrect" which is not
useful for end users.
Fixes #2213 
Without the PR, the log was 
```
F0329 23:35:27.090421    3936 main.go:58] Error running agent: error initializing agent: failed during hnsCallRawResponse: hnsCall failed in Win32: The parameter is incorrect. (0x57)
```
With the PR, the log became:
```
E0607 09:57:45.645715    1808 agent_windows.go:65] Transparent HNSNetwork requires a physical adapter while the uplink interface "vEthernet (Ethernet0 2)" is virtual, please detach it from other HNSNetwork and try again
F0607 09:57:45.647765    1808 main.go:58] Error running agent: error initializing agent: uplink "vEthernet (Ethernet0 2)" is not a physical adapter
```

[Windows] Check if the uplink is virtual before creating HNSNetwork

---

pkg/agent/cniserver/interface_configuration_windows.go

Cherry pick of #2253 on release-0.13.
#2253: Fix the race condition in ifConfigurator

Automated cherry pick of #2253: Fix the race condition in ifConfigurator

---

ci/jenkins/test-vmc.sh
ci/jenkins/test.sh

[CI] Clean up stale files & folders under /tmp

---

ci/jenkins/ssh-config
ci/jenkins/test-vmc.sh
ci/jenkins/test.sh
test/e2e/framework.go
test/e2e/service_test.go

* Added an e2e test for Cluster IP access from host
* Supported RunCommandOnNode() from all nodes

[CI][e2e] Add test for ClusterIP Service access from host

---

test/e2e/antreapolicy_test.go

Instead of using a fixed sleep delay, we poll the policy status until it
is updated with: DesiredNodesRealized > 0 and CurrentNodesRealized ==
DesiredNodesRealized. Those tests have been failing a lot recently, and
I believe this was because the sleep is insufficient. This seems better
than arbitrarily increasing the sleep delay.
Fixes #2266

Wait for policies to be realized for ANP/ACNP stats e2e tests

---

Makefile
plugins/octant/cmd/antrea-octant-plugin/antrea_info.go
plugins/octant/cmd/antrea-octant-plugin/main.go
plugins/octant/cmd/antrea-octant-plugin/traceflow.go

Run golangci-lint for Octant plugin in CI

---

pkg/ovs/openflow/ofctrl_packetout.go

The function does not shift the last byte of data by 8 bits,
causing checksum to be wrongly computed if the data is 
in odd number of bytes.

Fix checksum computation error in ofctrl_packetout.go

---

pkg/util/k8s/client.go

Refactor restconfig client function

---

test/e2e/antreapolicy_test.go
test/e2e/k8s_util.go
test/e2e/legacyantreapolicy_test.go

Signed-off-by: Bin Liu <biliu@vmware.com>

GetPodByLabel may return nil pod, check if nil before using it

---

README.md

Change the changelog link in /README.md to CHANGELOG/README.md

---

test/e2e/antreapolicy_test.go

* Integrate Quan's feedback for waitForANPRealized / waitForACNPRealized
and change the conditions used to determine whether a policy is
realized
* Use these functions instead of a fixed-duration sleep in a couple more
places
* Use polling in the audit logging test to validate the contents of the
log file

Antrea NetworkPolicy e2e tests improvements

---

site/_redirects
site/golang/libOpenflow.html

[Website] Configure vanity imports for antrea-io/libOpenflow

---

hack/windows/Prepare-Node.ps1

Replace InstallOVS with NodeIP.
Signed-off-by: William Tu <u9012063@gmail.com>

[Windows] Fix typo.

---

test/e2e/basic_test.go
test/e2e/framework.go
test/e2e/nodeportlocal_test.go
test/e2e/proxy_test.go
test/e2e/service_test.go
test/e2e/traceflow_test.go

`createBusyboxPod` and `createNginxPod`

[CI][e2e] Remove unnecessary wrappers

---

ci/jenkins/test.sh

[CI] Power on VM after reverting to a snapshot

---

go.mod
go.sum
pkg/agent/agent_windows.go
pkg/agent/route/route_windows.go
pkg/agent/route/route_windows_test.go
pkg/agent/util/net_windows.go
pkg/agent/util/powershell/powershell_windows.go
pkg/agent/util/winfirewall/winfirewall.go
plugins/octant/go.sum
test/integration/agent/net_windows_test.go

* Use "os/exec" to run commands on Windows host
* Implemented NetRoute related methods to replace "github.com/rakelkar/gonetsh/netroute"
fixed: #2364

[Windows] RunCommand with os/exec

---

build/images/Dockerfile.build.windows
ci/jenkins/test.sh
test/e2e/basic_test.go
test/e2e/framework.go
test/e2e/upgrade_test.go

Check if HNSEndpoint is removed or not when a Pod is deleted.

[Windows] Improve e2e test case DeletePod to support Windows

---

ci/test-conformance-aks.sh

Skip NodePort related cases for AKS since as Nodes in AKS cluster seem not accessible from other Nodes
through public IPs by default. See https://github.com/antrea-io/antrea/issues/2409

Skip enabling aks-preview and nodeport E2E testcases

---

ci/jenkins/test.sh

[CI] Ensure antrea-test namespace is cleaned before next test

---

go.mod
go.sum
pkg/agent/agent_windows.go
pkg/agent/route/route_windows.go
pkg/agent/route/route_windows_test.go
pkg/agent/util/net_windows.go
pkg/agent/util/powershell/powershell_windows.go
pkg/agent/util/winfirewall/winfirewall.go
plugins/octant/go.sum
test/integration/agent/net_windows_test.go

Cherry pick of #2363 on release-1.1.
#2363: RunCommand with os/exec * Use "os/exec" to run

Automated cherry pick of #2363: RunCommand with os/exec * Use "os/exec" to run

---

hack/release/process-changelog.go

Fix typos in process-changelog release helper script

---

site/_posts/2021-07-14-gke-networking-with-antrea.md
site/_posts/2021-07-21-egress-snat-ip-for-kubernetes-workloads.md

[Website] Add Egress blog post by Vino Alex

---

pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go
pkg/agent/openflow/pipeline.go
pkg/ovs/openflow/ofctrl_flow.go
pkg/util/ip/ip.go

Cherry pick of #2479 on release-1.2.
#2479: Improve NetworkPolicy batch installation

Automated cherry pick of #2479: Improve NetworkPolicy batch installation

---

pkg/agent/openflow/client.go

Cherry pick of #2476 on release-1.2.
#2476: Install all Endpoint flows belong to a Service via single

Automated cherry pick of #2476: Install all Endpoint flows belong to a Service via single

---

docs/maintainers/updating-ovs-windows.md
hack/.notableofcontents

Document update of OVS windows binaries distributed by Antrea

---

hack/windows/Install-OVS.ps1

[Windows] Upgrade OVS version

---

.github/workflows/go.yml

merge some jobs in workflow files go.yml so we can have
less concurrent jobs for one PR to reduce github runner waiting time.
Part of #2014

merge jobs in go.yml

---

go.mod
go.sum
pkg/agent/controller/networkpolicy/packetin.go
pkg/agent/controller/networkpolicy/packetin_test.go
pkg/agent/controller/traceflow/packetin.go
pkg/agent/controller/traceflow/packetin_test.go
pkg/agent/controller/traceflow/traceflow_controller.go
pkg/agent/openflow/client.go
pkg/agent/openflow/client_test.go
pkg/agent/openflow/packetin.go
pkg/agent/openflow/pipeline.go
pkg/ovs/openflow/interfaces.go
pkg/ovs/openflow/ofctrl_action.go
pkg/ovs/openflow/ofctrl_bridge.go
pkg/ovs/openflow/ofctrl_builder.go
pkg/ovs/openflow/ofctrl_builder_test.go
pkg/ovs/openflow/ofctrl_flow.go
pkg/ovs/openflow/ofctrl_group.go
pkg/ovs/openflow/ofctrl_meter.go
pkg/ovs/openflow/ofctrl_packetin.go
pkg/ovs/openflow/ofctrl_packetin_test.go
pkg/ovs/openflow/ofctrl_packetout.go
pkg/ovs/openflow/ofctrl_packetout_test.go
pkg/ovs/openflow/testing/mock_openflow.go
plugins/octant/go.mod
plugins/octant/go.sum
test/integration/ovs/ofctrl_test.go

Switch to antrea.io forks for libOpenflow and ofnet

---

pkg/agent/nodeportlocal/npl_agent_test.go
pkg/agent/nodeportlocal/portcache/port_table.go
pkg/agent/nodeportlocal/rules/iptable_rule.go
pkg/agent/nodeportlocal/rules/rules.go
pkg/agent/nodeportlocal/rules/testing/mock_rules.go
pkg/agent/route/route_linux.go
pkg/agent/util/iptables/iptables.go

Cherry pick of #2469 on release-1.2.
#2469: Bug fix in adding iptable rules * bug fix in

Automated cherry pick of #2469: Bug fix in adding iptable rules * bug fix in

---

pkg/flowaggregator/flowaggregator.go

Cherry pick of #2546 on release-1.2.
#2546: Fix missing template when sending first record

Automated cherry pick of #2546: Fix missing template when sending first record

---

.github/workflows/build.yml
.github/workflows/go.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml
pkg/apiserver/handlers/featuregates/handler_test.go

The CI config should be reverted before feature branch merged to main.

[flexible-ipam] Enable CI pipeline on feature branch and fix e2e error

---

ci/jenkins/test.sh

* Collect kubelet and docker logs on Windows VMs
* Refactor code

[CI][Windows] Refactor log collection

---

pkg/agent/openflow/client.go
pkg/agent/openflow/pipeline.go

Cherry pick of #2579 on release-1.2.
#2579: Fix Reject loop issue

Automated cherry pick of #2579: Fix Reject loop issue

---

CONTRIBUTING.md

[CI] Add doc about trigger phrases

---

hack/windows/Install-OVS.ps1

[Windows] Upgrade Windows OVS version to 2.14.2

---

docs/design/ovs-pipeline.md

Fix description of egress flows in ovs-pipeline.md

---

pkg/agent/controller/networkpolicy/audit_logging.go
pkg/agent/controller/networkpolicy/audit_logging_test.go

To avoid test flakiness issues on slower machines.
Fixes #2674

Use virtual clock for TestDropPacketMultiDedupLog

---

ci/jenkins/test.sh

* Retry after reverting Windows VM fails
* Skip pulling snonobuoy images if e2e test
* Clean support bundle files in cleanup function

[CI] Update test.sh

---

test/e2e/egress_test.go

Fix TestEgress flaky failure in jenkins-ipv6-only-e2e
The test failure is affected by the same IPv6 address in
`testEgressClientIP` test case.
The deleting Pod process in `defer deletePodWrapper(t, data, tt.fakeServer)`
deleted the EgressIP which used by `testEgressNodeFailure` when concurrently
running.
It only happens to only-ipv6-e2e because IPv6 test uses the same IP for
multiple tests while IPv4 uses different IPs. It has enough time to delete
Pod between different test cases in dual-stack cluster e2e.
This patch fixes it by changing the IPv6 addresses used in different
testEgress cases.
Resolves #2718

Fix TestEgress flaky failure in ipv6-only-e2e-test

---

pkg/agent/openflow/pipeline_windows.go

Cherry pick of #2702 on release-1.1.
#2702: Bugfix: SNAT is not performed on the +est packets.

Automated cherry pick of #2702: Bugfix: SNAT is not performed on the +est packets.

---

pkg/agent/route/route_linux.go

Correct comments on node routes for different traffic modes

---

.github/workflows/kind.yml

Download all image artifacts together in kind jobs

---

test/e2e/egress_test.go

Cherry pick of #2723 on release-1.3.
#2723: Fix TestEgress flaky failure in jenkins-ipv6-only-e2e

Automated cherry pick of #2723: Fix TestEgress flaky failure in jenkins-ipv6-only-e2e

---

pkg/agent/config/traffic_encap_mode.go
pkg/agent/config/traffic_encap_mode_test.go

Unify TrafficEncapMode string and those in antrea.yml

---

build/images/codegen/README.md

Otherwise it would be hard to know what's the change from the tag names.
For #2780

Document information about uploaded codegen images

---

pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go

Cherry pick of #2730 on release-1.1.
#2730: Fix panic bug in Antrea Policy

Automated cherry pick of #2730: Fix panic bug in Antrea Policy

---

pkg/antctl/raw/supportbundle/command.go

Cherry pick of #2399 on release-1.2.
#2399: Support return partial results for supportbundle when

Automated cherry pick of #2399: Support return partial results for supportbundle when

---

build/yamls/antrea-windows.yml
build/yamls/windows/base/conf/antrea-agent.conf

Signed-off-by: lzhecheng <lzhecheng@vmware.com>

[Windows] Provide kubeAPIServerOverride option for Windows agent

---

docs/contributors/github-labels.md

Signed-off-by: abhiraut <rauta@vmware.com>

Add multi-cluster label to github labels

---

pkg/antctl/raw/supportbundle/command.go

Cherry pick of #2813 on release-1.2.
#2813: Reduce memory consumption of supportbundle command

Automated cherry pick of #2813: Reduce memory consumption of supportbundle command

---

ci/jenkins/test.sh
hack/windows/Helper.psm1

* Retry download in helper.psm1
* Skip SCTP for Windows Netpol failure

[CI] Prerequisite to fix Windows Netpol failure

---

ci/jenkins/test.sh

* Retry resync VM time until success.
After the Windows VM is reverted to a snapshot, its date is incorrect.
One "resync" is not enough to work, so we keep trying.
* Run Windows NetPol tests serially
Currently, there're some bugs in HCS lib or Windows syscall that leads
to failure when tests are in parallel. Will fix the issue later and avoid
blocking PR merging.

[CI] Fix Windows NetPol test failures

---

ci/jenkins/test.sh

Cherry pick of #2815 on release-1.3.
#2815: Fix Windows NetPol test failures * Retry resync VM time

Automated cherry pick of #2815: Fix Windows NetPol test failures * Retry resync VM time

---

ci/jenkins/test.sh
cmd/antrea-agent/options.go
hack/generate-manifest.sh
test/e2e/fixtures.go

[CI] Support flexible ipam e2e

---

CONTRIBUTING.md

[Doc] Trigger phrase for flexible ipam e2e

---

.github/AREA-OWNERS
docs/contributors/github-labels.md
docs/maintainers/antrea-docker-image.md
docs/maintainers/release.md
hack/.notableofcontents

Remove some outdated information, include more details, improve
formatting.

Update release documentation

---

docs/design/architecture.md
docs/design/ovs-pipeline.md
docs/design/windows-design.md
pkg/agent/agent_windows.go
pkg/agent/apiserver/apiserver.go
pkg/agent/cniserver/pod_configuration.go
pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go
pkg/agent/openflow/client.go
pkg/agent/openflow/pipeline.go
pkg/agent/openflow/pipeline_windows.go
pkg/agent/proxy/proxier.go
pkg/agent/route/route_windows.go
pkg/agent/util/net.go
pkg/agent/util/net_windows.go
test/e2e/service_test.go
test/integration/agent/cniserver_test.go
test/integration/agent/net_windows_test.go
test/integration/agent/openflow_test.go
test/integration/agent/route_test.go
test/integration/ovs/openflow_test_utils.go

* Some docs/comments changes
* Some refactoring which doesn't touch code function to make
code clean and output friendly

[Doc] Some docs/comments changes and refactoring

---

pkg/agent/flowexporter/connections/conntrack_connections_test.go

Re-structured `AddOrUpdateConn` test.
Fixes: #2806 

Improve Conntrack Connection unit test

---

.github/workflows/build.yml
.github/workflows/go.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml

[flexible-ipam] Remove feature branch from CI pipeline

---

pkg/controller/egress/controller.go
pkg/controller/egress/controller_test.go

Otherwise non-strict CIDR would always be considered new when it's
processed the second time because it's normalized when creating
IPAllocator.

Normalize CIDR before checking existence in IPAllocator

---

docs/feature-gates.md

[flexible-ipam] Update doc for requirements and data path change

---

docs/feature-gates.md

[flexible-ipam] Update doc for requirements and data path change (#2971)

---

.github/AREA-OWNERS

add new multi-cluster reviewer

---

docs/aks-installation.md
docs/getting-started.md

Add AKS Engine to AKS installation doc

---

hack/windows/Install-OVS.ps1

It includes AntreaProxy related fixes.
https://github.com/openvswitch/ovs-issues/issues/229
https://github.com/openvswitch/ovs-issues/issues/231

[Windows] Upgrade OVS version to 2.15.2

---

build/yamls/antrea-kind.yml
build/yamls/flow-aggregator.yml
ci/check-manifest.sh

antrea-kind.yml and flow-aggregator.yml are not up-to-date and they were
not checked by CI.

Fix deployment manifests that are not up-to-date

---

test/e2e/flowaggregator_test.go

Fix https://github.com/antrea-io/antrea/issues/2980
In this PR, we change to comparing flow export time with flow start time in flow record instead of the test start time of the host running tests. So that the time difference between host and k8s pod will not cause the test failure.
Example logs on AntreaIPAM testbed: http://10.176.27.169:8080/job/antrea-flexible-ipam-e2e-for-pull-request/144/consoleFull
```
=== RUN   TestFlowAggregator/IPv4/RemoteServiceAccess
flowaggregator_test.go:514: iperf started at 1636397717, end at 1636397729, output: Connecting to host 10.111.104.11, port 5201
flowaggregator_test.go:782: Flow passed condition with flowStartSeconds 1636397736, flowEndSeconds 1636397749, srcPort 40090 on host time 1636397731
flowaggregator_test.go:591: Data record with …
```

Fix TestFlowAggregator failure on AntreaIPAM testbed

---

hack/windows/Helper.psm1
hack/windows/Start.ps1

Owner: vmware-tanzu -> antrea-io

[Windows] Update Owner in scripts

---

pkg/agent/cniserver/ipam/antrea_ipam.go
pkg/agent/cniserver/ipam/antrea_ipam_controller.go
pkg/agent/cniserver/ipam/antrea_ipam_test.go
pkg/ipam/poolallocator/allocator.go

Fix typos and formatting

---

pkg/controller/traceflow/controller_test.go

[traceflow] Fix flaky unit test failure

---

pkg/agent/flowexporter/connections/conntrack_connections.go
pkg/agent/flowexporter/connections/conntrack_linux_test.go
pkg/agent/openflow/fields.go
pkg/ovs/openflow/ofctrl_builder.go
pkg/ovs/openflow/ofctrl_flow.go
pkg/ovs/openflow/ofctrl_nxfields.go
test/integration/agent/openflow_test.go
test/integration/ovs/ofctrl_test.go

Use CT_MARK by bit rather than entire mark

---

test/integration/agent/openflow_test.go
test/integration/ovs/ofctrl_test.go
test/integration/ovs/openflow_test_utils.go

Dump OpenFlow entries from OVS with parameter "--names", and use table
name in the integration test cases.
Fixes #3016 

Use table name in OpenFlow integration test

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea-kind.yml
build/yamls/antrea.yml
build/yamls/base/crds.yml
docs/antrea-network-policy.md
pkg/agent/controller/networkpolicy/packetin.go
pkg/agent/openflow/fields.go
pkg/agent/openflow/network_policy.go
pkg/agent/openflow/pipeline.go
pkg/apis/crd/v1alpha1/types.go
pkg/controller/networkpolicy/validate.go
test/e2e/antreapolicy_test.go

Add Pass action for Antrea-native policies

---

.github/workflows/build.yml
.github/workflows/build_tag.yml
Makefile
build/images/Dockerfile.build.ubuntu
build/images/Dockerfile.simulator.build.ubuntu
build/images/Dockerfile.ubuntu
multicluster/Makefile
multicluster/build/Dockerfile.build

Add multicluster image in registry

---

CONTRIBUTING.md
ci/jenkins/jobs/projects.yaml
ci/jenkins/test-vmc.sh
docs/design/policy-only.md
multicluster/Makefile
multicluster/build/images/test/Dockerfile
multicluster/build/images/test/test-integration
multicluster/controllers/multicluster/resourceexport_controller.go
multicluster/controllers/multicluster/resourceexport_controller_test.go
multicluster/controllers/multicluster/serviceexport_controller.go
multicluster/hack/mc-integration-test.sh
multicluster/hack/verify-tools.sh
multicluster/test/integration/README.md
multicluster/test/integration/cluster-admin.yml
multicluster/test/integration/resourceexport_controller_test.go
multicluster/test/integration/resourceimport_controller_test.go
multicluster/test/integration/serviceexport_controller_test.go
multicluster/test/integration/stale_controller_test.go
multicluster/test/integration/suite_test.go
multicluster/test/integration/test_data.go

1. add integration initial scripts
2. integration codes for resource controllers
3. add integration test in docker and howto doc
Co-authored-by: Lan Luo <luola@vmware.com>
Co-authored-by: zbangqi <zbangqi@vmware.com>
Co-authored-by: Aravinda Kidambi <akidambi@vmware.com>

Multicluster Integration test

---

ci/cluster-api/vsphere/templates/cluster.yaml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml
ci/jenkins/test-vmc.sh
ci/run-k8s-e2e-tests.sh

* Migrate VMC jenkins testbed to private VC
* Upgrade clusterctl on private VC
* Update cluster.yaml and test-vmc.sh
Signed-off-by: Zhengsheng Zhou <zhengshengz@vmware.com>
Co-authored-by: Zhengsheng Zhou <zhengshengz@vmware.com>

[CI] Migrate VMC jenkins testbed to private VC

---

docs/antrea-ipam.md
docs/feature-gates.md

[flexible-ipam] Update doc for Antrea 1.5

---

test/e2e/README.md

Add documents and scripts on how to run e2e tests for Antrea when you already have a K8s cluster on which Antrea has been pushed.
Resolve #2250
Signed-off-by: Xiao Zhang xzhang2@vmware.com

Add documents to describe how to run e2e tests on an existing K8s cluster

---

CONTRIBUTING.md
ci/jenkins/README.md
ci/jenkins/test.sh
hack/generate-manifest.sh

Fixes #3073 
Co-authored-by: Zhecheng Li <lzhecheng@vmware.com>

[CI][Multicast] Support multicast e2e test 

---

pkg/agent/interfacestore/interface_cache.go

k8s.io/client-go/tools/cache.Indexer is thread safe and so we need not
another mutex for synchronization.

Remove mutex in interfaceCache

---

CONTRIBUTING.md
docs/contributors/docker-desktop-alternatives.md
hack/.notableofcontents

Document Docker Desktop alternatives for contributors

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea-kind.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf

Add SecondaryNetwork feature gate to Antrea manifests

---

test/e2e/framework.go

Most of flaky e2e tests failed when waiting for IP for test Pod. Logging
the Pod status makes it easier to find out the reason.

Log Pod status when waiting for Pod condition fails

---

ci/cluster-api/vsphere/templates/cluster.yaml
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects.yaml
ci/jenkins/test-vmc.sh
ci/run-k8s-e2e-tests.sh

Cherry pick of #3176 on release-1.2.
#3176: Migrate VMC jenkins testbed to private VC

Automated cherry pick of #3176: Migrate VMC jenkins testbed to private VC

---

pkg/agent/controller/noderoute/node_route_controller.go
pkg/agent/route/route_linux.go

Found some log and comment typos during PoC, fix them in this separate PR.

Fix typo in logs

---

.github/workflows/build.yml
.github/workflows/go.yml
docs/multicluster/getting-started.md

The core of multicluster is in main branch now, so no need to keep
the feature branch, we will submit new PR to main in the future
directly.

Update workflows for MC

---

pkg/agent/controller/serviceexternalip/controller.go

It's possible that some Endpoints don't have Service. For example,
kube-scheduler and kube-controller-manager may use Endpoints for leader
election.
Fixes #3255

Do not log error when Service for Endpoints is not found

---

CHANGELOG/CHANGELOG-1.5.md
CHANGELOG/README.md

Fix typo in CHANGELOG-1.5 and add a link for it

---

cmd/antrea-agent/agent.go
pkg/agent/nodeportlocal/k8s/npl_controller.go
pkg/agent/nodeportlocal/npl_agent_init.go
pkg/agent/nodeportlocal/npl_agent_test.go
pkg/agent/secondarynetwork/podwatch/controller.go

Change secondary network Pod controller to use the shared
localPodInfomer.

Update NPL and Secondary Network controllers initialization code

---

pkg/controller/stats/aggregator_test.go

Before this fix it was possible for the Run method to start processing
summaries before all ADD events had been processed by the registered
event handlers. When that happened, the summary was discarded by
doCollect. The reason is that there is no guarantee that all event
handlers have completed by the time the cache reports that it has
synced.
Another issue was that len(a.dataCh) being 0 is not a good enough signal
to detect that summaries have been processed. The Run method may still
be executing doCollect for the last summary. To avoid this issue, we
close stopCh and wait for Run to return.
Fixes #3300

Fix race condition in TestAggregatorCollectListGet unit test

---

test/e2e/infra/vagrant/playbook/roles/common/templates/containerd.conf.j2
test/e2e/infra/vagrant/push_antrea.sh

Support running ctr as vagrant user in vagrant-based test cluster.

---

test/e2e/flowaggregator_test.go

In this commit, we fixed some random failure cases of the FlowAggregator e2e test, which are previously raised by Jianjun in the email thread.
One fix is for the ToExternalFlows test, the reason this test fails randomly is that `wget` is used instead of `iperf -t 12` to generate traffic, so 6 seconds of waiting time is sometimes not enough because the first record theoretically arrives after 5.5 seconds `(exporterActiveFlowExportTimeout+aggregatorActiveFlowRecordTimeout)`. So we changed to it 9 seconds (5.5s plus one more `aggregatorActiveFlowRecordTimeout`) for waiting for flow records received on the IPFIX collector.
Another fix is adding `flowEndReason==3` in the condition of receiving the last flow record. We found in a low possibility, the `flowEndSeconds - flowStartSeconds` of the …

Fix FlowAggregator e2e test random failures

---

test/integration/ovs/ofctrl_test.go
test/integration/ovs/openflow_test_utils.go

The single flow/group add/modify/delete methods are asynchronous. It
may not take effect immediately after the methods return. The
integration test should take it into consideration and check the
operations eventually take effect.
Fixes #3213

Integration test should check OpenFlow operations eventually take effect

---

multicluster/controllers/multicluster/resourceexport_controller.go

Since there will be more different kinds of ResourceExport to handle, it will be better to have separate files for different kinds to avoid code change in existing controller and make the processing logic more clear.

Limit resource kinds in ResourceExport controller

---

.github/workflows/build.yml
.github/workflows/build_tag.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml
Makefile
build/images/Dockerfile.build.coverage
build/images/Dockerfile.build.ubi
build/images/base/Dockerfile.ubi
build/images/base/build.sh
build/images/flow-aggregator/Dockerfile
build/images/flow-aggregator/Dockerfile.coverage
build/images/ovs/CentOS.repo
build/images/ovs/Dockerfile.ubi
build/images/ovs/build.sh
ci/jenkins/test-mc.sh
ci/jenkins/test-vmc.sh
ci/jenkins/test.sh
hack/build-antrea-linux-all.sh

Add the required code to build an Antrea image based on Red Hat UBI
(Universal Base Image), which is in used by Red Hat platforms.
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>

Support antrea-agent UBI8 based image

---

.github/workflows/benchmark.yml
.github/workflows/build.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml
ci/gh-actions/has-changes/README.md

Move has-changes Github Action to its own repo

---

docs/antrea-ipam.md

Update Antrea IPAM documentation for enableBridgingMode parameter

---

test/integration/ovs/ofctrl_test.go
test/integration/ovs/openflow_test_utils.go

Cherry pick of #3357 on release-1.5.
#3357: Integration test should check OpenFlow operations eventually

Automated cherry pick of #3357: Integration test should check OpenFlow operations eventually

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea-kind.yml
build/yamls/antrea.yml
build/yamls/base/agent-rbac.yml
build/yamls/base/controller-rbac.yml
pkg/agent/agent.go
pkg/agent/nodeportlocal/k8s/annotations.go
pkg/agent/wireguard/client_linux.go

status update/patch permission can be used to update annotations.

Reduce permission of antrea service accounts

---

.github/workflows/build_tag.yml
Makefile
ci/jenkins/test-mc.sh
docs/multicluster/getting-started.md
multicluster/Makefile
multicluster/build/images/Dockerfile
multicluster/build/images/Dockerfile.build

Fix MC release build issue and remove duplicated Dockerfile
to keep one way to build MC image.

Fix MC release build issue

---

.github/workflows/go.yml

Skip Go build if there are only doc changes

---

build/images/Dockerfile.build.windows
hack/windows/Install-DevTools.ps1

[CI] Update 7zip download link

---

.github/workflows/build_tag.yml
Makefile
ci/jenkins/test-mc.sh
docs/multicluster/getting-started.md
multicluster/Makefile
multicluster/build/images/Dockerfile
multicluster/build/images/Dockerfile.build

Cherry pick of #3425 on release-1.5.
#3425: Fix MC release build issue

Automated cherry pick of #3425: Fix MC release build issue

---

.github/workflows/build.yml
.github/workflows/go.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml

Use version 2 of antrea-io/has-changes Github Action

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/conf/antrea-agent.conf
build/yamls/base/conf/antrea-controller.conf
cmd/antrea-agent/agent.go
docs/egress.md
docs/feature-gates.md
pkg/agent/openflow/pipeline.go
pkg/apiserver/handlers/featuregates/handler_test.go
pkg/features/antrea_features.go
test/e2e/egress_test.go

Egress will be graduated to Beta and enabled by default starting with
v1.6.

Graduate Egress feature from Alpha to Beta

---

multicluster/controllers/multicluster/stale_controller.go
multicluster/controllers/multicluster/stale_controller_test.go

The kind in ResourceImport for Service is ServiceImport,
so fix the kind and the unit test.

Fix stale service issue

---

CHANGELOG/CHANGELOG-1.6.md

Declare Beta support for proxyAll

---

.github/workflows/build.yml
.github/workflows/go.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/kind_upgrade.yml

Add feature label to branch filter.
Fixes #3551

Support kind and go CI jobs on feature branch

---

pkg/agent/route/route_linux.go
test/e2e/basic_test.go

Automated cherry pick of #3465: Remove stale ClusterIP routes after Antrea restart

---

.github/workflows/go.yml

Check CHANGELOGs for broken links on release branches

---

hack/release/prepare-changelog.sh

Add a script to draft changelog for release based on PR history

---

docs/cookbooks/multus/README.md

Remove dead link from Multus cookbook

---

test/e2e/framework.go

String search is unreliable, for example some YAML strings may be quoted
and others not. Instead we parse the config before accessing fields,
like we do for config mutation functions.

Do not use string search in e2e tests to check config params

---

pkg/agent/controller/networkpolicy/audit_logging_test.go

Use virtual clock for TestDropPacketDedupLog

---

pkg/agent/controller/networkpolicy/reject.go
test/e2e/antreapolicy_test.go

Cherry pick of #3569 on release-1.5.
#3569: Fix reject loop issue and add error handling

Automated cherry pick of #3569: Fix reject loop issue and add error handling

---

test/e2e/framework.go

Fix e2e test failures when coverage file is not available yet
Sometimes it seems that the coverage file is not available right away
after sending the SIGINT signal to the process. To avoid failing in this
case, we add a retry mechanism.
Fixes #3605

Fix e2e test failures when coverage file is not available yet

---

go.mod
go.sum
plugins/octant/go.sum

Bump antrea.io/ofnet from v0.5.5 to v0.5.7

---

.github/workflows/go.yml
.github/workflows/verify_docs.yml

1. Added a cron job verify to run a full check on a daily basis.
2. Added a check-modified-files-only: yes to the go.yml
Fixes #3631 

Enhance markdown-link-check

---

pkg/agent/memberlist/cluster_test.go

The current wait condition used to determine whether an external IP has
been processed is not accurate, and this can lead to failures on slower
machine. Instead, we wrap calls to `ShouldSelectIP` inside a
`wait.Poll`, and wait for the function to return the expected result,
with the test failing in case of a timeout. We keep using `wait.Poll`
(instead of `wait.PollImmediate`) with a pretty long initial sleep
(100ms), as it is useful for "negative tests", which expect
`ShouldSelectIP` to return an error.
Fixes #3657

Improve robustness of memberlist cluster unit tests

---

CONTRIBUTING.md
Makefile
hack/git_client_side_hooks/pre-commit

Adding pre-commit hook

---

docs/windows.md

Update Windows documentation

---

build/charts/antrea/templates/agent/daemonset.yaml

s/.Values.hwOffload./.Values.ovs.hwOffload
Fixes #3705

Fix Helm chart template for antrea-agent DaemonSet

---

docs/security.md

Cherry pick of #3694 on release-1.6.
#3694: Document some of the Antrea Agent RBAC permissions

Automated cherry pick of #3694: Document some of the Antrea Agent RBAC permissions

---

build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
build/yamls/base/agent-rbac.yml
build/yamls/base/antctl.yml
cmd/antrea-agent/agent.go
pkg/agent/apiserver/apiserver.go
pkg/agent/apiserver/handlers/serviceexternalip/handler.go
pkg/agent/controller/serviceexternalip/controller.go
pkg/agent/controller/serviceexternalip/controller_test.go
pkg/antctl/antctl.go
pkg/querier/querier.go
test/e2e/antctl_test.go
test/e2e/service_externalip_test.go

Cherry pick of #3691 on release-1.6.
#3691: Reduce permission of antrea-agent service account

Automated cherry pick of #3691: Reduce permission of antrea-agent service account

---

hack/update-codegen.sh

Add GOPROXY support for code generation

---

ci/jenkins/test.sh

* Add agnhost:2.29 image to harbor on windows
* Fix sed error in antrea.yml
* Fix potential time synchronization delay on windows
* Adjust power on waiting time

Add agnhost harbor image to avoid transient error

---

test/e2e/k8s_util.go

[e2e] Fix ACNPICMPSupport error on IPv6 env

---

test/e2e/README.md

Add known issues section to Vagrant documentation

---

Makefile
build/images/Dockerfile.build.windows
ci/jenkins/test.sh

Compile antctl together with Agent bits on Windows

---

pkg/agent/openflow/pipeline_test.go

Fix unit test in pkg/agent/openflow/pipeline_test.go

---

docs/network-flow-visibility.md

Add information about Theia in network-flow-visibility doc

---

pkg/agent/route/route_linux.go

Fix ip6tables restore in pkg/agent/route/route_linux.go

---

docs/design/ovs-pipeline.md

an slip reg in ServiceLBTable (41) of ovs-pipeline
Signed-off-by: Isaac He <648391827@qq.com>

Fix an slip in docs/design/ovs-pipline

---

build/charts/antrea/templates/crds/ippool.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml

Add IP version and prefix length validation in IPPool CRD manifest

---

docs/multicluster/quick-start.md
docs/multicluster/user-guide.md

Add more descriptions about multi-cluster Service and Multi-cluster
Gateway configuration. Add table of contents to user-guide.md. Also
made a few minor revisions of the user guide and quick-start guide.

Add more MC Service info and ToC to Multi-cluster user guide

---

docs/multicluster/quick-start.md
docs/multicluster/user-guide.md

Cherry pick of #3909 on release-1.7.
#3909: Add more MC Service info and ToC to Multi-cluster user guide

Automated cherry pick of #3909: Add more MC Service info and ToC to Multi-cluster user guide

---

README.md

Add information about Theia to README

---

docs/antrea-ipam.md

Add a section to enable NodeIPAM feature gate

---

pkg/agent/nodeportlocal/k8s/annotations.go
pkg/agent/nodeportlocal/k8s/annotations_test.go
pkg/agent/nodeportlocal/k8s/npl_controller.go
pkg/agent/nodeportlocal/npl_agent_test.go
pkg/agent/nodeportlocal/testing/annotations.go
pkg/agent/nodeportlocal/types/types.go
test/e2e/nodeportlocal_test.go

This PR creates a new Package for few types which are also used in e2e so as to support running e2e tests on MacOS.

Fix running e2e test on MacOS

---

ci/jenkins/test-vmc.sh

Upgrade CAPV image to 1.23.5

---

test/e2e/wireguard_test.go

Make sure route to Pod and gateway on peer Node target WireGuard device.
Fixes #3517

Enhance e2e tests for WireGuard

---

.github/workflows/process_release.yml
.github/workflows/website.yml

Trigger the workflow in antrea-io/website to update the Helm index for
the Antrea archive and the Flow Aggregator archive.

Trigger "Update Helm index" workflow for releases

---

hack/generate-manifest-flow-aggregator.sh

Fix typo in flow aggregator manifest generation script

---

ci/jenkins/test.sh

Support to switch IP mode of K8s cluster on CI flexible-ipam testbeds. K8s cluster will be redeployed if existing K8s cluster IP mode doesn't match the request property.
Support ipv4, ipv6-ds and ipv6-only cluster.
K8s version is 1.23.6

[ci][flexible-ipam] Deliver K8s cluster when running flexible-ipam-e2e

---

.github/workflows/golicense.yml
.github/workflows/process_release.yml
build/charts/antrea/Chart.yaml
build/charts/flow-aggregator/Chart.yaml
hack/generate-helm-release.sh
hack/release/prepare-assets.sh

See https://artifacthub.io/docs/topics/annotations/helm/
We may add support for more annotations in the future, but this seems
like a good place to start (all annotations are optional).
For #3979

Add some artifacthub.io annotations to Helm charts

---

hack/gc-host-local.sh

Add a script to clean up leaked IPs for host-local plugin

---

pkg/agent/agent.go

Sometimes the PodCIDR within the Node configuration is delayed and in
such case the Antrea Agent crashes.
This situation is addressed when the Pod restarts, but it's easy to
overcome this with a retry.
Retries are executed in 5-10-15-30 interval, so after 1 minute the
Antrea Agent will still crash if no PodCIDR is configured.
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>

Retry when retrieval of PodCIDRs fails

---

docs/vm-installation.md

This document captures the various steps that needs to be carried out 
by the user to configure and run antrea-agent on VM.
Signed-off-by: kumaranand <kumaranand@vmware.com>

[ExternalNode] Add documentation for running antrea-agent on VM

---

CONTRIBUTING.md
Makefile
hack/git_client_side_hooks/pre-push

Adding pre-push hook to verify that all commits are signed-off.
for more information refer this : https://www.git-scm.com/docs/githooks#_pre_push
Closes #3704

Adding pre-push hook 

---

ci/jenkins/test-mc.sh
multicluster/test/e2e/README.md
multicluster/test/e2e/antreapolicy_test.go
multicluster/test/e2e/framework.go
multicluster/test/e2e/main_test.go
multicluster/test/e2e/service_test.go

Refine multi-cluster e2e codes and CI script to support running e2e on a ClusterSet with three kind clusters.
Fixes #3845

Set up Kind clusters to run multi-cluster e2e

---

pkg/agent/agent.go

#3950 introduced a regression.
In networkPolicyOnly mode, the Node PodCIDR may be empty and
Agent initialization should not fail in that case.

Fix Agent initialization for networkPolicyOnly mode

---

ci/jenkins/test.sh
test/e2e/service_test.go

Cherry pick of #3802 on release-1.5.
#3802: Support K8s>=1.20

Automated cherry pick of #3802: Support K8s>=1.20

---

CONTRIBUTING.md

Link to code-review-comments doc in CONTRIBUTING.md

---

docs/multicluster/antctl.md
pkg/antctl/raw/multicluster/init.go
pkg/antctl/raw/multicluster/join.go

Add more comments to the antctl Multi-cluster commands code

---

test/e2e/antreapolicy_test.go
test/e2e/flowaggregator_test.go
test/e2e/framework.go
test/e2e/utils/anp_spec_builder.go
test/e2e/utils/externalnode_spec_builder.go
test/e2e/vmagent_test.go

Add test cases to verify ANP realization on ExternalNode

[ExternalNode] e2e test for ANP on VMs

---

multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go
multicluster/controllers/multicluster/commonarea/resourceimport_controller.go

Referring to kubebuilder sample, simplify deletion logic to delete
resources without checking existing one.

Delete resource directly without checking old one

---

docs/external-node.md

Document a known issue about OVS cleanup in VM reboot case, and
provide a workaround.

[ExternalNode] Add known issue in the document

---

pkg/flowaggregator/flowaggregator.go
pkg/flowaggregator/flowaggregator_test.go

When watchConfiguration was stopped "before" flowExportLoop, it was
possible for flowExportLoop to read from a closed updateCh (channel used
for configuration updates). A nil value was returned and passed to
updateFlowAggregator, causing a panic. Such a panic was observed in CI
(TestFlowAggregator_Run) unit test.
To avoid this issue, we test if the channel is closed when reding from
it. If it is closed, we stop reading from it altogether.
This fixes a bug introduced in https://github.com/antrea-io/antrea/pull/4080,
and doesn't need to appear in release notes for v1.9 or be backported.

Fix race condition when stopping Flow Aggregator

---

build/charts/antrea/templates/_helpers.tpl
build/charts/antrea/templates/agent/daemonset.yaml
build/charts/antrea/templates/controller/deployment.yaml
build/charts/flow-aggregator/templates/_helpers.tpl
build/charts/flow-aggregator/templates/deployment.yaml

Cherry pick of #4138 on release-1.8.
#4138: Fix image tag for Antrea and FlowAggregator Helm charts

Automated cherry pick of #4138: Fix image tag for Antrea and FlowAggregator Helm charts

---

pkg/agent/secondarynetwork/podwatch/controller_test.go

Fix flaky TestPodControllerRun unit test for SecondaryNetwork

---

ci/jenkins/test.sh
docs/windows.md
hack/windows/Helper.psm1

Reverts antrea-io/antrea#4188
Found new issues about proxy configuration with @wenyingd

Revert "Update the proxy mode of kube-proxy to vmkernel on windows"

---

ci/jenkins/README.md

Found in https://github.com/antrea-io/antrea/runs/8204887667?check_suite_focus=true when this file was updated.

Fix links in jenkins README.md

---

test/e2e/antreapolicy_test.go

The DNS server of e2e testbeds may reply large DNS response with a long
list of AUTHORITY SECTION and ADDITIONAL SECTION, which causes the
response to be truncated and the clients to retry over TCP. However,
antrea-agent only inspects DNS UDP packets, the DNS resolution result
will be missed by it if the clients uses DNS over TCP. And if the IP got
from DNS/TCP response is different from the IP got from the first
DNS/UDP response, the following application traffic will bypass FQDN
NetworkPolicy.
To fix the issue properly, either antrea-agent should inspect DNS
traffic over both UDP and TCP, or DNS over TCP should be disabled.
The patch avoids the issue by changing the FQDN used in the test to
github.com, which has a more stable DNS resolution result, so the first
DNS resolution attempt …

Fix FQDN e2e test

---

README.md

Add introduction about VM policies support and Nephe in README

---

pkg/agent/secondarynetwork/podwatch/controller.go

Implement podwatch controller cache to maintain a Pod specific VF pool and its corresponding Linux interface name.
When an SRIOV VF interface gets moved to a container namespace (for secondary network configuration needs), podwatch controller should pick up a unique PCI address from the Pod specific resource pool, which was not assigned for another network interface at that Pod scope.

Implement Podwatch controller cache to maintain a Pod specific VF pool and its corresponding Linux interface name.

---

pkg/agent/controller/trafficcontrol/controller_test.go

Fix flaky pkg/agent/controller/trafficcontrol unit tests

---

pkg/agent/interfacestore/interface_cache_test.go

Fix unit test failure caused by merge conflict

---

multicluster/controllers/multicluster/label_identity_controller.go

Fixes #4294
Data race caused by worker reading and writing r.localClusterID at the same time. 
Refactored the Reconcile loop so that the localClusterID is only set when it is missing.

Fix race condition in label_identity_controller

---

docs/antrea-ipam.md
docs/multicluster/quick-start.md
docs/multicluster/user-guide.md

Update Multi-cluster user guide about Gateway HA and antctl mc commands

---

pkg/antctl/raw/featuregates/command.go
pkg/antctl/raw/multicluster/common/cleanup.go
pkg/antctl/raw/multicluster/common/cleanup_test.go
pkg/antctl/raw/multicluster/common/common.go
pkg/antctl/raw/multicluster/create/member_token.go
pkg/antctl/raw/multicluster/create/member_token_test.go
pkg/antctl/raw/multicluster/delete/member_token.go
pkg/antctl/raw/multicluster/delete/member_token_test.go
pkg/antctl/raw/multicluster/deploy/deploy_helper.go
pkg/antctl/raw/multicluster/deploy/leader_cluster.go
pkg/antctl/raw/multicluster/deploy/member_cluster.go
pkg/antctl/raw/multicluster/destory_test.go
pkg/antctl/raw/multicluster/destroy.go
pkg/antctl/raw/multicluster/get/clusterset.go
pkg/antctl/raw/multicluster/get/clusterset_test.go
pkg/antctl/raw/multicluster/get/member_token.go
pkg/antctl/raw/multicluster/get/resourceexport.go
pkg/antctl/raw/multicluster/get/resourceexport_test.go
pkg/antctl/raw/multicluster/get/resourceimport.go
pkg/antctl/raw/multicluster/get/resourceimport_test.go
pkg/antctl/raw/multicluster/init.go
pkg/antctl/raw/multicluster/init_test.go
pkg/antctl/raw/multicluster/join.go
pkg/antctl/raw/multicluster/join_test.go
pkg/antctl/raw/multicluster/leave.go
pkg/antctl/raw/multicluster/leave_test.go

Unify antctl mc commands help and error messages

---

pkg/agent/controller/trafficcontrol/controller_test.go

The tests should wait for podInformer to be synced, otherwise it's indeterministic when the initial Pods will be processed, and caused flaky tests:
In TestTrafficControlAdd, Pods may not be in cache when syncTrafficControl is executed. (See https://github.com/antrea-io/antrea/actions/runs/3321530933/jobs/5489321100)
In TestPodLabelsUpdate, the initial Pod may be not in cache and the call that updates the Pod may generate an ADD event, instead of an UPDATE event.
Besides, the patch uses a deterministic method to wait for an update has been processed by informer to avoid unnecessary long time spent on sleeping.
Fixes #4197

Fix unit tests of TrafficControl

---

Makefile
ci/jenkins/test.sh

Add DOCKER_NETWORK parameter to support custom network name.

Add docker network parameter to windows build command

---

pkg/controller/egress/controller_test.go

When an ExternalIPPool is deleted, Egresses whose EgressIPs are allocated from it will be updated asynchronously. The unit test should assert Egresses will be updated eventually, instead of immediately after the IP allocations are deleted from cache.

Fix unit test TestUpdateEgress

---

pkg/flowaggregator/flowaggregator.go

The watchConfiguration method needs to return before the fsnotify watcher can be closed, or klog.Fatal will be closed.
Fixes #4298

Fix race condition in TestFlowAggregator_Run unit test

---

pkg/features/antrea_features.go
pkg/features/antrea_features_test.go

Add unit test for pkg/features/antrea_features.go

---

test/e2e-secondary-network/infra/network-attachment-definition-crd.yml
test/e2e-secondary-network/infra/prepare_cluster.sh
test/e2e-secondary-network/infra/prepare_sriov.sh
test/e2e-secondary-network/infra/secondary-network-configuration.yml
test/e2e-secondary-network/infra/virtual-network-instance-crd.yml

Script which helps to configure all the prerequisite configurations to enable Antrea's native secondary network configuration e2e validation.

Antrea native secondary network prerequisite configuration

---

pkg/antctl/command_list_test.go

Add unit test for pkg/antctl/command_list.go

---

pkg/version/version_test.go

Adds unit tests for version.go
For #4142 
Signed-off-by: Harshitha U R harshithaur1611@gmail.com

Add unit tests for pkg/version/version.go

---

test/e2e-secondary-network/infra/prepare_sriov.sh

Fix incorrect use of HostIP (Replace HostIP with hostName variable).

Fix incorrect use of HostIP.

---

.gitignore
Makefile

Signed-off-by: Bin Liu <biliu@vmware.com>

add trivy to scan CVEs in docker image

---

build/images/ovs/Dockerfile.ubi

Cherry pick of #4389 on release-1.9.
#4389: Fix UBI image build error

Automated cherry pick of #4389: Fix UBI image build error

---

pkg/agent/proxy/proxier_test.go

Add unit tests for pkg/agent/proxy

---

build/charts/antrea/README.md
build/charts/antrea/conf/antrea-controller.conf
build/charts/antrea/values.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
cmd/antrea-controller/controller.go
cmd/antrea-controller/options.go
multicluster/apis/multicluster/v1alpha1/multiclusterconfig_types.go
multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
multicluster/build/yamls/antrea-multicluster-member.yml
multicluster/cmd/multicluster-controller/leader.go
multicluster/cmd/multicluster-controller/leader_test.go
multicluster/cmd/multicluster-controller/member.go
multicluster/cmd/multicluster-controller/member_test.go
multicluster/cmd/multicluster-controller/options.go
multicluster/config/default/configmap/controller_manager_config.yaml
multicluster/controllers/multicluster/commonarea/remote_common_area.go
multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
multicluster/controllers/multicluster/gateway_controller_test.go
multicluster/controllers/multicluster/label_identity_controller_test.go
multicluster/controllers/multicluster/member_clusterset_controller.go
multicluster/controllers/multicluster/serviceexport_controller_test.go
multicluster/controllers/multicluster/stale_controller_test.go
multicluster/test/integration/suite_test.go
pkg/config/controller/config.go

This PR added a separate toggle for StretchedNetworkPolicy in MC Controller.

Add StretchedNetworkPolicy toggle

---

pkg/antctl/raw/traceflow/command.go
pkg/antctl/raw/traceflow/command_test.go

Add unit tests for pkg/antctl/raw/traceflow

---

pkg/agent/multicast/mcast_controller_test.go
pkg/agent/multicast/mcast_discovery.go
pkg/agent/multicast/mcast_discovery_test.go
pkg/agent/multicast/mcast_route_test.go

Add multicast unit tests

---

docs/egress.md

Fix indent in ExternalIPPool example

---

ci/kind/kind-setup.sh
docs/kind.md

Cherry pick of #3882 on release-1.7.
#3882: Add a new option --service-cidr

Automated cherry pick of #3882: Add a new option --service-cidr

---

test/e2e/connectivity_test.go

In testOVSFlowReplay, the number of flows before flow replay may be different from the one after it because there are some Pods being deleted during the flow replay. The patch fixes it by ensuring Pods used in the test running before it to be deleted.
--------------
Example failure:
```
=== RUN   TestConnectivity/testOVSFlowReplay
connectivity_test.go:379: Creating 2 busybox test Pods on 'jenkins-antrea-e2e-for-pull-request-1614-md-0-6757774785-mfjc2'
connectivity_test.go:75: Waiting for Pods to be ready and retrieving IPs
connectivity_test.go:89: Retrieved all Pod IPs: map[test-pod-0-ucgx67bn:IPv4(192.168.1.60),IPstrings(192.168.1.60) test-pod-1-vdh2o5ty:IPv4(192.168.1.61),IPstrings(192.168.1.61)]
connectivity_test.go:98: Ping mesh test between …
```

e2e: fix flaky test testOVSFlowReplay

---

cmd/antrea-agent/util.go
cmd/antrea-agent/util_test.go

Adds the unit test for util.go .
For #4142 
Signed-off-by: Harshitha U R harshithaur1611@gmail.com

Add unit test for cmd/antrea-agent/util.go

---

docs/antctl.md
docs/support-bundle-guide.md

Add support bundle docs

---

docs/multicluster/user-guide.md

Add documentation for Stretched NetworkPolicy feature

---

docs/antrea-l7-network-policy.md
docs/antrea-network-policy.md
docs/feature-gates.md

Add user guide for L7 NetworkPolicy

---

build/charts/antrea/README.md
build/charts/antrea/conf/antrea-agent.conf
build/charts/antrea/values.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml

Update code comments according to this discussion: https://github.com/antrea-io/antrea/pull/4350#discussion_r1054418162

Update comment to remove the tunnel type limit

---

docs/feature-gates.md

Update feature gate doc for the Multicluster feature

---

build/charts/antrea/conf/antrea-agent.conf
build/charts/antrea/conf/antrea-controller.conf
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
cmd/antrea-agent/agent.go
pkg/agent/agent.go
pkg/agent/controller/networkpolicy/networkpolicy_controller.go
pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
pkg/agent/openflow/client.go
pkg/agent/openflow/client_test.go
pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go
pkg/agent/openflow/pipeline.go
pkg/controller/networkpolicy/validate.go
pkg/controller/networkpolicy/validate_test.go
pkg/features/antrea_features.go
test/e2e/l7networkpolicy_test.go
test/integration/agent/openflow_test.go

For https://github.com/antrea-io/antrea/issues/4231

Add feature gate for L7 NetworkPolicy

---

build/charts/antrea/README.md
build/charts/antrea/conf/antrea-controller.conf
build/charts/antrea/values.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
pkg/agent/cniserver/interface_configuration_linux.go
pkg/config/agent/config.go
pkg/config/controller/config.go
pkg/controller/networkpolicy/networkpolicy_controller.go

Fix a few typos and formatting issues in config options

---

.github/workflows/process_release.yml

Upload new asset antrea-windows-containerd.yml to support Windows with containerd.

Upload asset antrea-windows-containerd.yml

---

.github/workflows/process_release.yml

Cherry pick of #4530 on release-1.10.
#4530: Upload asset antrea-windows-containerd.yml

Automated cherry pick of #4530: Upload asset antrea-windows-containerd.yml

---

pkg/graphviz/traceflow_test.go

Adds the unit test for traceflow.go .
For #4142
Signed-off-by: Harshitha U R <harshithaur1611@gmail.com>

Add unit test for pkg/graphviz/traceflow.go

---

build/charts/antrea/README.md
build/charts/antrea/conf/antrea-agent.conf
build/charts/antrea/conf/antrea-controller.conf
build/charts/antrea/values.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
docs/feature-gates.md
docs/multicluster/quick-start.md
docs/multicluster/user-guide.md
pkg/config/agent/config.go
pkg/config/controller/config.go

Started to use term "Multi-cluster NetworkPolicy" in YAML, comments, and docs.
Updated Multi-cluster user docs with introduction about Multi-cluster NetworkPolicy support.

Update YAMLs and docs about Multi-cluster NetworkPolicy

---

docs/network-requirements.md

Both TCP and UDP 10351 are required for memberlist gossip communication.

Fix network requirements doc

---

pkg/agent/util/net_linux.go
pkg/agent/util/net_windows.go
pkg/agent/wireguard/client_linux.go
pkg/agent/wireguard/client_test.go
pkg/agent/wireguard/client_windows_test.go

Add more unit tests for wireguard package

---

test/e2e/framework.go
test/e2e/security_test.go
test/e2e/supportbundle_test.go
test/e2e/utils/portforwarder/portforwarder.go

e2e tests should not run commands from the host machine

---

pkg/flowaggregator/flowaggregator_test.go

Add unit tests for pkg/flowaggregator/flowaggregator.go

Add UT for pkg/flowaggregator/flowaggregator.go

---

pkg/agent/apiserver/apiserver_test.go

There was a race condition (observed on Windows Github runners), caused by requests to the apiserver while handlers were still being installed.
Fixes #4557

Fix race condition in TestAPIServerLivezCheck

---

ci/jenkins/test-vmc.sh

Upgrade the cluster image to ubuntu-2004-kube-v1.25.5.

Upgrade CAPV image to 1.25.5

---

pkg/agent/openflow/pipeline.go

Remove the `Drop` for `DefaultDropFlow` before `Action` is applied.

Remove dummy drop in DefaultDropFlow

---

.github/codeql-config.yml
.github/workflows/codeql.yml
pkg/agent/util/net.go
pkg/apiserver/handlers/webhook/convert_crd.go
pkg/ovs/ovsctl/ovsctl_others.go

LGTM.com is going to shutdown, the official replacement is code scanning with the product CodeQL.
Add a new workflow file to trigger code scanning.

Add CodeQL code scanning to replace LGTM.com

---

pkg/agent/multicluster/stretched_networkpolicy_controller_test.go

Wait for Pod update in MCNP UT

---

.github/workflows/go.yml
multicluster/Makefile
multicluster/build/images/Dockerfile.build

Change multicluster "make build" to "make bin"

---

pkg/agent/proxy/proxier.go

Remove config for Endpoints API when feature gate EndpointSlice is enabled

---

ci/jenkins/README.md
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test-rancher.sh
test/e2e/connectivity_test.go
test/e2e/framework.go

Introducing test script to support running test on rancher ci pipeline

Introducing test script to support running test on rancher ci pipeline

---

ci/jenkins/test-vm.sh

1. Old `awk` command is incorrect. It happened to work for the old single-node cluster.
2. Image should be loaded by `ctr` command if the upgraded cluster uses containerd as container  runtime.

Fix setup code for external vms testbed after cluster version upgrade

---

ci/jenkins/test-vm.sh
pkg/agent/externalnode/external_node_controller.go
pkg/agent/externalnode/external_node_controller_linux.go
pkg/agent/externalnode/external_node_controller_linux_test.go
pkg/agent/externalnode/external_node_controller_test.go

Add unit tests for externalnode

---

pkg/controller/networkpolicy/antreanetworkpolicy.go
pkg/controller/networkpolicy/antreanetworkpolicy_test.go
pkg/controller/networkpolicy/clustergroup.go
pkg/controller/networkpolicy/clustergroup_test.go
pkg/controller/networkpolicy/clusternetworkpolicy.go
pkg/controller/networkpolicy/clusternetworkpolicy_test.go
pkg/controller/networkpolicy/crd_utils.go
pkg/controller/networkpolicy/crd_utils_test.go
pkg/controller/networkpolicy/endpoint_querier_test.go
pkg/controller/networkpolicy/networkpolicy_controller.go
pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
pkg/controller/networkpolicy/networkpolicy_controller_test.go
pkg/controller/networkpolicy/store/appliedtogroup.go
pkg/controller/networkpolicy/store/networkpolicy.go
pkg/controller/types/networkpolicy.go

#4028: Fix race conditions in NetworkPolicyController

Automated cherry pick of #4028: Fix race conditions in NetworkPolicyController Cherry pick of #4028 on release-1.7

---

pkg/flowaggregator/exporter/ipfix_test.go

For https://github.com/antrea-io/antrea/issues/4142
Signed-off-by: Naman Agarwal [naman.agarwal75@gmail.com]

Add unit test for pkg/flowaggregator/exporter/ipfix.go

---

docs/service-loadbalancer.md

Starting with v0.13, MetalLB is no longer configured using a ConfigMap, but with Custom Resources. We update the service-loadbalancer document to provide up-to-date MetalLB configuration examples.

Update documentation for recent MetalLB versions

---

pkg/agent/controller/traceflow/packetin_test.go
pkg/agent/controller/traceflow/traceflow_controller_test.go

Add more unit test for pkg/agent/controller/traceflow/traceflow_controller.go
For https://github.com/antrea-io/antrea/issues/4142

Add more unit test for pkg/agent/controller/traceflow/traceflow_controller.go

---

ci/jenkins/test.sh

Otherwise any error would cause no logs being collected.

Ignore errors encountered when collecting test logs

---

build/yamls/externalnode/support-bundle-collection-rbac.yml
ci/jenkins/test-vm.sh
docs/support-bundle-guide.md
hack/externalnode/sftp-deployment.yml
pkg/support/dump_windows.go
pkg/support/dump_windows_test.go
test/e2e/vmagent_test.go

Add simple e2e case for SupportBundleCollection feature, collecting on the Linux and Windows VMs.

SupportBundleCollection e2e test

---

test/e2e/ipsec_test.go

Do not assume that the ping tests are executed on the first Node. Instead, check from the Node where the first Pod is running. 
Fixes: #4477

Fix IPsec e2e flaky

---

pkg/antctl/raw/supportbundle/command.go
pkg/antctl/raw/supportbundle/command_test.go

Add unit test for pkg/antctl/raw/supportbundle

---

multicluster/controllers/multicluster/member/resourceimport_controller_test.go
multicluster/controllers/multicluster/stale_controller.go

Fix race condition between stale controller and resourceimport reconcilers

---

pkg/agent/controller/networkpolicy/fqdn.go
test/e2e/antreapolicy_test.go

Fix FQDN upper-case issue

---

build/images/base/Dockerfile

Reverts antrea-io/antrea#4933
Closes: #4921

Revert "Temporarily install Suricata from Ubuntu PPA instead of OISF PPA"

---

ci/jenkins/README.md
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test.sh

Cherry pick of #4872 on release-1.11.
#4872: Add containerd to windows jenkins jobs

Automated cherry pick of #4872: Add containerd to windows jenkins jobs

---

pkg/controller/networkpolicy/networkpolicy_controller.go
pkg/controller/networkpolicy/networkpolicy_controller_test.go

Cherry pick of #4986 on release-1.10.
#4986: Fix policy not being cleaned if a policy with the same name

Automated cherry pick of #4986: Fix policy not being cleaned if a policy with the same name

---

multicluster/controllers/multicluster/leader/labelidentity_export_controller.go
multicluster/controllers/multicluster/leader/labelidentity_export_controller_test.go

The labelsToID map in labelidentity_export_controller is not protected by mutex, and thus susceptible to concurrent map writes by multiple workers of the label queue, though the workers should be reconciling distinct label hash keys. Thus, this commit changes labelsToID to use sync.Map.

Fix concurrent map write in mc controller

---

test/e2e/framework.go

Phase Running just means at least one container is still running, or is in the process of starting or restarting.

waitForAntreaDaemonSetPods should wait for Pods being ready

---

.github/workflows/conformance.yml
ci/run-k8s-e2e-tests.sh

We can easily verify compatibility between Antrea and K8s releases with the workflow.

Add a parameterized workflow to run conformance tests flexibly

---

pkg/agent/controller/networkpolicy/reconciler.go

* Switched to strctured logging
* Change verbosity of potentially misleading Info log
Fixes #4974

Logging improvements in Agent NP reconciler

---

.github/workflows/conformance.yml

So we can test non default configurations.

Support specifying chart values for conformance test workflow

---

pkg/agent/openflow/network_policy.go
pkg/agent/openflow/network_policy_test.go

Cherry pick of #5078 on release-1.12.
#5078: Bugfix: TCP src port is unset on the TCP DNS response flow

Automated cherry pick of #5078: Bugfix: TCP src port is unset on the TCP DNS response flow

---

.gitignore

For paths that no longer exist

Remove stale .gitignore entries

---

pkg/agent/controller/egress/egress_controller.go
pkg/agent/controller/egress/egress_controller_test.go
pkg/agent/controller/serviceexternalip/controller.go
pkg/agent/controller/serviceexternalip/controller_test.go
pkg/agent/ipassigner/ip_assigner.go
pkg/agent/ipassigner/ip_assigner_linux.go
pkg/agent/ipassigner/responder/arp_responder.go
pkg/agent/ipassigner/responder/arp_responder_test.go
pkg/agent/ipassigner/responder/ndp_responder.go
pkg/agent/ipassigner/responder/ndp_responder_test.go
pkg/agent/ipassigner/testing/mock_ipassigner.go
test/e2e/egress_test.go
test/e2e/framework.go
test/e2e/multicast_test.go
test/integration/agent/ip_assigner_linux_test.go

Cherry pick of #5127 on release-1.12.
#5127: Fix Egress IP not advertised in some cases

Automated cherry pick of #5127: Fix Egress IP not advertised in some cases

---

test/e2e/framework.go

This change adds additional wait for ClickHouse Service in FA e2e test to avoid premature test failures due to service not found.
This is a cherry-pick of #5148 to release-1.11 branch.
Fixes https://github.com/antrea-io/antrea/issues/5146

Fix ClickHouse service not found in FA e2e test

---

pkg/agent/openflow/client_test.go
pkg/agent/openflow/pipeline.go
pkg/ovs/openflow/interfaces.go
pkg/ovs/openflow/ofctrl_action.go
test/integration/agent/openflow_test.go
test/integration/ovs/ofctrl_test.go

This change eliminates hard-coded variables in learned flow actions, refactors action methods, and ensures that each method is designed to add an action.

Refactor learn flow actions

---

test/e2e/antctl_test.go
test/e2e/framework.go

Speed up TestAntctl/testAntctlProxy e2e test and check Pod name for the Node

---

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller.go
pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go

Use fake clocks to make sure the test is deterministic. This helps to avoid flaky tests on slow testbeds.
Supersedes: https://github.com/antrea-io/antrea/pull/5155

Use fake clocks in IPsec certificate controller tests

---

Makefile
build/yamls/antrea-windows-containerd.yml
build/yamls/windows/containerd/agent-containerd.yml

Add generating windows containerd YAML in github action check.

Update Makefile to generate Windows containerd manifest

---

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller.go
pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go

The test is flaky because the computed rotation deadline is sometimes <7s, due to the NotAfter certificate field being truncated at the second. We can resolve the issue by also truncating the fake clock initial time.
We also use the controller's clock time when validating certificates. Because some tests use a fake clock, the time that was used was incorrect, leading to some error logs - and potentially test failures.
Fixes #5234

Fix TestController_RotateCertificates unit test

---

ci/jenkins/test.sh

Cherry pick of #5164 on release-1.11.
#5164: Add square brackets for IP addresse when using jumper mode

Automated cherry pick of #5164: Add square brackets for IP addresse when using jumper mode

---

.github/workflows/kind.yml
.github/workflows/netpol_cyclonus.yml
ci/kind/kind-setup.sh
multicluster/hack/verify-tools.sh
test/e2e/l7networkpolicy_test.go

Cherry pick of #4920 on release-1.11.
#4920: Upgrade Kind

Automated cherry pick of #4920: Upgrade Kind

---

pkg/apiserver/handlers/webhook/convert_crd_test.go
pkg/apiserver/handlers/webhook/mutation_crd_test.go
pkg/apiserver/handlers/webhook/mutation_labels_test.go
pkg/apiserver/handlers/webhook/validation_crd_test.go
pkg/apiserver/handlers/webhook/webhook_test.go

Add unit test for `pkg/apiserver/handlers/webhook` to improve code coverage.

Add unit test for pkg/apiserver/handlers/webhook

---

multicluster/controllers/multicluster/leader/resourceexport_controller.go
pkg/agent/cniserver/interface_configuration_windows.go
pkg/agent/cniserver/pod_configuration.go
pkg/agent/cniserver/pod_configuration_linux.go
pkg/agent/cniserver/pod_configuration_linux_test.go
pkg/agent/cniserver/pod_configuration_windows.go
pkg/agent/cniserver/server.go
pkg/agent/cniserver/server_linux_test.go
pkg/agent/cniserver/sriov.go
pkg/agent/secondarynetwork/cnipodcache/cache.go
pkg/agent/secondarynetwork/cnipodcache/types.go
pkg/agent/secondarynetwork/podwatch/controller.go
pkg/agent/secondarynetwork/podwatch/controller_test.go
pkg/controller/externalnode/controller.go

Fix wrong writing of namespace

---

test/e2e/k8s_util.go

Before this patch, GetPodByLabel may return err==nil even if there is an error. This patch fixed this bug.
This is because errors.WithMessagef(err, msg) returns nil if err is nil. If `err == nil && len(pods) == 0`, GetPodByLabel will return err==nil, so the caller won't know there is an error.

Fix a bug of error handling in GetPodByLabel

---

build/charts/antrea/crds/egress.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-crds.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml

Using a unified alignment method in egress yaml as other yaml files

Using a unified alignment method in egress yaml as other yaml files 

---

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go

Use a virtual time in the future. This is because
certutil.NewSelfSignedCACert uses real wall-clock time to generate the root certificate, and there is a possibility that the NotBefore field for the CA certificate is after the "now" virtual time. This can in turn cause certificate validation to fail and the unit test to fail.

Use new virtual time for TestController_RotateCertificates

---

ci/test-conformance-gke.sh
docs/gke-installation.md

Cherry pick of #5298 on release-1.12.
#5298: Fix GKE conformance job

Automated cherry pick of #5298: Fix GKE conformance job

---

go.mod
go.sum

Bump up libOpenflow library to v0.12.1

---

test/e2e/framework.go
test/e2e/l7networkpolicy_test.go

Fix flaky e2e test TestL7NetworkPolicy/TLS

---

go.mod
go.sum

Bump up libOpenflow library to v0.10.4

---

ci/jenkins/test-vm.sh

Cherry pick of #5254 on release-1.11.
#5254: Fix VM e2e script to import updated image

Automated cherry pick of #5254: Fix VM e2e script to import updated image

---

pkg/agent/config/ipsec_authentication_mode.go
pkg/agent/util/net_windows.go

[Windows] Support querying all NDIS network adapters

---

test/e2e/vmagent_test.go

Sometimes the image can take a long time to pull from Harbor, and 30s may not be enough.
Also improve logging to make future issues easier to troubleshoot.

[E2E VM Test] Increase timeout for sftp deployment to become ready

---

ci/kind/kind-setup.sh
ci/kind/test-e2e-kind.sh

Add an --extra-networks option to kind-setup.sh to create extra Docker bridge networks which will be connected by each kind worker node. The --extra-networks option cannot be specified together with the --subnets option.
Add an --extra-network option to test-e2e-kind.sh which will create a single extra network for the kind test cluster. The option does not work with the hybrid encap mode (which runs kind-setup.sh with the  --subnets option). The extra network will be required for the e2e tests of secondary VLAN network, which create a secondary OVS bridge on each worker node, and need an extra host interface connected on the bridge.

Support creating extra Docker networks in kind tests

---

ci/jenkins/test.sh

Support parallel image building on Linux and Windows nodes during the image delivery process.
Fixes #4805.

Support parallel image building on Linux and Windows nodes

---

build/charts/antrea/conf/antrea-agent.conf
build/charts/antrea/conf/antrea-controller.conf
build/yamls/antrea-aks.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
docs/feature-gates.md
pkg/features/antrea_features.go

fix: https://github.com/antrea-io/antrea/pull/5314#discussion_r1303567962

Add IPsecCertAuth in the docs

---

pkg/agent/memberlist/cluster.go
pkg/agent/memberlist/cluster_test.go

Cherry pick of #5434 on release-1.12.
#5434: Do not attempt to join Windows agents to memberlist cluster

Automated cherry pick of #5434: Do not attempt to join Windows agents to memberlist cluster

---

ci/jenkins/jobs/projects-lab.yaml

Update the Jenkins job description to enable e2e, conformance, and network policy tests with NSX VPC support.

Add NSX VPC jobs to the Jenkins pipeline

---

test/e2e/wireguard_test.go

Change the Wireguard e2e tests to make sure
the TrafficEncryptionMode will be reset to origin and namespaces created during setup will be destroyed after tests finish.

Fix Wireguard e2e tests

---

hack/windows/Install-OVS.ps1

Cherry pick of #5510 on release-1.11.
#5510: Fix Bugs and Introduce Enhancements in Install-OVS.ps1

Automated cherry pick of #5510: Fix Bugs and Introduce Enhancements in Install-OVS.ps1

---

pkg/controller/networkpolicy/networkpolicy_controller.go
pkg/controller/networkpolicy/networkpolicy_controller_test.go
pkg/controller/networkpolicy/subscribe.go
pkg/controller/networkpolicy/subscribe_test.go

Cherry pick of #5554 on release-1.12.
#5554: Fix NetworkPolicy span calculation

Automated cherry pick of #5554: Fix NetworkPolicy span calculation

---

ci/jenkins/test-vmc.sh

Upgrade the cluster image to ubuntu-2004-kube-v1.28.0.

Upgrade CAPV image to 1.28.0

---

build/yamls/antrea-prometheus.yml
docs/prometheus-integration.md
test/e2e/prometheus_test.go

Upgrade Prometheus to v2.46.0 and change the image to `ubuntu/prometheus:2.46.0-22.04_stable`

Upgrade Prometheus to v2.46.0

---

pkg/agent/util/ipset/ipset.go
pkg/agent/util/ipset/testing/mock_ipset.go

Add method DestroyIPSet in pkg/agent/util/ipset

---

pkg/agent/openflow/network_policy_test.go
pkg/agent/openflow/pipeline.go
test/e2e/antreapolicy_test.go
test/e2e/networkpolicy_test.go

Cherry pick of #5687 on release-1.13.
#5687: Fix NP not working on Hairpin

Automated cherry pick of #5687: Fix NP not working on Hairpin

---

docs/antrea-network-policy.md

A bit redundant perhaps, but I think it will help clarify things even more for users

Clarify hairpin Service traffic case in NP doc

---

ci/jenkins/test-vmc.sh

This patch improves the Docker image cleanup process to ensure that all images unused within
the last hour are removed.

Enhance Docker image cleanup process

---

.github/dependabot.yml
.github/workflows/conformance.yml
.github/workflows/golicense.yml
.github/workflows/kind.yml
.github/workflows/trivy_scan.yml

Bump them up from v3 to v4.
Also try to configure Dependabot to update them as a group in the future.

Update actions/upload-artifact and actions/download-artifact together

---

build/charts/antrea/templates/simulator/statefulset.yaml
docs/antrea-agent-simulator.md
docs/maintainers/build-kubemark.md

Update kubemark to v1.29.0

---

docs/antrea-l7-network-policy.md
docs/antrea-network-policy.md
docs/design/ovs-pipeline.md
docs/external-node.md
docs/multicluster/user-guide.md

Update NetworkPolicy version to v1beta1 in documents

---

test/e2e/egress_test.go

Generating events is asynchronous, e2e test should check it eventually gets the event. It should check the length of events first before accessing the index.
---
The panic:
```
=== RUN   TestEgress/testEgressCRUD/single_matching_Node_with_IPv6_range
--- FAIL: TestEgress (38.44s)
--- PASS: TestEgress/testEgressClientIP (32.89s)
--- SKIP: TestEgress/testEgressClientIP/ipv4-cluster (0.00s)
--- PASS: TestEgress/testEgressClientIP/ipv6-cluster (32.89s)
--- SKIP: TestEgress/testEgressClientIPFromVLANSubnet (0.00s)
--- FAIL: TestEgress/testEgressCRUD (0.69s)
--- SKIP: TestEgress/testEgressCRUD/single_matching_Node (0.00s)
--- FAIL: TestEgress/testEgressCRUD/single_matching_Node_with_IPv6_range (0.69s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: …
```

Fix e2e test panic when expected events not found

---

hack/windows/Install-OVS.ps1

Update windows ovs download link to remove the redundant certificate

---

pkg/agent/apiserver/handlers/ovstracing/handler.go
pkg/agent/apiserver/handlers/ovstracing/handler_test.go
pkg/ovs/ovsctl/appctl.go
pkg/ovs/ovsctl/ovsctl.go

Cherry pick of #5838 on release-1.13.
#5838: Fix antctl trace-packet arguments missing issue

Automated cherry pick of #5838: Fix antctl trace-packet arguments missing issue

---

docs/api.md
docs/service-loadbalancer.md
test/e2e/antreapolicy_test.go

Code and docs tidy up for Antrea 2.0 #4832

Update docs and clients with latest API versions

---

docs/design/architecture.md

* Update kube-proxy modes
* Point to kube-proxy documentation instead of kubernetes service documentation

Some minor updates to Architecture documentation

---

.github/workflows/build.yml
.github/workflows/build_tag.yml
Makefile
build/images/Dockerfile.build.agent.coverage
build/images/Dockerfile.build.agent.ubi
build/images/Dockerfile.build.agent.ubuntu
build/images/Dockerfile.build.controller.coverage
build/images/Dockerfile.build.controller.ubi
build/images/Dockerfile.build.controller.ubuntu
hack/build-antrea-linux-all.sh

Build different images for antrea-agent and antrea-controller

---

pkg/agent/flowexporter/connections/conntrack_connections.go
pkg/agent/flowexporter/exporter/exporter.go

When L7FlowExporter is not enabled, we cannot retrieve the l7EventMap and fill l7 event info in the flow-exporter. Checking if l7EventMapGetter is nil before getting the l7EventMap to prevent antrea-agent from crashing due to runtime error: invalid memory address or nil pointer dereference.

Check if l7EventMapGetter is nil in poll()

---

ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-cloud.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test.sh
ci/kind/kind-setup.sh

Closes: #5542
Run NetworkPolicy, conformance and e2e tests in kind-(dual-stack /ipv6-only )clusters in jenkins and aws.

Run NetworkPolicy, Conformance and e2e tests in dual stack and ipv6 kind cluster in lab jenkins and public cloud aws.

---

docs/antrea-node-network-policy.md

Update NodeNetworkPolicy document example case

---

docs/antrea-node-network-policy.md

Cherry pick of #5971 on release-1.15.
#5971: Update NodeNetworkPolicy document example case (#5971)

Automated cherry pick of #5971: Update NodeNetworkPolicy document example case (#5971)

---

hack/git_client_side_hooks/pre-commit
hack/git_client_side_hooks/pre-push

Use bash in pre-push pre-commit hook

---

pkg/agent/agent.go

Cherry pick of #5997 on release-1.15.
#5997: Use 65000 MTU upper bound for interfaces in encap mode

Automated cherry pick of #5997: Use 65000 MTU upper bound for interfaces in encap mode

---

docs/contributors/docker-desktop-alternatives.md

A free Docker Desktop alternative on macOS

Add more information about Colima

---

ci/test-conformance-aks.sh
ci/test-conformance-eks.sh
ci/test-conformance-gke.sh

These scripts call the check_and_cleanup_docker_build_cache function.

Source jenkins/utils.sh in public cloud CI scripts

---

pkg/agent/controller/traceflow/traceflow_controller.go
pkg/agent/controller/traceflow/traceflow_controller_test.go

Cherry pick of #5954 on release-1.14.
#5954: Fix race condition in agent Traceflow controller (#5954)

Automated cherry pick of #5954: Fix race condition in agent Traceflow controller (#5954)

---

build/images/ovs/Dockerfile.ubi
test/e2e/basic_test.go

Cherry pick of #6052 on release-1.14.
#6052: Fix log rotation in UBI images (#6052)

Automated cherry pick of #6052: Fix log rotation in UBI images (#6052)

---

docs/antctl.md

Update the command to print OVS table names

---

test/e2e/vmagent_test.go

Cherry pick of #6154 on release-1.15.
#6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"

Automated cherry pick of #6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"

---

docs/contributors/github-labels.md

Adding bgp label for bgp feature specific issues/Prs

Adding label area/transit/bgp for bgp specific issues and PRs

---

pkg/apiserver/certificate/selfsignedcert_provider.go
pkg/apiserver/certificate/selfsignedcert_provider_test.go

Cherry pick of #6205 on release-1.15.
#6205: Do not try to update type of Secret in selfSignedCertProvider

Automated cherry pick of #6205: Do not try to update type of Secret in selfSignedCertProvider

---

docs/antrea-network-policy.md

Cherry pick of #6280 on release-2.0.
#6280: Add documentation for the sameLabels feature in ACNP (#6280)

Automated cherry pick of #6280: Add documentation for the sameLabels feature in ACNP (#6280)

---

.github/workflows/kind.yml

Implements dual stack cluster in workflow to test Pre and Post installation checks

dual stack cluster support - installation tests

---

docs/traceflow-guide.md

Cherry pick of #6319 on release-2.0.
#6319: Fix inaccuracy in Traceflow user guide (#6319)

Automated cherry pick of #6319: Fix inaccuracy in Traceflow user guide (#6319)

---

ci/jenkins/test-vmc.sh

Update CAPV image to ubuntu22.04-v1.30.0.

Upgrade CAPV image to 1.30.0

---

build/charts/antrea/README.md
build/charts/flow-aggregator/README.md

Update Kubernetes version in README

Update Kubernetes version in README

---

docs/kubernetes-installers.md

Antrea version update with rancher

Antrea version update for rancher

---

pkg/agent/controller/networkpolicy/allocator_test.go

The test has been failing in Github CI, albeit very rarely. The issue is that there exists a possible race between the creation of the timer by the DelayingQueue (which determines when to add the item to the queue after the waiting period is over) and the test code that advances the clock. If the DelayingQueue determines that a 1s timer is appropriate, but we advance the fake clock right as NewTimer is being called, we will actually sleep until a deadline that is further in the future than expected. The K8s FakeClock implementation provides an HasWaiters method which is meant to be used by tests to avoid such races. However, it is not sufficient in our case, since the creation of the DelayingQueue will instantiate a Ticker, which itself counts as a waiter. Therefore HasWaiters cannot be …

Fix racy unit test TestIdAllocatorWorker

---

test/e2e/l7networkpolicy_test.go

I have seen the test fail quite frequently in CI. I do not know the root cause, but this patch tries to make it more robust (e.g., by allowing duplicate log entries) and adds some debugging information in case of test failure.

[e2e test] Increase robustness of TestL7NetworkPolicy/Logging

---

ci/jenkins/docker_login.sh
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-cloud.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test-vmc.sh

Cherry pick of #6368 on release-1.15.
#6368: Add Docker login to Jenkins script to avoid rate limit issue

Automated cherry pick of #6368: Add Docker login to Jenkins script to avoid rate limit issue

---

cmd/antrea-agent/agent.go

We want flowRestoreCompleteWait to depend on podNetworkWait. However, the implementation was invalid:
* the goroutine in charge of invoking flowRestoreCompleteWait.Done() after podNetworkWait.Wait() returns was placed too early in the initialization logic. There was a high probability that podNetworkWait.Wait() would be called before the first call to podNetworkWait.Increment(), making the goroutine useless.
* the statement that the dependency is guaranteed by CNIServer was incorrect for Nodes without non-hostNetwork Pods at the time of initialization. For such Nodes, flowRestoreCompleteWait.Done() was called immediately, without a dependency on podNetworkWait.Wait().

Fix dependency of flowRestoreCompleteWait on podNetworkWait

---

pkg/agent/monitortool/monitor_test.go

The monitor uses create to report the latest latency measurements, and we do not need to distinguish between create and update for our use case. However, the fake client is implemented using a simple object tracker that will fail if create is called multiple times for the same resource name. This can affect unit tests for the monitor, either because a misleading error message is logged or because updates are ignored.

Use create reactor for NodeLatencyStats fake client

---

test/integration/ovs/ovs_client_test.go

The test modifies other_config in the Open_vSwitch table. This is global configuration, and not specific to a bridge. Improper cleanup can affect subsequent runs of the test, but also other tests such as TestPacketOutIn, as it sets flow-restore-wait.

Fix cleanup in TestOVSOtherConfig integration test

---

ci/kind/validate-metrics-doc.sh
docs/prometheus-integration.md

Additionally, make validate-metrics-doc.sh output the diff if there is.

Fix Prometheus metrics doc

---

docs/feature-gates.md

Update the documentation to support renaming of TopologyAwareHints featuregate to Topology Aware Routing
#6469

Update document for TopolgyAwareHints featuregate

---

docs/api.md

Merge the PR after #6447 and #6203.

Add BGPPolicy to docs/api.md

---

pkg/agent/flowexporter/connections/l7_listener.go
pkg/agent/flowexporter/connections/l7_listener_test.go

The L7Listener is responsible for receiving and processing Suricata events. When the stop channel is closed, the listener should be closed in order to stop accepting connections. This doesn't really matter when this code is run as part of the antrea-agent, but it is useful for unit testing.
We also improve the unit tests for the L7Listener. Sub-tests should not share a common gomock controller. Instead of sleeps, we use polling when waiting for conditions to be met.

Improve L7Listener code in FlowExporter

---

Makefile

The patch adds a parameter `TEST_ARGS` to pass go test arguments when running tests with make.
It also add `-it` to `docker run` to make the tests interruptable.

test: support go test arguments and interuptting containerized tests

---

cmd/antrea-agent/agent.go
cmd/antrea-controller/controller.go
cmd/flow-aggregator/flow-aggregator.go

Make Start / Stop log messages consistent across Antrea programs.

Log Flow Aggregator version on start

---

pkg/controller/labelidentity/label_group_index_test.go

I have seen one test failing in Windows CI because of the short sleep duration. Use polling instead to make the tests more robust.

Replace sleeps with polling in LabelIdentityIndex unit tests

---

go.mod
go.sum
pkg/agent/route/route_linux.go
pkg/agent/route/route_linux_test.go

The minor release has some breaking API changes so some code updates are required.

Bump github.com/vishvananda/netlink to v1.3.0

---

CONTRIBUTING.md
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test.sh
ci/kind/kind-setup.sh
ci/kind/test-e2e-kind.sh
test/e2e/fixtures.go
test/e2e/framework.go

To support running Antrea Flexible IPAM tests on KIND.

---

pkg/agent/proxy/topology.go

This fix is ​​consistent with the latest kube-proxy implementation. See https://github.com/kubernetes/kubernetes/blob/25aa9cd074072307a1168259c92cfefb1eafc27a/pkg/proxy/topology.go#L165
Fix #6682

Add log verbosity to topology aware Endpoint filtering

---

test/e2e/flowaggregator_test.go

When the IPFIX collector has not received the expected flow records, we try to dump the actual list of records to facilitate troubleshooting. However, the output is to large to be handled by the testify assertions (and IMO it is too large to be useful for troubleshooting). With this change, if the expected records are not found in the collector output, we only print the 20 most recent records, in a format that should be easier to leverage for troubleshooting.
Fixes #6478

Fix error logs for FlowAggregator e2e tests

---

pkg/controller/ipam/antrea_ipam_controller_test.go

The tests should wait for the informers cache to have synced. Also remove some unnecessary code in TestStatefulSetLifecycle.

Improve some Antrea IPAM unit tests

---

pkg/agent/supportbundlecollection/support_bundle_controller.go
pkg/agent/supportbundlecollection/support_bundle_controller_test.go
pkg/controller/supportbundlecollection/controller.go
pkg/controller/supportbundlecollection/controller_test.go
pkg/util/auth/auth.go
pkg/util/auth/auth_test.go
pkg/util/sftp/ftp.go
pkg/util/sftp/ftp_test.go

moved from https://github.com/antrea-io/antrea/pull/6756#discussion_r1825202207
ftp file server package maybe shared by multiple controllers in the future, so move it to common pkg folder.

Move ftp file server code to common pkg

---

test/integration/agent/gobgp_test.go

For #6501
This commit simplifies the test to reduce failure potential and enables
debug logging for gobgp test to improve issue diagnosis.

Simplify gobgp integration test and set log level to debug

---

test/e2e/service_externalip_test.go

To avoid some rare failures.
Fixes #6783

Use non-overlapping IP ranges across e2e tests for ExternalIPPools

---

pkg/agent/controller/bgp/controller.go

Cherry pick of #6823 on release-2.2.
#6823: Fix race condition when getting BGP routes in BGPController

Automated cherry pick of #6823: Fix race condition when getting BGP routes in BGPController

---

ci/kind/kind-setup.sh

Fix the grep command in kind setup script
Fixes #6838.

Fix the grep command in kind setup script

---

ci/jenkins/test.sh

Fix Windows Conformance failure by updating time synchronization script

---

CONTRIBUTING.md
ci/jenkins/jobs/macros.yaml
ci/jenkins/jobs/projects-lab.yaml
ci/jenkins/test.sh
ci/kind/kind-setup.sh
ci/kind/test-e2e-kind.sh
test/e2e/fixtures.go
test/e2e/framework.go

Cherry pick of #5974 on release-2.1.
#5974: To support running Antrea Flexible IPAM tests on KIND (#5974)

Automated cherry pick of #5974: To support running Antrea Flexible IPAM tests on KIND (#5974)

---

docs/design/ovs-pipeline.md

Add table of contents and reorganize some sections.
Move sections about OVS registers and conntrack design to be under "OVS Registers and Conntrack".
Move sections that describe implementation of specific features to be under "Antrea Features".

Add table of contents to the OVS pipeline doc

---

build/charts/antrea/crds/packetcapture.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-crds.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml

Add 4 new columns:
- Captured-Packets
- Started
- Complete
- Uploaded
Captured-Packets, Started and Complete have priority 0 so they are displayed by default.

Add more printer columns for PacketCapture CRD

---

cmd/flow-aggregator/flow-aggregator.go
pkg/util/podstore/podstore.go
pkg/util/podstore/podstore_test.go

The PodStore is used to map a Pod IP to a specific Pod resource, taking into account time as a way to distinguish between Pods when an IP address is reused by the CNI.
This mapping is not applicable to hostNetwork Pods, as there will typically be multiple hostNetwork Pods on a given Node, and they will all "share" the same (host) IP. Therefore, we modify the PodStore implementation to ignore events for hostNetwork Pods.
Additionally, for the Flow Aggregator, we switch to a filtered informer, which will ignore hostNetwork Pods at the server level, and we trim Pods locally to reduce the overall memory footprint.

Ignore hostNetwork Pods in PodStore

---

test/e2e/framework.go
test/e2e/service_externalip_test.go

Fix test failure of ServiceExternalIP with LoadBalancerModeDSR

---

go.mod
go.sum
pkg/antctl/raw/featuregates/command_test.go
pkg/antctl/raw/multicluster/common/common_test.go
pkg/antctl/raw/multicluster/create/member_token_test.go
pkg/antctl/raw/multicluster/delete/member_token_test.go
pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
pkg/antctl/raw/multicluster/destory_test.go
pkg/antctl/raw/multicluster/get/clusterset_test.go
pkg/antctl/raw/multicluster/get/join_config_test.go
pkg/antctl/raw/multicluster/get/member_token_test.go
pkg/antctl/raw/multicluster/get/resourceexport_test.go
pkg/antctl/raw/multicluster/get/resourceimport_test.go
pkg/antctl/raw/multicluster/init_test.go
pkg/antctl/raw/multicluster/join_test.go
pkg/antctl/raw/multicluster/leave_test.go
pkg/antctl/raw/traceflow/command_test.go

`SetOutput` is deprecated, use `SetOut` and/or `SetErr` instead

Upgrade github.com/spf13/cobra to 1.9.1

---

docs/secondary-network.md
hack/.notableofcontents

For https://github.com/antrea-io/antrea/issues/7043

Document SecondaryNetwork support for SR-IOV

---

go.mod
go.sum
pkg/flowaggregator/exporter/ipfix.go

Update go-ipfix to v0.14.0

---

go.mod
go.sum
pkg/antctl/raw/featuregates/command_test.go
pkg/antctl/raw/multicluster/common/common_test.go
pkg/antctl/raw/multicluster/create/member_token_test.go
pkg/antctl/raw/multicluster/delete/member_token_test.go
pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
pkg/antctl/raw/multicluster/destory_test.go
pkg/antctl/raw/multicluster/get/clusterset_test.go
pkg/antctl/raw/multicluster/get/join_config_test.go
pkg/antctl/raw/multicluster/get/member_token_test.go
pkg/antctl/raw/multicluster/get/resourceexport_test.go
pkg/antctl/raw/multicluster/get/resourceimport_test.go
pkg/antctl/raw/multicluster/init_test.go
pkg/antctl/raw/multicluster/join_test.go
pkg/antctl/raw/multicluster/leave_test.go
pkg/antctl/raw/traceflow/command_test.go

Cherry pick of #7027 on release-2.3.
#7027: Upgrade github.com/spf13/cobra to 1.9.1 (#7027)

Automated cherry pick of #7027: Upgrade github.com/spf13/cobra to 1.9.1 (#7027)

---

ci/kind/kind-setup.sh
ci/kind/test-e2e-kind.sh

Support passing --flexible-ipam with dynamic action (create/destroy).

support passing --flexible-ipam with dynamic action (create/destroy)

---

test/e2e/packetcapture_test.go

fixes: #7063 
Added e2e test case for DestnationToSource direction of PacketCapture
Tested locally
```
=== NAME  TestPacketCapture
fixtures.go:523: Deleting 'testpacketcapture-f6c44b9n' K8s Namespace
I0314 15:14:18.195013    4965 framework.go:882] Deleting Namespace testpacketcapture-f6c44b9n took 3.568209ms
--- PASS: TestPacketCapture (111.84s)
--- PASS: TestPacketCapture/testPacketCaptureBasic (87.38s)
--- PASS: TestPacketCapture/testPacketCaptureBasic/testPacketCaptureBasic (0.00s)
--- PASS: TestPacketCapture/testPacketCaptureBasic/testPacketCaptureBasic/non-existing-pod (1.21s)
--- PASS: TestPacketCapture/testPacketCaptureBasic/testPacketCaptureBasic/ipv4-tcp-both (3.20s)
--- PASS: TestPacketCapture/testPacketCaptureBasic/testPacketCaptureBasic/ipv4-tcp (3.60s)
--- PASS: …
```

add e2e test for dst-to-src packet capture

---

pkg/agent/multicast/mcast_controller.go
pkg/agent/multicast/mcast_controller_test.go

Cherry pick of #7154 on release-2.3.
#7154: Remove stale local members in the group cache

Automated cherry pick of #7154: Remove stale local members in the group cache

---

build/charts/antrea/crds/ippool.yaml
build/yamls/antrea-aks.yml
build/yamls/antrea-crds.yml
build/yamls/antrea-eks.yml
build/yamls/antrea-gke.yml
build/yamls/antrea-ipsec.yml
build/yamls/antrea.yml
test/e2e/antreaipam_test.go

Make IPPool prefixLength and gateway immutable

---

pkg/agent/multicast/mcast_controller_test.go

The root cause of the flaky failure is one case is designed with multiple local members of a stale Multicast group. According to latest implementation, the mcast_controller will send IGMP leave event standing for all the local members one by one. And there exists two separate goroutines, eventHandler and worker. The worker may take different actions with the OpenFlow group according to the cached GroupMemberStatus in the runtime, e.g., 1. if there exists other local members (the event handler does not remove other stale local members) then the worker will re-install the OpenFlow group to update the local members, 2. if all local members are removed from the cache, the worker will un-install the OpenFlow group. Finally the OpenFlow group is removed.
To remove the flaky cases, this change …

[Multicast] Fix flaky failure in unit test case TestClearStaleGroups

---

ci/kind/kind-setup.sh

Reverting PR: #7190  changes to fix jenkins ci recent failure.
Later we will do the refactoring in separate PR: #7201.

Reverting PR 7190 changes to fix jenkins ci failure

---

pkg/agent/openflow/client.go
pkg/agent/openflow/pipeline.go

The logs provide visibility into packet drops by OVS meters, enabling users and developers to evaluate whether increasing the packetInRate configuration is needed.
Log example:
```
E0625 07:37:20.794697       1 client.go:1705] "Packets were dropped by OVS meter, please consider increasing the 'packetInRate' configuration" meter="PacketInMeterDNSInterception" packetInRate=500 totalDrops=200 newDrops=200
E0625 07:37:50.795050       1 client.go:1705] "Packets were dropped by OVS meter, please consider increasing the 'packetInRate' configuration" meter="PacketInMeterDNSInterception" packetInRate=500 totalDrops=400 newDrops=200
E0625 07:38:20.796004       1 client.go:1705] "Packets were dropped by OVS meter, please consider increasing the 'packetInRate' configuration" …
```

Log error when OVS meter drops packets

---

build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
build/yamls/antrea-windows-with-ovs.yml

Cherry pick of #7228 on release-2.2.
#7228: Enhance OVS commands for Antrea Windows (#7228)

Automated cherry pick of #7228: Enhance OVS commands for Antrea Windows (#7228)

---

ci/kind/kind-setup.sh

Docker network options `com.docker.network.bridge.gateway_mode_ipv4=nat-unprotected`
and `com.docker.network.bridge.gateway_mode_ipv6=nat-unprotected` are
not yet supported on macOS with Apple Silicon (arm64) when using Colima, as the
latest Colima v0.8.1 ships Docker Engine v27.4.0 (refer https://github.com/abiosoft/colima/releases).
These options require Docker 28.0.0 or later.
This change avoids setting these options when running on that platform, preventing
errors during Kind cluster setup.

Skip `nat-unprotected` option for Docker versions below 28.0.0

---

pkg/agent/secondarynetwork/podwatch/controller_test.go
pkg/agent/secondarynetwork/podwatch/sriov.go

If the SR-IOV device configuration fails after the device has been
assigned to the Pod, subsequent retries will also fail due to the device
being marked as unavailable. Improve the device assignment logic to
ensure the Pod can consistently get the correct device.
Resolves #7315

Improve SR-IOV device assignment to ensure it's idempotent

---

docs/antctl.md
pkg/agent/apis/types.go
pkg/agent/apiserver/handlers/bgppolicy/handler.go
pkg/agent/apiserver/handlers/bgppolicy/handler_test.go
pkg/agent/controller/bgp/controller.go
pkg/agent/controller/bgp/controller_test.go
pkg/antctl/antctl.go
pkg/querier/querier.go
pkg/querier/testing/mock_querier.go

Add confederation identifier in 'antctl get bgppolicy' response

---

pkg/agent/agent.go
pkg/agent/agent_test.go
test/e2e/antreaipam_test.go
test/e2e/connectivity_test.go

Cherry pick of #7389 on release-2.4.
#7389: Fix unexpected interface store initialization for

Automated cherry pick of #7389: Fix unexpected interface store initialization for

---

AGENTS.md

This document provides comprehensive guidelines and best practices for AI agents contributing to the Antrea project, including Go and Bash coding conventions, logging guidelines, git workflow, and project-specific requirements.
The document itself was generated using GenAI and edited by me.

Add AI agents development guidelines (AGENTS.md)

---

go.mod
go.sum
pkg/agent/cniserver/sriov_linux.go

The repo was migrated and the module name changed.

Replace Mellanox/sriovnet with k8snetworkplumbingwg/sriovnet

---

docs/antctl.md
pkg/agent/apis/types.go
pkg/agent/apiserver/handlers/bgppolicy/handler.go
pkg/agent/apiserver/handlers/bgppolicy/handler_test.go
pkg/agent/controller/bgp/controller.go
pkg/agent/controller/bgp/controller_test.go
pkg/antctl/antctl.go
pkg/querier/querier.go
pkg/querier/testing/mock_querier.go

Add memberASNs in 'antctl get bgppolicy' response
