pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_test.go, test/e2e/nodeportlocal_test.go
Currently we use container ports of a Pod to program iptables rules to make the Pod
reachable through a port in the Node. But container ports are not mandatory and multiple
services can use different target ports for the same pod. Hence adding a change in
NodePortLocal implementation, where target ports of all services would be used to
program iptables rules and annotate pods.
To implement this, target ports are being obtained from all the Services selecting a Pod,
in the function handleAddUpdatePod().
Necessary changes in the tests have been added.
Fixes #1912
=> Use target port of Service in NodePortLocal to configure Pod reachability

pkg/controller/egress/controller.go, pkg/controller/egress/controller_test.go
ipAllocatorMap was read without holding the mutex in syncEgressIP. This
patch fixes it and stabilizes the unit tests by waiting for cache sync
before starting creating objects. This is because resource creation
events will be missing if the resources are created in-between list and
watch call of an fake informer.
=> Fix race condition in EgressController and unit tests

pkg/apis/controlplane/v1beta1/conversion.go, pkg/apis/controlplane/v1beta1/conversion_test.go
Cherry pick of #2302 on release-1.1.
#2302: Fix MarshalJSON error caused by incorrect conversion function
=> Automated cherry pick of #2302: Fix MarshalJSON error caused by incorrect conversion function

pkg/legacyapis/controlplane/v1beta1/conversion.go, pkg/legacyapis/controlplane/v1beta1/register.go, pkg/legacyapis/networking/v1beta1/conversion.go
Cherry pick of #2305 on release-1.0.
#2305: Fix wrong types and missing field selectors in legacy APIs
=> Automated cherry pick of #2305: Fix wrong types and missing field selectors in legacy APIs

docs/design/ovs-pipeline.md, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/e2e/service_test.go, test/integration/agent/openflow_test.go
When AntreaProxy is disabled, if the reply traffic of a connection that
has been processed by iptables/ipvs rules (of kube-proxy) is received
from the tunnel interface, its destination MAC would be rewritten twice
because it would have both gatewayCTMark and macRewriteMark set. The
latter rewriting would overwrite the former one and would cause the
packets to be delivered to the destination Pod directly without doing
reversed NAT in the host netns.
This patch fixes it by making the pipeline rewrite the destination MAC
as most once. It moves the gatewayCTMark related MAC rewriting flow to
l3ForwardingTable, to make L3 forwarding decision in same table
uniformly. It also simplifies the two gatewayCTMark related flows by
matching the direction of traffic which ensures the flow doesn't apply …
=> Fix cross-Node service access when AntreaProxy is disabled

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/types/groupcounter.go
When dual stack is enabled, there will be IPv4 and IPv6 AntreaProxy. The IPv4
AntreaProxy and IPv6 AntreaProxy don't share the same GroupCounter. When a
IPv6 Service is created by IPv6 AntreaProxy, the GroupID generated may be
duplicated with a GroupID used by IPv4 Service. GroupCounter of IPv6 AntreaProxy
can start with 0x10000000 to avoid above issue.
=> Fix ovs group id conflict when dual stack is enabled

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/types/groupcounter.go
Cherry pick of #2317 on release-0.13.
#2317: Fix ovs group id conflict when dual stack is enabled
=> Automated cherry pick of #2317: Fix ovs group id conflict when dual stack is enabled

pkg/agent/cniserver/interface_configuration_windows.go
For docker on Windows, no HostComputeNamespace is created before calling CNI to add network configuration. But containerd would do it. If a HnsEndpoint is created without HostComputeNamespace, a default value "00000000-0000-0000-0000-000000000000" should be set. HCN API should return an Error if a HnsEndpoint is removed from host Namespace "00000000-0000-0000-0000-000000000000". Hence, we skip invocation of "hcn.RemoveNamespaceEndpoint" for docker case.
Fixes #2301
=> [Windows]Check HostNamespace value when removing HcnEndpoint

pkg/agent/cniserver/interface_configuration_windows.go
Cherry pick of #2306 on release-0.13.
#2306: [Windows]Check HostNamespace value when removing HcnEndpoint
=> Automated cherry pick of #2306: [Windows]Check HostNamespace value when removing HcnEndpoint

docs/design/ovs-pipeline.md, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/e2e/service_test.go, test/integration/agent/openflow_test.go
Cherry pick of #2318 on release-0.13.
#2318: Fix cross-Node service access when AntreaProxy is disabled
=> Automated cherry pick of #2318: Fix cross-Node service access when AntreaProxy is disabled

build/yamls/elk-flow-collector/logstash/ipfix.yml, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/ipfix/ipfix_intermediate.go, pkg/ipfix/testing/mock_ipfix.go, test/e2e/flowaggregator_test.go
In this commit, we fill the Pod labels information in flow records on the Flow Aggregator side.
Label information is necessary for network policy recommendation application and could also enhance usability on Kibana dashboard.
=> Add Pod labels infomation in flow records

pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/flowrecords/flow_records.go
This commit adds performance benchmarking for Flow Exporter. It evaluates Export() function under different number of conntrack connections, dying connections, idle records, deny connections and idle deny connections. A local server will receive the records and count number. CPU and memory profile is collected and visualized using pprof.
Also from benchmarking, we discovered and removed redundant calls like `GetNodeName()`, which is called every time when exporting a record and `ResetConnStatsWithoutLock`, which unnecessarily calls `NewConnectionKey` each time.
With fixes and changes in go-ipfix [v0.5.3](https://github.com/vmware/go-ipfix/releases/tag/v0.5.3) and redundant calls removal in this PR, we had following improvements:
Before:
```
BenchmarkExportConntrackConns   	  50	  21747542 …
```
=> Add performance unit test for Flow Exporter

pkg/controller/networkpolicy/mutate.go
Co-existence of `patchType` and `patch` is validated by [admissionreview](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/request/admissionreview.go#L67). In case of resource deletions (ACNP and ANP for now), there is usually no mutation needed, and no `patch` in AdmissionResponse as a result. Hence the `patchType` in such AdmissionResponse should not be set. 
This was not yet an issue in Antrea due to the fact that we do not register DELETE as a mutating webhook operation in Antrea manifest.
=> Only add patchType when there is a patch for mutating webhooks

ci/jenkins/jobs/projects.yaml
This e2e test is successful but the whole build reached the time limit of 120m.
https://jenkins.antrea-ci.rocks/view/antrea-core/job/antrea-e2e-for-pull-request/2806/consoleFull
=> [CI][e2e] Larger timeout for e2e

test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/service_test.go, test/e2e/upgrade_test.go
1. Use hostNetwork Pod to test Host-to-Service connection to avoid
relying on Nodes' ssh config.
2. Fail upgrade test if deploying new yaml fails.
3. Correct skip message when there is no Windows Nodes.
=> Improve e2e tests

docs/design/windows-design.md, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
When Egress enabled, extra flows will be added to L3Forwarding table,
one of which make the packets to local Pods jump to
L2ForwardingCalculation directly to prevent them from entering SNAT
table. However, it would also prevent the packets' MAC from being
rewritten even when they are marked as requiring it, which leads to
local Pods cannot access local Pods via their Services' ClusterIPs.
This patch fixes it by making the SNAT skipping flow apply to packets
that don't have macRewriteMark set only, with which all traffic to local
Pods will either be forwarded to L2ForwardingCalculation directly or be
MAC rewritten first before going to L2ForwardingCalculation if they are
required to do so. It also removes a flow in L3Forwarding table that
specially handles gatewayCT related traffic, which …
=> Fix intra-Node service access when both Egress and AntreaProxy is enabled

docs/design/windows-design.md, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Cherry pick of #2332 on release-1.0.
#2332: Fix intra-Node service access when both Egress and
=> Automated cherry pick of #2332: Fix intra-Node service access when both Egress and

ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh
* GC job allows more time for testbeds
* Larger timeout for whole-conformance test
=> [CI] Update timeout in GC & whole-conformance job

build/images/base/Dockerfile
We use '--no-same-owner' so that the files are extracted as the current
user (instead of as the user who created the archive).
Before:
```
abas-a01:base abas$ docker run -ti antrea/base-ubuntu:2.14.0 bash
root@99cd63fd5466:/# ls -l /opt/cni/bin/
total 50652
-rwxr-xr-x 1 root root   4246019 Aug 26  2020 bandwidth
-rwxr-xr-x 1 root root   3745368 Aug 26  2020 host-local
-rwxr-xr-x 1 root root   3566204 Aug 26  2020 loopback
-rwxr-xr-x 1 root root   3979034 Aug 26  2020 portmap
-rwxr-xr-x 1  502 staff 36322924 May 18 21:58 whereabouts
```
(502 is my UID on my work laptop, and I am the one who created & uploaded the archives)
After:
```
abas-a01:base abas$ docker run -ti antrea/base-ubuntu:2.14.0 bash
root@1078e02c805e:/# ls -l /opt/cni/bin/
total …
```
=> Fix whereabouts binary permission in antrea/base-ubuntu image

pkg/agent/flowexporter/connections/conntrack.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/exporter/exporter.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
- Flows are not getting expired as expected because of zero start time and the last export time is initialized as the start time. This commit fixes that bug by adding the current time as start time if it is zero when a new connection is added. Fixes: #1417 
- Idle flow export timeout is not configured properly in the e2e test. There is a bug in the test and this commit fixes that. This was introduced in PR: #1802. Ref: https://github.com/antrea-io/antrea/blame/main/test/e2e/framework.go#L572
- The expected number of records is not correct in Kind clusters as packet counters are not supported in conntrack entries for OVS userspace datapath. Flow exporter cannot send records after active timeout expiry as we cannot consider flows to be active without the statistics. Therefore, we expect …
=> Fix flakiness in Kind e2e flow aggregator tests

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller.yml, cmd/antrea-controller/controller.go, pkg/apiserver/apiserver.go, pkg/apiserver/handlers/webhook/validation_crd.go, pkg/controller/egress/controller_test.go, pkg/controller/egress/ipallocator/allocator.go, pkg/controller/egress/ipallocator/allocator_test.go, pkg/controller/egress/validate.go, pkg/controller/egress/validate_test.go
The webhook for Egress validates that the EgressIP must be within the IP
ranges of the ExternalIPPool if both are set.
The webhook for ExternalIPPool validates that the ExternalIPPool must
not shrink.
For #2128
=> Add validating webhooks for Egress and ExternalIPPool

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/ipfix/ipfix_intermediate.go, pkg/ipfix/testing/mock_ipfix.go, plugins/octant/go.sum, test/e2e/framework.go
This commit removes `originalExporterIPv4Address`, `originalExporterIPv6Address` and `originalObservationDomainId` from flow aggregator and related templates for these fields.
It also bumps go-ipfix to v0.5.4.
fixes #2336
=> [Flow Aggregator] Remove originalExporterAddress and originalObservationDomainId

pkg/agent/nodeportlocal/npl_agent_init.go
Otherwise the List method would log the following message when querying
Pods of a namespace in NPLController.getPodsFromService, and falls back
to slow search without index.
"can not retrieve list of objects using index : Index with name
namespace does not exist"
=> Add NamespaceIndex to podInformer of NPLController

docs/feature-gates.md
I forgot to update some columns when graduating the feature to Beta.
=> Fix outdated info in doc for NetworkPolicyStats feature gate

docs/egress.md, docs/feature-gates.md, docs/getting-started.md
=> Add user guide for Egress feature

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/options.go, docs/feature-gates.md, pkg/agent/nodeportlocal/k8s/annotations_test.go, pkg/agent/nodeportlocal/npl_agent_test.go, test/e2e/nodeportlocal_test.go
From 40000-41000 to 61000-62000, to avoid conflict with the default
ip_local_port_range on Linux. This may be a slighlty disruptive change
to users who rely on the NPL feature: NPL port mappings for all existing
Pods will be updated to use the new range. However, I consider this
acceptable and it's better to make this change while NPL is still an
Alpha feature. Note that this behavior is verified by an e2e test:
TestNPLChangePortRangeAgentRestart.
See #2381
=> Change default port range for NodePortLocal

cmd/antrea-controller/controller.go, pkg/controller/egress/controller_test.go, pkg/controller/grouping/controller.go, pkg/controller/grouping/controller_test.go, pkg/controller/grouping/group_entity_index.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
When initializing GroupEntityIndex, if there were more than 1000 events
need to send, adding more Pods or ExternalEntity would be pending with
the lock acquired because the channel was full and the Run method that
consumed the channel didn't start. The Run method ran after the
setInitialCounts method, which also needed to acquire the lock, hence
deadlock.
This patch fixes it by starting GroupEntityIndex's Run method
individually. To avoid similar issues in the future, it also removes
the need of acquiring the lock in setInitialCounts and HasSync methods.
Fixes #2378
=> Fix deadlock in initializing GroupEntityIndex with many groups

docs/antrea-network-policy.md, pkg/controller/networkpolicy/clusternetworkpolicy.go, test/e2e/antreapolicy_test.go, test/e2e/utils/anpspecbuilder.go, test/e2e/utils/cnpspecbuilder.go
This PR fixes #2380. When the From/To in ACNP ingress/egress rule is empty, there will be no clusterPeers or perNSPeers. However, a cluster level rule should still be created with peer being `matchAllPeer`, as defined:
```
NetworkPolicyPeer is supposed to match all addresses when it is empty and no clusterGroup is present.
It's treated as an IPBlock "0.0.0.0/0".
```
This PR also adds E2E testcase for this specific scenario and updates the doc to inform user of this usage.
Thanks to @tnqn for raising this issue.
=> Fix ACNP incorrectly process rules with no From/To in rules

docs/feature-gates.md, pkg/agent/nodeportlocal/k8s/npl_controller.go
And document the restriction that only TCP is supported.
See #2395
=> Ignore non-TCP Service ports in the NodePortLocal implementation

CONTRIBUTING.md
The initial idea was that contributors would add an entry to the
"Unreleased" section of the CHANGELOG for every significant change
contributed to the project. This would have simplified release
management. However, this is an error-prone process and we never
actually implemented it. Instead we should look into auto-generating the
CHANGELOG for each release based on PR descriptions (see #2411).
=> Remove CHANGELOG update step from contribution instructions

docs/network-flow-visibility.md
This commit updated flow visibility documentation for removed fields `originalExporterIPv4Address` and `originalObservationDomainId`.
fixes #2398
=> Document update for removed elements in Flow Exporter

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, .github/workflows/netpol_cyclonus.yml, test/e2e/fixtures.go, test/e2e/framework.go
1. Update kind to v0.11.1
2. Export logs if setupTest fails
3. Include kube-proxy logs in the exported logs
For #2407
I plan to backport this patch to release 0.13~1.1 to bump their kind version and improve log collection. There was no way to figure out what caused #2407 without fetching the kube-proxy logs after setUp failed.
=> Improve e2e tests on kind clusters

pkg/controller/grouping/controller.go
There is a known bug in sync/atomic when using 64-bit atomics on a
32-bit architecture (e.g. ARM). As a result precautions must be taken to
guarantee correct alignment of the uint64 value.
Fixes #2413
=> Fix usage of uint64 atomics in Antrea Controller

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, .github/workflows/netpol_cyclonus.yml, test/e2e/fixtures.go, test/e2e/framework.go
Cherry pick of #2408 on release-0.13.
#2408: Improve e2e tests on kind clusters
=> Automated cherry pick of #2408: Improve e2e tests on kind clusters

go.mod, go.sum, pkg/agent/agent_windows.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/util/net_windows.go, pkg/agent/util/powershell/powershell_windows.go, pkg/agent/util/winfirewall/winfirewall.go, plugins/octant/go.sum, test/integration/agent/net_test_windows.go
Cherry pick of #2363 on release-0.13.
#2363: RunCommand with os/exec * Use "os/exec" to run
=> Automated cherry pick of #2363: RunCommand with os/exec * Use "os/exec" to run

build/yamls/elk-flow-collector/elk-flow-collector.yml, build/yamls/elk-flow-collector/logstash/logstash.conf, docs/network-flow-visibility.md
Previously we do not support tcp transport for elk flow collector because template expiration is set by default for tcp transport, which does not align with IANA standard. 
Now we set expiration for templates from tcp to 365 days as workaround to provide support for tcp transport.
=> Support TCP transport for elk flow collector

pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/flowrecords/flow_records.go, pkg/agent/flowexporter/types.go
Deadlock is due to the access of connection map from exporter goroutine waiting to acquire connection map lock to update the "DoneExport" flag of the stored connection. At the same time, the connection polling goroutine acquires the connection map lock waiting to acquire flow record map, which is acquired by the exporter goroutine. 
This was caught in scale testing.
Resolved this through a temporary fix by adding the same flag in the flow record data struct. 
The connection and record deletion logic will be re-evaluated through PR #2360 as it refactors the related code quite a bit.
=> Fix the deadlock between the exporter and the conntrack polling go routines

build/yamls/elk-flow-collector/logstash/filter.rb, pkg/agent/flowexporter/connections/conntrack_connections.go
This PR fixes throughput divided by 0 issue happened in Logstash. 
Since we introduce `conn.StartTime.IsZero()` check and update StartTime to `time.Now()` in previous fix https://github.com/antrea-io/antrea/pull/2308, there are chances that `StartTime` will be equal or later than `StopTime`, which may cause incorrect throughput calculation or exception (divided by 0) in Logstash. And we will miss some flow records on Kibana due to this exception when the flow duration is quite short (less than 1 second)
=> [Flow Aggregator] Fix throughput calculation in Logstash

build/yamls/elk-flow-collector/logstash/filter.rb, pkg/agent/flowexporter/connections/conntrack_connections.go
Cherry pick of #2432 on release-1.2.
#2432: Fix throughput calculation in Logstash
=> Automated cherry pick of #2432: Fix throughput calculation in Logstash

pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/flowrecords/flow_records.go, pkg/agent/flowexporter/types.go
Cherry pick of #2429 on release-1.2.
#2429: Fix the deadlock between exporter and conntrack polling goroutines
=> Automated cherry pick of #2429: Fix the deadlock between exporter and conntrack polling goroutines

docs/antrea-network-policy.md, pkg/controller/networkpolicy/clusternetworkpolicy.go, test/e2e/antreapolicy_test.go, test/e2e/utils/anpspecbuilder.go, test/e2e/utils/cnpspecbuilder.go
Cherry pick of #2383 on release-1.1.
#2383: Fix ACNP incorrectly process rules with no from/to in
=> Automated cherry pick of #2383: Fix ACNP incorrectly process rules with no from/to in

cmd/antrea-controller/controller.go, pkg/controller/egress/controller_test.go, pkg/controller/grouping/controller.go, pkg/controller/grouping/controller_test.go, pkg/controller/grouping/group_entity_index.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go
Cherry pick of #2376 on release-1.0.
#2376: Fix deadlock in initializing GroupEntityIndex with many
=> Automated cherry pick of #2376: Fix deadlock in initializing GroupEntityIndex with many

test/e2e/antreapolicy_test.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/batch_test.go, test/e2e/connectivity_test.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/legacyantreapolicy_test.go, test/e2e/networkpolicy_test.go, test/e2e/nodeportlocal_test.go, test/e2e/proxy_test.go, test/e2e/service_test.go, test/e2e/traceflow_test.go, test/e2e/upgrade_test.go
In the most cases of e2e tests, we implicitly set namespace to `testNamespace` while we create Pods. And we then we make call to `podWaitForRunning(defaultTimeout, podName, testNamespace)` for example, which makes it unintuitive of the occurrence of `testNamespace` here. So we decide to make namespace as a parameter when we create Pods.
Fixes: #2249
=> Explicitly use testNamespace in creating Pods for e2e tests

go.mod, go.sum, pkg/agent/util/iptables/iptables.go, plugins/octant/go.sum
ListChains was used to check if a chain exists. The method
used "iptables -t TABLE -S" to list all rules and filter chains from
the output. If there are massive iptables chains and rules configured,
it would cause a lot of space allocated.
benchmark comparison (with 15K iptables rules configured for 1000
services, each of which has 3 endpoints):
```
name            old time/op    new time/op    delta
EnsureChain-48    78.2ms ± 3%    27.0ms ± 1%  -65.43%  (p=0.008 n=5+5)
name            old alloc/op   new alloc/op   delta
EnsureChain-48    6.06MB ± 0%    0.01MB ± 0%  -99.84%  (p=0.016 n=4+5)
name            old allocs/op  new allocs/op  delta
EnsureChain-48     4.16k ± 0%     0.04k ± 0%     ~     (p=0.079 n=4+5)
```
For #2457
=> Use ChainExists to reduce memory footprint

go.mod, go.sum
In https://github.com/antrea-io/antrea/pull/2452, I made a typo and used
v0.18.19 (which is the upstream release) instead of v0.18.19-1 (which is
the Antrea-specific release with Quan's patch).
=> Fix invalid client-go version

.github/workflows/update_ovs_image.yml, build/images/Dockerfile.build.coverage, build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu, build/images/base/Dockerfile, build/images/flow-aggregator/Dockerfile, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/apply-patches.sh, build/images/test/Dockerfile, ci/jenkins/test-vmc.sh, ci/jenkins/test.sh, docs/troubleshooting.md
Cherry pick of #2451 on release-0.13.
#2451: Update OVS version from 2.14.0 to 2.14.2
=> Automated cherry pick of #2451: Update OVS version from 2.14.0 to 2.14.2

pkg/util/runtime/runtime_linux.go, pkg/util/runtime/runtime_linux_test.go
Check kernel version splitted array length and intercept the first 3 elements for parsing kernel version.
Fixes #2449 
Signed-off-by: Zhengdong Wu <zhengdong.wu@transwarp.io>
=> Fix invalid prerelease characters when parse kernel version

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/support_request.md
update issue template descriptions as html comments so it won't show up in preview
which means user can leave it as default without removing them manually
=> use html comments for issue templates

docs/api.md, docs/versioning.md
* Update table of supported APIs to reflect the changes in Antrea v1.0
(all CRDs to defined in the same API group). We can now track
versioning of indvidual CRDs independently.
* Provide guidelines on which version to use when introducing new CRDs.
=> Update API versioning documentation

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/openflow/network_policy.go
In events where the batch NetworkPolicy rule installation fails after Antrea agent restart (which could be caused by agent Node slowness leading to OVS bundle commit timeout), the global conjunction cache of the Antrea agent should be reverted to empty, so as to keep in sync with the actual state of the OVS tables.
The cache needs to be updated during the flow change calculation step of batch-rule install: since the flow add/mod/del calculation logic is incremental, calculation of flows changes resulted from adding a later rule depends on the state of existing flows created by previous rules, even though they have not been sent to the datapath for realization.
Test done:
Manually set `sendConjunctiveFlows` fails for the batch rule install case. Observed that after the batch rule …
=> Revert policy conjunction cache when batch rule reconciliation fails

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, docs/assets/windows_external_traffic.svg, docs/design/windows-design.md, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/types/annotations.go, pkg/agent/util/net.go, pkg/agent/util/net_windows.go, test/integration/agent/route_test.go
1. SNAT is performed by Windows host for Pod-to-external traffic, not by OVS
2. Antrea Agent uses the configurable interface for Pod traffic. The interface
which is configured with Node IP is chosen, if user doesn't configure the
in-band traffic interface.
Fixes #2344
=> Support configurable interfaces for Pod traffic across Node

pkg/agent/stats/collector.go, pkg/agent/stats/collector_test.go
The process would panic when it calculates stats of a rule that is newly
added to an existing NetworkPolicy and the stats is zero.
Fixes #2494
=> Fix panic in stats.calculateRuleDiff

CHANGELOG/CHANGELOG-0.x.md, CHANGELOG/CHANGELOG-1.0.md
Before the 1.1 release train, CHANGELOG updates to release branches for new
patch releases are not committed automatically to main.
=> Update CHANGELOGs for 0.13.3, 0.13.4, 0.13.5 and 1.0.2

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/util/ip/ip.go
BatchInstallPolicyRuleFlows first generates all flows then installs them
via single bundle. However, it generates the flows incrementally. If an
address is shared by multiple rules, intermediate flows will be
generated, for instance:
expected flow:
```
add "nw_dst=10.128.119.108 actions=conjunction(64,2/2),conjunction(65,2/2),conjunction(66,2/2)"
```
actual flows:
```
add "nw_dst=10.128.119.108 actions=conjunction(64,2/2)"
mod "nw_dst=10.128.119.108 actions=conjunction(64,2/2),conjunction(65,2/2)"
mod "nw_dst=10.128.119.108 actions=conjunction(64,2/2),conjunction(65,2/2),conjunction(66,2/2)"
```
The number of flows for this address will be same as the number of the
actions. The number of actual actions in these flows will be O(N^2),
N=number of desired actions. This increases CPU and …
=> Improve NetworkPolicy batch installation

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/apis/controlplane/sets.go, pkg/apis/controlplane/v1beta1/sets.go, pkg/apis/controlplane/v1beta2/sets.go, pkg/controller/egress/store/egressgroup.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/store/appliedtogroup.go
When getting the union of multiple AddressGroups or AppliedToGroups,
agent used the GroupMemberSet.Union method, which always creates an
intermediate set and copies the original items when merging another
set. This wasted significant time and memory when the groups had
massive members. This patch adds the GroupMemberSet.Merge method which
avoids the above overhead.
benchmark comparison when merging two groups with 10K members and 100
members:
```
name                            old time/op    new time/op    delta
RuleCacheUnionAddressGroups-48    4.27ms ±15%    2.15ms ±15%  -49.72%  (p=0.008 n=5+5)
name                            old alloc/op   new alloc/op   delta
RuleCacheUnionAddressGroups-48    1.95MB ± 0%    0.97MB ± 0%  -50.00%  (p=0.008 n=5+5)
name                            old …
```
=> Use GroupMemberSet.Merge to reduce CPU usage and memory footprint

ci/jenkins/test.sh, docs/windows.md, hack/windows/Helper.psm1, hack/windows/Prepare-Node.ps1, hack/windows/Prepare-ServiceInterface.ps1
* Mkdir kube-proxy log path before installation as a Service
Otherwise kube-proxy Service may not work well.
* Updated asset links from kubernetes-sigs/sig-windows-tools repo
* Retry for Get-WebFileIfNotExist
* Have cleaner environment for docker (stop, remove docker.pid, start)
* Start Antrea Windows agent in Daemonset way for Windows NetworkPolicy test
Currently the script way leads to many flaky failures
* Skip SCTP test for Windows NetworkPolicy tests since it requires privilege mode
which is not available on Windows Node
* Force date sync after Windows VM is reverted to a snapshot
=> [Windows] Update Windows instructions

ci/kind/test-upgrade-antrea.sh
The script should not consider minor releases which predate the
"current" version (which we can retrieve from the top-level VERSION
file).
=> Fix test-upgrade-antrea.sh script so it can be used in release branches

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/apis/controlplane/sets.go, pkg/apis/controlplane/v1beta1/sets.go, pkg/apis/controlplane/v1beta2/sets.go, pkg/controller/egress/store/egressgroup.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/store/appliedtogroup.go
Cherry pick of #2467 on release-1.2.
#2467: Use GroupMemberSet.Merge to reduce CPU usage and memory
=> Automated cherry pick of #2467: Use GroupMemberSet.Merge to reduce CPU usage and memory

go.mod, go.sum, pkg/agent/util/iptables/iptables.go, plugins/octant/go.sum
Cherry pick of #2458 on release-1.2.
#2458: Use ChainExists to reduce memory footprint
=> Automated cherry pick of #2458: Use ChainExists to reduce memory footprint

build/images/scripts/start_ovs_netdev, ci/kind/kind-setup.sh, ci/kind/test-e2e-kind.sh
When deploying Antrea on a IPv6 KinD cluster the cluster become unreachable due to missing IPv6 address on the br-phy device.
1. Create a cluster config for IPv6
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
disableDefaultCNI: true
ipFamily: ipv6
nodes:
- role: control-plane
- role: worker
- role: worker
```
1. Create the KinD cluster: `kind create cluster --config ./cluster-config.yaml`
1. Fix kind networking: `kind get nodes | xargs ./hack/kind-fix-networking.sh`
1. Deploy Antrea: `kubectl apply -f https://github.com/antrea-io/antrea/releases/download/v1.1.1/antrea-kind.yml`
1. Eventually, during antrea pod init, `kubectl get pods -A` responds with: `Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get pods)` …
=> support ipv6 kind clusters

ci/kind/test-upgrade-antrea.sh
Cherry pick of #2487 on release-1.2.
#2487: Fix test-upgrade-antrea.sh script so it can be used in
=> Automated cherry pick of #2487: Fix test-upgrade-antrea.sh script so it can be used in

pkg/agent/openflow/client.go
It was observed that installing a bundle took around 1~3ms. In
InstallEndpointFlows, agent created a bundle for each Endpoint and
installed them sequentially. If there are many Services and Endpoints,
it could take long time to install flows in this fashion when agent
restarts. For instance, it took ~78s to install all flows for 4K
Services and 28K Endpoints.
This patch uses single bundle for all Endpoint flows belong to a Service
to reduce the number of bundles. In the above scale, the execution time
was reduced from ~78s to ~30s.
=> Install all Endpoint flows belong to a Service via single bundle

pkg/agent/stats/collector.go, pkg/agent/stats/collector_test.go
Cherry pick of #2495 on release-1.2.
#2495: Fix panic in stats.calculateRuleDiff
=> Automated cherry pick of #2495: Fix panic in stats.calculateRuleDiff

.github/workflows/kind.yml, ci/kind/test-e2e-kind.sh, hack/tidy-check.sh, test/e2e/antctl_test.go, test/e2e/antreapolicy_test.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/batch_test.go, test/e2e/clustergroup_test.go, test/e2e/connectivity_test.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/ipsec_test.go, test/e2e/legacyantreapolicy_test.go, test/e2e/legacyclustergroup_test.go, test/e2e/main_test.go, test/e2e/networkpolicy_test.go, test/e2e/nodeportlocal_test.go, test/e2e/prometheus_test.go, test/e2e/proxy_test.go, test/e2e/security_test.go, test/e2e/supportbundle_test.go, test/e2e/tls_test.go, test/e2e/traceflow_test.go
A few areas to reduce e2e overall time:
1. add t.Parallel() for those tests with multiple test data.
2. use subtest to reorganize most e2e test files so they can share the same setup/teardown.
3. add `skipIfNotRequired` method to allow user to skip cases with provided key word.
4. set some cases as default cases which will not be impacted by encap/noencap/hybird mode via method `skipIfNotRequired` with skip keyword "mode-irrelevant-case",  and execute them in " E2e tests on a Kind cluster on Linux" only and remove them from below jobs with option '--skip-mode-irrelevant'
* E2e tests on a Kind cluster on Linux with AntreaProxy disabled
* E2e tests on a Kind cluster on Linux (noEncap)
* E2e tests on a Kind cluster on Linux (hybrid)
* E2e tests on a Kind cluster on Linux with Antrea-native …
=> Reduce e2e overall time

pkg/controller/networkpolicy/validate.go, test/e2e/antreapolicy_test.go, test/e2e/clustergroup_test.go, test/e2e/legacyclustergroup_test.go
This is the first of two PRs that relaxes admission validations for ClusterGroup references. This PR removes the restriction that a child ClusterGroup must exist before it can be referred to as `childGroup` in other ClusterGroups. With this change, the effective member of a nested ClusterGroup will be calculated as the union of its childGroup members, for each childGroup that exist in the cluster.
Note that this PR does not change the max nested level of ClusterGroups, which is 1 at the moment. This means that any ClusterGroup that has a parent cannot be a nested ClusterGroup itself; and reversely, a ClusterGroup cannot select another nested ClusterGroup as its `childGroup`. This is validated upon creation/update of a ClusterGroup. The order of events matter in this case, as any update …
=> Remove child group existence validation for ClusterGroup

.github/workflows/clair.yml, .github/workflows/go.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
Closes #2514
Changes `actions/setup-go@v1` to `actions/setup-go@v2` in all workflows.
=> Use actions/setup-go@v2 in all workflows

cmd/flow-aggregator/flow-aggregator.go
Periodic deletion of log files is missing in the Flow Aggreegator.
This logic periodically deletes extra files by making sure that max
number of files to be 4. This will ensure that no disk space is wasted
on the Kubernetes node running the Flow Aggregator.
This logic was missed initially when the logging in the Flow Aggregator is
added in the beginning adopting the same framework as the Antrea Agent and the
Antrea Controller.
Signed-off-by: Srikar Tati <stati@vmware.com>
=> Log maintenance bug fix in the Flow Aggregator

cmd/flow-aggregator/flow-aggregator.go
Cherry pick of #2522 on release-1.2.
#2522: Log maintenance bug fix in the Flow Aggregator
=> Automated cherry pick of #2522: Log maintenance bug fix in the Flow Aggregator

docs/kubernetes-installers.md
Somehow the line wrapping is breaking the HTML rendering by
Redcarpet. This is strange since I don't think I have noticed this issue
with other links. Since we are switching to a different stack for the
antrea.io website, I just want to fix the issue, without doing too much
digging.
Fixes #2518
=> Fix link in kubernetes-installers.md

.github/workflows/go.yml
We cache downloaded Go modules and the Go build cache. The cache is
OS-specific. See
https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
=> Use Github workflow cache for Go CI builds

test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/main_test.go, test/e2e/networkpolicy_test.go
* Remove unused 'antreaNamespace' parameters in getFeatures related methods
* Check length of 'bwSlice'
* Move 'AntreaConfigMap' to framework.go
* Improve Pod name in networkpolicy_test.go
=> [e2e] Several improvement

cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/connections/deny_connections_test.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/flowrecords/flow_records.go, test/integration/agent/flowexporter_test.go
If flows are not exported to any collector, we do not clear the connections
in the connection store. This is applicable to both conntrack and deny
connections. This will increase the memory usage in the Antrea agent linearly.
Added goroutines that clean up connections if they are stale for more than 5 minutes (stale timeout)
after the last export. We also error out if `activeTimeout` and `idleTimeout` are more than stale connection timeout (constant 5 mins. value).
=> [Bug fix]Connections are not deleted properly in Flow Exporter when they are not exported

docs/egress.md, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, test/e2e/egress_test.go
Update Egress status when configuring a static Egress.
For example:
Create an `Egress` resources, assign EgressIP field and the EgressIP has been assigned to Node 'kind-worker' manually.
```yaml
kind: Egress
metadata:
name: egress-web-ipv4
spec:
appliedTo:
podSelector:
matchLabels:
role: web
namespaceSelector:
matchLabels:
env: prod
egressIP: 10.10.10.10
```
List the `Egress` resource with kubectl.
```yaml
NAME                 EGRESSIP       AGE   NODE
egress-web-ipv4      10.10.0.10     1m    kind-worker
```
It is an additional PR for #2186, and makes the Egress status more user friendly.
=> Update Egress status when configuring static Egress

pkg/agent/nodeportlocal/npl_agent_test.go, pkg/agent/nodeportlocal/portcache/port_table.go, pkg/agent/nodeportlocal/rules/iptable_rule.go, pkg/agent/nodeportlocal/rules/rules.go, pkg/agent/nodeportlocal/rules/testing/mock_rules.go, pkg/agent/route/route_linux.go, pkg/agent/util/iptables/iptables.go
* bug fix in EnsureRule()
* refactor iptables methods
=> [IPv6] Bug fix in adding iptable rules

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
In large-scale clusters, it may take 40~50 seconds for antrea-agent to
reconnect to antrea service after antrea-controller restarts.
antrea-agent shouldn't be reported as NotReady in this scenario,
otherwise DaemonSet controller would restart them at once, as opposed
to rolling update. Set failureThreshold to 8 so it can tolerate 70s of
disconnection.
Fixes #2534
The purpose of antrea-agent's readiness probe is to make the status of antrea-agent visible, e.g. the connection with antrea-controller, and it's not for service loadbalancing/failover. So it should be fine to be less aggressive to update its ready status.
=> antrea-agent readiness probe tolerates longer disconnection

cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/connections/deny_connections_test.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/flowrecords/flow_records.go, test/integration/agent/flowexporter_test.go
Cherry pick of #2516 on release-1.2.
#2516: Bug fix in Flow Exporter related deletion of connections
=> Automated cherry pick of #2516: Bug fix in Flow Exporter related deletion of connections

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
Cherry pick of #2535 on release-1.2.
#2535: antrea-agent readiness probe tolerates longer disconnection
=> Automated cherry pick of #2535: antrea-agent readiness probe tolerates longer disconnection

test/e2e/infra/vagrant/playbook/roles/common/tasks/docker.yml, test/e2e/infra/vagrant/playbook/roles/common/templates/docker.json.j2
In the playbooks, we always use the latest available version of K8s. K8s
v1.22 was just released, and one of the included changes was preventing
the Vagrant-based cluster from being provisioned successfully.
See https://github.com/kubernetes/kubernetes/pull/99647
This change requires us to configure the systemd cgroup explicitly for
Docker, or kubelet will refuse to run.
=> Fix Ansible playbooks (Vagrant test infra) for K8s 1.22

pkg/flowaggregator/flowaggregator.go
fixes https://github.com/vmware/go-ipfix/issues/235
`fa.templateIDv4` and `fa.templateIDv6` are not assigned with any value when first exporting the template records, which caused sanity check not getting passed when sending first record. 
```
E0804 17:01:13.684657 1 flowaggregator.go:392] Error when sending expired flow records: callback execution failed for popped flow record with key: &{10.10.0.1 10.10.1.7 6 48022 4739}, record: &{0xc0002e9aa0 0xc00007a8c0 true 0 true true true}, error: error when doing sanity check:process: templateID 256 does not exist in exporting process
```
This PR fixes issue above by assign template ID before exporting templates.
=> [Flow Exporter] Fix missing template when sending first record

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/agent/util/net.go
the purpose of this commit is to fix a tunnel interface issue founded during some IPSec PoC verification:
1. when the node name is like 'lan-k8s-0-0', the IPsec tunnel interface name will be
like '-k8s-0-2-e8dbe6', then it will failed to run command like
`ipsec up '-k8s-0-2-e8dbe6'` inside a Antrea agent with error `/usr/lib/ipsec/stroke: invalid option -- 'k'`
due to the first char is '-', ipsec command interrupted it as an
option. so changed the `generateInterfaceName` method to use `strings.TrimLeft()` to remove '-' in left.
2. `createIPSecTunnelPort` method can't handle the case when tunnel
interface name changed when there is cache matched for the node. it
will reuse the existing tunnel name without creating a new one with new
name which means any change in `generateInterfaceName` …
=> fix tunnel interface name issue

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_init.go, pkg/agent/nodeportlocal/npl_agent_test.go, pkg/agent/nodeportlocal/portcache/port_table.go
Add a retry mechanism in the Controller initialization, which will keep
trying to sync iptables rules until the operation is successful. On
success, the NPL Controller is notified through a channel and can start
its event handlers.
Fixes #2554
=> Handle iptables-restore failures correctly in NPL Controller

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_init.go, pkg/agent/nodeportlocal/npl_agent_test.go, pkg/agent/nodeportlocal/portcache/port_table.go
Cherry pick of #2555 on release-1.2.
#2555: Handle iptables-restore failures correctly in NPL
=> Automated cherry pick of #2555: Handle iptables-restore failures correctly in NPL

.github/dependabot.yml, .github/workflows/dependabot.yml
We enable Dependabot, which will automatically open PRs to update
dependencies (mainly go modules, but also Github actions). Some
troublesome dependencies are explicitly ignored and for some
dependencies (k8s.io modules), we only consider patch updates.
To ensure that the PR tidiness check will succeed for Dependabot PRs, we
add a new workflow which will run "make tidy" when Dependabot opens a PR
and which will commit the resulting changes to the source branch. While
Dependabot does run "go mod tidy" automatically (currently using Go
1.16), that would not be sufficient for updating plugins/octant/go.sum.
The workflow uses pull_request_target as a trigger. This can lead to
security vulnerabilities when checking-out arbitrary code. Therefore, we
ensure that the job only runs for Dependabot …
=> Automate Go module dependency updates with Dependabot

multicluster/Makefile, multicluster/config/crd/bases/multicluster.crd.antrea.io_clustersets.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml, multicluster/config/default/kustomization.yaml, multicluster/config/manager/manager.yaml, multicluster/config/multi-cluster.yaml
1. remove namespace in config/manager/manager.yaml, so we won't have
a `kube-system` namespace definition in multi-cluster.yaml
2. use `KUSTOMIZE = $(shell pwd)/bin/kustomize` in Makefile,
otherwise,it will do nothing if KUSTOMIZE is empty by `shell which kustomize`
3. add a common label `app: antrea` for all resources
4. other changes are auto-generated by `make manifests`
=> remove namespace creation

test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go, test/e2e/legacyantreapolicy_test.go, test/e2e/reachability.go
Previously, if there are multiple ports in `testStep`, `executeTestsWithData` will call `k8sUtils.Validate` for each port. In this case, when we call `step.Reachability.Summary()` to get the result, the data in `step.Reachability` is just what we observed from the last port, which is not what we want.
This PR makes `Validate` and `Probe` functions take multi-port instead of a single port as one of its parameters. The connectivity should be:
1. If the connectivities on all ports are the same, the connectivity from `fromPod` to `toPod` is this connectivity.
2. If the connectivities on all ports are not the same, the connectivity from `fromPod` to `toPod` is Error.
=> [Bug Fix] Change e2e test multi-port probe logic

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go
This PR fixes issue #2548 
This PR added some bypass flows in the ingress and egress table to make sure reject responses won't be enforced by network policies.
**Why we need it**
Previously, reject responses are controlled by network policies, which means that reject responses could also be rejected. It may cause an infinite loop of rejecting reject responses in the OVS pipeline. 
Instead of `Reject` reject response, now we choose to `Allow` the reject responses.
**Added Flows**
```
table=45/50/60/85/90/100, priority=64990,ct_state=-new+rel,ip actions=resubmit(,61/101)
table=45/50/60/85/90/100, priority=64990,ip,reg0=0x2000000/0x7000000 actions=resubmit(,61/101)
```
**Example**
Suppose we have:
* PodA on NodeA
* PodB on NodeB
* PolicyA: appliedTo: PodA,  ingress: Reject from PodB
* …
=> [Bug Fix]Fix infinite rejection loop by adding ingress/egress bypass flows

docs/antrea-network-policy.md
Add note regarding how to use the Namespace by Name feature in K8s and Antrea-native network policies depending on the
K8s version.
Signed-off-by: abhiraut <rauta@vmware.com>
=> Update Antrea-native policy doc for Namespace labels

docs/antrea-network-policy.md
DNS requests are of both UDP and TCP. When testing the AllowToCoreDNS Rule I was running into issues with wget and nslookup not resolving from within a pod by adding in a second port and protocol combo this was resolved. This update should make for it clearer how to expose dns to end users while the old example technically still worked it would not permit all dns traffic.
Signed-off-by: Brian Rieger <brieger@vmware.com>
=> Update AllowToCoreDNS rule to permit udp on port 53

docs/design/ovs-pipeline.md, pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/openflow/client.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_windows.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_builder_test.go, pkg/ovs/openflow/ofctrl_flow_test.go, pkg/ovs/openflow/ofctrl_group.go, pkg/ovs/openflow/ofctrl_nxfields.go, pkg/ovs/openflow/ofctrl_packetout.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go, test/integration/ovs/ofctrl_test.go
1. Use RegMark/RegField in OpenFlow Match or Load actions instead of passing the register ID and range.
2. The usage for OVS registers(including xxreg) should be predefined in regmarks.go.
3. Use reg0[0..3] to indicate the source of packet, and release reg0[4..15] for other usages.
=> Provide generic API for OVS register match/set value

pkg/antctl/antctl.go, pkg/antctl/command_definition.go
Previous to this change, the flag was only supported in "Controller
mode". This was a bit confusing when running "antctl get networkpolicy"
from the Agent Pod, because 1) the option shows in the examples from the
help message, and 2) the documentation doesn't make it clear that this
flag only works in "Controller mode".
Rather than update the documentation and add complexity in the help
message, I am adding support for that flag in "Agent mode". There
doesn't seem to be any reason not to.
=> Support --sort-by flag for "antctl get networkpolicy" for Agent

pkg/antctl/raw/supportbundle/command.go
=> Support return partial results for supportbundle when some nodes fails

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, docs/design/architecture.md, docs/ipsec-tunnel.md
I was trying to enable IPSec with VxLAN tunnel, after verify the traffic in real cluster, it turns out Antrea can actually support all tunnel modes now without much code changes. 
I verified all tunnel modes with IPSec in a local Cluster, it all works fine now, so I remove the limitation on our docs and the check in the code.
resolves #2468
=> Remove IPSec tunnel limitation

ci/kind/test-e2e-kind.sh, cmd/flow-aggregator/flow-aggregator.go, pkg/flowaggregator/flowaggregator.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
When we delete flow aggregator manifests, closing signal does not get passed to flow aggregator to close collecting process and aggregation process before main function exits. Last log (verbose=4) shown in flow aggregator when closing is like:
```
I0719 21:16:56.474762       1 reflector.go:225] Stopping reflector *v1.Pod (12h0m0s) from pkg/mod/k8s.io/client-go@v0.21.0/tools/cache/reflector.go:167
I0719 21:16:56.474949       1 flow-aggregator.go:121] Stopping flow aggregator
rpc error: code = Unknown desc = Error: No such container: dafd2b659ffba89e5170d75072f24fb3f2dcfe33a4c61981cf153ffd6653fb98%
```
There should be logs for closing collecting process https://github.com/vmware/go-ipfix/blob/main/pkg/collector/process.go#L111 but not, which means that collecting process is not closed …
=> Resolve flow aggregator close issue

hack/.md_links_config.json
We get a 503 (Service Unavailable) pretty often and it does seem the
website is down from time to time. To avoid CI failures, we explicitly
exclude this link.
=> Stop checking https://nssm.cc/ in markdown link checker

ci/kind/test-e2e-kind.sh, cmd/flow-aggregator/flow-aggregator.go, pkg/flowaggregator/flowaggregator.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
Reverts antrea-io/antrea#2431
@zyiou I'm reverting this PR because I see a large number of failures for the new test, on both Kind and Jenkins testbeds
```
=== RUN   TestFlowAggregator/IPv4/RestartFlowAggregator
flowaggregator_test.go:510: 
Error Trace:	flowaggregator_test.go:510
Error:      	Received unexpected error:
timed out waiting for the condition
Test:       	TestFlowAggregator/IPv4/RestartFlowAggregator
fixtures.go:391: Deleting Pod 'test-client-h5dc1mpy'
fixtures.go:391: Deleting Pod 'test-server-nsrch7ua'
```
=> Revert "Resolve flow aggregator close issue"

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/audit_logging.go, pkg/agent/controller/networkpolicy/audit_logging_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/packetin.go
This is a follow up PR for [Antrea Network Policy Audit Logging Deduplication and Unit Tests](https://github.com/antrea-io/antrea/pull/2294) to address comments.
- Converted back to include both `antreaPolicyEnabled` and `loggingEnabled` for extensible usage.
- Changed `AntreaPolicyLogger` method naming.
- Moved `bufferLength` to a member of `AntreaPolicyLogger` to avoid confusion.
=> [Follow Up][WIP]Antrea Network Policy Audit Logging Deduplication and Unit Tests

test/e2e/k8s_util.go
I tried running the tests locally today and couldn't get the test setup
(initial probe to check connectivity between all Pods) to succeed. I
added some log messages and it seems that a fraction of the probes
(different set of probes for every attempt) was always failing. I wasn't
able to reproduce the connection failures by exec'ing into the Pods
directly. I believe that this is caused by
https://github.com/antrea-io/antrea/pull/2565, which is causing a vey
large number of probes (648) to execute in parallel, each in its own
goroutine. This happens when running Docker on my macOS laptop, but
surprisingly I haven't observed any such failure in Github Actions. My
fix is to limit parallel probes to a single port number.
=> Fix e2e networkpolicy tests on Kind for slower machines

pkg/apiserver/registry/system/supportbundle/rest.go
when iproute2 is not installed in docker image, and run `antctl supportbundle` in
antrea-agent, it will panic, this is because, collectAgent will return a nil pointer
for systemv1beta1.SupportBundle, and `func (r *supportBundleREST) Create`,
antrea handles the nil pointer directly which leads to the panic.
=> supportbundle: fix nil pointer error

ci/kind/test-e2e-kind.sh
A patch was merged in upstream OVS and we picked up this patch when we
upgraded to OVS 2.15.1.
Fixes #897
=> Stop forcing tunnel type to VXLAN for Kind NetworkPolicy tests

pkg/antctl/raw/supportbundle/command.go, pkg/apis/system/v1beta1/types.go, pkg/apiserver/openapi/zz_generated.openapi.go, pkg/apiserver/registry/system/supportbundle/rest.go, pkg/log/log_file.go, pkg/support/dump.go, pkg/support/dump_others.go, pkg/support/dump_test.go, pkg/support/dump_windows.go
This PR is based on #1560, besides conflict fixes, the additional
changes are:
1. fix a command args help string error
2. revert the interface changes and use struct fields
3. create a func to do timefilter cal
Co-authored-by: Weiqiang Tang <weiqiangt@vmware.com>
=> Support timestamp filter in antctl supportbundle command

ci/jenkins/test.sh
The GO_VERSION was read from the wrong file, causing Windows CI jobs to
fail.
=> [CI] Fix typo in Jenkins test.sh script

docs/api.md, hack/windows/Helper.psm1, test/e2e/infra/vagrant/push_antrea.sh
* When Windows agents are started with script, not in a pod,
env var KUBE_DNS_SERVICE_HOST and KUBE_DNS_SERVICE_PORT
need to be set.
* Harmonize all '-o jsonpath' usage
=> [Windows] Update helper.psm1 to set env var for Windows FQDN

hack/windows/Clean-AntreaNetwork.ps1
[Windows] Add enhancement in the script Clean-AntreaNetwork.ps1
1. Reset ovs-vswitchd service if it is broken.
2. Remove NetworkAdapterBinding on the physical network adapter if exists,
to ensure Windows IP address to come back.
=> [Windows] Add enhancement in the script Clean-AntreaNetwork.ps1

pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go, pkg/agent/util/ndp/doc.go, pkg/agent/util/ndp/ndp_linux.go, pkg/agent/util/ndp/ndp_linux_test.go, pkg/util/ip/ip.go, pkg/util/ip/ip_test.go, test/integration/agent/ip_assigner_linux_test.go
Send NDP NA message upon assigning egress IP
Implement Neighbor Discovery Protocol(NDP) neighbor advertisement for Egress IPv6 support.
Once an IPv6 IP address has been assigned to Node, an unsolicited Neighbor Advertisement ICMPv6
multicast packet will be sent, announcing the IP to all IPv6 nodes as per RFC4861.
For #2128
=> Send NDP NA message upon assigning egress IP

build/images/base/Dockerfile, hack/build-whereabouts.sh
Also adding a script to simplify updating these binaries in the
future. The script outputs tarballs that need to be uploaded to the
downloads.antrea.io AWS S3 bucket.
Fixes #2656
=> Update whereabouts binaries from v0.4 to v0.4.2

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/util/net.go
1.Fix adding node routes crash bug, which caused by uninitialized DualStackIPs param.
2.Fix ipv4 address and ipv6 address confused bug and return the first ipv4 and ipv6 ips for transport interface.
Fixes #2665
=> Fix init node transport interface bug

ci/jenkins/mellanox/common/common_functions.sh, ci/jenkins/mellanox/scripts/start_ci.sh
Following https://github.com/antrea-io/antrea/pull/2609, `docker build`
for the ubuntu image now requires the `GO_VERSION` to be passed, which
broke the Mellanox CI. This patch changes the Mellanox CI so that it would
use `make build-ubuntu` instead of using the `docker build` command so that
all changes to Makefile would not break CI.
=> Fix Mellanox CI build command

ci/jenkins/mellanox/common/common_functions.sh, ci/jenkins/mellanox/scripts/start_ci.sh
Cherry pick of #2633 on release-1.3.
#2633: Fix Mellanox CI build command
=> Automated cherry pick of #2633: Fix Mellanox CI build command

docs/antrea-network-policy.md, pkg/agent/controller/networkpolicy/audit_logging.go, pkg/agent/controller/networkpolicy/audit_logging_test.go, test/e2e/antreapolicy_test.go
This PR follows [the previous PR](https://github.com/antrea-io/antrea/pull/1477) to update the documentation for audit logging. Recently deduplication is added for drop and reject packets.
Also, there was a discussion in the PR about removing `SRC: DEST:` in the log to keep consistency.
=> Update Audit Logging Documentation and Format

docs/antrea-network-policy.md
FQDN based policies cannot be used with "normal" (non headless Services)
as the DNS records point to the ClusterIP, yet policies are enforced
after AntreaProxy LB.
Reported by @GraysonWu
=> Fix documentation for FQDN based policies which use Service DNS names

docs/antrea-network-policy.md
Cherry pick of #2667 on release-1.3.
#2667: Fix documentation for FQDN based policies which use
=> Automated cherry pick of #2667: Fix documentation for FQDN based policies which use

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/util/net.go
Cherry pick of #2670 on release-1.3.
#2670: Fix init node transport interface bug (#2670)
=> Automated cherry pick of #2670: Fix init node transport interface bug (#2670)

test/e2e/legacyantreapolicy_test.go
Audit logging format has been updated in PR #2659, but forget to change it accordingly in `testLegacyAuditLoggingBasic`.
Change it in this PR.
=> Update Audit logging format in legacy e2e test

hack/windows/Install-OVS.ps1
Cherry pick of #2681 on release-1.3.
#2681: Upgrade Windows OVS version to 2.14.2
=> Automated cherry pick of #2681: Upgrade Windows OVS version to 2.14.2

test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
Add a new test case using in-cluster headless Services to test FQDN
policies, to avoid having a dependency on external connectivity. The reason we
use headless Service is that FQDN will use the IP from DNS A/AAAA records to
implement flows in the egress policy table. For a non-headless Service, the DNS
name resolves to the ClusterIP for the Service. But when traffic arrives to the
egress table, the dstIP has already been DNATed to the Endpoints IP by
AntreaProxy Service Load-Balancing, and the policies are not enforced correctly.
For a headless Service, the Endpoints IP will be directly returned by the DNS
server. In this case, FQDN based policies can be enforced successfully.
=> Add in-cluster svc fqdn e2e test

pkg/util/env/env.go
Currently, the startup scripts force an environment variable
to have lowercase node name. This gets complex once we add
support to native windows services as they don't get
env variables from local shell.
An example of startup script is function: Start-AntreaAgent in
https://raw.githubusercontent.com/antrea-io/antrea/v1.2.0/hack/windows/Helper.psm1
Signed-off-by: Gurucharan Shetty <gurushetty@google.com>
=> For Windows, the hostname in kube-apiserver is in lowercase.

pkg/util/env/env.go
Cherry pick of #2672 on release-1.3.
#2672: Convert NodeName obtained from env var to lowercase on
=> Automated cherry pick of #2672: Convert NodeName obtained from env var to lowercase on

test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
Cherry pick of #2662 on release-1.3.
#2662: Add in-cluster svc fqdn e2e test
=> Automated cherry pick of #2662: Add in-cluster svc fqdn e2e test

pkg/agent/agent.go, pkg/agent/wireguard/client_linux.go, pkg/agent/wireguard/client_windows.go, test/e2e/wireguard_test.go
The service traffic requiring SNAT couldn't be transferred to peer Node
when the endpoint Pod is on another Node. This was because we didn't
set any address on WireGuard device antrea-wg0. Therefore, when
iptables MASQUERADE action took effect, it chose one IP from other
interfaces, which might not be the gateway address on antrea-gw0. This
caused two problems:
1. Peer wireguard didn't accept the packet as its source address was not
in its "allowed ips"
2. Peer Node wouldn't route the response back via the encrypted tunnel
as the destination IP was not in its "allowed ips"
This patch fixes it by assigning the gateway IPs on the WireGuard
device. But it uses "/32" mask for IPv4 address and "/128" mask for
IPv6 address to avoid impacting routes on Antrea gateway.
Signed-off-by: Quan Tian …
=> [WireGuard] Fix service traffic requiring SNAT

pkg/agent/agent.go, pkg/agent/wireguard/client_linux.go, pkg/agent/wireguard/client_windows.go, test/e2e/wireguard_test.go
Cherry pick of #2697 on release-1.3.
#2697: Fix service traffic requiring SNAT
=> Automated cherry pick of #2697: Fix service traffic requiring SNAT

ci/jenkins/test.sh, test/e2e/wireguard_test.go
WireGuard kernel module is present on IPv6 and IPv6 dual-stack clusters. Make sure that we can run commands on all nodes to check for kernel modules. This is a prerequisite for WireGuard e2e tests.
The error is as follows:
```
=== RUN   TestWireGuard
fixtures.go:95: The following modules have been found on Node 'antrea-ipv6-9-0': [wireguard]
fixtures.go:89: Skipping test as modprobe could not be run to confirm the presence of module 'wireguard': unable to find 'HostName' for 'antrea-ipv6-9-1' in SSH config
--- SKIP: TestWireGuard (0.81s)
```
Fixes https://github.com/antrea-io/antrea/issues/2661
=> [CI]Generate ssh-config for all Nodes

Makefile, hack/verify-spelling.sh, hack/verify-toc.sh
To avoid the following warning when using Go 1.17 (default version for
Antrea):
go get: installing executables with 'go get' in module mode is deprecated.
See https://golang.org/doc/go-get-install-deprecation
=> Use "go install" to install the tools required by "make verify"

build/images/scripts/start_ovs, pkg/ovs/ovsctl/interface.go, pkg/ovs/ovsctl/ovsctl_others.go
Otherwise the call may fail and crash the process.
Besides, it cleans up the OVS run files on exit to avoid stale PID
from being used.
Fixes #2694
=> Wait for ovs-vswitchd PID before calling ovs-appctl

ci/jenkins/test.sh, test/e2e/wireguard_test.go
Cherry pick of #2675 on release-1.3.
#2675: Generate ssh-config for all Nodes
=> Automated cherry pick of #2675: Generate ssh-config for all Nodes

build/images/scripts/start_ovs, pkg/ovs/ovsctl/interface.go, pkg/ovs/ovsctl/ovsctl_others.go
Cherry pick of #2695 on release-1.3.
#2695: Wait for ovs-vswitchd PID before calling ovs-appctl
=> Automated cherry pick of #2695: Wait for ovs-vswitchd PID before calling ovs-appctl

cmd/antrea-agent/agent.go, pkg/agent/memberlist/cluster.go, pkg/agent/util/ndp/doc.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/service_test.go, test/e2e/wireguard_test.go
Fixed agent panic because of nil NodeIP in pure IPv6 cluster
The `nodeConfig.NodeIPv4Addr` is nil which would cause panic in agent,
when starting agent with Egress feature enabled in pure IPv6 cluster.
Related #2436
Add Egress IPv6 test cases in dual-stack or pure IPv6 cluster. Related #2196
=> Fix agent nil panic in pure IPv6 cluster

cmd/antrea-agent/agent.go, pkg/agent/memberlist/cluster.go, pkg/agent/util/ndp/doc.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/service_test.go, test/e2e/wireguard_test.go
Cherry pick of #2655 on release-1.3.
#2655: Fix agent panic because of nil NodeIP in pure IPv6 cluster
=> Automated cherry pick of #2655: Fix agent panic because of nil NodeIP in pure IPv6 cluster

test/e2e/wireguard_test.go
It shouldn't use IPv4 localhost IP 127.0.0.1.
=> Fix WireGuard testServiceConnectivity in IPv6 cluster

test/e2e/wireguard_test.go
Cherry pick of #2712 on release-1.3.
#2712: Fix WireGuard testServiceConnectivity in IPv6 cluster
=> Automated cherry pick of #2712: Fix WireGuard testServiceConnectivity in IPv6 cluster

ci/jenkins/test.sh
Cherry pick of #2705 on release-1.3.
#2705: Update test.sh * Retry after reverting Windows VM
=> Automated cherry pick of #2705: Update test.sh * Retry after reverting Windows VM

build/yamls/elk-flow-collector/elk-flow-collector.yml, docs/network-flow-visibility.md
This commit changes ```ES_JAVA_OPTS``` in elasticsearch to decrease the memory required to run the ELK flow collector when using the network visibility in Antrea.
This allows the ELK flow collector to run without the --large option when provisioning the Nodes in Vagrant clusters. But it may require more initialization time for the ELK flow collector.
=> Fix ELK Flow Collector manifest to run it on regular Vagrant clusters

pkg/agent/openflow/pipeline_windows.go
Load the SNAT mark in snatTable on the established connection packets which is sent out from local Pods.
Fixes #2701 
Signed-off-by: wenyingd wenyingd@vmware.com
=> [Windows] Bugfix: SNAT is not performed on the +est packets.

ci/conformance-image-config.yaml
It seems that images are sometimes missing from
mirror.gcr.io/library. After some testing, it seems that
k8s.gcr.io/e2e-test-images includes all images.
=> Change dockerLibraryRegistry for conformance testing

hack/.md_links_config.json
For some reason, the site is down pretty often, causing CI failures. I
have confirmed it manually, so it is not an issue with the link checker
itself.
=> Stop checking virtualbox.com in markdown link checker

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go
Check if the clause pointer is nil before looping the matches.
Fixes #2729 
=> Fix panic bug in Antrea Policy

pkg/agent/util/net_windows.go
Append "-Confirm:$false" in the powershell command "Remove-NetNat" for NonInteractive mode
Fixes #2750 
=> [Windows] Bugfix: Agent crashed when removing the existing NetNat

README.md, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-controller.conf, build/yamls/base/controller-rbac.yml, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go, docs/feature-gates.md, pkg/apiserver/handlers/featuregates/handler.go, pkg/apiserver/handlers/featuregates/handler_test.go, pkg/features/antrea_features.go, third_party/ipam/LICENSE, third_party/ipam/README, third_party/ipam/controller_util_node/controller_utils.go, third_party/ipam/nodeipam/ipam/cidr_allocator.go, third_party/ipam/nodeipam/ipam/cidrset/cidr_set.go, third_party/ipam/nodeipam/ipam/cidrset/metrics.go, third_party/ipam/nodeipam/ipam/range_allocator.go, third_party/ipam/nodeipam/node_ipam_controller.go, third_party/ipam/util_node/node.go
Import K8S NodeIPAMController code into third_party, use it within Antrea Controller. Then run it within Antrea Controller.
Usable when kube-controller-manager doesn't run nodeipam such as in EKS.
Uses RangeAllocatorType only.
=> Use NodeIPAMController code from K8S

pkg/agent/util/net_windows.go
Cherry pick of #2751 on release-1.3.
#2751: Bugfix: Agent crashed when removing the existing netnat
=> Automated cherry pick of #2751: Bugfix: Agent crashed when removing the existing

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go
Cherry pick of #2730 on release-1.3.
#2730: Fix panic bug in Antrea Policy
=> Automated cherry pick of #2730: Fix panic bug in Antrea Policy

hack/update-codegen.sh
codegen:kubernetes-1.21.0 has been reverted to Golang v1.15 as previous
releases still use it. codegen:kubernetes-1.21.0-build.0 is created
with Golang upgraded to v1.17.
For #2780
=> Pin codegen image tag to kubernetes-1.21.0-build.0

pkg/apiserver/registry/system/supportbundle/rest.go
Cherry pick of #2598 on release-1.2.
#2598: supportbundle: fix nil pointer error
=> Automated cherry pick of #2598: supportbundle: fix nil pointer error

pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
When a ClusterGroup is created, updated, or deleted, `triggerCNPUpdates`
will be called to update ClusterNetworkPolicies that reference to it.
However, a ClusterNetworkPolicy may have not been processed by `addCNP`
when they are found in the informer cache, which means its internal
NetworkPolicy doesn't exist yet. `triggerCNPUpdates` would panic if it
assumes the internal NetworkPolicy always exist and uses the returned
value directly.
This patch fixes it by checking existence first before using the
returned internal NetworkPolicy.
Fixes #2769
=> Fix triggerCNPUpdates panic

pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
Cherry pick of #2768 on release-1.2.
#2768: Fix triggerCNPUpdates panic
=> Automated cherry pick of #2768: Fix triggerCNPUpdates panic

pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/cniserver/sriov.go
Use a separate goroutine to process interface configuration async. The
configurations are taken after the host interface is created.
Fixes #2773
=> [Windows] Bugfix for MTU configuration on nonexistent interface

pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/cniserver/sriov.go
Cherry pick of #2778 on release-1.2.
#2778: Bugfix for MTU configuration on nonexistent
=> Automated cherry pick of #2778: Bugfix for MTU configuration on nonexistent

build/images/scripts/start_ovs, build/images/scripts/start_ovs_netdev
Starting with OVS 2.15.0, the permissions are set correctly (i.e. more
securely) for the OVSDB .db file (with no read permissions for
"others"). Because we use OVS 2.15.1 in Antrea, we no longer need to
manually fix the permissions in start_ovs / start_ovs_netdev.
Fixes #1292
=> Remove chmod for OVSDB file from start_ovs

docs/contributors/github-labels.md
In addition to NetworkPolicy label updates, introduce new github labels for "grouping" to cover Groups, ClusterGroups
and GroupEntity controller in addition to other group related features.
Signed-off-by: abhiraut <rauta@vmware.com>
=> Update NetworkPolicy related github labels

pkg/antctl/raw/supportbundle/command.go
Instead of creating a buffer which buffers all converted objects and
outputs to file together, this patch traverses the item list, and
converts and outputs items one by one.
In a scale cluster with 26,000+Pods, the memory usage is reduced from
16GB to 600MB.
=> Reduce memory consumption of supportbundle command

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go
If destination IP is nodeIPs, we must skip SNAT if egress is enabled,
no need to forward such packets to the egressIP node
Signed-off-by: Yang Li <yang.li@transwarp.io>
=> Install flows to skip SNAT for k8s nodes (#2708)

.github/AREA-OWNERS, .github/workflows/reviews.yml
Reviews will be automatically requested based on the area label(s) added
to the PR. Based on the set of approving reviews, the Github action will
then determine whether the PR can be merged.
For the sake of initial testing, the action will only run on PRs
labelled with 'review-manager-test'.
One potential concern is rate-limiting of Github API operations (1,000
requests per hour per repository). We will see if this becomes an issue
and we can adjust @antrea-io/review-manager accordingly if needed.
See #2752
=> Use @antrea-io/review-manager to manage PR reviews

ci/jenkins/test.sh
Cherry pick of #2815 on release-1.2.
#2815: Fix Windows NetPol test failures * Retry resync VM time
=> Automated cherry pick of #2815: Fix Windows NetPol test failures * Retry resync VM time

CONTRIBUTING.md
Use test-windows-all for whole Windows tests, instead of part of
test-all.
Signed-off-by: lzhecheng <lzhecheng@vmware.com>
=> [CI][doc] Update Jenkins trigger phrase

.github/AREA-OWNERS, docs/contributors/github-labels.md
area/transit/egress
area/transit/ipv6
=> Add missing Github labels

third_party/ipam/controller_util_node/controller_utils.go, third_party/ipam/nodeipam/ipam/cidrset/metrics.go
gofmt discovers the formatting issues. They were not found by CI because
golangci-lint skips "third_party" dir by default. The original third
party code are formatted correctly.
=> Fix code formatting

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go
Use same naming and format convention for for NodeIPAM as it is for
other Antrea features.
Fixes: #2839
=> Unify config name and format

cmd/antrea-agent/agent.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/ipassigner/ip_assigner_linux.go, pkg/agent/controller/egress/ipassigner/ip_assigner_windows.go, pkg/agent/memberlist/cluster.go, pkg/agent/memberlist/cluster_test.go
1. Use transportInterface as Egress external interface to send EgressIP gratuitous arp.
2. Remove unused field in Cluster struct.
=> Use Node TransportIP interface to send EgressIP gratuitous arp

cmd/antrea-agent/agent.go, pkg/agent/proxy/proxier.go, third_party/proxy/meta_proxier.go, third_party/proxy/types.go
Otherwise components that rely on Service availability (e.g. agent
APIServer) would fail to initialize and crash the whole process.
Fixes #2857
=> Wait for AntreaProxy to be ready before accessing Service

pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/ipam/ipam_delegator.go, pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/cniserver/ipam/testing/mock_ipam.go, pkg/agent/cniserver/ipam/testing/mock_multi_driver.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/cniserver/types/arg_types.go, test/integration/agent/cniserver_test.go
In preparation for antrea IPAM support, allow a list of drivers to
be registered. This is useful for antrea IPAM: antrea ipam driver
will claim ownership of request if corersponding object has ipam
annotation. Otherwise, fallback driver (host-local) will handle
ipam for this request.
=> Allow multiple drivers per IPAM type

pkg/controller/egress/controller.go, pkg/controller/egress/controller_test.go
Now Egress does not support HostNetwork Pods, so need to ignore selected HostNetwork Pods in Egress groups.
Fixes: #2850 
=> Ignore selected hostNetwork Pods in Egress groups

.github/workflows/website.yml, .github/workflows/website_release.yml
These events will trigger the "Update website source" workflow in the
antrea-io/website repository, and the website will be updated.
Fixes #2274
=> Trigger automatic website updates for the main branch and for releases

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, plugins/octant/go.sum, test/e2e/framework.go
see https://github.com/vmware/go-ipfix/releases/tag/v0.5.8 for changes.
With basic structure change of NewInfoElementWithValue, memory usage is expected to be reduced. Here is the Flow Exporter benchmarking improvement for conntrack connections:
Before:
|# conns | iterations | ns/op | B/op | allocs/op|
|-- | -- | -- | -- | --|
|20000   |  100	 |  3484688 ns/op	|  527820 B/op	|    8214 allocs/op|
|30000  |  100  |  5868374 ns/op	|  788098 B/op        |   12313 allocs/op|
|40000  |   100 | 7300047 ns/op     | 1047562 B/op	|   16392 allocs/op|
|50000  |  100	 |  9312464 ns/op	| 1308313 B/op	|   20503 allocs/op|
After change:
|# conns | iterations | ns/op | B/op | allocs/op|
|-- | -- | -- | -- | --|
|20000   |   100	|   3174982 ns/op 	 | 328104 B/op	|    3262 allocs/op|
|30000   |   100	 | …
=> Upgrade go-ipfix to v0.5.8

docs/windows.md
This corrects an incorrect path in the windows docs that points the prepare script to the wrong folder
Fixes: #2827
=> Correct Prepare-antreaagent.ps1 Script Path in Docs

docs/windows.md
Adds a randomdelay flag to the windows scheduled job to allow the task to run slightly after startup.  Running directly At Startup can include a failure to initialise, where this delay allows a slight leeway to run a little after. 
Fixes: #2826 
Signed-off-by: Peri Thompson <perit@vmware.com>
=> Added windows task delay up to 30s to improve job resiliency

docs/design/policy-only.md, docs/eks-installation.md, docs/getting-started.md
=> Document encap mode installation for EKS

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/route/route_windows.go
listRoutes() only considers routes with antrea-gw0 as interface
so no need to consider kube-proxy Service routes. Also for AntreaProxy
Service routes, all of them should be returned and be compared with
desiredClusterIPSvcIPs.
NodePort and LoadBalancer Services also have ClusterIPs so the check
if Service is ClusterIP Service is unnecessary.
=> [Windows][AntreaProxy] Fix route reconcile()

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller.yml, cmd/antrea-controller/controller.go, docs/feature-gates.md, pkg/apiserver/apiserver.go, pkg/controller/ipam/validate.go, pkg/controller/ipam/validate_test.go
The patch adds a ValdatingWebhookConfiguration for IPPool:
- For update operation, the IPPool must not shrink
- For delete operation, the IPPool must not be in use
Based on #2871, the only new patch in this PR is https://github.com/antrea-io/antrea/pull/2946/commits/0f81d3a777b842647b25f46324427e166e62c47a
=> Add validating webhook for IPPool

pkg/controller/egress/controller.go, pkg/controller/egress/controller_test.go
IPv6 does not support broadcast address so it doesn't make sense to
exclude it from IP ranges. And the util function GetLocalBroadcastIP
will panic if an IPv6 CIDR is provided.
=> Do not calculate broadcast address for IPv6 CIDR

CONTRIBUTING.md
proxyall-e2e is included in test-windows-all and remove
test-windows-proxyall-all
=> [CI] Update trigger phrases for Windows tests

.github/workflows/benchmark.yml, test/performance/benchmark.yml
Add Go Benchmark check
Run Go benchmarks as part of CI and automatically monitor for performance
regressions.
Fixes #2488
=> Add Go benchmark check

hack/windows/Clean-AntreaNetwork.ps1
Add a parameter in the powershell script "Clean-AntreaNetwork.ps1" to
control if renewing ipconfig or not. The default value is $false.
Fixes #2954 
=> [Windows] Add a PS parameter to renew ipconfig

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/fqdn.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/controller/networkpolicy/reject.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_packetout.go, test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
Fixes issue #2699 
**1. Change reject response packetOut logic to below:**
* Pod-to-Pod traffic
* Locally: Directly output the packet to the destination OF port. Use src/dstPod's OF port as in/outPort.
* Remote to local: Directly output the packet to the destination OF port. Use gateway's OF port as inPort and dstPod's OF port as outPort.
* Local to remote: Resubmit packet to l3ForwardingTable(70). Use Pod's OF port as inPort.
* Service traffic
* AntreaProxy enabled
* Locally: Resubmit packet to conntrackTable(30). Use srcPod's OF port as inPort.
* Remote to local: Use gateway's OF port as inPort.
* Local to remote: Same as Pod-to-Pod traffic local to remote case.
* AntreaProxy disabled
* Locally: Directly output the packet to gateway's OF port. Use srcPod's OF port as inPort and …
=> Fix reject action on Service traffic

test/e2e/antreapolicy_test.go
This was introduced by merging #2956 and #2772 whose code conflict was
not detected by git.
=> Fix missing parameter in tests

test/e2e/antreapolicy_test.go
Cherry pick of #2968 on release-1.4.
#2968: Fix missing parameter in tests
=> Automated cherry pick of #2968: Fix missing parameter in tests

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/connections/deny_connections_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/types.go, test/integration/agent/flowexporter_test.go
1. Include the initializations of priority queue and connection store into flowExporter
2. Use setter to to inject the `denyConnStore` into the `networkPolicyController`
Fixed: #2829 
=> Combine FlowExporter resources initialization in agent.go

Makefile, docs/antrea-network-policy.md, docs/cookbooks/fluentd/README.md, docs/cookbooks/fluentd/resources/fluentd.yml, docs/cookbooks/fluentd/resources/kibana-elasticsearch.yml, docs/cookbooks/fluentd/resources/kubernetes.conf, docs/network-flow-visibility.md, hack/update-spelling.sh, hack/update-toc.sh
This is to complete this issue request [Add documentation support for Fluentd integration with Audit Logging](https://github.com/antrea-io/antrea/issues/2642)
- Added a cookbook for using Fluentd with Antrea
- Changed `go get` to `go install` in file `hack/update-toc.sh` and `hack/update-spelling.sh`
- Changed set jvm guide link to 7.8 version to avoid 404 status
After investigating with `top`, the CPU consumption percentage does not have significant change after deploying Fluentd.
=> Fluentd for Audit Logging

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
It is a workaround for a Windows OVS issue which marks the reply packet
as "new" in conntrack, and mark it as a connection initiated from
antrea-gw0 (including the Node or the external). The issue results the
reply packet from antrea-gw0 is output to antrea-gw0 and finally dropped
by OVS datapath because the input and output port number are the same.
The workaround is only rewrite the dst MAC as antrea-gw0's on the reply
packet which enters OVS from the local Pods or the tunnel port even if
the connection is marked as initiated from antrea-gw0.
=> [Windows] Rewrite dMAC as the gateway's only for local and remote Pods

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Cherry pick of #2985 on release-1.4.
#2985: Rewrite dMAC as the gateway's only for local and
=> Automated cherry pick of #2985: Rewrite dMAC as the gateway's only for local and

docs/antrea-ipam.md, docs/eks-installation.md
Also fixed a mistake in eks-installation.md that encap mode for EKS
requires Antrea version >= 1.4, which is the first version with the
Antrea NodeIPAM feature.
=> Add example values of the clusterCIDRs parameter of NodeIPAM

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/agent/flowexporter/exporter/exporter.go, pkg/flowaggregator/flowaggregator.go, pkg/ipfix/ipfix_collector.go, pkg/ipfix/ipfix_intermediate.go, plugins/octant/go.sum, test/e2e/framework.go
This commit adds changes in [go-ipfix v0.5.9](https://github.com/vmware/go-ipfix/releases/tag/v0.5.9). 
It is expected to be merged with PR #2878.
=> Upgrade to go-ipfix v0.5.9

Makefile, build/yamls/antrea-kind.yml, ci/kind/kind-setup.sh, ci/kind/test-e2e-kind.sh, ci/kind/test-upgrade-antrea.sh, docs/kind.md, hack/.notableofcontents, hack/make-metrics-doc.sh
* Default "--antrea-cni" to false: most of the time, it is actually how
we use it, and it is how users need to use the script.
* Check-in build/yamls/antrea-kind.yml to avoid user confusion.
* Improve Antrea with Kind documentation.
Fixes #2934
=> Improve ci/kind/kind-setup.sh usage

cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, test/integration/agent/route_test.go
Move the validation for serviceCIDR under the condition that AntreaProxy
is disabled. So that the user could not ignore the item when using
AntreaProxy instead of kube-proxy.
Fixes #2935 
=> Validate serviceCIDR configuration only if AntreaProxy is disabled

.github/workflows/upload_release_assets.yml
For some reason, I forgot to use the setup-go action for that workflow
when I added it, which means that we have been using the default Go
version provided by the Github runners since the beginning. The default
Go version is [currently 1.15](https://github.com/actions/virtual-environments/blob/8fd74ebe0f0706cb6aa2cc01f5863961d01173e9/images/linux/toolsets/toolset-2004.json#L52), which is not maintained.
We now use the setup-go action to use the same Go version as all other
workflows (1.17).
=> Use go 1.17 to build release assets

.github/workflows/upload_release_assets.yml
Cherry pick of #3007 on release-1.3.
#3007: Use go 1.17 to build release assets
=> Automated cherry pick of #3007: Use go 1.17 to build release assets

pkg/agent/cniserver/interface_configuration_windows.go
For non-infra containers, there's no need to remove HNSEndpoint if failure since it will be done when the Pod is removed.
=> [Windows] Remove HNSEndpoint only if infra container fails to create

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-controller/options.go, docs/antrea-ipam.md, pkg/config/controller/config.go, pkg/features/antrea_features.go
* Multiple CIDRs for an IP family is not supported by NodeIPAM
* nodeCIDRMaskSizeIPv6 defaults to 64, use a larger CIDR as example
* AntreaIPAM is introduced in v1.4
=> Fix IPAM doc and enhance validation 

pkg/agent/controller/networkpolicy/reject.go
Fix error handling in Reject implementation, when determining if the
packet belongs to Service traffic.
Because of the situation described in PR #3006, I didn't notice this
bug before. Fix it in this PR.
=> Fix error handling in Reject implementation

cmd/antrea-agent/agent.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_perf_test.go
Add a dedicated initialization function for testing purpose - `NewFlowExporterForTest`. 
Fixes: #2984 
=> Fix exporter benchmark failures

.github/workflows/go.yml
Run the benchmarks once for each PR.
Fixes #2984
=> Add Go benchmark test

test/e2e/k8s_util.go
This PR has two changes:
1. Adds a parameter `containerName` to `probe` func.
Previously we use "c[port]" as containerName in `probe` to call
`runCommandFromPod`. But in this case, `probe` func couldn't work
with the client created by `createAgnhostPodOnNode` or functions that
create Pod with different container names. We hope `probe` func could
be more generic, so I add `containerName` parameter. Let the caller
to choose the containerName.
2. Changes the way that how we decides the connectivity.
Our framework will do probe 3 times to get the connectivity. Previous
logic is:
- If one of them connected, then it's connected.
- If no one connected and one of them is timeout, then it's
dropped.
- All other situation return rejected.
This could be a problem. For example: …
=> Add containerName param to probe func

pkg/agent/controller/networkpolicy/reject.go
Fixes issue #2979.
For this issue, after investigation, I noticed that only intra-Node Pod-to-Pod traffic with ingress reject policy will fail.
The root cause of this issue is that in AntreaIPAM mode, MAC addresses will always be re-written as `srcMAC=localGatewayMAC, dstMAC=dstPodInterfaceMAC` in L3ForwardingTable. https://github.com/antrea-io/antrea/blob/main/pkg/agent/openflow/pipeline.go#L1150-L1152. 
Previous reject logic for intra-Node Pod-to-Pod case is that directly output the reject response to the OF port of the dstPod of the reject response. This could work for egress policies because the packet hasn't reached L3ForwardingTable. But for ingress policies, MAC addresses haven't re-written. The generated reject response will use localGatewayMAC as dstMAC. When the client receives …
=> Make reject action work in AntreaIPAM mode

pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/types/group.go, test/e2e/clustergroup_test.go
Fixes #3002.
ClusterGroup with child groups should only be considered groupMembersComputed after all its child groups are created and processed.
=> Fix ClusterGroup realization status logic

pkg/agent/agent.go
For Windows, antrea-gw0 interface must be enabled before
MTU is set, so MTU is not configured with current code.
Currently the result of SetInterfaceMTU is not checked, so
the error is not found.
=> Fix SetInterfaceMTU not working on Windows bug

go.mod, go.sum, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/pod_configuration_linux.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/agent/cniserver_test.go, test/integration/ovs/ovs_client_test.go
1. Use OVS Port externalIDs to cache the externalIDS in containerd
runtime instead of HNSEndpoint
2. Create the OVS Interface with type "" if the host interface is
not created (in containerd case), and update the type as "internal"
after the host interface is created
3. Connect the OVS port to the host interface in function "reconcile" if
the OVS port's ofport number is -1, by updating the OVS Interface type
as "internal".
Fixes #2913 
=> [Windows] Replace the private patch in the dependent hcsshim library

ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh, codecov.yaml
1. fix the bug where codecov is not executed at all
2. add missing codecov flag `kind-e2e-tests` which is used in kind workflow
3. add a new flag for multicluster integration test
4. limit concurrent integration jobs
Resolve #3060
=> Fix coverage upload issue

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, test/e2e/antreapolicy_test.go
For an Antrea-native policy with multiple rules that have different AppliedTo, some rules may not be effective on a Node when the policy applies to the Node. In this case, antrea-agent didn't make any actual dataplane change and didn't report new status to antrea-controller if the only changed part of a policy event is about the ineffective rules, even though the generation of the policy may have changed. This leads to a policy staying in realizing state because of the missing status report.
This patch fixes it by triggering status report at least once as long as a policy is actually updated. In addition, it removes some useless return value and changes the order of event logs to better reflect the cause of policy reconciliation.
Fixes #3075
=> Fix status report of Antrea-native policies

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
Fixes #3078
Signed-off-by: Yang Ding dingyang@vmware.com
=> Do not group hostNetwork Pods in ClusterGroup/AddressGroup

docs/antrea-network-policy.md
This is a one-line change: there was a typo in the Tier name for one
policy example.
s/securityOps/securityops
=> Fix typo in antrea-network-policy doc

pkg/agent/agent.go
Cherry pick of #3043 on release-1.4.
#3043: Fix SetInterfaceMTU not working on Windows bug For Windows,
=> Automated cherry pick of #3043: Fix SetInterfaceMTU not working on Windows bug For Windows,

docs/antrea-network-policy.md
update Namespace match type to `Self` in antrea network policy doc.
Fixes: #3091 
=> update Namespace match type to `Self` in antrea network policy doc.

pkg/antctl/command_list.go, test/e2e/antctl_test.go, test/e2e/flowaggregator_test.go
This commit adds a more concrete e2e test to check the output of `antctl get flowrecords -o json` on the Flow Aggregator. 
=> Add e2e test to check flow records from flow aggregator antctl

pkg/apis/controlplane/v1beta2/marshal.go, pkg/support/dump.go
There was an obvious bug where all NetworkPolicy resources
(NetworkPolicies, AddressGroups, AppliedToGroups) were dumped to the
same file, and the file itself ("agentinfo") was subsequently
overwritten with a dump of the appropriate AgentInfo CRD as expected.
This is fixed by dumping these resources to their respective appropriate
files: networkpolicies, addressgroups, appliedtogroups.
In addition, we:
* switch from JSON to YAML for these resources (along with the AgentInfo
CRD) for consistency with the files included in the Controller's
supportbundle.
* define a custom MarshalYAML function for the IPAddress type. IPAddress
is typedef'ed to a byte slice, which means that by default it is
marshalled as an array of individual byte values, making the files
difficult to read.
Fixes #3082 …
=> Fix NetworkPolicy resources dump for Agent's supportbundle

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
Add throttle setting property in project definition will be
overwritten by template, so add a new template for integration jobs
so we can define throttle concurrency for them.
=> Fix concurrent setting for integration jobs

build/images/scripts/start_ovs, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/interfacestore/types.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
Introduce Antrea interface yype to map the OVS port to Antrea created
interfaces, and use OVS port  external_ids field to save the
configuration. This is helpful for Antrea to define more interface types.
=> Use OVS port external_ids to save Antrea interface type

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, test/e2e/antreapolicy_test.go
Cherry pick of #3074 on release-1.4.
#3074: Fix status report of Antrea-native policies
=> Automated cherry pick of #3074: Fix status report of Antrea-native policies

docs/antrea-network-policy.md
Cherry pick of #3092 on release-1.2.
#3092: update Namespace match type to `Self` in antrea network
=> Automated cherry pick of #3092: update Namespace match type to `Self` in antrea network

pkg/apis/controlplane/v1beta2/marshal.go, pkg/support/dump.go
Cherry pick of #3083 on release-1.3.
#3083: Fix NetworkPolicy resources dump for Agent's supportbundle
=> Automated cherry pick of #3083: Fix NetworkPolicy resources dump for Agent's supportbundle

docs/network-flow-visibility.md
The protocol must be written in lowercase, otherwise the validation
would fail.
I followed the doc to deploy flow-aggregator and found it crashed because of this.
=> Fix the case of protocol in flow-aggregator doc

pkg/controller/networkpolicy/validate.go, test/e2e/antreapolicy_test.go
=> Make Peer validation more comprehensive

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
The issue mentioned in #3091 has been encountered by several people, validating the value can avoid misuse of the field.
=> Validate namespaces.match of AntreaClusterNetworkPolicy rules

docs/node-port-local.md
* list supported Service types
* add information about existing integrations with external Load
Balancers (at the moment, we are only aware of AVI / AKO leveraging
NodePortLocal)
=> Improve NodePortLocal documentation

docs/antrea-network-policy.md
It doesn't make sense that the ACNP for zero-trust denies traffic
from/to Pods but allows external addresses.
=> Update the example of ACNP for zero-trust

ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml
1. add multi-cluster manual integration job
2. update status_context for all integration jobs to be consistent as
other jobs.
the change to add  multicluster-integration test cases support in `test-vmc.sh` will be submitted in another PR in feature branch.
=> Add multi-cluster manual integration job

test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2, test/e2e/infra/vagrant/provision.sh
=> Support for kube-proxy ipvs mode in Vagrant testbed

.github/workflows/lifecycle_management.yml
The number of Github API calls generated by some Jenkins jobs is
proportional to the number of open PRs. When there are too many of them,
we can hit API rate limiting issues. This should help with such issues
in the long run.
=> Half the number of days before issues & PRs become stale / closed

pkg/agent/cniserver/interface_configuration_windows.go
We should use containerNetNS when deciding if a container is an infra one.
Fixes #3077
=> [windows] Fix bug in configureContainerLink

test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/playbook/roles/common/tasks/containerd.yml, test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml, test/e2e/infra/vagrant/playbook/roles/common/tasks/netplan.yml, test/e2e/infra/vagrant/playbook/roles/common/templates/netplan.conf.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2
Use same private network for IPv4 and IPv6 by using a custom netplan
instead of relying on Vagrant to configure K8s networking. This enables
us to meet the condition that both the Node's IPv4 and IPv6 addresses be
assigned to the same interface (required by Antrea).
Fixes #3157
=> Fix dual-stack support for Vagrant-based test cluster

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/testing/mock_interfacestore.go, pkg/agent/interfacestore/types.go, pkg/agent/multicast/mcast_controller.go, pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/packetin.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/apiserver/handlers/featuregates/handler.go, pkg/apiserver/handlers/featuregates/handler_test.go, pkg/features/antrea_features.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_packetout.go, test/integration/agent/openflow_test.go
1. Use packetIn/packetOut to collect IGMP membership report and detect
Multicast group.
2. Add an OpenFlow entry for each Multicast group in which local Pods
have joined to forward the packet normally and output it to
antrea-gw0.
3. Output the Multicast traffic to antrea-gw0 if no local Pods have
joined the target Multicast group.
=> [Multicast] Multicast group auto-discovery

cmd/antrea-agent/agent.go, pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/ipam/antrea_ipam_controller.go, pkg/agent/cniserver/ipam/antrea_ipam_test.go, pkg/ipam/poolallocator/allocator.go, pkg/ipam/poolallocator/allocator_test.go, pkg/ipam/poolallocator/testing/fake_client.go
For sake of efficiency, use pool informer rather than client.
This change introduces a ip pool specific testing client, since
simple fake client is not designed to deal with object versioning.
=> [flexible-ipam] Use IP Pool informer in pool allocator

ci/run-k8s-e2e-tests.sh
Otherwise running the script with `--e2e-all` would not run any
NetworkPolicy tests.
Fixes #3172
=> Do not override global RUN_E2E_SKIP in e2e script

ci/jenkins/jobs/projects.yaml
Use comment /skip-integration or /skip-all to manually skip integration
tests.
Signed-off-by: Zhengsheng Zhou <zhengshengz@vmware.com>
=> Jenkins: Allow to Skip Integration Test

CONTRIBUTING.md, build/images/ovs/README.md, build/images/scripts/start_ovs_ipsec, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/patches/ipsec/pskEnv.yml, docs/contributors/github-labels.md, docs/network-requirements.md, hack/generate-manifest.sh, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/types.go, pkg/agent/openflow/client.go, pkg/config/agent/config.go, pkg/ovs/ovsconfig/ovs_client.go, test/e2e/ipsec_test.go
1. according to [rfc6071](https://datatracker.ietf.org/doc/html/rfc6071), correct abbr
for `IP security` should be `IPsec`, replace all `IPSec` to `IPsec`
2. add a new section to highlight some general words and abbreviations
=> Fix IPSec abbr to IPsec

pkg/agent/multicast/mcast_controller.go, pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go
Antrea Agent sends IGMPv1/v2/v3 query messages to snoop the multicast groups in which local Pods have joined.
=> [Multicast] Support IGMP query v1/v2/v3 message

pkg/controller/networkpolicy/networkpolicy_controller.go
Use sets instead of slice to resolve duplicated AddressGroup key problem when generating AddressGroup keys from NetworkPolicy rules.
Fixes: #3135 
=> Fix the AddressGroup duplicated deleted bug

pkg/controller/networkpolicy/status_controller.go
To reslove the conflict problem in updating NetworkPolicy status
process, add a retry logic in updating NetworkPolicy status function.
Fixes: #3133 
=> Add retry to update NetworkPolicy status

cmd/antrea-agent/options.go, docs/noencap-hybrid-modes.md, pkg/util/env/env.go
When using NoEncap traffic mode without AntreaProxy, Pod-to-Service
traffic is handled by kube-proxy (iptables/ipvs) in the root netns.
If the Endpoint is not local the DNATed traffic will be output to
the physical network directly without going back to OVS for Egress
NetworkPolicy enforcement, which breaks basic security functionality.
Therefore, we usually do not allow the NoEncap traffic mode without
AntreaProxy. But one can bypass this check and force this feature
combination to be allowed, by defining the ALLOW_NO_ENCAP_WITHOUT_ANTREA_PROXY
environment variable and setting it to true. This may lead to better
performance when using NoEncap if Egress NetworkPolicy enforcement is
not required.
Signed-off-by: Wenze Gao <wenze.gao@transwarp.io>
Signed-off-by: Wu zhengdong …
=> Add env parameter to support noEncap without AntreaProxy

pkg/antctl/raw/traceflow/command.go
Sometimes the traceflow function may be used incorrectly, so need to display the reason for the failure.
=> Add reason field in antctl traceflow command output

ci/jenkins/test-vmc.sh
After skipping certificate check, CI integration test will be recovered with new private IP.
The reason is this IP is not yet included in the vCenter certificate.
=> [CI] Recover integration test by skipping certificate check

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/config/agent/config.go
A new proxyExternalIPs configuration parameter is added for
AntreaProxy. When set to false, ntreaProxy no longer load-balances
traffic destined to the ExternalIPs of LoadBalancer Services. This is
useful when the external LoadBalancer provides additional capabilities
(e.g. TLS termination) and it is desirable for Pod-to-ExternalIP traffic
to be sent to the external LoadBalancer instead of being load-balanced
to an Endpoint directly by AntreaProxy.
The default behavior is unchanged, i.e. proxyExternalIPs is true by
default.
Note that setting ProxyExternalIPs to false usually only makes sense
when ProxyAll is set to true and kube-proxy is removed from the cluser,
otherwise kube-proxy will still load-balance this traffic.
This feature cannot be leveraged by an external Load Balancer that …
=> Make externalIP proxying configurable for AntreaProxy

cmd/antrea-agent/agent.go, pkg/agent/cniserver/ipam/annotations.go, pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/ipam/antrea_ipam_controller.go, pkg/agent/cniserver/ipam/antrea_ipam_test.go, pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_init.go, pkg/agent/nodeportlocal/npl_agent_init_windows.go, pkg/agent/nodeportlocal/npl_agent_test.go, pkg/apis/crd/v1alpha2/types.go, pkg/ipam/poolallocator/allocator.go, pkg/util/k8s/name.go
Add support for Pod annotation "ipam.antrea.io/ippools" and
"ipam.antrea.io/pod-ips", which allows user to specify IPPool and IP for a
specified Pod.
Support persistent IP for StatefulSet. A StatefulSet Pod will keep its
allocated IP during restart process.
=> [flexible-ipam] Support Pod IPPool/IP annotation and StatefulSet

ci/kind/test-e2e-kind.sh, hack/netpol-generator/test-kind.sh, test/e2e/framework.go, test/e2e/k8s_util.go, test/e2e/nodeportlocal_test.go
And pre-load the image into all Kind Nodes when using Kind for CI
testing.
This is an attempt to mitigate #3119
=> Use unique agnhost Docker image for all e2e tests

multicluster/controllers/multicluster/resourceexport_controller.go
Our imported Service has name but endpoint is without name
which causes the Antrea agent fail to install openflow rule.
so simply remove the name since it's defined by ourself.
=> Remove Service Port Name

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/cmd/multicluster-controller/controller.go, multicluster/cmd/multicluster-controller/options.go, multicluster/config/default/configmap/controller_manager_config.yaml
I found below error in a long running MC controller, so increase the
timeout, and disable leader election by default in config yaml.
```
E0106 07:29:05.501113       1 leaderelection.go:361] Failed to update lock: context deadline exceeded
I0106 07:29:05.895992       1 leaderelection.go:278] failed to renew lease antrea-mcs-ns/6536456a.crd.antrea.io: timed out waiting for the condition
2022-01-06T07:29:05.896Z	DEBUG	controller-runtime.manager.events	Normal	{"object": {"kind":"ConfigMap","namespace":"antrea-mcs-ns","name":"6536456a.crd.antrea.io","uid":"a4de74cd-0441-4140-a78b-acf163055f91","apiVersion":"v1","resourceVersion":"23629919"}, "reason": "LeaderElection", "message": "antrea-mc-controller-6dcb88b9d6-vxqvm_e1b1b0a9-b2b5-471f-b424-b11a34343d64 stopped leading"} …
```
=> Fix leader eletion timeout issue

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/controller-rbac.yml, cmd/antrea-controller/controller.go, pkg/agent/cniserver/ipam/antrea_ipam_controller.go, pkg/controller/ipam/antrea_ipam_controller.go, pkg/controller/ipam/antrea_ipam_controller_test.go, pkg/ipam/ipallocator/allocator.go, pkg/ipam/ipallocator/allocator_test.go, pkg/ipam/poolallocator/allocator.go, pkg/ipam/poolallocator/allocator_test.go, pkg/util/k8s/name.go
* Support continuous IP range allocation in ip allocator
* Support pe-allocating continuous range of IPs from an IP
Pool for StatefulSet. This functionality will be used by
StatefulSets that do not have a dedicated IP Pool annotated.
=> Prepare for Antrea IPAM StatefulSet support

go.mod, go.sum, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, plugins/octant/go.sum
1. Replay multicast cached flows when Agent reconnects to OVS
2. PacketIn all IGMP messages to antrea agent. Since IGMPv1 report uses
the target multicast group as the IP destination, we can't use static
destination IP as a filtier for IGMP messages, otherwise IGMPv1 report
packets would be missing.
Fixes #3184 
=> [Multicast] Bugfix in multicast in IGMP member snooping

ci/jenkins/test-mc.sh, ci/jenkins/test.sh, multicluster/test/e2e/README.md, multicluster/test/e2e/fixtures.go, multicluster/test/e2e/framework.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go, multicluster/test/e2e/util.go, multicluster/test/yamls/clusterset.yml, multicluster/test/yamls/east-member-cluster.yml, multicluster/test/yamls/leader-access-token-secret.yml, multicluster/test/yamls/test-east-serviceexport.yml, multicluster/test/yamls/test-west-serviceexport.yml, multicluster/test/yamls/west-member-cluster.yml
1. build clusters base on the Getting-started of multi-cluster
2. run test cases to export service and try to test the imported service.
This PR is based on #3024 , only the top commit need to be reviewed.
=> Add E2E test for antrea multiclusters

ci/jenkins/test-mc.sh, multicluster/test/e2e/framework.go, multicluster/test/e2e/service_test.go, test/e2e/utils/anpspecbuilder.go
PR based on #3124. Only the last commit is relevant to this PR.
=> Add E2E testcase for ANP toService egress rules on multi-cluster Service 

ci/jenkins/test-mc.sh, pkg/apiserver/apiserver.go
1. Delete deprecated apiservice v1beta1.controlplane.antrea.tanzu.vmware.com to fix the antrea-controller error
2. Build antrea-controller image from the feature branch rather than pull the latest image.
=> Bug fix deprecated apiservice

pkg/agent/util/net_windows.go
Set/Get-VMSwitch could return hostname resolution error in some environments.
The root cause is the remote DNS name didn’t match hostname, then Set/Get-VMSwitch
could return error once it needed to get hostname from DNS name.
This issue can be fixed by adding hostname to configuration.
e.g. Get-VMSwitch -ComputerName $(hostname) -Name %s
=> [Windows] Fix agent initialization error by adjusting VMSwitch commands

build/yamls/elk-flow-collector/logstash/ipfix.yml, ci/kind/test-e2e-kind.sh, docs/network-flow-visibility.md, go.mod, go.sum, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, plugins/octant/go.sum, test/e2e/flowaggregator_test.go, test/e2e/framework.go
Flow-visibility solution is moving away from elk flow collector, we are moving throughput calculation from logstash into flow-aggregator: https://github.com/vmware/go-ipfix/pull/270
This PR makes the necessary changes on Antrea side corresponding to the changes in the above PR. More description can be found on the PR description of the above Go-ipfix PR.
fixes: #2211
=> Add throughput calculation into flow-aggregator

pkg/version/version.go
While this can currently be obtained at runtime, it requires installing
a new package (e.g. gdb) in the antrea-ubuntu Docker image. See
https://dave.cheney.net/2017/06/20/how-to-find-out-which-go-version-built-your-binary
This will make it easier to figure out which version of Go was used to
build a given version of Antrea.
=> Add Go version to full version string for Antrea binaries

pkg/agent/config/node_config.go, pkg/agent/route/route_linux.go, test/integration/agent/route_test.go
The Antrea Agent has logic to periodically sync gateway routes and to
ensure that any route deleted by mistake is restored. However this logic
did not include the subnet route automatically configured by the kernel
when an IP address is configured on the gateway interface. We update the
logic to include this route.
Fixes #3187
=> Restore autoconfed kernel route for gw if missing

multicluster/Makefile, multicluster/hack/generate-manifest.sh
Golicense job is still failed: https://github.com/antrea-io/antrea/runs/4837536108?check_suite_focus=true
1. reuse verify-kustomize.sh to install and verify kustomize.
2. remove some unused Make targets.
=> Fix kustomize path issue

test/e2e/antreaipam_service_test.go, test/e2e/antreaipam_test.go, test/e2e/basic_test.go, test/e2e/framework.go
This PR requires #3141 merged first.
=> [flexible-ipam] Add e2e for StatefulSet

test/integration/agent/route_test.go
A call to route.NewClient needs to be updated. The code no longer builds
because of a merge conflict.
=> Fix integration tests for route client

docs/assets/hns_integration.svg, docs/design/windows-design.md, hack/windows/Clean-AntreaNetwork.ps1, pkg/agent/agent_windows.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/interfacestore/types.go, pkg/agent/util/net_windows.go
Rename the vnic created by Windows host when creating the HNS Network as
the OVS bridge name, and add OVS internal port for the bridge port. Then
OVS uses the vnic created by Windows host directly, and IP/MAC/route
migrations is not needed. With this workflow, the time of losing IP on
the Windows host is cut off.
Fixes #3057 
Signed-off-by: wenying <wenyingd@vmware.com>
=> [Windows] Use Windows management virtual network adapter for OVS bridge

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go
NetworkConfig.TransportIface represents user provided transport interface name. It shouldn't be overridden by the actual transport interface calculated based on default value and user configuration, otherwise code that check its value would think it's set by users and behaves unexpectedly, e.g. getNodeTransportAddrs, leading to log spam.
The patch adds NodeConfig.NodeTransportInterfaceName to represent the actual transport interface. It also corrects some improper variable names and comments.
Fixes #3208
=> Fix log spam in NodeRouteController 

docs/feature-gates.md
With missing feature gates introduced in v1.5: Multicast and
SecondaryNetwork. Documentation for these features will be added in the
future.
=> Update feature gates document

ci/jenkins/README.md, ci/test-conformance-eks.sh
1.17 is no longer supported in EKS, upgrade the version to 1.21.
Update the version information for AKS and GKE.
=> Upgrade default K8s version tested in eks

pkg/controller/traceflow/controller_test.go
The test must wait for cache sync first, otherwise resource creation
events will be missing if the resources are created in-between list and
watch call of an informer. This is because fake clientset doesn't
support watching with resourceVersion. A watcher of fake clientset only
gets events that happen after the watcher is created.
Fixes #3222
=> Fix flaky unit test TestTraceflow

test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2, test/e2e/infra/vagrant/provision.sh
This can be helpful for running e2e test locally with antrea-proxy `proxyAll` feature enabled.
=> Support skip deploying kube-proxy in Vagrant testbed

docs/feature-gates.md
I forgot this new feature gate when I updated the documentation for
Antrea v1.5.
=> Add ServiceExternalIP feature gate to documentation

docs/feature-gates.md
Cherry pick of #3227 on release-1.5.
#3227: Add ServiceExternalIP feature gate to documentation
=> Automated cherry pick of #3227: Add ServiceExternalIP feature gate to documentation

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/apiserver/apiserver.go, pkg/agent/config/node_config.go, pkg/agent/controller/networkpolicy/fqdn.go, pkg/agent/controller/networkpolicy/fqdn_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/apiserver/registry/system/supportbundle/rest.go, pkg/support/dump.go, pkg/support/dump_others.go, test/integration/agent/openflow_test.go, test/integration/agent/route_test.go
Add flags IPv4Enabled/IPv6Enabled in NetworkConfig, which is set in
agent Initialize. The flags are used in other modules directly.
Fixes #2972 
=> Remove unnecessary function call for IPv4/IPv6 enabled

docs/contributors/cherry-picks.md, docs/contributors/github-labels.md, docs/maintainers/release.md
action/backport: Indicates a PR that requires backports.
action/release-note: Indicates a PR that should be included in release notes.
=> Add github labels to indicate actions required to take

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
The previous job name of antrea-all-feature-conformance-for-pull-request
was too long to be accepted by CAPV worker nodes.
We renamed it to antrea-all-conformance-for-pull-request, which worked
well in the current testbed.
Co-authored-by: Zhengsheng Zhou <zhengshengz@vmware.com>
=> [CI] Fix all-feature-conformance test issue by shortening the job name 

ci/jenkins/test-vmc.sh
Cherry pick of #3162 on release-1.2.
#3162: Recover integration test by skipping certificate check
=> Automated cherry pick of #3162: Recover integration test by skipping certificate check

pkg/agent/util/net_windows.go
Cherry pick of #3169 on release-1.2.
#3169: Fix agent initialization error by adjusting
=> Automated cherry pick of #3169: Fix agent initialization error by adjusting

ci/kind/test-e2e-kind.sh, test/e2e/framework.go
To avoid flaky e2e tests caused by image pulling error, use the alpine based image (23.4MB) which is much smaller than the debian one (141MB).
=> Use a smaller nginx image

docs/windows.md
Fixes #3245 .
kube-proxy.yml uses the command `pwsh` which is not a valid command
when the Powershell version is earlier than 6.0.
This commit added this reminder and the command replacement in
windows doc.
=> Add powershell command replacement in windows doc

docs/antrea-network-policy.md
Cherry pick of #3079 on release-1.2.
#3079: Fix typo in antrea-network-policy doc
=> Automated cherry pick of #3079: Fix typo in antrea-network-policy doc

build/images/scripts/install_cni
Otherwise container runtimes such as cri-o would fail to validate the
cni conf if it doesn't find the bins when it resyncs network conf,
triggered by the conf file update event.
Fixes #2531
=> Install cni conf after installing cni bins

docs/node-port-local.md
The nodeportlocal.antrea.io Pod annotation is managed by Antrea. If
users provide or modify the annotation, it may be overwritten by Antrea
or have unexpected behavior.
Fixes #3272
=> Clarify in NPL doc that nodeportlocal.antrea.io is not for users

pkg/agent/nodeportlocal/k8s/npl_controller.go
For ExternalName Services, the selector is meaningless and should be
ignored. Before this patch, the NPL Controller would treat these
Services in the same way as ClusterIP / LoadBalancer Services.
=> Ignore Services of type ExternalName in NodePortLocal Controller

docs/antrea-network-policy.md
markdownlint-cli 0.31.0 adds MD050/strong-style which requires
consistent emphasis/strong style.
=> Fix markdownlint verification MD050/strong-style

test/e2e/infra/vagrant/playbook/roles/common/tasks/containerd.yml, test/e2e/infra/vagrant/playbook/roles/common/templates/crictl.yaml.j2
Set endpoints correctly for containerd to avoid error logs.
=> Configure crictl correctly in Vagrant testbed

.github/workflows/go.yml
To avoid issues such as #3283, pin markdownlint version.
markdownlint version should be upgraded manually when necessary.
=> Pin markdownlint version for consistent verification result

.github/workflows/go.yml, docs/antrea-network-policy.md
Cherry pick of #3283 on release-1.2.
#3283: Fix markdownlint verification MD050/strong-style
=> Automated cherry pick of #3283: Fix markdownlint verification MD050/strong-style

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/manager/manager.yaml, multicluster/config/prometheus/monitor.yaml, multicluster/config/rbac/auth_proxy_service.yaml, multicluster/config/webhook/service.yaml
Update the label of antrea-mc-controller in manifests to make them
consistent as antrea controller and agent.
=> Update label of antrea-mc-controller

CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/README.md
Cherry pick of #3282 on release-1.5.
#3282: Fix typo in CHANGELOG-1.5 and add a link for it
=> Automated cherry pick of #3282: Fix typo in CHANGELOG-1.5 and add a link for it

ci/jenkins/test-mc.sh, multicluster/test/e2e/framework.go
Use Kubernetes upstream nginx image instead of offical nginx image, which makes multi-cluster e2e test faster.
Signed-off-by: hjiajing <hjiajing@vmware.com>
=> Use a smaller nginx image for multicluster e2e test

multicluster/test/e2e/framework.go, test/e2e/k8s_util.go
There might be some issues in Pod exec API that it sometimes doesn't
return error when the probe fails. However, regardless of the issue,
the code should check both err and stderr because the probe tried 3
times. If it checks err only, failure+failure+success would be
considered connected.
Fix #2394
=> Fix AntreaNetworkPolicy e2e test random failures

build/images/base/Dockerfile
Instead of iptables directly.
Antrea uses a Ubuntu 20.04 base container image, for which the default iptables
mode is "legacy". This may not match the iptables mode for the Node OS, which in
turn can create issues:
* Other K8s components (kubelet, kube-proxy) will create rules using the
default iptables mode for the Node. Assumptions about evaluation order
between these rules and the Antrea rules may break.
* The required kernel module for the "legacy" mode (ip_tables) may not be
available on the Node.
The iptables-wrapper is meant to address these issues:
https://github.com/kubernetes-sigs/iptables-wrappers. We install it in the
Antrea container image. The first time Antrea invokes iptables, the wrapper will
determine the underlying iptables mode (for the Node OS) and adjust the iptables …
=> Use iptables-wrapper in Antrea container

build/images/base/Dockerfile
Cherry pick of #3276 on release-1.5.
#3276: Use iptables-wrapper in Antrea container
=> Automated cherry pick of #3276: Use iptables-wrapper in Antrea container

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, test/e2e/framework.go, test/e2e/proxy_test.go
Fix #3301 
When proxyAll is enabled, create a NodePort/LoadBalancer Service whose
externalTrafficPolicy is Cluster, then only an OVS group with all
Endpoints will be installed. If change externalTrafficPolicy of the
Service from Cluster to Local, an OVS group with only local Endpoints
should be also installed since externalTrafficPolicy is Local, but it
is not. This patch fixes the issue that OVS group with only local
Endpoints is not installed when externalTrafficPolicy of Service is
changed from Cluster to Local.
=> Fix NodePort/LoadBalancer issue when proxyAll is enabled

test/e2e/infra/vagrant/playbook/roles/common/tasks/kube.yml
The original link [https://apt.kubernetes.io/](https://apt.kubernetes.io/) is just a redirect to the link [https://packages.cloud.google.com/apt/](https://packages.cloud.google.com/apt/). Use the later one to avoid some redirection issues.
=> Update apt repository link for Kubernetes

pkg/agent/cniserver/ipam/antrea_ipam_controller.go
Avoid running unnecessary code in getIPPoolsByPod function when
no IPAM annotation is present.
=> [flexible-ipam] Optimization on NodeIPAM code path

pkg/apis/crd/v1alpha1/doc.go, pkg/apis/crd/v1alpha2/doc.go, pkg/apis/crd/v1alpha3/doc.go
=> Remove unused openapi marker

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/groups.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/types/groupcounter.go
The existing code maintains OpenFlow group ID allocator under path
pkg/agent/proxy, and it introduces difficulty for other features to
leverage OpenFlow groups
The change moves OpenFlow group ID new/recycle function to a seperate
struct under path pkg/agent/openflow, and leaves the caches inside the
caller package, then we could have a unique group ID allocator.
=> Move group ID allocator under path pkg/agent/openflow

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
Fixes #3262
This commit fixed the issue of Network Policy does not validate protocol and accept wrong configuration.
=> validate the  protocol in the crd schema

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, test/e2e/framework.go, test/e2e/proxy_test.go
Cherry pick of #3295 on release-1.4.
#3295: Fix NodePort/LoadBalancer issue when proxyAll is enabled
=> Automated cherry pick of #3295: Fix NodePort/LoadBalancer issue when proxyAll is enabled

hack/windows/Helper.psm1, hack/windows/Prepare-ServiceInterface.ps1
CI testbed building still failed randomly with unmodified commands.
This issue can be fixed by adding hostname to configuration.
e.g. Get-VMSwitch -ComputerName $(hostname) -Name %s
Refer to #3169
=> Fix remaining VMSwitch command issue

pkg/controller/networkpolicy/validate.go, pkg/controller/networkpolicy/validate_test.go
Fixes #3285.
This PR added some additional validations to ANP, ACNP and CG in
validating webhook. Antrea will validate labels used in ANP, ACNP and
CG under PodSelector, NamespaceSelector and ExternalEntitySelector.
=> Validate labels in ANP/ACNP/CG

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/types/groupcounter.go
Add method IfAllocateNotExist to generate a unique group ID for a Service
if the group ID has not been generated, then return the group ID (new
allocated or already allocated). Method Get is reserved and can be
only to get the allocated group ID.
Fix #3339
=> Add method AllocateIfNotExist to interface GroupCounter in proxy

docs/service-loadbalancer.md
Signed-off-by: Tianyi Huang <hty690@126.com>
Closes #2020
=> Add document for Service of type LoadBalancer

pkg/agent/agent_windows.go
Traffic from the uplink interface will be output to the bridge local
interface directly. When an external client connects to a LoadBalancer
type Service, and the packets of the connection are routed to the
selected backend Pod via the bridge interface, if we do not enable IP
forwarding on the bridge interface, the connection will be discarded
on the bridge interface as the destination of the connection is not the
Node.
=> Enable IP forwarding on the Windows bridge local interface

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go
Fixes #3306.
This PR fixes the nil pointer dereference error while dumping the ovsflows of NetworkPolicy, by adding a nil check on the NetworkPolicyReference attribute of the policyRuleConjunction Object
=> Fix dumping OVS flows of a NetworkPolicy

docs/feature-gates.md
It seems the per-rule example for feature NetworkpolicyStats is missing. 
=> Add a per-rule example for NetworkpolicyStats docs 

.github/workflows/build.yml, .github/workflows/build_tag.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, Makefile, build/images/Dockerfile.build.coverage, build/images/Dockerfile.build.ubi, build/images/base/Dockerfile.ubi, build/images/base/build.sh, build/images/flow-aggregator/Dockerfile, build/images/flow-aggregator/Dockerfile.coverage, build/images/ovs/CentOS.repo, build/images/ovs/Dockerfile.ubi, build/images/ovs/build.sh, ci/jenkins/test-mc.sh, ci/jenkins/test-vmc.sh, ci/jenkins/test.sh, hack/build-antrea-linux-all.sh
Add the required code to build an Antrea image based on Red Hat UBI
(Universal Base Image), which is in used by Red Hat platforms.
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>
=> Support antrea-agent UBI8 based image

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_windows.go, hack/generate-manifest.sh, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/config/agent/config.go
In the current implementation, enabling the AntreaIPAM feature gate will
enable both AntreaIPAM which allocates IPs from IPPools, and Node side
datapath configurations to support traffic forwarding of AntreaIPAM Pods
whose IPs are allocated from IPPools by AntreaIPAM.
This commit adds a separate config parameter - enableBridgingMode - to
antrea-agent, to enable/disable support for AntreaIPAM Pods on a Node.
Only when enableBridgingMode is set to true, Antrea Agent connects the
uplink interface to the OVS bridge, requests IP allocation from
AntreaIPAM and implements traffic forwarding for AntreaIPAM (bridging
mode) Pods. This change is also needed to extend AntreaIPAM for other
IPAM use cases, in addition to IPAM for bridging mode Pods.
=> Add an agent config parameter for enabling flexible IPAM (bridging mode)

test/e2e/proxy_test.go, test/e2e/service_test.go
In NodePort e2e test, a test Service and its backend Pod are
created. The match label is app=agnhost. However, the test
client is also a Pod that has label app=agnhost, but netexec is
not running on the test client. As a result, the test has a 50%
chance of failing. This PR fixes the issue by using a busybox Pod
as test client.
=> Fix NodePort e2e test

pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/flowexporter/exporter/exporter.go, test/e2e/connectivity_test.go
- Fix CT mark matching without range in
pkg/agent/flowexporter/exporter/exporter.go
- Fix typo in test/e2e/connectivity_test.go
- Remove extra blank line in
pkg/agent/apiserver/handlers/ovsflows/handler.go
=> Fix CT mark matching without range in flow exporter

build/yamls/antrea-windows.yml, build/yamls/windows/base/conf/antrea-agent.conf, third_party/proxy/config/config.go
=> [Windows] Enable EndpointSlices support on Antrea windows

multicluster/controllers/multicluster/common/helper.go, multicluster/controllers/multicluster/commonarea/remote_common_area.go, multicluster/controllers/multicluster/commonarea/resourceimport_controller.go, multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go, multicluster/controllers/multicluster/serviceexport_controller.go, multicluster/controllers/multicluster/serviceexport_controller_test.go
Add local cluster ID as an annotation to ServiceExport/Import
which help to simplify the logic to group ServiceExport/Import in
Antctl.
=> Add clusterID annotation to ServiceExport/Import

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/ipfix/ipfix_intermediate.go, pkg/ipfix/testing/mock_ipfix.go, plugins/octant/go.sum, test/e2e/framework.go
This commit adds changes in [go-ipfix v0.5.12](https://github.com/vmware/go-ipfix/releases/tag/v0.5.12).
It fixes some issues leading to the unexpected burst in the throughput calculated in the flow aggregator.
=> Upgrade to go-ipfix v0.5.12

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/controller.yml, pkg/controller/ipam/validate.go, pkg/controller/ipam/validate_test.go
Verify that:
- There are no overlaps between an IPPool ranges while creating and
updating pools.
- Validate that the gateway IP belongs to the same subnet as the IP
range addresses.
Signed-off-by: Kobi Samoray <ksamoray@vmware.com>
=> Validate AntreaIPAM IP ranges

cmd/antrea-agent/agent.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/status_controller_test.go, pkg/agent/types/networkpolicy.go, pkg/controller/egress/controller.go, pkg/controller/egress/controller_test.go, pkg/util/channel/channel.go, pkg/util/channel/channel_test.go, test/e2e/egress_test.go, test/integration/agent/cniserver_test.go
Cherry pick of #3360 on release-1.5.
#3360: Realize Egress for a Pod once its network is created
=> Automated cherry pick of #3360: Realize Egress for a Pod once its network is created

pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go, pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go, pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/networkpolicy_controller.go, test/e2e/antreapolicy_test.go
=> Fix ipBlock referenced in nested ClusterGroup not processed correctly

pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go, pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go, pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/networkpolicy_controller.go, test/e2e/antreapolicy_test.go
Cherry pick of #3383 on release-1.5.
#3383: Fix ipBlock referenced in child ClusterGroup not processed
=> Automated cherry pick of #3383: Fix ipBlock referenced in child ClusterGroup not processed

multicluster/test/e2e/framework.go, test/e2e/k8s_util.go
Cherry pick of #3304 on release-1.5.
#3304: Fix AntreaNetworkPolicy e2e test random failures
=> Automated cherry pick of #3304: Fix AntreaNetworkPolicy e2e test random failures

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/controller-rbac.yml, pkg/agent/agent.go, pkg/agent/nodeportlocal/k8s/annotations.go, pkg/agent/wireguard/client_linux.go
Cherry pick of #3393 on release-1.5.
#3393: Reduce permission of antrea service accounts
=> Automated cherry pick of #3393: Reduce permission of antrea service accounts

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/flow-aggregator.yml, build/yamls/flow-visibility.yml, hack/verify-kustomize.sh, multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/build/yamls/antrea-multicluster-member.yml
This PR upgrades Kustomize from v3.8.8 to v4.4.1 to fix the fields-missing problem in Cronjob patching.
=> Upgrade Kustomize from v3.8.8 to v4.4.1 to fix Cronjob patching bugs

ci/jenkins/README.md, ci/test-conformance-eks.sh
Cherry pick of #3220 on release-1.5.
#3220: Upgrade default K8s version tested in eks
=> Automated cherry pick of #3220: Upgrade default K8s version tested in eks

ci/jenkins/test-mc.sh, docs/antctl.md, docs/troubleshooting.md
Fix below deprecated warning in case it's removed in the future.
```log
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
```
=> Fix deprecated kubectl exec commands

pkg/apiserver/certificate/cacert_controller.go
Webhooks are used by other features besided AntreaPolicy. At the moment,
if someone tries to disable AnteraPolicy and enable Egress for example,
the webhooks would not be using the correct CA cert and the Egress API
would not be usable.
Given that we unconditionally create these webhooks in the Antrea
deployment manifest, it makes sense to unconditionally sync the CA cert
for them.
=> Unconditionally sync CA cert for Controller webhooks

docs/getting-started.md, docs/kubernetes-installers.md, docs/minikube.md
This PR updates the kubernetes-installer documentation
and adds a minikube to the list, also supporting documentation
to deploy antrea in minikube is added.
=> Adding documentation for minikube

test/e2e/framework.go, test/e2e/k8s_util.go
Fixes #3387.
This PR adds a Poll to the deletion of namespace, that is done after
completion of a particular test. So, that the namespaces are deleted
completely and no content remains, so as to prevent race condition when
performing further test.
=> Fix e2e TestClusterGroup on kind flaky

pkg/agent/secondarynetwork/cnipodcache/cache.go
The cache itself uses cache.Indexer which is thread-safe, and so needs
not the mutex to protect cache accesses. The mutex should be  used just
for protecting CNIConfigInfo.PodCNIDeleted, which is written by
CNIServer and read by the secondary network Pod controller.
=> Remove unncessary mutex usage in the secondary network CNI cache

pkg/agent/types/marks.go, test/integration/agent/route_test.go
HostLocalSourceMark is used to mark locally generated packets from Node
net namespace, but it conflicted with bits used by SNATIPMark, leading
to these packets being SNATed mistakenly when there happens to be an
Egress using same mark.
Fixes #3431
=> Fix pkt mark conflict between HostLocalSourceMark and SNATIPMark

test/e2e/infra/vagrant/playbook/roles/common/templates/containerd.conf.j2
Recently provisioning the testbed has been failing with:
containerd: failed to load TOML: /etc/containerd/debug.toml: open /etc/containerd/debug.toml: no such file or directory
I am not sure what changed, so I am just removing the `imports`
directive, which is not present in the sample configuration given at
https://containerd.io/docs/getting-started/.
=> Fix contained configuration for Vagrant testbed

.github/workflows/benchmark.yml
The "check-changes" job is both incorrect and unused.
Incorrect because it ignores changes in the pkg/ directory, which is the
opposite of what it should be doing. This is probably because of poor
naming of the "args" action parameter for the has-changes action (it
should really be something like "ignore-paths").
Unused because the "go-benchmark-checks" will anyway run for all "push"
changes, and the Github workflow itself is configured to only run for
"push" events (on the main branch).
=> Remove unused job in Benchmark Github Workflow

pkg/agent/controller/networkpolicy/packetin.go
If the NetworkPolicy or rule cannot be found in the cache.
I assume that this is ok, since the existing log message used for this
scenario has such a high level (4).
=> Do not panic when processing a PacketIn message for a denied connection

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, docs/design/architecture.md, docs/network-requirements.md, docs/traffic-encryption.md, pkg/agent/agent.go
The 'gre' tunnel type does not work for IPv6 overlays. The correct
tunnel type for OVS would be 'ip6gre'. For dual-stack clusters with both
an IPv4 and an IPv6 overlay, we would need 2 default tunnel ports: one
for IPv4 (with type 'gre') and one for IPv6 (with type 'ip6gre'). This
would add complexity (and require testing) as the code currently assumes
a single default tunnel port. Rather than trying to support IPv6 with
the added complexity that it entails, we choose to fail during Agent
initialization for now if the user-provided tunnel type is 'gre' and the
cluster supports IPv6.
Note that this means that the default manifest for IPsec
(antrea-ipsec.yml) cannot be used in an IPv6 cluster as the tunnel type
defaults to GRE in that case. However, this is not new, and it is better
to fail …
=> Fail in Agent initialization if GRE tunnel type is used with IPv6

pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go
After a Node restarts, IP allocation storage used by host-local plugin
is reset and all Pods on the Node will be recreated. It could happen
that two Pods have same IP in K8s API if the Pod previously owning the
IP hasn't been recreated and another Pod gets the IP assigned when it's
recreated. This leads to an issue in NetworkPolicy as it calculated IPs
to add and remove by getting added and removed Pods first, then getting
IPs from the Pods.
NetworkPolicy rule reconciler didn't handle this case correctly as it
calculated added and removed Pods first, then got IPs to add and remove
from the added and removed Pods. For example, if both Pod A and Pod B
have IP 1.1.1.1, removing Pod B would cause IP 1.1.1.1 to be removed
from dataplane.
This patch changes to calculate IPs to add and remove …
=> Fix duplicate IP case for NetworkPolicy

pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go
Cherry pick of #3467 on release-1.2.
#3467: Fix duplicate IP case for NetworkPolicy
=> Automated cherry pick of #3467: Fix duplicate IP case for NetworkPolicy

pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go
IGMPv3 doesn't have an explicit message to describe a member leaving a
multicast group. Instead, IGMPv3 report message is used, but the group
record has an empty "include" sources. So Antrea Agent checks the group
record type and source number with IGMPv3 report message, and picks out
the groups which the member expects to leave.
Fixes #3388 
=> [Multicast] Support IGMPv3 leave action

test/e2e/egress_test.go, test/e2e/framework.go, test/e2e/proxy_test.go, test/e2e/service_test.go
Wget in busybox doesn't support retry argument. To avoid
failure of related tests as possible, this PR adds a
function to run wget command in busybox Pod in a loop.
=> Fix e2e issue about wget in busybox

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/hack/generate-manifest.sh
Update the default multi-cluster image to
projects.registry.vmware.com/antrea/antrea-mc-controller:latest
which is the same as other antrea manifests.
=> Update default image to vmware registry

build/images/ovs/apply-patches.sh
When using IPv6, the IPsec configuration (ipsec.conf) generated by
ovs-monitor-ipsec for strongSwan is currently not correct. A patch has
been submitted upstream, but until it is accepted and merged, we apply a
temporary version of the patch.
This was tested for a VXLAN overlay in an IPv6-only cluster.
Fixes #3151
=> Fix IPsec for IPv6 overlays

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/serviceexternalip/controller.go, pkg/agent/ipassigner/ip_assigner_linux.go, pkg/agent/ipassigner/ip_assigner_windows.go, pkg/agent/util/net.go, pkg/agent/util/net_test.go, test/integration/agent/ip_assigner_linux_test.go, test/integration/agent/route_test.go
Cherry pick of #3219 on release-1.5.
#3219: Add ignored interfaces names when getting interface by IP
=> Automated cherry pick of #3219: Add ignored interfaces names when getting interface by IP

pkg/agent/types/marks.go, test/integration/agent/route_test.go
Cherry pick of #3430 on release-1.5.
#3430: Fix pkt mark conflict between HostLocalSourceMark and
=> Automated cherry pick of #3430: Fix pkt mark conflict between HostLocalSourceMark and

pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/command_list.go, pkg/antctl/output/output.go, pkg/antctl/raw/multicluster/commands.go, pkg/antctl/raw/multicluster/get/output.go, pkg/antctl/raw/multicluster/get/resourceimport.go, pkg/antctl/raw/multicluster/scheme/scheme.go, pkg/antctl/transform/resourceimport/transform.go
antctl: add multicluster subcommand
Add a new subcommand for antrea multicluster and add get verb for query resources. We could list or get mc resource by antctl mc get <Resource>.
Example:
```bash
NAMESPACE                NAME                                                       KIND
antrea-mcs-ns            antrea-multicluster-test-east-nginx-endpoints              ResourceImport
antrea-mcs-ns            antrea-multicluster-test-east-nginx-service                ResourceImport
antrea-mcs-ns            antrea-multicluster-test-west-nginx-endpoints              ResourceImport
antrea-mcs-ns            antrea-multicluster-test-west-nginx-service                ResourceImport
```
In the future, other verb like `create` or `delete` also could be added to the sub-command mc if it is …
=> Add [antctl mc] command for antrea multicluster resources

build/images/scripts/install_cni, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
Fixes #3422.
This PR adds a new feature by introducing skip_cni_binaries variable, to allow users to skip
installing some of the CNI plugin binaries which they think are not
required for certain reasons.
=> Add SKIP_CNI_BINARIES env var to support skipping installing specified cni bins

pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/ipam/antrea_ipam_controller.go
This commit fixed 2 IP leak issues in below situations with AntreaIPAM enabled:
1. NodeIPAM Pods were deleted.
2. AntreaIPAM Pods were deleted when agent restart.
This PR closes #3333 and closes #3384
=> [flexible-ipam] Fix IP leak issues

.github/workflows/go.yml
We were using a fork temporarily because of a bug that had not been
fixed yet. The bug was fixed upstream a while back and we can now
switch back to the upstream action. It may help with the transient
failures we sometimes observe for this Github workflow.
=> Use upstream action for markdown link check

ci/jenkins/test-mc.sh
Fix issue in multi-cluster e2e tests introduced by #3466.
The pipeline is not picking up the correct image to test because it's saving the newly built image as `antrea/antrea-mc-controller:latest` instead of `projects.registry.vmware.com/antrea/antrea-mc-controller:latest`.
=> Use the correct mc controller image for e2e testing

pkg/antctl/raw/multicluster/commands.go, pkg/antctl/raw/multicluster/get/clusterset.go, pkg/antctl/raw/multicluster/get/resourceexport.go, pkg/antctl/transform/clusterset/transform.go, pkg/antctl/transform/resourceexport/transform.go
antctl multicluster command for clusterset & clustersets, resourceexport
For command lines for ClusterSets, we have 
```
Gel all ClusterSets in default Namesapce
$ antctl mc get clusterset
Get all ClusterSets in all Namespaces
$ antctl mc get clusterset -A
Get all ClusterSets in the specified Namespace
$ antctl mc get clusterset -n <NAMESPACE>
Get all ClusterSets and print them in JSON format
$ antctl mc get clusterset -o json
Get the specified ClusterSet
$ antctl mc get clusterset <CLUSTERSETID>
```
For command lines for ResourceExport, we have
```
Gel all ResourceExports of ClusterSet in default Namesapce
$ antctl mc get resourceexport
Get all ResourceExports of ClusterSet in all Namespaces
$ antctl mc get resourceexport -A
Get all ResourceExports in the specified Namespace
$ antctl mc …
```
=> Antctl for multicluster

docs/multicluster/user-guide.md, hack/.notableofcontents
Renamed the getting-started.md doc to user-guide.md and adjusted the
sections, as the doc is no longer just about Antrea Multi-cluster
installation, but also talks about individual features.
=> Rename and update Antrea Multi-cluster user doc

multicluster/test/e2e/fixtures.go, multicluster/test/e2e/framework.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go, test/e2e/antctl_test.go, test/e2e/antreaipam_test.go, test/e2e/antreapolicy_test.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/batch_test.go, test/e2e/connectivity_test.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/ipsec_test.go, test/e2e/k8s_util.go, test/e2e/main_test.go, test/e2e/multicast_test.go, test/e2e/networkpolicy_test.go, test/e2e/nodeportlocal_test.go, test/e2e/performance_test.go, test/e2e/proxy_test.go, test/e2e/service_externalip_test.go, test/e2e/service_test.go, test/e2e/supportbundle_test.go, test/e2e/tls_test.go, test/e2e/upgrade_test.go, test/e2e/wireguard_test.go
Main changes:
- Export some functions from `/test/e2e.TestData` so that they can be reused by multi-cluster e2e pkg.
- Changed some util functions' receiver from `k8sUtils` to `TestData` so that they can be reused by multi-cluster e2e pkg.
- In multi-cluster e2e pkg, instantiate a new `MCTestData` which has copies of `TestData` of each cluster, instead of creating an entirely new TestData struct. 
=> Share test functions between e2e and multicluster e2e package

ci/jenkins/test-mc.sh, multicluster/test/e2e/antreapolicy_test.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go, multicluster/test/yamls/test-acnp-copy-span-ns-isolation.yml, test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
PR is based on #3424 and #3363. Only the last commit is relevant to this PR.
=> E2E test for MC ACNP copy-span

pkg/agent/route/route_linux.go
Check whether the route and neigh to peer gateway are still needed
and delete the route and neigh if necessary. This can happen when
the traffic encryption mode or traffic encapsulation mode changes.
Fixes #3437
=> Delete IPv6 route and neigh to peer gateway if necessary

pkg/agent/agent_windows.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_windows.go
With noEncap mode the Pod packet to remote Pod/Node is output to the
uplink interface directly. This change modifies the source MAC with the
uplink interface's MAC, so that it doesn't require hybrid configurations
on the host interface.
Fixes #3505 
=> [Windows] Use uplink MAC as source if packet is output to uplink

build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/flow-aggregator.yml
This change fixes Secret containing Clickhouse credential and
corresponding ENV in flow-aggregator missing due to an overlooked
rebase error. Now the username and password for clickhouse is
correctly created and mounted as part of the manifest.
Signed-off-by: Shawn Wang <wshaoquan@vmware.com>
=> [Flow Visibility] Fix Clickhouse credentials missing in FA manifest

docs/feature-gates.md
Add link for the document of ServiceExternalIP feature and remove
the limitation description as well.
Fixes https://github.com/antrea-io/antrea/issues/3230
=> Update document for ServiceExternalIP feature

.github/workflows/docker_update_flow_visibility.yml, build/yamls/clickhouse-operator-install-bundle.yml, build/yamls/flow-visibility.yml, build/yamls/flow-visibility/base/clickhouse.yml, build/yamls/flow-visibility/base/grafana.yml, ci/check-manifest.sh, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/test-flow-visibility.sh, docs/network-flow-visibility.md
In this commit, we add a CI validation job for Flow Visibility. It will
validate the deployment of Flow Exporter, Flow Aggregator, Clickhouse
Server, and Grafana UI dashboard. It will execute daily on Jenkins like
what we have before for the ELK Flow Collector setup.
=> [Flow Visibility] Add CI validation job for flow visibility depolyment files

pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/agent/controller/networkpolicy/cache.go, pkg/antctl/antctl.go, pkg/querier/querier.go
When the `-p <PodName> -n <PodNamespace>` options are used in `antctl get networkpolicy` command, the `-n` option should only be used to identify the Pod being queried, but not filter any internal policies based on the Namespace. Otherwise, all ACNPs applied to the Pod will be filtered out.
This PR also fixes an issue where duplicate policy names are displayed.
=> Fix incorrect results by `antctl get networkpolicy` on Pods

docs/antrea-ipam.md, docs/feature-gates.md
=> [doc][flexible-ipam] Update document for Multiple-VLAN support

ci/jenkins/README.md, ci/test-flow-visibility.sh, hack/generate-manifest-flow-aggregator.sh
In this commit, we updated the hack/generate-manifest-flow-aggregator.sh
with the new configuration of Flow Aggregator introduced in PR #3196 to 
support both FlowCollector and Clickhouse sink.
Signed-off-by: Yongming Ding <dyongming@vmware.com>
=> Update generate-manifest-flow-aggregator.sh with new config

build/yamls/flow-visibility.yml, build/yamls/flow-visibility/base/grafana.yml, docs/network-flow-visibility.md
=> Refactor Grafana and ClickHouse deployment configuration instructions

pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pod_connectivity.go
When NetworkPolicyOnly mode is enabled, PodIPv4CIDR of nodeConfig is nil,
then l3FwdFlowToLocalPodCIDR should not be called.
=> Fix NetworkPolicyOnly mode issue

pkg/agent/route/route_linux.go, test/e2e/basic_test.go
=> Remove stale ClusterIP routes after Antrea restart

test/e2e/egress_test.go, test/e2e/proxy_test.go
Egress feature is enabled by default now.
=> No need to enable Egress FeatureGate in E2E tests

CHANGELOG/CHANGELOG-1.6.md
Cherry pick of #3544 on release-1.6.
#3544: Declare Beta support for proxyAll
=> Automated cherry pick of #3544: Declare Beta support for proxyAll

cmd/antrea-agent/agent.go, pkg/apiserver/handlers/featuregates/handler_test.go, pkg/features/antrea_features.go
A feature might be enabled by default on Linux, but is not supported on
Windows, so set the default feature gates of such features to false on
Windows.
=> Set default feature gates of unsupported features to false on Windows

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
InternalTrafficPolicy is introduced in Kubernetes 1.21. Service Internal
Traffic Policy enables internal traffic restrictions to only route
internal traffic to Endpoints within the Node the traffic originated
from. The "internal" traffic here refers to traffic originated from Pods
in the current cluster. This can help to reduce costs and improve
performance.
=> Support Internal Traffic Policy in AntreaProxy

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/egress.go, pkg/agent/openflow/multicast.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pod_connectivity.go, pkg/agent/openflow/service.go, pkg/agent/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
Functions listed in the following are used to install initial flows. However,
in framework Flexible Pipeline, every feature has a method `initFlows()`
to install initial flows. This PR moves the installation of initial flows in
the following functions to the method `initFlows()` of corresponding
features.
- InstallGatewayFlows() error -> feature PodConnectivity
- InstallClusterServiceCIDRFlows(serviceNets []*net.IPNet) error -> feature Service
- InstallDefaultServiceFlows(nodePortAddressesIPv4, nodePortAddressesIPv6 []net.IP) error -> feature Service
- InstallDefaultTunnelFlows() error -> feature PodConnectivity
- InstallBridgeUplinkFlows() error -> feature PodConnectivity
- InstallExternalFlows(exceptCIDRs []net.IPNet) error  -> feature Egress
Signed-off-by: Hongliang Liu …
=> Unify the installation of initial flows in AntreaProxy

pkg/controller/ipam/validate.go, pkg/controller/ipam/validate_test.go
Validate IP version and prefix length fields.
=> Add more validation of IPPool CRD

ci/jenkins/test-mc.sh, docs/multicluster/user-guide.md, multicluster/controllers/multicluster/resourceexport_controller.go, multicluster/controllers/multicluster/resourceexport_controller_test.go, multicluster/controllers/multicluster/serviceexport_controller.go, multicluster/controllers/multicluster/serviceexport_controller_test.go
In v1.5, we removed original Service name during export/import, but the CNI will fail to realize the Service/Endpoint due to imported Endpoint still has original name, we export Service's name in this PR so we can fix this kind of issue and also support Service with multiple ports.
Fixes #3588
=> Export Service's name to support multi-ports

pkg/agent/controller/networkpolicy/reject.go, test/e2e/antreapolicy_test.go
Fixes #3559
Skip the reject response generation when neither src nor dst are on
current Node.
Re-write the MAC address for `RejectPodLocal` reject type no matter
AntreaIPAM is on or not. And send the packetOut directly to the
dstPod instead of L3Forwarding table.
=> Fix reject loop issue and add error handling

hack/.md_links_config.json
The avinetworks link in the documentation seems to cause link checking
to fail very frequently. The link is not dead, but it is possible that
the website uses DDoS protection, or something else causing the check to
fail.
=> Remove https://avinetworks.com from link checker

.github/workflows/clair.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
From v1 & v2 to v3.
Some small manual changes were required because of breaking changes
introduced between download-artifact@v1 and download-artifact@v2.
=> Upgrade artifact upload and download Github Actions

pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/ipam/antrea_ipam_controller.go, pkg/agent/cniserver/ipam/antrea_ipam_test.go, pkg/ipam/poolallocator/allocator.go, pkg/ipam/poolallocator/allocator_test.go, test/e2e/secondary_network_ipam_test.go
With this change, multiple IPPools can be specified in the CNI IPAM
config, and then antrea-agent will try allocating one IP in each IPPool
for the secondary network interface.
```
An example CNI config:
{
"cniVersion": "0.3.0",
"type": "macvlan",
"master": "enp0s9",
"mode": "bridge",
"ipam": {
"type": "antrea-ipam",
"ippool": ["ippool-v4", "ipppol-v6"]
}
}
```
=> Support multiple IPPools for secondary network IPAM

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
SessionAffinity timeout is implemented using a hard_timeout in
OVS. hard_timeout is represented by a uint16 in the OpenFlow protocol,
hence we cannot support timeouts greater than 65535 seconds. However,
the K8s Service spec allows timeout values up to 86400 seconds for
ClientIP-based SessionAffinity
(https://godoc.org/k8s.io/api/core/v1#ClientIPConfig). For values
greater than 65535 seconds, we need to set the hard_timeout to 65535
rather than let the timeout value wrap around.
For #1578
=> Truncate SessionAffinity timeout values instead of wrapping around

pkg/agent/controller/networkpolicy/reject.go, test/e2e/antreapolicy_test.go
Cherry pick of #3569 on release-1.6.
#3569: Fix reject loop issue and add error handling
=> Automated cherry pick of #3569: Fix reject loop issue and add error handling

pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/openflow/pod_connectivity.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
- MatchRegMark supports matching multiple reg marks
- MatchCTMark supports matching multiple CT marks
- LoadRegMark supports loading multiple reg marks
- LoadToCtMark supports loading multiple CT marks
=> Enhance some methods of FlowBuilder and CTAction

Makefile, hack/update-codegen-dockerized.sh, hack/update-codegen.sh
Some times, the codes we changed just requires mock code re-generation
but we can only run `make codegen` at this moment to run all auto-gen tools
which is a little time-consuming, so move mockgen related codes out of codegen
with standalone Makefile target, developer can use `make mockgen` to
update mock codes separately.
=> Add new target mockgen

pkg/antctl/client.go, pkg/antctl/runtime/runtime.go, test/e2e/antctl_test.go
At the moment is is possible to run antctl in Agent mode from a Windows
Node on which Antrea is runing, but it requires setting the following
environment variables manually:
```
> $Env:POD_NAME="antrea-agent"
> $Env:KUBERNETES_SERVICE_HOST="<ClusterIP>"
> $Env:KUBERNETES_SERVICE_PORT="443"
```
This is not very convenient and it is not documented
either. Additionally, there is no reason to require
KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT in Agent mode. This
requirement is caused by a bug in the antctl code: when antctl is
running inside a Pod, there is no need to resolve the "in-cluster"
Kubeconfig, as we generate this config manually to connect to the Antrea
API server.
In order to make antctl work out-of-the-box for that case, we change the
logic which decides what the antctl …
=> Out-of-the-box "Agent mode" support for antctl on Windows

pkg/agent/agent_windows.go, pkg/agent/util/net_windows.go
1. After creating HNSNetwork, Windows host creates a virtual management
network adapter which takes over the uplink's IP and MAC. Originally
the name with a format "vEthernet ($uplink_name)" is used to get the
virtual adapter, but it might fail when the name is taken by other
adapter. In this change, uses the uplink's IP and MAC to find the
adpter, and uses the prefix "vEthernet" as a filter.
2. Remove the virtual adapter name from the name list to search the
Windows Node transport interface's IP configuration in agent restart
case. This is because the IP is finally moved to OVS bridge
interface, which is renamed from the virtual network adapter. So in a
restart case, a virtual network adapter with the name format 
"vEthernet ($uplink_name)" should not exist.
Fixes #3636 
Signed-off-by: …
=> [Windows] Use IP and MAC to find virtual management adatper

build/yamls/clickhouse-operator-install-bundle.yml
Make this change to keep the default image in ClickHouse-Operator in consistent with the one in flow-visibility.yml
=> Update ClickHouse Server default image in ClickHouse-Operator manifest

pkg/agent/agent_windows.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_windows.go
Cherry pick of #3516 on release-1.2.
#3516: Use uplink MAC as source if packet is output to
=> Automated cherry pick of #3516: Use uplink MAC as source if packet is output to

test/e2e/framework.go
Current busybox image is invalid on harbor.
Before errors are fixed the image source should be replaced.
=> Replace busybox source to fix image errors 

.github/workflows/go.yml
When check-modified-files-only is specified, base-branch will be used as
the branch to compare to find modified files. It defaults to "master"
which doesn't exist in Antrea. It should be set to the target branch of
the pull request. After it's corrected, there is no difference between
main and release branches. Therefore, we could just merge them to one
job.
"Verify docs and spelling" of all PRs failed because of the issue.
=> Fix broken Markdown links check for main branch

test/e2e/infra/vagrant/playbook/roles/control-plane/tasks/main.yml, test/e2e/infra/vagrant/provision.sh
Remove read permissions from 'group' and 'world'. These restricted
permissions are typically recommended by compliance tools, and Helm
complains in case of extra permissions.
=> [Vagrant testbed] Fix kubeconfig permissions

.github/workflows/go.yml
`check-modified-files-only` can only be used for pull_request events (as
per the documentation for the action), and `github.base_ref` is not set
for push events.
At the moment the Github job is failing because it is run for push
events on the main and release branches.
=> Fix broken Markdown links check

docs/network-flow-visibility.md
* fix link to ClickHouse operator YAML manifest
* add note about traffic which is excluded by default in Grafana
dashboards
=> Improve flow visibility documentation

pkg/agent/openflow/client.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pod_connectivity.go, pkg/ovs/openflow/ofctrl_builder.go, test/integration/agent/openflow_test.go
When proxyAll is enabled, kube-proxy can be replaced by AntreaProxy, then
Service traffic and non-Service traffic can be distinguished by ServiceCTMark
and NotServiceCTMark. Service traffic with ServiceCTMark should not bypass
Network Policies, and non-Service traffic generated by kubelet with
NotServiceCTMark should bypass Network Policies.
This PR also fixes the issue that the reply packets of Pod -> local Antrea gateway
bypasses EgressMetricTable.
=> Fix the issue of local probe bypassing flows on Windows

pkg/agent/cniserver/ipam/antrea_ipam.go, pkg/agent/cniserver/types/types.go, test/e2e/secondary_network_ipam_test.go
Support configuring static addresses in the CNI IPAM configuration,
besides allocating IPs from IPPools.
=> Support static addresses in secondary network IPAM

cmd/antrea-agent/options.go
It is for consistency with other features.
=> Return an error when bridging mode is enabled without AntreaIPAM enabled

test/e2e/framework.go
Cherry pick of #3661 on release-1.4.
#3661: Replace busybox source to fix image errors
=> Automated cherry pick of #3661: Replace busybox source to fix image errors

pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, test/e2e/framework.go
Conntrack connection store's polling go routine and flow exporter both access to conntrack connection store, and there's a race condition error. 
In `func (cs *ConntrackConnectionStore) Poll()`, two things happen in sequence:
1. in `deleteIfStaleOrResetConn`, we acquire the lock, reset `conn.IsPresent = false` for all the connections in connection map, and then release the lock (`conn.IsPresent` is used to describe whether the connection exist in conntrack table or not)
2. if a connection is verified to exist in the conntrack table, in `AddOrUpdateConn`, we acquire the lock, set `conn.IsPresent = true`, then release the lock
It is likely to happen, when flow exporter's timer is triggered between 1 and 2, it will grab the lock, and read a connection with `IsPresent` set to false. In the …
=> Fix race condition in ConntrackConnectionStore and FlowExporter

multicluster/controllers/multicluster/serviceexport_controller.go, multicluster/test/integration/serviceexport_controller_test.go
If Service is deleted after it's exported successfully, Endpoint kind
of ResourceExport is not deleted. Fix this bug to delete both Service
and Endpoint kinds of ResourceExport when a Service is deleted but
ServiceExport is still kept.
=> Clean up Endpoint kind of ResourceExport

ci/jenkins/test-mc.sh, multicluster/test/e2e/framework.go, multicluster/test/e2e/service_test.go
1. verify the MC Service from a Pod instead of a Node.
2. fix the ServiceExport manifests file sync bug.
=> Fix e2e test for multicluster service

build/yamls/externalnode/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, docs/feature-gates.md, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/apiserver/apiserver.go, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/config/agent/config.go, pkg/features/antrea_features.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, pkg/util/env/env.go, test/integration/agent/openflow_test.go
1. Use feature gate "ExternalNode" to support Antrea Agent running
on a non-Kubernetes Node.
3. Support Agent running APIServer only on localhost if it is not
running on cluster worker Node.
4. CNIServer is loaded only when Agent is running on cluster worker
Node.
=> [ExternalNode] Add feature gate to run Agent on a non-Kubernetes Node

docs/antrea-proxy.md, docs/feature-gates.md
We add some initial documentation which is long overdue. This is
user-facing documentation and does not cover implementation specifics.
Most notably, it includes information about the configuration options
for AntreaProxy and how they service different use cases.
=> Start AntreaProxy document

docs/network-flow-visibility.md, test/e2e/infra/vagrant/push_antrea.sh
The flow-aggregator will exit if we apply it before grafana and clickhouse are ready. Previously, the sequence in push_antrea is: ELK/Grafana -> FA -> Antrea. I change the sequence to: Antrea -> Grafana (clickhouse ->flow-v) -> FA, because grafana and clickhouse need antrea-agent in order to be ready.
Signed-off-by: Yun-Tang Hsu <hsuy@vmware.com>
=> Adding option Grafana flow collector for push_antrea.sh

cmd/antrea-agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/meters_linux.go, pkg/agent/openflow/meters_others.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pod_connectivity.go, test/integration/agent/openflow_test.go
Since now we no longer rely on the userspace datapath as mentioned in #3591, then
related code can be removed.
=> Remove ovsDatapathType in openflow client structure

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Since antrea.io/ofnet in #3630 is updated to v.5.7 and a CT mark with zero
value can be realized to OVS, the flow with priorityNormal in ConntrackCommitTable
to commit non-Service connections can use NotServiceCTMark to filter non-Service
connections, and the flow with priorityHigh to bypass Service connections can be
deleted.
=> Optimize flows in ConntrackCommitTable

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, .github/workflows/netpol_cyclonus.yml, ci/kind/kind-setup.sh, multicluster/hack/verify-tools.sh
This is the first Kind release in almost a year.
The default K8s image is now v1.23.4.
Thanks to https://github.com/kubernetes-sigs/kind/pull/2375, we no
longer need to explicitly enable route_localnet when testing ProxyAll
and disabling kube-proxy.
=> Update Kind from v0.11.1 to v0.12.0

pkg/agent/cniserver/server.go
In networkPolicy only mode, Antrea is not reponsible for IPAM so ipam
field in cni conf is not set. The code that reads ipam type would panic
if it doesn't check nil first.
For #3699
=> Fix nil pointer dereference in networkPolicy only mode

build/yamls/antrea-aks.yml, build/yamls/chart-values/antrea-aks.yml
AKS overrides KUBERNETES_SERVICE_HOST with a FQDN value. Using
ClusterFirstWithHostNet would lead to antrea-agent start failure.
For #3699
=> Use default dnsPolicy for AKS

docs/security.md
And how to restrict them using Gatekeeper / OPA.
=> Document some of the Antrea Agent RBAC permissions

ci/golicense/README.md
A one-line fix for the wrong link in golicense doc: conf.json -> conf.yml
Signed-off-by: Yongming Ding <dyongming@vmware.com>
=> Fix wrong link in golicense doc

docs/cookbooks/fluentd/README.md
Some of the links in the Fluentd cookbook uses documentation for Fluentbit, which is confusing. Fixing it here.
=> Fix Fluentd Cookbook Links

docs/design/architecture.md, docs/getting-started.md, docs/multicluster/architecture.md
Add the multi-cluster and Service LoadBalancer user doc links to
getting-started.md.
Add the multi-cluster architecture doc link to architecture.md.
=> Add multi-cluster and Service LB doc links

pkg/controller/ipam/antrea_ipam_controller.go, pkg/controller/ipam/antrea_ipam_controller_test.go
A periodic task would go over all IP Pools and clean up
all allocations and reservations for which owner no longer
exists in k8s.
=> Implement garbage collector for IP Pools

test/e2e/framework.go
We use the `node-role.kubernetes.io/<ROLE>` label to identify the
control-plane Node. The `<ROLE>` we use needs to depend on the K8s
version because:
- before K8s v1.20, the label is `node-role.kubernetes.io/master`
- starting with K8s v1.24, the label is `node-role.kubernetes.io/control-plane`.
- in between, both labels are used by K8s
However, the function used to determine the correct label to use based
on the K8s version was called *before* the K8s server version was
actually determined, so it was always returning
`node-role.kubernetes.io/master`. This was causing tests to fail for K8s
v1.24 (which has just been released), since the label no longer exists
in that version.
=> Fix identification of control-plane Node in e2e test framework

cmd/antrea-agent/agent.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/multicast/mcast_controller.go, pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go, pkg/agent/multicast/mcast_route_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/framework.go, pkg/agent/openflow/multicast.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/types/event.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/testing/mock_openflow.go, pkg/util/channel/channel.go, pkg/util/channel/channel_test.go, test/e2e/multicast_test.go, test/integration/agent/openflow_test.go, test/integration/ovs/ofctrl_test.go
1. Add local Pod receivers into an OpenFlow type "all" group for each
multicast group, and use such groups in the flow actions. Remove a Pod
from group buckets if the Pod has left the multicast group or is deleted
before leaving the multicast group.
2. Improve e2e tests.
=> [Multicast] Use group as flow actions for multicast traffic

build/yamls/flow-visibility.yml, build/yamls/flow-visibility/base/clickhouse.yml, build/yamls/flow-visibility/base/provisioning/datasources/create_table.sh, build/yamls/flow-visibility/patches/chmonitor/chMonitor.yml, build/yamls/flow-visibility/patches/e2e/imagePullPolicyClickhouse.yml, build/yamls/flow-visibility/patches/pv/createLocalPv.yml, build/yamls/flow-visibility/patches/pv/createNfsPv.yml, build/yamls/flow-visibility/patches/pv/mountPv.yml, build/yamls/flow-visibility/patches/ram/mountRam.yml, docs/network-flow-visibility.md, hack/generate-manifest-flow-visibility.sh, plugins/flow-visibility/clickhouse-monitor/go.mod, plugins/flow-visibility/clickhouse-monitor/go.sum, plugins/flow-visibility/clickhouse-monitor/main.go
This commit supports deploying ClickHouse with Persistent Volume. It provides examples using Local PV, NFS PV or other customized StorageClass.
=> Support ClickHouse deployment with Persistent Volume

build/charts/antrea/templates/agent/clusterrole.yaml, build/charts/antrea/templates/antctl/clusterrole.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/handlers/serviceexternalip/handler.go, pkg/agent/controller/serviceexternalip/controller.go, pkg/agent/controller/serviceexternalip/controller_test.go, pkg/antctl/antctl.go, pkg/querier/querier.go, test/e2e/antctl_test.go, test/e2e/service_externalip_test.go
Remove the update permission for services/status of antrea-agent
service account. Remove the optimization for ExternalTrafficPolicy
setting to Local cases in ServiceExternalIP feature accordingly.
=> Reduce permission of antrea-agent service account

build/charts/antrea/templates/crds/networkpolicy.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml
Add externalEntitySelector in ANP appliedTo field. ACNP is not
supported for EntitySelector yet.
=> [ExternalNode] Support applying ANP to ExternalEntity

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller.yml, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/performance_test.go
Cherry pick of #3731 on release-1.6.
#3731: Fix tolerations for Kubernetes >= 1.24
=> Automated cherry pick of #3731: Fix tolerations for Kubernetes >= 1.24

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-kind.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/antctl.yml, cmd/antrea-agent/agent.go, pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/handlers/serviceexternalip/handler.go, pkg/agent/controller/serviceexternalip/controller.go, pkg/agent/controller/serviceexternalip/controller_test.go, pkg/antctl/antctl.go, pkg/querier/querier.go, test/e2e/antctl_test.go, test/e2e/service_externalip_test.go
Cherry pick of #3691 on release-1.5.
#3691: Reduce permission of antrea-agent service account
=> Automated cherry pick of #3691: Reduce permission of antrea-agent service account

test/e2e/framework.go
Cherry pick of #3728 on release-1.6.
#3728: Fix identification of control-plane Node in e2e test
=> Automated cherry pick of #3728: Fix identification of control-plane Node in e2e test

.github/workflows/kind.yml, ci/kind/test-e2e-kind.sh
This change fixes a couple of minor issues in current Kind e2e test:
- GitHub Kind workflow cleanup not waiting for flow visibility job
- test-e2e-kind.sh pulling the wrong busybox image
- FlowAggregator image being wrongly declared in no-FA e2e test
Signed-off-by: Shawn Wang <wshaoquan@vmware.com>
=> Fix Flow Visibility Kind E2E Test Issues

ci/test-conformance-gke.sh
1. Use containerd runtime as creation of node pools using node images
based on Docker container runtimes is not supported in GKE v1.23,
which is now the default version.
2. Pin conformance image version to v1.20.15 as there is a problem with
the netpol suite added in v1.21.0 when running on GKE.
For #3762
=> [CI] Fix GKE test

ci/test-conformance-gke.sh
Cherry pick of #3771 on release-1.6.
#3771: Fix GKE test
=> Automated cherry pick of #3771: Fix GKE test

ci/test-conformance-gke.sh
GKE now uses containerd, the test script should load image to correct
namespace via ctr, instead of docker CLI.
Related to #3771
=> [CI] Fix image loading in GKE

ci/test-conformance-gke.sh
Cherry pick of #3779 on release-1.6.
#3779: Fix image loading in GKE
=> Automated cherry pick of #3779: Fix image loading in GKE

Makefile
The script is currently not executable, which gives an error when
committing:
```
hint: The '.git/hooks/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```
=> Make pre-commit hook script executable

build/images/scripts/install_cni
To prevent init container from crashing due to`unbound variable` when the env var is unset.
=> Tolerate unset SKIP_CNI_BINARIES env var

test/e2e/connectivity_test.go
In case of count mismatch, we dump flows and groups to help with
troubleshooting.
See #3648
=> Dump flows and groups if TestConnectivity/testOVSFlowReplay fails

ci/kind/validate-metrics-doc.sh
In case of failure, the script was exiting right away, without
displaying the error message.
=> Fix ci/kind/validate-metrics-doc.sh script

cmd/antrea-agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/packetin.go, pkg/agent/openflow/testing/mock_openflow.go
Currently, packetIn reason only supports 0 and 1. There is no more available packetIn reasons
as traceflow and antreaPolicy use both. Multicast reuses packetIn reason with antreaPolicy, and
uses different register bit to indicate the real reason. There is no queue for packetIn reason
'PacketInReasonNP' if antreaPloicy is disabled. And multicast will not work then.
This patch fixes https://github.com/antrea-io/antrea/issues/3808
=> [multicast] fix the issue multicast does not work if antreaPolicy is disabled

cmd/antctl/main.go, cmd/antrea-agent-simulator/main.go, cmd/antrea-agent/main.go, cmd/antrea-controller/main.go, cmd/flow-aggregator/main.go, multicluster/cmd/multicluster-controller/leader.go, multicluster/cmd/multicluster-controller/main.go, multicluster/cmd/multicluster-controller/member.go, pkg/antctl/antctl_test.go, pkg/antctl/command_list.go, pkg/log/log.go, pkg/log/log_file.go, pkg/log/log_file_test.go
K8s is deprecating most of the klog files that we use in Antrea (e.g.,
--log_file). To avoid any disruption (and to avoid the deprecation
warnings which are now displayed when running an Antrea component), we
stop using k8s.io/component-base/logs and instead configure klog
directly.
There is no significant change in the code base, as klog is still used
as the logging facade. We use klog as the logging backend (same as
before), with the possibility to move to something else in the future.
Fixes #3786
=> Stop using k8s.io/component-base/logs to configure logging

pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/openflow/packetin.go
When assign values to IP addresses, we were doing shallow copy by
assignment. This PR changes shallow copy to deep copy to avoid
unexpected IP addresses changes due to pktIn memory address reuse.
Fixes: #3795 
=> Change deny connections IP address assignment methods

pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/types.go
As an ExternalEntity is generated according to one Interface defined
in an ExternalNode, one InterfaceConfig is created for the ExternalEnity
accordingly.
For ExternalNode scenario, Antrea Agent should connect the host network
interface to OVS as the uplink, and create a new host internal port to
take the uplink's network configurations. An IntefaceConfig for
ExteranlEntity uses the name of the host internal port, and maintains
the OpenFlow ports of the OVS port pair.
=> [ExternalNode] Add InterfaceConfig type for ExternalEntity

ci/jenkins/test.sh, test/e2e/service_test.go
Add support K8s>=1.20 for e2e.
Since K8s 1.20, the master role is changed to "control-plane,master".
Since K8s 1.21, service IPFamilies cannot be set to IPv4 in an IPv6 only cluster.
Since K8s 1.22, antrea-prometheus must be deleted first to avoid Pod stuck in Terminating state.
=> [e2e] Support K8s>=1.20

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, hack/generate-manifest.sh, pkg/agent/multicast/mcast_controller.go, pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go, pkg/config/agent/config.go, test/e2e/framework.go
For multicast, IGMP query is sent by antrea-agent every 125 seconds. This patch makes IGMP query interval configurable.
=> multicast: make igmp query interval configurable

cmd/antrea-agent/agent.go, multicluster/test/e2e/antreapolicy_test.go, test/e2e/antreaipam_service_test.go, test/e2e/antreaipam_test.go, test/e2e/antreapolicy_test.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/batch_test.go, test/e2e/clustergroup_test.go, test/e2e/connectivity_test.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/k8s_util.go, test/e2e/multicast_test.go, test/e2e/networkpolicy_test.go, test/e2e/nodeportlocal_test.go, test/e2e/performance_test.go, test/e2e/providers/exec/docker.go, test/e2e/proxy_test.go, test/e2e/service_externalip_test.go, test/e2e/service_test.go, test/e2e/traceflow_test.go, test/e2e/upgrade_test.go, test/e2e/wireguard_test.go
Fixes #3480
Fixes #3574
Created different namespaces for different e2e tests, so that the test
should not be delayed because of waiting for namespace deletion from
prior tests.
Time Statistics:
```txt
Name                               old time    new time
antrea-e2e test                    2692.584s   2316.626s
antrea-e2e test                    2640.578s   2309.422s
```
Removed stale TODO comment from agent.go file.
Co-authored-by: Zhengsheng Zhou <zhengshengz@vmware.com>
=> Create different namespaces for different e2e tests

pkg/agent/route/route_linux.go
When a LoadBalancer with ingress IP is created, corresponding route
for the ingress IP is also installed. When deleting the LoadBalancer,
corresponding route should be also uninstalled. Before uninstalling
the route, if the route is removed, then deleting the route will
get a failure and return an error. The error will trigger LoadBalancer
deletion again, and obviously, deleting the route will get a failure
and return an error another time, resulting in an error loop. This PR
fixes error loop by printing log instead of returning error when getting
the error "no such process" (such error means that the route expected to
be deleted doesn't exist).
=> Fix error loop caused by failure to delete a non-existing route

pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/antctl/raw/traceflow/command_test.go
* "%w" can only be used only in 'fmt.Errorf'
* TestReconcilerReconcile should check the call's argument
=> Improve unit tests

test/integration/ovs/ofctrl_test.go, test/integration/ovs/openflow_test_utils.go
1. The integration test supports dump OpenFlow test with table name
or table ID. The issue is the expected flow uses the ID to represent
table, while the actual flow from OVS uses table name, so the
comparison failed. The fix is using a separte variable for the
expected table, which is overwritten in the retry.
2. Improve the test case that deleting flows with a special cookie. Add
retry mechnism when dump flows from OVS, to avoid comparison with a
status that OVS does not complete flow realization
Fixes #3213 
=> Fix OpenFlow flaky errors in the integration tests

test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
Follow up on #3506. This PR replaced the leftover usages of
the old namespaces "antrea-test" with the new namespace, to
fix the consistent failures on the FlowAggregator e2e test.
=> Fix inconsistent namespaces used in Flow Aggregator e2e test

pkg/agent/controller/egress/egress_controller.go, pkg/agent/ipassigner/ip_assigner.go, pkg/agent/ipassigner/ip_assigner_linux.go, pkg/agent/ipassigner/ip_assigner_windows.go, pkg/agent/ipassigner/testing/mock_ipassigner.go, test/integration/agent/ip_assigner_linux_test.go
Check the arp_ignore sysctl value of the transport interface
and start a userspace ARP responder if it has a value other
than 0.
Copy the assigned IPs on the dummy interface to the ARP/NDP
responders on initializing to fix an issue that the responders
may not work as expected after the agent restarts.
Fixes: #3804
=> Fix Egress not working with kube-proxy IPVS strictARP mode

build/yamls/antrea-eks-node-init.yml, ci/test-conformance-eks.sh
Containerd is available as an alternative to docker since EKS
v1.21. Starting with EKS v1.23, containerd will also be the default
container runtime. Currently antrea-eks-node-init.yml assumes that
docker is always the container runtime, which means that Antrea cannot
be run on EKS clusters using containerd. We fix this by adding support
for containerd.
We also make a couple of improvements to the startup script in
antrea-eks-node-init.yml, to ensure that it can be run again if the
contents of the script change, which is useful for testing and may
also be useful to roll out patches.
Finally, we update our EKS CI to test with containerd instead of docker,
since containerd will be the default soon.
Fixes #3471
=> Add support for containerd to antrea-eks-node-init.yml

cmd/antrea-agent/options.go, pkg/features/antrea_features.go
* Set default IPsec authentication mode to avoid Agent crash on
Windows caused by config missing.
* Add `IPsecCertAuth` to unsupported feature gate on Windows.
Fixes: #3848
=> Set default IPsec authentication mode

docs/multicluster/api.md, docs/multicluster/assets/sample-clusterset.svg, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, hack/.notableofcontents, multicluster/apis/multicluster/v1alpha1/clusterclaim_types.go, multicluster/config/samples/clusterset_init/multicluster_clusterset_template.yaml, multicluster/config/samples/clusterset_init/multicluster_leader_access_token_template.yaml, multicluster/config/samples/clusterset_init/multicluster_membercluster_template.yaml, multicluster/config/samples/multicluster_v1alpha1_clusterclaim.yaml, multicluster/test/integration/suite_test.go, multicluster/test/yamls/clusterset.yml, multicluster/test/yamls/east-member-cluster.yml, multicluster/test/yamls/west-member-cluster.yml
Add a quick start guide.
Update the user guide with Multi-cluster Gateway.
=> Update multi-cluster user guide and templates

docs/multicluster/antctl.md, multicluster/apis/multicluster/v1alpha1/clusterclaim_types.go, multicluster/test/yamls/clusterset.yml, multicluster/test/yamls/east-member-cluster.yml, multicluster/test/yamls/west-member-cluster.yml, pkg/antctl/antctl.go, pkg/antctl/raw/multicluster/add/member_cluster.go, pkg/antctl/raw/multicluster/commands.go, pkg/antctl/raw/multicluster/create/access_token.go, pkg/antctl/raw/multicluster/create/clusterclaim.go, pkg/antctl/raw/multicluster/create/clusterset.go, pkg/antctl/raw/multicluster/delete/clusterclaim.go, pkg/antctl/raw/multicluster/delete/clusterset.go, pkg/antctl/raw/multicluster/delete/member_cluster.go, pkg/antctl/raw/multicluster/deploy/deploy_helper.go, pkg/antctl/raw/multicluster/deploy/leader_cluster.go, pkg/antctl/raw/multicluster/deploy/member_cluster.go
Deploy multi-cluster ClusterSet in antctl command.
The users could just input `antctl mc create` or `antctl mc add` to create a new ClusterSet or add a member cluster to a existing ClusterSet rather than edit YAML files.
There are three verb in `antctl mc` command, `add`, `create` and `delete`. Use for creating ClusterSet, updating ClusterSet and deleting ClusterSet.
Signed-off-by: hjiajing <hjiajing@vmware.com>
=> Multi-cluster bootstrap in antctl

pkg/antctl/raw/helper.go, test/e2e/antctl_test.go, test/e2e/framework.go
Command "antctl proxy --agent-node" requires the information from AntreaAgentInfo.
As a result, we need to make sure the content of AntreaAgentInfo is populated before
we run the command.
Since we recently move AntreaAgentInfo creation from agent to controller, agent may
not set the content for AntreaAgentInfo when it starts if controller has not created the AntreaAgentInfo.
In this case, it will take a minute for agent to update the content in its next try.
This change adds retry logics in the antctl proxy e2e test and it will only invoke the command
after AntreaAgentInfo is ready.
Fixes:https://github.com/antrea-io/antrea/issues/3856
=> [ExternalNode] Fix antctl e2e test

pkg/agent/openflow/pipeline.go, pkg/agent/openflow/service.go, test/integration/agent/openflow_test.go
Fix #3806
Currently, when Egress and AntreaIPAM are enabled, there are several flows in
L3ForwardingTable like the follows:
```
1. table=L3Forwarding, priority=190,ip,reg0=0/0x200,reg8=0/0xfff,nw_dst=10.10.0.0/24 actions=resubmit(,L2ForwardingCalc)
2. table=L3Forwarding, priority=190,ct_mark=0x10/0x10,reg0=0x200/0x200,reg4=0/0x100000 actions=mod_dl_dst:d2:35:24:7f:3a:f8,load:0x2->NXM_NX_REG0[4..7],resubmit(,L3DecTTL)
3. table=L3Forwarding, priority=190,ct_mark=0x10/0x10,reg4=0x100000/0x100000 actions=resubmit(,L3DecTTL)
4. table=L3Forwarding, priority=190,ct_state=-rpl+trk,ip,reg0=0x3/0xf actions=resubmit(,EgressMark)
5. table=L3Forwarding, priority=190,ct_state=-rpl+trk,ip,reg0=0x1/0xf actions=mod_dl_dst:d2:35:24:7f:3a:f8,resubmit(,EgressMark)
6. table=L3Forwarding, priority=0 …
```
=> Optimize the flows for forwarding the packets with unknown destination in L3ForwardingTable

ci/cluster-api/vsphere/templates/cluster.yaml
Cherry pick of #3846 on release-1.6.
#3846: Switch the storage of CAPV cluster to vSan
=> Automated cherry pick of #3846: Switch the storage of CAPV cluster to vSan

test/e2e/prometheus_test.go
Add retry to TestPrometheus to solve intermittent failure.
=> [e2e][flexible-ipam] Fix TestPrometheus failed

pkg/agent/nodeportlocal/npl_agent_test.go
The failed case has updated both Service and Pod.
The issue happens when Service update is processed by NPL controller before Pod update.
In this case, the pod2 annotation was fully removed firstly.
Then NPL controller added a new nodeport with both tcp and udp rules to pod2 by service update.
As the result, the pod2 annotation was:
'[{80 10.10.10.10 61002 tcp [tcp]} {80 10.10.10.10 61002 udp [udp]}]'.
issue https://github.com/antrea-io/antrea/issues/3847
The fix ensures the execution sequence to avoid unexpected annotation in race condition.
Annotation after fix:
'[{80 10.10.10.10 61001 tcp [tcp]} {80 10.10.10.10 61001 udp [udp]}]'
=> Fix random NPL unit test failure

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/agent/controller/trafficcontrol/controller.go, pkg/agent/controller/trafficcontrol/controller_test.go, pkg/agent/interfacestore/types.go, pkg/agent/openflow/pipeline_test.go, pkg/apis/crd/v1alpha2/register.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/e2e/trafficcontrol_test.go, test/integration/ovs/ovs_client_test.go
For #3324 
The Antrea Agent is responsible for realizing the traffic control request. 
It watches the TrafficControl resources from the K8s API server and manages the container traffic with OpenFlow rules. Specifically, the agent executes the following steps for a TrafficControl resource:
=> Add trafficControlController to handle TrafficControl requests

docs/antrea-network-policy.md
Changes include:
- Adding more examples and usage of the `namespaces match: self` field.
- Refining the strict-ns-isolation sample yaml so that it does not select core-dns Pods in appliedTo.
- Reorganized sections for better readability.
- Adding note about indeterministic behavior for conflicting rules. 
- Addressing typos and grammar issues.
=> Improve documentation for Antrea-native policy

pkg/agent/config/node_config.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_test.go, pkg/agent/openflow/service.go, pkg/agent/proxy/proxier.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go
For a NodePort connection sourced from external network or local Node,
destination IP will be DNATed with a virtual IP, then the connection
will be forwarded to OVS via Antrea gateway. However, in UnSNATTable,
a flow is installed to unSNAT replied packets of SNATed connections by
matching the virtual IP as destination IP. The flow is like the following:
```
table=UnSNAT, priority=200,ip,nw_dst=169.254.0.253 actions=ct(table=ConntrackZone,zone=65521,nat)
```
Note that, the request packets of a DNATed NodePort connection are also
matched by the flow above, but it is unnecessary. To optimize the
performance of NodePort, another virtual IP is used to DNAT NodePort
connections.
TCP_RR and TCP_CRR improvement is as fowllows:
```
Test      old TPS     new TPS    delta
TCP_CRR   3510.28 …
```
=> Optimize NodePort performance by reducing request packets CT actions

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/controller/networkpolicy/fqdn.go, pkg/config/agent/config.go, pkg/util/ip/ip.go, pkg/util/ip/ip_test.go, test/e2e/antreapolicy_test.go
IPv6 address must be wrapped with "[]" when used in network API.
This patch ensures that the auto-discovered and the user-provided DNS
servers use correct format. It also adds the missing configuration
"dnsServerOverride" to the configuration file.
Fixes #3873
=> Fix FQDN policy support for IPv6

ci/jenkins/test-mc.sh, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, hack/release/prepare-assets.sh, multicluster/Makefile, multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml, multicluster/config/overlays/leader-ns/kustomization.yaml, multicluster/config/overlays/leader-ns/member_cluster_role.yaml, multicluster/config/overlays/leader-ns/member_cluster_rolebinding.yaml, multicluster/config/overlays/leader-ns/member_cluster_serviceaccount.yaml, multicluster/config/overlays/leader-ns/prefix_transformer.yaml, multicluster/config/overlays/leader-ns/webhook_rbac.yaml, multicluster/hack/generate-manifest.sh, multicluster/test/yamls/clusterset.yml, multicluster/test/yamls/east-member-cluster.yml, multicluster/test/yamls/leader-access-token-secret.yml, multicluster/test/yamls/test-acnp-copy-span-ns-isolation.yml, multicluster/test/yamls/west-member-cluster.yml, pkg/antctl/raw/multicluster/deploy/deploy_helper.go
Change th default Namespace from `changeme` to `antrea-multicluster`
for leader manifest, so user can deploy leader controller without any Namespace
replacement step by default.
=> Change the default Namespace in leader manifest

docs/egress.md, docs/service-loadbalancer.md
=> Fix pool CRD format in egress.md and service-loadbalancer.md

docs/cookbooks/ids/README.md, docs/cookbooks/ids/resources/suricata.yml, docs/feature-gates.md, docs/traffic-control.md
* Add a document to introduce the feature
* Add a cookbook to describe how to use Antrea with Suricata to provide
IDS to Pods
For #3324
=> Add docs for TrafficControl feature

ci/jenkins/test-mc.sh
Here is a CI bug reported by @Dyanngg  when he was running e2e test, after debug with him, we found it's caused
by incorrect if condition check:
The if condition will always be true if a bool type of variable is surrounded with `[[]]`.
Both formats `if ${IS_CONTAINERD};then...` or `if [[ ${IS_CONTAINERD} == true ]]; then...`
works, here we refine it as `if ${IS_CONTAINERD};then...`.
The new MC e2e enables both containerd and gateway, so this bug doesn't impact new MC e2e CI job. It only impacts old e2e job which is deprecated but might be used for old release's verification.
=> Fix mc e2e CI

docs/egress.md, docs/service-loadbalancer.md
The issue was fixed in Antrea v1.7.0. Update the Egress and Servic
Load-balancing documents for that.
=> Update the Egress - IPVS interoperability issue in documents

cmd/antrea-agent/options.go, pkg/config/agent/config.go
Some distros have exposed the multicastInterfaces option and made it
uncommented in the config file. antrea-agent would crash if a cluster
upgrades to v1.7.0 but doesn't remove the option. This patch adds the
option back and deprecates it in a compatible manner.
=> Deprecate the multicastInterfaces option

ci/jenkins/test.sh
* Update testbed to 1.24 with containerd runtime support.
* Add a new jumper node on testbed, which support building images with docker and delivering files to containerd nodes.
* Adjust script to run test on new jumper node.
=> Update latest CI testbed to 1.24 and adjust related script 

test/e2e/multicast_test.go, test/e2e/networkpolicy_test.go
Cherry pick of #3803 on release-1.7.
#3803: Add multicast statistics e2e tests
=> Automated cherry pick of #3803: Add multicast statistics e2e tests

ci/kind/kind-setup.sh, docs/kind.md
* `--ip-family` can now specify `dual` to create a dual-stack cluster
* Use kind default podCIDR when `--pod-cidr` is not set to make deploying ipv6 or dual-stack clusters easier
* Add `--k8s-version` to specify the Kubernetes version of the cluster
=> Add dual-stack and K8s version options for kind-setup.sh

docs/multicluster/architecture.md, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md
Revise the descriptions about Multi-cluster Gateway configuration.
Add descriptions about the `gateway-ip` annotation.
Remove unnecessary descriptions about implementations from the user
documents.
=> Revise Multi-cluster Gateway descriptions in user docs

test/e2e/antreapolicy_test.go, test/e2e/multicast_test.go, test/e2e/traceflow_test.go
There were many unnecessary sleeps and checks in TestAntreaPolicy:
* NetworkPolicies, Services, Tiers, Groups are created and deleted synchronously. There is no point to do existence check.
* For Antrea native policies, check their realization status before traffic tests. For Kubernetes NetworkPolicy, we simply wait for 100ms instead of 2s. For Kubernetes Service, we wait for 1s because the minInterval of AntreaProxy's BoundedFrequencyRunner is 1s.
* For port range tests, test 3 ports instead of 6 ports.
With above changes, total execution time can be reduced more than 500s.
=> Reduce e2e execution time

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/openflow/client.go, pkg/agent/openflow/cookie/allocator.go, pkg/agent/openflow/externalnode_connectivity.go, pkg/agent/openflow/framework.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/util/net.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, test/e2e/flowaggregator_test.go, test/e2e/performance_test.go
1. Set up Openflow pipeline for ExternalNode
2. Install Openflow entries for ExternalNode connectivity
3. Install Openflow entries for ANP on ExternalNode case
4. Install Openflow entries to bypass traffic to/from special peer address on a protocol.
5. Resolve e2e test failures in flow visiblity case introduced by the OVS pipeline change.
=> [ExternalNode] Agent datapath implementation

multicluster/controllers/multicluster/leader_clusterset_controller.go, multicluster/controllers/multicluster/member_clusterset_controller.go, multicluster/controllers/multicluster/memberclusterannounce_controller.go, multicluster/controllers/multicluster/memberclusterannounce_controller_test.go, multicluster/controllers/multicluster/mock_membercluster_status_manager.go
When the ClusterSet is deleted in leader Namespace, there will be
a nil pointer issue due to data inconsistency. This issue will cause
leader controller crash and restart. Refined codes to make data
consistent.
```
leader_clusterset_controller.go:72] "Received ClusterSet delete" config=""
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x188b9b1]
goroutine 274 [running]:
antrea.io/antrea/multicluster/controllers/multicluster.(*MemberClusterAnnounceReconciler).processMCSStatus(0xc00052ff20)
/antrea/multicluster/controllers/multicluster/memberclusterannounce_controller.go:181 +0x331
...
```
Fixes #3918
=> Fix nil pointer issue when clusterset is deleted in leader

pkg/util/externalnode/externalnode.go
When ExternalNode interface name is not empty, we used to use
[ExternalNode name]-[Interface name] to be the generated ExternalEntity name.
However, interface name may be not satisfied with the regex check of Kubernetes
object name.
With this fix, when interface name is empty, we now use
[ExternalNode name]-[First four characters of hashed interface name] to ensure that
the generated ExternalEntity name is legal.
=> [ExternalNode] Fix ExternalEntity name generation rules

docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, multicluster/apis/multicluster/v1alpha1/multiclusterconfig_types.go, multicluster/controllers/multicluster/leader_clusterset_controller.go, multicluster/controllers/multicluster/leader_clusterset_controller_test.go, multicluster/controllers/multicluster/member_clusterset_controller.go, multicluster/controllers/multicluster/node_controller.go
1. Update GatewayIPPrecedence to support "external/internal" option
which is equal to `public/private`.
2. Update MC doc to add more columns info.
3. Exclude leader in the totalClusters in ClusterSet status since MC
supports one leader only.
=> Update Precedence config and resources output

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/config/node_config.go, pkg/agent/controller/networkpolicy/fqdn.go, pkg/agent/controller/networkpolicy/fqdn_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reject.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/openflow/client.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/multicast.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/openflow/pod_connectivity.go, pkg/agent/openflow/service.go, test/integration/agent/openflow_test.go
Originally the OpenFlow entries are using static port numbers for
gateway/tunnel/uplink which are used in the ofport_request fields in OVS
port creation. This is possible to introduce traffic issues if the
actual numbers assigned by OVS are different from the requests.
With this change, the predefined port numbers are still used in the OVS
port creation request, and save the actual port numbers in NodeConfig
after the OVS ports are created. And for the OpenFlow entries, the
actual port numbers are used.
Fixes #3409 
=> Support dynamic ofport on OVS gateway/tunnel port

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
The concurrent conflict is mainly introduced by multi-cluster integration test
since it's not running inside a docker container before. We can remove the
limitation since it's already supported to run multi-cluster integration
in a docker container.
=> Remove concurrent limit for integration jobs

ci/jenkins/test-vmc.sh, ci/jenkins/test.sh
The role of K8s control plane might be `control-plane`, `control-plane,master`
or `master` in different versions, so refine the script to handle K8s version properly.
test.sh is already updated by #3750, but test-vmc.sh is missing.
=> Update CI script to support multiple K8s versions

.github/workflows/kind.yml, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/conf/antrea-controller.conf, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, ci/jenkins/test-vmc.sh, ci/kind/test-e2e-kind.sh, hack/generate-manifest.sh, test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/e2e/infra/vagrant/push_antrea.sh, test/e2e/ipsec_test.go, test/e2e/nodeportlocal_test.go, test/e2e/secondary_network_ipam_test.go, test/e2e/service_externalip_test.go, test/e2e/trafficcontrol_test.go
There were 3 feature specific jobs running e2e tests with AntreaProxy
disabled, AntreaProxy and proxyAll enabled, and AntreaPolicy disabled
separately. Having a job for each feature is not extensible and
requires maintenance efforts to configure the job along with the
feature's lifecycle. There is a lot of redundancy between these jobs as
unrelated tests ran repeatedly in them.
There were other feature specific test cases enabling the features at
runtime, which doesn't cover the scenario when two features are enabled
at the same time.
This patch removes some feature specific jobs and creates one job
running tests with all features enabled, which can test all features'
interaction. The patch also makes necessary changes to kind test script
and manifest generating script to achieve it. …
=> Improve kind e2e tests

multicluster/test/e2e/framework.go, test/e2e/antreaipam_test.go, test/e2e/bandwidth_test.go, test/e2e/egress_test.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/nodeportlocal_test.go, test/e2e/proxy_test.go, test/e2e/service_externalip_test.go, test/e2e/service_test.go, test/e2e/traceflow_test.go, test/e2e/trafficcontrol_test.go, test/e2e/wireguard_test.go
Functions createPodOnNode and CreatePodOnNodeInNamespace have long lists
of parameters, and some of them are almost never used. Their naming is
also confusing since they both let you specify an arbitrary Namespace,
and the only difference is that CreatePodOnNodeInNamespace takes a
container name as parameter, while createPodOnNode auto-generates it
based on the container image name.
We try a different approach, using a "PodBuilder" object. The advantage
is the ability to add new methods to the builder, with explicit names,
instead of adding new function parameters or using the mutate function.
=> Refactor Pod creation for e2e tests

codecov.yaml
Set carryforward flag to true to use a reference of past coverage for tests
that are not run on the current commit.
You can refer to https://docs.codecov.com/docs/carryforward-flags to
learn more details.
This is a part of #3943
=> Set carryforward flag to true on codecov configuration

build/charts/antrea/crds/externalnode.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, pkg/controller/externalnode/controller.go, pkg/util/externalnode/externalnode.go
Update ExternalNode openAPIV3Schema to only allow create/update
ExternalNode when its interfaces exist and the ips of the interface
exist.
=> [ExternalNode] Add validations for ExternalNode

test/e2e/egress_test.go, test/e2e/service_externalip_test.go
Before pkill v3.3.13, the return value could be 0 even if the operation failed,
which led to a false positive result for RunCommandOnNode function in e2e test.
The command should be run with root privilege in CAPV environment because the
user of antrea-agent process is root.
=> Fix pkill failure in e2e test

test/e2e/egress_test.go, test/e2e/service_externalip_test.go
Cherry pick of #3948 on release-1.7.
#3948: Fix pkill failure in e2e test
=> Automated cherry pick of #3948: Fix pkill failure in e2e test

Makefile, ci/jenkins/test-mc.sh, ci/jenkins/test-vmc.sh, multicluster/Makefile, multicluster/build/images/Dockerfile.build.coverage, multicluster/cmd/multicluster-controller/bincover_run_main_test.go, multicluster/config/overlays/leader-ns/coverage/manager_command_patch_coverage.yaml, multicluster/config/overlays/member/coverage/manager_command_patch_coverage.yaml, multicluster/hack/generate-manifest.sh
1. Add a new target on Makefile to build MC controller image with
instrumented binary
2. Add steps on test-mc.sh to collect coverage files from leader and member cluster
controllers and upload it to codecov
This is a part of https://github.com/antrea-io/antrea/issues/3943
=> Upload Multi-cluster e2e coverage to codecov

ci/jenkins/test-vmc.sh
1. The crd path is changed, so fix the path in MC integration test.
2. Change the codecov caller parameters and the path to run codecov which help to correct the relative path in codecov, so integration test data can be calculated correctly with right package names. You may refer to an old PR's file lists to see the total top packages being calculated are incorrect. https://app.codecov.io/gh/antrea-io/antrea/compare/3941/tree
Part of #3943
=> Fix integration data on codecov

pkg/agent/route/route_linux.go, test/e2e/egress_test.go
The verification was wrong, which lead to false positive.
Besides, DeleteSNATRule should only call iptables or ip6tables based on
the protocol of SNAT IP, otherwise it would fail and lead to retries.
=> Fix egress e2e test

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/manager/manager.yaml
The `hostNetwork` mode is required to run Multi-cluster controller on a public
cloud like EKS clusters.
=> Use hostNetwork for Multi-cluster controller

pkg/antctl/command_definition.go, pkg/antctl/output/output.go
Current output formatters (table, json, and yaml) of Antctl are
not good at displaying multi-line string responses.
Add a new output formatter `raw` whose output is similar to
fmt.Print(responseString) to better display multi-line string responses.
Fixes https://github.com/antrea-io/antrea/issues/3426
=> [Antctl] Add an output formatter to better display multi-line string responses.

.github/workflows/go.yml
Do not use jobs with os matrix when any of the expanded jobs are required checks, otherwise the reports would be missing if the job is skipped, causing PRs unmergeable.
Fixes #3563
=> Fix missing reports of matrix jobs when they are skipped

build/charts/antrea/conf/antrea-agent.conf, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, docs/feature-gates.md, pkg/agent/proxy/endpoints.go, pkg/agent/proxy/endpointslicecache.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/topology.go, pkg/agent/proxy/topology_test.go, pkg/features/antrea_features.go, third_party/proxy/config/config.go, third_party/proxy/endpoints.go, third_party/proxy/types.go
Feature TopologyAwareHints is at Beta stage in Kubernetes v1.23, and it is
enabled by default in Kubernetes v1.24 See more
https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/.
=> Support TopologyAwareHints in AntreaProxy

multicluster/test/e2e/framework.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go
Use this PR to replace PR #3286.
Grouped multicluster service export test cases together, and
trigger the test cases from multicluster/test/e2e/main_test.go
Signed-off-by: Enhao Cui <ecui@vmware.com>
=> Multicluster E2E Test Refactoring

pkg/agent/route/route_linux.go, test/e2e/egress_test.go
Cherry pick of #3953 on release-1.7.
#3953: Fix egress e2e test
=> Automated cherry pick of #3953: Fix egress e2e test

CONTRIBUTING.md, README.md, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh, codecov.yaml, multicluster/Makefile
Codecov supports uploading multiple files into one flag.
Since there is no conflict between multi-cluster and antrea integration
tests, we run them in one line command and use the same flag `integration-tests` for both cases to simplify CI.
Signed-off-by: Lan Luo [luola@vmware.com](mailto:luola@vmware.com)
=> Run multi-cluster integration tests with test-integration

Makefile, ci/jenkins/test-mc.sh, ci/jenkins/test-vmc.sh, multicluster/Makefile, multicluster/build/images/Dockerfile.build.coverage, multicluster/cmd/multicluster-controller/bincover_run_main_test.go, multicluster/config/overlays/leader-ns/coverage/manager_command_patch_coverage.yaml, multicluster/config/overlays/member/coverage/manager_command_patch_coverage.yaml, multicluster/hack/generate-manifest.sh
Cherry pick of #3942 on release-1.7.
#3942: Upload multi-cluster e2e coverage to codecov
=> Automated cherry pick of #3942: Upload multi-cluster e2e coverage to codecov

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/controller/trafficcontrol/controller.go, pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/ovs_schema.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/ovs/ovs_client_test.go
Use uplink interface name for host interface internal port, to support DHCP client.
Add a suffix to uplink when bridging to OVS bridge.
=> [flexible-ipam] Use uplink interface name for host interface internal port

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/controller/trafficcontrol/controller.go, pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/ovs_schema.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/ovs/ovs_client_test.go
Cherry pick of #3938 on release-1.7.
#3938: Use uplink interface name for host interface
=> Automated cherry pick of #3938: Use uplink interface name for host interface

docs/multicluster/user-guide.md
Fix apiVersion typo in the user-guide. Change the apiVersion of ClusterClaim from "multicluster.crd.antrea.io/v1alpha1" to "multicluster.crd.antrea.io/v1alpha2"
=> Fix apiVersion typo in the user-guide

docs/getting-started.md, docs/helm.md
=> Add documentation for Helm installation method

pkg/agent/route/route_linux.go, pkg/agent/util/iptables/iptables.go
When using Antrea in policyOnly mode on an EKS cluster, an additional
iptables rule is needed in the PREROUTING chain of the nat table. The
rule ensures that Pod-to-external traffic coming from Pods whose IP
address comes from a secondary network interface (secondary ENI) is
marked correctly, so that it hits the appropriate routing table. Without
this, traffic is SNATed with the source IP address of the primary
network interface, while being sent out of the secondary network
interface, causing the VPC to drop the traffic.
Relevant rules (before the fix):
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -i eni+ -m comment --comment "AWS, outbound connections" -m state --state NEW -j AWS-CONNMARK-CHAIN-0
-A PREROUTING -m comment --comment …
```
=> Fix Pod-to-external traffic on EKS in policyOnly mode

pkg/agent/route/route_linux.go, pkg/agent/util/iptables/iptables.go
Cherry pick of #3975 on release-1.7.
#3975: Fix Pod-to-external traffic on EKS in policyOnly mode
=> Automated cherry pick of #3975: Fix Pod-to-external traffic on EKS in policyOnly mode

pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/connections/deny_connections_test.go, pkg/agent/flowexporter/priorityqueue/priorityqueue.go, pkg/agent/flowexporter/priorityqueue/priorityqueue_test.go
When flow exporter is enabled, but failed to connect to downstream IPFIX collector, connections added to the priority queue inside flow exporter won't be expired and removed from queue, causing memory to bloat. Furthermore, connection store polling will remove conn from its `connections` map when the flow is no longer in conntrack, but not the related items in priority queue. When a new flow with same flow key is reestablished, a duplicated item with same key will be added to the queue, while the reference to the old one is lost, essentially causing memory leak.
This change addresses above issue in the following aspects:
1. Connection store polling removes stale conn from both `connections` map and the priority queue. Since CS polling is independent of exporting process liveness, this …
=> Fix FlowExporter memory bloat when export process is dead

pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/connections/deny_connections.go, pkg/agent/flowexporter/connections/deny_connections_test.go, pkg/agent/flowexporter/priorityqueue/priorityqueue.go, pkg/agent/flowexporter/priorityqueue/priorityqueue_test.go
Cherry pick of #3994 on release-1.7.
#3994: Fix FlowExporter memory bloat when export process is dead
=> Automated cherry pick of #3994: Fix FlowExporter memory bloat when export process is dead

pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/util/ndp/ndp.go
=> [ipv6] Add GratuitousNDP for Pod creation

.github/workflows/go.yml
Cherry pick of #3670 on release-1.6.
#3670: Fix broken Markdown links check for main branch
=> Automated cherry pick of #3670: Fix broken Markdown links check for main branch

build/charts/antrea/templates/agent/daemonset.yaml, build/images/base/Dockerfile, build/images/scripts/install_cni_chaining, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml
The script is in charge of overwriting the cloud-specific CNI conf file
(e.g., 10-aws.conf for EKS).
However, the script is currently run as an initContainer, and does not
account for the possibility that the CNI conf file may be modified again
by the cloud provider at a later time, hence discarding the changes
made by the script.
For example, restarting aws-node on EKS will cause the 10-aws.conf file
to be overwritten with the default configuration, and Antrea will no
longer be involved in Pod networking configuration. For the user,
everything may appear to work from a connectivity standpoint, but
NetworkPolicies will not be enforced!
To avoid this issue, we run install_cni_chaining in a "normal"
container, and leverage inotify to monitor the CNI conf file. Every time
another process …
=> Improve install_cni_chaining to support updates to CNI conf file

go.mod, go.sum, pkg/controller/networkpolicy/networkpolicy_controller.go
Most of our code uses github.com/google/uuid, but the NetworkPolicy
controller was using github.com/satori/go.uuid.
github.com/satori/go.uuid has a security issue (CVE-2021-3538) which was
fixed in the master branch but is not part of any released version. It
seems that the package is not actively maintained any more.
Even though this security issue doesn't impact us, it can still show up
in some security scans. Therefore, we remove the dependency and instead
use github.com/google/uuid consistently throughout the code. Plus, one
less dependency is always nice :)
The new UUIDs are the same as the old ones, which is not really a strict
requirement given that on Controller restart, all the information is
computed again and sent to all Agents.
=> Remove dependency on github.com/satori/go.uuid module

ci/jenkins/test.sh
Cherry pick of #3750 on release-1.5.
#3750: Update latest CI testbed to 1.24 and adjust related script
=> Automated cherry pick of #3750: Update latest CI testbed to 1.24 and adjust related script

docs/multicluster/quick-start.md, multicluster/controllers/multicluster/member_clusterset_controller.go, multicluster/controllers/multicluster/member_clusterset_controller_test.go
Add a step to ensure that member ClusterSet controller will
clean up MemberClusterAnnounce in the leader cluster if
the ClusterSet in the member is deleted.
=> Remove MemberClusterAnnounce if ClusterSet deleted 

hack/windows/Install-OVS.ps1
Windows OVS needs SSL files to start service.
Add new funtion in Install-OVS.ps1 to check files exist and install
SSL library if files don't exist.
Fixes https://github.com/antrea-io/antrea/issues/4027
Co-authored-by: wenyingd <wenyingd@vmware.com>
=> Add SSL checking function in windows OVS script

multicluster/apis/multicluster/v1alpha2/clusterclaim_webhook.go, multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/cmd/multicluster-controller/clusterset_webhook.go, multicluster/cmd/multicluster-controller/clusterset_webhook_test.go, multicluster/cmd/multicluster-controller/controller.go, multicluster/cmd/multicluster-controller/main.go, multicluster/config/overlays/member/webhook_patch.yaml, multicluster/config/webhook/manifests.yaml
1. Add a ClusterSet webhook to make Leader's ClusterID immutable, and
allow only one ClusterSet in mc-controller's  Namespace.
2. Update ClusterClaim webhook to make `Value` field
(ClusterID/ClusterSetID) immutable
3. Remove unused mutate webhook of ClusterClaim
=> Update ClusterSet and ClusterClaim webhooks

build/images/scripts/install_cni_chaining, build/yamls/antrea-aks-node-init.yml, build/yamls/antrea-eks-node-init.yml, build/yamls/antrea-gke-node-init.yml
The current solution which consists of overwriting the existing CNI conf
file (e.g., 10-aws.conflist) suffers from one issue for which I cannot
find a simple workaround:
When a Node restarts, there can be a short window of time during which
the CNI conf file reverts to the old one (without Antrea). If some Pods
are restarted / scheduled on the Node during that time, they will not be
processed by Antrea and NetworkPolicies may not be applied to them.
The solution I have come up with is to create a new CNI conf file with
higher priority (05-antrea.conflist). Because that file will stay the
same during Node restart, the problematic window of time does not exist
anymore. We still watch for changes to the intial CNI conf file (e.g.,
10-aws.conflist), so we can update 05-antrea.conflist as …
=> Use different CNI conf file when configuring chaining with Antrea

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
Wait one second as the fake clientset doesn't support watching with specific resourceVersion.
Otherwise the update event would be missed by the watcher used in `csrutil.WaitForCertificate()`
if it happens to be generated in-between the List and Watch calls.
Fixes: #3851
=> Fix unit test flaky for IPsec controller

build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/conf/antrea-controller.conf, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/multicast/mcast_controller.go, pkg/agent/multicast/mcast_controller_test.go, pkg/agent/multicast/mcast_discovery.go, pkg/agent/multicast/mcast_discovery_test.go, pkg/agent/multicast/mcast_route.go, pkg/agent/multicast/mcast_route_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/multicast.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route_linux.go, pkg/agent/types/multicast.go, pkg/agent/util/iptables/iptables.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_group.go, pkg/util/k8s/node.go, test/e2e/multicast_test.go
1. Use a single routine to send local multicast groups in an IGMP v3
Report message to notify all the other Nodes in the cluster
2. Multicast controller maintains both local Pod members and remote
Nodes which have Pod members for each multicast group found in the
cluster
3. Add remote Node members in the OpenFlow group buckets.
=> [Multicast] support encap mode

ci/jenkins/test.sh, test/e2e/service_test.go
Cherry pick of #3802 on release-1.6.
#3802: Support K8s>=1.20
=> Automated cherry pick of #3802: Support K8s>=1.20

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/cmd/multicluster-controller/leader.go, multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go, multicluster/cmd/multicluster-controller/memberclusterannounce_webhook_test.go, multicluster/config/overlays/leader-ns/role.yaml, multicluster/controllers/multicluster/commonarea/remote_common_area.go, multicluster/controllers/multicluster/member_clusterset_controller.go, multicluster/controllers/multicluster/memberclusterannounce_controller.go, multicluster/controllers/multicluster/memberclusterannounce_controller_test.go
Auto update ClusetSet and MemberClusterAnnounce in the leader cluster. 
+ When a new member cluster is added to the ClusterSet. The ClusterSet in the leader cluster will update the new member cluster in the `spec.members`.
+ When a member cluster departs the ClusterSet. The `MemberClusterAnnounce` in the leader cluster will be deleted. The member cluster will be removed from the `spec.members`.
=> Auto update ClusterSet and MemberClusterAnnounce in leader cluster

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
Wait for the signer goroutine to finish before quitting the tests.
This ensures that the *testing.T is always valid in the signer.
Fixes: #4059
=> Fix race condition in unit test for IPsec

build/charts/antrea/templates/whereabouts/clusterrole.yaml, build/images/base/Dockerfile, pkg/agent/secondarynetwork/podwatch/controller.go
Register Whereabouts CNI as a valid IPAMType for secondary network configuration. Whereabouts is the IPAM used to configure secondary/virtual networks for Service function chaining needs at this time.
Signed-off-by: <arunkumar.velayutham@intel.com>
=> Upgrade whereabouts CNI to v0.5.4 and align secondary network IPAM with additional pluginArgs

multicluster/controllers/multicluster/serviceexport_controller.go, multicluster/controllers/multicluster/serviceexport_controller_test.go, multicluster/test/integration/serviceexport_controller_test.go
Refine ServiceExport controller to watch Endpoints events to
ensure that Service kind of ResourceExport can be removed
when the exported Service no longer has available Endpoints,
or skip writing ResourceExport if there is no Endpoints at the beginning.
Fixes #4055 
=> Cleanup ResourceExport if exported Service has no available Endpoints

docs/network-requirements.md
=> Add new ports to network requirement doc

multicluster/controllers/multicluster/controller_utils.go, multicluster/controllers/multicluster/leader_clusterset_controller.go
Since this leader Namespace should always be the same
as the ClusterSet's Namespace in the metadata when it's in leader
cluster, skip this Namespace validation in the leader cluster. This
allow the leader Namespace to be empty when user is trying to create
a ClusterSet in leader cluster.
=> Remove unnecessary Namespace validation in leader

go.mod, go.sum, pkg/flowaggregator/clickhouseclient/clickhouseclient.go, pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go, plugins/octant/go.sum
This change fixes an unsafe deque access in flow aggregator clickhouse client. Reads of the deque including Len() and At() are not protected with mutex during batchCommitAll(), which could run concurrently with another routine writing items to deque with CacheSet().
To avoid holding the mutex for extended period of time, the following behavior is adopted:
1. (With mutex) Pop front #Len() items off deque and store in buffer
2. (Without mutex) Transform records in buffer and batch export them with SQL driver. This step is where I/O happens.
3. (With mutex) If SQL commit rolled back, PushFront records in buffer back to deque. Oldest records will be discarded if deque full.
Also bumped github.com/gammazero/deque to v0.1.2.
=> Fix clickhouse client race during batch commit

build/charts/antrea/templates/controller/clusterrole.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, pkg/controller/ipam/antrea_ipam_controller.go, pkg/controller/ipam/antrea_ipam_controller_test.go
In AntreaIPAMController, the statefulSet worker and the workers that
update IP pool counters could update IP pool status. In real-world,
update conflicts can be detected by the real kube-apiserver by checking
the resourseVersion of the object. However, this is not supported by
the fake client, and update conflicts causes one update to override
another.
Since the latter workers are only responsible for updating IP counters,
it could use Patch method to avoid overriding other status in both
real-world and tests.
The patch also changes TestStatefulSetLifecycle to use subtest to run
its test cases, otherwise it's not clear which test case fails.
Fixes #4081
=> Use Patch to update IP counters of IPPools

multicluster/controllers/multicluster/member_clusterset_controller.go
Remove the validation of ClusterSet member list in a member cluster.
From a member perspective, it only concerns about the leader access
information, and Member ClusterID is already defined in the
ClusterClaim.
=> Remove ClusterSet member ID validation

multicluster/apis/multicluster/v1alpha1/clusterset_types.go, multicluster/apis/multicluster/v1alpha1/memberclusterannounce_types.go, multicluster/apis/multicluster/v1alpha2/clusterclaim_types.go, multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/crd/bases/multicluster.crd.antrea.io_clusterclaims.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_clustersets.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_memberclusterannounces.yaml, multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go, multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go, multicluster/controllers/multicluster/commonarea/mock_remote_common_area_wrapper.go, multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go, multicluster/controllers/multicluster/gateway_controller_test.go, multicluster/controllers/multicluster/member_clusterset_controller_test.go, multicluster/controllers/multicluster/serviceexport_controller_test.go, multicluster/controllers/multicluster/stale_controller_test.go
1. Set Leaders in ClusterSet and Value in ClusterClaim as required
fields.
2. Fix the column field issue on MemberClusterAnnounce
3. Clean up some unused codes.
=> Minor fixes for multi-cluster manifests

build/charts/antrea/crds/ippool.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml
To make the output informative and consistent with ExternalIPPools.
Before:
```
NAME    AGE
pool1   10h
```
After:
```
NAME    TOTAL   USED   AGE
pool1   9       3      10h
```
=> Show IP counters when kubectl getting IPPools

multicluster/cmd/multicluster-controller/leader.go, multicluster/cmd/multicluster-controller/member.go, multicluster/controllers/multicluster/commonarea/remote_common_area.go, multicluster/controllers/multicluster/stale_controller.go, multicluster/controllers/multicluster/stale_controller_test.go, multicluster/test/integration/suite_test.go
Add a role argument for the StaleController so that it can run in both
leader and member clusters. When it runs in a member cluster, the
controller will GC Service, ACNP, and CI resources. When it runs in a
leader cluster, the controller will GC MemberClusterAnnounces.
Signed-off-by: hujiajing <hjiajing@vmware.com>
=> Add controller for leader cluster to GC MemberClusterAnnounce

docs/antrea-network-policy.md, pkg/agent/controller/networkpolicy/audit_logging.go, pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/integration/agent/openflow_test.go
Previously audit logging only works for Antrea NetworkPolicy and ClusterNetworkPolicy when setting the `enableLogging` field in the rule. This PR is to address this [issue](https://github.com/antrea-io/antrea/issues/3640).
Method overview of this PR is at this [design doc](https://docs.google.com/document/d/1lgPxhhAw8INUxE6ulUo_RngmWd5X4IrLkwtx744CwG4/edit?usp=sharing).
To enable logging for K8s NetworkPolicy, set `annotations` in `metadata` for the Namespace as `policy.antrea.io/enable-np-logging: "true"`. Then K8s NetworkPolicy applied to this Namespace will be logged in the directory `/var/log/antrea/networkpolicy/np.log`.
=> Audit Logging support K8s Networkpolicy

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/types.go, pkg/agent/multicast/mcast_discovery_test.go, pkg/config/agent/config.go, pkg/ovs/ovsconfig/ovs_client.go, test/integration/ovs/ovs_client_test.go
This PR supports configurable tunnel port for TrafficEncapMode. When
deployed on the public cloud, the tunnel type and tunnel port used by
the underlying network may be the same as the antrea container network,
so it needs to support the modification of the tunnel port to prevent
conflicts.
=> Support configurable tunnel port for TrafficEncapMode

build/charts/antrea/README.md, build/charts/antrea/templates/controller/service.yaml, build/charts/antrea/values.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vm.sh, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/main_test.go, test/e2e/utils/externalnode_spec_builder.go, test/e2e/vmagent_test.go
Adding a new test for VM/BM agent.
- Test configures namespace, serviceaccount
- Applies vm-agent-rbac.yaml
- Starts antrea service as nodeport
- Verifies create/delete externalentity, validates interface
configuration in OVS
Signed-off-by: Anand Kumar <kumaranand@vmware.com>
=> [ExternalNode] New CI test for VM agent

ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh
GKE's cluster version now defaults to v1.24.1, which no longer creates
secret for service account automatically, the verification in old test
cases would fail. This patch makes the test determine conformance
container image version based on the cluster's version to avoid such
issue.
However, the test suite Netpol introduced in new conformance image uses
a Namespace creation function which is not robust, leanding to random
test failures in GKE test. This patch skips it temporarily.
Besides, legacy NetworkPolicy tests for AKS and EKS have been skipped
by mistake for a while because of a conflicting skip regex. This patch
fixes it.
For https://github.com/antrea-io/antrea/issues/3762
=> [CI] Fix NetworkPolicy tests on Clouds

multicluster/cmd/multicluster-controller/clusterset_webhook.go, multicluster/cmd/multicluster-controller/clusterset_webhook_test.go, multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go
Since ClusterSet's member list is maintained by MemberClusterAnnounce
controller, mc-controller should deny ClusterSet member list updates by users
manually.
=> Validate ServiceAccount for ClusterSet member list changes

docs/multicluster/antctl.md, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, multicluster/config/samples/clusterset_init/leader-access-token-template.yml, multicluster/config/samples/clusterset_init/member-clusterset-template.yml
Add steps to set up a set up Multi-cluster ClusterSet using antctl
commands to the Multi-cluster quick-start guide.
Also made minor revisions to the Multi-cluster antctl and user guides,
and the sample YAML template for creating a member token.
=> Document steps to set up Multi-cluster ClusterSet with antctl

docs/external-node.md
@wenyingd : when reading the doc, I feel these bold font sentences look strange, and also feel not necessary to emphasize them. Let me know what you think.
=> Minor updates to the external Node document

multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/cmd/multicluster-controller/options.go, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml, multicluster/config/default/configmap/controller_manager_config.yaml, multicluster/config/manager/manager.yaml
1. Set the metrics binding address to 0 to disable it since we do not
provide metrics.
2. Change the health binding address port to 8080.
3. Remove unused configurations.
=> Disable metrics api for multicluster controller and clean up configs

pkg/agent/util/ndp/ndp.go
Agent sends IPv6 Gratuitous NDP packet on each Pod to broadcast its
address. The socket is not closed after sending packet, which introduces
socket leak.
To resolve the issue, adding a defer function to close the socket after
writing the packet into the connection.
Fixes #4086 
=> Bugfix: socket is leak on IPv6 testbed

pkg/agent/config/traffic_encap_mode.go, pkg/agent/config/traffic_encap_mode_test.go, pkg/agent/config/traffic_encryption_mode.go, pkg/agent/config/traffic_encryption_mode_test.go
Antrea Agent uses TrafficEncryptionModeInvalid in networkConfig. It may
introduce a panic when calling TrafficEncapModeInvalid.String(), since
its string value is not defined in the string slice for the supported
TrafficEncryptionModeInvalid, and its value is -1 which is not a valid
index in any slice.
To resolve the issue, a constant string is returned when
TrafficEncapModeInvalid is used.
The same issue may exist on type TrafficEncapModeInvalid in the logging.
As a result, a default string value is given to TrafficEncapModeInvalid
too.
Fixes #4095 
=> [ExternalNode] Fix Agent log issue

docs/antrea-network-policy.md, test/e2e/antreapolicy_test.go
Addresses followup comments in [Audit Logging support K8s Networkpolicy #4047](https://github.com/antrea-io/antrea/pull/4047).
=> [Follow Up] Audit Logging support K8s Networkpolicy

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/default/configmap/controller_manager_config.yaml
The type should be string instead of int.
When it's `0`, controller will fail to start due to below error:
```
Failed to load options" err="could not decode file into runtime.Object"
```
=> Fix the port type in the config

pkg/agent/config/node_config.go, pkg/agent/route/route_windows.go
VirtualServiceIPv4 is the wrong parameter for AddNodePort.
It should be replaced by VirtualNodePortDNATIPv4 to match the
correct IP destination.
=> Fix Windows AddNodePort parameter error

go.mod, go.sum, plugins/octant/go.sum
Bump up ofnet version
ofnet resolves a reconnect issue, this change is to involve the fix.
Fixes #4092 
=> Resolve reconnect issue between Agent and OVS

docs/external-node.md, hack/externalnode/install-vm.ps1, hack/externalnode/install-vm.sh
- Provides install script for both Windows and Linux
- Expects the user to copy the antrea-agent binary, antrea-agent.conf,
antrea-agent.kubeconfig and antrea-agent.antrea.kubeconfig files to the
VM.
- Update the documentation
Linux usage:
./install-vm.sh --ns vm-ns --bin /tmp/antrea-agent --config /tmp/antrea-agent.conf --kubeconfig /tmp/my.kubeconfig --antrea-kubeconfig /tmp/my.antrea.kubeconfig
Windows usage:
.\Install-vm.ps1 -NameSpace vm-ns -BinaryPath C:\temp\antrea-agent.conf -ConfigPath C:\temp\antrea-agent.conf -KubeConfigPath C:\temp\my.kubeconfig -AntreaKubeConfigPath C:\temp\my.antrea.kubeconfig
Signed-off-by: kumaranand <kumaranand@vmware.com>
=> Install script for configuring antrea-agent on VM

docs/maintainers/release.md
When updating the VERSION file, one also needs to run `make -C
build/charts/ helm-docs` and commit the changes.
=> Add missing step to release documentation

pkg/agent/nodeportlocal/portcache/port_table_others.go
Add a portcache file to support go building across different OSs.
Fixes https://github.com/antrea-io/antrea/issues/3826
=> Fix running NPL unit test on MacOS

ci/test-conformance-aks.sh
As AKS Nodes don't support SCTP protocol.
Fixes #4132
=> [CI] Skip SCTPConnectivity test on AKS

build/charts/antrea/templates/_helpers.tpl, build/charts/antrea/templates/agent/daemonset.yaml, build/charts/antrea/templates/controller/deployment.yaml, build/charts/flow-aggregator/templates/_helpers.tpl, build/charts/flow-aggregator/templates/deployment.yaml
When installing a released version of a chart (for Antrea or the
FlowAggregator), the image tag was not generated correctly. It was
missing the leading "v".
I tested this change by changing the value of `appVersion` in
`Chart.yaml` to 1.8.0, and I made sure that the following images
were used:
- `projects.registry.vmware.com/antrea/antrea-ubuntu:v1.8.0`
- `projects.registry.vmware.com/antrea/flow-aggregator:v1.8.0`
Fixes #4137
=> Fix image tag for Antrea and FlowAggregator Helm charts

ci/kind/kind-setup.sh, hack/make-metrics-doc.sh
Fixes #3787 
This commit adds extra port mappings for the kind control plane node so that antrea agent and antrea controller can be reached, because the nodes of the Kind cluster cannot be accessed directly from the MacOS
host, like linux.
=> Support running ./hack/make-metrics-doc.sh from macOS

.github/workflows/docker_update_base_windows.yml, build/images/base-windows/Dockerfile, build/images/base-windows/README.md, hack/build-antrea-windows-all.sh
At the moment, updating this image is a very manual process and requires
access to a Windows machine. To simplify this process, we add a new
Github Workflow which can be used to manually trigger a Docker image
build and push on Github hosted Windows workers.
Ideally, the workflow would not need to be triggered manually and would
run as part of CI (like we do for Linux base images). However this is a
good compromise / first step. Even with Docker caching, running
./hack/build-antrea-windows-all.sh for every pull request and push event
may be a bit too expensive. Something that can be investigated later.
=> Support updating the antrea/base-windows image with Github Actions

ci/jenkins/test.sh
Add image cleanup commands on both docker and containerd nodes to prevent
the depletion of storage.
=> Add commands to cleanup dangling images on 1.24 testbed

pkg/ovs/openflow/ofctrl_packetout.go, pkg/ovs/openflow/ofctrl_packetout_test.go
Test_ofPacketOutBuilder_Done relies on specific pseudo-random numbers to
be generated and will fail if another test also calls the pseudo-random
number generator. This patch creates a dedicated random number generator
for ofPacketOutBuilder and specifies a hardcoded seed for unit tests to
make test outputs predictable.
=> Fix unit tests that rely on pseudo-random numbers

cmd/antrea-agent/agent.go, pkg/agent/memberlist/cluster.go, pkg/agent/memberlist/cluster_test.go
Otherwise tests would fail if the memberlist port is already bound on
the server that runs the tests.
=> Use mock network for memberlist unit tests

build/charts/antrea/templates/agent/daemonset.yaml, build/images/base/Dockerfile, build/images/scripts/install_cni_chaining, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml
Cherry pick of #4012 on release-1.7.
#4012: Improve install_cni_chaining to support updates to CNI conf
=> Automated cherry pick of #4012: Improve install_cni_chaining to support updates to CNI conf

test/e2e/framework.go
Resource request at Pod scope is required to enable e2e framework to create
Pods with a specific set of VFs while creating a list of secondary networks
on a Pod using SRIOV.
Resource requests and limits can be used for other type of resource allocation
specific to a Pod as well (CPU, Memory etc.,)
=> Add Resource requests and limits of Pods created by NewPodBuilder API.

pkg/config/agent/config.go, pkg/config/controller/config.go, pkg/config/flowaggregator/config.go, pkg/config/flowaggregator/default.go
Somehow they were named differently from the base names of their source
directories, which make code consuming them look very confusing if they
are not imported with alias. For example, code would look like the
following:
```
import "antrea.io/antrea/pkg/config/agent"
func newOptions() *Options {
return &Options{
config: &config.AgentConfig{},
}
}
```
=> Fix names of packages in pkg/config

pkg/controller/egress/store/egressgroup.go, pkg/controller/egress/store/egressgroup_test.go
Add unit test for egress group store
For #4142 
=> Add unit test for egress group store

pkg/ovs/openflow/ofctrl_group.go
Fixes: #4159
This PR fixes the issue by appending buckets directly in `Done()` in
pkg/ovs/openflow/ofctrl_group.go instead of calling `AddBuckets` method
of `Group` defined in the ofnet which sends an Openflow message to install
the group.
=> Avoid redundant Openflow messages when syncing an updated group to OVS

pkg/ovs/openflow/ofctrl_group.go
Cherry pick of #4160 on release-1.8.
#4160: Avoid redundant Openflow messages when syncing an updated
=> Automated cherry pick of #4160: Avoid redundant Openflow messages when syncing an updated

Makefile
* -coverpkg was not set, causing coverage to be missed for some packages
with no unit tests, but exercised by unit tests from another
package. This is often the case for some deeply nested packages,
e.g., `pkg/agent/secondarynetwork/cnipodcache/` is exercised by unit
tests defined in `pkg/agent/secondarynetwork/podwatch`.
* coverage was not enabled for Windows unit tests
=> Fix code coverage reporting for unit tests

multicluster/cmd/multicluster-controller/clusterset_webhook_test.go, multicluster/controllers/multicluster/common/helper.go, multicluster/controllers/multicluster/controller_utils_test.go
Add more unit tests for multi-cluster and remove some dead codes.
For #4142 
=> Improve multi-cluster unit test

go.mod, go.sum, pkg/agent/proxy/endpoints.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, test/e2e/proxy_test.go, third_party/proxy/healthcheck/README, third_party/proxy/healthcheck/common.go, third_party/proxy/healthcheck/service_health.go
antrea-agent: Implement service health check.
When services are created with "externalTrafficPolicy: Local",
a "healthCheckNodePort" is created in the k8s service object.
kube-proxy in turn will listen on this port and answer queries
on http://0.0.0.0:healthCheckNodePort/healthz". In kube-proxy
replacement mode, antrea does not support this feature. This
becomes more important for Windows support as userspace
kube-proxy is being deprecated.
This commit implements this feature in Antrea and is inspired
by the same feature in upstream kube-proxy with some differences.
The predominant difference is that upstream kube-proxy goes
through all endpoints of cluster in each iteration of
endpoints:update() to find the local endpoints. This has been
changed here to only look for changed endpoints.
=> Implement service health check in Antrea-agent

pkg/agent/secondarynetwork/podwatch/controller.go, pkg/agent/secondarynetwork/podwatch/controller_test.go
Fix one of the tests (`TestPodControllerAddPod/missing_Status.PodIPs`)
and add a few more unit tests.
For #4142
=> Add more unit tests for secondarynetwork feature

multicluster/Makefile, multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/default/kustomization.yaml, multicluster/config/manager/manager.yaml, multicluster/hack/update-checksum.sh
When the ConfigMap is generated with suffix by kustomize, it will
generate a manifest with new ConfigMap like 'antrea-mc-controller-config-***'.
When a new Deployment is applied, it will leave a stale ConfigMap.
To avoid stale ConfigMaps, here we add checksum of multi-cluster configuration
file as Deployment's annotation. This way can help to restart the controller Pod
automatically without the suffix of ConfigMap.
=> Add checksum of config file as an annotation

multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/cmd/multicluster-controller/gateway_webhook.go, multicluster/cmd/multicluster-controller/gateway_webhook_test.go, multicluster/cmd/multicluster-controller/member.go, multicluster/config/overlays/leader-ns/kustomization.yaml, multicluster/config/overlays/leader-ns/webhook_patch.yaml, multicluster/config/webhook/manifests.yaml, multicluster/controllers/multicluster/gateway_controller.go, multicluster/controllers/multicluster/gateway_controller_test.go, multicluster/controllers/multicluster/node_controller.go, multicluster/controllers/multicluster/node_controller_test.go
In order to support Gateway active-standby mode HA, the Node
controller has been refined to handle Node readiness changes.
There will be at most one Gateway in a given Namespace, and the
Gateway controller is updated correspondingly.
1. Check Node readiness and create a Gateway CR if Node is ready
and there is no existing Gateway.
2. Initialize active Gateway and Gateway candidate Nodes with annotation
'multicluster.antrea.io/gateway'.
3. Add Gateway webhook to allow at most one Gateway in a given
Namespace.
For #3754
=> Refine Node controller to support Gateway HA

pkg/antctl/raw/multicluster/get/clusterset.go, pkg/antctl/raw/multicluster/get/clusterset_test.go, pkg/antctl/raw/multicluster/get/output.go, pkg/antctl/raw/multicluster/get/output_test.go, pkg/antctl/raw/multicluster/get/resourceexport.go, pkg/antctl/raw/multicluster/get/resourceimport.go, pkg/antctl/transform/clusterset/transform.go
When a ClusterSet is created in the leader cluster, there might be
no status yet, then `antctl mc get clustersets -A` will skip print the
ClusterSet when the status is empty.
Fix it by passing an empty status and condition.
The old output:
```
CLUSTER-ID        NAMESPACE                CLUSTER-SET-ID  TYPE     STATUS REASON
test-cluster-east kube-system              test-clusterset IsLeader True   <NONE>
test-cluster-east kube-system              test-clusterset Ready    True   <NONE>
```
The new output:
```
CLUSTER-ID        NAMESPACE                CLUSTER-SET-ID  TYPE     STATUS REASON
<NONE>            antrea-multicluster-test test-clusterset <NONE>   <NONE> <NONE>
test-cluster-east kube-system              test-clusterset IsLeader True   <NONE>
test-cluster-east kube-system …
```
=> Fix ClusterSet output when status is empty

ci/jenkins/README.md, ci/jenkins/test-vmc.sh, ci/run-k8s-e2e-tests.sh
* Add sig-network test support for CAPV cluster.
* Skip test cases which are not supported by private lab environment.
=> Add sig-network test cases to the conformance CI job

ci/jenkins/test.sh, docs/windows.md, hack/windows/Helper.psm1
* E2e, conformance and networkpolicy tests passed with vmkernel mode proxy.
* Update the kube-proxy image on Windows CI pipeline.
=> Update the proxy mode of kube-proxy to vmkernel on windows

multicluster/controllers/multicluster/leader_clusterset_controller.go
The `updateStatus` will be called every 30s, this debug log becomes annoying line in the controller log, need to remove this and backport to v1.8.
=> Remove debug log

pkg/agent/flowexporter/connections/conntrack_linux_test.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/priorityqueue/priorityqueue_test.go, pkg/agent/flowexporter/utils_test.go
Add more test cases for pkg/agent/flowexporter package and
its subpackages: connections, exporter, priorityqueue.
For #4142
=> Improve unit test of flowexporter package

pkg/flowaggregator/clickhouseclient/clickhouseclient.go, pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go, pkg/flowaggregator/exporter/clickhouse.go, pkg/flowaggregator/exporter/clickhouse_test.go, pkg/flowaggregator/exporter/s3_test.go
Add unit test for pkg exporter under flowaggregator
For https://github.com/antrea-io/antrea/issues/4142
Signed-off-by: Yun-Tang Hsu <hsuy@vmware.com>
=> Add unit test for pkg exporter

docs/multicluster/user-guide.md, multicluster/apis/multicluster/v1alpha1/resourceexport_types.go, multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml, multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go, multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go, multicluster/controllers/multicluster/commonarea/clusterinfo_importer.go, multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go, multicluster/controllers/multicluster/leader_clusterset_controller.go
Change ResourceExport's json tag to lowerCamelCase. After
antrea-mc-controller is upgraded from an older version to a version
with this change, it will get an empty spec for an existing existing
ResourceExport/ResourceImport of type ClusterInfo or
ClusterNetworkPolicy type, so we add code to skip importing any
ResoureImport if it doesn't have a valid spec.
=> Update ResourceExport's json tag as lowerCamelCase

pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/certificate/cacert_controller_test.go
This is for https://github.com/antrea-io/antrea/issues/4142
=> Improve unit test of certificate package

build/yamls/flow-visibility-e2e.yml, pkg/flowaggregator/clickhouseclient/clickhouseclient.go, pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go, pkg/flowaggregator/exporter/clickhouse.go, pkg/flowaggregator/exporter/clickhouse_test.go, pkg/flowaggregator/exporter/ipfix.go, pkg/flowaggregator/exporter/s3.go, pkg/flowaggregator/exporter/s3_test.go, pkg/flowaggregator/exporter/utils.go, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/flowaggregator/s3uploader/s3uploader.go, pkg/flowaggregator/s3uploader/s3uploader_test.go, test/e2e/flowaggregator_test.go
To support multi-cluster, we add a column "clusterUUID" to the S3Uploader and ClickHouseExporter flows table, as the cluster identifier.
=> Add clusterUUID column to S3Uploader and ClickHouseExporter

hack/.md_links_config.json
Specifically 403 and 503.
Both of these codes can be used by web protection services (e.g., Cloudflare) when a client is not recognized as a web browser or for rate-limiting purposes.
Hopefully this means that the periodic CI job checking for dead links will stop failing.
=> Accept more HTTP status codes as "alive" in Markdown link checker

multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go
Add a new e2e test to validate Endpoint change event to make sure event filter works as expected.
This fix needs to be back-ported to v1.8 with a minor change to remove GenerationChangedPredicate
in ServiceExport controller.
=> Add e2e test for Multi-cluster Service Endpoints changes

pkg/flowaggregator/clickhouseclient/clickhouseclient.go, pkg/flowaggregator/exporter/s3_test.go, pkg/flowaggregator/s3uploader/s3uploader.go
We determine the region programmatically in the S3 uploader, using the region "hint" provided in the config.
Before this change, there was a mismatch between the description of the "region" config parameter and its actual implementation in the S3 uploader.
=> [Flow Aggregator] Determine bucket region in S3 uploader

pkg/agent/controller/ipseccertificate/ipsec_certificate_controller_test.go
The difference in CSR CreationTimestamp can be lower than 7s because the resolution of the certificate's NotAfter field is at the second level, which means the provided expiration time will be truncated.
Fixes #4224
=> Fix flaky TestController_RotateCertificates unit test

build/images/ovs/Dockerfile.ubi, build/images/scripts/start_ovs_ipsec
1. Do not install strongswan in UBI-based image.
2. Add support for libreswan to `start_ovs_ipsec` start script.
Fixes: #4243
=> Add support for IPsec to UBI based image

go.mod, go.sum, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/multicast.go, pkg/agent/openflow/service.go, pkg/agent/proxy/proxier.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/ofctrl_group.go, pkg/ovs/openflow/ofctrl_meter.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go
Fixes: #2092
Due to the message size of Openflow, the maximum number of Endpoints for
a Service in AntreaProxy is 800. Since Openflow 1.5 is used in Antrea,
the operation `insert_buckets` introduced in Openflow 1.5 can be used to
create a Service with more than 800 Endpoints. To sync Service with more
than 800 Endpoints to OVS, multiple Openflow messages will be sent to
OVS in a bundle (the first message uses `add` to sync the OVS group and
its corresponding buckets to OVS, other messages use `insert_buckets` to
sync other buckets to OVS).
=> Remove the limit on the number of Endpoints in AntreaProxy

docs/antrea-network-policy.md, pkg/agent/controller/networkpolicy/audit_logging.go, pkg/agent/controller/networkpolicy/audit_logging_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/testing/mock_openflow.go, test/e2e/antreapolicy_test.go
Fixes #3980 
Add rule name to audit logging. It will be `<nil>` for K8s NetworkPolicies.
The solution added a rule name field to the conjunction structure to retrieve rule information when logging.
=> Add rule name to Audit Logging

pkg/agent/openflow/client.go, pkg/agent/openflow/framework.go, pkg/agent/openflow/multicast_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_test.go
This is because MulticastEgressRule defines rule to match nw_src and nw_dst, while
IGMP v1 report will sent to multicast group address. For example, if we define a
rule like:
```
spec:
priority: 5
tier: securityops
appliedTo:
- podSelector:
matchLabels:
app: mcjoin6
egress:
- action: Drop
to:
- ipBlock:
cidr: 225.1.2.4/32
```
Not only normal multicast traffic from Pods match label "app=mcjoin6", but also IGMP
v1 report will be matched. In this case, if there is egress rule to block multicast
traffic, IGMP v1 report will also be blocked, which is not expected.
Another issue, is that multicast stats will also count IGMP v1 report packet into
normal multicast egress rule as well. This
This patch defines a higher priority rule to match IGMP report to jump to table
MulticastRouting directly. …
=> [multicast]fix IGMP v1 report matches flow in MulticastEgressRule

pkg/agent/interfacestore/interface_cache_test.go, pkg/agent/interfacestore/types.go
1. Remove unused InterfaceType "HostInterface"
2. Add unit test in path pkg/agent/interfacestore
=> Add unit test in path pkg/agent/interfacestore

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/types.go, pkg/agent/multicast/mcast_discovery_test.go, pkg/config/agent/config.go
For Linux kernel before Mar 2021, UDP checksum must be present to trigger GRO on the receiver for better performance of Geneve and VXLAN tunnels. The issue has been fixed in Linux kernel [1], thus computing UDP checksum is no longer necessary.
This patch exposes a configuration parameter TunnelCsum which determines whether to compute UDP encapsulation header (Geneve or VXLAN) checksums on outgoing packets and makes it default to false. It should only be set to true when Nodes run an unpatched Linux kernel and poor transfer performance is observed.
[1] https://github.com/torvalds/linux/commit/89e5c58fc1e2857ccdaae506fb8bc5fed57ee063
I have confirmed the following distributions have included the above patch:
- Ubuntu 20.04.3 LTS (Focal Fossa), …
=> Make tunnel csum option configurable and default to false

pkg/agent/util/net.go, pkg/agent/util/net_test.go
The util function commonPrefixLen returns at most 64 bits prefix length, which leads to the calculated CIDR for IPv6 ClusterIPs being larger than actual value. For example, "aabb:ccdd::1" and "aabb:ccdd::2" should get "aabb:ccdd::/126" but got "aabb:ccdd::/64". The patch removes the 64 bits limit and changes the function name to longestCommonPrefixLen.
=> Fix route for IPv6 ClusterIPs

pkg/agent/stats/collector.go, pkg/agent/stats/collector_test.go
The empty MulticastGroupInfo will be reported unexpectedly during a single report session when:
1. Statistics of NP, ANP, or ANCP are getting updated.
2. MulticastGroupInfo is not refreshed. Fix: Always report updated MulticastGroupInfo when reporting is necessary.
=> Fix unexpected reporting of empty MulticastGroupInfo

docs/external-node.md, hack/externalnode/install-vm.ps1, hack/externalnode/install-vm.sh
Run cleanup before running antrea-agent service
Before running the antrea-agent, validate
whether ovs configuration is in good state.
If there is an error, cleanup ovs configuration
and then start antrea-agent.
Also fix typo and style issues.
Also update documentation.
Fixes #4122
Signed-off-by: Anand Kumar <kumaranand@vmware.com>
=> Perform cleanup before running antrea-agent

pkg/controller/externalnode/controller.go, pkg/controller/externalnode/controller_test.go
1. Use group/apiversion for OwnerReference when creating ExternalEntity from ExternalNode
2. Add unit tests for ExternalNodeController
=> Fix an issue when generating ExternalEntity from ExternalNode

multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller.go, multicluster/controllers/multicluster/commonarea/acnp_resourceimport_controller_test.go, multicluster/controllers/multicluster/commonarea/clusterinfo_importer.go, multicluster/controllers/multicluster/commonarea/clusterinfo_importer_test.go, multicluster/controllers/multicluster/commonarea/resourceimport_controller.go, multicluster/controllers/multicluster/commonarea/resourceimport_controller_test.go
The ResourceImport reconciler only adds/updates installed ResourceImports to the installedResImports cache, but never removes them when they are deleted from the K8s API and all corresponding resources are deleted successfully. This PR fixes the above issue.
=> Fix leak in resourceimport_controller.go

.github/workflows/process_release.yml, Makefile, hack/release/prepare-assets.sh
* antrea-agent binaries for Linux
* install-vm.sh and install-vm.ps1
Fixes #4247
=> Add release assets needed for running Antrea on VMs (ExternalNode)

multicluster/controllers/multicluster/gateway_controller.go, multicluster/controllers/multicluster/serviceexport_controller.go
Data race can occur if multiple workers read or write r.localClusterID at the same time. 
Refactored the Reconcile loop so that the localClusterID is only set when it is missing.
=> Fix data race in serviceexport_controller

build/charts/antrea/templates/agent/daemonset.yaml, build/images/scripts/container_liveness_probe, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_test.go, pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/apiserver_test.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_bridge_test.go
This helps automatic recovery if some issues cause OFSwitch reconnection to
not work properly.
It also fixes a race condition between the IsConnected and SwitchConnected
methods of OFBridge and makes necessary changes to the constructor of
APIServer to allow testing.
For #4092
=> Add OFSwitch connection check to Agent's liveness probes

pkg/apiserver/registry/controlplane/egressgroup/rest_test.go, pkg/apiserver/registry/controlplane/nodestatssummary/rest_test.go, pkg/apiserver/registry/networkpolicy/addressgroup/rest_test.go, pkg/apiserver/registry/networkpolicy/appliedtogroup/rest_test.go, pkg/apiserver/registry/networkpolicy/clustergroupmember/rest_test.go, pkg/apiserver/registry/networkpolicy/groupassociation/rest_test.go, pkg/apiserver/registry/networkpolicy/networkpolicy/rest_test.go, pkg/apiserver/registry/networkpolicy/networkpolicy/subresources_test.go, pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go, pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go, pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go, pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go, pkg/apiserver/registry/stats/multicastgroup/rest.go, pkg/apiserver/registry/stats/multicastgroup/rest_test.go, pkg/apiserver/registry/stats/networkpolicystats/rest.go, pkg/apiserver/registry/stats/networkpolicystats/rest_test.go, pkg/apiserver/registry/system/controllerinfo/rest.go, pkg/apiserver/registry/system/controllerinfo/rest_test.go, pkg/apiserver/registry/system/supportbundle/rest_test.go, pkg/support/dump.go
=> Add unit test for pkg/apiserver/registry

pkg/agent/controller/networkpolicy/reject.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/service.go, test/e2e/antreapolicy_test.go, test/integration/agent/openflow_test.go
1. Only load Service GroupID into reg when AntreaPolicy is enabled.
Service GroupID is only used by AntreaPolicy "toServices"
and "AppliedTo NodePort Serivces" features for now.
2. In IngressSecurityClassifierTable, only forward packet to
AntreaPolicyIngressRuleTable when AntreaPolicy is enabled and
proxyAll is enabled.
This forward flow is only used by AntreaPolicy "AppliedTo NodePort
Services" feature to avoid packets skip
AntreaPolicyIngressRuleTable, where policy will be enforced, when
the endpoint of this Service is not on current NodePort Node.
3. In ACNP appliedTo NodePort Service e2e test, change to add another
netNS to fake external network.
=> Enhance ACNP Service related feature

pkg/apiserver/registry/stats/multicastgroup/rest_test.go
The backend storage stores items in a map, when the List method reads item list from the map, the order of items is random, which caused the test to fail sometimes. The patch fixes it by ignoring the order of the elements when validating.
---
Thanks @jainpulkit22 for reporting the issue.
=> Fix multicast group unit test

docs/multicluster/user-guide.md
Add doc for Pod to Pod connectivity feature in the Antrea Multi-cluster user guide.
=> Update Multi-cluster doc for Pod to Pod connectivity

docs/multicluster/antctl.md, pkg/antctl/antctl.go, pkg/antctl/raw/multicluster/commands.go, pkg/antctl/raw/multicluster/common/common.go, pkg/antctl/raw/multicluster/common/common_test.go, pkg/antctl/raw/multicluster/create/member_token.go, pkg/antctl/raw/multicluster/create/member_token_test.go, pkg/antctl/raw/multicluster/delete/member_token.go, pkg/antctl/raw/multicluster/delete/member_token_test.go, pkg/antctl/raw/multicluster/get/clusterset.go, pkg/antctl/raw/multicluster/get/clusterset_test.go, pkg/antctl/raw/multicluster/get/member_token.go, pkg/antctl/raw/multicluster/get/member_token_test.go, pkg/antctl/transform/clusterset/transform.go, pkg/antctl/transform/membertoken/transform.go
Add 2 new commands for the users to fetch and delete tokens.  
+ `antctl mc get membertoken`: to fetch a member token, and print them out or write it in a file
+ `antctl mc delete membertoken`: to delete a member token and also the RoleBinding and ServiceAccount of it.
added the unit-test of these tokens and the relation functions
Resolve #4255
=> Add antcl mc commands to get/delete member token

pkg/agent/agent.go
OVS ports for TrafficControl is configured with no-flood when it is created. However, after restarting OVS, no-flood config is lost for the ports. This PR adds no-flood config to OVS ports for TrafficControl when initializing Antrea Agent.
=> Set no-flood config with ports for TrafficControl after restarting

pkg/apiserver/registry/system/supportbundle/rest.go, pkg/apiserver/registry/system/supportbundle/rest_test.go
The code should only schedule file cleanup when the returned error is empty (meaning the returned supportbundle is not nil), otherwise the supportbundle file would never be deleted and the program would panic when there is any error encountered during supportbundle collection.
https://github.com/antrea-io/antrea/pull/2598 tried to fix it but did the opposite.
Based on #4304 and #4295's testing code.
=> Fix nil pointer error when collecting agent supportbundle fails 

ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh
Images from dockerhub should add docker.io prefix. Otherwise, the ctr tag command will not recognize it.
=> Recover cloud jenkins by fixing ctr image tag issue

pkg/agent/controller/networkpolicy/reject.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/service.go, test/e2e/antreapolicy_test.go, test/integration/agent/openflow_test.go
Cherry pick of #4261 on release-1.8.
#4261: Enhance ACNP Service related feature
=> Automated cherry pick of #4261: Enhance ACNP Service related feature

pkg/agent/agent.go
Cherry pick of #4318 on release-1.7.
#4318: Set no-flood config with ports for TrafficControl after
=> Automated cherry pick of #4318: Set no-flood config with ports for TrafficControl after

multicluster/controllers/multicluster/stale_controller.go, multicluster/controllers/multicluster/stale_controller_test.go
The normalized form of a label identity was changed from
'namespace:key=value.....' to 'ns:key=value' for saving data
transferred on the wire.  The change was not reflected in
stale_controller, who calculates all non-stale label identities
in a cluster by doing a Cartesian product of Namespace
labels and Pod labels.
=> Fix wrong label normalization in stale_controller

pkg/agent/secondarynetwork/podwatch/controller.go, pkg/agent/secondarynetwork/podwatch/controller_test.go
When a Pod gets deleted and recreated, secondary network configuration fails due to misconfigured VF resource cache. Pod specific VF resource must be cleared, when a Pod gets deleted everything.
NOTE: Upon Pod creation, Podwatch controller will build a VF resource cache, if the Pod annotates to configure SRIOV based secondary network interfaces.
=> Delete Pod specific VF resource cache from Podwatch controller, when a Pod gets deleted.

.github/workflows/docker_update_base_windows.yml
Wrapping string with double quotes will throw an error. The patch fixes it by using the boolean variable itself as the expression.
See https://docs.github.com/en/actions/learn-github-actions/expressions#literals
> You don't need to enclose strings in ${{ and }}. However, if you do, you must use single quotes (') around the string. To use a literal single quote, escape the literal single quote using an additional single quote (''). Wrapping with double quotes (") will throw an error.
=> Fix antrea/base-windows image building workflow

build/images/base-windows/Dockerfile, hack/build-antrea-windows-all.sh
CNI_BINARIES_VERSION is missing when building windows-golang and base-windows images, leading to CNI binaries missing in the target image. The issue was not discovered because the curl command used in the Dockerfile ignored HTTP 404 code and didn't fail the build.
The patch adds the missing argument and makes curl command fail on HTTP errors.
=> Fix base-windows Dockerfile and script 

docs/multicluster/antctl.md, pkg/antctl/raw/multicluster/common/common.go, pkg/antctl/raw/multicluster/common/common_test.go, pkg/antctl/raw/multicluster/create/member_token.go, pkg/antctl/raw/multicluster/create/member_token_test.go, pkg/antctl/raw/multicluster/get/join_config.go, pkg/antctl/raw/multicluster/get/join_config_test.go, pkg/antctl/raw/multicluster/get/member_token.go, pkg/antctl/raw/multicluster/get/member_token_test.go, pkg/antctl/raw/multicluster/init.go, pkg/antctl/raw/multicluster/init_test.go, pkg/antctl/raw/multicluster/join.go, pkg/antctl/raw/multicluster/join_test.go
Add a "--member-token TOKEN" option to print the token Secret manifest with the member join parameters.
Also fixed the "get membertoken" YAML output and "join" command code to support creating the token Secret from the "get membertoken" output.
=> Extend "antctl mc get joinconfig" to print member token Secret

Makefile, ci/jenkins/test.sh
Current windows building method always build base-windows image at
the first time. But it is not necessary when the base image exists.
The goal of this PR is to skip base image building by default if
it exists to speed up compilation for both CI pipelines and users.
=> Skip building base-windows image if it already exists

pkg/antctl/raw/set/command.go, pkg/antctl/raw/set/flowaggregator/command.go, pkg/antctl/raw/set/flowaggregator/command_test.go
=> Add unit tests for pkg/antctl/raw/set package.

build/images/ovs/Dockerfile.ubi
subscription-manager is disabled when running inside a container. Modify rhsm.conf to achieve the same result.
=> Fix UBI image build error

pkg/agent/multicluster/mc_route_controller.go, pkg/agent/multicluster/mc_route_controller_test.go
There is a bug when GatewayIP or InternalIP of active Gateway is changed, the corresponding openflow rules won't be updated until any other event triggers the flow sync process.
Fix the bug by comparing installed active Gateway's InternalIP and GatewayIP with current active Gateway. And add more unit tests to cover Gateway update event.
=> Update openflow rules when Gateway updates

multicluster/cmd/multicluster-controller/controller.go, multicluster/cmd/multicluster-controller/controller_test.go, multicluster/cmd/multicluster-controller/leader.go, multicluster/cmd/multicluster-controller/leader_test.go, multicluster/cmd/multicluster-controller/member.go, multicluster/cmd/multicluster-controller/member_test.go
Add unit test for `multicluster/cmd`. Using a func variable to mock the `setupManagerAndCertController` method.
=> Add unit test for multicluster/cmd

.golangci.yml, ci/README.md, hack/netpol/.golangci.yml, pkg/agent/agent_windows.go, pkg/agent/cniserver/server.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/multicast/mcast_route.go, pkg/agent/multicast/mcast_route_others.go, pkg/agent/nodeportlocal/testing/annotations.go, pkg/agent/openflow/pipeline.go, pkg/agent/proxy/endpoints.go, pkg/agent/proxy/proxier.go, pkg/agent/util/winfirewall/winfirewall.go, pkg/apiserver/registry/system/supportbundle/rest.go, pkg/controller/networkpolicy/status_controller.go, pkg/flowaggregator/exporter/ipfix.go, pkg/flowaggregator/flowaggregator.go, pkg/ovs/openflow/ofctrl_nxfields.go, pkg/support/dump.go, test/e2e/framework.go, test/e2e/nodeportlocal_test.go, test/e2e/wireguard_test.go
The "deadcode" linter is deprecated (no longer maintained) and is now replaced with "unused".
Running this new linter revealed some deadcode throughout the code base, which is being removed by this PR.
I tried to make sure that in each instance, the code was actually supposed to be removed, as opposed to indicative of a bug (e.g., function that should be called for correctness but that is not actually called).
=> Remove deadcode

pkg/agent/multicluster/mc_route_controller.go, pkg/agent/multicluster/mc_route_controller_test.go
Cherry pick of #4388 on release-1.8.
#4388: Update openflow rules when Gateway updates
=> Automated cherry pick of #4388: Update openflow rules when Gateway updates

pkg/agent/util/syscall/linux/types.go, pkg/controller/networkpolicy/tier.go, pkg/controller/networkpolicy/tier_test.go
When Antrea is newly deployed to a cluster, antrea-controller will create some system tiers but may fail a few times because kube-apiserver couldn't call validating webhook served by antrea-controller itself successfully due to readiness probing delay. The related logs looked confusing as there were only failures and users don't know if they succeed finally.
To reduce confusion, the patch uses INFO for the creation failure and indicates explicitly it will retry, and adds a success log.
=> Reduce confusion caused by transient error encountered creating tiers

pkg/flowaggregator/s3uploader/s3uploader.go
This commits fixes a typo in S3Uploader: when an upload error occurs, we should discard the successfully-uploaded buffers and keep the rest in `buffersToUpload`. Previously we were mistakenly modifying `bufferQueue`, instead of `buffersToUpload`. The typo was not caught by UT, as we currently do not have a test case to properly simulate a partial-success upload.
=> Fix typo in S3Uploader

pkg/controller/networkpolicy/antreanetworkpolicy.go, pkg/controller/networkpolicy/antreanetworkpolicy_test.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/crd_utils_test.go, pkg/controller/networkpolicy/validate.go, pkg/controller/networkpolicy/validate_test.go
This PR add support for L7 Antrea native NetworkPolicy in the controller side.
- Added support for passing `L7Protocols` to agent when processing ClusterNetworkPolicy and AntreaNetworkPolicy.
- Added validation for Antrea native policy that checks `L7Protocols` is only used with `Allow` action, not used with `toServices`. When `HTTP` is set, then L4Protocol is only `TCP` or unset, and not with `IGMP` or `ICMP`.
- Added UT.
=> Add L7 Antrea native NetworkPolicy support in controller

ci/check-manifest.sh, multicluster/build/yamls/antrea-multicluster-leader-global.yml, multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml, multicluster/build/yamls/antrea-multicluster-member.yml, multicluster/config/crd/bases/multicluster.crd.antrea.io_labelidentities.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml, multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
1. Update the multi-cluster manifests which are introduced by stretched NetworkPolicy controller change.
2. Add new CI steps to check multi-cluster manifests change.
=> Update multi-cluster manifests and add CI check

build/images/ethtool/Dockerfile
The image is used in tests (e.g., Kind tests) to modify some iptables rules in the host network. Because the host OS and the container OS may not use the same iptables backend by default, it is important to use the iptables wrapper: https://github.com/kubernetes-sigs/iptables-wrappers.
=> Use iptables wrapper in antrea/ethtool Docker image

multicluster/controllers/multicluster/gateway_controller.go, multicluster/controllers/multicluster/gateway_controller_test.go
After Gateway HA is enabled, the ClusterInfo type of ResourceExport will be recreated when the active Gateway is changed. But there is a case that a new ClusterInfo of ResourceExport creation may fail when the leader controller process is slow and existing ResourceExport is not deleted in time. 
The root cause is the Gateway creation event will update a ClusterInfo of ResourceExport instead of creating a new one due to it still can get existing one from cache when the ResourceExport's DeletionTimestamp is not zero, after ResourceExport is updated, it will be recycled by kubernetes very quickly since it's stale object. From Gateway controller's perspective, Gateway change is reflecting in ResourceExport, but it's actually being deleted eventually.
Fix the issue through retry when the …
=> Fix ClusterInfo type ResourceExport recreation bug

docs/antctl.md, docs/feature-gates.md, docs/multicast-guide.md
=> Add multicast documents

pkg/agent/agent.go, pkg/agent/agent_linux_test.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/agent_windows_test.go, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/interfacestore/interface_cache_test.go, pkg/agent/interfacestore/types.go, pkg/agent/util/net.go, pkg/agent/util/net_test.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/ovs_client_test.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, third_party/containernetworking/ip/link_linux.go
This issue is found on Ubuntu 22.04: the network interface for antrea-gw0
is different from the one we used in OpenFlow rules.
The reason is systemd-udev has modified the interface's MAC after it watches
a new one is created. So if Antrea Agent reads interface's information before
systemd-udev's modification, Antrea Agent would uses an incorrect value to
install OpenFlow rules.
To resolve the issue,
1. Agent generates a static MAC for antrea-gw0 or the interface used by Pod
2. Agent uses the generated MAC to create OVS internal port or veth pair
To implement the logic, some code is copied from containernetworking/plugins/ip/link_linux
latest versions to path thirdparty, this is to avoid unexpected issues introduced
when bumping up the dependent libraries.
Fix #4426 
Signed-off-by: …
=> Bugfix: Pod or gateway  use a different MAC address

multicluster/controllers/multicluster/gateway_controller.go, multicluster/controllers/multicluster/gateway_controller_test.go
Cherry pick of #4412 on release-1.9.
#4412: Fix ClusterInfo type ResourceExport recreation bug
=> Automated cherry pick of #4412: Fix ClusterInfo type ResourceExport recreation bug

build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/templates/agent/clusterrole.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/externalnode/conf/antrea-agent.conf, build/yamls/externalnode/vm-agent-rbac.yml, cmd/antrea-agent/agent.go, go.mod, go.sum, pkg/agent/supportbundlecollection/support_bundle_controller.go, pkg/agent/supportbundlecollection/support_bundle_controller_test.go, pkg/apiserver/registry/system/supportbundle/rest.go, pkg/util/compress/compress.go, pkg/util/compress/compress_test.go
Implement SupportBundleCollection on Agent
1. Watch internal SupportBundleCollection events.
2. Refactor SupportBundle compression to util.
3. Let agent to collect SupportBundle for Node/ExternalNode.
4. Upload the collected SupportBundle to file server.
Only SFTP and basic authentication are supported for now.
=> [ExternalNode]Implement SupportBundleCollection on Agent

go.mod, go.sum, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_builder.go, test/integration/ovs/ofctrl_test.go
- Remove `SetDstMAC` from interface `LearnAction` since it is never used.
- Optimize function `ctLabelRange`.
- Fix matcher string of `MatchCTLabelField` of `ofFlowBuilder`.
- Fix matcher string of `MatchICMPv6Type` of `ofFlowBuilder`.
- Fix matcher string of `MatchICMPv6Code` of `ofFlowBuilder`.
- Fix method `MatchCTSrcIP` of `ofFlowBuilder` for matching IPv6 address.
- Fix method `MatchCTDstIP` of `ofFlowBuilder` for matching IPv6 address.
- Fix method `MatchCTSrcIPNet` of `ofFlowBuilder` for matching IPv6 CIDR.
- Fix method `MatchCTDstIPNet` of `ofFlowBuilder` for matching IPv6 CIDR.
- Fix method `MatchCTProtocol` of `ofFlowBuilder` for matching IPv6 protocols.
- Add integration test for `MatchCTSrcIP`, `MatchCTDstIP`, `MatchCTSrcIPNet` and
`MatchCTDstIPNet`.
Signed-off-by: Hongliang …
=> Fix some issues in pkg/ovs/openflow

pkg/agent/cniserver/ipam/antrea_ipam_test.go, pkg/agent/cniserver/ipam/ipam_delegator.go, pkg/agent/cniserver/ipam/ipam_delegator_test.go, pkg/agent/cniserver/ipam/ipam_service_test.go
Add unit test for `antrea/pkg/agent/cniserver/ipam`. The code coverage has improved from 30% to about 79%.
=> Add unit test for ipam

pkg/agent/nodeportlocal/portcache/port_table_others_test.go, pkg/agent/nodeportlocal/portcache/port_table_test.go, pkg/agent/nodeportlocal/portcache/port_table_windows_test.go
Added unit test for pkg/agent/nodeportlocal/portcahce package.
For #4142 
=> Improve the UT coverage for portcache

ci/jenkins/test-vm.sh, test/e2e/vmagent_test.go
The CI currently uses a customized image, which contains the antrea-agent
service pre-created. The CI/Test only starts the antrea-agent service and
validates the status of the antrea agent service. But this commit integrates
the installations script with CI, utilizes that installation script
(like an end user), and installs the antrea-agent on both Linux and Windows VMs
and CI validates the status of the antrea-agent service in both VMs.
Also, Now the CI would support installing antrea-agent using install script
on multiple Linux and Windows VMs for testing purposes.
Signed-off-by: nithishs <nithishs@vmware.com>
=> Make vm agent CI script install antrea-agent service

pkg/agent/memberlist/cluster.go, pkg/agent/memberlist/cluster_test.go
The issue is several Antrea Agent are out of memory in a large scale cluster, and we observe that the memory of the failed Antrea Agent is continuously increasing, from 400MB to 1.8G in less than 24 hours.
After profiling Agent memory and call stack, we find that most memory is taken by Node resources received by Node informer watch function. From the goroutines, we find a dead lock that,
1. funciton "Cluster.Run()" is stuck at caling "Memberlist.Join()", which is blocked by requiring lock "Memberlist.nodeLock".
2. Memberlist has received a Node Join/Leave message sent by other Agent, and holds the lock "Memberlist.nodeLock". It is blocking at sending message to "Cluster.nodeEventsCh", while the consumer is also blocking.
The issue may happen in the large scale setup. Although Antrea has …
=> Bugfix: Resolve a deadlock in cluster memberlist maintanance

pkg/agent/controller/traceflow/traceflow_controller_test.go
=> Add unit tests for pkg/agent/controller/traceflow/traceflow_controller.go

pkg/agent/memberlist/cluster.go, pkg/agent/memberlist/cluster_test.go
Cherry pick of #4469 on release-1.9.
#4469: Bugfix: Resolve a deadlock in cluster memberlist maintanance
=> Automated cherry pick of #4469: Bugfix: Resolve a deadlock in cluster memberlist maintanance

pkg/agent/config/node_config.go, pkg/agent/route/route_windows.go
Cherry pick of #4103 on release-1.7.
#4103: Fix Windows AddNodePort parameter error
=> Automated cherry pick of #4103: Fix Windows AddNodePort parameter error

pkg/agent/agent.go, pkg/agent/agent_linux_test.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/agent_windows_test.go, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/interfacestore/types.go, pkg/agent/util/net.go, pkg/agent/util/net_test.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/ovs_client_test.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, third_party/containernetworking/ip/link_linux.go
Cherry pick of #4428 on release-1.8.
#4428: Bugfix: Pod or gateway interface use a different MAC from the
=> Automated cherry pick of #4428: Bugfix: Pod or gateway interface use a different MAC from the

ci/jenkins/test.sh, test/e2e/antreapolicy_test.go
Cherry pick of #3951 on release-1.7.
#3951: Add commands to cleanup dangling images on 1.24 testbed
=> Automated cherry pick of #3951: Add commands to cleanup dangling images on 1.24 testbed

build/charts/antrea/templates/agent/daemonset.yaml, build/images/scripts/container_liveness_probe, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_test.go, pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/apiserver_test.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_bridge_test.go, pkg/ovs/openflow/ofctrl_packetout_test.go
Cherry pick of #4126 on release-1.7.
#4126: Add OFSwitch connection check to Agent's liveness probes
=> Automated cherry pick of #4126: Add OFSwitch connection check to Agent's liveness probes

Makefile, build/images/Dockerfile.build.coverage, build/images/Dockerfile.build.ubi, build/images/Dockerfile.build.ubuntu, build/images/base/Dockerfile, build/images/base/Dockerfile.ubi, build/images/base/build.sh, build/images/build-tag.sh, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/apply-patches.sh, build/images/ovs/build.sh, build/images/test/Dockerfile, hack/build-antrea-linux-all.sh
Ubuntu 20.04 comes with iptables 1.8.4, which seems to have several bugs
when used with nft. In particular, we observe that iptables-restore
sometimes segfaults when restoring the ANTREA-NODE-PORT-LOCAL chain in
the nat table. Ubuntu 22.04 comes with a more recent iptables version, 1.8.7.
As part of this change, we change the tag format for base images
(antrea/openvswitch and antrea/base-ubuntu). We no longer use the OVS
version as the tag, instead we use the Antrea minor version number.
Fixes #4435
=> Upgrade Antrea base image to ubuntu:22.04

Makefile, build/images/Dockerfile.build.coverage, build/images/Dockerfile.build.ubi, build/images/Dockerfile.build.ubuntu, build/images/base/Dockerfile, build/images/base/Dockerfile.ubi, build/images/base/build.sh, build/images/build-tag.sh, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/apply-patches.sh, build/images/ovs/build.sh, build/images/test/Dockerfile, hack/build-antrea-linux-all.sh
Cherry pick of #4459 on release-1.7.
#4459: Upgrade Antrea base image to ubuntu:22.04
=> Automated cherry pick of #4459: Upgrade Antrea base image to ubuntu:22.04

pkg/apis/controlplane/types.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/crd_utils_test.go
This PR is to fix stretched networkpolicy enforcement on Pod
to MC Service traffic when the MC Service endpoint resides in
the same cluster of the client. Under current datapath design,
the packet will loose tunnel information which contains the
client's label identity, thus bypassing stretched policy
enforcement. For more details on this issue, refer to #4431
As a result, stretched NetworkPolicy enforcement need to be
divided into two parts: for in-cluster access, the Antrea Controller
will create an addressgroup matching the clusterSet-scoped
selector, just like cluster-scoped selectors. For cross-cluster
policy enforcement, label identity will be used to match
selected peers.
=> Add addressgroup peer for in-cluster stretched NetworkPolicy enforcement

ci/jenkins/test-mc.sh, multicluster/test/e2e/README.md, multicluster/test/e2e/antreapolicy_test.go, multicluster/test/e2e/framework.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go
Cherry pick of #3995 on release-1.7.
#3995: Set up Kind clusters to run multi-cluster e2e
=> Automated cherry pick of #3995: Set up Kind clusters to run multi-cluster e2e

docs/external-node.md, hack/externalnode/install-vm.sh
The installation script would help to install antrea-agent
in containers by specifying the container option in the installation
command for Linux VMs.
- Install Docker automatically based on the Linux OS.
- The script picks the latest Antrea version or the user can 
also specify the version.
- This creates systemd service which monitors the containers. 
Also, support start, restart and stop the service.
Signed-off-by: nithishs <nithishs@vmware.com>
=> Adds the containerize option for antrea-agent installation on Linux VMs 

build/charts/antrea/crds/traceflow.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/packetin_test.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/controller/traceflow/traceflow_controller_test.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/pipeline.go, pkg/apis/crd/v1alpha1/types.go, pkg/graphviz/traceflow.go, pkg/graphviz/traceflow_test.go, pkg/querier/querier.go, test/e2e/traceflow_test.go, test/integration/agent/openflow_test.go
Add an Observation in result of Traceflow for Egress which
include Egress component, two TraceflowAction, Egress IP
and Egress name.
Add a mark `RemoteSNATRegMark` to indicate remote SNAT for
remote Egress traffic. This mark helps to distinguish this traffic from
Inter-Node Pod-to-Pod traffic on source Node when Egress IP is 
equal to a remote Node IP (static Egress).
Add e2e test for Egress in Traceflow for two cases.
1. Egress from local Node.
2. Egress from remote Node.
Add unit tests for this patch.
Fixes #2247
=> Improve support for Egress in Traceflow

build/yamls/antrea-windows-containerd.yml, build/yamls/windows/base/agent-containerd.yml, build/yamls/windows/base/conf/Install-WindowsCNI-Containerd.ps1, build/yamls/windows/base/conf/Run-AntreaAgent-Containerd.ps1, ci/jenkins/test-mc.sh, ci/jenkins/test.sh, docs/windows.md, hack/generate-manifest-windows.sh, hack/release/prepare-assets.sh, test/e2e/traceflow_test.go
Add new containerd yaml file for windows agent because of the different cni workflow.
=> Add containerd runtime support for antrea agent on windows

build/images/Dockerfile.octant.ubuntu, build/images/Dockerfile.simulator.build.ubuntu, build/images/codegen/Dockerfile, build/images/codegen/README.md, build/images/ethtool/Dockerfile, build/images/ethtool/README.md, build/images/flow-aggregator/Dockerfile, build/images/flow-aggregator/Dockerfile.coverage, build/images/perftool/Dockerfile, build/images/perftool/README.md, build/images/wireguard-go/Dockerfile, build/images/wireguard-go/README.md, docs/cookbooks/multus/build/cni-dhcp-daemon/Dockerfile, docs/cookbooks/multus/resources/dhcp-daemon.yml, hack/update-codegen.sh, multicluster/build/images/Dockerfile.build.coverage, test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/playbook/roles/common/templates/containerd.conf.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2
We also update the Vagrant-based test infra to use Ubuntu 22.04 as the Node OS. Because Ubuntu 22.04 ships with crgroup v2, we need to configure containerd to use the systemd cgroup driver.
=> Update remaining images to use ubuntu:22.04 base image

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, pkg/config/agent/config.go
Antrea agent configuration file to enable and configure secondary network specific OVS parameters. Required to enable service function chaining.
Signed-off-by: Adwait Patil <adwait.nilesh.patil@intel.com>
=> Antrea agent configuration file to enable and configure secondary network specific OVS parameters.

pkg/agent/controller/networkpolicy/l7engine/reconciler.go, pkg/agent/controller/networkpolicy/l7engine/reconciler_test.go, test/e2e/l7networkpolicy_test.go
By default, suricata performs pattern-matching for provided content. To support exact match, prefix match, and suffix match, we use wildcards to indicate whether an exact match is expected.
- A string starting with `*` means suffix match. For example, `"*.foo.com"` matches `"www.foo.com"`.
- A string ending with `*` means prefix match. For example, `"/public/*"` matches `"/public/index.html"`.
- A string starting with and ending with `*` means pattern-matching. For example, `"*/v2/*"` matches `"/api/v2/pods"`.
- A string having no `*` means exact match. For example, `"/index.html"` can only match `"/index.html"`.
For https://github.com/antrea-io/antrea/issues/4231
=> Support wildcards for HTTP path and host in L7NetworkPolicy

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/conf/antrea-controller.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, ci/jenkins/test-mc.sh, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_linux_test.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go, docs/feature-gates.md, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, multicluster/build/images/Dockerfile.build, multicluster/build/images/Dockerfile.build.coverage, pkg/config/agent/config.go
To be compatible with earlier version deployment manifests, set multicluster.enableGateway to true if multicluster.enable is set to true.
Also change the validation logic to ingore Multi-cluster options if the Multicluster feature gate is disabled, to be consistent with other features.
=> Rename Agent config option multicluster.enable to enableGateway

hack/.md_links_config.json
The HTTP requests seem to fail consistently, maybe because of some DDOS protection.
=> Exclude https://suricata.io/ from markdown link checker

pkg/agent/multicluster/stretched_networkpolicy_controller_test.go
This PR change to use a longer timeout in Multi-cluster NetworkPolicy UT.
Recently, we notice that Multi-cluster NetworkPolicy UT is flaky. The err shows that it timeout while waiting for the Pod to be created.
One flake example:
https://github.com/antrea-io/antrea/actions/runs/3733157661/jobs/6333694462
=> Use longer timeout in MCNP UT

pkg/monitor/agent_test.go, pkg/monitor/controller_test.go
=> Add unit test for pkg/monitor

pkg/ipfix/ipfix_registry_test.go
=> Add unit test for pkg/ipfix

Makefile
Until now, one had to manually remove the old binary for the new one to be installed.
=> Automatically install new golangci-lint binary when version is bumped

pkg/flowaggregator/flowaggregator_test.go
Few unit tests for pkg/flowaggregator/flowaggregator.go fails 
sometime because informer used in unit tests was not cache synced.
=> Fix UT for pkg/flowaggregator/flowaggregator.go

build/charts/antrea/crds/clusternetworkpolicy.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, multicluster/test/e2e/service_test.go
=> Change toService.scope to enum

pkg/controller/networkpolicy/status_controller.go, pkg/controller/networkpolicy/status_controller_test.go
Modify the max length of Message field in ANP Condtion to 256
Fix #4559 
=> Modify the message length limitation in ANP Condition

multicluster/controllers/multicluster/commonarea/remote_common_area.go, multicluster/controllers/multicluster/member/acnp_resourceimport_controller_test.go, multicluster/controllers/multicluster/member/clusterinfo_importer_test.go, multicluster/controllers/multicluster/member/clusterset_controller.go, multicluster/controllers/multicluster/member/labelidentity_import_controller.go, multicluster/controllers/multicluster/member/labelidentity_import_controller_test.go, multicluster/controllers/multicluster/member/resourceimport_controller.go, multicluster/controllers/multicluster/member/resourceimport_controller_test.go
Also change NewResourceImportReconciler and
NewLabelIdentityResourceImportReconciler to private funcs.
=> Change RemoteCommonArea localClusterID to ClusterID type

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/conf/antrea-controller.conf, build/charts/antrea/crds/clusternetworkpolicy.yaml, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, docs/feature-gates.md, docs/multicluster/quick-start.md, docs/multicluster/user-guide.md, multicluster/test/e2e/service_test.go, pkg/config/agent/config.go, pkg/config/controller/config.go
Cherry pick of #4543 and #4562 on release-1.10.
#4543: Update YAMLs and docs about Multi-cluster NetworkPolicy
#4562: Change ANP/ACNP toService.scope to enum
=> Automated cherry pick of #4543 and #4562

pkg/antctl/runtime/runtime.go
Antctl failed to talk with GCP cluster and it shows: `Error: no Auth Provider found for name "gcp"`. According to the example of client-go, we need to import auth package to support different public platform's authentication.
Here is the sample code:
https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L33-L40
=> Import auth to support different platforms

pkg/antctl/runtime/runtime.go
Cherry pick of #4494 on release-1.10.
#4494: Import auth to support different platforms
=> Automated cherry pick of #4494: Import auth to support different platforms

build/yamls/externalnode/vm-agent-rbac.yml, ci/jenkins/test-vm.sh, docs/external-node.md
1. Crate a separate Secret for VM Agent in RBAC file, because the Secret for a ServiceAccount is not created automatically since K8s v1.24.
2. Use the manually created Secret in Agent kubeconfig file.
Fix #4558 
=> [ExternalNode] Create Secret for vm-agent in RBAC

pkg/agent/agent.go, pkg/agent/config/node_config.go, pkg/agent/config/node_config_test.go
When a Cluster is dualstack, it assumes that every Node is configured with both IPv4 and IPv6 addresses for Antrea Agent. However, if a Node is only configured with either IPv4 or IPv6 address, Antrea Agent will get crashed.
=> Fix possible Antrea Agent crash in dualstack mode

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/serviceexternalip/controller_test.go, pkg/agent/ipassigner/ip_assigner_linux.go, pkg/agent/ipassigner/ip_assigner_windows.go, pkg/agent/memberlist/cluster.go, pkg/config/agent/config.go
The current implementation of Egress uses 8 bits of pkt mark to indicate which SNAT IP the egress traffic should use, which means at most 255 Egress IPs can be assigned to a single Node. Besides, some Node network may restrict the number of secondary IPs that can be assigned to a Node, e.g. EKS.
This patch adds a configuration option maxEgressIPsPerNode and makes it default to 255. When a Node cannot accommodate more Egress IPs, the next Node will be tried, until an available Node is found or all Nodes are tried.
=> Support limiting number of Egress IPs that can be assigned to a Node 

pkg/agent/controller/networkpolicy/fqdn_test.go
Adds the unit test for pkg/agent/controller/networkpolicy/fqdn.go
for #4142
Signed-off-by: Harshitha U R <harshithaur1611@gmail.com>
=> Adds unit test for fqdn.go

cmd/antrea-agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go
Set NO_FLOOD to IPsec tunnel ports to avoid ARP flooding.
=> Set NO_FLOOD to IPsec tunnel ports

build/images/scripts/install_cni
Whereabouts CNI binary is executed in the antrea-agent container for secondary network IPAM. It needs not to be in the host filesystem.
=> No longer install Whereabouts CNI to host

pkg/ovs/ovsconfig/default_windows.go, pkg/ovs/ovsconfig/ovs_client.go
Improve comment to clarify that we connect to ovsdb
using unix domain socket or named pipe on windows,
never using any SSL connection option.
Fixes #4033
=> Add comment for constant "winpipe"

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-agent.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-agent/agent.go, docs/multicluster/user-guide.md, pkg/agent/multicluster/mc_route_controller.go, pkg/agent/multicluster/mc_route_controller_test.go, pkg/config/agent/config.go
Add a toggle for Multi-cluster Pod-to-Pod connectivity in antrea-agent configuration. The Pod-to-Pod connectivity feature will be enabled when the toggle is set true and Pod CIDRs are provided in the Antrea Multi-cluster configuration.
=> Add a toggle for Multi-cluster Pod-to-Pod connectivity

.github/workflows/go.yml, .github/workflows/kind.yml
The codecov upload step will still show success when coverage report uploading is actually failed, so set the `fail_ci_if_error` to true to make sure developers be aware that the report upload job need to be re-run when it's failed.
=> Fail CI when codecov upload failed

docs/maintainers/release.md
Github introduced a new option when creating a release (`Set as the latest release` check box). The box is checked by default. It should be unchecked when creating a patch release for an older minor version of Antrea.
For example, assuming the most recent minor version of Antrea is 1.9:
* when releasing 1.8.X, the box should be unchecked (not the latest release)
* when releasing 1.9.X, the box should be checked (latest release)
* when releasing 1.10.0, the box should be checked (latest release); after this release, the box will be unchecked for all 1.9.X patch releases.
=> Update the release documentation for maintainers

.github/workflows/build_tag.yml, .github/workflows/process_release.yml, .github/workflows/update_changelog.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Remove deprecated set-output command

cmd/antrea-agent/agent.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/egress/ip_scheduler.go, pkg/agent/controller/egress/ip_scheduler_test.go, pkg/agent/memberlist/cluster.go, pkg/agent/memberlist/cluster_test.go, pkg/agent/types/annotations.go
PR #4593 introduced maxEgressIPsPerNode to limit the number of Egress IPs that can be assigned to a Node. However, it used the EgressInformer cache to check whether a Node can accommodate new Egress IPs and did the calculation for different Egresses concurrently, which may cause inconsistent schedule results among agents. For instance:
When Nodes' capacity is 1 and two Egresses, e1 and e2, are created concurrently, different agents may process them in different orders, with different contexts:
- agent a1 may process Egress e1 first and assign it to Node n1; it then processes Egress e2 and think it should be assigned to Node n2 by agent a2 because n1 is out of space.
- agent a2 may process Egress e1 and e2 faster, before any of their status is updated in Egress API, and would think both …
=> Improve Egress IP scheduling

multicluster/test/e2e/service_test.go
Fixed #4503
Add the test case to verify the serviceexport connection in the same cluster
=> MCS e2e tests for local Service's Endpoint access

.github/workflows/go.yml, .github/workflows/kind.yml
Codecov upload fail quite often due to token accessibility issue, this will block github CI.
So disable it when it's triggered in pull request.
Please check the details in #4668
=> Don't fail codecov upload in pull request CI

pkg/agent/openflow/client_test.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/topology.go, pkg/agent/proxy/topology_test.go, third_party/proxy/service.go, third_party/proxy/types.go, third_party/proxy/util/service.go
=> Support ProxyTerminatingEndpoints in AntreaProxy

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_test.go, pkg/agent/controller/trafficcontrol/controller.go, pkg/agent/interfacestore/interface_cache_test.go, pkg/agent/interfacestore/types.go
There could be some cases that OVS ports are left invalid. Setting NO_FLOOD for these ports will fail for sure and restarting agents would just meet the same error. Later we should enhance the port cleanup logic, either when they are firstly identified, or when their owners do the initialization. For now, as there could be invalid ports in interface cache, we should ensure a port is valid before setting NO_FLOOD.
Fixes #4673
=> Ensure OVS port is valid before setting NO_FLOOD

pkg/agent/controller/traceflow/packetin.go
On dual-stack testbed, Inter-Node traceflow observation for 
IPv4 packet in encap mode has empty tunnelDstIP field because 
`isIPv6` variable is set.
Change the logic to set `isIPv6` variable based on the packet 
IPv4 or IPv6.
Fixes #4502
=> Fix tunnelDstIP field in traceflow on dual-stack

build/yamls/antrea-windows-containerd.yml, build/yamls/windows/containerd/conf/Run-AntreaAgent-Containerd.ps1
Set the default klog verbosity value to 0 for Windows containerd agent.
=> Update default klog verbosity value for Windows containerd agent

cmd/antrea-agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/openflow/types/types.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/topology.go, pkg/agent/proxy/topology_test.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_group.go, pkg/ovs/openflow/ofctrl_group_test.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
When the Endpoint of Multi-cluster Service is a local Service ClusterIP, refine the action to let it go to the corresponding exported Service's group to do final Endpoint selection. This can avoid the case that the traffic goes out of antrea-gw0 and goes back to OVS again when a local Pod is trying to access a MC Service but a local Service's Endpoint is selected.
Resolve #4431 
=> Refine Endpoint selection for multi-cluster Service

pkg/agent/apiserver/handlers/memberlist/handler.go, pkg/agent/apiserver/handlers/memberlist/handler_test.go, pkg/support/dump.go, pkg/support/dump_others.go, pkg/support/dump_windows.go
TestAntctl/testAntctlControllerRemoteAccess failed
on all windows testbed because it cannot get
output of `antctl get memberlist` while collecting
supportbundle from outside on windows testbed as
memberlist is not running.
This PR handles the above case as success on linux
and writes output to file that memberlist is not running.
On Windows, don't collect memberlist as it never runs on Windows.
Fixes #4659
=> Fix e2e TestAntctl on windows testbed

build/yamls/antrea-windows-containerd.yml, build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
Create /opt/cni/bin/ and /etc/cni/net.d/ folders to avoid errors caused by non-existent paths.
Fixes #4680
=> Force create cni folders when starting Windows containerd agent

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_linux_test.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/route/testing/mock_route.go, pkg/agent/util/net.go, test/integration/agent/route_test.go
=> Fix that Service routes may get lost when starting on Windows

pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_bridge_test.go
Fix missing call of removing groupDb cache when deleting OVS group
The old group will be reused unexpectedly if groupDb cache managed
by OFBridge is not cleared for that group, which causes a new group
claims to have a different group type acquiring the old group type.
Fixes #4575
=> Fix missing call of removing groupDb cache when deleting OVS group

cmd/antrea-agent/agent.go, docs/antrea-ipam.md, multicluster/test/e2e/antreapolicy_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reject.go, pkg/agent/controller/networkpolicy/reject_test.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_linux_test.go, pkg/ovs/openflow/interfaces.go, test/e2e/antreaipam_anp_test.go, test/e2e/antreaipam_test.go, test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/e2e/k8s_util.go, test/e2e/proxy_test.go, test/e2e/service_test.go
Fixed issues:
Unexpected SNAT from local regular Pod to local FlexibleIPAM Pod.
ANP/ACNP reject failed on some cases when src/dst is FlexibleIPAM Pod.
e2e enhancement:
Added AntreaIPAMAntreaPolicy e2e cases.
Fixed wrong Pod labels on createAgnhostServiceAndBackendPods
doc enhancement:
Added missing requirements.
=> [flexible-ipam] Fix issues and add ClusterNetworkPolicy e2e cases

ci/jenkins/test.sh
DOCKER_REGISTRY is no longer needed in agent image tag.
Remove it to align with containerd image tag in CI pipeline.
Update more image tags which is unavailable in public repo.
Fixes https://github.com/antrea-io/antrea/issues/4696
=> Fix windows image building error in jenkins pipeline

ci/test-conformance-eks.sh
Otherwise creaing cluster would fail with error.
=> Specify AMI Family required by eksctl when using a custom AMI

ci/jenkins/README.md, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects-lab.yaml, ci/jenkins/test.sh
Task: build a CI script for Antrea upstream to create a kind cluster and run CI tests (conformance and NetworkPolicy ) on it.
We don't need to run Antrea E2E tests in kind via this test.sh.  because the github workflow ".github/workflows/kind.yml" also runs E2E test in kind via "./ci/kind/test-e2e-kind.sh".
=> Run Conformance and NetworkPolicy Tests in Kind

pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, test/integration/agent/openflow_test.go
The main purpose of this PR is to avoid potential inconsistencies between
the cached Endpoints and those installed in OVS, like #4681, #4692.
This PR also updates:
- Method UninstallEndpointFlows of ofClient, support deleting flows of
multiple Endpoints.
- Remove possible groups when a Service is deleted.
- Log something when a group for a Service is not created.
- Optimize and unify log.
=> Keep the cached Endpoints the same as those installed in OVS

pkg/apiserver/storage/ram/store_test.go
The test failure was observed several times on Windows runners, which is slower than Linux runners.
100ms is perhaps too short for the unresponsive watcher to be killed.
```
W0313 08:27:30.789254    3936 env.go:126] Failed to get Pod Namespace from environment. Using "kube-system" as the Antrea Service Namespace
--- FAIL: TestRamStoreWatchTimeout (0.75s)
store_test.go:526: w2 was not stopped, expected stopped
store_test.go:528: 
Error Trace:	D:/a/antrea/antrea/pkg/apiserver/storage/ram/store_test.go:528
Error:      	Not equal: 
expected: 1
actual  : 2
Test:       	TestRamStoreWatchTimeout
Messages:   	Unexpected watchers number
W0313 08:27:31.564994    3936 store.go:350] Forcing stopping watcher (selectors: &{ app=nginx }) due to unresponsiveness
```
=> Increase watcher termination reaction timeout to avoid flaky test

pkg/agent/openflow/groups.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
AntreaProxy doesn't allocate a group for cluster Endpoints if a ClusterIP Service's InternalTrafficPolicy is Local, so getting the group ID of cluster Endpoints returns nothing. The previous code stopped processing the Service and logged error mistakenly in this case, causing this Service's flows and routes never being deleted.
The patch fixes it and enhances the validation for this case.
=> Fix ClusterIP Service processing

pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/packetin_test.go, pkg/agent/openflow/packetin.go
After receiving a Packet In for a live Traceflow, the controller uninstalls the corresponding OVS flows to prevent additional Packet Ins (from different connections which also match the Live Traceflow filters).
However, if 2 connections happen within a very short time window (< 1ms in my testbed) and both match the Live Traceflow filters, it is still possible for 2 Packet In messages to be received. To avoid duplicate Node Results in the Live Traceflow Status, we need to ignore all Packet In messages received after the first one.
Fixes #4714
=> Avoid duplicate Node Results in Live Traceflow Status

pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_linux_test.go, pkg/agent/util/net_test.go, pkg/agent/util/net_windows.go, pkg/agent/util/net_windows_test.go, pkg/agent/util/netlink/netlink_linux.go, pkg/agent/util/netlink/testing/mock_netlink_linux.go, test/integration/agent/net_windows_test.go
=> Add unit tests for pkg/agent/util/net

docs/antrea-l7-network-policy.md, docs/antrea-network-policy.md, pkg/agent/controller/networkpolicy/audit_logging.go, pkg/agent/controller/networkpolicy/audit_logging_test.go, pkg/agent/controller/networkpolicy/l7engine/reconciler.go, pkg/agent/controller/networkpolicy/l7engine/reconciler_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/openflow/fields.go, pkg/agent/openflow/openflow_test_utils.go, pkg/agent/openflow/pipeline.go
Fix inaccurate Antrea Native Policy logging, where the L7NP will be logged as `Redirect` not `Allow`. Update UT to cover more cases.
Add event log file for Suricata at `/var/log/antrea/networkpolicy/l7engine`. Due to the limitation of available Suricata options, currently `eve.log` logs all the alerts (`reject`&`pass`) regardless of `enableLogging`, event_type: "alert". Meanwhile packets are only logged if `enableLogging: true`, "event_type: "packet".
=> Support L7 Network Policy Logging

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_linux_test.go, pkg/agent/route/route_windows.go, pkg/agent/route/testing/mock_route.go
When proxyAll is enabled, AntreaProxy needs to install routes in the host network namespace to redirect traffic to OVS for load balancing. For a Service with multiple ports, multiple ServicePorts are generated and processed. The previous code installed the route for a ClusterIP or a LoadBalancerIP multiple times when such a Service was created, and uninstalled the route multiple times when it was deleted, leading to a few problems.
This patch adds a serviceIPRouteReferences which tracks the references of Service IPs' routes. The key is the Service IP and the value is the the set of ServiceInfo strings. With the references, we install a route exactly once as long as it's used by any ServicePorts and uninstall it exactly once when it's no longer used by any ServicePorts.
This patch also …
=> Fix route deletion for Service ClusterIP and LoadBalancerIP

build/charts/antrea/conf/antrea-agent.conf, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/windows/base/conf/antrea-agent.conf, docs/feature-gates.md, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/apiserver/handlers/featuregates/handler_test.go, pkg/features/antrea_features.go
Test environment:
- Kubernetes version: v.1.24.0
- AntreaProxy options:
- with proxyAll enabled, and with kube-proxy removed
- IPv4 only
Passed tests:
Kubernetes whole Conformance tests, **356/356** passed.
Kubernetes sig-network tests, **11/172** passed with skip argument `\[Slow\]|\[Serial\]|\[Disruptive\]|\[GCE\]|\[Feature:IPv6DualStack\]|\[Feature:IPv6DualStackAlphaFeature\]|should create pod that uses dns|should provide Internet connection for containers`. 
The following tests are not related to EndpointSlice.
```
[sig-network] KubeProxy should set TCP CLOSE_WAIT timeout [Privileged]
[sig-network] Networking should check kube-proxy urls
[sig-network] Services should implement service.kubernetes.io/headless
[sig-network] Conntrack should be able to preserve UDP traffic when server pod …
```
=> Graduate feature EndpointSlice from Alpha to Beta

pkg/agent/controller/networkpolicy/fqdn.go, pkg/ovs/openflow/ofctrl_packetin.go, pkg/ovs/openflow/ofctrl_packetin_test.go, third_party/dns/dns.go, third_party/dns/dns_test.go
A DNS message sent over TCP will be fragmented if its length is greater than MTU, in which case FQDN policy wouldn't work as expected because the used DNS library expects the entire message. However, it's been observed that DNS message was fragmented frequently in tests, which may be applicable to production environments as well. On the other hand, we don't really need the entire message to support FQDN policy, and the first fragment normally already contains the information we need, the question and answer sections.
This patch forks and modifies the message Unpack function to be able to handle fragmented messages.
=> Support inspecting fragmented DNS message for FQDN policy

cmd/antrea-agent/agent.go, docs/feature-gates.md, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
When EndpointSlice feature is enabled, it required EndpointSlice v1 API to be available, otherwise it didn't work. But EndpointSlice v1 API is only available in Kubernetes >= 1.21. For earlier versions, there is no simple way to fallback to EndpointSlice v1beta1 API because the proxy library code supports one API version only.
To make Antrea compatible with earlier releases, we could check if the EndpointSlice v1 API is available and fallback to Endpoints API if it's not.
-----------
I found the issue because the K8s version of some testbeds in Antrea CI is quite old, leading to test failures.
The original statement that Antrea can work with Kubernetes version >=1.16 as long as the EndpointSlice API is enabled was wrong. The code can only work with EndpointSlice v1 API, which was added in …
=> Fallback to Endpoints API if EndpointSlice API is unavailable

ci/jenkins/test.sh
…containerd testbed
This fix is to avoid deleting latest images on testbed.
=> Clean up agent images before building linux images on containerd testbed 

pkg/agent/apiserver/handlers/memberlist/handler.go, pkg/support/dump_others.go
The antctl test expects a command to either succeed or fail with an error message saying the feature is not enabled.
=> Update the error message of memberlist command

test/e2e/framework.go
To reduce test run time and to avoid affecting subsequent tests.
Fixes #4717 #4675 #4632
=> Set test Pod's TerminationGracePeriodSeconds to 1 for immediate shutdown

build/yamls/antrea-windows-containerd.yml, build/yamls/windows/base/conf/Run-AntreaAgent-Containerd.ps1
Cherry pick of #4676 on release-1.10.
#4676: Update default klog verbosity value for Windows containerd
=> Automated cherry pick of #4676: Update default klog verbosity value for Windows containerd

pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_bridge_test.go
Cherry pick of #4592 on release-1.10.
#4592: Fix missing call of removing groupDb cache when deleting OVS
=> Automated cherry pick of #4592: Fix missing call of removing groupDb cache when deleting OVS

build/images/Dockerfile.octant.ubuntu, build/images/Dockerfile.simulator.build.ubuntu, build/images/codegen/Dockerfile, build/images/codegen/README.md, build/images/ethtool/Dockerfile, build/images/ethtool/README.md, build/images/flow-aggregator/Dockerfile, build/images/flow-aggregator/Dockerfile.coverage, build/images/perftool/Dockerfile, build/images/perftool/README.md, build/images/wireguard-go/Dockerfile, build/images/wireguard-go/README.md, docs/cookbooks/multus/build/cni-dhcp-daemon/Dockerfile, docs/cookbooks/multus/resources/dhcp-daemon.yml, hack/update-codegen.sh, multicluster/build/images/Dockerfile.build.coverage, test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/playbook/roles/common/templates/containerd.conf.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2
Cherry pick of #4499 on release-1.7.
#4499: Update remaining images to use ubuntu:22.04 base image
=> Automated cherry pick of #4499: Update remaining images to use ubuntu:22.04 base image

hack/release/prepare-changelog.sh
Update the script to support rendering changelog for patch releases.
The idea is to list PRs with the "kind/cherry-pick" label and find
the original PRs. Then retrieve the information of the original PR if
it contains the label "action/release-note".
This takes more time as we cannot check the PRs in one shot.
=> Support rendering changelog for patch releases

ci/jenkins/test.sh
Cherry pick of #4697 on release-1.7.
#4697: Fix windows image building error in jenkins pipeline
=> Automated cherry pick of #4697: Fix windows image building error in jenkins pipeline

.github/workflows/benchmark.yml, .github/workflows/codeql.yml, .github/workflows/dependabot.yml, .github/workflows/go.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/process_release.yml, .github/workflows/trivy_scan.yml, .github/workflows/trivy_scan_before_release.yml, .github/workflows/verify_docs.yml
The new version of the action enables caching by default.
=> Bump actions/setup-go from 3 to 4

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/nodeportlocal/rules/netnat_rule.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_linux_test.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/route/testing/mock_route.go, pkg/agent/util/net.go, pkg/agent/util/net_windows.go, pkg/agent/util/net_windows_test.go, test/integration/agent/route_test.go
This PR unifies the functions in route_linux.go and route_windows.go:
- AddLoadBalancer
- DeleteLoadBalancer
Remove:
- DeleteClusterIPRoute
- AddClusterIPRoute
Fix:
- Add the route for calculated ClusterIP CIDR to Service route cache,
then the route can be restored when it was deleted since members of
the route cache are synchronized periodically.
=> Unify some functions in pkg/agent/route

ci/jenkins/test.sh
Add necessary image tags which was removed by (#4720).
For #4704
=> Fix Windows CI failures by updating image tags

README.md
It is now possible to display the latest release by semver, instead of the latest release by date. When displaying by date, the README may show an older Antrea version, for which a patch release was recently published. Instead, we prefer to display the most recent patch release for the most recent minor release, which is what most new users will need / want to deploy.
=> Fix release badge at the top of README file

multicluster/test/e2e/fixtures.go, multicluster/test/e2e/framework.go, multicluster/test/e2e/main_test.go, multicluster/test/e2e/service_test.go, pkg/agent/controller/networkpolicy/reject.go, pkg/agent/controller/networkpolicy/reject_test.go, test/e2e/antreaipam_test.go, test/e2e/antreapolicy_test.go, test/e2e/basic_test.go, test/e2e/framework.go, test/e2e/proxy_test.go, test/e2e/service_externalip_test.go, test/e2e/service_test.go, test/e2e/wireguard_test.go
Cherry pick of #4547 on release-1.10.
#4547: Add ServiceLocalToRemote reject type
=> Automated cherry pick of #4547: Add ServiceLocalToRemote reject type

build/charts/antrea/crds/clustergroup.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-crds.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, docs/api.md, test/e2e/antreapolicy_test.go, test/e2e/clustergroup_test.go, test/e2e/k8s_util.go, test/e2e/utils/cg_spec_builder.go
The API was scheduled for deletion a year ago.
My proposal is to stop serving the API in the next release (v1.12), and remove it completely in the release after that (v1.13). If someone upgrades to Antrea v1.12 and gets errors, they can easily edit the CRD to re-enable serving for the older version (and then convert all their existing resources).
=> Stop serving v1alpha2 version of the ClusterGroup CRD

Makefile
Cherry pick of #4331 on release-1.9.
#4331: Add docker network parameter to windows build command
=> Automated cherry pick of #4331: Add docker network parameter to windows build command

pkg/agent/controller/traceflow/packetin.go
Cherry pick of #4529 on release-1.10.
#4529: Fix tunnelDstIP field in traceflow on dual-stack
=> Automated cherry pick of #4529: Fix tunnelDstIP field in traceflow on dual-stack

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
The API resource name is plural. The incorrect check caused AntreaProxy to always fall back to the Endpoints API.
=> Fix EndpointSlice API availablility check

test/e2e/framework.go
Cherry pick of #4745 on release-1.10.
#4745: Set test Pod's TerminationGracePeriodSeconds to 1 for
=> Automated cherry pick of #4745: Set test Pod's TerminationGracePeriodSeconds to 1 for

test/e2e/antreapolicy_test.go, test/e2e/service_test.go
createAgnhostServiceAndBackendPods should create the service with the
selector that can only selects the Pod created together with it.
Previous selector selected all Pods using agnhost image, causing
traffic destined for service to be forwarded to unexpected Pod.
This patch also changed to use same Pod selector for Service and
ClusterNetworkPolicy to avoid redundancy and inconsistency.
=> Fix e2e test RejectServiceTraffic

build/charts/antrea/README.md, build/charts/antrea/conf/antrea-controller.conf, build/charts/antrea/values.yaml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, cmd/antrea-controller/controller.go, pkg/config/controller/config.go
In the existing logic, Antrea Controller retrieves the client CA from ConfigMap kube-system/extension-apiserver-authentication, which is published by kube-apiserver. In some cases, the incoming connection is from the client with a certificate signed by a different CA bundle.
This patch adds a configuration in antrea-controller to allow user to specify the client CA. Antrea Controller will use it to validate the incoming client certificate in a mTLS connection.
=> Add Controller configuration to specify client CA

.golangci.yml, Makefile, multicluster/controllers/multicluster/member/serviceexport_controller_test.go, pkg/agent/externalnode/external_node_controller_linux_test.go, pkg/agent/externalnode/external_node_controller_test.go
The timeout for golangci-lint is also increased to 15m, as I have observed some recent Gihub workflow failures caused by the 10m timeout.
=> Update golangci-lint version

ci/run-k8s-e2e-tests.sh
The default timeout will be 60mins which is not necessary for a deletion action, so change it to 10mins so e2e tests can fail quicker instead of waiting for 1 hour to fail:
```
Deleting sonobuoy resources
time="2023-04-10T14:13:43Z" level=info msg="delete request issued" kind=namespace namespace=sonobuoy
time="2023-04-10T14:13:43Z" level=info msg="delete request issued" kind=clusterrolebindings
time="2023-04-10T14:13:43Z" level=info msg="delete request issued" kind=clusterroles
time="2023-04-10T15:13:43Z" level=error msg="failed to delete sonobuoy resources: waiting for delete conditions to be met: timed out waiting for the condition"
```
=> Add timeout for sonobuoy deletion

ci/jenkins/test.sh
When the sonobuoy test is failed, the script `run-k8s-e2e-tests.sh` will return exit code 1, and then the caller `test.sh` will fail immediately without checking and printing the sonobuoy test results in the jenkins console. Fix the issue by ignoring the exit code temporarily.
And update a few print log.
=> Ignore script exit code for conformance test

ci/jenkins/test-rancher.sh, ci/jenkins/test.sh, ci/run-k8s-e2e-tests.sh, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh, docs/gke-installation.md
* Disable auto-upgrade when creating the cluster
* Remove old sed command which is no longer relevant
* Fix Kubeconfig retrieval
* Fix retry mechanism for cluster deletion
* Remove SERVICE_CIDR (no longer needed with AntreaProxy)
In addition we do the following:
* Replace --kube-conformance-image-version (deprecated) with
--kubernetes-version for Sonobuoy (in all conformance test scripts)
* Remove --kube-conformance-image parameter as it is unused and
deprecated for Sonobuoy
* Bring Antrea GKE installation doc up-to-date
=> Several fixes in ci/test-conformance-gke.sh

docs/multicast-guide.md
Document the limitation of a large number of receiver groups in one node for multicast.
=> Supplyment multicast document with a limitation
