antrea-io/antrea

- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
Currently the installServices method is somewhat long and redundant, making it hard to maintain and error-prone. In fact, a few bugs were found in the recent releases which are related to it more or less. While sorting out the code, I found there are actually more bugs in it:
1. After updating stickyMaxAgeSeconds, the flow for ClusterIP isn't updated because the installServiceFlows interface skip updating flows whose cache keys already exist.
2. After updating stickyMaxAgeSeconds, the flows for NodePort and LoadBalancerIPs aren't updated because the installServiceFlows interface is not even called.
3. After updating InternalTrafficPolicy, the flows for ClusterIP isn't updated.
4. After updating InternalTrafficPolicy for a ClusterIP Service, the stale group is not removed.
5. Endpoints are …
> Fix Service update processing

- go.mod
- go.sum
- pkg/ovs/openflow/ofctrl_bridge_test.go
Old ofnet versions do not have concurrency control over tableDb, groupDb and meterDb in OFSwitch, which will cause Antrea Agent to crash when calling ofSwitch.NewGroup concurrently.
Fixes #4847
> Bump up ofnet library to v0.6.10

- docs/multicast-guide.md
Cherry pick of #4850 on release-1.11.
#4850: Supplyment multicast document with a limitation
> Automated cherry pick of #4850: Supplyment multicast document with a limitation

- ci/jenkins/jobs/projects-cloud.yaml
- ci/test-conformance-gke.sh
This is causing the cloud-antrea-gke-cleanup Jenkins job to fail (even though the cluster is deleted properly), because for some reason "gcloud container clusters delete" tries to create the Kubeconfig file (and the directory does not exist):
```
ERROR: (gcloud.container.clusters.delete) Unable to create private file [/home/ubuntu/jenkins/out/gke/kubeconfig]: [Errno 1] Operation not permitted: '/home/ubuntu/jenkins/out/gke/kubeconfig'
```
This issue was introduced in #4862. It was not caught during testing because the cleanup job, which is triggered by the main conformance job, was not triggered using the correct parameters. Current build parameters (ANTREA_REPO and ANTREA_GIT_REVISION) need to be propagated to the cleanup job to enable proper testing before merges. We update the cloud …
> Stop exporting KUBECONFIG in ci/test-conformance-gke.sh

- test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2
The feature gate was GA'ed in K8s v1.25, and removed in K8s v1.27
> [Vagrant infra] Remove NetworkPolicyEndPort feature gate for apiserver

- go.mod
- go.sum
- pkg/ovs/openflow/ofctrl_bridge_test.go
Cherry pick of #4870 on release-1.10.
#4870: Bump up ofnet library to v0.6.10
> Automated cherry pick of #4870: Bump up ofnet library to v0.6.10

- ci/jenkins/test.sh
- ci/run-k8s-e2e-tests.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
- docs/gke-installation.md
Cherry pick of #4862 on release-1.10.
#4862: Several fixes in ci/test-conformance-gke.sh
> Automated cherry pick of #4862: Several fixes in ci/test-conformance-gke.sh

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- Makefile
- ci/jenkins/test-mc.sh
- docs/multicluster/user-guide.md
- multicluster/build/images/Dockerfile
1. Add a new build image target in Makefile to support local multi-cluster image build.
2. Rename targets to align with other target name format.
> Support local multi-cluster image build

- ci/jenkins/test.sh
Cherry pick of #4740 on release-1.10.
#4740: Clean up agent images before building linux images on
> Automated cherry pick of #4740: Clean up agent images before building linux images on

- docs/multicluster/user-guide.md
Update Multi-cluster user guide to provide more details for Gateway enablement.
> Update Multi-cluster user guide

- ci/jenkins/test-mc.sh
- ci/jenkins/test-vm.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
Reduce time limit for docker system prune to 12 hours in Windows testbed for improved resource cleaning efficiency.
Add detailed information statistics for all Docker resource objects across all testbeds.
> Update Docker cleanup command and add resource usage information

- .github/workflows/trivy_scan.yml
The existing logic was not ordering semantic versions correctly: it was treating v1.11.0-alpha.0 as greater than v1.11.0.
Instead we use the Github API, which will return the latest version, and always exclude all "prerelease" versions.
> Get the correct Antrea version in trivy_scan.yml workflow

- docs/prometheus-integration.md
- pkg/agent/metrics/prometheus.go
- pkg/ovs/openflow/ofctrl_bridge.go
- test/integration/agent/openflow_test.go
Issue: https://github.com/antrea-io/antrea/issues/4566
Add the OVS table name as a label for the `antrea_agent_ovs_flow_count` metric to facilitate identifying the corresponding table for each metric.
> Add OVS table name as label for ovs_flow_count Prometheus metrics

- ci/jenkins/jobs/projects-cloud.yaml
The result is saved in the root directory of the workspace.
> Fix the wrong path of sonobuoy result artifact

- pkg/monitor/controller.go
- pkg/monitor/controller_test.go
Antrea Controller checks the existence of AntreaAgentInfo API before creating or deleting the resources for worker Node or ExternalNode.
> Check the existence of CRD AntreaAgentInfo before operating on it

- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
This is a separate patch which backports only necessary changes in PR #4845 to release-1.10 to fix Service update processing as the original patch has too many dependencies on code not in this release. It fixes the following cases:
1. After updating stickyMaxAgeSeconds, the flow for ClusterIP isn't updated because the installServiceFlows interface skip updating flows whose cache keys already exist.
2. After updating stickyMaxAgeSeconds, the flows for NodePort and LoadBalancerIPs aren't updated because the installServiceFlows interface is not even called.
3. After updating InternalTrafficPolicy, the flows for ClusterIP isn't updated.
> Manual cherry pick of #4845: Fix Service update processing

- multicluster/controllers/multicluster/leader/resourceexport_controller.go
- multicluster/controllers/multicluster/member/serviceexport_controller.go
- multicluster/controllers/multicluster/member/serviceexport_controller_test.go
- multicluster/test/integration/serviceexport_controller_test.go
ExternalName type of Service shouldn't be exported since it has no ClusterIP assinged, and it's not supported by KEP1645 either. So add a few validation codes to disable ExternalName type of Service exporting.
> Disable ExternalName type of Service exporting

- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
This patch is to resolve a concurrency issue in Multicast feature with encap mode.
The root cause is the existing code doesn't create a new object for field "remoteMembers" before updating it into cache.
Fixed: #4904
> [Multicast] Clone remoteMembers when creating an updated GroupMemberStatus 

- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
Cherry pick of #4903 on release-1.11.
#4903: Clone remoteMembers when updating a
> Automated cherry pick of #4903: Clone remoteMembers when updating a

- pkg/antctl/raw/multicluster/deploy/deploy_helper.go
- pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
- pkg/antctl/raw/multicluster/deploy/leader_cluster_test.go
- pkg/antctl/raw/multicluster/deploy/member_cluster_test.go
1. Refine unit test of multicluster antctl helper to remove unnecessary dependency
2. Add more unit tests for antctl/raw/multicluster/deploy package
Resolves #4689
> Refine Multi-cluster unit tests to remove unnecessary dependency

- pkg/flowaggregator/flowaggregator_test.go
There was a race condition caused by assigning mock exporter expectations while running exporter.
Fixes #4913.
> Fix race condition in TestFlowAggregator_Run

- test/e2e/antreapolicy_test.go
- test/e2e/k8s_util.go
The NetworkPolicy e2e tests have been failing randomly for some time. However, it was really hard to get useful information from the "reachability" comparison. This patch logs the probe command's detailed output when the result doesn't match expectation.
> Log command output when the probe result doesn't match expectation

- .github/workflows/netpol_cyclonus.yml
- .github/workflows/verify_docs.yml
- .github/workflows/website.yml
There is little point in running scheduled workflows on forks. It can generate unhelpful notifications and it wastes compute resources.
The workflow that updates the antrea.io website automatically should also be disabled for forks.
> Disable some workflows on forks

- pkg/apis/crd/v1alpha1/types.go
- pkg/controller/networkpolicy/status_controller.go
- pkg/controller/networkpolicy/status_controller_test.go
Modify the ANP status phase as "Failed" when all Agents have reported the status and at least one failure is received.
> Introduce "Failed" phase in ANP status

- cmd/antrea-agent/agent.go
If kube-proxy is not running, AntreaProxy is responsible for proxying the access to Services. For components that rely on Services, they should run after AntreaProxy is ready.
Accessing Service IPs before they are proxied leads to weird behaviors on Windows platform.
> Run modules that rely on Services after AntreaProxy is ready

- build/images/base/Dockerfile
To avoid a known issue with Suricata 6.0.11.
The main Ubuntu PPA ships Suircata 6.0.4.
With this change, e2e tests for L7NetworkPolicy will stop failing.
We do not "fix" the UBI build at the moment, but it will be taken care of before the Antrea v1.12 release.
For #4921
> Temporarily install Suricata from Ubuntu PPA instead of OISF PPA

- hack/windows/Install-OVS.ps1
- test/e2e/nodeportlocal_test.go
Upgrade windows ovs to 2.16.7 on both script and CI testbeds.
Fixes #4702
> Update windows ovs download link to ovs 2.16.7

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
- ci/kind/kind-setup.sh
part of: #4460
There could be chance that Job is aborted then the kind cluster becomes garbage.
The kind test job should delete existing kind clusters before creating a new cluster.
Note:
we have set 135 minutes timeout for both conformance and NetworkPolicy tests in the jobs because sometime NetworkPolicy takes more time to finish its executions( It depends on how many test cases are running and the time of each test cases ) although we can choose 120m also, but just to be on the safe side we have set 135m just like other ci jobs in project-lab.yaml, for example "rancher-networkpolicy".
so in case if tests gets stuck during their execution then it will wait for 135m and run will aborted automatically, and in aborted cases clusters …
> Cleanup Leftover Kind Cluster in Kind Testbed

- pkg/agent/controller/networkpolicy/fqdn.go
- test/e2e/antreapolicy_test.go
Cherry pick of #4934 on release-1.10.
#4934: Fix FQDN upper-case issue
> Automated cherry pick of #4934: Fix FQDN upper-case issue

- ci/jenkins/README.md
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
- ci/jenkins/test.sh
Windows containerd jobs are supported since Antrea 1.10. This solution adds description to the Jenkins job description for these jobs.
Fixes #4806
> Add Containerd to Windows Jenkins Jobs

- hack/windows/Clean-AntreaNetwork.ps1
The existing script would reset ovs-vswitchd when stuck in "starting" status. In some corner cases, ovsdb-server/ovs-ovswitchd services may be removed unexpectedly.
This change includes,
1. add improvement to recover ovsdb-server/ovs-vswitched service if if they do not exist when running the cleanup script.
2. remove vNICs using Windows VMSwitch API rather than calling ovs-vsctl commands, this can remove the dependency on the running OVS userspace process (ovs-vswitchd).
Fix: #4721
> [Windows] Improvement in cleanup script

- hack/.md_links_config.json
The check for https://twitter.com/ProjectAntrea has been failing, presumably because of some DDos mitigation service.
> Whitelist twitter.com links in Markdown link checker config

- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/fields.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/testing/mock_openflow.go
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/agent/route/interfaces.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/route/route_windows.go
- pkg/agent/route/route_windows_test.go
- pkg/agent/route/testing/mock_route.go
- pkg/ovs/openflow/testing/utils.go
- test/integration/agent/openflow_test.go
- third_party/proxy/types.go
This PR adds the ability to serve ExternalIP for AntreaProxy, allowing for
external client accesses to Services running in Kubernetes. In Kubernetes, an
ExternalIP is a feature that allows a Service to be accessed from outside the
cluster using a static IP address.
> Add support for ExternalIP in AntreaProxy

- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
Currently Flow Aggregator looks up Pods by IP address to fetch labels, it is very possible to obtain incorrect Pods when Pod turnover quickly.
In this commit, we change to looking up Pods by Pod Name and Namespace to fetch labels in Flow Aggregator.
> Look up Pods by name to fetch labels in Flow Aggregator

- pkg/antctl/raw/proxy/command.go
- pkg/antctl/raw/proxy/command_test.go
Adds unit test for pkg/antctl/raw/proxy/command.go
for #4142
> Adds unit test for pkg/antctl/raw/proxy/command.go

- multicluster/test/e2e/framework.go
- multicluster/test/e2e/service_test.go
- test/e2e/framework.go
The test didn't check if the test has been deleted entirely before proceeding, causing random failures.
The commit improves the test in the following ways:
1. Update the backend Pod's label to scale down and up the number of Endpoints to fix the above issue and speed up the test.
2. Check if desired state is reached with a periodical check instead of always waiting for a mount of time.
3. Ensure the change made by the test is reverted via a deferred call.
> Fix Multicluster e2e test ScaleDownMCServiceEndpoints

- build/images/base/Dockerfile
- build/images/base/Dockerfile.ubi
- test/e2e-secondary-network/infra/prepare_cluster.sh
- test/e2e-secondary-network/infra/prepare_sriov.sh
Bump up whereabouts to v0.6.1 to fix CVEs.
> Bump up whereabouts to v0.6.1

- ci/jenkins/test-vm.sh
- ci/jenkins/test-vmc.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
The command returns error code when the operation is already running. Like we don't fail a build when pruning images fails, there is no point to fail a build when showing docker disk usage fails.
> Do not fail a build if showing docker disk usage fails

- pkg/agent/proxy/proxier.go
CONTROLLER cannot be used as the in_port due to a bug in Windows ovsext driver, otherwise the Windows OS would crash.
See https://github.com/openvswitch/ovs-issues/issues/280.
Fixes #4990
> Use LOCAL instead of CONTROLLER as the in_port of packet-out message

- pkg/agent/openflow/network_policy_test.go
Fix the golangci-lint issue:
SA1019: sets.String is deprecated: use generic Set instead
> Use the generic Set to fix golangci-lint issue

- ci/kind/test-e2e-kind.sh
- go.mod
- go.sum
- test/e2e/framework.go
go-ipfix v0.6.1 is a minor release with only setting a flow-aggregator log message with higher verbosity value. The logs themselves are harmless and showing up frequently. Logging them with the lowest verbosity value can be misleading. This has been noticed for a while, and has been brought up recently by users.
> Upgrade to go-ipfix v0.6.1

- hack/windows/Clean-AntreaNetwork.ps1
"LOG" function is not defined in script Clean-AntreaNetwork.ps1, an invalid call may cause unexpected failure.
> [Windows] Remove invalid call in cleanup script

- pkg/agent/servicecidr/discoverer.go
- pkg/agent/servicecidr/discoverer_test.go
In the case of a headless Service, where the ClusterIP is set to "None", and the ClusterIP should not be used to update the current Service CIDR.
> Prevent headless Service from updating Service CIDR

- build/charts/antrea/crds/clustergroup.yaml
- build/charts/antrea/templates/controller/apiservices.yaml
- build/charts/antrea/templates/controller/clusterrole.yaml
- build/charts/antrea/templates/webhooks/mutating/crdmutator.yaml
- build/charts/antrea/templates/webhooks/mutating/labelsmutator.yaml
- build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
- multicluster/build/yamls/antrea-multicluster-member.yml
- multicluster/cmd/multicluster-controller/controller.go
- multicluster/cmd/multicluster-controller/controller_test.go
- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/leader_test.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/cmd/multicluster-controller/member_test.go
- multicluster/config/overlays/leader-ns/webhook_patch.yaml
- multicluster/config/overlays/leader-ns/webhook_rbac.yaml
- multicluster/config/overlays/member/additional_role_patch.yaml
- multicluster/config/overlays/member/webhook_patch.yaml
- multicluster/hack/generate-manifest.sh
- pkg/apiserver/apiserver.go
- pkg/apiserver/certificate/cacert_controller.go
- pkg/apiserver/certificate/cacert_controller_test.go
- pkg/apiserver/certificate/config.go
Antrea APIServices/Webhooks are not needed in some scenarios, e.g., Nephe
watches internal resources from Antrea Controller directly in agentless mode.
The existing code may report errors when updating CA bundle in these
non-existing reosurces.
This change tries to list the existing APIServices/Webhooks with label filters
first, and then to update Controller CA Bundle on them. Except for antrea's
general label "app: antrea", the below principle is used,
- For general case, antrea-controller updates CA bundle on the resources labeled
with "served-by: antrea-controller"
- For multi-cluster case, antrea-mc-controller updates CA bundle on these
resource:
- leader controller updates resources labeled with both "role: leader" and
"served-by: antrea-mc-controller"
- member controller updates …
> Update CA Bundle on the existing APIServices/Webhooks

- multicluster/test/e2e/fixtures.go
- multicluster/test/e2e/framework.go
- multicluster/test/e2e/main_test.go
- test/e2e/framework.go
- test/e2e/k8s_util.go
- test/e2e/nodeportlocal_test.go
- test/e2e/upgrade_test.go
Add E2E test for Multi-cluster WireGuard encryption scenario. After the original E2E test is finished, the TrafficEncryptionMode will be set to 'wireGuard' and run the test again.
> Add E2E test for Multi-cluster WireGuard encryption 

- cmd/antrea-agent/agent.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/servicecidr/discoverer.go
- pkg/agent/servicecidr/discoverer_test.go
- pkg/util/ip/ip.go
- pkg/util/ip/ip_test.go
The previous implementation always generated intermediate values for ServiceCIDR on agent start, which may interrupt the Service traffic and causes difficulty for cleaning up stale routes as the value calculated at one point may not be reliable to identify all stale routes.
This commit waits for the Service Informer to be synced first, and calculates the ServiceCIDR based on all Services. Ideally the Service route won't change in most cases, and hence avoid the above issues.
Besides, it fixes an issue that stale routes on Linux were not cleaned up correctly due to incorrect check.
> Avoid ServiceCIDR flapping on agent start

- pkg/controller/networkpolicy/validate_test.go
Adds unit test for pkg/controller/networkpolicy/validate.go
for #4142
Signed-off-by: Harshitha U R harshithaur1611@gmail.com
> Adds unit tests for pkg/controller/networkpolicy/validate.go

- pkg/agent/route/route_windows.go
- pkg/agent/util/powershell/powershell_windows.go
This PR fixes the following issues:
1. AntreaAgent logs "Failed to sync route" when attempting to sync route entries
every time.
2. AntreaAgent logs "Failed to install route for Service CIDR" err="failed to
delete stale Service CIDR route" during startup.
For the first issue, previously, to recover the connected route of antrea-gw0
(assuming the IP address is 10.10.0.1/24) that may have been deleted by mistake,
a route with a destination 10.10.0.1/24 and gateway 10.10.0.1 was periodically
synced. However, this caused an error because an existing active route with the
same destination but a different gateway 0.0.0.0 should have already been
automatically installed when antrea-gw0 was created. To address this issue, this
PR changes the gateway of the recover route from 10.10.0.1 to 0.0.0.0, …
> Improve AntreaProxy route syncing on Windows

- .github/workflows/kind.yml
- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/conf/antrea-controller.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- ci/jenkins/test.sh
- ci/kind/kind-setup.sh
- ci/kind/test-e2e-kind.sh
- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- docs/antrea-ipam.md
- docs/feature-gates.md
- docs/multicast-guide.md
- hack/generate-manifest.sh
- pkg/agent/apiserver/handlers/multicast/handler.go
- pkg/apiserver/handlers/featuregates/handler.go
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/config/agent/config.go
- pkg/features/antrea_features.go
- test/e2e/antreapolicy_test.go
- test/e2e/framework.go
- test/e2e/main_test.go
- test/e2e/multicast_test.go
This patch graduates the following features from Alpha to Beta.
* Multicast: it has been verified with scale tests and has been patched with a number of fixes in the development cycle of release-1.12.
* TopologyAwareHints: most of its logic references the kube-proxy implementation.
* NodeIPAM: most of its logic references the kube-controller-manager imlementation. Note that it still requires the config parameter `enableNodeIPAM` to be true to run NodeIPAM, to avoid conflicts with kube-controller-manager which runs NodeIPAM in most cases.
Besides, it makes necessary changes to make NodeIPAM and Multicast e2e tests run on some kind testbeds.
> Graduate features from Alpha to Beta

- hack/release/prepare-changelog.sh
Normally these PRs won't be included in change log so stop collecting them in the Unlabelled section to avoid efforts to filter them.
If a PR authored by bot account is labelled with "action/release-note", it will still be collected.
> Ignore PRs authored by bots

- build/images/base/Dockerfile
- build/images/base/Dockerfile.ubi
- test/e2e-secondary-network/infra/prepare_cluster.sh
- test/e2e-secondary-network/infra/prepare_sriov.sh
Cherry pick of #4988 on release-1.11.
#4988: Bump up whereabouts to v0.6.1
> Automated cherry pick of #4988: Bump up whereabouts to v0.6.1

- hack/generate-manifest.sh
```
if $MULTICAST_INTERFACES; then ...
```
will raise the error `./hack/generate-manifest.sh: line 270: ens224: command not found`
> Use -n to test if MULTICAST_INTERFACES is not empty

- ci/jenkins/test-vmc.sh
Cherry pick of #5035 on release-1.12.
#5035: Remove uninitialized taint to recover CAPV testbeds
> Automated cherry pick of #5035: Remove uninitialized taint to recover CAPV testbeds

- ci/jenkins/test-vm.sh
- test/e2e/fixtures.go
In vm e2e testbed, users cannot retrieve log tarball for a failed test. This pr fix such problem.
> Fix empty log for the failed tests in the VM e2e testbed

- build/images/ovs/Dockerfile.ubi
Cherry pick of #4991 on release-1.10.
#4991: Fix UBI image build error
> Automated cherry pick of #4991: Fix UBI image build error

- pkg/agent/servicecidr/discoverer.go
- pkg/agent/servicecidr/discoverer_test.go
Cherry pick of #5008 on release-1.11.
#5008: Prevent headless Service from updating Service CIDR
> Automated cherry pick of #5008: Prevent headless Service from updating Service CIDR

- ci/kind/validate-metrics-doc.sh
- hack/make-metrics-doc.sh
It appears that the script was never really working on macOS, unless the built-in fmt and sed utilities were replaced by their GNU "equivalent". Instead of making this assumption, we explicitly use gfmt and gsed when macOS is detected, and give an error if they have not been installed.
While in other scripts, we try to use expressions which are compatible with both flavors of sed (GNU and FreeBSD), this script is used so rarely that it doesn't seem worth the maintenance effort. In particular, there is no simple equivalent to the GNU sed expression to capitalize every word in a sentence.
Fixes #5012
> Fix hack/make-metrics-doc.sh on macOS

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- ci/kind/values-flow-exporter.yml
- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- docs/network-flow-visibility.md
- pkg/config/agent/config.go
Adding configuration toggle for flow exporter to prevent antrea agent from showing error in log, which happens when user enable flow exporter feature gate without installing flow aggregator.
Fixes [#4953](https://github.com/antrea-io/antrea/issues/4953)
Signed-off-by: Yun-Tang Hsu <hsuy@vmware.com>
> Add configuration toggle for FlowExporter

- test/e2e/proxy_test.go
In e2e tests like TestProxyHairpinIPv4:
- A test Service is created
- A test Pod for the Service is created
- Probe the Service using code `data.RunCommandFromPod(data.testNamespace, pod, container, []string{"wget", "-O", "-", url, "-T", "5"})`
When using the command wget -O url -T 5 to connect to a Service without an Endpoint, which is implemented by AntreaProxy, a rejection message will be received, and no retry will be attempted. There is a chance that even if the test Pod is ready, the Service may not be fully synced, resulting in a rejection message and a failed test. This PR fixes the flaky test by adding retry logic.
> Fix flaky e2e tests

- .github/workflows/kind.yml
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/conf/antrea-controller.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- cmd/antrea-controller/controller.go
- docs/antrea-ipam.md
- pkg/config/agent/config.go
- pkg/config/controller/config.go
- pkg/util/k8s/client.go
- pkg/util/k8s/client_test.go
To override the address of Kubernetes apiserver for antrea-controller, the option, kubeAPIServerOverride, is added to antrea-controller.conf. It's typically used when kube-proxy is not deployed (substituted by AntreaProxy) and kube-controller-manager does not run NodeIPAMController (substituted by Antrea NodeIPAM).
Fixes #5022
> Add kubeAPIServerOverride option to antrea-controller

- .github/workflows/trivy_scan.yml
- .github/workflows/trivy_scan_before_release.yml
Reverts antrea-io/antrea#5085
Because of this bug: https://github.com/aquasecurity/trivy-action/issues/238
> Revert "Bump aquasecurity/trivy-action from 0.10.0 to 0.11.0"

- .github/dependabot.yml
We stop auto-upgrade from Dependabot on the package as it will involve dependency conflicts. We should upgrade the package manually when needed.
> Stop checking upgrades for clickhouse-go/v2

- pkg/support/dump_others_test.go
- pkg/support/dump_test.go
- pkg/support/dump_windows_test.go
Adds the unit test for support pkg
for #4142 
Signed-off-by: Harshitha U R <harshithaur1611@gmail.com>
> Adds the unit test for pkg/support

- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/audit_logging_test.go
Instead of calling fmt.Sprintf with a large number of format arguments, we use strings.Join.
In addition to being 4X faster, I believe it is also more readable, especially as we add new fields to log.
> Improve audit logging performance

- .github/dependabot.yml
Any version later than clickhouse-go/v2 v2.6.1 requires go.opentelemetry.io/otel v1.13.0, which conflicts with the K8s api dependencies on go.opentelemetry.io/otel. We shall wait until we upgrade Go version and K8s api version, then we may be able to upgrade clickhouse-go/v2.
> Stop picking up patch from clickhouse-go/v2

- pkg/agent/controller/networkpolicy/cache.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- test/e2e/antreapolicy_test.go
When no-op changes are applied to Antrea-native policies, such as adding or removing a non-existing group, there will be no datapath change but the generation has changed. The agent must report it has realized the latest generation even if it does nothing, otherwise the policy would stay realizing.
Fixes #5097
> Fix status report when no-op changes are applied to Antrea-native policies

- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/audit_logging_test.go
Instead of custom Clock interface
> Use k8s.io/utils/clock for audit logging

- pkg/agent/openflow/network_policy.go
- pkg/agent/openflow/network_policy_test.go
This change is to resolve an issue in ANP with FQDN rules which has sent all TCP packets marked with ack and psh flags to antrea-agent rather than only sent the DNS response packets.
The root cause is the existing code would add a match pair with tp_dst=0 into the service match pairs even if no dst port is set in the ANP prtocols. Then the DNS logic has picked a wrong service match pair to generate the OpenFlow entries.
This change directly generates the conjunctive match conditions for DNS response packets rather than calling `getServiceMatchPairs` to make the logic simply.
> Bugfix: TCP src port is unset on the TCP DNS response flow

- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/audit_logging_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/network_policy.go
- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/testing/mock_openflow.go
- test/e2e/antreaipam_anp_test.go
- test/e2e/antreapolicy_test.go
- test/e2e/k8s_util.go
- test/e2e/util.go
We include 2 new fields in the audit logs:
* the "direction" of the NP rule (`Ingress` or `Egress`)
* the reference of the Pod to which the NP rule is applied (as
`<namespace>/<name>`).
These new fields are *NOT* added to the end of the logs, which could
break existing consumers.
We also refactor the e2e tests for AuditLogging to improve correctness
and readbility. Some logs were not validated properly because of an
early "break" statement, and some log fields (e.g., logLabel) were not
validated.
Fixes #3794
> Add appliedTo Pod namespace / name to audit logs

- go.mod
- go.sum
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/multicast.go
- pkg/agent/openflow/pipeline.go
- pkg/ovs/openflow/interfaces.go
- pkg/ovs/openflow/ofctrl_bridge.go
- pkg/ovs/openflow/ofctrl_bridge_test.go
- pkg/ovs/openflow/ofctrl_group.go
- pkg/ovs/openflow/ofctrl_meter.go
- pkg/ovs/openflow/testing/mock_openflow.go
- test/integration/ovs/ofctrl_test.go
The existing code call APIs in ofnet to create Table/Group/Meter on OpenFlow Switch. Since antrea agent also maintains these resources in its memory, the usage of ofctrl.tableDb/groupDb/meterDb is duplicated.
This change only creates the Table/Group/Meter resources using ofnet APIs but do not save them in a second map.
> Use new API in ofnet to remove the unnecessary map in memory

- test/e2e/flowaggregator_test.go
Remove the special case for Kind cluster in Flow Aggregator e2e test because we no longer use userspace OVS when running Antrea on Kind.
> Remove special case for Kind in Flow Aggregator e2e test

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
This job utilizes the rdiff-backup tool to periodically back up all
configuration files of the Jenkins control node.
> Add Jenkins backup job on CI pipeline

- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
In the openflow client, the `modifyFlows` function incorrectly flipped the `add` and `mod` type of `FlowMod` messages that it passes to the lower level `BundleOps` operation. This could lead to unexpected openflow state for the caller.
> Fix incorrect FlowMod message passing in openflow client modifyFlows

- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- pkg/agent/controller/serviceexternalip/controller.go
- pkg/agent/controller/serviceexternalip/controller_test.go
- pkg/agent/ipassigner/ip_assigner.go
- pkg/agent/ipassigner/ip_assigner_linux.go
- pkg/agent/ipassigner/responder/arp_responder.go
- pkg/agent/ipassigner/responder/arp_responder_test.go
- pkg/agent/ipassigner/responder/ndp_responder.go
- pkg/agent/ipassigner/responder/ndp_responder_test.go
- pkg/agent/ipassigner/testing/mock_ipassigner.go
- test/e2e/egress_test.go
- test/e2e/framework.go
- test/e2e/multicast_test.go
- test/integration/agent/ip_assigner_linux_test.go
This patch fixes two cases, in which an Egress IP is not advertised:
- When userspace ARP responder is not running (arp_ignore is 0), assigning a new Egress IP to a Node would not advertise the IP.
- When an Egress IP is obtained by multiple Nodes in some situations, e.g. split brain, the eventual winner would not advertise the IP after they are back to normal, because the IP is already assigned to the Node.
The patch moves IP advertising out of responders. Responders will only be responsible for answering neighbor queries. The IP assigner will advertise an IP when the IP is newly assigned to the Node, or the IP's Node recorded in Egress API is updated from another Node to this Node.
Fixes #5117
> Fix Egress IP not advertised in some cases 

- multicluster/cmd/multicluster-controller/clusterclaim_webhook.go
- multicluster/cmd/multicluster-controller/clusterclaim_webhook_test.go
Cherry pick of #5075 on release-1.12.
#5075: Fix ClusterClaim deletion webhook bug
> Automated cherry pick of #5075: Fix ClusterClaim deletion webhook bug

- cmd/antrea-controller/main.go
- cmd/antrea-controller/options.go
- cmd/antrea-controller/options_test.go
Add unit test for cmd/antrea-controller and improve validateNodeIPAMControllerOptions
> Add unit test for cmd

- go.mod
- go.sum
This is to resolve an issue in packetIn2 which may lead to incorrect field values in PackintIn2.Userdata and PacketIn2.Metadata. The issue is because the existing code uses a pointer reference to set byte slice fields when unmarshaling the mesages, and libOpenlow reuses the buffer to process the next messages.
Fix: #5062
> Bump up libOpenflow and ofnet versions

- test/e2e/framework.go
This change adds additional wait for ClickHouse Service in FA e2e test to avoid premature test failures due to service not found.
Fixes #5146
> Fix ClickHouse service not found in FA e2e test

- go.mod
- go.sum
This is to resolve an issue when unmarshaling IP packet which may lead to incorrect field values in PacketIn meesages. The issue is because the existing code uses a pointer reference to set byte slice fields when unmarshaling the mesages, and libOpenlow reuses the buffer to process the next messages.
> Bugfix: Bump up libOpenflow version

- test/e2e/fixtures.go
- test/e2e/networkpolicy_test.go
One subtest of TestNetworkPolicy restarts antrea-controller, which causes its log missing when subtests running before it fail. To preserve component logs, we export logs for every subtest if it fails.
For https://github.com/antrea-io/antrea/actions/runs/5295909048/jobs/9586763929
> [e2e] Export logs for TestNetworkPolicy subtests

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea-windows.yml
- build/yamls/antrea.yml
- build/yamls/windows/base/conf/antrea-agent.conf
- cmd/antrea-agent/agent.go
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/agent/proxy/service.go
- pkg/config/agent/config.go
- third_party/proxy/service.go
- third_party/proxy/util/utils.go
The service.kubernetes.io/service-proxy-name label was initially intended to offload
the kube-proxy from handling all Services already handled by a service mesh.
AntreaProxy should honor the service.kubernetes.io/service-proxy-name label, which
means that if the label is defined in a Service, AntreaProxy must not handle the
Service. Refer to this link https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2447-Make-kube-proxy-service-abstraction-optional
for more information.
> Support service.kubernetes.io/service-proxy-name label in AntreaProxy

- pkg/antctl/raw/multicluster/common/common.go
Fix a deletion error during rollback after an `antctl mc` command failed.
```
Failed to delete  kube-system/test-clusterset: Object 'Kind' is missing in
'unstructured object has no kind'
```
apiVersion and kind are required fields in unstructured object to do deletion,
but `DefaultUnstructuredConverter.ToUnstructured` will not convert them
automatically.
> Add apiVersion and kind for unstructured objects in "antctl mc" code

- .github/workflows/kind.yml
- .github/workflows/netpol_cyclonus.yml
- multicluster/hack/verify-tools.sh
Upgrade Kind from v0.18.0 (K8s v1.26.3) to v0.20.0 (K8s v1.27.3)
Since all CI testbeds upgrades from old versions to K8s 1.27+ are in progress, it's better to upgrade Kind to latest v0.20.0
which will also use K8s v1.27.3 as default node image.
> Upgrade Kind to v0.20.0

- ci/jenkins/test.sh
When the testbed is deployed in jumper mode, if the testbed is an IPv6 testbed, the "scp" command will fail since both "scp" command and IPv6 address use the colon as a separator. So we need to add square brackets around the IP address when using jumper mode.
> Add square brackets for IP address when using jumper mode

- cmd/antrea-agent/agent.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/agent/controller/networkpolicy/reconciler_test.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/openflow/groups.go
- pkg/agent/proxy/proxier_test.go
OpenFlow Group IDs are Node global resources. Not only IPv4 and IPv6 specific OpenFlow rules could use Groups, but also IP family independent rules could use it. Diving the whole ID pool into two pools makes such use cases have to choose either IPv4 or IPv6 ID pool, which looks weird. Besides, there seems no good reason why two ID allocators should be created to manage the same pool.
> Use an unique ID allocator for OpenFlow groups

- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/audit_logging_test.go
- pkg/apiserver/registry/system/supportbundle/rest.go
- pkg/apiserver/registry/system/supportbundle/rest_test.go
No reason to use a pointer here. RealClock is an empty object, and all its methods have a value receiver.
I tried to benchmark the change, and while there is a minor improvement, it is really insignificant.
> Replace &clock.RealClock{} with clock.RealClock{}

- build/images/Dockerfile.build.coverage
The e2e tests copy the antctl binaries from the Docker image to the host node, and if the binaries are built with CGO enabled then they are not portable, and generate errors when they are used on different OS. That's the reason we are disabling CGO while creating binaries.
> Disable CGO when building antctl binaries for e2e tests

- pkg/agent/proxy/endpointslicecache.go
- pkg/agent/proxy/proxier_test.go
The condition which checks whether IP family matches or not was wrong. For IPv4 proxier, IPv6 endpoints were not ignored.
Release Note:
```
Fix IPv4 groups containing IPv6 endpoints mistakenly in dual-stack clusters in AntreaProxy implementation.
```
Fixes #5193
> Fix IPv4 group containing IPv6 endpoints in dual-stack cluster

- docs/antrea-ipam.md
- docs/antrea-proxy.md
- docs/egress.md
- docs/external-node.md
- docs/multicluster/policy-only-mode.md
- docs/multicluster/quick-start.md
- docs/multicluster/user-guide.md
- docs/node-port-local.md
- docs/noencap-hybrid-modes.md
- docs/service-loadbalancer.md
- docs/traffic-encryption.md
1. Remove "..." from yaml examples, otherwise [the examples are displayed in a weird way in website](https://antrea.io/docs/v1.12.0/docs/service-loadbalancer/#enable-service-external-ip-management-feature).
2. Remove leading "$" from bash examples which contain only commands, to make the example to be copied and executed easier.
3. Insert a space between "$" and command for bash examples which contain both commands and outputs, to avoid ambiguity of dollar sign.
4. Remove the random suffix of Antrea ConfigMap name which is no longer used.
5. Fix a few wrong examples.
> Fix code examples in docs

- pkg/agent/proxy/endpointslicecache.go
- pkg/agent/proxy/proxier_test.go
Cherry pick of #5194 on release-1.12.
#5194: Fix IPv4 group containing IPv6 endpoints in dual-stack
> Automated cherry pick of #5194: Fix IPv4 group containing IPv6 endpoints in dual-stack

- build/yamls/antrea-windows-containerd.yml
- build/yamls/antrea-windows.yml
- build/yamls/windows/base/conf/antrea-agent.conf
- ci/jenkins/test.sh
- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_linux.go
- cmd/antrea-agent/options_windows.go
- pkg/agent/nodeportlocal/k8s/npl_controller.go
- test/e2e/nodeportlocal_test.go
There were a few issues contributing to NPL tests' flake:
* testNPLAddPod failed because Windows default port range for random source
port overlaps with the port range used for NPL testing.
* testNPLChangePortRangeAgentRestart failed because it takes more than 3
seconds to execute powershell command on the testbed for each rules.
After agent restarting, when the annotation is read before it is updated,
test fails due to incorrect mapping between netnat and annotation.
* Test may fail randomly during image pulling, which occurs when the Windows
node has low disk space and randomly clean available images. This results in
a re-pull of large images when creating new pods during e2e test, causing
timeout failures
This commit fixes them via the following changes:
* Update e2e and windows NPL …
> Change default port range for NodePortLocal on Windows and improve NPL e2e tests

- ci/run-k8s-e2e-tests.sh
- ci/verify-sonobuoy.sh
The default K8s registry is changed to `registry.k8s.io`, the related change is introduced since sonobuoy v0.56.8, upgrade its version to the latest release v0.56.16 to avoid image pull failure.
> Update sonobuoy version to v0.56.16

- docs/antctl.md
- go.mod
- go.sum
- pkg/antctl/antctl.go
- pkg/antctl/command_definition.go
- pkg/antctl/transform/addressgroup/transform.go
- pkg/antctl/transform/addressgroup/transform_test.go
- pkg/antctl/transform/appliedtogroup/transform.go
- pkg/antctl/transform/appliedtogroup/transform_test.go
- pkg/antctl/transform/networkpolicy/transform.go
- pkg/antctl/transform/networkpolicy/transform_test.go
Fixes #1605.
Added sort by flag for networkpolicy, addressgroup, and appliedtogroup resource.
> Add sort-by flag in more antctl resources for more fields

- pkg/agent/externalnode/external_node_controller.go
- pkg/agent/externalnode/external_node_controller_linux_test.go
The issue is seen on a RHEL 8.4 VM on azure cloud, which is configured with dhclient to manage the network interface. The root cause is antrea-agent fails to recover the IP/Routes from host internal interface to uplink after ExternalNode is deleted, because the added IP/Routes is deleted or conflicted with dhclient configuration. Then in the continuous retry with ExternalNode deletion, antrea-agent is blocking at the precheck on the existentance of host internal interface always returns true as the uplink's name is already recovered.
Fix: #5111
> [VM Agent] Bugfix: antrea-agent failed to delete ExternalNode

- multicluster/cmd/multicluster-controller/controller.go
- multicluster/controllers/multicluster/common/types.go
- multicluster/controllers/multicluster/commonarea/remote_common_area.go
- multicluster/controllers/multicluster/leader/labelidentity_export_controller.go
- multicluster/controllers/multicluster/member/labelidentity_controller.go
- multicluster/controllers/multicluster/member/labelidentity_import_controller.go
After performance tests, we noticed that default QPS and Burst introduce a bad performance when a lot of LabelIdentity events concurrently occur. So this commit changes to use a higher QPS and Burst config for MultiCluster ResourceExchange pipeline and increases the worker numbers of LabelIdentity related controllers.
**Performance Test results:**
_**No LabelID sync test**_
This case is that when users create an MCNP, all the resources including all appliedTo and peers workloads are already created for a while, which means that all the LabelIdentities needed have been synced and stored in the caches of antrea-controllers and antrea-agents. So in this case, the performance of creating MCNP should have a similar result as creating a single cluster NetworkPolicy, like ACNP.
**_With LabelID …
> Change Multi-cluster Controller ResEx QPS and LabelID worker num

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-cloud.yaml
Add` Multi-cluster E2E Jenkins job on clouds, so that developers can trigger the E2E job and get the console output of the jenkins job.
> Add Multi-cluster E2E Jenkins job on cloud

- build/images/Dockerfile.build.ubi
- build/images/Dockerfile.build.ubuntu
Disable CGO to avoid GLIBC dependency in antctl for cross-platform compatibility. This also reduces the size of the antrea ubuntu image from 564MB to 540MB.
> Disable CGO for antctl binary

- third_party/proxy/service.go
- third_party/proxy/types.go
New service.kubernetes.io/topology-mode annotation has been introduced as a replacement for the service.kubernetes.io/topology-aware-hints annotation. The service.kubernetes.io/topology-aware-hints annotation has been deprecated in K8s 1.27.
This change let AntreaProxy consume both annotations to support topology aware routing.
Fixes: #5122
> Consume Topology Mode Annotation for AntreaProxy

- ci/jenkins/test-vm.sh
Fix VM e2e script to import updated image
Organize the VM e2e setup script to follow the steps: compile,
import the image to containerd and apply the Antrea YAML.
Fixes #5258
> Fix externalnode e2e script

- docs/multicluster/upgrade.md
- docs/multicluster/user-guide.md
- multicluster/cmd/multicluster-controller/controller.go
- multicluster/cmd/multicluster-controller/controller_test.go
- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/cmd/multicluster-controller/options.go
- multicluster/controllers/multicluster/common/controller_utils.go
- multicluster/controllers/multicluster/common/controller_utils_test.go
- multicluster/controllers/multicluster/leader/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/gateway_controller_test.go
- multicluster/controllers/multicluster/member/labelidentity_controller_test.go
- multicluster/controllers/multicluster/member/resourceimport_controller_test.go
- multicluster/controllers/multicluster/member/serviceexport_controller_test.go
- multicluster/controllers/multicluster/stale_controller_test.go
- multicluster/test/integration/suite_test.go
Refine ClusterSet controller to watch ClusterClaims to handle the ClusterSet upgrade from v1alpha1 to v1alpha2. When the ClusterID is not in ClusterSet spec, controller will try to get ClusterID from ClusterClaims.
> Enhance ClusterSet controller to support ClusterSet version upgrade

- ci/kind/test-e2e-kind.sh
Before this patch, the testbed clean-up is never executed because of a mistake in the "quit" function. This patch fixed this bug.
This is because in Shell, `a=false` is nothing special but assign a "false" string to variable `a`. A non-empty string is true, so `[[ $setup_only || $test_only ]]` is **always true**.
> Fix a bug in test-e2e-kind.sh

- ci/jenkins/test.sh
The script loaded antrea-ubuntu image for other Nodes but not the Node that built the image.
> Windows containerd e2e should load antrea-ubuntu image for containerd

- build/charts/antrea/crds/clustergroup.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/api.md
This reverts commit 4f6e9aaaba6b6e9d6b0ca8709b13eccca87a6891.
According to the discussion here https://github.com/antrea-io/antrea/pull/5181#discussion_r1263031468 . We would remove v1alpha2 at the same time as all the other APIs we are promoting for Antrea v2.0, once we publish the CLI tool to update old API resources stored in etcd.
> Revert "Stop serving v1alpha2 version of the ClusterGroup CRD (#4812)"

- test/e2e/fixtures.go
- test/e2e/framework.go
- test/e2e/main_test.go
When developing something, it should be common that Antrea is already deployed and we just want to validate it with e2e tests. For example, I usually deploy Antrea using helm which is easier to set the configurations. But running e2e always deployed Antrea and required the manifest yaml to be present in the home directory of control plane node, which adds some burden to running e2e tests.
This commit adds a flag "--deploy-antrea" to support skipping deploying Antrea. It defaults to true to keep the same behavior as before. When we just want to run e2e tests and not to redeploy Antrea. We can set "--deploy-antrea=false".
> [e2e] Support skipping deploying Antrea

- docs/antrea-proxy.md
- docs/feature-gates.md
For https://github.com/antrea-io/antrea/issues/5025
> Document LoadBalancerMode related feature gate and configuration

- .github/workflows/kind.yml
flow-visibility e2e test is recently failed because the error: ”No space left on device“.
Release more space as a workaround before running the flow-visibility e2e test.
resolve https://github.com/antrea-io/antrea/issues/5268
> free more space before running the flow-visibility e2e test

- build/charts/antrea/crds/clustergroup.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/api.md
Cherry pick of #5277 on release-1.12.
#5277: Re-serve v1alpha2 ClusterGroup
> Automated cherry pick of #5277: Re-serve v1alpha2 ClusterGroup

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/feature-gates.md
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/agent/route/interfaces.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_windows.go
- pkg/agent/route/testing/mock_route.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
- pkg/features/antrea_features.go
Previously, when a client accessed a UDP Service through AntreaProxy, if the
selected backend Pod was deleted and no new available backend Pod was automatically
selected by AntreaProxy, the connection would always remain unavailable. This issue
occurred because a conntrack entry was generated through OVS ct action in AntreaProxy
when handling the first packet of the UDP connection. Even if the selected Endpoint
was removed, the conntrack entry's timeout would be flushed upon receiving a packet
from the client in AntreaProxy OVS pipeline. Consequently, the stale conntrack entry
would persist as long as the client continued sending packets to the UDP service,
causing AntreaProxy's OVS pipeline to direct the packets to the IP of the removed
backend Pod.
This PR addresses the issue by …
> Remove the associated stale conntrack entries when UDP Endpoints are removed

- pkg/ovs/openflow/ofctrl_bridge_test.go
Currently the number of goroutines created in TestConcurrentCreateGroups is too large that sometimes the limit of 8192 goroutines of the race detector on Windows is exceeded. Reducing the number of goroutines may relieve the problem.
Fixes #5261.
> Reduce number of goroutines in TestConcurrentCreateGroups

- ci/kind/test-e2e-kind.sh
The images should not be pulled, as we want to use the ones we have built locally. The reason why this has not been an issue so far for CI is that all jobs us the "coverage" images, which are not available in the Docker registry (but the logs show error messages because of the failed docker pull commands).
> Stop pulling Antrea images in ci/kind/test-e2e-kind.sh

- ci/test-conformance-gke.sh
- docs/gke-installation.md
The job was only deleting Pods in the kube-system Namespace after installing Antrea. However, GKE has been introducing new Namespaces (e.g., gmp-system), which are also running non-hostNetwork Pods. If we do not delete ALL non-hostNetwork Pods in ALL Namespaces after installing Antrea, it can lead to IP address reuse, and a broken GKE cluster.
> Fix GKE conformance job

- .github/workflows/kind.yml
Cherry pick of #5287 on release-1.11.
#5287: free more space before running flow-visibility e2e test
> Automated cherry pick of #5287: free more space before running flow-visibility e2e test

- cmd/antrea-agent/agent.go
- docs/prometheus-integration.md
- pkg/agent/metrics/prometheus.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/pipeline.go
- pkg/ovs/openflow/interfaces.go
- pkg/ovs/openflow/ofctrl_bridge.go
- pkg/ovs/openflow/ofctrl_bridge_test.go
- pkg/ovs/openflow/testing/mock_openflow.go
- pkg/ovs/ovsctl/testing/mock_ovsctl.go
- test/e2e/prometheus_test.go
- test/integration/agent/openflow_test.go
We have implemented rate-limiting for packet-in messages on NetworkPolicy audit logging and Traceflow.
This change adds a metric to show the packet count which is got from meter statistics. A separate goroutine is used here to get the statistics every 30 seconds and collect the metric. The value more than 0 indicates that current rate exceeds predefined limit(100 per second).
Fixes: #5037
> Add ovs meter metric

- docs/windows.md
- hack/windows/Prepare-Node.ps1
This patch gives the user the option of using containerd runtime while using the PrepareNode.ps1 for configuring k8s on windows node.
> Add containerd support to PrepareNode script

- ci/jenkins/test.sh
- ci/run-k8s-e2e-tests.sh
To improve testing efficiency, this commit enables the e2e-parallel
flag for Sonobuoy, allowing e2e tests to be executed in parallel.
This optimization reduces the execution time for different jobs:
* conformance: 60 min -> 26 min
* networkpolicy: 86 min -> 32 min
* ipv6-only-conformance: 24 min -> 20 min
* ipv6-only-networkpolicy: 266 min -> 94 min
* ipv6-ds-conformance: 24 min -> 20 min
* ipv6-ds-networkpolicy: 254 min -> 96 min
> Enable parallel execution for Sonobuoy e2e tests 

- Makefile
- build/images/Dockerfile.build.windows
- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/windows/containerd-with-ovs/conf/Run-AntreaOVS-Containerd.ps1
- build/yamls/windows/containerd-with-ovs/conf/VMSwitchExtension-AntreaAgent-Containerd.ps1
- build/yamls/windows/containerd-with-ovs/containerd-with-ovs.yml
- build/yamls/windows/containerd-with-ovs/kustomization.yml
- build/yamls/windows/containerd/agent-containerd.yml
- build/yamls/windows/containerd/conf/Run-AntreaAgent-Containerd.ps1
- docs/windows.md
- hack/generate-manifest-windows.sh
- hack/release/prepare-assets.sh
- hack/windows/Clean-AntreaNetwork.ps1
- hack/windows/Install-OVS.ps1
- hack/windows/Prepare-Node.ps1
- hack/windows/Uninstall-OVS.ps1
> Add support to run Windows OVS in container

- docs/getting-started.md
- docs/kubernetes-installers.md
Add Documentation for deploying Antrea with Rancher cluster.
> Add Documentation for deploying Antrea with Rancher cluster

- build/images/Dockerfile.build.windows
- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/antrea-windows-containerd.yml
- build/yamls/windows/containerd-with-ovs/containerd-with-ovs.yml
- build/yamls/windows/containerd/conf/Run-AntreaAgent-Containerd.ps1
> Use antrea-windows image for antrea-ovs container

- docs/antctl.md
- pkg/antctl/antctl.go
- pkg/antctl/command_definition.go
- pkg/antctl/command_list.go
- pkg/antctl/raw/upgrade/apistorage/command.go
- pkg/antctl/raw/upgrade/apistorage/command_test.go
Add command 'antctl upgrade api-storage' in antctl to upgrade
existing objects of Antrea CRDs to the latest API version.
For #4832
TODO:
> Add command 'antctl upgrade api-storage' in antctl

- docs/external-node.md
- pkg/controller/networkpolicy/mutate_test.go
- test/e2e/k8s_util.go
- test/e2e/traceflow_test.go
traceflowIntraNodeANNP failed due to Windows containerd env setup according to issue #5126 , which is closed now. But there are still some minor fixes remaining in this PR.
> Cleanup traceflowIntraNodeANNP and followup ANNP

- test/e2e/vmagent_test.go
The original test cases uses the same domain name and different applications for
both "Drop" and "Reject" actions, the two rules may be impacted by each other if
the DNS response referred to the same IP address, then the test results are also
impacted. Use different domain names in the FQDN cases to avoid such flaky
failure.
> Resolve flaky failure in VM agent e2e case with ANP FQDN

- third_party/proxy/healthcheck/service_health.go
This commit adds the new header "X-Load-Balancing-Endpoint-Weight" to AntreaProxy. The header will be returned from the service health and its value will represent the number of local Endpoints. This header enables weighted load balancing and offers a faster alternative to parsing JSON from the content body.
The addition of this header is necessary for achieving parity with kube-proxy.
> Add "X-Load-Balancing-Endpoint-Weight" header to AntreaProxy Service healthcheck

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/config/agent/config.go
Users can now configure log rotation for audit logs in the antrea-agent config.
The default values for log rotation parameters are the same as the hardcoded values in previous Antrea versions. Even if the user omits the auditLogging section in the configuration, default values will be used.
Fixes #5262
> Add log rotation configuration for audit logs

- ci/kind/test-e2e-kind.sh
From 15m to 20m.
I have seen the job fail a couple of times lately because of the timeout.
> Increase timeout for Flow Visibility e2e tests on Kind

- pkg/agent/agent.go
- pkg/agent/agent_test.go
When agent fails to connect to K8s API, the previous error logs about empty PodCIDR has no basis, and it shouldn't suggest users to check kube-controller-manager configuration.
> E0803 11:57:06.000640       1 agent.go:926] "Spec.PodCIDR is empty for Node. Please make sure --allocate-node-cidrs is enabled for kube-controller-manager and --cluster-cidr specifies a sufficient CIDR range" err="failed to get Node with name kind-worker from K8s: Get \"https://1.1.1.1/api/v1/nodes/kind-worker\": dial tcp 1.1.1.1:443: i/o timeout" nodeName="kind-worker"
> F0803 11:57:06.001470       1 main.go:53] Error running agent: error initializing agent: CIDR string is empty for Node kind-worker
This patch fixes the error logs by differentiating ErrWaitTimeout from other errors. Only the former means the …
> Fix error log when agent fails to connect to K8s API

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- pkg/config/agent/config.go
Revert #4440. The OVS secondary network parameters were added for overlay secondary network support, but the feature was not continued, and #5279 introduces a new way to configure OVS bridges for secondary networks.
> Revert "Antrea Agent configuration parameters for OVS secondary network"

- build/images/Dockerfile.build.coverage
- build/images/Dockerfile.build.ubi
- build/images/Dockerfile.build.ubuntu
- test/e2e/antctl_test.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
- test/e2e/main_test.go
- test/e2e/service_externalip_test.go
Instead of copying the antctl binary to the Node.
This simplifies tests in the following ways:
* No need to generate a Kubeconfig using the kube-system/antctl ServiceAccount token. Instead we define a ServiceAccount in the test Namepace, bind the antctl ClusterRole to it, and use it for the antctl Pod.
* No need to use different antctl binary paths for Kind and VMs.
* Easier lifecyle management when running antctl proxy.
We also remove the assumption that curl is available on the control-plane Node.
> Always run antctl in Pod for e2e tests

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_test.go
- pkg/agent/agent.go
- pkg/agent/agent_linux.go
- pkg/agent/agent_test.go
- pkg/agent/agent_windows.go
- pkg/agent/secondarynetwork/init.go
- pkg/agent/secondarynetwork/init_test.go
- pkg/agent/util/net.go
- pkg/agent/util/net_test.go
- pkg/config/agent/config.go
- pkg/ovs/ovsconfig/ovs_client.go
- pkg/util/k8s/client.go
- test/integration/ovs/ovs_client_test.go
Add OVS bridge configuration to the secondary network configuration in antrea-agent.conf, which specifies the OVS bridges for Pod secondary networks and also physical interfaces of the bridges. At the moment, only a single bridge is supported and at most one physical interface can be configured on the bridge. antrea-agent will automatically create the OVS bridge and connects the physical interface (if specified) to the bridge, when the bridge is specified in the secondary network configuration and does not exist on the host.
Issue: #5278
> Support OVS bridge creation for secondary network

- pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go
- pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go
- pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go
- pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go
- pkg/apiserver/registry/stats/networkpolicystats/rest.go
- pkg/apiserver/registry/stats/networkpolicystats/rest_test.go
Some unit tests were assuming that the clock for the test machine was using the UTC time zone. In my case, the unit tests were failing when run locally.
> Fix unit tests for pkg/apiserver/registry/stats

- pkg/agent/cniserver/sriov.go
- pkg/ovs/ovsctl/appctl.go
- pkg/ovs/ovsctl/interface.go
- pkg/ovs/ovsctl/mock_ovsctl_test.go
- pkg/ovs/ovsctl/ofctl.go
- pkg/ovs/ovsctl/ovsctl.go
- pkg/ovs/ovsctl/ovsctl_others.go
- pkg/ovs/ovsctl/ovsctl_windows.go
- pkg/ovs/ovsctl/testing/mock_ovsctl.go
We are currently using the shell (/bin/sh) to run ovs-appctl and ovs-ofctl commands, but there does not seem to be a reason to do so.
Instead, we can invoke the binary directly with exec.Command and pass the arguments as a slice.
Before this change, ovsVSwitchdUDS would return
"/var/run/openvswitch/ovs-vswitchd.*.ctl" as a fallback value in case the PID of ovs-vswitchd could not be determined. The shell would then expand the wildcard patterns. I now believe that it is better to return an error in that case. We want to make sure that we use a valid file always (and returning the glob pattern would cause an error if multiple files match). If we run into issues because of this approach, we can update the code to expand the glob pattern programmatically and, if a single path matches, we can …
> Stop using /bin/sh for OVS commands

- pkg/agent/cniserver/sriov.go
- pkg/ovs/ovsctl/appctl.go
- pkg/ovs/ovsctl/interface.go
- pkg/ovs/ovsctl/mock_ovsctl_test.go
- pkg/ovs/ovsctl/ofctl.go
- pkg/ovs/ovsctl/ovsctl.go
- pkg/ovs/ovsctl/ovsctl_others.go
- pkg/ovs/ovsctl/ovsctl_windows.go
- pkg/ovs/ovsctl/testing/mock_ovsctl.go
Cherry pick of #5364 on release-1.13.
#5364: Stop using /bin/sh for OVS commands
> Automated cherry pick of #5364: Stop using /bin/sh for OVS commands

- pkg/controller/grouping/controller_test.go
- pkg/controller/traceflow/controller_test.go
Move TestPodIPsIndexFunc from package controller/traceflow to controller/grouping, because PodIPsIndexFunc is in package controller/grouping.
> Move TestPodIPsIndexFunc to package controller/grouping

- multicluster/controllers/multicluster/leader/clusterset_controller.go
- multicluster/controllers/multicluster/leader/clusterset_controller_test.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
1. r.Update() will only update Spec but not status. Revert the change
back to update status only.
2. Update the ClusterSet's ClusterID in ClusterSet's reconciler.
3. Refine test codes for leader ClusterSet controller.
> Fix a bug that ClusterSet status is no longer updated

- pkg/agent/controller/networkpolicy/reconciler.go
- pkg/agent/controller/networkpolicy/reconciler_test.go
- pkg/controller/networkpolicy/adminnetworkpolicy.go
When processing AdminNetworkPolicy and BaselineAdminNetworkPolicy named port rules, the ports section will not have protocol specified. Antrea agent should infer the protocol from the container spec so that rule can be enforced correctly in ovs.
Change has been verified with https://github.com/kubernetes-sigs/network-policy-api/pull/132
> Fix missing protocol in service when processing ANP named ports

- pkg/apiserver/registry/stats/multicastgroup/rest.go
- pkg/apiserver/registry/stats/multicastgroup/rest_test.go
> [Multicast] Remove NetworkPolicyStats dependency of MulticastGroup API

- multicluster/controllers/multicluster/leader/clusterset_controller.go
- multicluster/controllers/multicluster/leader/clusterset_controller_test.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
Cherry pick of #5338 on release-1.13.
#5338: Fix a bug that ClusterSet Status is not updated
> Automated cherry pick of #5338: Fix a bug that ClusterSet status is no longer updated

- cmd/antrea-agent/options.go
- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
The initialization was in setK8sNodeDefaultOptions, which is incorrect, as it also applies to the VM / ExternalNode case.
> Fix Audit Logging options initialization in Agent

- build/yamls/externalnode/conf/antrea-agent.conf
VM Agent crashes because log rotation configuration is nil. 
This change adds log rotation configuration for VM Agent.
> Add log rotation configuration for VM Agent

- pkg/agent/config/ipsec_authentication_mode.go
- pkg/agent/util/net_windows.go
Cherry pick of #5385 on release-1.13.
#5385: Support querying all NDIS network adapters
> Automated cherry pick of #5385: Support querying all NDIS network adapters

- build/charts/antrea/templates/webhooks/validating/crdvalidator.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-controller/controller.go
- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
- pkg/apiserver/apiserver.go
- pkg/controller/traceflow/controller.go
- pkg/controller/traceflow/controller_test.go
- pkg/controller/traceflow/validate.go
- pkg/controller/traceflow/validate_test.go
- test/e2e/fixtures.go
- test/e2e/traceflow_test.go
Currently, the traceflow CRD validation is executed in run-time, which is less user-friendly than the webhook validation. I moved most of the validation to the webhook validation.
Some of the validations in Agent is unchanged because they need the information of the Agent. Also, I found the current validation is insufficient, but I left the improvement as a future work.
> Switch traceflow CRD validation to webhook validation.

- pkg/apiserver/registry/stats/multicastgroup/rest.go
- pkg/apiserver/registry/stats/multicastgroup/rest_test.go
Cherry pick of #5367 on release-1.11.
#5367: Remove NetworkPolicyStats dependency of
> Automated cherry pick of #5367: Remove NetworkPolicyStats dependency of of MulticastGroup API

- cmd/antrea-agent/agent.go
Recent changes for K8s Node cause VM Agent RBAC warnings regarding service and node. These warnings will flood VM Agent logs.
This change fixes the issue by only initializing the related components for K8s Node case.
> Fix VM Agent RBAC warnings

- ci/jenkins/test-vm.sh
Clean stale docker resources before running
VM e2e tests.
> Cleanup enhancement for VM e2e test

- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- pkg/agent/controller/networkpolicy/audit_logging.go
- pkg/agent/controller/networkpolicy/audit_logging_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/agent/controller/networkpolicy/packetin.go
- pkg/agent/openflow/framework.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
Currently Audit logging is controlled by AntreaPolicy feature gate, but it also logs K8s NetworkPolicies.
This solution decouples Audit logging with the AntreaPolicy feature gate and renames the related objects.
Fixes #5340
> Decouple Audit logging from AntreaPolicy feature gate

- multicluster/controllers/multicluster/member/labelidentity_controller.go
- multicluster/controllers/multicluster/member/labelidentity_controller_test.go
- pkg/controller/labelidentity/label_group_index.go
- pkg/controller/labelidentity/label_group_index_test.go
Fixes #5403 
When a Pod is created without any labels at all, its labelidentity will include `pod:<none>` as defined by FormatLabels in apimachinery. This case is not handled correctly by the label group index and can cause the controller to crash.
> Fix controller issue in handling empty pod labels for labelidentity

- build/charts/flow-aggregator/README.md
- build/charts/flow-aggregator/templates/deployment.yaml
- build/charts/flow-aggregator/values.yaml
- build/yamls/flow-aggregator.yml
Add hostAliases to Helm values for Flow Aggregator
User might want to use hostAliases field when connecting Flow Aggregator to ClickHouse through Ingress/LoadBalancer.
It is also convenient for e2e test.
Signed-off-by: Yun-Tang Hsu <hsuy@vmware.com>
> Add hostAliases to Helm values for Flow Aggregator

- test/e2e/traceflow_test.go
The test case was making the assumption that every Pod always has an IPv4 address, which is not the case for IPv6-only clusters.
To simplify the test case, we use the Pod's namepspace/name to define the Traceflow destination, instead of the Pod's IP address.
> Fix e2e test testTraceflowValidation for IPv6-only cluster

- ci/jenkins/test-mc.sh
- docs/multicluster/user-guide.md
- hack/release/prepare-assets.sh
- multicluster/Makefile
- multicluster/build/yamls/antrea-multicluster-leader.yml
- multicluster/config/overlays/leader/coverage/manager_command_patch_coverage.yaml
- multicluster/config/overlays/leader/crd_patch.yaml
- multicluster/config/overlays/leader/kustomization.yaml
- multicluster/config/overlays/leader/kustomizeconfig.yaml
- multicluster/config/overlays/leader/manager_command_patch.yaml
- multicluster/config/overlays/leader/member_cluster_role.yaml
- multicluster/config/overlays/leader/member_cluster_rolebinding.yaml
- multicluster/config/overlays/leader/member_cluster_serviceaccount.yaml
- multicluster/config/overlays/leader/prefix_transformer.yaml
- multicluster/config/overlays/leader/role.yaml
- multicluster/config/overlays/leader/role_binding.yaml
- multicluster/config/overlays/leader/secret.yaml
- multicluster/config/overlays/leader/service_account.yaml
- multicluster/config/overlays/leader/webhook_patch.yaml
- multicluster/config/overlays/leader/webhook_rbac.yaml
- multicluster/hack/generate-manifest.sh
- pkg/antctl/raw/multicluster/deploy/deploy_helper.go
- pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
For the multi-cluster leader cluster deployment, we provide two separate manifests for CRDs and Namespaced Controller deployment respectively. However, this is not a typical way for OSS users, so we add a new all-in-one manifest to simplify the deployment.
> Add a new all-in-one manifest for the Multi-cluster leader cluster

- pkg/agent/metrics/prometheus.go
- pkg/agent/openflow/client.go
Otherwise the metric is not showing up if OVS Meter is not supported on the system, causing e2e test failure.
> Always initialize ovs_meter_packet_dropped_count metrics

- multicluster/controllers/multicluster/member/labelidentity_controller.go
- multicluster/controllers/multicluster/member/labelidentity_controller_test.go
- pkg/controller/labelidentity/label_group_index.go
- pkg/controller/labelidentity/label_group_index_test.go
Cherry pick of #5404 on release-1.11.
#5404: Fix controller issue in handling empty pod labels for
> Automated cherry pick of #5404: Fix controller issue in handling empty pod labels for

- pkg/antctl/client.go
- pkg/antctl/command_message.go
- pkg/antctl/command_message_test.go
I saw the following error when running golangci (only shows up with certain versions of Go and Golangci-lint).
```
===> Running golangci (linux) <===
pkg/antctl/command_message.go:28:88: SA4023: this comparison is always true (staticcheck)
if errMsg := generate(opt.commandDefinition, opt.args, code, result.Error().Error()); errMsg != nil {
^
pkg/antctl/command_message.go:41:6: SA4023(related information): antrea.io/antrea/pkg/antctl.generate never returns a nil interface value (staticcheck)
func generate(cd *commandDefinition, args map[string]string, code int, err string) error {
^
make: *** [golangci] Error 1
```
When fixing the code, I realized that the code was not well-commented, and was a bit confusing, so I did some refactoring.
For resource requests, the StatusError returned by the …
> Clean up code in pkg/antctl/command_message.go

- pkg/agent/metrics/prometheus.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/network_policy.go
- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/packetin.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/types/networkpolicy.go
- pkg/ovs/openflow/interfaces.go
- pkg/ovs/openflow/ofctrl_builder.go
- pkg/ovs/openflow/testing/mock_openflow.go
Fixes #5387
1. Change to use ct_state to match the DNS responses that need further interception.
2. Add OF meter for DNS interception.
> Uniform TCP and UDP DNS interception flows

- pkg/agent/metrics/prometheus.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/network_policy.go
- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/packetin.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/types/networkpolicy.go
- pkg/ovs/openflow/interfaces.go
- pkg/ovs/openflow/ofctrl_builder.go
- pkg/ovs/openflow/testing/mock_openflow.go
Cherry pick of #5392 on release-1.13.
#5392: Uniform DNS Interception
> Automated cherry pick of #5392: Uniform DNS Interception

- pkg/antctl/raw/proxy/command.go
The port was always overwritten by the default port.
> Fix antctl proxy not using user specified port

- pkg/agent/memberlist/cluster.go
- pkg/agent/memberlist/cluster_test.go
Windows Nodes should not join the memberlist cluster as all features relying on it is not only supported on Windows. Currently an agent only runs the memberlist module and listen to the memberlist port when required so attempts to join Windows agents are destined to fail, leading to misleading error logs.
This commit fixes it by ignoring Windows Nodes when joining agents.
Fixes #5431
----------
Confirmed the error logs are gone in a mixed OS testbed.
> Do not attempt to join Windows agents to memberlist cluster

- pkg/antctl/raw/proxy/command.go
Cherry pick of #5435 on release-1.13.
#5435: Fix antctl proxy not using user specified port
> Automated cherry pick of #5435: Fix antctl proxy not using user specified port

- multicluster/cmd/multicluster-controller/controller.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
Use the Namespace field selector to filter Gateway and ClusterSet events
via "NewCache" to minimize unnecessary event handling.
> Add Namespace field selector in cache to filter Gateway and ClusterSet

- pkg/agent/memberlist/cluster.go
- pkg/agent/memberlist/cluster_test.go
Cherry pick of #5434 on release-1.11.
#5434: Do not attempt to join Windows agents to memberlist cluster
> Automated cherry pick of #5434: Do not attempt to join Windows agents to memberlist cluster

- multicluster/controllers/multicluster/stale_controller.go
- multicluster/controllers/multicluster/stale_controller_test.go
- pkg/controller/labelidentity/label_group_index.go
- pkg/controller/labelidentity/label_group_index_test.go
This is a follow-up on PR #5404 which intends to address issue #5403. 
In upgrade cases, Antrea controller will still receive LabelIdentity add events for LabelIdentities created by previous controller, which it needs to handle correctly. Also, the stale controller logic needs to be updated to ensure that LabelIdentities created with old normalization method are cleaned up after upgrade.
> Handle stale LabelIdentities created for empty Pod labels correctly after upgrade

- multicluster/controllers/multicluster/stale_controller.go
- multicluster/controllers/multicluster/stale_controller_test.go
- pkg/controller/labelidentity/label_group_index.go
- pkg/controller/labelidentity/label_group_index_test.go
Cherry pick of #5449 on release-1.13.
#5449: Handle stale LabelIdentities created for empty Pod labels
> Automated cherry pick of #5449: Handle stale LabelIdentities created for empty Pod labels

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
Change IPv6 and dual-stack Jenkins job script from test-vms.sh to test.sh to correct the
inconsistent definitions with the actual job definitions in the Jenkins. Issue #5334
> Fix: Change IPv6 and Dual-stack jenkins job

- ci/jenkins/jobs/macros.yaml
Since a Jenkins variable "conformance_type" is used in the Jenkins macro "builder-conformance-jumper", shell variables need double brackets rather than single brackets.
> Fix Jenkins jobs validation error

- cmd/antrea-agent/agent.go
- cmd/antrea-controller/controller.go
- pkg/agent/cniserver/ipam/antrea_ipam_controller.go
- pkg/agent/cniserver/ipam/antrea_ipam_test.go
- pkg/agent/controller/noderoute/node_route_controller.go
- pkg/agent/controller/noderoute/node_route_controller_test.go
- pkg/agent/controller/traceflow/packetin.go
- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/nodeportlocal/npl_agent_init.go
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/controller/ipam/antrea_ipam_controller.go
- pkg/controller/ipam/antrea_ipam_controller_test.go
While checking the usage of nodeInformer, I found modules used different ways to get needed informers. Some get informers from parameters directly while some create them with the informerFactory parameter. Unifying to the first usage could help track the resource's consumer more directly, and is more in line with the principle of least priviledge: instead of giving a module the access to all resources, we give it the access needed to perform its job only.
This commit also cleans up some parameters and member variables that are never used.
> Clean up parameters of constructors

- pkg/ovs/openflow/ofctrl_bridge.go
- pkg/ovs/openflow/ofctrl_bridge_test.go
The burst was not effective because the number of tokens was hardcoded to 1, leading to 10ms delay when processing every successive DNS response. For example, in some scenario it takes a client 10 DNS queries to get a valid DNS response, the later 9 DNS responses would be delayed 90ms in total. This affected the DNS resolution delay when a Pod has any FQDN policy applied.
This commit fixes the burst setting of the PacketInQueue. The connection time of accessing a FQDN is reduced from 134ms to 41ms according to my test.
For #5446
> Fix burst of PacketInQueue

- pkg/agent/agent_linux.go
- pkg/agent/agent_linux_test.go
- pkg/agent/agent_test.go
- pkg/agent/agent_windows_test.go
- pkg/agent/util/net_linux.go
- pkg/agent/util/sysctl/sysctl_linux.go
Cherry pick of #5409 on release-1.13.
#5409: Enable IPv6 on OVS internal port if needed in bridging mode
> Automated cherry pick of #5409: Enable IPv6 on OVS internal port if needed in bridging mode

- pkg/agent/openflow/packetin.go
Fixes #5446
100 packets per second and 200 burst are not enough. 
Increase to 500 packets per second and 1000 burst.
> Increase Rate-limit config

- ci/run-k8s-e2e-tests.sh
- ci/verify-sonobuoy.sh
Cherry pick of #5184 on release-1.11.
#5184: Update sonobuoy version to v0.56.16
> Automated cherry pick of #5184: Update sonobuoy version to v0.56.16

- docs/multicluster/quick-start.md
- docs/multicluster/user-guide.md
- docs/traffic-encryption.md
When the QE follows the doc to set up a ClusterSet, they misunderstood the guide and failed the setup, so add a few more details to avoid misreading.
1. Update the user guide to make it clearer.
2. Update the requirement of WireGuard encryption.
> Update Multi-cluster docs with more details

- docs/prometheus-integration.md
The Prometheus metrics doc validation job is failed. Fix it by updating the metrics doc for Golang metrics change.
There is a new GODEBUG setting added which impact the metrics. https://github.com/golang/go/issues/61965.
The change has been verified here: https://github.com/antrea-io/antrea/actions/runs/6118857003/job/16608129508?pr=5475
> Update Prometheus metrics doc

- ci/jenkins/test.sh
- ci/run-k8s-e2e-tests.sh
Cherry pick of #5280 on release-1.11.
#5280: Sonobuoy e2e tests Enhancement
> Automated cherry pick of #5280: Sonobuoy e2e tests Enhancement

- ci/jenkins/jobs/macros.yaml
Change double brackets to single brackets for Jenkins macro builder-e2e-jumper.
> Fix IPv6 E2E Jenkins job

- multicluster/build/yamls/antrea-multicluster-leader-namespaced.yml
- multicluster/build/yamls/antrea-multicluster-leader.yml
- multicluster/build/yamls/antrea-multicluster-member.yml
- multicluster/cmd/multicluster-controller/clusterset_webhook.go
- multicluster/cmd/multicluster-controller/clusterset_webhook_test.go
- multicluster/cmd/multicluster-controller/controller.go
- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/config/webhook/manifests.yaml
Add a ClusterSet deletion webhook to fail the ClusterSet deletion request
in the leader cluster when any MemberClusterAnnounce exists.
> Add a ClusterSet deletion webhook for the leader cluster

- CHANGELOG/CHANGELOG-1.11.md
The PR https://github.com/antrea-io/antrea/pull/5470 for v1.11.3 has been overwritten bot for v1.13.1, hence manually cherry-pick the change log for the former.
> Update CHANGELOG for v1.11.3 release

- cmd/antrea-agent/agent.go
- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/testing/mock_openflow.go
- pkg/agent/servicecidr/discoverer.go
- pkg/agent/servicecidr/discoverer_test.go
- pkg/agent/servicecidr/testing/mock_servicecidr.go
When AntreaProxy is asked to skip some Services or is not running at all, Pod-to-Service traffic would be forwarded to Egress Node and be load-balanced remotely, as opposed to locally, which could incur performance issue and unexpected behaviors.
This patch installs flows to prevent traffic destined for ServiceCIDRs from being SNAT'd.
Fixes #5494
> Do not apply Egress to traffic destined for ServiceCIDRs

- hack/windows/Install-OVS.ps1
* Fix the bug to prevent downloading the SSL library if files exist in the host path.
* Add a parameter to support installing local SSL library.
* Update the SSL download URL to the GitHub link.
Fixes #5479
> Fix Bugs and Introduce Enhancements in Install-OVS.ps1

- pkg/agent/agent_linux.go
Fixes: #5398
When the MTU value of Antrea network is greater than the maximum supported MTU by
Suricata, which is used as L7 NetworkPolicy engine in Antrea. It may fail to start.
Currently, assuming that the page size is 4096, the maximum supported MTU by Suricata
is 32678 according to Suricata source code at
https://github.com/OISF/suricata/blob/49713ebaa0b8edb057d60f1cfe9126946645a848/src/source-af-packet.c#L1757C2-L1777C129.
This commit adds an error logging to warn users about that.
> Add error logging for that Antrea network's MTU exceeds Suricata's maximum supported value

- .github/workflows/benchmark.yml
- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- .github/workflows/codeql.yml
- .github/workflows/conformance.yml
- .github/workflows/dependabot.yml
- .github/workflows/docker_update_base_windows.yml
- .github/workflows/go.yml
- .github/workflows/golicense.yml
- .github/workflows/kind.yml
Now that we are using actions/checkout@v4, we can choose not to log fetch progress when using the action. The fetch progress does not add any value and can cause hundreds of unnecessary lines to be logged.
> Stop logging git fetch progress in actions/checkout

- pkg/agent/memberlist/cluster_test.go
The test was flaky on machine with a limited amount of CPU, and I was able to reproduce locally by setting GOMAXPROCS to 1.
If the Node object is created after starting the informers and waiting for them to be synced, then the Node may not be "visible" to the lister when the ExternalIPPool is synced. So we need to create the Node when we instantiate the fake K8s client, before starting the informers.
> Fix flaky TestCluster_Run unit test

- cmd/antrea-agent/agent.go
- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/testing/mock_openflow.go
- pkg/agent/servicecidr/discoverer.go
- pkg/agent/servicecidr/discoverer_test.go
- pkg/agent/servicecidr/testing/mock_servicecidr.go
Cherry pick of #5495 on release-1.12.
#5495: Do not apply Egress to traffic destined for ServiceCIDRs
> Automated cherry pick of #5495: Do not apply Egress to traffic destined for ServiceCIDRs

- hack/update-codegen.sh
The mockgen target was behaving like the codegen target, and running "make mockgen" meant that all the generators were run, instead of only the mocks generator.
> Fix "make mockgen"

- pkg/flowaggregator/flowaggregator.go
The test was flaky because sometimes not all expectations were met. For example:
> mockPodStore.EXPECT().Run(gomock.Any())
The reason is that the FlowAggregator Run method can return "too quickly", while some of its goroutines are still in the process of being started. Rather than make these expectations optional, which I think is a bit hacky, we leverage WaitGroups in Run to ensure that all child goroutines complete before returning from Run.
> Fix flaky TestFlowAggregator_Run unit test

- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
At present, flows for nested Services that are used by the multi-cluster are unconditionally added to EndpointDNAT, leading to the presence of numerous redundant flows when the multi-cluster feature is inactive. With the proposed changes, these associated flows will be only installed when multi-cluster is enabled.
> Install flows for nested Services in EndpointDNAT only when MC is enabled

- ci/kind/test-e2e-kind.sh
- test/e2e/main_test.go
Fixes #5525.
Go has an inbuilt skip flag with go test options so we cannot use a flag with same name in our custom test options.
> Rename skip in custom Test Options

- ci/kind/test-e2e-kind.sh
- test/e2e/main_test.go
Cherry pick of #5526 on release-1.12.
#5526: Rename skip flag in custom Test Options
> Automated cherry pick of #5526: Rename skip flag in custom Test Options

- pkg/agent/cniserver/ipam/ipam_service.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_test.go
* When performing configuration rollback after an error in CmdAdd, we do not invoke CmdDel directly. Instead, we invoke an internal version of it which does not log a "Received CmdDel request" message (the message is confusing otherwise as it implies that we received a new CNI DEL command from the container runtime), and which does not process the network config again (as it was already processed at the beginning of CmdAdd). By not processing the config a second time, we ensure that there are no duplicate CIDRs in the IPAMConfig.
* Migrate klog calls in server.go to use structured logging.
* Improve unit tests for the CNI server to validate this fix.
Fixes #5547
> Fix rollback invocation after CmdAdd failure in CNI server

- pkg/agent/cniserver/ipam/ipam_service.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_test.go
Cherry pick of #5548 on release-1.13.
#5548: Fix rollback invocation after CmdAdd failure in CNI
> Automated cherry pick of #5548: Fix rollback invocation after CmdAdd failure in CNI

- pkg/agent/supportbundlecollection/support_bundle_controller.go
- pkg/agent/supportbundlecollection/support_bundle_controller_test.go
- pkg/apiserver/registry/system/supportbundle/rest.go
- pkg/apiserver/registry/system/supportbundle/rest_test.go
- pkg/support/dump.go
- pkg/support/dump_test.go
Fixes #5243 
This PR adds goroutine stack dump in support bundle for both agent and controller. Sample shown below for controller.
```
antrea % kubectl get pods -l app=antrea -n kube-system
NAME                                 READY   STATUS    RESTARTS   AGE
antrea-agent-lvnl6                   2/2     Running   0          57m
antrea-controller-668f6cc866-b4gxt   1/1     Running   0          57m
antrea % kubectl exec -it antrea-controller-668f6cc866-b4gxt -n kube-system -c antrea-controller bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@minikube:/# antctl supportbundle
Created bundle under /tmp
Expire time: 2023-10-01 17:07:18 +0000 UTC
root@minikube:/# tar -xzvf /tmp/bundle_269813909.tar.gz …
```
> Add goroutine stack dump in support bundle

- .github/dependabot.yml
Instead of having 3+ Dependabot PRs every time there is a new patch release for golang.org/x packages, there will be a single PR to update all of them at the same time.
> [Dependabot] Group golang.org/x updates

- pkg/apis/controlplane/types.go
- pkg/apis/controlplane/v1beta2/zz_generated.conversion.go
- pkg/apis/controlplane/zz_generated.deepcopy.go
- pkg/apiserver/registry/networkpolicy/clustergroupmember/rest.go
- pkg/client/clientset/versioned/typed/controlplane/v1beta2/clustergroupmembers_expansion.go
- pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_clustergroupmembers_expansion.go
- pkg/client/clientset/versioned/typed/controlplane/v1beta2/fake/fake_groupmembers_expansion.go
- pkg/client/clientset/versioned/typed/controlplane/v1beta2/generated_expansion.go
- pkg/client/clientset/versioned/typed/controlplane/v1beta2/groupmembers_expansion.go
GroupMembers API was introduced in #5380 , pagination was supported for proxy server, but not for client. There are usecases for client-go pagination. This solution utilizes the `GroupMembersExpansion` to provide a new method `GetPaginated`.
> Support GroupMembers API Pagination for Client

- pkg/util/k8s/node.go
- pkg/util/k8s/node_test.go
Some cloud providers can return multiple addresses of the same type for a Node. We should use the first matching address to find the correct transport interface.
> Use the first matching address when getting node address

- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/controller/networkpolicy/subscribe.go
- pkg/controller/networkpolicy/subscribe_test.go
A NetworkPolicy's span is calculated in internalNetworkPolicyWorker, based on the span of the AppliedToGroups it refers to, while the span of AppliedToGroup is calculated in appliedToGroupWorker which runs in parallel with internalNetworkPolicyWorker. It could happen that the calcuated span is out of date if AppliedToGroups' span is updated after internalNetworkPolicyWorker calculates a NetworkPolicy's span, and the NetworkPolicy wouldn't be enqueued for another sync if it's not committed to the storage yet.
On the other hand, if we commit the NetworkPolicy to the storage before calculating the NetworkPolicy's span, it would have to use a stale span first and might need to update the NetworkPolicy twice and generate two update events in one sync.
To fix the issue without generating extra …
> Fix NetworkPolicy span calculation

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
Fixes #5565 
As descried in the issue above, a deadlock could occur when :
1. Rule sync fails due to realization error in dataplane, and the controller 
retries it later despite there's no IP changes for the FQDN. 
2. A single Antrea-native policy rule refers to multiple FQDNs, and the
fqdn controller receives updated records for these FQDNs at around
the same time. One of the FQDN has address updates so the rule
need to be resynced and thus marked dirty. Another FQDN does not
have address updates, but the controller tries to read the dirtyRules
to make sure that, if it is a previously failed to sync rule, it gets 
re-queued even when there's no address updates.
This PR addresses the deadlock issue by explicitly putting the lock
around the get dirty rules op itself. 
Additional UT for …
> Fix deadlock when accessing dirtyRules in fqdn controller

- pkg/ovs/openflow/ofctrl_action_test.go
- pkg/ovs/openflow/ofctrl_builder_test.go
- pkg/ovs/openflow/ofctrl_group_test.go
- pkg/ovs/openflow/ofctrl_meter_test.go
- pkg/ovs/openflow/ofctrl_packetout.go
- pkg/ovs/openflow/ofctrl_packetout_test.go
- pkg/ovs/openflow/utils.go
- pkg/ovs/ovsctl/interface.go
> Add unit tests for pkg/ovs/openflow

- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/controller/networkpolicy/subscribe.go
- pkg/controller/networkpolicy/subscribe_test.go
Cherry pick of #5554 on release-1.11.
#5554: Fix NetworkPolicy span calculation
> Automated cherry pick of #5554: Fix NetworkPolicy span calculation

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
Cherry pick of #5566 on release-1.13.
#5566: Fix deadlock when accessing dirtyRules in fqdn controller
> Automated cherry pick of #5566: Fix deadlock when accessing dirtyRules in fqdn controller

- pkg/ovs/openflow/ofctrl_action_test.go
dc0ca2d0444f ("Add unit tests for pkg/ovs/openflow") was not rebased on top of tree when it was merged, introducing a build error.
> Fix build error caused by merge conflict

- Makefile
- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/antrea-windows-containerd.yml
- build/yamls/antrea-windows.yml
- build/yamls/windows/base/kustomization.yml
- build/yamls/windows/containerd-with-ovs/kustomization.yml
- build/yamls/windows/containerd/agent-containerd.yml
- build/yamls/windows/containerd/kustomization.yml
- build/yamls/windows/default/agent.yml
- build/yamls/windows/default/kustomization.yml
- hack/update-checksum-windows.sh
When the ConfigMap is generated with suffix by kustomize, it will generate a manifest with new ConfigMap like 'antrea-windows-config-***'. When a new manifest is applied, it will leave stale ConfigMaps. To avoid stale ConfigMaps, here we add checksum of windows configuration files as annotations.
> Add checksum of windows config files as annotations

- pkg/agent/controller/networkpolicy/fqdn.go
`ruleSyncTracker.Run()` can update `ruleSyncTracker.dirtyRules` in-place, while `ruleSyncTracker.getDirtyRules()` returns the pointer of the set which could be read by other goroutines and leads to a data race like below:
```
WARNING: DATA RACE
Write at 0x00c000dd8180 by goroutine 276:
runtime.mapdelete_faststr()
/usr/local/go/src/runtime/map_faststr.go:301 +0x0
k8s.io/apimachinery/pkg/util/sets.Set[go.shape.string].Delete()
/root/go/pkg/mod/k8s.io/apimachinery@v0.26.4/pkg/util/sets/set.go:62 +0x2ae
antrea.io/antrea/pkg/agent/controller/networkpolicy.(*ruleSyncTracker).Run()
/root/antrea/pkg/agent/controller/networkpolicy/fqdn.go:570 +0x1d2
antrea.io/antrea/pkg/agent/controller/networkpolicy.(*fqdnController).runRuleSyncTracker()
/root/antrea/pkg/agent/controller/networkpolicy/fqdn.go:584 …
```
> Fix data race in FQDN ruleSyncTracker

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
Cherry pick of #5566 and #5583 on release-1.12.
#5566: Fix deadlock when accessing dirtyRules in fqdn controller
#5583: Fix data race in FQDN ruleSyncTracker
> Automated cherry pick of #5566 and #5583: Fix deadlock when accessing dirtyRules in fqdn controller

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
Cherry pick of #5566 and #5583 on release-1.11.
#5566: Fix deadlock when accessing dirtyRules in fqdn controller
#5583: Fix data race in FQDN ruleSyncTracker
> Automated cherry pick of #5566 and #5583 Fix deadlock when accessing dirtyRules in fqdn controller

- pkg/antctl/raw/traceflow/command.go
- pkg/antctl/raw/traceflow/command_test.go
> Fix antctl traceflow using IPv6 address

- pkg/antctl/raw/traceflow/command.go
- pkg/antctl/raw/traceflow/command_test.go
Cherry pick of #5588 on release-1.12.
#5588: Fix antctl traceflow using IPv6 address
> Automated cherry pick of #5588: Fix antctl traceflow using IPv6 address

- CONTRIBUTING.md
- ci/jenkins/README.md
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
- ci/jenkins/stop-stale-jobs.sh
Note: This PR implemented "/stop-all-jobs" to kill background running and waiting jobs related to a PR . Currently this feature enable only for CAPV related jobs, in the code i have used Jenkins REST API to implement this task.
Trigger '/stop-all-jobs' on your PR to kill stale running and waiting CAPV jobs related to PR.
> Implement /stop-all-jobs to kill jobs related to a PR

- docs/multicluster/user-guide.md
The new asset `antrea-multicluster-leader.yml` is not ready yet since v1.14 is not released. It's a little confused for a user to follow the guide with the new manifest, so added the version info about the deployment change.
> Clarify the version of Multi-cluster user guide for the new leader manifest

- test/e2e/k8s_util.go
To differentiate whether the output gets cut or the agnhost command didn't output anything.
For #5139
> [e2e] Append an ending message in the test output

- test/e2e/antreapolicy_test.go
- test/e2e/framework.go
- test/e2e/multicast_test.go
- test/e2e/performance_test.go
The test testACNPICMPSupport failed a few times because pulling the netshoot image took in excess of 90s. The toolbox image also has ping tool and is smaller than netshoot (169MB vs. 432MB). The patch switches to the toolbox image for all e2e tests.
---
The netshoot image can be removed from antrea's dockerhub repo after the patch is backported to all releases in maintenance.
> e2e: switch from netshoot image to toolbox image

- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/antrea-windows-containerd.yml
- build/yamls/antrea-windows.yml
- build/yamls/windows/base/conf/antrea-agent.conf
Helm varible shouldn't be used in windows manifest. 
Fix what https://github.com/antrea-io/antrea/pull/5401 broke.
> Fix windows deployment manifest

- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/windows/containerd-with-ovs/conf/Run-AntreaOVS-Containerd.ps1
- ci/jenkins/test.sh
- docs/windows.md
- hack/windows/Prepare-AntreaAgent.ps1
> Enable Windows OVS Container to run on pristine Host Environment

- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/antrea-windows-containerd.yml
- build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
- ci/jenkins/test.sh
- hack/windows/Prepare-Node.ps1
The patch is required to handle following cases:-
1.To handle WindowsHostProcessContainer for k8s 1.28  and and make required adjustment in antrea-windows-containerd.yaml for containerd 1.7.
2.To change commands to clean containerd environment on jumper node from ci/jenkins.sh (since on new tested we only have docker runtime)
> To support new changes for Windows HostProcess Pod for K8S v1.28 and containerd 1.7

- docs/multicluster/user-guide.md
- hack/.notableofcontents
- multicluster/cmd/multicluster-controller/clusterset_webhook.go
- multicluster/cmd/multicluster-controller/gateway_webhook.go
- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/leader_test.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/cmd/multicluster-controller/options.go
- multicluster/controllers/multicluster/common/controller_utils.go
- multicluster/controllers/multicluster/common/helper.go
- multicluster/controllers/multicluster/leader/clusterset_controller.go
- multicluster/controllers/multicluster/leader/clusterset_controller_test.go
- multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
- multicluster/controllers/multicluster/leader/stale_controller.go
- multicluster/controllers/multicluster/leader/stale_controller_test.go
- multicluster/controllers/multicluster/member/acnp_resourceimport_controller_test.go
- multicluster/controllers/multicluster/member/clusterinfo_importer_test.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
- multicluster/controllers/multicluster/member/gateway_controller_test.go
- multicluster/controllers/multicluster/member/labelidentity_controller_test.go
- multicluster/controllers/multicluster/member/labelidentity_import_controller_test.go
- multicluster/controllers/multicluster/member/node_controller.go
- multicluster/controllers/multicluster/member/resourceimport_controller_test.go
- multicluster/controllers/multicluster/member/serviceexport_controller_test.go
- multicluster/controllers/multicluster/member/stale_controller.go
- multicluster/controllers/multicluster/member/stale_controller_test.go
- multicluster/test/integration/suite_test.go
- pkg/config/controller/config.go
1. Split existing stale controller into leader and member folders.
2. The new stale controller in the leader cluster will do following things:
* Check MemberClusterAnnounce periodically in the leader cluster and
delete the stale CR if its last timestamp annotation `touch-ts` is over 24 hours.
* Clean up all corresponding ResourceExports when a MemberClusterAnnounce is deleted.
* Clean up stale ResourceExports if there is no existing MemberClusterAnnounce when
the controller is started.
* Clean up all MemberClusterAnnounces and corresponding ResourceExports when the controller
is started with no ClusterSet CR.
3. The ClusterSet controller in leader will remove all remaining ResourceExports and
MemberClusterAnnounces when the ClusterSet CR is deleted in the leader cluster.
4. The new stale …
>  Clean up auto-generated resources in leader and member clusters

- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/controllers/multicluster/member/gateway_controller.go
- multicluster/controllers/multicluster/member/gateway_controller_test.go
- multicluster/controllers/multicluster/member/labelidentity_controller.go
- multicluster/controllers/multicluster/member/labelidentity_controller_test.go
- multicluster/controllers/multicluster/member/node_controller.go
- multicluster/controllers/multicluster/member/node_controller_test.go
- multicluster/controllers/multicluster/member/serviceexport_controller.go
- multicluster/controllers/multicluster/member/serviceexport_controller_test.go
- multicluster/test/integration/suite_test.go
1. Add ClusterSet event mapping to several member cluster controllers
to ensure that when a ClusterSet CR is recreated in a member cluster,
the corresponding ResourceExports will be created again in the leader
cluster.
2. Skip reconciling resources when there is no ClusterSet CR in the
member cluster.
This change is on top of #5351, please review the top commit. Thanks.
> Recreate resources when a member cluster rejoins the ClusterSet 

- test/e2e/antreapolicy_test.go
- test/e2e/framework.go
- test/e2e/multicast_test.go
- test/e2e/performance_test.go
Cherry pick of #5536 on release-1.13.
#5536: e2e: switch from netshoot image to toolbox image
> Automated cherry pick of #5536: e2e: switch from netshoot image to toolbox image

- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
When handling a ClusterSet deletion event in a member cluster, check the deleted ClusterSet and clean up Multi-cluster resources only when the current ClusterSet is deleted.
Also fix and enhance the ClusterSet deletion unit test.
> Check deletion event matches ClusterSet before Multi-cluster cleanup

- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
Cherry pick of #5633 on release-1.14.
#5633: Check deletion event matches ClusterSet before Multi-cluster
> Automated cherry pick of #5633: Check deletion event matches ClusterSet before Multi-cluster

- multicluster/cmd/multicluster-controller/leader.go
- multicluster/controllers/multicluster/leader/clusterset_controller.go
- multicluster/controllers/multicluster/leader/clusterset_controller_test.go
- multicluster/controllers/multicluster/member/clusterset_controller.go
- multicluster/controllers/multicluster/member/clusterset_controller_test.go
The ClusterSet resource saved in the leader and member ClusterSet reconcilers is not really useful. This commit removes this field from the reconcilers and uses other fields to read ClusterSet information instead.
> Remove saved ClusterSet from Multi-cluster ClusterSet reconciler

- build/yamls/antrea-windows-containerd-with-ovs.yml
- build/yamls/antrea-windows-containerd.yml
- build/yamls/windows/containerd/conf/Install-WindowsCNI-Containerd.ps1
- ci/jenkins/test.sh
- hack/windows/Prepare-Node.ps1
Cherry pick of #5528 on release-1.13.
#5528: Update prepare-node script, antrea-windows-containerd.yml and
> Automated cherry pick of #5528: Update prepare-node script, antrea-windows-containerd.yml and

- docs/maintainers/release.md
- hack/release/draft-release.sh
- hack/release/prepare-changelog.sh
Creating releases is an error-prone operation. Instead of relying on people to be meticulous, we can automate the process.
The commit adds a script to draft a release in Github for a given version, based on the changelog. It still leaves the final click to people before it's proven reliable.
To make Github include a "Contributors" section with an avatar list of all the mentioned contributors, the author links are removed.
For #2411
-----
Example of "Contributors" section: https://github.com/antrea-io/antrea/releases/tag/v1.13.2
> Add a script for drafting release

- pkg/apiserver/storage/ram/store.go
- pkg/apiserver/storage/ram/store_test.go
- pkg/apiserver/storage/ram/watch.go
- pkg/apiserver/storage/ram/watch_test.go
We refactor the test to use a virtual clock. The modified test still validates that watcherAddTimeout is enforced correctly. The new version of the test also completes faster (<100ms instead of >500ms).
Fixes #5648
> Fix flaky TestRamStoreWatchTimeout in Windows CI

- pkg/agent/agent.go
- pkg/agent/agent_linux.go
- pkg/agent/agent_test.go
- pkg/agent/agent_windows.go
- pkg/agent/openflow/pod_connectivity.go
- pkg/agent/openflow/pod_connectivity_test.go
- pkg/agent/util/net_linux.go
- test/integration/agent/openflow_test.go
Fix #5451
Set arp_announce to 1 on Linux platform to make the ARP requests sent on the gateway
interface always use the gateway IP as the source IP, otherwise the ARP requests would be
dropped by ARP SpoofGuard flow.
> Set net.ipv4.conf.antrea-gw0.arp_announce to 1

- pkg/antctl/raw/multicluster/deploy/deploy_helper.go
- pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
If a resource to create already exists, the command `antctl mc deploy` will do nothing even when the manifests are changed. Revise the code to apply changes if there is any manifest update.
> Revise `antctl mc deploy` to support manifest update

- ci/check-manifest.sh
There was a new manifest "antrea-multicluster-leader.yml" added for Antrea Multi-cluster, but it's not added to the check list. So refine the code to check all manifests to avoid missing the new manifest.
> Check all multi-cluster manifests in check-manifest.sh

- pkg/agent/agent.go
- pkg/agent/agent_linux.go
- pkg/agent/agent_test.go
- pkg/agent/agent_windows.go
- pkg/agent/openflow/pod_connectivity.go
- pkg/agent/openflow/pod_connectivity_test.go
- pkg/agent/util/net_linux.go
- test/integration/agent/openflow_test.go
Cherry pick of #5657 on release-1.14.
#5657: Set net.ipv4.conf.antrea-gw0.arp_announce to 1
> Automated cherry pick of #5657: Set net.ipv4.conf.antrea-gw0.arp_announce to 1

- build/images/ovs/Dockerfile.windows
Use mcr.microsoft.com/powershell::lts-nanoserver-$nanoserver-version as the basic image to build OVS packages. The antrea/windows-ovs image size is reduced from 4.6GB to 596MB.
Fix: #5113
> Use Windows nanoserver to build image antrea/windows-ovs

- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/pipeline.go
- test/e2e/antreapolicy_test.go
- test/e2e/networkpolicy_test.go
Fix #5681
Network policy didn't work when using a server Pod to establish a connection to the service provided by itself. This hairpin service connection initiated through a local Pod will be SNATed to the gateway IP, which will prevent it from being correctly categorized by the network policy during the Ingress rule enforcement.
This commit added a bypass flow to always allow the hairpin service connection to address this issue. Given we don't consider self-access blocking to be a valid case.
> Fix NP not working on hairpin Service connection

- pkg/agent/controller/networkpolicy/cache.go
- pkg/agent/controller/networkpolicy/priority.go
- pkg/agent/controller/networkpolicy/priority_test.go
- pkg/agent/controller/networkpolicy/reconciler.go
- pkg/agent/controller/networkpolicy/reject.go
- pkg/agent/controller/networkpolicy/reject_test.go
Uncapitalize some consts, methods and type definitions since
they are never used outside of the package.
> Uncapitalize some words in pkg/agent/controller/networkpolicy

- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/pipeline.go
- test/e2e/antreapolicy_test.go
- test/e2e/networkpolicy_test.go
Cherry pick of #5687 on release-1.14.
#5687: Fix NP not working on Hairpin
> Automated cherry pick of #5687: Fix NP not working on Hairpin

- pkg/agent/controller/networkpolicy/packetin.go
- pkg/agent/flowexporter/connections/connections.go
- pkg/agent/flowexporter/connections/conntrack_connections.go
- pkg/agent/flowexporter/connections/deny_connections.go
- pkg/agent/flowexporter/connections/deny_connections_test.go
- pkg/agent/flowexporter/exporter/exporter_test.go
- test/e2e/bandwidth_test.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
1. Remove redundant logs in fillPodInfo/fillServiceInfo to avoid Flow
Exporter from flooding logs.
2. Add Mark field for deny connections. We were missing this field
previously, resulting in trying to fill service information for
non-service IPs.
3. Update the DestinationServiceAddress for deny connections when we can
find this information in PacketIn.
4. Update e2e/unit tests to verify that the Service-relateds field are
filled correctly.
Fixes #5573
> Remove redundant log in fillPodInfo/fillServiceInfo and update deny connection store.

- docs/antrea-network-policy.md
- test/e2e/networkpolicy_test.go
This is a follow-up PR of PR #5687.
1. Skip allowHairpinSerivce test when Antrea-Proxy is disabled.
2. Add documentation including the behavior of the hairpin service when Antrea-Proxy is enabled and disabled.
> Add Hairpin traffic limitation doc

- cmd/antrea-agent/agent.go
- pkg/util/lazy/lazy.go
- pkg/util/lazy/lazy_test.go
Instead of checking various conditions to determine whether localPodInformer should be initialized, which is error-prone and looks ugly, this patch adds a Generic interface for lazy evaluation and uses it to initialize localPodInformer when it's necessary.
> Lazily initialize localPodInformer in a more readable way

- pkg/antctl/raw/traceflow/command.go
- pkg/antctl/raw/traceflow/command_test.go
- pkg/controller/traceflow/validate.go
- pkg/controller/traceflow/validate_test.go
- test/e2e/traceflow_test.go
Update traceflow api to v1beta1 in antctl traceflow and traceflow e2e tests.
Fixes https://github.com/antrea-io/antrea/issues/5656
> Use Traceflow API v1beta1

- docs/antrea-network-policy.md
- test/e2e/networkpolicy_test.go
Cherry pick of #5705 on release-1.13.
#5705: Add Hairpin traffic limitation doc
> Automated cherry pick of #5705: Add Hairpin traffic limitation doc

- build/charts/antrea/crds/traceflow.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- pkg/agent/controller/traceflow/packetin.go
- pkg/agent/controller/traceflow/packetin_test.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
- pkg/apis/crd/v1beta1/types.go
- pkg/apiserver/openapi/zz_generated.openapi.go
- test/e2e/traceflow_test.go
Add NetworkPolicy rule name in Traceflow observation.
Update Traceflow e2e tests to verify "NetworkPolicy" and "NetworkPolicyRule"
in Traceflow observation.
> Add NetworkPolicy rule name in Traceflow observation

- go.mod
The version provided in the go directive must be a valid Go version. go1.21 refers to a development version of Go, not a released version. Prior to 1.21, 1.X was actually the first released version for Go language version 1.X. Starting with 1.21, the first released version is 1.X.0, and the go directive in go.mod should correspond to a valid toolchain version (unless a toolchain directive is also present).
One way to reproduce the issue is to run:
`GOTOOLCHAIN="go1.20+auto" go version`
When using the `go 1.21` directive, the above command will fail as go will try to download toolchain 1.21, which does not exist.
See https://github.com/golang/go/issues/62278 for a detailed discussion.
> Use correct go directive in go.mod file

- pkg/antctl/raw/traceflow/command.go
- pkg/antctl/raw/traceflow/command_test.go
- pkg/controller/traceflow/validate.go
- pkg/controller/traceflow/validate_test.go
- test/e2e/traceflow_test.go
Cherry pick of #5689 on release-1.14.
#5689: Use Traceflow API v1beta1
> Automated cherry pick of #5689: Use Traceflow API v1beta1

- build/images/Dockerfile.build.ubi
Starting with Go 1.21, the runtime system needs to have a version of glibc "compatible" with the version available at build time. The ubi8 image comes with a very old version of glibc compared to the golang builder, and the Antrea binaries no longer run.
To address this, we use the ubi8 image to build Antrea, which means we need to install Go manually.
Fixes #5722
> Fix antrea-ubi image build

- build/images/Dockerfile.build.ubi
git is required to compute the version string correctly
> Add git to antrea-build image for UBI build

- build/charts/antrea/README.md
- build/charts/antrea/templates/agent/daemonset.yaml
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
When running on some K8s distributions, users may want to adjust the securityContext for antrea-agent containers. This is reserved for "power users", and most users should not modify the default values. When modifying the securityContext, some Antrea functions may break.
For #5707
> Make Pod securityContext configurable in antrea Helm chart

- ci/jenkins/jobs/macros.yaml
- ci/kind/kind-setup.sh
Modify the kind builder script and destroy function in `kind-setup.sh` to perform correct kind cleanup.
If we create a kind cluster by using `kind-setup.sh` script then we should need to delete cluster using same script.
> Modify the kind builder script to perform correct kind cleanup

- cmd/antrea-agent/agent.go
- pkg/agent/controller/networkpolicy/cache.go
- pkg/agent/controller/networkpolicy/cache_test.go
- pkg/agent/controller/networkpolicy/filestore.go
- pkg/agent/controller/networkpolicy/filestore_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- test/e2e/networkpolicy_test.go
In the previous implementation, traffic from/to a Pod may bypass NetworkPolicies applied to the Pod in a time window when the agent restarts because realizing NetworkPolicies and enabling forwarding are asynchronous.
This patch stores NetworkPolicy data in files when they are received, and makes antre-agent fallback to use the files as data source if it can't connect to antrea-controller on startup. This prevents security regression: a NetworkPolicy that has been realized on a Node will continue to work even if antrea-controller is not available after antrea-agent restarts.
The benchmark results of the storage's operations are as below:
```
BenchmarkFileStoreAddNetworkPolicy-40              70383             16102 ns/op             520 B/op          9 allocs/op …
```
> Store NetworkPolicy in filesystem as fallback data source

- ci/jenkins/test-mc.sh
- ci/jenkins/test-rancher.sh
- ci/jenkins/test-vm.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
- ci/jenkins/utils.sh
Every time the Jenkins jobs are triggered, the jobs will check the Golang version on the testbed and compare with the Golang version in go.mod. If the Golang version is different, the jobs will automatically download and install newer Golang. (#5338)
> Automatically upgrade testbed golang version to antrea golang version

- README.md
Update zoom meeting for Antrea community meeting.
Also remove reference to Antrea live office hour call, but let event archive available.
> README: Update zoom meeting link.

- docs/getting-started.md
The same `kubectl apply` command that is used for first-time installation can also be used for upgrading to a more recent version.
Fixes #5695
> Clarify getting started doc for upgrade

- docs/kubernetes-installers.md
Starting with Antrea v1.15, Antrea can be used as the CNI for Talos clusters. This requires custom Helm values.
This support was tested using both the Docker provisioner and the QEMU provisioner.
Fixes #5707
> Add Talos to the K8s installers document

- test/e2e/flowaggregator_test.go
In this pull request, we:
1. Set a label to Perftest Pods before initiating traffic in each subtest to filter records in both the IPFIX collector Pod and the ClickHouse.
2. Remove the --since-time flag used during log retrieval from the IPFIX collector Pod in the e2e test.
3. Cease reliance on timestamps for record filtering due to potential time discrepancies between the testbed and Kubernetes nodes, which might hinder the retrieval of desired logs.
resolve #5730
> Use labels to enhance records filtering in FA e2e tests

- docs/egress.md
The commit covers AWS only, other clouds will be added after more experiments.
> Document Egress feature's options and usage on cloud

- CONTRIBUTING.md
Our container images have been using Ubuntu 22.04 for a while. I removed the reference to the Ubuntu version in the doc, so that we no longer need to update it in the future.
> Remove stale reference to Ubuntu 20.04 in CONTRIBUTING doc

- pkg/controller/networkpolicy/endpoint_querier.go
- pkg/controller/networkpolicy/endpoint_querier_test.go
The current endpoint querier rule index shows the index of the rule among all matched rules in the original policy for this endpoint.
This change updates the rule index to show the rule index among all rules in the original policy.
Fixes #5782
> Fix Endpoint Querier RuleIndex In Response

- pkg/controller/ipam/antrea_ipam_controller.go
- pkg/controller/ipam/antrea_ipam_controller_test.go
- pkg/ipam/poolallocator/allocator.go
- pkg/ipam/poolallocator/allocator_test.go
- test/e2e/antreaipam_test.go
Make IP pre-allocation working on StatefulSet.
> [flexible-ipam] Fix IP annotation not work on a StatefulSet

- cmd/antrea-agent/agent.go
- pkg/agent/agent.go
- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/util/wait/wait.go
- pkg/util/wait/wait_test.go
- test/e2e/networkpolicy_test.go
- test/integration/agent/cniserver_test.go
Pod network should only be enabled after realizing initial NetworkPolicies, otherwise traffic from/to Pods could bypass NetworkPolicy when antrea-agent restarts.
After commit f9fc979345bf ("Store NetworkPolicy in filesystem as fallback data source"), antrea-agent can realize either the latest NetworkPolicies got from antrea-controller or the ones got from filesystem as fallback. Therefore, waiting for NetworkPolicies to be realized should not add marked delay or make antrea-controller a failure point of Pod network.
This commit adds an implementation of wait group capable of waiting with a timeout, and uses it to wait for common initialization and NetworkPolicy realization before installing any flows for Pods. More preconditions can be added via the wait group if needed in the future.
> Enable Pod network after realizing initial NetworkPolicies

- test/e2e/antreapolicy_test.go
- test/e2e/k8s_util.go
Discovered the issue when adding extended test cases for ANNP in #5486.
Issue: calling `CreateOrUpdateANNP` with an updated annp would return an error `resourceVersion missing`, which is because the annp from builder.Get() does not contain the real annp meta data returned.
Solution: use the returned annp from Get, modify its spec to that of the new annp, call Update then.
> Fix E2E Util Update ANNP

- pkg/agent/cniserver/ipam/ipam_service.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_linux_test.go
- pkg/agent/cniserver/server_test.go
- pkg/agent/cniserver/server_windows_test.go
- pkg/agent/cniserver/testing/utils.go
Pod IP is recorded as OVS port attribute and used in Pod specific flows. If releasing Pod IP before deleting OVS port and flows, it could happen that multiple Pod ports and flows reference to the same Pod IP as the same time in some corner cases and lead to corrupted network.
This commit ensures all resources that reference to Pod IP are deleted before releasing the IP.
---
Thanks @antoninbas for suggesting this solution.
> Delete OVS port and flows before releasing Pod IP

- test/e2e/multicast_test.go
RunCommandOnNode should be avoided as much as possible, as it tends to make assumptions about software available on Nodes. In this case, we can run the same commands from the Antrea Agent Pod.
With this change, we can also remove some Kind-specific code.
> Remove usage of RunCommandOnNode for multicast e2e tests

- pkg/agent/proxy/proxier_test.go
- third_party/proxy/util/service.go
Since K8s 1.29, setting Local ExternalTrafficPolicy for ClusterIP Services with ExternalIPs is supported.
For #5792
> Support Local ExternalTrafficPolicy for Services with ExternalIPs

- pkg/agent/controller/trafficcontrol/controller.go
- pkg/agent/controller/trafficcontrol/controller_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/network_policy.go
- pkg/agent/openflow/network_policy_test.go
- pkg/agent/openflow/pod_connectivity.go
- pkg/agent/openflow/testing/mock_openflow.go
- pkg/agent/types/trafficcontrol.go
- test/integration/agent/openflow_test.go
When applying an L7NP to a Pod, there's a potential issue where creating a TrafficControl CR with a redirect action to the same Pod could bypass the L7 engine. This is due to the fact that both the ct mark `L7NPRedirectCTMark` for identifying L7NP packets and the reg mark `TrafficControlRedirectRegMark` for identifying TrafficControl redirect packets can be set together. In `OutputTable`, the priorities of flows to match the ct mark and the reg mark are the same. Without an additional condition to distinguish between them, packets with both the reg mark and ct mark may be matched by either flow with an equal chance. To rectify this and ensure proper L7NP enforcement, it is crucial to assign a higher priority to the flow that matches the ct mark L7NPRedirectCTMark.
This patch also adds an …
> Prioritize L7NP flows over TrafficControl

- ci/kind/test-e2e-kind.sh
The common images for flow-visibility were not pulled beforehand.
This PR changes it to pull the images before running "go test"
> Pull flow-visibility common images

- pkg/agent/cniserver/interface_configuration_linux_test.go
- pkg/agent/cniserver/pod_configuration_linux_test.go
- pkg/agent/cniserver/server_linux_test.go
- pkg/agent/cniserver/server_test.go
- pkg/agent/cniserver/server_windows_test.go
- pkg/util/ip/ip.go
cniServer.reconcile() now installs flows asynchorously.
Fixes #5796
> Fix unit test TestReconcile

- hack/.md_links_config.json
Checking these links keep failing in Github Actions with an HTTP 500 code. I have noticed that when I try to access https://www.wireguard.com from my corporate network, it also fails (connection reset). When I access it from home, it works fine...
> Ignore wireguard.com links in markdown link checker

- ci/jenkins/test.sh
- cmd/antrea-agent/agent.go
- docs/external-node.md
- docs/multicast-guide.md
- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/multicast/mcast_route.go
- pkg/agent/multicast/mcast_route_linux.go
- pkg/agent/multicast/mcast_route_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/multicast.go
- pkg/agent/openflow/multicast_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/testing/mock_openflow.go
- test/e2e/antreaipam_anp_test.go
- test/e2e/antreaipam_test.go
- test/e2e/antreapolicy_test.go
- test/e2e/multicast_test.go
When FlexibleIPAM is enabled for the cluster, inbound multicast traffic will
be forwarded to MulticastRoutingTable. Outbound multicast traffic will
forward to local ports, the uplink interface, and the host interface.
> [Multicast] Add Support for FlexibleIPAM

- build/charts/antrea/crds/clusternetworkpolicy.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- multicluster/build/yamls/antrea-multicluster-leader-global.yml
- multicluster/build/yamls/antrea-multicluster-leader.yml
- multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceexports.yaml
- multicluster/config/crd/bases/multicluster.crd.antrea.io_resourceimports.yaml
- pkg/apis/crd/v1beta1/types.go
- pkg/apis/crd/v1beta1/zz_generated.deepcopy.go
- pkg/apiserver/openapi/zz_generated.openapi.go
- pkg/controller/networkpolicy/adminnetworkpolicy.go
- pkg/controller/networkpolicy/antreanetworkpolicy.go
- pkg/controller/networkpolicy/clusternetworkpolicy.go
- pkg/controller/networkpolicy/clusternetworkpolicy_test.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
> Add Controlplane changes for NodeNetworkPolicy

- build/images/base-windows/Dockerfile
Recently, the curl is not working in github workflow and failed to build base Windows images. Replace the curl with `Invoke-WebRequest` to bypass the issue.
> Replace curl with built-in Invoke-WebRequest on Windows

- ci/jenkins/test.sh
- pkg/agent/util/net_windows.go
- pkg/agent/util/net_windows_test.go
To address the potential race condition issue where acquiring a DHCP IP address may fail after CreateHNSNetwork,
we added a retry mechanism to wait for an available IP. If the DHCP IP cannot be acquired within six seconds,
an error will be logged.
> Add DHCP IP Retries in PrepareHNSNetwork

- build/charts/antrea/templates/agent/clusterrole.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- pkg/agent/controller/serviceexternalip/controller.go
- pkg/agent/ipassigner/ip_assigner.go
- pkg/agent/ipassigner/ip_assigner_linux.go
- pkg/agent/ipassigner/testing/mock_ipassigner.go
- test/e2e/egress_test.go
- test/integration/agent/ip_assigner_linux_test.go
Fixes #4614.
Record event when EgressIP is assigned to the Node interface.
> Record an event when Egress IP assignment changes

- pkg/agent/route/route_linux.go
Although it has been documented as a prerequisite in [1], there are some platforms not enabling ip forwarding by default. kube-proxy ipvs mode and some CNIs enable it by themselves to ensure Pod networking work properly.
As Antrea needs IP forwarding to be enabled, there seems no reason to not do it by itself, rather than expecting users or other components to do it.
[1] https://kubernetes.io/docs/setup/production-environment/container-runtimes/#install-and-configure-prerequisites
For https://github.com/vmware/antrea-operator-for-kubernetes/issues/98
> Enable IPv4/IPv6 forwarding on demand automatically

- ci/jenkins/test.sh
- pkg/agent/util/net_windows.go
- pkg/agent/util/net_windows_test.go
Cherry pick of #5819 on release-1.13.
#5819: Add DHCP IP Retries in PrepareHNSNetwork
> Automated cherry pick of #5819: Add DHCP IP Retries in PrepareHNSNetwork

- go.mod
- test/e2e/traceflow_test.go
improvement for #5760. It's not easy to reproduce the failed case for now, so added more detailed packet structure for the future usage.
> Add detailed packet structure info output for traceflow test.

- hack/windows/Install-OVS.ps1
Cherry pick of #5839 on release-1.13.
#5839: Update windows ovs download link to remove the redundant
> Automated cherry pick of #5839: Update windows ovs download link to remove the redundant

- docs/cookbooks/multus/README.md
The current link is dead as man.openbsd.org is down for maintenance and there is not ETA for it coming back up. I don't think there was any reason to point to OpenBSD documentation in the first place.
> Change doc link for dhcpd.conf in Multus cookbook

- .github/workflows/docker_update_base_windows.yml
- .github/workflows/trivy_scan.yml
Use recommended 'inputs' context in github workflows to fix the if condition check.
> Use recommended 'inputs' context in github workflows

- CONTRIBUTING.md
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
For #5641
* Remove all windows docker jobs.
* Rename the trigger phases of all Windows containerd jobs to normal Windows trigger phases.
* Remove windows proxyall job as we have set this feature as the default value in agent.
> Update Windows Jenkins Jobs to Remove Docker Testbed

- pkg/agent/apiserver/handlers/ovstracing/handler.go
- pkg/agent/apiserver/handlers/ovstracing/handler_test.go
- pkg/ovs/ovsctl/appctl.go
- pkg/ovs/ovsctl/ovsctl.go
Fix the following error when running `antctl trace-packet`, which is caused by missing arguments for ovs-appctl command.
```
syntax error at br-int (or the bridge name was omitted)
ovs-appctl: /var/run/openvswitch/ovs-vswitchd.103.ctl: server returned an error
```
Fixes #5831
> Fix antctl trace-packet arguments missing issue

- hack/windows/Prepare-Node.ps1
There was no space before `--cert-dir`. As a result, the command-line arg had no effect and kubelet could not start.
Fixes #5857
> Add missing space for kubelet args in Prepare-Node.ps1

- hack/windows/Prepare-Node.ps1
Cherry pick of #5858 on release-1.13.
#5858: Add missing space for kubelet args in Prepare-Node.ps1
> Automated cherry pick of #5858: Add missing space for kubelet args in Prepare-Node.ps1

- hack/windows/Clean-AntreaNetwork.ps1
- hack/windows/Prepare-AntreaAgent.ps1
In "containerized OVS" mode, Clean-AntreaNetwork.ps1 should be invoked with `-OVSRunMode "container"`.
Fixes #5852
> Fix Clean-AntreaNetwork.ps1 invocation in Prepare-AntreaAgent.ps1

- hack/windows/Clean-AntreaNetwork.ps1
- hack/windows/Prepare-AntreaAgent.ps1
Cherry pick of #5859 on release-1.14.
#5859: Fix Clean-AntreaNetwork.ps1 invocation in
> Automated cherry pick of #5859: Fix Clean-AntreaNetwork.ps1 invocation in

- pkg/agent/apiserver/handlers/ovstracing/handler.go
- pkg/agent/apiserver/handlers/ovstracing/handler_test.go
- pkg/ovs/ovsctl/appctl.go
- pkg/ovs/ovsctl/ovsctl.go
Cherry pick of #5838 on release-1.14.
#5838: Fix antctl trace-packet arguments missing issue
> Automated cherry pick of #5838: Fix antctl trace-packet arguments missing issue

- docs/antrea-l7-network-policy.md
- docs/antrea-network-policy.md
- docs/design/ovs-pipeline.md
- docs/external-node.md
- docs/multicluster/user-guide.md
Cherry pick of #5830 on release-1.14.
#5830: Update NetworkPolicy version to v1beta1 in documents
> Automated cherry pick of #5830: Update NetworkPolicy version to v1beta1 in documents

- .github/workflows/build.yml
- Makefile
- build/images/Dockerfile.build.migrator
- build/images/scripts/migrate_cni
- build/yamls/antrea-migrator.yml
- docs/migrate-to-antrea.md
- hack/.notableofcontents
A new image "antrea-migrator" is responsible for restarting all Pods on each Nodes. It is a DaemonSet that tries to kill sandboxes to restart the Pods in-place. In this way, the cluster could be migrated from old CNIs to Antrea.
> Add script for migrating from other CNI to Antrea

- docs/design/windows-design.md
- docs/windows.md
The user-facing Windows document is updated as follows:
* containerd will be the only supported container runtime on Windows Nodes, Docker support (that includes cri-dockerd, Docker Desktop) is officially deprecated.
* we split the "Installation as Pod" section into 2 new sections (one for containerd, one for Docker).
* installation methods are re-ordered, starting with the recommended / most common one: Installation as a Pod for containerd, Installation as Windows services, Installation as a Pod for Docker (deprecated).
The main idea is to make the installation instructions clearer and easier to follow for a "normal" user, deploying the latest Antrea version on a recent K8s cluster. In this situation, the recommended installation method is to use antrea-windows-containerd.yml or …
> Update Windows documentation

- test/e2e/tls_test.go
TestAntreaApiserverTLSConfig, this e2e test requires the openssl command to be installed in antrea-controller and antrea-agent pod, but adding openssl library to the antrea-controller image unnecessarily increases the size of the antrea-controller image, so I have leveraged the the openssl library which is already installed in the antrea-agent image to perform the e2e test.
> Remove the dependency of openssl library in antrea-controller image

- build/charts/antrea/README.md
- build/charts/antrea/values.yaml
- docs/multicluster/user-guide.md
* Indicate that cross-cluster WireGuard is not compatible with in-cluster encryption.
* Indicate that Multi-cluster Gateway is not compatible with in-cluster WireGuard.
* Remove stale information from Helm doc about "encap" mode being required for Multi-cluster Gatway.
> Some minor updates to Multi-cluster documentation

- pkg/agent/config/node_config.go
When using Wireguard for inter-Node traffic, there is no need to create the OVS tunnel port (antrea-tun0) interface, as traffic will go through antrea-wg0, which is managed by Linux directly.
The exception is when using Multi-cluster (in gateway mode), as antrea-tun0 is then still used for cross-cluster traffic, for example to tunnel traffic from the source Node to the local gateway Node.
Fixes #5869
> Don't create tunnel interface (antrea-tun0) when using Wireguard

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
Recently an issue was raised in the Kubernetes Antrea channel, where @krobbo sees very frequent reconciliations of the same FQDN rule in very short succession. It was also disclosed that the specific rule in questions contains several FQDN selectors, and the FQDNs are S3 endpoints which have dynamic IPs and relatively short TTL. 
From the logs excerpts, I found that for some DNS response handling, the FQDN controller actually reconciles the same rule immediately after it finishes syncing in datapath:
```
4914 I0106 10:43:51.785381       1 networkpolicy_controller.go:663] "Rule realization was done" ruleID="e7b262670e58c0ee"
4915 I0106 10:43:51.785408       1 networkpolicy_controller.go:619] "Finished syncing rule" ruleID="e7b262670e58c0ee" duration="4.593564ms"
4916 I0106 10:43:51.785430 …
```
> Fix redundant reconciles in FQDN controller

- pkg/agent/agent_windows.go
- pkg/agent/util/net_windows.go
The current windows agent initialization couldn't guarantee that the `EnableHNSNetworkExtension` was executed after creating the HNS network.
In certain corner cases where the Windows agent pod was restarted after creating HNS network, the agent might miss executing `EnableHNSNetworkExtension`.
To address this issue, this enhancement runs `EnableHNSNetworkExtension` even if the HNS network has been created, which ensures the OVS Extension is properly enabled.
> Enhance HNS network initialization

- ci/kind/test-e2e-kind.sh
In this PR, we increase the timeout from 20m to 30m for flow-visibility e2e test.
> Increase timeout for flow-visibility e2e test

- test/e2e/traceflow_test.go
Packet dropped by K8s NetworkPolicy default drop rule has never been associated with any specific K8s NetworkPolicy. The expectation added by commit 68b5a027320e ("Add NetworkPolicy rule name in Traceflow observation ") is wrong.
> e2e: Fix the wrong expectation of Traceflow observation

- pkg/agent/openflow/client.go
- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pod_connectivity.go
- pkg/agent/openflow/pod_connectivity_test.go
After merging #5885, the OVS tunnel port is no longer created when enabling WireGuard, as it is not being used. However, we were still trying to install flows referencing the tunnel port. Even though the port was non-existent, flow creation would succeed, but the condition matching on the tunnel port was being dropped silently. This would lead to invalid datapath behavior. We update the code to prevent installing these invalid flows when WireGuard is enabled.
Fixes #5905
> Remove invalid flow when WireGuard is enabled

- docs/aks-installation.md
AKS has supported a "Bring Your Own CNI" mode for a while now: https://learn.microsoft.com/en-us/azure/aks/use-byo-cni?tabs=azure-cli
With this support, Antrea can easily be installed in encap mode in AKS clusters, with no limitation (unlike for EKS where there is no more connectivity from the control-plane to the Nodes). The only requirement is to enable Antrea NodeIPAM.
This support relies on the
[Konnectivity Service](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/), which is deployed by default in "recent" AKS versions, and guarantees connectivity from the control-plane to the Nodes, regardless of which CNI is used.
Fixes #5817
> Add instructions to install Antrea in encap mode in AKS

- .github/workflows/kind.yml
It is no longer possible to use geekyeggo/delete-artifact (since v4) for workflows triggered by pull request events, without using a PAT directly. Instead of depending on a 3rd party action, we now use actions/upload-artifact to overwrite the large artifacts with an empty file.
> Fix artifact cleanup in Kind workflow

- cmd/antrea-agent/agent.go
- pkg/agent/agent.go
- pkg/agent/config/node_config.go
- pkg/agent/config/node_config_test.go
- pkg/agent/multicluster/mc_route_controller.go
- test/e2e-secondary-network/secondary_network_test.go
- test/e2e/antreaipam_test.go
- test/e2e/connectivity_test.go
- test/e2e/framework.go
- test/e2e/ipsec_test.go
- test/e2e/traceflow_test.go
- test/e2e/upgrade_test.go
- test/e2e/vmagent_test.go
- test/e2e/wireguard_test.go
The commit fixes 3 incorrect MTU configurations:
1. When using the WireGuard encryption mode, the Pod eth0's MTU was not correct. The MTU deducted Geneve overhead because the default tunnel type is Geneve while it should deduct the WireGuard overhead as traffic will be encrypted instead of encapsulated.
2. When using the GRE tunnel type, the Pod eth0's MTU was not correct. The actual overhead is 14 outer MAC, 20 outer IP, and 8 GRE header (4 standard header + 4 key field), summing up to 42 bytes.
3. When enabling Wireguard for Multicluster, the MTU of all Pod interfaces and wireguard interface were reduced 130 bytes (50 for geneve + 80 for wireguard), however, cross-cluster traffic sent from Pods were not forwarded by wireguard interface. This is because traffic originated from Pods will …
> Fix incorrect MTU configurations

- ci/jenkins/test.sh
Update Ginkgo configuration to enable running test in parallel.
This optimization reduces the execution time for the windows networkpolicy job:
windows-networkpolicy: 95 min -> 56 min
> Support running Ginkgo in parallel on Windows testbeds 

- pkg/agent/wireguard/client_linux.go
- pkg/agent/wireguard/client_test.go
In ce46eb1e2cde ("Fix incorrect MTU configurations"), we changed WireGuard interface's MTU in IPv4 case. However, if a cluster already enables WireGuard, the WireGuard interface's MTU would remain unchanged while new Pod would use a higher MTU, causing problems.
> Ensure MTU is set correctly when WireGuard interface already exists

- hack/cherry-pick-pull.sh
cherry_pick_pull.sh was copied from Kubernetes which allows merge commits. It makes sense to cherry pick original commits for Kubernetes because the original commits can be found in both master and release branches. However, Antrea uses squash merging at the most time, cherry-picking original commits would cause inconsistency between master and release branches. The commit changes to cherry pick the merge commit.
> Cherry pick merge commit instead of original commits

- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/service_test.go
```
1. table=NodePortMark, priority=200,ipv6,nw_dst=::1 actions=set_field:0x80000/0x80000->reg4"
2. table=NodePortMark, priority=200,ip,nw_dst=127.0.0.1 actions=set_field:0x80000/0x80000->reg4
3. table=NodePortMark, priority=200,ip,nw_dst=192.168.77.102 actions=set_field:0x80000/0x80000->reg4
4. table=NodePortMark, priority=200,ip,nw_dst=172.17.0.1 actions=set_field:0x80000/0x80000->reg4
5. table=NodePortMark, priority=200,ip,nw_dst=169.254.0.252 actions=set_field:0x80000/0x80000->reg4
6. table=NodePortMark, priority=0 actions=goto_table:SessionAffinity
```
In table NodePortMark:
- Flows 1-2, which were intended to match NodePort traffic from local Pods to loopback IP addresses, have been removed as they are never used.
- Flows 3-5 are kept intact, as they are intended to match NodePort …
> Remove flows which are never used

- CHANGELOG/README.md
Cherry pick of #5934 on release-1.15.
#5934: Add a link to CHANGELOG-1.15 (#5934)
> Automated cherry pick of #5934: Add a link to CHANGELOG-1.15 (#5934)

- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_test.go
- test/e2e/wireguard_test.go
Mutlicast feature can't work with WireGuard or IPSec configurations with encap mode. It will return error when Multicast feature gate is enabled and either Wireguard or IPSec is configured in the initial validations.
Fix: #5916
> [Multicast] Add precheck on the encryption mode configurations

- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/pod_configuration_linux.go
- pkg/agent/cniserver/pod_configuration_windows.go
Define separate configureInterfaces funcs for Linux and Windows respectively. The Windows implementation first checks if the container interface has already been created for the infra container, and if yes returns the interfaces based on the information in the interface store.
> Refactor Windows CNI interface configuration

- README.md
- ROADMAP.md
Node NetworkPolicies and support for Egress IPs in different subnets (with VLAN tagging) have been added in the latest Antrea v1.15 release, so removing these items from the ROADMAP.
> Update ROADMAP doc after Antrea v1.15 release

- .github/workflows/codeql.yml
There was an alert in the repository:
> To avoid interfering with the CodeQL analysis, perform all installation steps
before calling the github/codeql-action/init Action.
> Install Go before CodeQL initialization in workflow

- ci/jenkins/test-mc.sh
- ci/jenkins/test-rancher.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
- ci/jenkins/utils.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
- docs/minikube.md
- hack/build-antrea-linux-all.sh
* Add BuildKit cache cleanup in CI
* Declare DOCKER_BUILDKIT when building image for docker compatibility.
fixes https://github.com/antrea-io/antrea/issues/5941
> Update BuildKit configurations to enhance compatibility

- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
It may happen that a Traceflow is assigned with a tag that was just released from an old Traceflow but the controller hasn't processed the deletion event of the old Traceflow yet. Previously the controller skipped starting new Traceflow if the tag was already being used, which caused the Traceflow to timeout.
The commit adds a check when determining whether it should start a Traceflow. If the tag is associated with another Traceflow, it will clean it up then start a new trace for the current one.
It also fixes a bug in cleanupTraceflow, which might uninstall flows for another Traceflow if the tag is reassigned.
Fixes #5760
Fixes #5609
> Fix race condition in agent Traceflow controller

- docs/kind.md
Added the direct GitHub link to the e2e tests page instead of a relative link in the Kind documentation according to the discussions with @tnqn
> Fixed relative link in Kind documentation

- pkg/agent/cniserver/interface_configuration_linux.go
- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/server.go
Came accross some typos in in pkg `cniserver` while code-reading.
> pkg/agent/cniserver: fix typos in comments

- Makefile
- hack/build-antrea-linux-all.sh
Some test scripts call `make` to build test images. Also, as the most used make target, it should build the most frequently used images, not the legacy image.
Remove "--skip-unified-image" from build-antrea-linux-all.sh as it's never used and the script is meant to build all images.
> make should build antrea-agent-ubuntu and antrea-controller-ubuntu

- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.agent.ubuntu
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubi
- build/images/Dockerfile.build.controller.ubuntu
- build/images/Dockerfile.build.coverage
- build/images/Dockerfile.build.ubi
- build/images/Dockerfile.build.ubuntu
By sharing more common layers, the total time can be reduced about 15s.
> Make intermediate images share more common layers

- test/e2e/README.md
In `./test/e2e/README.md` there was a minor error in the go test `timeout` flag. I believe the intended timeout is 75 minutes.
> Fix go test `timeout` flag in e2e tests README

- docs/helm.md
There was a disclaimer in the documentation that the Helm installation method was still considered "Alpha".
We now consider this installation method stable, and we remove the disclaimer for the Antrea v2.0 release.
For #4832
> Graduate Helm support

- pkg/agent/agent.go
OVS configures the MTU for tunnel ports to 65000.
In some cases (e.g., Kind clusters), the MTU of the transport interface can be larger than that, and so can be the calculated MTU of antrea-gw0 and of Pod interfaces. When this happens, packets can be dropped. To handle this edge case (real clusters are unlikely to use that kind of MTU), we set an upper bound of 65000 for the calculated MTU.
Note that setting the tunnel port's MTU to 65535, or even to the calculated MTU, is not an option, as it may not work on all systems.
An alternative would be to find the MTU for the tunnel interface dynamically and use that as an upper bound, rather than rely on this hardcoded constant (65000). However, that constant has remained unchanged for 7 years, and finding the MTU dynamically would require …
> Use 65000 MTU upper bound for interfaces in encap mode

- pkg/agent/apiserver/handlers/ovsflows/handler.go
- pkg/agent/apiserver/handlers/ovsflows/handler_test.go
- pkg/agent/openflow/pipeline.go
- pkg/antctl/antctl.go
- pkg/antctl/command_definition.go
- pkg/antctl/command_definition_test.go
Add a new flag to print OVS table names only.  Fixes #5810
```
./antctl get ovsflows --table-names-only
ARPResponder
ARPSpoofGuard
AntreaPolicyEgressRule
AntreaPolicyIngressRule
Classifier
ConntrackCommit
ConntrackState
ConntrackZone
EgressDefaultRule
EgressMark
EgressMetric
EgressRule
EndpointDNAT
IngressDefaultRule
IngressMetric
IngressRule
IngressSecurityClassifier
L2ForwardingCalc
L3DecTTL
L3Forwarding
Output
PipelineRootClassifier
PreRoutingClassifier
SNAT
SNATMark
ServiceLB
SessionAffinity
SpoofGuard
UnSNAT
```
> Add a flag for antctl to print OVS table names only

- build/charts/antrea/README.md
- build/charts/antrea/templates/agent/daemonset.yaml
- build/charts/antrea/values.yaml
- build/images/scripts/install_cni
- build/images/scripts/install_cni_chaining
- build/images/scripts/module_utils
- build/images/scripts/start_ovs
If a module is built-in, trying to load the module with modprobe inside a container may fail (insted of just being a no-op). This will cause Antrea initialization to fail unless agent.dontLoadKernelModules is explicitly set to true.
Now that the Docker Desktop LinuxKit VM comes with openvswitch built-in (starting with 4.27.0), trying to install "default" Antrea (i.e., without setting agent.dontLoadKernelModules) in a Kind cluster running with Docker Desktop on macOS will fail. To make sure that users will not run into this issue, we add logic to the install_cni script to skip the modprobe call if the module is built-in.
After this change, there should be very limited use cases for the agent.dontLoadKernelModules parameter, but there is no harm in keeping in case it is needed in the future …
> Skip loading openvswitch Kernel module if built-in

- build/charts/antrea/templates/controller/clusterrole.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- pkg/apiserver/apiserver.go
These APIServices were removed in Antrea v1.6 and it's safe to assume none of them still exists in the cluster when deploying the upcoming Antrea v2.0.
> Clean up deprecated APIServices

- Makefile
- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.agent.ubuntu
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubi
- build/images/Dockerfile.build.controller.ubuntu
- build/images/Dockerfile.build.coverage
- build/images/Dockerfile.build.ubi
- build/images/Dockerfile.build.ubuntu
- hack/release/prepare-assets.sh
Instead of selectively disabling cgo for some binaries (e.g., release
assets), we now unconditionally disable cgo for all binaries, even those
that only run inside the container image for which they were built
(e.g., antrea-controller). After some analysis, there seems to be no
downside in doing this. We also get some benefits such as reduced build
time for the default make command.
Fixes #5724
> Disable cgo for all Antrea binaries

- test/e2e/vmagent_test.go
Fix the TestVMAgent/testExternalNodeSupportBundleCollection test. The test case was not updated correctly after #5538 was merged.
> [e2e test] Fix TestVMAgent

- go.mod
- go.sum
- pkg/agent/openflow/multicast.go
- pkg/agent/openflow/multicast_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pipeline_test.go
- pkg/ovs/openflow/ofctrl_group.go
The current implementation limits the maximum number of buckets in an OVS group
add/insert_bucket message to 800. This constraint is based on the fact that each
bucket has 3 actions, such as `set_field:0xa0a0007->reg0`,
`set_field:0x50/0xffff->reg4`, and `resubmit(,EndpointDNAT)`. However, an update
in #5205 introduced a new action, `set_field:0x4000000/0x4000000->reg4`, for
remote Endpoints, making it impossible to accommodate 800 buckets with 4 actions
in an OVS group add/insert_bucket message.
To overcome the limitation, we set the maximum number of buckets to 700, considering
the worst-case scenario where each bucket includes all available actions. For example,
a bucket with all available actions, which is for a remote non-hostNetwork IPv6 Service
Endpoint like this: …
> Update maximum number of buckets in OVS group add/insert_bucket message

- build/charts/antrea/README.md
- build/charts/antrea/templates/agent/daemonset.yaml
- build/charts/antrea/values.yaml
- build/images/scripts/install_cni
- build/images/scripts/install_cni_chaining
- build/images/scripts/module_utils
- build/images/scripts/start_ovs
Cherry pick of #5979 on release-1.15.
#5979: Skip loading openvswitch Kernel module if built-in (#5979)
> Automated cherry pick of #5979: Skip loading openvswitch Kernel module if built-in (#5979)

- test/e2e/antreapolicy_test.go
- test/e2e/k8s_util.go
- test/e2e/nodenetworkpolicy_test.go
When ACNPCustomTiers deletes Tiers after deleting ACNPs, it sometimes failed because antrea-controller hadn't received the deletion events of ACNPs yet, for example:
```
antreapolicy_test.go:96] unable to delete tier high-priority: admission webhook "tiervalidator.antrea.io" denied the request: tier high-priority is referenced by 1 Antrea ClusterNetworkPolicies
```
However, there is no good solution to achieve strong consistency when executing validating webhook so far. The patch fixes the e2e test by retrying a few times when meeting the specific error.
Incidentally, it simplifies some utility functions.
> Fix flaky e2e ACNPCustomTiers

- ci/jenkins/test-mc.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
If same image REPOSITORY has different TAG then the cmd `docker images | grep 'antrea' | awk '{print $3}' | xargs -r docker rmi || true` will not work because you can't delete it with imageID if they referencing in multiple repositories.  in this case either we can use `-f` flag OR  delete images with tag (FullName).
:~$ docker images
REPOSITORY                                   TAG                         IMAGE ID       CREATED        SIZE
antrea/antrea-ubuntu                         latest                      138fdae0c1ea   2 days ago     506MB
antrea/antrea-ubuntu                         v2.0.0-dev-96926ede.dirty   138fdae0c1ea   2 days ago     506MB
antrea/antrea-agent-ubuntu                   latest                      6a04b1bc593a   2 days ago     416MB
antrea/antrea-agent-ubuntu …
> Refactoring docker cmd to remove dangling images on testbed.

- test/e2e/antreapolicy_test.go
- test/e2e/basic_test.go
- test/e2e/batch_test.go
- test/e2e/connectivity_test.go
- test/e2e/egress_test.go
- test/e2e/fixtures.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
- test/e2e/infra/vagrant/playbook/roles/common/tasks/busybox.yml
- test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml
- test/e2e/networkpolicy_test.go
- test/e2e/proxy_test.go
- test/e2e/service_test.go
- test/e2e/wireguard_test.go
> [tests/e2e]: Remove all references of busybox in e2e tests

- pkg/controller/certificatesigningrequest/approving_controller.go
- pkg/controller/certificatesigningrequest/ipsec_csr_approver.go
- pkg/controller/certificatesigningrequest/ipsec_csr_approver_test.go
fix: #5990
* added a function `getAntreaAgentServiceAccount()` which fixes the warnings outside k8s
`kubectl exec -it antrea-controller-6b554d9c74-l9ms2 -n kube-system -- /bin/bash
root@kind-worker:/# antrea-controller --version`
`antrea-controller version v2.0.0-dev-43ee1f47 linux/amd64 go1.21.7`
`docker run antrea/antrea-controller-ubuntu:v2.0.0-dev-43ee1f47 antrea-controll
er --version
antrea-controller version v2.0.0-dev-43ee1f47 linux/amd64 go1.21.7`
> bug: fixing `running antrea-controller --version "outside of K8s" print warnings `

- pkg/agent/agent.go
Cherry pick of #5997 on release-1.14.
#5997: Use 65000 MTU upper bound for interfaces in encap mode
> Automated cherry pick of #5997: Use 65000 MTU upper bound for interfaces in encap mode

- test/e2e/connectivity_test.go
- test/e2e/framework.go
- test/e2e/tls_test.go
An explicit sleep is not required as the default command in the container is already "pause".
The Windows version of the toolbox image will not start when using "sleep", as the command is not available.
Even on Linux, pause is superior to sleep for signal handling.
> [e2e tests] Remove explicit sleep command for toolbox containers

- pkg/apiserver/certificate/selfsignedcert_provider.go
- pkg/apiserver/certificate/selfsignedcert_provider_test.go
There was some "interference" between TestSelfSignedCertProviderRotate and TestSelfSignedCertProviderRun. The root cause is that the certutil.GenerateSelfSignedCertKey does not support a custom clock implementation and always calls time.Now() to determine the current time. It then adds a year to the current time to set the expiration time of the certificate. This means that when rotateSelfSignedCertificate() is called as part of TestSelfSignedCertProviderRotate, the new certificate is already expired, and rotateSelfSignedCertificate() will be called immediately a second time. By this time however, TestSelfSignedCertProviderRotate has already exited, and we are already running the next test, TestSelfSignedCertProviderRun. This creates a race condition because the next test will overwrite …
> Fix race condition in pkg/apiserver/certificate unit tests

- go.mod
- go.sum
- pkg/agent/openflow/multicast.go
- pkg/agent/openflow/multicast_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pipeline_test.go
- pkg/ovs/openflow/ofctrl_group.go
Cherry pick of #5942 on release-1.15.
#5942: Update maximum number of buckets in an OVS group message
> Automated cherry pick of #5942: Update maximum number of buckets in an OVS group message

- docs/antrea-ipam.md
- docs/secondary-network.md
- hack/.notableofcontents
> Add user document for Antrea native secondary network support

- .github/workflows/build.yml
- Makefile
- build/images/base/build.sh
- build/images/build-utils.sh
- build/images/ovs/build.sh
- hack/build-antrea-linux-all.sh
We use "docker buildx" when building the base Linux images for Antrea. This gives us access to all the BuildKit capabilities, in particular exporting the build cache to the registry as a separate image, when using the docker-container driver. Exporting the cache means that the base images won't need to be rebuilt from scratch every time (whether it is for local builds or CI builds).
Using buildx with Docker requires Docker Engine 19.03 or newer, but that version came out in 2019. Note that we already require buildx / BuildKit since merging https://github.com/antrea-io/antrea/pull/5918.
Note that in recent Docker versions (starting with Docker Engine 23.0 and Docker Desktop 4.19), "docker build" is an alias for "docker buildx build" (buildx is the default build client). However, explicitly …
> Use docker buildx to build base Linux images

- docs/antrea-l7-network-policy.md
- pkg/agent/controller/networkpolicy/l7engine/reconciler.go
For allowed http traffic, log in "eve-YYYY-MM-DD.json" shows `event_type: http`
```
{"timestamp":"2024-02-22T21:26:07.074791+0000","flow_id":757085628206447,"in_iface":"antrea-l7-tap0","event_type":"http","vlan":[1],"src_ip":"10.10.1.8","src_port":44132,"dest_ip":"10.10.1.7","dest_port":80,"proto":"TCP","tx_id":0,"http":{"hostname":"10.10.1.7","url":"/public/main.html","http_user_agent":"Wget/1.21.1","http_content_type":"text/html","http_method":"GET","protocol":"HTTP/1.1","status":404,"length":153}}
```
For dropped packets, `event_type: alert` and `event_type: packet` are stilled logged as before.
```
{"timestamp":"2024-02-22T21:26:26.141099+0000","flow_id":647971985302376,"in_iface":"antrea-l7-tap0","event_type":"alert","vlan":[1],"src_ip":"10.10.1.8","src_port":58174,"dest_ip":"10.10.1. …
```
> Add L7 Network Policy Logs for Allowed HTTP

- cmd/antrea-agent/options.go
- docs/node-port-local.md
- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_others_test.go
- pkg/agent/nodeportlocal/rules/iptable_rule.go
- pkg/agent/nodeportlocal/rules/iptable_rule_test.go
- pkg/agent/nodeportlocal/rules/types.go
- pkg/agent/nodeportlocal/testing/annotations.go
- pkg/agent/nodeportlocal/types/types.go
- pkg/config/agent/config.go
- test/e2e/nodeportlocal_test.go
> NPL code tidy-up for Antrea v2.0

- pkg/agent/secondarynetwork/podwatch/sriov.go
- pkg/agent/util/net.go
- pkg/agent/util/net_linux.go
- pkg/agent/util/net_windows.go
- pkg/cni/client.go
- pkg/cni/dial_linux.go
- pkg/cni/dial_windows.go
It only needs a dial function but imports many unnecessary code from `pkg/agent/util`.
Removing the import reduces the binary size by 10MB, from 18MB to 8.4MB.
For https://github.com/antrea-io/antrea/issues/5883
----------
Before:
```
-rwxr-xr-x  1 root root  18M Feb 29 10:10 antrea-cni
antrea/antrea-agent-ubuntu                v2.0.0-dev-d28e282d0   7e84ada052f8   15 seconds ago   350MB
```
After:
```
-rwxr-xr-x  1 root root 8.4M Feb 29 10:19 antrea-cni
antrea/antrea-agent-ubuntu                v2.0.0-dev-d28e282d0.dirty   36526d98148d   18 seconds ago   340MB
```
> Reduce antrea cni binary size

- ci/kind/test-upgrade-antrea.sh
In particular, when testing upgrade from a minor version already using split images (e.g., 1.15.0), we should not pull the unified image and load it into the K8s Nodes, as it won't be used.
This should help reduce disk usage of the Kind cluster in CI.
> Do not load unnecessary images in ci/kind/test-upgrade-antrea.sh

- docs/secondary-network.md
At the moment, we do not support annotation update / deletion for `k8s.v1.cni.cncf.io/networks`.
> Add important limitation to SecondaryNetwork document

- ci/kind/test-secondary-network-kind.sh
- test/e2e-secondary-network/secondary_network_test.go
For VLAN Secondary Network e2e tests, we need to wait for secondary IPs to be available. Interface creation can take up to a few seconds after the Pod is in the Running state, as it happens asynchronously. Otherwise we can get the following error:
```
secondary_network_test.go:194: Error when pinging between interfaces: interface eth1 not found on vlan-pod2. err: <nil>
```
Fixes #6023
> [e2e tests] Wait for secondary IPs before running ping test

- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_test.go
- docs/secondary-network.md
- pkg/agent/secondarynetwork/init.go
- pkg/agent/secondarynetwork/init_test.go
- pkg/config/agent/config.go
Given that most SR-IOV have 8 queues, this commit allows adding at most 8 physical interfaces to the secondary OVS bridge.
Fixes: https://github.com/antrea-io/antrea/issues/5846
> Allow multiple physical interface support for secondary network bridge

- test/e2e/egress_test.go
- test/e2e/flowaggregator_test.go
- test/e2e/prometheus_test.go
- test/e2e/proxy_test.go
- test/e2e/service_externalip_test.go
- test/e2e/service_test.go
- test/e2e/util.go
wget in toolbox image expects the protocol to be specified when IPv6 address is used in the url, otherwise it would use ftp protocol. This patch fixes it and unifies how we get url from IP, port and path.
> Fix IPv6 e2e test caused by image update

- build/charts/antrea/crds/traceflow.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
Cherry pick of #6050 on release-1.15.
#6050: Fix wrong TCP flags validation (#6050)
> Automated cherry pick of #6050: Fix wrong TCP flags validation (#6050)

- ci/jenkins/test.sh
- ci/kind/test-e2e-kind.sh
- docs/cookbooks/fluentd/resources/kibana-elasticsearch.yml
> Remove unused busybox image references

- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
Cherry pick of #5954 on release-1.15.
#5954: Fix race condition in agent Traceflow controller (#5954)
> Automated cherry pick of #5954: Fix race condition in agent Traceflow controller (#5954)

- ci/kind/test-upgrade-antrea.sh
- docs/kind.md
- hack/generate-helm-release.sh
- hack/release/prepare-assets.sh
We stop referencing the VMware Harbor registry
(projects.registry.vmware.com) in the Helm charts and K8s manifests that we release to users, with the expectation that images for future releases will not be available from that registry, as it is scheduled to be EOL'd and we won't be mirroring them there.
Because the antrea DockerHub organization is part of the "Sponsored OSS" program, there should be no concern about users running into issues because of DockerHub rate-limits. We could also consider mirroring these images to ghcr.io in the future, to offer users an alternative.
At the moment, we do not update references to other images in the projects.registry.vmware.com/antrea project (images used for testing), with the expectation that they will remain available for the foreseeable …
> Stop using projects.registry.vmware.com for user-facing images

- .github/workflows/build.yml
- .github/workflows/conformance.yml
- ci/kind/test-e2e-kind.sh
- Add basic e2e tests for UBI image
- Run basic e2e tests on a Kind cluster for the UBI image to make sure the UBI image can be deployed as expected. Add a new input parameter `distro` to the conformance workflow to allow testing of the UBI image.
Fixes: #5729
> Add basic e2e tests for UBI image

- pkg/controller/networkpolicy/clustergroup.go
- pkg/controller/networkpolicy/clusternetworkpolicy.go
- pkg/controller/networkpolicy/clusternetworkpolicy_test.go
- pkg/controller/networkpolicy/crd_utils.go
- pkg/controller/networkpolicy/crd_utils_test.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/controller/networkpolicy/store/addressgroup.go
- pkg/controller/networkpolicy/store/appliedtogroup.go
- pkg/controller/types/networkpolicy.go
When an AppliedToGroup or AddressGroup is derived from a ClusterGroup or Group, we used the existence of the source Group in the internal group storage as the indicator of the type of AppliedToGroup or AddressGroup. After the source Group is deleted, the AppliedToGroup or AddressGroup was considered as a Group with its own selector mistakenly. Accessing its selector would panic due to nil pointer dereference.
This patch makes the type of AppliedToGroup and AddressGroup more explicit by adding a field "SourceGroup" to indicate it. If the source Group can't be found in the storage, we just return nil to indicate the Group selects nothing at the moment.
Fixes #6075
> Fix nil pointer dereference when ClusterGroup/Group is used

- ci/kind/test-upgrade-antrea.sh
- docs/kind.md
- hack/generate-helm-release.sh
- hack/release/prepare-assets.sh
Cherry pick of #6073 on release-1.15.
#6073: Stop using projects.registry.vmware.com for user-facing
> Automated cherry pick of #6073: Stop using projects.registry.vmware.com for user-facing

- pkg/controller/networkpolicy/clustergroup.go
- pkg/controller/networkpolicy/clusternetworkpolicy.go
- pkg/controller/networkpolicy/clusternetworkpolicy_test.go
- pkg/controller/networkpolicy/crd_utils.go
- pkg/controller/networkpolicy/crd_utils_test.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/controller/networkpolicy/store/addressgroup.go
- pkg/controller/networkpolicy/store/appliedtogroup.go
- pkg/controller/types/networkpolicy.go
Cherry pick of #6077 on release-1.15.
#6077: Fix nil pointer dereference when ClusterGroup/Group is used
> Automated cherry pick of #6077: Fix nil pointer dereference when ClusterGroup/Group is used

- pkg/controller/networkpolicy/store/addressgroup.go
- pkg/controller/networkpolicy/store/appliedtogroup.go
The Namespace index was no longer needed since 46a2fc53e966 ("Extract and optimize group member calculation") was merged.
> Remove unused index from AppliedToGroup and AddressGroup storages

- pkg/agent/memberlist/cluster.go
Formatted the error logs when the agent tries to establish a cluster with others. It will recover eventually after all agents are up.
Fixes #5966
> Fix Improve log when agent fails to join a new Node

- build/images/ovs/Dockerfile.ubi
- test/e2e/basic_test.go
Cherry pick of #6052 on release-1.13.
#6052: Fix log rotation in UBI images (#6052)
> Automated cherry pick of #6052: Fix log rotation in UBI images (#6052)

- ci/jenkins/jobs/job-templates.yaml
- ci/jenkins/jobs/projects-cloud.yaml
- ci/test-conformance-gke.sh
* Add a new credential job to generate temporary credentials.
* GKE job is now triggered as a post-build action of the credential job.
* Update the GKE script to support the new login method.
> Update GKE job to support the new cloud credential

- .github/workflows/build.yml
- .github/workflows/kind_ubi.yml
Create a dedicated workflow for KinD tests of UBI
images to align with the Ubuntu images.
Fixes: #6031, #6095
> Move KinD tests for UBI images to a dedicated workflow

- ci/jenkins/README.md
- ci/jenkins/jobs/projects-cloud.yaml
- docs/maintainers/release.md
Enable new Jenkins URL jenkins.antrea.io for all cloud jobs.
> Migrate Jenkins Service and Update URL

- test/e2e/antctl_test.go
Currently when running antctl e2e tests for controller mode+coverage not enabled, the command arguments are empty. 
So commands are not tested as expected. This PR fixes the issue. (Mainly line 200)
> Fix antctl e2e controller-mode empty tests

- build/images/ovs/Dockerfile.ubi
This change adds back the default `RPMBUILD_OPT` option to disable unnecessary tests when building OVS rpm packages, which was previously overwritten in #6052.
> Do not run tests when building OVS for UBI

- ci/kind/kind-setup.sh
- ci/kind/test-e2e-kind.sh
The script was failing with:
```
Deleting VLAN subnets
Option "-br" is unknown, try "ip help".
```
when cleaning-up a test cluster.
This is because the ip command on macOS only supports a subset of the command-line options supported on Linux. In any case, on macOS, the command needs be wrapped with docker_run_with_host_net, since we are looking for VLAN interfaces running in the Docker Linux VM.
As a minor improvement, we also add the "antrea" prefix to the external server container we create, along with a short random suffix ($RANDOM is sufficient for this) to avoid possible conflicts.
Fixes #6022
> Fix ci/test-e2e-kind.sh script on macOS

- Makefile
- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.agent.ubuntu
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubi
- build/images/Dockerfile.build.controller.ubuntu
- build/images/Dockerfile.build.coverage
- build/images/Dockerfile.build.ubi
- build/images/Dockerfile.build.ubuntu
- hack/release/prepare-assets.sh
- test/e2e/vmagent_test.go
Cherry pick of #5988 on release-1.15.
#5988: Disable cgo for all Antrea binaries (#5988)
> Automated cherry pick of #5988: Disable cgo for all Antrea binaries (#5988)

- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.controller.ubi
Because we are now disabling cgo when building all Antrea binaries, there is no need to install Go manually when building the UBI images. It was required before because of incompatibility between the glibc versions in the golang image and the ubi8 base image. We can now use the standard golang image to compile the Antrea binaries (without cgo, there is no dependency on glibc), then copy these binaries to the ubi8 image.
PR https://github.com/antrea-io/antrea/pull/5988, which disabled cgo, removed the unnecessary code from Dockerfile.build.ubi, but not from the other Dockerfiles (Dockerfile.build.agent.ubi and Dockerfile.build.controller.ubi).
> Remove unnecessary code from UBI Dockerfiles

- ci/kind/test-e2e-kind.sh
- test/e2e/connectivity_test.go
- test/e2e/framework.go
- test/e2e/tls_test.go
Fix the antrea-windows-containerd-e2e failure in release-1.15.1 #6110 by updating the toolbox image to v1.3-0 and cherry-pick PR6021.
There is an old issue tracked the same failure: https://github.com/antrea-io/image-utils/issues/26
> Update the toolbox image to v1.3-0 and cherry-pick PR6021 to fix windows containerd e2e failure

- pkg/agent/proxy/proxier_test.go
- pkg/agent/proxy/topology_test.go
- third_party/proxy/service.go
- third_party/proxy/util/utils.go
> Support LoadBalancerIPMode in AntreaProxy

- pkg/agent/agent_test.go
- pkg/agent/nodeportlocal/npl_agent_test.go
- pkg/antctl/raw/set/flowaggregator/command_test.go
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/flowaggregator/exporter/clickhouse_test.go
- pkg/util/env/env_test.go
- pkg/util/k8s/client_test.go
Fixes #6122 
I used subtests (t.Run) in env_test.go because we should restore envs after every test from testTable.
All other changes seems obvious.
> replacing os.Setenv with t.Setenv in all unit tests

- test/e2e/l7networkpolicy_test.go
- test/e2e/proxy_test.go
Fix L7 NetworkPolicy e2e test failure
Fix #6129
In the failure tests, the following function is called to
verify whether a connection should be allowed or denied.
To verify a connection should be denied, it requires 5 seconds.
```go
func probeClientIPFromPod(data *TestData, pod, container string, baseUrl string) (string, error) {
url := fmt.Sprintf("%s/%s", baseUrl, "clientip")
hostPort, _, err := data.runWgetCommandFromTestPodWithRetry(pod, data.testNamespace, container, url, 5)
if err != nil {
return "", err
}
host, _, err := net.SplitHostPort(hostPort)
return host, err
}
```
Before #5843, these e2e tests utilized the function `PollImmediate`
from `k8s.io/apimachinery/pkg/util/wait`, which immediately calls an
anonymous function including the above function. Since the timeout
is 5 …
> Fix L7 NetworkPolicy e2e test failure

- test/e2e/infra/vagrant/playbook/roles/common/tasks/kube.yml
As legacy Linux package repositories for Kubernetes are frozen, the old vagrant playbook throws an error.
```
fatal: [k8s-node-control-plane]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://packages.cloud.google.com/apt kubernetes-xenial Release' does not have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details."}
```
```
E:The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release …
```
> Update apt for Kubernetes in vagrant playbook

- ci/kind/test-e2e-kind.sh
The generated manifest was using the default ubuntu images.
> Fix build-and-test-ubi not using UBI images

- multicluster/cmd/multicluster-controller/clusterset_webhook.go
- multicluster/cmd/multicluster-controller/clusterset_webhook_test.go
- multicluster/cmd/multicluster-controller/controller.go
- multicluster/cmd/multicluster-controller/gateway_webhook.go
- multicluster/cmd/multicluster-controller/gateway_webhook_test.go
- multicluster/cmd/multicluster-controller/leader.go
- multicluster/cmd/multicluster-controller/member.go
- multicluster/cmd/multicluster-controller/memberclusterannounce_webhook.go
- multicluster/cmd/multicluster-controller/memberclusterannounce_webhook_test.go
- multicluster/cmd/multicluster-controller/options.go
- multicluster/cmd/multicluster-controller/options_test.go
A few issues were introduced by #5843 because of changes in the sigs.k8s.io/controller-runtime interface.
The biggest issue was that the call to ctrl.NewManager was not using the Options object populated earlier in the setupManagerAndCertController function. Instead it was creating and using a new, incomplete Options object.
Fixes #6149
> [Multicluster] Fix cache options for controller Manager

- cmd/antrea-agent/options.go
- cmd/antrea-controller/options.go
- multicluster/cmd/multicluster-controller/options.go
- pkg/flowaggregator/options/options.go
- pkg/util/yaml/decode.go
- pkg/util/yaml/decode_test.go
- test/e2e/basic_test.go
When upgrading Antrea, the config is usually updated first and there may be some new fields added to it. If a yet update agent crashes during the process, it will fail to restart due to the unknown new fields because we do strict decoding only.
The patch adds lenient decoding when strict decoding fails to tolerate unknown fields and duplicate fields. Other errors like malformed data and unmatched type are still fatal.
---
For reference, kube-proxy and kubelet have been doing this since 1.17:
https://github.com/kubernetes/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/cmd/kube-proxy/app/server.go#L491
https://github.com/kubernetes/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/pkg/kubelet/kubeletconfig/util/codec/codec.go#L76
> Fall back to lenient decoding when strict decoding config fails

- cmd/antrea-agent/agent.go
- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
Add a precheck on the Multicast feature gate status with IPv6-only cluster settings in agent Initializer, and install the iptables rules only in the IPv4 related chains.
Fix: #6113
> [Bugfix] Install Multicast related iptables rules only on IPv4 chains

- ci/jenkins/test-mc.sh
Multicluster e2e test was killed because the default timeout is not enough sometime, I have seen below errors in old patch releases, so increase it to 15m.
```
*** Test killed with quit: ran too long (11m0s).
```
> Increase timeout to 15m for Multicluster e2e test

- multicluster/build/images/Dockerfile.build
We use Docker cache mounts to accelerate Docker builds with Go. With cache mounts, we can cache package dependencies and the Go build cache in a persistent fashion (i.e., persists across builds).
This is similar to #5918, which implemented the same change for the "main" Antrea images.
With this change, we go from 5 minutes down to 30 seconds when re-building the antrea/antrea-mc-controller image after a minor change to the source code.
> Optimize Docker build for Multicluster image

- .github/workflows/kind.yml
- test/e2e-secondary-network/infra/prepare_cluster.sh
1. Fix test-secondary-network workflow image by adding the correct
tag, so that we can use the image we built instead of pulling the one
from the registry.
3. Fix typo in the script.
> Fix test-secondary-network workflow image

- ci/jenkins/test-mc.sh
Cherry pick of #6163 on release-1.14.
#6163: Increase timeout to 15m for Multicluster e2e test (#6163)
> Automated cherry pick of #6163: Increase timeout to 15m for Multicluster e2e test (#6163)

- cmd/antrea-agent/agent.go
- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
Cherry pick of #6123 on release-1.13.
#6123: Install Multicast related iptables rules only on
> Automated cherry pick of #6123: Install Multicast related iptables rules only on

- test/e2e/vmagent_test.go
Cherry pick of #6154 on release-1.14.
#6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"
> Automated cherry pick of #6154: Fix a flaky failure in VM Agent e2e test "testExternalNode"

- docs/antrea-ipam.md
- docs/egress.md
When defining a pool with a CIDR, the first and the last IP address will usually be excluded. The last IP address (broadcast) is only excluded for IPv4, and, for IPPool, only if the prefix length matches the CIDR mask size.
> Clarify documentation for IPPool and ExternalIPPool CRDs

- pkg/antctl/output/output.go
- pkg/antctl/transform/networkpolicy/response.go
- pkg/antctl/transform/networkpolicy/response_test.go
- pkg/apiserver/apis/types.go
- pkg/controller/networkpolicy/endpoint_querier.go
- pkg/controller/networkpolicy/endpoint_querier_test.go
- pkg/controller/types/networkpolicy.go
As necessary for `networkpolicyevaluation` consumption, this PR adds the `Action` field to the above `antctl` command response.
> Add Action to NetworkPolicy Evaluation response

- pkg/monitor/agent.go
- pkg/monitor/controller.go
- pkg/ovs/openflow/ofctrl_bridge.go
- third_party/proxy/config/config.go
While debugging an issue with improved log level, I found that periodical events like updating monitoring CRs and EndpointSlice events lead to a lot of logs, each of which took considerable space as they dump the entire objects, while we rarely need them.
---
Before the patch:
```
I0408 04:23:36.457147       1 agent.go:95] Updating agent monitoring CRD &{TypeMeta:
{Kind: APIVersion:} ObjectMeta:{Name:kind-worker2 GenerateName: Namespace: SelfLink:
UID:6427a66a-d181-4992-8198-2bab3b8c650f ResourceVersion:649256 Generation:1500
CreationTimestamp:2024-04-07 03:23:34 +0000 UTC DeletionTimestamp:<nil>
DeletionGracePeriodSeconds:<nil> Labels:map[] Annotations:map[] OwnerReferences:[] Finalizers:
[] ManagedFields:[{Manager:antrea-controller Operation:Update APIVersion:crd.antrea.io/v1beta1 …
```
> Reduce verbose logs that dump large objects

- pkg/apiserver/certificate/selfsignedcert_provider.go
- pkg/apiserver/certificate/selfsignedcert_provider_test.go
If a cluster used user provided certificate and created a Secret named antrea-controller-tls of Opaque type, changing to use self-signed certificate would fail because the type field is immutable.
To support switching the certificate provider, we don't try to update the type of Secret if it already exists.
---
cert-manager has similar logic: https://github.com/cert-manager/cert-manager/commit/7a4be1edfdeb75429baf9f2b6e94c63c9b57d5a6
The following scenarios have been considered:
1. cert-manager provided certificate -> Antrea self-signed certificate: as both of them use tls type
2. user manually created certificate -> Antrea self-signed certificate: as Antrea doesn't update type
3. Antrea self-signed certificate -> cert-manager provided certificate: as cert-manager doesn't update type 
4. …
> Do not try to update type of Secret in selfSignedCertProvider

- pkg/agent/supportbundlecollection/support_bundle_controller.go
- pkg/agent/supportbundlecollection/support_bundle_controller_test.go
- pkg/apiserver/registry/system/supportbundle/rest.go
- pkg/apiserver/registry/system/supportbundle/rest_test.go
- pkg/support/dump.go
> Add OVS groups to support bundle

- pkg/apiserver/certificate/selfsignedcert_provider.go
- pkg/apiserver/certificate/selfsignedcert_provider_test.go
Cherry pick of #6205 on release-1.13.
#6205: Do not try to update type of Secret in selfSignedCertProvider
> Automated cherry pick of #6205: Do not try to update type of Secret in selfSignedCertProvider

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
The agent maintains DNS cache for FQDNs matching any FQDN rule of NetworkPolicy in two ways, one of which is that it periodically queries these FQDNs. However, it turned out that the current implementation made more queries than needed, for several reasons:
1. addFQDNRule() always triggered a DNS query immediately even if the FQDN was already tracked, and the function was called by podReconciler every time the rule was updated. This means if a FQDN's resolution is changed by a proactive query or a packet-in event, the FQDN would always be queried another time immediately.
2. When calculating the expiration time for proactively queried records and the delay for next query, the pre-query timestamp was used as the base. This caused the next query to likely return the same record with a very …
> Avoid unnecessary DNS queries for FQDN rule of NetworkPolicy

- build/charts/antrea/crds/externalentity.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/api.md
v1alpha1/ExternalEntity is not served for a long time, so it can be removed from the CRD definition.
> Remove deprecated v1alpha1/ExternalEntity

- build/charts/antrea/templates/simulator/statefulset.yaml
- ci/docker-registry
- ci/jenkins/test-vm.sh
- ci/jenkins/test.sh
- ci/kind/test-e2e-kind.sh
- ci/kind/test-secondary-network-kind.sh
- ci/run-k8s-e2e-tests.sh
- hack/externalnode/sftp-deployment.yml
- multicluster/test/e2e/framework.go
- test/e2e/charts/flow-visibility/templates/clickhouseinstallation.yaml
- test/e2e/framework.go
Replace Harbor images with Docker Hub images due to the impending unavailability of projects.registry.vmware.com.
> Replace Harbor images with DockerHub images

- docs/node-port-local.md
The targetPort for the Service should be 8080 to match the NPL annotation in the example.
> Fix typo in NodePortLocal documentation

- test/e2e/vmagent_test.go
The test was failing because of a missing expected entry for the supportbundle (OVS groups, which was added recently).
Because this is not the first time that it happens, we relax the test so that it no longer fails when the supportbundle actual contents are not an exact match with the expected contents (they have to be a superset).
Fixes #6215
> Fix VM Agent e2e test

- .golangci.yml
- multicluster/cmd/multicluster-controller/clusterset_webhook.go
- multicluster/controllers/multicluster/commonarea/remote_common_area_test.go
- multicluster/controllers/multicluster/member/resourceimport_controller.go
- multicluster/controllers/multicluster/member/serviceexport_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/flowexporter/connections/l7_listener.go
- pkg/agent/secondarynetwork/podwatch/controller.go
It also fixes a bug in secondary podController that the code would panic due to nil pointer dereference when there is a DeletedFinalStateUnknown received from the informer.
Fixes #6054
> Fix misformatted klog and add a linter for loggers

- cmd/antrea-controller/options.go
- cmd/antrea-controller/options_test.go
Using higher QPS and Burst rather than the default settings (QPS: 5, Burst: 10), otherwise synchronizing resources like ClusterNetworkPolicies and Egresses would be rather slow when they are created in bulk.
> Increase default rate limit of antrea-controller

- pkg/support/dump_windows.go
- pkg/support/dump_windows_test.go
After switching to Containerd runtime, Antrea doesn't depend on rancher-wins when running agent. So the agent log files should start with "antrea-agent".
This change has removed the prefix "rancher-wins" in the file name filters when collecting agent logs on Windows.
Fix: #6222
> [Windows] Remove prefix "rancher-wins" when collecting antrea-agent logs

- docs/antrea-network-policy.md
Related to https://github.com/antrea-io/antrea/issues/6229
> Document Pods using FQDN based policies must respect DNS TTL

- docs/antrea-network-policy.md
Starting with Antrea v1.13, logging is best-effort, which means that logging cannot typically be used for compliance purposes.
For older Antrea versions, traffic for which logging was enabled would be dropped after a certain rate was reached, creating issues for production workloads.
> Document the limitations of Audit Logging for policy rules

- build/charts/antrea/README.md
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
Starting with [K8s v1.22](https://github.com/kubernetes/kubernetes/pull/99729), system-cluster-critical Pods no longer get low OOM score like system-node-critical Pods. antrea-controller's OOM score adjustment was changed from -997 to 999 passively, which made it just have a bit higher chance of survival over best-effort Pods (OOM score adjustment: 1000). While it's hard to say how much memory it can use as it's highly related to the scale of the cluster, we can add a basic memory request which can decrease the score a bit according to [the formula for burstable Pods](https://github.com/kubernetes/kubernetes/blob/d831b13e6f6fb5efb566100286190fedca6dd340/pkg/kubelet/qos/policy.go#L71):
oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity
It should also be a bit helpful to avoid …
> Request basic memory for antrea-controller

- ci/jenkins/test.sh
- hack/windows/Prepare-Node.ps1
> Explicitly set kubelet's log files in Prepare-Node.ps1 on Windows

- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_linux.go
- cmd/antrea-agent/options_windows.go
The code was logging an incorrect warning about AntreaProxy being disabled. This is is because checkUnsupportedFeatures was in charge of the check, but o.enableAntreaProxy is set later in the validation chain. To avoid the issue, we introduce a new function for platform-specific checks, validateConfigForPlatform, which runs after all other validations and after all fields in the Options struct have been set.
We also replace the warning message with an error message (but we do not fail Agent initialization) and we add a check for proxyAll.
> Remove incorrect AntreaProxy warning on Windows

- hack/externalnode/sftp-deployment.yml
We don't have any intro for the image in Dockerhub, there is no clue for the args usage. So add the link to the original image.
@antoninbas do you think we can also add a reference link in the Dockerhub? and another thing is for the image sync, looks like the image in our repo is 9 months ago.
> Change sftp image URL to github container registry

- build/charts/antrea/templates/simulator/statefulset.yaml
- ci/docker-registry
- ci/jenkins/test-vm.sh
- ci/jenkins/test.sh
- ci/kind/test-e2e-kind.sh
- ci/run-k8s-e2e-tests.sh
- hack/externalnode/sftp-deployment.yml
- multicluster/test/e2e/framework.go
- test/e2e/charts/flow-visibility/templates/clickhouseinstallation.yaml
- test/e2e/framework.go
Cherry pick of #6076 on release-1.14.
#6076: Replace test Harbor images with DockerHub images (#6076)
> Automated cherry pick of #6076: Replace test Harbor images with DockerHub images (#6076)

- docs/antrea-network-policy.md
Clarify how the pass action interacts with both Antrea-native policy objects and K8s NP
> Minor doc improvement for Pass action in Antrea-native policies

- test/e2e/fixtures.go
- test/e2e/k8s_util.go
- test/e2e/nodenetworkpolicy_test.go
In NodeNetworkPolicy e2e tests, we have the following cases:
- Node to Node. We deploy two hostNetwork Pods on different Nodes.
- Node to Pods. We deploy a hostNetwork Pod on a Node and two
non-hostNetwork Pods on different Nodes.
For the case of Node to Pods, after creating test Pods, a full mesh
probing is run to ensure that all Pods can be reachable from each
other. However, the UDP or SCTP probing from a non-hostNetwork Pod, using
the Node external IP (the IP in the hostNetwork Pod object) as destination
IP, to the hostNetwork Pod within on the same Node will get a failure. The
reason is that due to UDP's connectionless nature, the reply traffic
may use a source IP address determined by routing decisions or outgoing
interfaces, which means that the local Antrea gateway IPs will be …
> Fix NodeNetworkPolicy e2e test failure

- test/e2e/antreapolicy_test.go
In current baseline isolation e2e test, the nsSelector expression is misplaced as nodeSelector expression, yet the test case does not detect the error based on current test factors.
This PR fixes the nsSelector expression issue, and also adds test factors in the baseline isolation test case to increase coverage.
> Fix and Enhance E2E ACNP Baseline Isolation Test

- ci/jenkins/test.sh
By utilizing the `trap` command, the script now automatically triggers `collect_windows_network_info_and_logs` upon any failure that occurs during running test.
> Enhance logging for Windows CI failures

- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- test/e2e/egress_test.go
Record event when Egress is uninstalled from a node.
FIxes #5996.
> Record event when EgressIP remains unassigned

- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/fields.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pod_connectivity_test.go
- pkg/agent/openflow/service.go
- test/integration/agent/openflow_test.go
Before this commit, in AntreaProxy, to respect short-circuiting, when installing flows for an external Services, an extra flow with higher priority to match traffic sourced from local (local Pods or local Node) and destined for the external Service will be installed. This is achieved by matching the local Pod CIDR obtained from the local Node object. However, when Antrea is deployed in networkPolicyOnly mode, the Pod CIDR in the local Node object is nil, resulting in the failure of install the extra flow mentioned above. To fix the issue, a new reg mark `FromLocalRegMark` identifying traffic from local Pods or the local Node is introduced to mark the traffic from local. This reg mark can be used in all traffic mode.
Fix #6244
> Fix that local traffic cannot be identified in networkPolicyOnly mode

- cmd/antrea-agent/agent.go
- pkg/agent/agent_linux.go
- pkg/agent/agent_linux_test.go
- pkg/agent/secondarynetwork/init.go
- pkg/agent/secondarynetwork/init_test.go
- pkg/agent/util/net.go
- pkg/agent/util/net_linux.go
- pkg/agent/util/net_windows.go
Fixes: https://github.com/antrea-io/antrea/issues/5735
> Use a Node's primary NIC as the secondary OVS bridge physical interface

- pkg/antctl/transform/networkpolicy/response.go
- pkg/antctl/transform/networkpolicy/response_test.go
- pkg/controller/networkpolicy/endpoint_querier.go
- pkg/controller/networkpolicy/endpoint_querier_test.go
When processing Kubernetes NetworkPolicy, a default action Allow is assigned in Antrea controller. This was not handled in NetworkPolicyEvaluation action field. This PR fixes it to differentiate from Isolate value in specific case of default isolation model.
> [Followup] Fix action field in NetworkPolicyEvaluation for KNP

- .gitignore
- ci/jenkins/jobs/macros.yaml
Fixes #4841.
Current implementation of updater job builder uses find's built-in capabilities to directly filter files safely based on their names. This avoids the overhead of piping all file paths through multiple grep commands, which can slow down the process.
> Improve macros for job updater builder

- build/images/Dockerfile.build.controller.ubi
- hack/build-antrea-linux-all.sh
The image was incorrectly using ubuntu:22.04 as the base image instead of registry.access.redhat.com/ubi8. This issue must have been present since introducing split images for the Agent and Controller in v1.15.0.
Credit goes to @xliuxu for finding this issue.
> Fix base image for antrea/antrea-controller-ubi

- docs/versioning.md
> Add upgrade instructions for Antrea v2.0

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- .github/workflows/kind_ubi.yml
- build/images/Dockerfile.build.controller.ubi
- build/images/base/Dockerfile.ubi
- build/images/ovs/CentOS.repo
- build/images/ovs/Dockerfile.ubi
- build/images/ovs/build.sh
- hack/build-antrea-linux-all.sh
- Switch to centos:stream9 to build OVS
- Use bind mount to reduce intermediate layers
Fixes: https://github.com/antrea-io/antrea/issues/5725
> Upgrade base image of UBI to UBI9

- pkg/agent/openflow/client_test.go
- pkg/agent/openflow/fields.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pod_connectivity_test.go
- pkg/agent/openflow/service.go
- test/integration/agent/openflow_test.go
Cherry pick of #6251 on release-1.15.
#6251: Fix that local traffic cannot be identified in
> Automated cherry pick of #6251: Fix that local traffic cannot be identified in

- CONTRIBUTING.md
> Document Kind CI trigger phrases

- ci/jenkins/test-mc.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
Update Docker image pruning command to remove all unused Docker images, not just the dangling ones to optimize the disk space utilization.
> Optimize disk space usage in CI by pruning all unused Docker images

- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/npl_agent_test.go
- pkg/agent/nodeportlocal/portcache/port_table.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_others_test.go
- pkg/agent/nodeportlocal/portcache/port_table_windows.go
- test/e2e/nodeportlocal_test.go
The logic for deleting an individual NPL mapping was broken. It incorrectly believed that the protocol socket was still in use, and the mapping could never be deleted, putting the NPL controller in an endless error loop.
The State field in ProtocolSocketData was left over from pre Antrea v1.7, back when we would always use the same port number for multiple protocols, for a give Pod IP + port. With the current version of the NPL implementation, this field is not needed and should be removed. By removing the field, we avoid the deletion issue.
This patch also ensures that if a rule is only partially cleaned-up, we can attempt to delete it again, by making DeleteRule idempotent. To identify that a prior deletion attempt failed, we introduce a "defunct" field in the NPL rule data. If this …
> Fix single rule deletion for NodePortLocal on Linux

- go.mod
- go.sum
- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/test_podtopodinternode.go
* Test results will be displayed in green, red, and yellow to indicate success, failure, and skipped, respectively.
* Show the total number of success, failure, and skipped tests in the end.
* Return error if any test fails. Otherwise, it would be hard for automation tools to detect whether the check succeeds or not.
---
Example of success:
Example of failure:
> Improve the readability of post-installation test results

- docs/noencap-hybrid-modes.md
The legacy in-tree provider has been removed.
> Update documentation link for GCP cloud provider

- docs/noencap-hybrid-modes.md
Cherry pick of #6296 on release-2.0.
#6296: Update documentation link for GCP cloud provider (#6296)
> Automated cherry pick of #6296: Update documentation link for GCP cloud provider (#6296)

- docs/antrea-proxy.md
> Update document antrea-proxy.md

- docs/antrea-proxy.md
Cherry pick of #6274 on release-2.0.
#6274: Mention LoadbalancerIPMode support in AntreaProxy doc(#6274)
> Automated cherry pick of #6274: Mention LoadbalancerIPMode support in AntreaProxy doc(#6274)

- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/npl_agent_test.go
- pkg/agent/nodeportlocal/portcache/port_table.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_others_test.go
- pkg/agent/nodeportlocal/portcache/port_table_windows.go
- test/e2e/nodeportlocal_test.go
Cherry pick of #6284 on release-2.0.
#6284: Fix single rule deletion for NodePortLocal on Linux (#6284)
> Automated cherry pick of #6284: Fix single rule deletion for NodePortLocal on Linux (#6284)

- build/images/scripts/start_ovs
The SLEEP_PID variable (used to store the PID of the sleep process started by the "main" loop) was being overwritten in the signal handler. The 1-second sleep which runs in the signal handler and wait for uplink port deletion (when bridging mode is enabled) does not need to run in the background.
> Minor fix to start_ovs script when bridging mode is enabled

- build/charts/antrea/crds/traceflow.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- pkg/agent/controller/traceflow/packetin.go
- pkg/agent/controller/traceflow/packetin_test.go
- pkg/apis/crd/v1beta1/types.go
- pkg/apiserver/openapi/zz_generated.openapi.go
- test/e2e/traceflow_test.go
> Add srcPodIP field in Traceflow observations

- .github/workflows/kind.yml
- ci/kind/test-e2e-kind.sh
- test/e2e/antreapolicy_test.go
- test/e2e/fixtures.go
- test/e2e/framework.go
- test/e2e/k8s_util.go
- test/e2e/reachability.go
The PR will add E2E tests for `networkpolicyevaluation` introduced in #5740 .
This framework design and test example is for discussion before moving on.
> NetworkPolicy Evaluation E2E Tests

- pkg/agent/controller/networkpolicy/node_reconciler_linux.go
- pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
To improve the readability of iptables rules installed for NodeNetworkPolicy, the rule name, which is more meaningful, instead of rule ID, which is a unique string, is used in the corresponding iptables rule.
> Use rule name in iptables rule comment for NodeNetworkPolicy

- test/e2e/fixtures.go
- test/e2e/ipsec_test.go
- test/e2e/wireguard_test.go
This is an e2e fix because of PR #5920.
> Skip IPSec/WireGuard e2e test when the Multicast feature is enabled

- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_route.go
- pkg/agent/multicast/mcast_route_linux.go
- pkg/agent/multicast/mcast_route_test.go
- pkg/agent/multicast/mcast_socket_linux.go
- pkg/agent/multicast/mcast_socket_others.go
- pkg/agent/multicast/testing/mock_multicast.go
- pkg/agent/util/syscall/linux/types.go
- pkg/agent/util/syscall/syscall_unix.go
- pkg/agent/util/syscall/ztypes_linux.go
This commit removes the relevant stale multicast routes. When multicast sender Pods are deleted or stop sending multicast traffic in 10 minutes, the related multicast routes should be considered as stale and are removed with this commit. MRouted implements a similar stale routes cleanup mechanism in [OpenBSD](https://github.com/openbsd/src/blob/1eb3d403c0b906b74d72964ea1ac54f688ca1692/usr.sbin/mrouted/prune.c#L1470-L1497) and [NetBSD](https://github.com/NetBSD/src/blob/5970d5082c482e82e9d8ca572f57c4acdb86c996/usr.sbin/mrouted/prune.c#L1686-L1714).
Periodically cleaning stale multicast routes would improve the readability of multicast routes, such as the readability of "ip mroute" output. Also, the memory consumption of Nodes could be slightly reduced(
running 28 multicast senders, each …
> [Multicast] removal of stale multicast routes

- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/test_podtoserviceinternode.go
- pkg/antctl/raw/check/installation/test_podtoserviceintranode.go
Ref #6061 
This PR Enables the testing framework to test Pod to service connectivity. 
It does it by connecting the client pod to 2 services. 1 service routes the traffic to Pod of same Node deployment and 1 service routes the traffic to Pod of other Node deployment.
Situations for single Node cluster is also handled.
> Enabling service connectivity tests in Post-installation testing framework

- pkg/antctl/raw/multicluster/deploy/deploy_helper.go
- pkg/antctl/raw/multicluster/deploy/deploy_helper_test.go
This patch ensures that `v` is optional in the version tag and improves the error message if the specified version tag is not found.
If someone provide an invalid tag the error message would be,
```
$ ./bin/antctl mc  deploy leadercluster -n antrea-multicluster --antrea-version 2.15.0
Error: specified version tag is not found
```
This PR addresses the issue #6151
> Fix antctl mc deploy command usage

- .github/workflows/conformance.yml
- .github/workflows/kind.yml
- .github/workflows/trivy_scan_before_release.yml
Whenever the Antrea images are built from scratch using `./hack/build-antrea-linux-all.sh` in Github CI, we should set up Docker Buildx first. It ensures that the docker-container driver is used, which enables the registry cache backend. We depend on this cache backend to speed up the build by avoiding re-building the base images if it is not necessary. Without caching, the build takes ~10 minutes instead of ~3 minutes.
> Set up Docker Buildx in workflows whenever building Antrea

- docs/traceflow-guide.md
For TCP / UDP traces, the srcPort can be omitted, in which case the Antrea Agent will use a random source port when injecting the Traceflow packet at the source Node.
> Fix inaccuracy in Traceflow user guide

- .github/workflows/trivy_scan.yml
Ever since splitting up the Agent and Controller images, there was an issue with the Trivy workflow, as the same output path was used for the Trivy report for both the Agent and Controller. When generating the report for the Controller, it would overwrite the one for the Agent, meaning that incomplete information was uploaded as job artifacts.
> Fix trivy Github workflow

- test/e2e/antreaipam_test.go
- test/e2e/framework.go
- test/e2e/l7networkpolicy_test.go
- test/e2e/traceflow_test.go
- test/e2e/trafficcontrol_test.go
This PR adds an E2E test for L7 NetworkPolicy logging. It checks both allowed and dropped HTTP event logs under l7engine directory.
Resolving [this issue](https://github.com/antrea-io/antrea/pull/6014#issuecomment-1967277544) from discussion.
> Add E2E test for L7 NetworkPolicy Logging

- cmd/antrea-agent/agent.go
- cmd/antrea-controller/controller.go
- pkg/util/k8s/transform.go
- pkg/util/k8s/transform_test.go
Unused fields stored in informers can occupy significant memory usage. The informer provides a transform func to allow mutating the objects before they are stored, via which we can trim unneeded fields.
In general, managedFields is never used for all types of objects. In addition, we trim some unneeded fields from Pod objects given their unused fields take the most considerable space.
It can reduce the memory usage of 1k simple Pod by approximately 5m.
---
Test:
Measured the memory usage of antrea-controller with 2k, 4k, 6k Pods with the following Pod template:
```
template:
metadata:
labels:
app: client
spec:
containers:
- image: k8s.gcr.io/e2e-test-images/agnhost:2.29
imagePullPolicy: IfNotPresent
name: agnhost
resources: {}
terminationMessagePath: /dev/termination-log …
```
> Trim unneeded fields stored in informers to reduce memory footprint

- pkg/agent/secondarynetwork/init_linux.go
When SecondaryNetwork is enabled, but the ovsBridges list is empty, the antrea-agent currently panics during graceful termination. This is because the RestoreHostInterfaceConfiguration was assuming that there was alwasy one OVS bridge.
The panic is not really impactful, as it happens during Pod termination. However, for code coverage collection in e2e tests, it can have an impact, so we want to make sure it doesn't happen.
> Fix RestoreHostInterfaceConfiguration for SecondaryNetwork

- build/images/base-windows/Dockerfile
I am not sure why but the download is no longer working. Using this trick (https://stackoverflow.com/a/69552948), we can force Sourceforge to redirect us to the download mirror immediately.
> Fix mingw download in base Windows image

- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/command_test.go
- pkg/antctl/raw/check/installation/test_podtointernet.go
- pkg/antctl/raw/check/installation/test_podtopodinternode.go
- pkg/antctl/raw/check/installation/test_podtopodintranode.go
- pkg/antctl/raw/check/installation/test_podtoserviceinternode.go
- pkg/antctl/raw/check/installation/test_podtoserviceintranode.go
To support running a subset only of tests, based on which test names match the provided regex.
We also log stderr when `/agnhost connect` fails, to assist in troubleshooting. I have seen the `antctl check installation` command fail in CI, and at the moment it is impossible to troubleshoot.
> Add "-run" filter for antctl check installation command

- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/test_podtoserviceinternode.go
- pkg/antctl/raw/check/installation/test_podtoserviceintranode.go
- pkg/antctl/raw/check/util.go
The function was not returning the contents of stdout / stderr in case of a command error, making troubleshooting impossible.
> Fix ExecInPod implementation for antctl check

- ci/jenkins/README.md
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-lab.yaml
- ci/jenkins/test.sh
Following CI jobs are added as a part of  jenkins job for Windows OVS containerization
1. Add new jobs to run e2e, conformance and networkpolicy tests on testbed with Containerd runtime and
OVS running inside container.
2. Add job to allow skiping windows e2e, conformance and networkpolicy jobs with trigger phrases  skip-windows-e2e, skip-windows-conformance and skip-windows-networkpolicy respectively, also one can make use of skip-all to skip running all the three jobs. 
3. Add period job for OVS userspace daemons running as Windows services
For #5325
> Add Jenkins Job for Windows OVS containerization

- cmd/antrea-agent/agent.go
- pkg/util/k8s/transform.go
- pkg/util/k8s/transform_test.go
The images field is of no use to Antrea while it could be a long list and take quite some space as antrea-controller and all antrea-agent instances cache all Nodes in the cluster.
Trimming images can release nearly 10m memory from each Antrea process in a cluster of 1k Nodes, saving 10G memory in total.
> Trim images in Node objects to reduce memory footprint

- cmd/antrea-cni/main.go
- go.mod
- go.sum
> update cni to 1.2.0

- pkg/util/k8s/transform.go
- pkg/util/k8s/transform_test.go
AntreaIPAM uses ownerReferences to know if there is a IP reserved for the Pod by StatefulSet.
Fixes #6356
> Do not clear ownerReferences of Pod as it's used by AntreaIPAM

- pkg/antctl/raw/check/cluster/command.go
- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/util.go
Ref #6061 
This PR refactors the labels used in test deployments of `antctl check installation` command framework to match the label pattern with rest of the codebase.
> Refactored post-installation framework labels

- pkg/agent/controller/networkpolicy/l7engine/reconciler.go
When antrea-agent starts Suricata instance with the following command:
```
suricata -c /etc/suricata/suricata.yaml --af-packet -D -l /var/log/antrea/networkpolicy/l7engine/
```
The method `Run()` of `exec.Cmd` should be used instead of `Start()` to avoid generating a zombie process. The above command will exit after starting the process of Suricata instance in the background, so using `Run()` ensures that the command's resources are properly released and no defunct process remains.
> Avoid generating defunct process when starting Suricata

- pkg/agent/controller/networkpolicy/l7engine/reconciler.go
Cherry pick of #6366 on release-2.0.
#6366: Avoid generating defunct process when starting Suricata
> Automated cherry pick of #6366: Avoid generating defunct process when starting Suricata

- pkg/agent/memberlist/cluster.go
The config is a very large struct and some of the fields cannot be logged:
```
New memberlist cluster" config="<internal error: json: unsupported type: func(string) bool>"
```
We update the call to klog.InfoS so that only a few selected config fields are logged.
> Fix invalid log for memberlist creation

- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
Prior to this change, only updates to the configuration of exporters (sinks) were handled gracefully, without requiring a FlowAggregator restart.
After this change, we also support updating recordContents.podLabels at runtime.
For all other unsupported config changes, we print an error log, asking users to restart the FlowAggregator.
> Improve handling of config changes in FlowAggregator

- ci/jenkins/docker_login.sh
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-cloud.yaml
- ci/jenkins/jobs/projects-lab.yaml
- ci/jenkins/test-vmc.sh
Enhance Jenkins pipeline by integrating Docker credentials for login to avoid rate limit issues
> Add Docker login to Jenkins script to avoid rate limit issue

- build/charts/antrea/templates/agent/daemonset.yaml
- build/charts/antrea/templates/controller/deployment.yaml
- build/charts/flow-aggregator/templates/deployment.yaml
- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.controller.coverage
- build/images/flow-aggregator/Dockerfile.coverage
- test/e2e/antctl_test.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
This PR includes the following changes:
- Coverage binaries are now named as regular binaries, without "-coverage" suffix.
- Regular binaries are not included in coverage-enabled Dockerfiles.
cc: @antoninbas @luolanzone
> Use same name for coverage-enabled binaries and regular binaries

- docs/antrea-network-policy.md
Explain the risk of setting FQDN rules with drop or reject actions
> Add recommend usage of FQDN policies

- build/images/flow-aggregator/Dockerfile
- build/images/flow-aggregator/Dockerfile.coverage
We have made some improvements to the "main" Antrea Docker images (Agent, Controller) in the past, which can also benefit the FlowAggregator image:
* use Docker cache mounts to accelerate builds
* improve layer sharing between images by building antctl first
* install apt packages first in the final image (before copying binaries over from the intermediate build image); this improves caching and build parallelism.
> Improve Docker build for FlowAggregator image

- cmd/antrea-agent/agent.go
- pkg/agent/agent.go
- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_test.go
- pkg/agent/controller/noderoute/node_route_controller.go
- pkg/agent/controller/noderoute/node_route_controller_test.go
- test/e2e/connectivity_test.go
- test/integration/agent/cniserver_test.go
Until a set of "essential" flows has been installed. At the moment, we include NetworkPolicy flows (using podNetworkWait as the signal), Pod forwarding flows (reconciled by the CNIServer), and Node routing flows (installed by the NodeRouteController). This set can be extended in the future if desired.
We leverage the wrapper around sync.WaitGroup which was introduced previously in #5777. It simplifies unit testing, and we can achieve some symmetry with podNetworkWait.
We can also start leveraging this new wait group
(flowRestoreCompleteWait) as the signal to delete flows from previous rounds. However, at the moment this is incomplete, as we don't wait for all controllers to signal that they have installed initial flows.
Because the NodeRouteController does not have an initial "reconcile" …
> Delay removal of flow-restore-wait

- test/e2e/basic_test.go
There should no longer be a need for a custom timeout value in testAntreaGracefulExit when coverage is enabled. The increased timeout was not actually required for code coverage collection (which is qite fast), but because of issues with the coverage-enabled image, which was not handling signals correctly. After #6090, this should have been fixed.
> [e2e tests] Remove custom timeout value for coverage image

- hack/make-metrics-doc.sh
From time to time, the script will fail in CI with the following error:
```
error: no matching resources found
```
This error occurs when the kubectl command used to wait for all Antrea Pods to become Ready is run but no Pod has been created yet. This is possible, especially on a slow machine, as applying the Antrea manifest does not create any Pod. Instead, it creates the antrea-agent DaemonSet and the antrea-controller Deployment, and the K8s control-plane may take some time to actually create the corresponding Pods. To fix this issue, we first wait for the rollout to complete for both antrea-agent and antrea-controller.
> Fix hack/make-metrics-doc.sh script

- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
- pkg/flowaggregator/flowaggregator.go
In particular, updates to recordContents.podLabels and recordFormat were ignored, without any kind of warning.
> [FlowAggregator] Fix live config updates for IPFIXExporter

- ci/jenkins/test-mc.sh
- ci/jenkins/test-vmc.sh
It turns out kubectl cp with wildcard is not working properly. I saw following errors in our CI jobs:
```
tar: /tmp/coverage/*: Cannot stat: No such file or directory
```
Fix it by check all files on /tmp/coverage/ and copy them one by one.
Here is some discussion about the kubectl cp bug.
https://devops.stackexchange.com/questions/6669/copy-multiple-files-using-wildcard-from-kubernetes-container
> Fix kubectl cp failure with wildcard

- pkg/agent/util/net_linux.go
- pkg/agent/util/net_linux_test.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
> Remove unexpected AltName after rename interface

- ci/jenkins/test-rancher.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
When the conformance test is aborted by Jenkins, the results log is actually an incomplete file, we need also to check if there is a `complete` text for e2e test result. Otherwise, the result will show `All tests passed.` when the test is actually running and aborted unexpectedly, which is misleading.
> Handle unexpected error when the test is aborted

- pkg/agent/agent.go
- pkg/agent/route/route_linux.go
In networkPolicyOnly mode and proxyAll is enabled, the ifindex of antrea-gw0 in `nodeConfig`
is uninitialized, resulting in the failure to install the ip neighbor to antrea-gw0 due to
the fact that the ifindex of antrea-gw0 is wrong. Additionally, the ipsets storing the pairs
of Node IP and NodePort are not initialized and periodically synced. Consequently, this results
in the failure to sync the iptables rules that referring to the ipsets.
> Fix antrea-agent crashing with proxyAll enabled in networkPolicyOnly mode

- pkg/agent/agent.go
- pkg/agent/route/route_linux.go
Cherry pick of #6259 on release-1.14.
#6259: Fix antrea-agent crashing with proxyAll enabled in
> Automated cherry pick of #6259: Fix antrea-agent crashing with proxyAll enabled in

- pkg/agent/controller/networkpolicy/node_reconciler_linux.go
- pkg/agent/util/iptables/builder.go
- pkg/agent/util/iptables/builder_test.go
- pkg/agent/util/iptables/iptables.go
Needed by #6308
This PR adds more methods to build an iptables entries:
- `SetTargetDNATToDst`, setting DNAT destination IP and port.
This PR also updates the methods:
- `MatchCIDRSrc`, supporting an IP or CIDR as source.
- `MatchCIDRDst`, supporting an IP or CIDR as destination.
- `MatchIPSetSrc`, supporting ipset type of hashIPPort as destination IP and port.
- `MatchIPSetDst`, supporting ipset type of hashIPPort as source IP and port.
- Rename `MatchDstPort` to `MatchPortDst` to be consistent with other method.
- Rename `MatchSrcPort` to `MatchPortSrc` to be consistent with other method.
> Update iptables builder

- pkg/agent/flowexporter/exporter/exporter_test.go
- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
We always include the Pod labels IEs (for source and destination Pods), regardless of the value of the recordContents.podLabels configuration parameter. This simplifies the logic and the IPFIXExporter no longer needs to be aware of this configuration. There will be a minor size increase to the IPFIX records exported by the FlowAggregator when recordContents.podLabels is false, as we will need to include empty strings in the records for the 2 IEs.
We use an empty string when recordContents.podLabels is false, or when the endpoint is not a Pod. We use an empty JSON dictionary ("{}"), when the Pod has no labels.
Fixes #6386
> Always include Pod labels in FlowAggregator IPFIX template

- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
Cherry pick of #6379 on release-1.14.
#6379: Fix AntreaProxy not deleting stale UDP conntrack entries for
> Automated cherry pick of #6379: Fix AntreaProxy not deleting stale UDP conntrack entries for

- pkg/agent/util/net_linux.go
- pkg/agent/util/net_linux_test.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
Cherry pick of #6321 on release-1.15.
#6321: Remove unexpected AltName after rename interface (#6321)
> Automated cherry pick of #6321: Remove unexpected AltName after rename interface (#6321)

- pkg/agent/ipassigner/responder/arp_responder_test.go
- pkg/agent/ipassigner/responder/ndp_responder_test.go
- pkg/agent/util/nettest/packetconn.go
In the pkg/agent/util/nettest/ package.
The ARPResponder unit tests are updated to use this new fake. It will also be useful when writing unit tests for the NodeLatencyMonitor.
> Add fake implementation for net.PacketConn interface

- ci/run-k8s-e2e-tests.sh
In most cases, we'd like to run the whole Conformance tests for K8s compatibility verification, since there is no other tests using '--e2e-all', simply enable the whole Conformance tests when all are selected.
> Change Comformance test to whole Conformance tests when all are selected

- pkg/agent/util/net_linux.go
- pkg/agent/util/net_linux_test.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
Cherry pick of #6402 on release-1.14.
#6402: Remove unexpected AltName after rename interface (#6321)
> Automated cherry pick of #6402: Remove unexpected AltName after rename interface (#6321)

- pkg/agent/proxy/proxier_test.go
Refine test functions with multiple parameters and add some UDP Service tests.
> Refactor pkg/agent/proxy/proxier_test.go

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/feature-gates.md
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/features/antrea_features.go
In #5112, due to the limitations of the Go netlink library, AntreaProxy
would unconditionally delete conntrack entries added by kube-proxy in
conntrack zone 0. AntreaProxy was supposed to only delete its own entries
in conntrack zones 65520 or 65521. To address this, a feature was added
to isolate the relevant code.
After the merge of #6193, the netlink library was updated, allowing
AntreaProxy to precisely delete conntrack entries in zones 65520 or 65521.
It is now safe to enable the corresponding code by default.
Depends on #6379
> Promote feature CleanupStaleUDPSvcConntrack from Alpha to Beta

- Makefile
- build/images/base/build.sh
- build/images/ovs/build.sh
- ci/jenkins/jobs/macros.yaml
- ci/jenkins/test.sh
- hack/build-antrea-linux-all.sh
- hack/generate-manifest.sh
Run Multiple kind Jobs on same testbed.
Fixes #5734
> Run Multiple Kind CI Jobs on a single testbed

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- build/images/Dockerfile.build.controller.ubi
- build/images/base/Dockerfile.ubi
- build/images/ovs/CentOS.repo
- build/images/ovs/Dockerfile.ubi
- build/images/ovs/build.sh
- hack/build-antrea-linux-all.sh
Cherry pick of #5737 #6104 on release-1.15.
#5737: Upgrade base image of UBI to UBI9 (#5737)
#6104: Do not run tests when building OVS for UBI (#6104)
> Automated cherry pick of #5737: Upgrade base image of UBI to UBI9 (#5737) #6104: Do not run tests when building OVS for UBI 

- test/e2e/fixtures.go
- test/e2e/ipsec_test.go
- test/e2e/wireguard_test.go
Cherry pick of #6264 on release-2.0.
#6264: Skip IPSec/WireGuard e2e test when the Multicast feature is
> Automated cherry pick of #6264: Skip IPSec/WireGuard e2e test when the Multicast feature is

- ci/jenkins/test-mc.sh
- ci/jenkins/test-rancher.sh
- ci/jenkins/test-vmc.sh
- ci/jenkins/test.sh
- ci/jenkins/utils.sh
- ci/test-conformance-aks.sh
- ci/test-conformance-eks.sh
- ci/test-conformance-gke.sh
- docs/minikube.md
- hack/build-antrea-linux-all.sh
Cherry pick of #5937 on release-1.15.
#5937: Update BuildKit Configurations to Enhance Compatibility
> Automated cherry pick of #5937: Update BuildKit Configurations to Enhance Compatibility

- build/images/ovs/Dockerfile.windows
Indy’s Fulgan mirror is currently down, preventing the image from building. This is not the first time apparently, and the OpenSSL binaries are also available in Indy's Github repository. See https://www.indyproject.org/2020/06/16/openssl-binaries-moved-to-github/
In the future, we could even consider keeping a copy of the archive in downloads.antrea.io if needed.
> Download OpenSSL from Github for Windows Docker build

- ci/jenkins/test.sh
generate-manifest.sh generates manifests to the standard output by default, this means all feature changes in test.sh does not take effect now without file redirection. Add it back to save the changes to the local antrea.yml.
The bug is introduced by #6010 which has been merged, we need to merge this bug fix ASAP, otherwise, our e2e tests for other PRs might not be valid.
> Fix manifest generation step for e2e test

- test/e2e/fixtures.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
Logs were not being collected in case of failure while setting up the FLow Aggregator and its "dependencies" (e.g., ClickHouse). We make sure that logs are now collected, making it possible to troubleshoot such test failures
> [FlowAggregator e2e tests] Collect logs when setup fails

- pkg/agent/client/endpoint_resolver_test.go
Wait for informers to have synced before creating new runtime objects, to avoid the race condition between List and Watch with the fake clientset.
Fixes #6460
> [Flaky unit test] Fix TestEndpointResolver

- Makefile
Fix Syntax error while checking env variable in Makefile.
> Fix Syntax error while checking env variable in Makefile

- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.agent.ubuntu
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubi
- build/images/Dockerfile.build.controller.ubuntu
- build/images/Dockerfile.build.windows
- build/images/Dockerfile.simulator.build.ubuntu
- build/images/base/Dockerfile
- build/images/base/Dockerfile.ubi
- build/images/codegen/Dockerfile
- build/images/flow-aggregator/Dockerfile
- build/images/flow-aggregator/Dockerfile.coverage
- build/images/ovs/Dockerfile
- build/images/ovs/Dockerfile.ubi
- build/images/ovs/Dockerfile.windows
- docs/cookbooks/multus/build/cni-dhcp-daemon/Dockerfile
- multicluster/build/images/Dockerfile.build
- multicluster/build/images/Dockerfile.build.coverage
Recent versions of BuildKit supports build checks: https://docs.docker.com/reference/build-checks/
Because our Github CI uses a very recent version of buildx (through docker/setup-buildx-action), CI builds have been reporting warnings because we do not use the same casing for the "FROM" and "as" keywords in our Dockerfiles:
https://docs.docker.com/reference/build-checks/from-as-casing/
To avoid these warnings, we fix the casing in all Dockerfiles.
> Fix build warnings from BuildKit

- pkg/agent/agent.go
- pkg/ovs/ovsconfig/interfaces.go
- pkg/ovs/ovsconfig/ovs_client.go
- pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
- test/integration/ovs/ovs_client_test.go
We wait (for a maximum of 5s) for the datapath_id of the br-int OVS bridge to be reported in OVSDB, after creating the bridge and before checking supported datapath features. This prevents errors when querying the supported features before the ofproto-dpif provider has been initialized.
Fixes #6471
> Wait for OVS bridge datapath ID to be available after creating br-int

- build/images/base-windows/Dockerfile
Cherry pick of #6337 on release-2.0.
#6337: Fix mingw download in base Windows image (#6337)
> Automated cherry pick of #6337: Fix mingw download in base Windows image (#6337)

- pkg/agent/bgp/testing/mock_bgp.go
PRs #6447 and #6477 got merged around the same time, and the mock file for the BGP interface was not generated using the latest mockgen version.
> Add missing whitespace in generated mock file

- hack/update-codegen-dockerized.sh
- pkg/agent/monitortool/monitor.go
- pkg/client/clientset/versioned/typed/stats/v1alpha1/fake/fake_nodelatencystats.go
- pkg/client/clientset/versioned/typed/stats/v1alpha1/fake/fake_stats_client.go
- pkg/client/clientset/versioned/typed/stats/v1alpha1/nodelatencystats.go
- pkg/client/clientset/versioned/typed/stats/v1alpha1/stats_client.go
Not sure how we missed this when reviewing #6392
> Add plural exception for NodeLatencyStats in stats API

- docs/service-loadbalancer.md
- pkg/agent/types/annotations.go
- pkg/controller/serviceexternalip/controller.go
- pkg/controller/serviceexternalip/controller_test.go
- test/e2e/framework.go
- test/e2e/service_externalip_test.go
Users want to share LoadBalancerIP between multiple Services when they face external IP shortage. It's possible to do it when the Services sharing an IP meet the requirements:
* The Services use different ports
* The Services use the `Cluster` external traffic policy, or they have identical Endpoints.
However, the ability of using any IP that is already allocated to another Service may incur a security risk that a Service can "steal" LoadBalancer traffic intended for another Service.
To support the use case without introducing the security risk, we use the annotation `service.antrea.io/allow-shared-load-balancer-ip: true` on Services to restrict IPs that can be shared. Services without the annotation will continue to have their LoadBalancerIPs exclusively used. Services with the …
> Support shared LoadBalancerIP for multiple Services

- .github/workflows/go.yml
- .github/workflows/kind.yml
- ci/jenkins/test-mc.sh
- ci/jenkins/test-vmc.sh
It seems that codecov upload has been broken for a while for ci/jenkins/test-vmc.sh and ci/jenkins/test-mc.sh. The file pattern must be quoted when calling the codecov binary, or the glob will be expanded by the shell instead of by codecov (which is bad because we want the glob to be expanded in the context of the search directory).
We also set "disable_search" to "true" when using the codecov-action in Github workflows. This action uses the codecov CLI and there is no need to keep search enabled when providing an explicit and comprehensive list of files to include in the report.
> Fix codecov upload for Jenkins CI scripts

- build/charts/antrea-windows/conf/Run-AntreaAgent.ps1
- build/charts/antrea-windows/conf/ovs/Install-OVSDriver.ps1
- build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
- build/images/Dockerfile.build.windows
- build/yamls/antrea-windows-with-ovs.yml
- build/yamls/antrea-windows.yml
- ci/jenkins/test.sh
- docs/windows.md
- hack/windows/Install-OVS.ps1
- hack/windows/Uninstall-OVS.ps1
1. Add logic to check the installed OVSext drivers, if only the desired version
of driver is already installed, skip the installation; otherwise, remove the
existing the drivers and re-install.
2. Add logic to check the installed VC redistributable files, if the existing
installd vc_redist version is equal to or higher than the lowest requirement,
skip the installation; otherwise re-install the files provided in the image.
3. Optimize the logic of maintaining the system paths by removing the duplicated
path.
4. Optimize Uninstall-OVS script by removing OVS bin paths from the system path
after it is deleted.
> [Windows] Optimize the containerized OVS installation

- ci/jenkins/jobs/macros.yaml
Added sudo to the clean job script to align with the login process and ensure correct access to the necessary secrets. The clean job was failing to access the correct secrets because it was not using sudo, whereas the login process used with Jenkins account.
> Update cloud job cleanup scripts for correct secret access

- build/images/scripts/install_cni_chaining
The chaining CNI conf was not created correctly under two conditions:
1. If there is non CNI conf file in the directory, like a kubeconfig required by the primary CNI.
2. If the CNI conf file is created but not completely written yet.
The patch ensures it only selects valid CNI conf and waits for it to be written before using it to create the chaining CNI conf.
Fixes #6499
> Fix install_cni_chaining not creating CNI conf correctly in some cases

- docs/contributors/github-labels.md
There has not been a CLA for this project for years, at least not since it became a CNCF project.
> Remove references to VMware CLA in github-labels.md

- build/images/scripts/install_cni_chaining
Cherry pick of #6506 on release-1.15.
#6506: Fix install_cni_chaining not creating CNI conf correctly in
> Automated cherry pick of #6506: Fix install_cni_chaining not creating CNI conf correctly in

- CONTRIBUTING.md
- ci/jenkins/jobs/projects-lab.yaml
> To support running ipv4 e2e tests in Kind

- pkg/controller/egress/controller.go
- pkg/controller/egress/controller_test.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/util/k8s/pod.go
When calculating AddressGroups, terminated Pods should be excluded because their IPs can be recycled and reused by other active Pods.
When calculating AppliedToGroups and EgressGroups, terminated Pods could be excluded as their network resources including network interfaces have been deleted.
Fixes #6507
> Exclude terminated Pods from group members

- ci/kind/validate-metrics-doc.sh
- docs/prometheus-integration.md
Cherry pick of #6514 on release-2.0.
#6514: Fix Prometheus metrics doc (#6514)
> Automated cherry pick of #6514: Fix Prometheus metrics doc (#6514)

- pkg/controller/egress/controller.go
- pkg/controller/egress/controller_test.go
- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/util/k8s/pod.go
Cherry pick of #6508 on release-2.0.
#6508: Exclude terminated Pods from group members (#6508)
> Automated cherry pick of #6508: Exclude terminated Pods from group members (#6508)

- ci/kind/kind-setup.sh
- ci/kind/test-e2e-kind.sh
- docs/windows.md
- hack/netpol-generator/test-kind.sh
- hack/windows/Prepare-Node.ps1
- multicluster/test/e2e/framework.go
- pkg/antctl/raw/check/installation/command.go
- test/e2e/framework.go
* Add detailed containerd version requirements for various Kubernetes versions.
* Upgrade agnhost image for Windows2022 compatibility.
> Update Antrea Windows requirements for containerd and Kubernetes

- cmd/antrea-agent/agent.go
- pkg/agent/secondarynetwork/init.go
- pkg/agent/secondarynetwork/init_linux.go
- pkg/agent/secondarynetwork/init_windows.go
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- pkg/agent/secondarynetwork/podwatch/sriov.go
Physcial network interface is attached on the OVS bridge with SecondaryNetwork feature enabled. Antrea uses a global configuration flow-restore-wait='true' to ensure that OVS OpenFlow entries can start working after the dependencies are ready. A connectivity issue exists if a setup uses the Node NIC as secondary network interface and connects the NIC to OVS bridge before removing the flow-restore-wait option.
This change ensures agent attaches the physical network interface to the secondary OVS bridge after the global flow-restore-wait option is removed.
Fix: #6448
> [SecondaryNetwork] Attach OVS uplink after removing flow-restore-wait flag

- .github/workflows/conformance.yml
When triggering Manually upstream conformance test on Linux, if the input kubernetes version has no corresponding kind node image, the job will build a kind Node image with the Kubernetes source code, and create Kind Cluster with local Node image.
> Add support for building local kind Node image

- .github/workflows/kind.yml
- ci/kind/test-e2e-kind.sh
- docs/antrea-proxy.md
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/agent/route/interfaces.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/route/route_windows.go
- pkg/agent/route/route_windows_test.go
- pkg/agent/route/testing/mock_route.go
- pkg/agent/util/iptables/iptables.go
- pkg/agent/util/iptables/testing/mock_iptables_linux.go
- test/e2e/proxy_test.go
Depends on #6381
Resolve #6232
To ensure full functionality of AntreaProxy, except for handling ClusterIP from Nodes,
even when kube-proxy in iptables mode is present, certain key changes are implemented
when proxyAll is enabled:
The jump rules for the chains managed by Antrea, `ANTREA-PREROUTING` and `ANTREA-OUTPUT`
in nat table, are installed by inserting instead of appending to bypass the chain
`KUBE-SERVICES` performing Service DNAT managed by kube-proxy. Antrea ensures that
the jump rules take precedence over those managed by kube-proxy.
The iptables rules of nat table chain `ANTREA-PREROUTING` are like below, and they are
similar in chain `ANTREA-OUTPUT`.
```
-A ANTREA-PREROUTING -m comment --comment "Antrea: DNAT external to NodePort packets" -m set --match-set ANTREA-NODEPORT-IP …
```
> Ensure full functionality of AntreaProxy with proxyAll enabled when kube-proxy presents

- hack/windows/Install-OVS.ps1
An "Access is denied" error is possibly returned when importing certificate into the trusted publishers store at the first time on a fresh Windows 2022 Node.
To resolve the issue, this change uses the "Add" method provided by certificate stre as an alternative when importing to trusted publishers.
Fix: #6530
> [Windows] Fix access denied issue in OVS cert import

- pkg/agent/nodeportlocal/k8s/annotations.go
- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/npl_agent_test.go
- pkg/agent/nodeportlocal/portcache/port_table.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_others_test.go
- pkg/agent/nodeportlocal/portcache/port_table_test.go
- pkg/agent/nodeportlocal/portcache/port_table_windows.go
- pkg/agent/nodeportlocal/portcache/port_table_windows_test.go
- pkg/agent/nodeportlocal/rules/types.go
The NodePortLocal cache bound a Pod's NodePortLocal rules to its Pod IP. However, a Pod IP can be recycled and allocated to another Pod when it runs into succeeded or failed stage, which causes more than one Pod to share a Pod IP. When the terminated Pod was deleted, NodePortLocal controller incorrectly deleted the rules that belong to another Pod because they have the same IP.
The patch fixes it by binding the NodePortLocal rules to its Pod key (namespace + name). The podToIP cache is no longer needed as we can clean up rules by Pod key.
Fixes #6527
> Fix NodePortLocal rules being deleted incorrectly due to PodIP recycle

- pkg/agent/nodeportlocal/k8s/annotations.go
- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/npl_agent_test.go
- pkg/agent/nodeportlocal/portcache/port_table.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_others_test.go
- pkg/agent/nodeportlocal/portcache/port_table_test.go
- pkg/agent/nodeportlocal/portcache/port_table_windows.go
- pkg/agent/nodeportlocal/portcache/port_table_windows_test.go
- pkg/agent/nodeportlocal/rules/types.go
Cherry pick of #6531 on release-1.15.
#6531: Fix NodePortLocal rules being deleted incorrectly due to
> Automated cherry pick of #6531: Fix NodePortLocal rules being deleted incorrectly due to

- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/templates/agent/clusterrole.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- docs/feature-gates.md
- pkg/agent/controller/bgp/controller.go
- pkg/agent/controller/bgp/controller_test.go
- pkg/agent/types/annotations.go
- pkg/agent/types/bgppolicy.go
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/features/antrea_features.go
This commit implements the controller of API `BGPPolicy`, designed to advertise
Service IPs, Egress IPs, and Pod IPs to BGP peers from selected Kubernetes Nodes.
According to the spec of `BGPPolicy`, the Node selector is used to select Nodes
to which a `BGPPolicy` is applied. Multiple `BGPPolicies` can be applied to the
same Node. However, only the oldest `BGPPolicy` will be effective on a Node,
with others serving as alternatives. The effective one may be changed in the
following cases:
- The current effective BGPPolicy is updated and not applied to the Node.
- The current effective BGPPolicy is deleted.
The BGP server instance is only created and started for the effective BGPPolicy on
a Node. If the effective BGPPolicy is changed, the corresponding BGP server instance
will be terminated …
> Implement the controller for API BGPPolicy

- pkg/apiserver/registry/stats/nodelatencystats/rest.go
- pkg/apiserver/registry/stats/nodelatencystats/rest_test.go
In last PR https://github.com/antrea-io/antrea/pull/6392, we have defined some rest apis for `nodelatencystats`.
We have implemented the inner operations by `cache.Indexer` and support query `nodelatencystats` by api.
Example:
```bash
antrea git:(feat/impl-node-latency-query-api) ✗ kubectl get nodelatencystats
SOURCENODENAME       PEERNODELATENCYSTATS
kind-worker          [map[nodeName:kind-worker2 targetIPLatencyStats:[map[lastMeasuredRTTNanoseconds:1097048 lastRecvTime:2024-06-30T03:21:02Z lastSendTime:2024-06-30T03:21:12Z targetIP:10.244.1.1]]] map[nodeName:kind-control-plane targetIPLatencyStats:[map[lastMeasuredRTTNanoseconds:1143333 lastRecvTime:2024-06-30T03:21:02Z lastSendTime:2024-06-30T03:21:12Z targetIP:10.244.0.1]]]]
kind-worker2         [map[nodeName:kind-control-plane …
```
> Add nodelatencystats rest apis implementation.

- cmd/antrea-agent/agent.go
The NodeLatencyMonitor was not starting (more precisely, the monitorLoop method was never called). This is because NewNodeLatencyMonitor was called *after* starting the informer factory. This means that the informer created in NewNodeLatencyMonitor was never started, and that WaitForNamedCacheSync was blocking indefinitely.
With this change, we ensure that NewNodeLatencyMonitor is called *before* starting the informer factory. The Run method is still called at the end of Agent "initialization", once the datapath has been configured.
Note that it is not clear that WaitForNamedCacheSync is really needed for the NodeLatencyMonitor. However, it is probably fine to use the same "pattern" as for our other controllers.
> Fix NodeLatencyMonitor not starting

- test/e2e/bgppolicy_test.go
- test/e2e/fixtures.go
- test/e2e/framework.go
> Add e2e tests for BGPPolicy

- .github/workflows/conformance.yml
When K8s version is not specified, it's supposed to use default version. The step of building local image is not implemented to support empty input, it should be skipped when K8s version is empty.
> Only try to build local image if K8s version is specified

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- .github/workflows/conformance.yml
- .github/workflows/kind.yml
- .github/workflows/kind_ubi.yml
- .github/workflows/trivy_scan_before_release.yml
For most workflows, we want to use the "docker" driver, while the "docker-container" driver should be used when images need to be pushed to the registry (so we can use registry-based caching).
When using the "docker-container" driver, images are built in a build container, and there is no access to the docker image store (see https://github.com/moby/buildkit/issues/2343). This means that when building a new image, we cannot use "local" images as base images. This is an issue because the base image may not exist yet in the directory, and because we may want to use a modified base image which is not the same as the one in the registry.
> Use appropriate docker driver in Github workflows

- docs/api.md
- docs/feature-gates.md
The feature is quite simple at the moment, so maybe no need for a dedicated documentation page.
Fixes #6551
> Add documentation for NodeLatencyMonitor feature

- docs/api.md
- docs/feature-gates.md
Cherry pick of #6561 on release-2.1.
#6561: Add documentation for NodeLatencyMonitor feature (#6561)
> Automated cherry pick of #6561: Add documentation for NodeLatencyMonitor feature (#6561)

- ci/jenkins/jobs/projects-lab.yaml
> Add logs for the kind tests in jenkins

- pkg/antctl/raw/check/cluster/command.go
The image tag missed "v" when built for a released antctl.
The patch also makes test images configurable to support scenarios that hardcoded images are not accessible.
Fixes #6563
> antctl: fix cluster checker image

- pkg/antctl/raw/check/cluster/command.go
- pkg/antctl/raw/check/constants.go
- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/command_test.go
- pkg/antctl/raw/check/installation/test_denyall.go
- pkg/antctl/raw/check/installation/test_podtointernet.go
- pkg/antctl/raw/check/installation/test_podtopodinternode.go
- pkg/antctl/raw/check/installation/test_podtopodintranode.go
- pkg/antctl/raw/check/installation/test_podtoservice.go
To support scenarios that hardcoded images are not accessible.
Depends on https://github.com/antrea-io/image-utils/pull/39
> antctl: unify checker image and make it configurable

- docs/antrea-network-policy.md
The ACNP doc wrongly describes egress to have a "from" field. It only supports "to" field.
> Doc: ACNP Egress Rule Doesn't Support "from"

- hack/generate-manifest.sh
Some alpha features were not tested because of it.
> e2e: fix feature-gates being overridden when specified multiple times

- pkg/apiserver/registry/stats/nodelatencystats/rest.go
- pkg/apiserver/registry/stats/nodelatencystats/rest_test.go
Attempts to fix issue #6569 about `creationTimestamp` field is always null in `NodeLatencyStats`.
Awaiting review.
> Added initialisation of  creationTimestamp when creating instances of NodeLatencyStats .

- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/pipeline_other.go
- pkg/agent/openflow/pipeline_windows.go
- pkg/agent/openflow/pod_connectivity_test.go
When promiscuous mode is enabled, OVS incorrectly forwards packets destined for
non-local IP addresses from the uplink to the host interface. Due to IP forwarding
being enabled, these packets are re-sent to br-int according to the default route
and are eventually forwarded to the uplink. Since the source MAC of these packets
has been changed to the local host’s MAC, this can potentially cause errors on the switch.
This patch matches dstIP field in ClassifierTable to ensure proper packet handling
and preventing unintended forwarding.
> Match dstIP in Classifier to address windows promiscuous mode issue

- docs/egress.md
To achieve the desired egress behavior, a dummy interface that is always down is automatically created on the Node hosting the egress IP.
#6310
> Update Egress Document to include egress dummy interface

- pkg/agent/proxy/topology.go
- pkg/agent/proxy/topology_test.go
This commit is to be consistent with kube-proxy's behavior for Topology
Aware Routing feature.
For `service.kubernetes.io/topology-mode` hint annotation, any non-empty
and non-disabled values for the annotation are acceptable to enable
Topology Aware Routing for a Service.
> Fix hint annotation implementation in AntreaProxy

- test/e2e/egress_test.go
Fix IPv6 address parameter in testEgressClientIPFromVLANSubnet
Fixes: #6617
> Fix IPv6 address parameter in testEgressClientIPFromVLANSubnet

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- cmd/antrea-agent/options.go
- cmd/antrea-agent/options_windows.go
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/route/route_windows.go
- pkg/agent/util/iptables/iptables.go
- pkg/agent/util/iptables/testing/mock_iptables_linux.go
- pkg/config/agent/config.go
- test/integration/agent/route_test.go
We expose 2 new configuration parameters for the Agent: snatFullyRandomPorts and egress.snatFullyRandomPorts. When the first one is set to true, the MASQUERADE iptables rules used to implement "local" Node SNAT will use randomized source port mappings. When the second one is set to true, the SNAT iptables rules used to implement Egress SNAT will use randomized source port mappings. This is achieved with the `--random-fully` iptables flag.
These new configuration parameters are only supported on Linux Nodes. They require iptables `>= 1.6.2`, which is not a problem with the standard antrea-agent container images. They also require Linux kernel `>= 3.13` and `>= 3.14` respectively, but these are very old releases so we can ignore this requirment, which is consistent with the K8s …
> Support --random-fully for iptables SNAT / MASQUERADE rules

- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
If destination protocol/port isn't provided when destination is service in antrea traceflow, it just uses destinaton service's IP(clusterIP) and runs traceflow as Pod-to-IP(icmp) case which is incorrect.
To fix this, we use the first protocol/port from the service's 'ports' list as default value.
Fixes #6594
> Use default protocol/port when destination is service in  antrea traceflow

- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
One rule was already using `--random-fully` unconditionally prior to it. The fact that no issue has ever been reported indicates that `--random-fully` should be supported by all systems running Antrea...
> Always check for random-fully support

- pkg/flowaggregator/exporter/ipfix.go
The template ID is only available after the exporter has been initialized.
With this fix, we avoid the following error for the first data record to be exported:
```
error when sending IPFIX record: error when doing sanity check:process:
templateID 0 does not exist in exporting process
```
> [Flow Aggregator] Fix template ID error in IPFIX exporter

- pkg/flowaggregator/exporter/ipfix.go
Cherry pick of #6630 on release-2.1.
#6630: Fix template ID error in IPFIX exporter
> Automated cherry pick of #6630: Fix template ID error in IPFIX exporter

- pkg/flowaggregator/exporter/ipfix.go
When the IPFIX exporter is stopped in the Flow Aggregator, the connection to the collector should be explicitly closed.
> [FlowAggregator] Close connection to IPFIX collector on Stop

- hack/release/prepare-assets.sh
It was an oversight not to distribute an antctl binary that can run on Apple ARM-based chips.
Note that macOS bundles an emulation solution (Rosetta 2) to enable x86 applications to run on their ARM-based chips, so `antctl-darwin-x86_64` can typically be used on these machines. However, it is common practice for OSS projects to provide a native arm64 binary.
> Add antctl-darwin-arm64 to release assets

- pkg/flowaggregator/exporter/ipfix.go
Cherry pick of #6635 on release-2.1.
#6635: Close connection to IPFIX collector on Stop
> Automated cherry pick of #6635: Close connection to IPFIX collector on Stop

- .github/workflows/build.yml
Two shell if conditions in .github/workflows/build.yml were not valid syntactically. As a result, the "latest" images for the Antrea Agent and Controller were not updated for almost 2 months (for the amd64 arch).
> Fix some if conditions in Github workflows

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/test.sh
- cmd/antrea-agent/options.go
o.config.Egress.SNATFullyRandomPorts should be checked for nil regardless of
whether the egress feature is enabled.
> Resolve Windows agent crash issue caused by egressSNATRandomFully

- pkg/agent/util/syscall/syscall_windows.go
* Refactored ListIPForwardRows to deep copy IP forwarding table rows.
* Removed unsafe.Slice and replaced with manual pointer dereferencing and copying.
This change addresses a potential fault memory issue when iterating through the IP forwarding table,
caused by the use of slices after corresponding memory has been freed, leading to access failure.
> Replace unsafe.Slice with memory copying to avoid potential fault memory issue

- build/charts/antrea/templates/simulator/statefulset.yaml
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubuntu
- build/images/Dockerfile.build.migrator
- build/images/Dockerfile.controller.ubuntu
- build/images/Dockerfile.simulator.build.ubuntu
- build/images/base/Dockerfile
- build/images/base/Dockerfile.ubi
- build/images/base/build.sh
- build/images/flow-aggregator/Dockerfile
- build/images/flow-aggregator/Dockerfile.coverage
- build/images/ovs/Dockerfile
- build/images/ovs/Dockerfile.windows
- build/images/ovs/apply-patches.sh
- build/images/ovs/build.sh
- hack/build-antrea-linux-all.sh
- multicluster/build/images/Dockerfile.build.coverage
Upgrade to ubuntu:24.04 in most places (except for a few build / test
images which will be updated later on). In particular ubuntu:24.04 is
now the base image for antrea/antrea-agent-ubuntu and
antrea/controller-ubuntu.
In order for our current version of OVS (2.17.7) to build correctly on
Ubuntu 24.04, some "recent" patches have to be applied manually.
After this change, the antrea/antrea-agent-ubuntu image is slightly
bigger (344MB -> 372MB uncompressed), and the size increase seems to be
driven by some systemd libraries.
> Upgrade Ubuntu to 24.04 (Noble)

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/test.sh
Cherry pick of #6669 on release-2.0.
#6669: Add docker credentials to windows CI to avoid rate limit
> Automated cherry pick of #6669: Add docker credentials to windows CI to avoid rate limit

- .github/workflows/go.yml
- Makefile
Running "make antctl" is common when someone wants to build antctl for the current machine. The current target builds 3 versions of the antctl binary: one for Linux, one for Windows and one for Darwin (using the architecture of the current machine). This seems unnecessary and potentially confusing. We change the antctl target to be an alias of antctl-release. Running "make antctl" will now produce a single binary named "antctl", which can be run on the current machine.
For backwards-compatibility, we preserve the ability to run "make antctl-linux", "make antctl-windows", and "make antctl-darwin". These 3 targets combined will produce the 3 antctl binaries described above.
Finally, we update the Github workflow in charge of validating the antctl Go build. We now have one dedicated step for …
> Change antctl make target

- docs/antrea-l7-network-policy.md
- pkg/agent/controller/networkpolicy/l7engine/reconciler.go
- pkg/agent/controller/networkpolicy/l7engine/reconciler_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- test/e2e/l7networkpolicy_test.go
Current logs by Suricata when enableLogging is set, logs the wrong packet of RST instead of the original TCP packet, and remains an existing bug in Suricata. 
This solution modifies the design to remove enableLogging in L7, keep it in L4, and instead configure Suricata to log Packet info for all alert events.
Also add Packet test to E2E tests.
Decode the packet `dtwWezuaHlOhfWpNgQAAAQgARQAAjbT0QABABm9cCgoBBAoKAQOJUgBQa2w1WZlax6yAGAH7nAIAAAEBCAorcsv8RSTwQkdFVCAvYWRtaW4vaW5kZXguaHRtbCBIVFRQLzEuMQ0KSG9zdDogMTAuMTAuMS4zDQpVc2VyLUFnZW50OiBjdXJsLzcuNzQuMA0KQWNjZXB0OiAqLyoNCg0K`
-> `10.10.1.4 → 10.10.1.3 HTTP GET /admin/index.html HTTP/1.1`
Fixes #6636.
> Fix L7NP enable logging wrong packet

- pkg/controller/egress/controller.go
- pkg/controller/egress/controller_test.go
- pkg/controller/externalippool/controller.go
The validation webhook for ExternalIPPools prevents modifications to IP address ranges. However, it is theoretically possible for an ExternalIPPool to be deleted, then recreated immediately with different IP address ranges, and for the Egress controller to only process the Egress resources referencing the pool once, *after* the CREATE event has been handled by the ExternalIPPool controller. This is because the ExternalIPPool controller is in charge of notifying the Egress controller through a callback (event handler) mechanism, and that multiple events for the same ExternalIPPool name can be merged in the workqueue.
With this change, we try to ensure the same "observable" behavior for the Egress controller, regardless of whether the DELETE and CREATE events have been merged or not. The …
> Handle ExternalIPPool range changes in Egress controller

- multicluster/controllers/multicluster/member/resourceimport_controller_test.go
- pkg/util/podstore/podstore.go
- pkg/util/podstore/podstore_test.go
- In multicluster tests, stop using a pointer to the Custom Resource as the workqueue key, and instead use a NamespacedName value, which matches actual usage in the controller.
- In the PodStore implementation (which keeps track of Pod deletion events with timestamps), use the Pod's UID as the workqueue key, instead of a pointer to the Pod object. It is uncommon to use a pointer as the workqueue key (even though it is functionally correct here). By using the string UID as the key, we could theoretically reduce memory usage, as we don't need to hold the Pod object in memory for a delay of 5 minutes, and the object could be garbage collected right after deletion. The Flow Aggregator in particular uses the PodStore for all Pods in the cluster (while for the Antrea Agent it is only local …
> Improve a couple of workqueue usages

- test/e2e/antreapolicy_test.go
- test/e2e/basic_test.go
- test/e2e/batch_test.go
- test/e2e/connectivity_test.go
- test/e2e/egress_test.go
- test/e2e/fixtures.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
- test/e2e/infra/vagrant/playbook/roles/common/tasks/busybox.yml
- test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml
- test/e2e/networkpolicy_test.go
- test/e2e/proxy_test.go
- test/e2e/service_test.go
- test/e2e/wireguard_test.go
Cherry pick of #6000 on release-1.15.
#6000: [tests/e2e]: Remove all references to busybox in e2e tests
> Automated cherry pick of #6000: [tests/e2e]: Remove all references to busybox in e2e tests

- pkg/apiserver/apiserver.go
IPPool is also used when the SecondaryNetwork is enabled, so fix the condition to run IPPool webhook handler as well when SecondaryNetwork feature gate is enabled.
> Run IPPool webhook handler when SecondaryNetwork is enabled

- pkg/agent/util/ipset/ipset.go
The error returned from `Cmd.Run` is not very useful, for example, "error destroying ipset ANTREA-POL-F7B29A365E132446-4: exit status 1".
Ths patch adds the command's output to the error, for example, "error destroying ipset ANTREA-POL-4F5505D534DEB0EF-4, err: exit status 1, output: ipset v7.19: Set cannot be destroyed: it is in use by a kernel component".
For #6706
> Log ipset command output on failure

- docs/antctl.md
- pkg/agent/apis/types.go
- pkg/agent/apiserver/apiserver.go
- pkg/agent/apiserver/handlers/bgppeer/handler.go
- pkg/agent/apiserver/handlers/bgppeer/handler_test.go
- pkg/agent/controller/bgp/controller.go
- pkg/agent/controller/bgp/controller_test.go
- pkg/antctl/antctl.go
- pkg/antctl/command_list_test.go
- pkg/querier/querier.go
- pkg/querier/testing/mock_querier.go
Add `antctl get bgppeers` agent command to print current status of all BGP peers
of effective BGP policy applied on the local Node.
For https://github.com/antrea-io/antrea/issues/6209
> Add "antctl get bgppeers" agent command

- pkg/controller/networkpolicy/store/group.go
The intention here should be to initialize a slice with a capacity of   `len(g.ChildGroups)` rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
> fix: fix slice init length

- pkg/monitor/controller.go
The Run method of controllers usually never returns until the stop channel is closed. The controllerMonitor seems to be the exception, as it returns after "initialization", despite the Run method being invoked in a separate goroutine. This leads to a confusing message in the Antrea Controller logs, informing us that AntreaControllerMonitor is shutting down.
> Block on stopCh in Run method of controllerMonitor

- cmd/flow-aggregator/flow-aggregator.go
- pkg/flowaggregator/cluster_uuid.go
- pkg/flowaggregator/cluster_uuid_test.go
- pkg/flowaggregator/exporter/clickhouse.go
- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
- pkg/flowaggregator/exporter/s3.go
- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
Before this change, the cluster UUID was strictly required by the S3Exporter and by the ClickHouseExporter, but somewhat optional for the IPFIXExporter (if not available after a certain timeout, a random UUID was generated and used to compute the IPFIX observation domain ID). Furthermore, every exporter by responsible for calling getClusterUUID independently, and that was the only reason for their implementations to require access to the K8s client.
I think it makes more sense to make things more uniform, and require the cluster UUID to be available regardless of which exporters are enabled. We can retrieve the cluster UUID once during FlowAggrgator initialization, then pass it along to all exporters which need it.
> Always require the cluster UUID in the FlowAggregator

- pkg/util/channel/channel_test.go
I have observed the test failing in Github CI, and I was able to reproduce locally by setting GOMAXPROCS=2.
When using the race detector (-race flag), it usually takes 25ms for the condition function in assert.Eventually to run successfully on my laptop. However, it sometimes spikes to 100+ms, and then the test fails, as the timeout is set to 100ms.
My take is that there could be too much contention between the channel logic and the goroutine performing the checks. The issue only occurs when using the race detector.
To avoid the issue, we use a timeout of 500ms and we set the tick period to 50ms. This is more than sufficient on my machine. If we see the failure in CI again, we can always double these values.
We also fix the error log for the test, as the previous log would never print …
> Fix flaky TestSubscribe test in pkg/util/channel

- pkg/agent/monitortool/monitor.go
- pkg/agent/monitortool/monitor_test.go
* Add missing crdInformerFactory.Start call for TestNodeAddUpdateDelete to avoid cache sync error logs.
* Add extra logging for TestUpdateMonitorPingInterval, which has been failing infrequently in CI. I cannot figure out the reason for the failures, nor have I been able to reproduce it locally, so adding some logs may help.
> Update NodeLatencyMonitor unit tests

- pkg/apiserver/apiserver.go
- pkg/controller/networkpolicy/tier.go
- pkg/controller/networkpolicy/tier_test.go
System Tier initialization should ideally wait for the Tier informer's cache to sync before using the lister.
Otherwise we may think that the system Tiers have not been created yet when in fact it is just the informer that has not completed the initial List operation.
Additionally, we improve the logic in system Tier initialization:
* After every failed API call, we should probably check the state of the informer cache again (via the lister) and decide which step is needed next (creation / update / nothing). In case of a failed create or update, this gives us the opportunity to check again if the Tier actually exists, and if yes, what its priority is.
* AlreadyExists is no longer treated differently for create. The reason is that if the Tier already exists and for some reason it was not …
> More robust system Tier creation / update

- test/e2e/proxy_test.go
After creating or updating a Service, wait for 2 seconds before running traffic tests to ensure the Service is fully realized.
Add a timestamp to help debug this test in the future.
Fixes #6704
> Fix flaky e2e test TestProxyLoadBalancerModeDSR

- pkg/agent/controller/networkpolicy/node_reconciler_linux.go
- pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Fix #6706 
This commit addresses an issue where stale ipset or iptables chain is
not deleted during NodeNetworkPolicy updates or deletions. The root cause
is that the ipset or iptables chain is still referenced by other iptables
rules during the deletion or update attempt. The fix ensures proper order
of ipset and iptables synchronization.
> Fix issue with ipset or iptables chain removal during NodeNetworkPolicy updates or deletions

- pkg/agent/controller/networkpolicy/node_reconciler_linux.go
- pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
Cherry pick of #6707 on release-2.1.
#6707: Fix issue with ipset or iptables chain removal during
> Automated cherry pick of #6707: Fix issue with ipset or iptables chain removal during

- pkg/apiserver/apiserver.go
- pkg/controller/networkpolicy/tier.go
- pkg/controller/networkpolicy/tier_test.go
Cherry pick of #6696 on release-2.1.
#6696: More robust system Tier creation / update (#6696)
> Automated cherry pick of #6696: More robust system Tier creation / update (#6696)

- docs/antrea-node-network-policy.md
- pkg/agent/controller/networkpolicy/node_reconciler_linux.go
- pkg/agent/controller/networkpolicy/node_reconciler_linux_test.go
- pkg/agent/types/networkpolicy.go
- pkg/agent/util/iptables/builder.go
- pkg/agent/util/iptables/builder_test.go
- pkg/agent/util/iptables/iptables.go
- pkg/controller/networkpolicy/validate.go
- pkg/controller/networkpolicy/validate_test.go
- test/e2e/nodenetworkpolicy_test.go
For #6525
This commit introduces limited support for traffic logging in Node
NetworkPolicy. The limitations are:
- Traffic logs are written only to the system log (not managed by Antrea).
Users can filter logs using syslog filters.
- The `LogLabel` for Node NetworkPolicy is restricted to a maximum of
12 characters.
Node NetworkPolicy's data path is implemented via iptables. An iptables
"non-terminating target" `LOG` is added before the final matching rule to
log packets to the system kernel log. The logs provide packet match details,
such as:
```
Sep  2 10:31:07 k8s-node-control-plane kernel: [6657320.789675] Antrea:I:Allow:allow-http:IN=ens224 OUT= MAC=00:50:56:a7:fb:18:00:50:56:a7:23:47:08:00 SRC=10.10.0.10 DST=192.168.240.200 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=52813 DF PROTO=TCP …
```
> Add `EnableLogging` and `LogLabel` supports for Node NetworkPolicy

- pkg/agent/util/net_linux.go
PrepareHostInterfaceConnection should return the bridged interface name if the host interface is already attached to the OVS bridge.
> [SecondaryNetwork] Fix agent crash if host interface is already attached to OVS bridge

- pkg/apiserver/apiserver.go
Cherry pick of #6691 on release-2.1.
#6691: Run IPPool webhook handler when SecondaryNetwork is enabled.
> Automated cherry pick of #6691: Run IPPool webhook handler when SecondaryNetwork is enabled.

- multicluster/cmd/multicluster-controller/options.go
- multicluster/cmd/multicluster-controller/options_test.go
- multicluster/embed.go
The MultiClusterConfig struct does not have yaml tags, only json tags. Therefore, trying to unmarshal it as YAML (by calling yaml.UnmarshalLenient) will not work, and will show a log indicating that strict unmarshalling has failed. The resulting struct object will be all empty, since none of the fields can be decoded without a tag.
A key observation is that calling yaml.UnmarshalLenient does not serve any purpose, as we are also calling runtime.DecodeInto (which will first convert the YAML data to JSON data, before unmarshalling). Hence we can just remove the call to yaml.UnmarshalLenient.
We add a couple of unit tests, and in particular we validate that the default controller_manager_config.yaml config can be unmarshalled (strictly) to MultiClusterConfig. While this is slightly …
> Avoid error log when unmarshalling config for MC controller

- pkg/agent/util/syscall/syscall_windows.go
- pkg/agent/util/syscall/syscall_windows_test.go
uintptr cannot be stored in variable before conversion back to Pointer. This is because the variable is an integer with no pointer semantics, even if a uintptr holds the address of some object, the garbage collector will not update that uintptr's value if the object moves, nor will that uintptr keep the object from being reclaimed.
The issue can be detected by checkptr when running unit test with race detector:
checkptr: pointer arithmetic result points to invalid allocation
```
pFirstRow := uintptr(unsafe.Pointer(&table.Table[0]))
row := *(*MibIPForwardRow)(unsafe.Pointer(pFirstRow + rowSize*uintptr(i)))
```
While it can be fixed by performing both conversions in the same expression like below, using `unsafe.Slice` to get the slice is much simpler.
```
row := …
```
> Fix invalid conversion between unsafe.Pointer and uintptr

- pkg/agent/util/syscall/syscall_windows.go
- pkg/agent/util/syscall/syscall_windows_test.go
Cherry pick of #6664 on release-2.1.
#6664: Replace unsafe.Slice with memory copying to avoid potential
> Automated cherry pick of #6664: Replace unsafe.Slice with memory copying to avoid potential

- hack/update-codegen.sh
- multicluster/hack/update-codegen.sh
Starting with git v2.39.4, the directory ownership checks that were previously introduced in v2.30.3 were extended to cover cloning local repositories, which is what we do in update-codegen-dockerized.sh.
While previously, we didn't need to mark source .git directory as "safe", it is now required.
See https://fossies.org/linux/git/Documentation/RelNotes/2.39.4.txt
> Fix codegen for recent versions of git

- docs/antrea-network-policy.md
> Add documentation for except support in ipBlock

- multicluster/apis/multicluster/constants/constants.go
- multicluster/apis/multicluster/v1alpha1/resourceexport_webhook.go
- multicluster/controllers/multicluster/common/helper.go
- multicluster/controllers/multicluster/leader/clusterinfo_export_handler.go
- multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
- multicluster/controllers/multicluster/leader/resourceexport_controller.go
- multicluster/controllers/multicluster/leader/resourceexport_controller_test.go
- multicluster/controllers/multicluster/leader/stale_controller.go
- multicluster/test/integration/resourceexport_controller_test.go
> Update finalizer of ResourceExport to be domain-qualified

- docs/antctl.md
- pkg/agent/apis/types.go
- pkg/agent/apiserver/apiserver.go
- pkg/agent/apiserver/handlers/bgproute/handler.go
- pkg/agent/apiserver/handlers/bgproute/handler_test.go
- pkg/agent/controller/bgp/controller.go
- pkg/agent/controller/bgp/controller_test.go
- pkg/antctl/antctl.go
- pkg/antctl/command_list_test.go
- pkg/querier/querier.go
- pkg/querier/testing/mock_querier.go
Add `antctl get bgproutes` agent command to print the advertised BGP routes.
The command is implemented using a new HTTP endpoint (`/bgproutes`), which will return a `404 Not Found` error if no BGPPolicy has been applied on the Node.
For https://github.com/antrea-io/antrea/issues/6209
> Add "antctl get bgproutes" agent command

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- Makefile
- build/images/.gitignore
- build/images/Dockerfile.agent.ubuntu
- build/images/Dockerfile.build.agent.coverage
- build/images/Dockerfile.build.agent.ubi
- build/images/Dockerfile.build.agent.ubuntu
- build/images/Dockerfile.build.controller.coverage
- build/images/Dockerfile.build.controller.ubi
- build/images/Dockerfile.build.controller.ubuntu
- build/images/base/Dockerfile
- build/images/base/Dockerfile.ubi
- build/images/base/build.sh
- build/images/build-utils.sh
- build/images/ovs/build.sh
- build/images/test/Dockerfile
- hack/build-antrea-linux-all.sh
Github-hosted Arm runners are now in Beta for Enterprise accounts, and available to all CNCF projects. We can use them to build Antrea Arm images for the Agent and Controller, instead of relying on a private Github repo with self-hosted Arm runners.
At the moment, we only migrate the building part (along with creation of the multi-image manifest), and we use the existing workflow in vmware-tanzu/antrea-build-infra for "asynchronous" testing of the Arm images. We will handle the migration of the testing part in the future.
As part of this change, we also push "base images" (antrea/openvswitch, antrea/base-ubuntu) for arm64 and arm/v7 to the registry. This is necessary for building the Antrea images with the Docker container build driver. The base images now have the architecture as a …
> Build Arm images from this repo using Github-hosted Arm runners

- ci/jenkins/test-vm.sh
- ci/jenkins/test.sh
- test/e2e/vmagent_test.go
* Upgraded Windows images to restore CI on the latest kubernetes cluster
* Updated external node names for testbed migration.
> Update Jenkins Scripts for Testbed Migration

- .github/workflows/build_tag.yml
If VERSION is not set, make will not use the correct tag, and the job will fail.
> Set VERSION env var in workflow when building Antrea images for tag

- .github/workflows/build_tag.yml
Without the get-version dependency, the DOCKER_TAG var  will be empty.
> Add missing job dependency in build_tag.yml workflow

- pkg/agent/controller/networkpolicy/fqdn.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/pod_reconciler_test.go
This is a draft PR for work towards #6722 .
> Cache TTLs for individual IP addresses in DNS responses.

- pkg/antctl/raw/check/installation/test_podtointernet.go
Fixes #6432
Use api.github.com as suggested to be more stable in the issue above
> Replace domain used for Pod internet connectivity test

- cmd/antrea-agent/agent.go
- go.mod
- go.sum
- pkg/agent/controller/egress/egress_controller.go
- pkg/agent/controller/egress/egress_controller_test.go
- pkg/agent/controller/serviceexternalip/controller.go
- pkg/agent/ipassigner/ip_assigner_linux.go
- pkg/agent/ipassigner/linkmonitor/link_monitor.go
- pkg/agent/ipassigner/linkmonitor/link_monitor_linux.go
- pkg/agent/ipassigner/linkmonitor/link_monitor_linux_test.go
- pkg/agent/ipassigner/linkmonitor/link_monitor_windows.go
- pkg/agent/ipassigner/responder/arp_responder.go
- pkg/agent/ipassigner/responder/arp_responder_test.go
- pkg/agent/ipassigner/responder/factory.go
- pkg/agent/ipassigner/responder/ndp_responder.go
- pkg/agent/ipassigner/responder/ndp_responder_test.go
- pkg/agent/util/ndp/ndp.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
- test/integration/agent/ip_assigner_linux_test.go
For secondary-network scenarios, the transport interface can be changed after the agent is started. The ARP/NDP responders should be restarted after the initialization of secondary-network to bind to the transport interface of the new index.
Besides, this change also addresses the following issues:
- NDP responder may fail to bind to the new interface due to the Duplicate Address Detection process.
- Golang caches the zone index for the interface, which may result in NDP responder binding on the stale interface
Fixes: #6623
> Reinitialize ARP/NDP responders when the transport interface changes

- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/crds/packetcapture.yaml
- build/charts/antrea/templates/agent/clusterrole.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- docs/feature-gates.md
- docs/packetcapture-guide.md
- go.mod
- go.sum
- hack/.notableofcontents
- pkg/agent/packetcapture/capture/bpf.go
- pkg/agent/packetcapture/capture/bpf_test.go
- pkg/agent/packetcapture/capture/pcap_linux.go
- pkg/agent/packetcapture/capture/pcap_windows.go
- pkg/agent/packetcapture/capture_interface.go
- pkg/agent/packetcapture/packetcapture_controller.go
- pkg/agent/packetcapture/packetcapture_controller_test.go
- pkg/agent/supportbundlecollection/support_bundle_controller_test.go
- pkg/apis/crd/v1alpha1/types.go
- pkg/apis/crd/v1alpha1/zz_generated.deepcopy.go
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/features/antrea_features.go
- test/e2e/packetcapture_test.go
This is a refactor of #5821 (ovs based) which use a custom bpf filter parser  to perform the capture.
> Add packetcatpure feature

- pkg/agent/packetcapture/capture/pcap_linux.go
- pkg/agent/packetcapture/capture/pcap_unsupported.go
- pkg/agent/packetcapture/packetcapture_controller.go
- pkg/agent/packetcapture/packetcapture_controller_test.go
- test/e2e/framework.go
- test/e2e/nodeportlocal_test.go
- test/e2e/packetcapture_test.go
The patch fixes the following issues:
1. The local pcap file was not closed on error. The patch ensures the file is closed regardless of success or failure.
2. The pcap file was not updated to `status.filePath` and was not uploaded to file server if not all packets have been captured. The patch ensures it's updated to status and uploaded as long as any packet is captured.
3. The Complete condition was not set correctly in one case. The patch uses two errors to track capturing error and uploading error separately.
4. The unit tests could report false negative as they only check that unexpected conditions don't exist, while they should check expected conditions exist.
5. Change the local pcap path's permission to 700.
6. Avoid panic when handling delete events containing …
> Improve error handling and resource cleanup for PacketCapture

- hack/release/draft-release.sh
`${project^}` is not supported in older versions of macOS's default shell, bash v3.2.
> Make draft-release.sh compatible with old versions of bash

- MAINTAINERS.md
We also update the maintainers' affiliation from VMware to Broadcom.
Congratulations Lan!
Closes #6805
> Add Lan Luo (@luolanzone) to maintainers

- .github/workflows/go.yml
- .github/workflows/kind.yml
The "file" input has been deprecated (and is now gone) in favor of "files".
> Fix codecov-action usage after upgrading to v5

- .github/dependabot.yml
Their releases seem to be synchronized, and ginkgo depends on gomega. It makes sense to update them together.
> [Dependabot] Update ginkgo/v2 and gomega as a group

- ci/jenkins/jobs/job-templates.yaml
- ci/jenkins/jobs/projects-cloud.yaml
After CI migration, GKE credential jobs should be removed as they will no longer be available.
> Remove GKE credential job following testbed migration

- go.mod
- go.sum
- pkg/flowaggregator/clickhouseclient/clickhouseclient.go
- pkg/flowaggregator/clickhouseclient/clickhouseclient_test.go
Manual upgrade needed because of some breaking changes (switch to generics, removal of deque.New function).
> Bump github.com/gammazero/deque to v1.0.0

- pkg/agent/packetcapture/capture/pcap_linux.go
- pkg/agent/packetcapture/capture/pcap_unsupported.go
- pkg/agent/packetcapture/capture_interface.go
- pkg/agent/packetcapture/packetcapture_controller.go
- pkg/agent/packetcapture/packetcapture_controller_test.go
- test/e2e/packetcapture_test.go
By default, gopacket will write snap length=0 in the pcapng file header, means unlimited snaplen. tcpdump on osx(libpcap version 1.10.1) cannot recognize this and will report error. This patch will set a default value(524288) for it. This patch also add packets file verification in e2e tests.
origin error message:
```
tcpdump: pcap_loop: invalid packet capture length 74, bigger than snaplen of 524288
```
pcapng format ref: https://pcapng.com/
> Fix PacketCapture pcapng file issue on macOS

- .github/dependabot.yml
- .github/workflows/trivy_scan.yml
- .github/workflows/trivy_scan_before_release.yml
Recently some Trivy scans have started failing because of rate limiting when downloading the vulnerability DB from ghcr.io (either because of some new rate limits or because of an increase in users).
We improve our workflows in order to setup Trivy and download the DB separately. This allows us to support retries (up to 5) when downloading the DB. Based on some experiments, it seems that the download consistently succeeds on the second attempt.
We also use caching to reduce the frequency at which we download the DB. We will download the DB at most once every 24 hours (at the moment this means we will download the DB every time the trivy_scan.yml workflow runs, given that it runs once a day). For release PRs, we do not use a cached DB.
> Support retries when downloading Trivy vulnerability DB

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
The Github Container Registry (ghcr.io) is introduced as an alternative to Docker Hub for users. There is no change to how images are pushed to Docker Hub, but antrea/antrea-agent-ubuntu and
antrea/antrea-controller-ubuntu are now also available in ghcr.io, as antrea-io/antrea-agent-ubuntu and antrea-io/antrea-controller-ubuntu respectively.
We do not retroactively push previously-released images to ghcr.io. Antrea v2.3 will be the first release also available in ghcr.io.
In the future, we may also push UBI-based images to ghcr.io.
Fixes #6454
> Push Antrea Ubuntu-based images to ghcr.io

- pkg/apis/controlplane/types.go
The TLSProtocol control plane internal (unversioned) type had a JSON / Protobuf field tag. Internal types are never serialized, so the tag was unnecessary and misleading.
> Remove superfluous json and protobuf tags for CP internal type

- pkg/antctl/raw/supportbundle/command.go
- pkg/antctl/raw/supportbundle/command_test.go
- pkg/antctl/runtime/runtime.go
Fixes: https://github.com/antrea-io/antrea/issues/6687
* Create a new kubeconfig for local support bundle requests to avoid errors caused
by the absence of this file.
* For ResolveKubeconfig, detailed error messages are returned, differentiating
between kubeconfig file errors and InClusterConfig errors.
> Create new kubeconfig for SupportBundleClient

- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- test/e2e/antreapolicy_test.go
`EnableLogging` was not set for default-deny-all K8s NetworkPolicy even with Namespace properly annotated. This PR fixes the issue by configuring `enableLogging` field.
Fixes #6844
> Fix K8s NetworkPolicy Deny All Audit Logging

- pkg/controller/networkpolicy/networkpolicy_controller.go
- pkg/controller/networkpolicy/networkpolicy_controller_test.go
- test/e2e/antreapolicy_test.go
Cherry pick of #6855 on release-2.0.
#6855: Fix K8s NetworkPolicy Deny All Audit Logging
> Automated cherry pick of #6855: Fix K8s NetworkPolicy Deny All Audit Logging

- ci/jenkins/test-vm.sh
- ci/jenkins/test-vmc.sh
- ci/kind/test-e2e-kind.sh
- ci/kind/test-secondary-network-kind.sh
- test/e2e/framework.go
- test/e2e/packetcapture_test.go
- test/e2e/sftp_util.go
- test/e2e/supportbundle_test.go
- test/e2e/trafficcontrol_test.go
- test/e2e/vmagent_test.go
The SupportBundleCollection CRD can be used to collect support bundle files and upload them to a file server. It supports both K8s Nodes and VMs (External Nodes). Prior to this change, we would only test the VM case. The SupportBundleCollection e2e test for VMs cannot easily be run locally on a Kind cluster, which makes it impractical for development. The corresponding CI job (which runs the e2e test) also has to be triggered manually, which means it is not always run for all PRs, which can cause breakage.
This change introduces a new SupportBundleCollection e2e test, which only collects bundles from K8s Nodes. The test can be run locally on a Kind cluster, as long as Antrea is installed with the SupportBundleCollection Feature Gate enabled.
We also use a uniform mechanism to deploy an …
> Add e2e test for SupportBundleCollection for K8s Nodes

- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/pod_configuration_test.go
On Windows, OVS has an issue which doesn't correctly update the port status after an OpenFlow port is successfully installed. So OVS may send out PortStatus message with Port state as LINK_DOWN, this issue doesn't impact on the datapath forwarding.
This change is a workaround to ensure Pod's OpenFlow entries are installed as long as the OpenFlow port is allocated.
Fix: #6888
> [Windows] Support OF port state "down" when installing Pod forwarding rules

- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/pod_configuration_test.go
Cherry pick of #6889 on release-2.2.
#6889: Support OF port state "down" when installing Pod
> Automated cherry pick of #6889: Support OF port state "down" when installing Pod

- go.mod
- go.sum
- pkg/agent/flowexporter/exporter/exporter.go
- pkg/agent/flowexporter/exporter/exporter_test.go
- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
We switch to more efficient versions of AddRecord, which generate fewer memory allocations.
> Upgrade go-ipfix to 0.12.0

- pkg/agent/ipassigner/ip_assigner_linux.go
- pkg/agent/util/net_linux.go
- test/integration/agent/ip_assigner_linux_test.go
The IPAssigner should ensure that the promote_secondaries sysctl variable is always set when creating an interface. This ensures that When the primary IP address is removed from the interface, a secondary IP address is promoted, instead of removing all the corresponding secondary IP addresses. Otherwise, the deletion of one IP address can trigger the automatic removal of all other IP addresses in the same subnet, if the deleted IP happens to be the primary (first one assigned chronologically). For example, this can affect the Egress feature (when EgressSeparateSubnet is used).
Fixes #6890
> Ensure that promote_secondaries is set on IPAssigner interfaces

- build/charts/antrea/README.md
- build/charts/antrea/templates/agent/daemonset.yaml
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- pkg/agent/cniserver/interface_configuration_linux.go
- pkg/agent/cniserver/interface_configuration_linux_test.go
- pkg/agent/cniserver/interfaces.go
- pkg/agent/cniserver/sriov_linux.go
- pkg/agent/cniserver/testing/mock_cniserver.go
- pkg/agent/secondarynetwork/podwatch/sriov.go
VM Nodes don't have access to Physical Function, the patch removes the code that checks whether the Physical Function exists or not, which is not really necessary.
It also fixes two issues:
1. The usage of grpc.NewClient was wrong.
2. The kubelet socket was not accessible in the Pod.
TODO:
The directory only contains a socket that provides read-only APIs for exposing resource allocation details of Pods. Multus thick mode also mounts the directory unconditionally.
> Support SecondaryNetwork of SR-IOV type for VM Nodes

- pkg/agent/ipassigner/ip_assigner_linux.go
- test/integration/agent/ip_assigner_linux_test.go
If the VLAN interface already exists (e.g., in case of an Agent restart), we should still ensure that the necessary sysctl variables are set correctly.
> Ensure correct sysctl values if VLAN iface exists in IPAssigner

- build/charts/antrea/crds/bgppolicy.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/bgp-policy.md
- pkg/apis/crd/v1alpha1/types.go
Previously, for safety and internal using only purposes, the local ASN was restricted to the private range (64512-65535). However, based on user feedback, BGPPolicy may also be used to peer with public BGP ASNs. Therefore, this restriction is no longer justified.
To prevent potential misconfigurations that could disrupt BGP operations, we have added the follow paragraph to documentation to remind users of the implications of using unrestricted ASN ranges.
```
Private ASNs, which are within the ranges 64512-65534 (16-bit), should be strictly limited to private networks or
environments that do not peer with public ASNs. If public network connectivity is required, coordinate with your upstream
provider to avoid issues caused by private ASN usage.
```
> Remove local ASN range limitation in BGPPolicy

- multicluster/apis/multicluster/constants/constants.go
- multicluster/apis/multicluster/v1alpha1/resourceexport_webhook.go
- multicluster/controllers/multicluster/common/helper.go
- multicluster/controllers/multicluster/leader/clusterinfo_export_handler.go
- multicluster/controllers/multicluster/leader/memberclusterannounce_controller.go
- multicluster/controllers/multicluster/leader/resourceexport_controller.go
- multicluster/controllers/multicluster/leader/resourceexport_controller_test.go
- multicluster/controllers/multicluster/leader/stale_controller.go
- multicluster/test/integration/resourceexport_controller_test.go
Cherry pick of #6742 on release-2.1.
#6742: Update finalizer of ResourceExport to be domain-qualified
> Automated cherry pick of #6742: Update finalizer of ResourceExport to be domain-qualified

- .github/workflows/conformance.yml
Now that the workflow is also run automatically when the main branch is updated, I think the current name does not make sense.
> Change name of conformance.yml workflow

- build/charts/antrea/README.md
- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/values.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/antrea-proxy.md
- pkg/agent/proxy/proxier.go
- pkg/agent/proxy/proxier_test.go
- pkg/config/agent/config.go
Running both kube-proxy and Antrea Proxy with `proxyAll` can trigger some error logs for Services of type LoadBalancer with `externalTrafficPolicy` set to `Local`. For such Services, the proxy is in charge of running a health check server on each Node, in order to report the number of local Endpoints which implement the Service. Because both kube-proxy and Antrea Proxy (with `proxyAll`) will try to run the health check servers on the same ports, one of them will fail to bind to the desired address. In practice, we typically observe that Antrea Proxy tries to bind to the address first (and succeeds), while kube-proxy fails and logs an error message, but there is no guarantee that it will be the case.
To avoid kube-proxy error logs, users can now set …
> Add antreaProxy.disableServiceHealthCheckServer config

- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
And ignore any additional config update.
A restart is required to change the mode.
> Add error log if FlowAggregator mode is updated dynamically

- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_linux.go
- pkg/agent/cniserver/server_windows.go
- pkg/agent/cniserver/server_windows_test.go
- test/e2e/connectivity_test.go
This change is to support reconciling the host-network Pods on Windows because k8s expects to let CNI manage such Pods as long as they are not using host-process containers.
Antrea has received the CmdAdd request for such Pods when they are created, so they should be included in the Pod reconcile list after agent is restarted.
Fix: #6943
> [Windows] Reconcile host-network Pods after agent is restarted

- build/charts/flow-aggregator/templates/deployment.yaml
- build/yamls/flow-aggregator.yml
When updating the config with Helm, the annotation will be automatically updated and the FlowAggregator Pod will be recreated. This is consistent with the main Helm chart for Antrea.
Note that the FlowAggregator can handle some config changes "dynamically" (i.e., without a Pod restart), but not all config updates are supported and we may want to remove that partial support altogether in the future.
The annotation can also be updated manually to roll the Deployment (e.g, if Helm is not being used).
> Add checksum/config annotation to FlowAggregator

- pkg/antctl/raw/supportbundle/command.go
- pkg/antctl/raw/supportbundle/command_test.go
- pkg/util/compress/compress.go
- pkg/util/k8s/pod.go
When the normal supportbundle api failed for some nodes or controller,
use kubernetes api instead to collect logs. Also, in either case,
clusterinfo will always be gathered first.
> Support collect logs for failed agents and controller for supportbundle

- pkg/controller/grouping/group_entity_index_test.go
I have seen the test fail in Github CI (Windows).
The 100ms sleep before verifying assertions is replaced with an assert.EventuallyWithT statement, with a tick duration of 50ms and a timeout of 1s.
> Remove sleep for TestGroupEntityIndexEventHandlers unit test

- .github/workflows/kind.yml
- ci/kind/kind-setup.sh
- ci/kind/test-e2e-kind.sh
- test/e2e/antreapolicy_test.go
>  adding a new workflow to validate the FlexibleIPAM feature

- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
- pkg/flowaggregator/infoelements/elements.go
This can help identify if the flow was exported from the source or destination Node in a more "standard" way. Note that we use a "special" value (0xff) for intra-Node flows.
> Add flowDirection IE when proxying records in FlowAggregator

- build/charts/antrea/conf/antrea-agent.conf
- build/charts/antrea/conf/antrea-controller.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/feature-gates.md
- docs/service-loadbalancer.md
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/features/antrea_features.go
Fixes: https://github.com/antrea-io/antrea/issues/6743
> Promote ServiceExternalIP to beta

- pkg/flowaggregator/flowaggregator.go
- test/e2e/fixtures.go
The code was invalid as the function was consuming messages straight from the collector instead of from the preprocessor, hence bypasing the preprocessor. This was not caught by e2e tests because the preprocessor output channel is small (capacity of 16), hence it was filling up very quickly and only a few uninteresting (i.e., irrelevant to the test cases) records were lost.
> [FlowAggregator] Use correct input channel in flowExportLoopProxy

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- cmd/antrea-agent/agent.go
- docs/antrea-l7-network-policy.md
- pkg/agent/agent.go
- pkg/agent/agent_linux.go
- pkg/agent/agent_windows.go
- pkg/config/agent/config.go
- test/e2e/l7networkpolicy_test.go
Fixes: #6806
This commit introduces the ability to disable TX checksum offload for the host gateway interface (default: `antrea-gw0`) by setting the `disableTXChecksumOffload` option to `true`.
Note: If this option is later set to false, Antrea will not restore the original TX checksum state, as it does not retain the original configuration. Users are responsible for manually reconfiguring the setting if needed.
> Enable disabling TX checksum offload for Antrea host gateway

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/egress.md
- docs/feature-gates.md
- pkg/apiserver/handlers/featuregates/handler_test.go
- pkg/features/antrea_features.go
> Promote EgressSeparateSubnet feature to Beta

- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_linux.go
- pkg/agent/cniserver/server_windows.go
- pkg/agent/cniserver/server_windows_test.go
- test/e2e/connectivity_test.go
- test/e2e/framework.go
Cherry pick of #6944 on release-2.1.
#6944: Reconcile host-network Pods after agent is
> Automated cherry pick of #6944: Reconcile host-network Pods after agent is

- build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
- build/yamls/antrea-windows-with-ovs.yml
- hack/externalnode/install-vm.ps1
- hack/windows/Clean-AntreaNetwork.ps1
- hack/windows/Helper.psm1
- hack/windows/Prepare-ServiceInterface.ps1
- pkg/agent/util/winnet/net_windows.go
- pkg/agent/util/winnet/net_windows_test.go
- test/integration/agent/net_windows_test.go
fixes https://github.com/antrea-io/antrea/issues/6989
To prevent error caused by long host name in Active Directory validation, all VMSwitch-related
commands have been updated to add `-ComputerName localhost` explictly. This change ensures local
execution of commands without relying on external network resolution or authentication.
> Add localhost for VMSwitch commands to avoid potential validation issue

- ci/kind/kind-setup.sh
Fix context issue during cleanup of kind clusters.
Fixes #6768.
> Fix context issue during cleanup of kind clusters

- build/charts/antrea-windows/conf/ovs/VMSwitchExtension-AntreaAgent.ps1
- build/yamls/antrea-windows-with-ovs.yml
- hack/externalnode/install-vm.ps1
- hack/windows/Clean-AntreaNetwork.ps1
- hack/windows/Helper.psm1
- hack/windows/Prepare-ServiceInterface.ps1
- pkg/agent/util/winnet/net_windows.go
- pkg/agent/util/winnet/net_windows_test.go
- test/integration/agent/net_windows_test.go
Cherry pick of #6985 on release-2.1.
#6985: Add localhost for VMSwitch commands to avoid potential
> Automated cherry pick of #6985: Add localhost for VMSwitch commands to avoid potential

- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- pkg/agent/secondarynetwork/podwatch/sriov.go
The "k8s.v1.cni.cncf.io/resourceName" annotation should be provided for all SRIOV NetworkAttachmentDefinitions. Otherwise, it is impossible to guarantee that the right device type is allocated for a given interface.
> [SecondaryNetwork] Require resourceName annotations for SRIOV

- ci/kind/kind-setup.sh
If all the clusters are cleaned up then .clusters.swp file is not created and it gives an error that file not present.
> Fixed the cleanup failure

- pkg/flowaggregator/options/options.go
Prior to this change, the FlowAggregator would crash if the configuration didn't enable at least one collector (e.g., the IPFIX collector). While it was probably introduced to help identify misconfigurations easily, it seems like an unnecessary restriction. We should be able to deploy the FlowAggregator in such a way that IPFIX records are still received from Agents (and metrics are incremented), while discarding aggregated / proxied data instead of exporting it.
> [FlowAggregator] Accept configurations with no collector / sink

- cmd/antrea-agent/options.go
- pkg/agent/controller/noderoute/node_route_controller.go
- pkg/agent/controller/noderoute/node_route_controller_test.go
- pkg/agent/flowexporter/exporter/exporter.go
- pkg/agent/util/net.go
- pkg/agent/util/net_windows.go
The FlowExporter in the Agent queries the NodeRouteController to determine whether the source / destination IPs are Pod IPs (NodeIPAM only). Prior to this change, these checks were expensive, involving an indexer lookup and conversions between different IP formats. The new implementation is about 10x faster, and performs no memory allocations.
The new implementation introduces a new set in the NodeRouteController, dedicated to storing all the PodCIDRs in the cluster. While I considered removing the dependency of the FlowExporter on the NodeRouteController altogether, it would have been a much bigger change. Additionally, in the long term, we could consider removing these checks from the FlowExporter altogether, and pushing the logic to the FlowAggregator.
We also make a few additional …
> [FlowExporter] More efficient IP checks

- Makefile
- ci/jenkins/test.sh
- ci/kind/kind-setup.sh
- test/e2e/providers/kind.go
There were three main causes of failure:
1) Overriding of DOCKER_IMG_VERSION in makefile.
2) Overriding of kubeconfig because of which, when
we ran multiple e2e tests together it used the
same kubeconfig which was present the default
location, so multiple jobs used the same cluster
and failed.
3) Cleanup of antrea images after test.
Refer #6446 for more details
> Fix the cause of failure of multiple kind job runs on same VM

- cmd/flow-aggregator/flow-aggregator.go
- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_linux.go
- pkg/agent/cniserver/server_windows.go
This change is to resolve the issue that "spec.hostNetwork" is not supported as Pod's field selector since K8s v1.28, so we may hit issues if antrea run on a cluster with version [1.19, 1.27] .
The fix is to remove the field selector "spec.hostNetwork" in the Pod list options, and locally filters out the hostNetwork Pod on Linux.
> Filter out the hostNetwork Pods locally on Linux

- .github/workflows/kind.yml
The codecov CLI has been updated, and the glob translation logic is different. We need the '**' pattern to match the full path. See https://github.com/codecov/codecov-cli/pull/619
We also remove the trailing wildcard, as it seems that we only ever use the .cov.out suffix for these tests.
> Fix glob pattern in codecov action (Kind tests)

- .github/workflows/build_tag.yml
Remove undefined references to push_needed.
Add the ability to trigger the workflow manually in case it is ever needed because of a release issue.
> Fix build_tag.yml workflow

- cmd/antrea-agent/agent.go
- pkg/agent/controller/l7flowexporter/l7_flow_export_controller.go
- pkg/agent/controller/l7flowexporter/l7_flow_export_controller_test.go
- pkg/util/sync/sync_test.go
It doesn't need to take the whole l7Reconciler as a parameter to be able to start it.
> Improve maintainability for L7FlowExporterController

- ci/jenkins/test.sh
Cherry pick of #6906 on release-2.1.
#6906: Fix Windows Conformance failure by updating time
> Automated cherry pick of #6906: Fix Windows Conformance failure by updating time

- pkg/agent/cniserver/server.go
- pkg/agent/cniserver/server_linux.go
- pkg/agent/cniserver/server_windows.go
Cherry pick of #7012 on release-2.1.
#7012: Filter out the hostNetwork Pods locally on Linux (#7012)
> Automated cherry pick of #7012: Filter out the hostNetwork Pods locally on Linux (#7012)

- .github/workflows/kind.yml
Cherry pick of #7013 on release-2.3.
#7013: Fix glob pattern in codecov action (Kind tests) (#7013)
> Automated cherry pick of #7013: Fix glob pattern in codecov action (Kind tests) (#7013)

- ci/test-conformance-eks.sh
This change is to bump up the EKS version to 1.31 in the CI script.
> Bump K8s version to 1.31 in EKS CI script

- docs/network-flow-visibility.md
I missed it when merging #7028 as the CI job is currently broken for other reasons (invalid Jenkins https links).
> Fix broken markdown link

- pkg/util/podstore/podstore.go
- pkg/util/podstore/podstore_test.go
The PodStore uses the UID as the unique key in the indexer, and not the usual namespace/name. Because it is possible for the deletion of a Pod, followed by the creation of a different Pod wih the same name, to be observed as an Update by a client (see
https://pkg.go.dev/k8s.io/client-go/tools/cache#SharedInformer), the Update event handler needs to handle this case gracefully by comparing UIDs. Note that this is probably quite an unlikely situation in the case of Pods, but we should still account for this in the PodStore implementation.
> Handle Pod UID updates in PodStore

- cmd/antrea-agent/agent.go
- docs/network-requirements.md
- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/route/route_windows.go
- test/integration/agent/route_test.go
This change is to actively configure the iptables rules wireguard.port when wireguard is used as the encryption mode. This can fix traffic issues if the Node is configured with iptables default DROP policy.
Fix: #7009
> Install iptables rules to allow wireguard packets

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
As an alternative to docker.io
This is the same change that we did previously for the "main" Antrea images (antrea-agent-ubuntu and antrea-controller-ubuntu).
> Push flow-aggregator image to ghcr.io registry

- pkg/agent/controller/bgp/controller.go
- pkg/agent/controller/bgp/controller_test.go
Cherry pick of #7042 on release-2.1.
#7042: Fix crash when deleting the Secret storing BGP passwords
> Automated cherry pick of #7042: Fix crash when deleting the Secret storing BGP passwords

- build/charts/antrea/crds/packetcapture.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/packetcapture-guide.md
- pkg/agent/packetcapture/capture/bpf.go
- pkg/agent/packetcapture/capture/bpf_test.go
- pkg/agent/packetcapture/capture/pcap_linux.go
- pkg/agent/packetcapture/capture/pcap_unsupported.go
- pkg/agent/packetcapture/capture_interface.go
- pkg/agent/packetcapture/packetcapture_controller.go
- pkg/agent/packetcapture/packetcapture_controller_test.go
- pkg/apis/crd/v1alpha1/types.go
- test/e2e/packetcapture_test.go
fixes: #6862 
Added `bidirectional` field in packet capture CR spec.
For testing, I created two pods and pinged one from the other. 
Screenshot of the `.pcapng` output file.
> Add bidirectional packet capture

- ci/jenkins/utils.sh
A missing Go binary during checking go version can cause script failure. The condition check
failed to handle this case because the directory still existed.
This patch improves the directory check by directly verifying the existence of `bin/go`
to prevent script failure when retrieving go version.
> Ensure Go binary exists before version check

- pkg/agent/apis/types.go
- pkg/agent/apiserver/apiserver.go
- pkg/agent/apiserver/handlers/fqdncache/handler.go
- pkg/agent/apiserver/handlers/fqdncache/handler_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/agent/types/networkpolicy.go
- pkg/antctl/antctl.go
- pkg/antctl/command_list_test.go
- pkg/querier/querier.go
- pkg/querier/testing/mock_querier.go
This PR adds functionality for a new antctl command: antctl get fqdncache This command fetches the DNS mapping entries for FQDN policies by reading the cache for DNS entries and outputting FQDN name, associated IP, and expiration time. It can also be used with a --domain (-d) flag that can be specified to filter the result for only a certain FQDN name.
> Add antctl get fqdncache

- docs/secondary-network.md
- hack/.notableofcontents
Cherry pick of #7076 on release-2.3.
#7076: Document SecondaryNetwork support for SR-IOV (#7076)
> Automated cherry pick of #7076: Document SecondaryNetwork support for SR-IOV (#7076)

- docs/network-flow-visibility.md
According to the IE registry at https://github.com/vmware/go-ipfix/blob/f5f76764c947db56138a2f0bb237534f3dd5387d/pkg/registry/registry.go#L26 the current value was incorrect.
I recently ran into this and after hours of troubleshooting I finally realized the docs are wrong. Hopefully this will prevent others from running into the same issue.
> Fix invalid ie registry id in docs

- cmd/antrea-agent/agent.go
- pkg/agent/secondarynetwork/init.go
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- test/e2e-secondary-network/secondary_network_test.go
- test/e2e/antreaipam_test.go
- test/e2e/antreapolicy_test.go
- test/e2e/bgppolicy_test.go
- test/e2e/egress_test.go
- test/e2e/flowaggregator_test.go
- test/e2e/framework.go
- test/e2e/k8s_util.go
- test/e2e/l7networkpolicy_test.go
- test/e2e/multicast_test.go
- test/e2e/networkpolicy_test.go
- test/e2e/nodelatencymonitor_test.go
- test/e2e/packetcapture_test.go
- test/e2e/proxy_test.go
- test/e2e/secondary_network_ipam_test.go
- test/e2e/service_externalip_test.go
- test/e2e/supportbundle_test.go
- test/e2e/traceflow_test.go
- test/e2e/trafficcontrol_test.go
- test/e2e/vmagent_test.go
Closes: #6578 #5623 
Store the SecondaryNetwork interface in interfacestore after Agent restart and delete secondaryNetwork OVS ports correctly.
e2e case: -->
1. restart the antrea agent
2. check for the ovs ports restored or not
3. delete the one testpod p1
4. check for the stale ovs ports
5. check for the pod ip (released or not)
> Reconcile secondary network OVS ports after Agent restart

- test/e2e/k8s_util.go
* On older machines, the tests `AntreaPolicyExtendedNamespaces` would fail but not on CI
* The failure was due to the 1k+ simultaneous probes that the api-server would not handle
* For that test the number of probes were ~1800:
* n^2 x m
* n = 5 namespace x 3 pods
* squared for the nested for loop validating all pod to pod connections 
* m = 8 ports
* Using a semaphore, the probing is rate limited by doing them in batches of 150
* Addresses (#7067)
> fix: batch probing in e2e test setup (#7067)

- build/images/Dockerfile.build.windows
- build/images/build-windows.sh
- build/images/ovs/build.sh
- ci/jenkins/test.sh
- hack/build-antrea-windows-all.sh
When a user switches the Docker registry for image access, building Windows images still pulls images from the default registry. This patch improves compatibility for registry changes.
> Enhance Windows CI Compatibility with Different Docker Registry

- docs/antctl.md
- pkg/antctl/antctl.go
- pkg/antctl/command_list.go
- pkg/antctl/command_list_test.go
- pkg/antctl/raw/check/cluster/test_checkcniexistence.go
- pkg/antctl/raw/check/cluster/test_checkovsloadable.go
- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/util.go
- pkg/antctl/raw/helper.go
- pkg/antctl/raw/packetcapture/command.go
- pkg/antctl/raw/packetcapture/command_test.go
- pkg/util/compress/compress.go
TODO items:
after #3659 , the CodeQL alert should be fixed and UT coverage will also be  improved.
> Support antctl command for packetcapture

- test/e2e/k8s_util.go
* PR #7068 removed the 10 retries for setting up the cluster which introduced flakiness in CI
> fix: re-adds retry in e2e kind setup

- docs/antrea-network-policy.md
The `namelabelmutator.antrea.io` MutatingWebhookConfiguration YAML in antrea-network-policy.md is missing the necessary labels to ensure that the CA cert is synced correctly by the Antrea Controller (e.g., when the certificate is rotated).
> Add missing labels to namelabelmutator.antrea.io in doc

- build/charts/flow-aggregator/README.md
- build/charts/flow-aggregator/templates/deployment.yaml
- build/charts/flow-aggregator/values.yaml
- build/yamls/flow-aggregator.yml
- hack/generate-manifest-flow-aggregator.sh
- test/e2e/fixtures.go
- test/e2e/framework.go
* hostNetwork
* dnsPolicy
* securityContext for the flow-aggregator container
* resources (requests and limits) for the flow-aggregator container
We also set some reasonable default resource requests for the
flow-aggregator container, even though actual resource usage will
be highly dependent on the cluster size, workloads, and on the
flow-aggregator configuration.
> Add more configuration values to the flow-aggregator chart

- build/charts/antrea/templates/agent/clusterrole.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- test/e2e-secondary-network/secondary_network_test.go
related #7048 
Add Network Status Annotations for Pod to make Pod SecondaryNetwork IP visible. For example:
```
Annotations:        k8s.v1.cni.cncf.io/networks: macvlan-conf
k8s.v1.cni.cncf.io/network-status:
[{
"name": "cbr0",
"ips": [
"10.244.1.73"
],
"default": true,
"dns": {}
},{
"name": "macvlan-conf",
"interface": "net1",
"ips": [
"192.168.1.205"
],
"mac": "86:1d:96:ff:55:0d",
"dns": {}
}]
```
TestDone:    
kubectl get pods sriov-pod1  -n testsriovnetwork-uu5azxvs -oyaml
```
apiVersion: v1
kind: Pod
metadata:
annotations:
k8s.v1.cni.cncf.io/network-status: |-
[{
"name": "sriov-net1",
"interface": "eth1",
"ips": [
"172.31.16.199"
],
"mac": "02:1d:78:31:6f:c7",
"dns": {}
}]
k8s.v1.cni.cncf.io/networks: '[{"name": "sriov-net1", "namespace": "default",
"interface": "eth1"}]' …
```
> Add networkstatus annotation to make secondarynetwork Pod IP visible

- test/e2e/packetcapture_test.go
The `invalid-host-public-key` test case is currently failing. The test case includes a failed SFTP upload, and it needs a custom timeout value to account for upload retries (and the delay between retries). It is not clear why it was passing before. It seems that we were right at the edge, and an update to the Github runner affected the timing and caused the test to fail.
> Fix TestPacketCapture e2e test failure

- docs/secondary-network.md
- pkg/agent/util/net_linux.go
- pkg/agent/util/net_linux_test.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
Resolve #7058
1. Add a limitation in the doc that multi-path routes are not supported for SecondaryNetwork
2. Using `netlinkUtil.RouteAdd` to replace `netlinkUtil.RouteReplace` when recovering the secondary interfaces routes in K8s Nodes, which will help avoid conflicts when the interface is managed by a network daemon. For example, routes may be added back automatically by the daemon when we bring the interface back up, and replacing them with Antrea could potentially create issues in some edge cases (e.g., when multi-path routes are present). More details can be checked in #7058
> Configure routes via ip route add

- ci/kind/kind-setup.sh
The version of Docker Engine included in the Github runners was recently updated from v26 to v28. This has caused consistent CI failures.
* Use `com.docker.network.endpoint.ifname` label when connecting an additional network to Kind Nodes to provide an explicit interface name - see https://github.com/moby/moby/issues/49935
* Use `gateway_mode_ipv[46]=nat-unprotected` to make sure that Kind Nodes on a non-default docker network can acess the K8s apiserver - see https://github.com/moby/moby/pull/49325
> Fix Kind job failures on Github after Docker Engine update

- ci/kind/kind-setup.sh
Cherry pick of #7165 on release-2.2.
#7165: Fix Kind job failures on Github after Docker Engine update
> Automated cherry pick of #7165: Fix Kind job failures on Github after Docker Engine update

- pkg/agent/multicast/mcast_controller.go
- pkg/agent/multicast/mcast_controller_test.go
This change is to resolve the issue that the same receiver may fail to receive multicast packets after it rejoins the group with encap mode. The issue happens when the last local member has left the Multicast group, but there exists receivers located on other Nodes in the cluster.
The issue was introduced because the Multicast controller directly adds the group into the worker queue but didn't update status in the cache, which makes the re-join event from the same Pod is ignored.
The fix is to generate IGMP leave message for the stale members even if it is the last member on the current Node. It also calls checkLastMember in function `clearStaleGroups` when no local members are left, rather than directly adds the group into the worker queue. It also removes the field "lastIGMPReport" in …
> [Multicast] Remove stale local members in the group cache

- pkg/agent/openflow/packetin.go
- pkg/ovs/openflow/ofctrl_bridge.go
- pkg/ovs/openflow/ofctrl_bridge_test.go
- test/integration/ovs/ofctrl_test.go
PacketIn events may be dropped when their rate exceeds 500 per second. Such drops can lead to traffic issues, for instance, if the dropped packet is a DNS reply for FQDN policy enforcement. Previously, there was no visibility into whether such drops occurred.
This patch adds rate-limited logging (once per minute) for these dropped events to help identify potential bottleneck. Frequent occurrences may indicate the need to increase the rate limit.
```
E0516 10:29:58.479969       1 ofctrl_bridge.go:681] "Failed to dispatch PacketIn event due to full channel" category=2 pktDrops=1
E0516 10:31:01.431538       1 ofctrl_bridge.go:681] "Failed to dispatch PacketIn event due to full channel" category=2 pktDrops=255
E0516 10:34:43.554807       1 ofctrl_bridge.go:681] "Failed to dispatch PacketIn …
```
> Log PacketIn drops when dispatching to per-category queues

- docs/bgp-policy.md
- pkg/agent/bgp/gobgp/gobgp.go
- pkg/agent/bgp/interface.go
- pkg/agent/controller/bgp/controller.go
- pkg/agent/controller/bgp/controller_test.go
- test/e2e/bgppolicy_test.go
For https://github.com/antrea-io/antrea/issues/6567
Done: add some text about ASN to documentation.
Depends on #6905
> Add BGP confederation support in BGPPolicy

- ci/jenkins/jobs/macros.yaml
- ci/jenkins/jobs/projects-cloud.yaml
- ci/test-conformance-gke.sh
Updated the GKE cluster creation script to explicitly specify the shared VPC network and subnetwork. Also updated the Jenkins job YAML configuration to use the correct settings. These changes allow the GKE cloud job to be restored and run successfully with the new account.
> Restore Antrea GKE cloud job

- multicluster/test/e2e/service_test.go
- pkg/agent/monitortool/monitor.go
- pkg/agent/multicast/mcast_controller_test.go
- pkg/agent/openflow/client.go
- pkg/agent/openflow/cookie/allocator_test.go
- pkg/flowaggregator/s3uploader/s3uploader.go
- pkg/flowaggregator/s3uploader/s3uploader_test.go
- pkg/ovs/openflow/ofctrl_packetout.go
- pkg/ovs/openflow/ofctrl_packetout_test.go
- test/e2e/framework.go
- test/e2e/performance_test.go
- test/integration/agent/net_test.go
Fixes: #6648 
This PR replaces all usages of `math/rand` with the new `math/rand/v2` package.
I have updated the code following the previous review suggestions from @antoninbas on related PRs.
Let me know if any additional adjustments are needed.
> Replace usage of math/rand with math/rand/v2

- ci/kind/kind-setup.sh
Fixing the the network deletion logic, to ensure that the network we create manually using script for the Kind cluster is correctly deleted.
> Fix network deletion logic in kind script

- pkg/agent/monitortool/monitor.go
- pkg/agent/monitortool/monitor_test.go
Fixes: #6570 
This PR decouples ICMP probe sending from latency reporting in the NodeLatencyMonitor to improve accuracy of measurements and reduce system load. Previously, latency reporting happened immediately after sending probes, which could lead to misleading timestamps in the NodeLatencyStats CRD.
- Separated ping and report operations into distinct tickers
- Added minimum report interval (10s) to prevent excessive reporting 
- Added jitter to report interval to avoid report clustering
- Updated tests to handle decoupled operations
I have updated the code following the previous review suggestions from @antoninbas  on related PRs.
Let me know if any additional adjustments are needed.
Attached the test result.
> Decouple sending of ICMP probes & latency reporting

- pkg/agent/nodeportlocal/k8s/npl_controller.go
* Use structured logging consistently in handleAddUpdatePod.
* Increase verbosity level of "IP address not set for Pod" log.
* Add new logs when a rule is added / deleted. While the iptables-based implementation of NPL will also log a message, it doesn't include the Pod name, which makes troubleshooting issues harder.
> Improve logging in NodePortLocal controller

- pkg/agent/agent_test.go
- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/pod_configuration_linux.go
- pkg/agent/cniserver/pod_configuration_linux_test.go
- pkg/agent/cniserver/pod_configuration_windows.go
- pkg/agent/cniserver/secondary.go
- pkg/agent/cniserver/server_linux_test.go
- pkg/agent/cniserver/server_test.go
- pkg/agent/cniserver/server_windows_test.go
- pkg/agent/interfacestore/interface_cache_test.go
- pkg/agent/interfacestore/types.go
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
The following agent functions require netns of a container network interface:
* Create or update a Pod secondary interface.
* Delete a Pod secondary interface and clean up its state.
* Restore the original name of a SR-IOV VF interface after it is removed from the container netns.
If the container netns info is not persisted, these functions may break after agent restarts. This commit stores netns in the interface store, and writes it to an OVS port external ID with a Pod's primary or a secondary VLAN interface and restores it into the interface store after agent restarts.
> Persist container netns with OVS port external IDs

- pkg/agent/cniserver/interface_configuration_linux.go
- pkg/agent/cniserver/interface_configuration_linux_test.go
If configureContainerLinkVeth fails, either while disabling TX checksum offloading or configuring IPAM, the veth interfaces are left behind in a broken state. Subsequent retries by the controller will fail to create the veth again because they already exist.
This patch performs proper cleanup, allowing retries to succeed.
Logs without the fix (2.3.0):
```
I0606 08:43:10.229897       1 allocator.go:155] "IP Pool update succeeded" pool="vlan100-ipv4" allocation={"ipAddresses":[{"ipAddress":"172.100.0.10","phase":"Allocated","owner":{"pod":{"name":"sample-pod-secondary-network-vlan","namespace":"default","containerID":"a18542cd74fa5a80cb3b0bf1b633976e13b68ef589a5c4ef47695851484a4d24","ifName":"eth1"}}}],"usage":{"total":11,"used":1}}
I0606 08:43:10.234288       1 allocator.go:251] "IP Pool …
```
> Fix rollback when configureContainerLinkVeth fails

- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
- pkg/flowaggregator/preprocessor_test.go
When switching to a buffered exporter in #6998, the exporter code was "optimized" a bit too agressively, and we ended up in a situation where data records with a template ID of 0 could be exported.
The template ID should be set explicitly for all IPFIX records to account for the following:
1) the template ID may not always match between the FlowExporter (Agent)
and the FlowAggregator, even though it is the case today.
2) when there is version skew between the FlowExporter and the
FlowAggregator, and IEs are either added or removed, the FA
preprocessor resets the template ID of data records to 0 to avoid
confusion (mutated data record no longer matches original template
ID), which means that the correct template ID must be set at export
time.
> Fix invalid template ID in FlowAggregator (IPFIX exporter)

- docs/design/ovs-pipeline.md
The current implementation excludes the entire Service CIDR from Egress SNAT, not just the Services specified in `antreaProxy.skipServices`.
Relevant code path:
- https://github.com/antrea-io/antrea/blob/23b12810fe9b3bd3a910755ea6fbc09a2e71a970/pkg/agent/openflow/pipeline.go#L2183
- https://github.com/antrea-io/antrea/blob/23b12810fe9b3bd3a910755ea6fbc09a2e71a970/pkg/agent/openflow/client.go#L1047
- https://github.com/antrea-io/antrea/blob/23b12810fe9b3bd3a910755ea6fbc09a2e71a970/pkg/agent/controller/egress/egress_controller.go#L388
> Fix incorrect description in pipeline.md

- docs/antctl.md
- pkg/flowaggregator/apis/types.go
- pkg/flowaggregator/apiserver/handlers/recordmetrics/handler.go
- pkg/flowaggregator/apiserver/handlers/recordmetrics/handler_test.go
- pkg/flowaggregator/exporter/ipfix.go
- pkg/flowaggregator/exporter/ipfix_test.go
- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
- pkg/flowaggregator/querier/querier.go
- pkg/util/podstore/podstore.go
- pkg/util/podstore/testing/mock_podstore.go
* Use exponential backoff when reconnecting to IPFIX collector. This is especially important in Proxy mode, where previously we would try to reconnect for every new proxied record, and log an error in case of failure. We now enforce a backoff and skip logging an error when reconnection is not attempted because of the backoff delay (instead we increment a counter).
* Reset the IPFIX exporting process when a flush operation fails. This also helps to avoid repeated error logs.
* Wait for initial sync of the PodStore before collecting records, to avoid error logs about missing Pod information.
> FlowAggregator improvements

- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
We use a mutex which is locked for every loop iteration (flowExportLoopProxy / flowExportLoopAggregate), as well as in the GetRecordMetrics function.
> [FlowAggregator] Fix race condition when getting metrics

- pkg/agent/nodeportlocal/k8s/npl_controller.go
- pkg/agent/nodeportlocal/portcache/port_table_others.go
- pkg/agent/nodeportlocal/portcache/port_table_windows.go
- pkg/agent/nodeportlocal/portcache/port_table_windows_test.go
A NPL cleanup log was being generated every time a Pod without NPL enabled was created, updated, or deleted. This could flood the logs and potentially confuse users.
This patch removes the code that handles the delete-all-rules case specifically and logs the event unconditionally even if nothing is done. It also reduces code redundancy.
> Remove unnecessary logs about NPL cleanup

- build/charts/antrea-windows/conf/ovs/Run-AntreaOVS.ps1
- build/yamls/antrea-windows-with-ovs.yml
* Add -ErrorAction parameter to Get-Process to prevent pod restarts if an ovs process is missing.
* Reduce wait time after restarting OVS processes to accelerate container recovery.
* Skip checking ovs-vswitchd if ovsdb-server is not running, as ovs-vswitchd depends on a functional ovsdb-server to start successfully.
> Enhance OVS commands for Antrea Windows

- pkg/controller/grouping/controller.go
- pkg/controller/grouping/controller_test.go
- pkg/controller/grouping/group_entity_index.go
- pkg/controller/grouping/group_entity_index_test.go
Cherry pick of #7217 on release-2.0.
#7217: Sync groups members for pods that turns into terminated
> Automated cherry pick of #7217: Sync groups members for pods that turns into terminated

- ci/test-conformance-eks.sh
- ci/test-sriov-secondary-network-aws.sh
Set AWS environment variables to access AWS resources instead of writing the credentials to the Jenkins test machine. It would also simplify running this script locally from a dev machine.
see also: https://github.com/antrea-io/antrea/pull/6922#discussion_r1964852586
Advantages
- Avoids storing sensitive information on disk.  
- Temporary credentials expire automatically, providing enhanced security.  
test record: http://35.164.122.165/job/antrea-sriov-secondary-network-e2e-for-pull-request/29/
http://35.164.122.165/job/cloud-antrea-eks-conformance-net-policy/46
> Set AWS environment variables to access AWS resources

- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- pkg/agent/util/netlink/netlink_linux.go
- pkg/agent/util/netlink/testing/mock_netlink_linux.go
Cherry pick of #7238 on release-2.3.
#7238: Periodically sync permanent neighbors to ensure route
> Automated cherry pick of #7238: Periodically sync permanent neighbors to ensure route

- go.mod
- go.sum
- pkg/agent/cniserver/sriov_linux.go
- pkg/agent/cniserver/sriov_linux_test.go
The old version [GetVFLinkNames](https://github.com/k8snetworkplumbingwg/sriov-cni/blob/v2.1.0/pkg/utils/utils.go#L145-L163) from sriov-cni utils may raise an errror: `runtime error: index out of range [0] with length 0`, so copy the latest version to Antrea without importing the package.
> Fix index out of range issue for GetVFLinkNames

- pkg/agent/cniserver/ipam/antrea_ipam_controller.go
- pkg/agent/cniserver/secondary.go
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- test/e2e-secondary-network/secondary_network_test.go
When the agent restarts, current interfaceStore for SecondaryNetwork will not recover the assigned SRIOV interfaces for containers because of no OVS bridge to check, so we leverage the NetworkStatus info in the Pod annotation to recover the interface info.
This change would help to ensure the interface name restoration for SR-IOV devices after agent restarts, and also fix the issue that IP is not released when a Pod with secondary SR-IOV nic is deleted after agent restarts.
> Initialize SRIOV interfaces via NetworkStatus when agent restarts

- pkg/agent/secondarynetwork/podwatch/controller_test.go
primaryInterfaceStore is expected to be empty before a new Pod is added.
Otherwise, `reconcileSecondaryInterfaces` may restore the cniCache
unexpectly and treat a Pod add event as update and skip reconciling.
The reason is main test routine and `go podController.Run(stopCh)`
execution sequence is not guaranteed. So remove unused test codes to
fix flaky UT of TestPodControllerRun.
> Fix flaky UT of TestPodControllerRun

- docs/secondary-network.md
- pkg/agent/cniserver/interface_configuration_linux.go
- pkg/agent/cniserver/interface_configuration_linux_test.go
- pkg/agent/cniserver/interface_configuration_windows.go
- pkg/agent/cniserver/interfaces.go
- pkg/agent/cniserver/pod_configuration.go
- pkg/agent/cniserver/pod_configuration_linux.go
- pkg/agent/cniserver/pod_configuration_linux_test.go
- pkg/agent/cniserver/pod_configuration_windows.go
- pkg/agent/cniserver/secondary.go
- pkg/agent/cniserver/server.go
- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- pkg/agent/secondarynetwork/podwatch/testing/mock_podwatch.go
- test/e2e-secondary-network/secondary_network_test.go
Allow defining static mac adresses for SecondaryInterfaces
Handling VLAN network case in this PR.
using similar approach like multus with macvlan: https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/examples/macvlan-pod.yml
fixes: #6996
> Allow defining static mac adresses for SecondaryInterfaces for VLAN network

- pkg/agent/cniserver/pod_configuration_linux.go
connectInterfaceToOVSCommon no longer needs to be a separate func.
> Merge connectInterfaceToOVSCommon into connectInterfaceToOVS

- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
- test/e2e-secondary-network/secondary_network_test.go
This PR introduces support for **adding or deleting** secondary network configurations for Pods by dynamically reconciling the `k8s.v1.cni.cncf.io/networks` annotation. Users can now add new secondary network configurations or remove existing ones during a Pod's lifecycle, and the changes will be applied without requiring Pod recreation.
- **Annotation lifecycle support**:
- Adding the `k8s.v1.cni.cncf.io/networks` annotation to a Pod triggers creation of all specified secondary network interfaces
- Deleting the annotation triggers removal of all associated secondary network interfaces
- **Unsupported operations**:
- ❌ Modifying existing network entries in the annotation (e.g., adding/removing individual interfaces from the array)
- ❌ Changing interface parameters for existing network …
> Support `k8s.v1.cni.cncf.io/networks` annotation removal or reset to blank to clean up Pod's secondary interfaces

- build/charts/antrea-windows/templates/daemonset.yaml
- build/yamls/antrea-windows-with-ovs.yml
- build/yamls/antrea-windows.yml
Based on performance testing on a 4C8G Windows node running 100 pods, the antrea-agent container showed an average CPU usage of 30m and memory usage of 50MB, while the OVS container consumed 17m CPU and 23MB memory.
To account for potential burst scenarios and ensure runtime stability, both containers have been configured with resource requests of 100m CPU and 100MB memory.
> Add resource requests for Windows container in Antrea deployment

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
When the `flowExporter.protocolFilter` Helm value is nil, we need to make sure that we don't add a trailing whitespace in the rendered antrea-agent.conf YAML. Otherwise this leads to formatting issues (no pretty-printing) when displaying or editing the antrea-config ConfigMap.
This is a known "issue":
https://github.com/kubernetes/kubernetes/issues/75446.
We already have at least one other configuration value, `egress.snatFullyRandomPorts`, for which we can have a nil value and that is handled in the same way.
> Remove trailing whitespace from default manifests

- ci/kind/kind-setup.sh
- ci/kind/test-e2e-kind.sh
The commit enhances the KinD deployment script to support
creating an IPv6 or dual-stack KinD cluster for testing Antrea in
hybrid traffic mode.
> Add support for deploying IPv6/Dual-Stack hybrid mode testbed

- build/charts/antrea/conf/antrea-agent.conf
- build/yamls/antrea-aks.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
Cherry pick of #7311 on release-2.4.
#7311: Remove trailing whitespace from default manifests (#7311)
> Automated cherry pick of #7311: Remove trailing whitespace from default manifests (#7311)

- pkg/agent/secondarynetwork/podwatch/controller.go
- pkg/agent/secondarynetwork/podwatch/controller_test.go
Cherry pick of #7286 on release-2.4.
#7286: Improve secondary interface reconciliation (#7286)
> Automated cherry pick of #7286: Improve secondary interface reconciliation (#7286)

- pkg/controller/ipam/validate.go
- pkg/controller/ipam/validate_test.go
Now checks that the start IP address is not greater than the end IP address in the `IPRange` when adding/updating an `IPPool`.
Fixes #7307
> Add validation to ensure IP range start is not greater than end in IPPool

- pkg/controller/ipam/validate.go
- pkg/controller/ipam/validate_test.go
Cherry pick of #7308 on release-2.4.
#7308: Add validation to ensure IP range start is not greater than
> Automated cherry pick of #7308: Add validation to ensure IP range start is not greater than

- ci/jenkins/jobs/projects-cloud.yaml
- ci/test-conformance-eks.sh
- ci/test-sriov-secondary-network-aws.sh
- Removed all usage and references to AWS_SERVICE_USER_NAME from ci/jenkins/jobs/projects-cloud.yaml and related test scripts.
- Eliminated AWS_SERVICE_USER_NAME as a Jenkins credential and variable.
- Removed --aws-service-user parameter and all associated handling from test-conformance-eks.sh and test-sriov-secondary-network-aws.sh.
- Updated usage messages and documentation accordingly.
- Improved the cleanup logic in ci/test-sriov-secondary-network-aws.sh:
- Refactored the clean_up function to dynamically find and remove all network interfaces attached to an instance, rather than relying on a single ENI argument.
- Now waits for instance termination and for each ENI to be available before deletion, and handles possible missing ENIs gracefully.
- Updated clean_up_all to call clean_up …
> Remove AWS_SERVICE_USER_NAME usage and improve AWS EC2/ENI cleanup in SRIOV test scripts

- pkg/config/agent/config.go
* When protocolFilter was introduced, the original name still remained in the FlowExporter's struct tag
* As a result, any user configuration of protocolFilter did not propagate to the agent
* The included unit test validates a match between the generated build yaml which provides the keys for user input and the struct tag. It confirms user's inputted value for protocolFitler is properly consumed by the agent
> fix: protocolFilter struct tag typo

- pkg/agent/route/route_linux.go
- pkg/agent/route/route_linux_test.go
- test/integration/agent/route_test.go
This commit replaces the custom Antrea chain `ANTREA-MANGLE` (previously used
in the iptables mangle PREROUTING chain) with a unified name: `ANTREA-PREROUTING`.
This commit also introduces a mechanism to clean up orphan jump rules and chains
that were previously added by Antrea but are no longer in use.
> Unify Antrea iptables chain names and clean up orphan rules/chains

- ci/kind/kind-setup.sh
Cherry pick of #7346 on release-2.4.
#7346: Fix kind network cleanup failure on newly provisioned Jenkins
> Automated cherry pick of #7346: Fix kind network cleanup failure on newly provisioned Jenkins

- cmd/antrea-agent/agent.go
- cmd/flow-aggregator/flow-aggregator.go
- pkg/agent/flowexporter/exporter.go
- pkg/flowaggregator/flowaggregator.go
- pkg/flowaggregator/flowaggregator_test.go
- pkg/util/objectstore/store.go
Cherry pick of #7343 on release-2.4.
#7343: Add missing Run calls for nodeStore /
> Automated cherry pick of #7343: Add missing Run calls for nodeStore /

- test/e2e/antreapolicy_test.go
- test/e2e/multicast_test.go
- test/e2e/net_constants.go
- test/e2e/nodenetworkpolicy_test.go
- test/e2e/traceflow_test.go
- test/e2e/vmagent_test.go
Fix: #7347 
For e2e test ACNPICMPSupport, when running on an IPv6 testbed, the ICMP Echo Request type should be 128 (ICMPv6 Echo Request type) rather than 8 (ICMPv4 Echo Request type). Using the incorrect Echo Request type causes the test to produce incorrect results.
> Correct ICMPv6 echo request type in ACNPICMPSupport

- test/e2e/antreapolicy_test.go
- test/e2e/multicast_test.go
- test/e2e/net_constants.go
- test/e2e/nodenetworkpolicy_test.go
- test/e2e/traceflow_test.go
- test/e2e/vmagent_test.go
Cherry pick of #7351 on release-2.4.
#7351: Correct ICMPv6 echo request type in ACNPICMPSupport (#7351)
> Automated cherry pick of #7351: Correct ICMPv6 echo request type in ACNPICMPSupport (#7351)

- .github/workflows/kind.yml
- docs/antrea-network-policy.md
- pkg/agent/controller/networkpolicy/reject.go
- pkg/agent/controller/networkpolicy/reject_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/service_test.go
- test/e2e/antreapolicy_test.go
- test/e2e/proxy_test.go
In noEncap mode, when an ACNP with action `REJECT` is applied to a NodePort Service,
traffic to the NodePort is allowed instead of being rejected or dropped if a remote
Endpoint is selected.
Take e2e test `TestAntreaPolicy/TestGroupNoK8sNP/Case=ACNPNodePortServiceSupport` as
an example. In this test, the source IP `1.1.1.1` is expected to be rejected by the
NodePort, but the connection is instead established.
In the `AntreaPolicyIngressRule` table, the first packet of the connection is matched
by the following flows.
Note: `load:0x2->NXM_NX_REG0[25..31]` set 0x2 to `PacketInOperationField`.
```
table=AntreaPolicyIngressRule, priority=14900,conj_id=3 actions=load:0x3->NXM_NX_REG3[],load:0x1->NXM_NX_REG0[10],load:0x2->NXM_NX_REG0[25..31],load:0x19->NXM_NX_REG2[0..7],group:4 …
```
> Fix ACNP applied to NodePort failing to reject traffic in noEncap/hybrid mode

- pkg/agent/multicast/mcast_discovery.go
- pkg/agent/multicast/mcast_discovery_test.go
- test/e2e/multicast_test.go
In hybrid or encap mode, IGMP reports between Nodes could be sent via tunnels using packet-out,
with the Node transport IP as the source for encapsulated packets. For remote Nodes:
- The underlay packet (carrying the encapsulated IGMP report) uses the Node transport IP as
its source.
- The remote Node extracts this source IP of the underlay packet to determine `tun_dst`
and install OVS flow-based tunnel flows.
- The installed OVS flow-based tunnel flows ensures that the multicast traffic is correctly
forwarded over tunnel.
In hybrid or encap mode, however, the underlay packets may be SNATed before reaching the remote
Node. This means:
- The underlay packet source IP could be altered and no longer reflect the Node transport IP.
- Relying on the underlay source IP would cause incorrect OVS …
> Use a more robust way to extract the source Node IP from encapsulated IGMP messages

- build/charts/antrea/crds/packetcapture.yaml
- build/yamls/antrea-aks.yml
- build/yamls/antrea-crds.yml
- build/yamls/antrea-eks.yml
- build/yamls/antrea-gke.yml
- build/yamls/antrea-ipsec.yml
- build/yamls/antrea.yml
- docs/antctl.md
- docs/packetcapture-guide.md
- pkg/agent/packetcapture/capture/bpf.go
- pkg/agent/packetcapture/capture/bpf_test.go
- pkg/antctl/raw/packetcapture/command.go
- pkg/antctl/raw/packetcapture/command_test.go
- pkg/apis/crd/v1alpha1/types.go
- test/e2e/packetcapture_test.go
Fixes: #6976 
This PR enhances the `PacketCapture` feature by making the `.spec.source` and `.spec.destination` fields optional. It addresses the limitation where users were required to specify both endpoints, preventing them from being able to capture all ingress or egress traffic for a given Pod.
With this change, users can now specify just a `source` or just a `destination`, as long as at least one of them is present in the manifest.
@antoninbas @hangyan 
Let me know if the updated code looks good to you or if you'd like me to tweak anything further!
> [PacketCapture] Support arbitrary source or destination

- .github/workflows/build.yml
- .github/workflows/build_tag.yml
- .github/workflows/kind.yml
CNCF has hosted ephemeral GitHub runners on Oracle that we want projects to use instead of the GitHub-hosted ones, which now incur a cost to use.
Please direct any questions to me, @jeefy, @krook, and @RobertKielty. You can also join `#cncf-ci-infra` channel on CNCF Slack.
> update github runners to oci gh arc runners

- .github/workflows/kind.yml
- docs/antrea-network-policy.md
- pkg/agent/controller/networkpolicy/reject.go
- pkg/agent/controller/networkpolicy/reject_test.go
- pkg/agent/openflow/pipeline.go
- pkg/agent/openflow/service_test.go
- test/e2e/antreapolicy_test.go
- test/e2e/proxy_test.go
Cherry pick of #7265 on release-2.3.
#7265: Fix ACNP applied to NodePort failing to reject traffic in
> Automated cherry pick of #7265: Fix ACNP applied to NodePort failing to reject traffic in

- pkg/agent/multicast/mcast_discovery.go
- pkg/agent/multicast/mcast_discovery_test.go
- test/e2e/multicast_test.go
Cherry pick of #7282 on release-2.3.
#7282: More robust way to extract source Node IP from encapsulated
> Automated cherry pick of #7282: More robust way to extract source Node IP from encapsulated

- multicluster/build/yamls/antrea-multicluster-member.yml
- multicluster/cmd/multicluster-controller/controller.go
- multicluster/cmd/multicluster-controller/leader_test.go
- multicluster/cmd/multicluster-controller/member_test.go
- multicluster/config/overlays/member/role.yaml
- multicluster/controllers/multicluster/common/controller_utils.go
- multicluster/controllers/multicluster/common/controller_utils_test.go
- multicluster/controllers/multicluster/common/test_data.go
- multicluster/controllers/multicluster/member/node_controller.go
The original way to get the ServiceCIDR is from an error message, but
the error message doesn't contain the Service IP range anymore since
1.33. Change it to a new network API to get Service CIDR conditionally
when the K8s version is newer than 1.33.0. 1.33.0 is the version which
the ServiceCIDR CR was enabled by default.
```
F0710 03:59:25.869671      14 member.go:45] Error running controller: error creating Node controller: could not determine
the ClusterIP range via Service creation - the expected error was not returned. The actual error was "Service \"invalid-svc\"
is invalid: spec.clusterIPs: Invalid value: []string{\"0.0.0.0\"}: failed to allocate IP 0.0.0.0: the provided network does not
match the current range"
```
> Fix ServiceCIDR issue in Multi-cluster member controller

- cmd/antrea-agent/agent.go
- pkg/agent/controller/traceflow/packetin.go
- pkg/agent/controller/traceflow/packetin_test.go
- pkg/agent/controller/traceflow/traceflow_controller.go
- pkg/agent/controller/traceflow/traceflow_controller_test.go
- pkg/apis/crd/v1beta1/types.go
- pkg/controller/traceflow/controller.go
- test/e2e/traceflow_test.go
Cherry pick of #7266 on release-2.4.
#7266: Handle Traceflow external destination IP correctly in NoEncap
> Automated cherry pick of #7266: Handle Traceflow external destination IP correctly in NoEncap

- .github/workflows/kind.yml
- pkg/antctl/raw/check/cluster/command.go
- pkg/antctl/raw/check/installation/command.go
- pkg/antctl/raw/check/installation/command_test.go
- pkg/antctl/raw/check/installation/test_denyall.go
- pkg/antctl/raw/check/util.go
Instead of using a hard-coded 2s value.
While I am not able to reproduce the issue locally (even without a sleep), the egress-deny-all-connectivity and ingress-deny-all-connectivity tests sometimes fail in CI, presumably because the policy has not been realized by all Agents yet. So to help prevent the issue, we use a 5s delay in CI, using the new flag.
> Add network-policy-delay flag to antctl check installation

- go.mod
- go.sum
- pkg/antctl/raw/multicluster/get/join_config_test.go
A new error "NotExistError" was introduced since v1.0.7, refined the test codes to check error message to fix the UT failure:
```
Error Trace:	/home/runner/work/antrea/antrea/pkg/antctl/raw/multicluster/get/join_config_test.go:215
Error:      	Not equal: 
expected: *errors.errorString(&errors.errorString{s:"flag accessed but not defined: kubeconfig"})
actual  : *pflag.NotExistError(&pflag.NotExistError{name:"kubeconfig", specifiedShorthands:"", messageType:1})
Test:       	TestOptValidate/K8s_client_error
```
https://github.com/antrea-io/antrea/actions/runs/17506341499/job/49730539389?pr=7411
This is to replace the PR https://github.com/antrea-io/antrea/pull/7411
> fix(deps): update module github.com/spf13/pflag to v1.0.10

- cmd/antrea-agent/agent.go
- pkg/agent/controller/networkpolicy/allocator.go
- pkg/agent/controller/networkpolicy/allocator_test.go
- pkg/agent/controller/networkpolicy/fqdn_test.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller.go
- pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
- pkg/agent/controller/networkpolicy/pod_reconciler_test.go
- pkg/agent/flowexporter/connections/connections.go
- pkg/agent/flowexporter/connections/connections_test.go
- pkg/agent/flowexporter/connections/conntrack_connections.go
- pkg/agent/flowexporter/connections/conntrack_connections_perf_test.go
- pkg/agent/flowexporter/connections/conntrack_connections_test.go
- pkg/agent/flowexporter/exporter.go
- pkg/agent/flowexporter/exporter_perf_test.go
- pkg/agent/flowexporter/exporter_test.go
- test/integration/agent/flowexporter_test.go
To avoid missing or invalid NetworkPolicy data in flow records, we increase the time interval during which the mapping from flow ID to NetworkPolicy rule is available in the idAllocator after rule deletion. During that time, the flow ID cannot be reused.
We also avoid resolving NetworkPolicy metadata for connections which started prior to the Agent starting and the initial NetworkPolicy flows being installed. After an Agent restart, the flow ID assignment is expected to change, and we do not want to include invalid NetworkPolicy data for these connections (better to omit it altogether). We only make this change for the "conntrack" connection store. The "deny" connection store is not as sensitive to this because it reacts to PacketIn messages and not conntrack entries (which can exist for …
> [FlowExporter] Avoid invalid NetworkPolicy data in records

- pkg/agent/flowexporter/connections/connections.go
- pkg/agent/flowexporter/connections/conntrack_connections.go
- test/integration/agent/flowexporter_test.go
We can use this to evaluate improvements to the FlowExporter in the future.
Current results:
```
go test -bench=BenchmarkConntrackConnectionStorePoll -cpuprofile=cpu.out -benchtime=100x -benchmem -run=XXX ./test/integration/agent/
goos: linux
goarch: amd64
pkg: antrea.io/antrea/test/integration/agent
cpu: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
BenchmarkConntrackConnectionStorePoll-16    	     100	 279751187 ns/op	146577693 B/op	 2373538 allocs/op
--- BENCH: BenchmarkConntrackConnectionStorePoll-16
flowexporter_test.go:229: Creating 32768 conntrack entries across multiple destination addresses...
flowexporter_test.go:262: Cleaning up 32768 conntrack entries...
PASS
ok  	antrea.io/antrea/test/integration/agent	29.711s
```
CPU time is almost the same when forcing `GOMAXPROCS=1`.
This …
> Add benchmark for ConntrackConnectionStore's Poll method

- build/yamls/antrea-aks-node-init.yml
- build/yamls/antrea-aks.yml
- build/yamls/chart-values/antrea-aks.yml
- ci/test-conformance-aks.sh
- docs/aks-installation.md
- docs/contributors/eks-terraform.md
- docs/contributors/github-labels.md
- docs/design/architecture.md
- docs/getting-started.md
- docs/kubernetes-installers.md
- docs/maintainers/release.md
- docs/versioning.md
- hack/generate-standard-manifests.sh
- pkg/agent/agent.go
- test/integration/agent/cniserver_test.go
We stopped testing Antrea on Azure. This patch adds disclaimers to Azure related code and docs.
> Add Disclaimer to Azure Docs and Code

- pkg/agent/memberlist/cluster.go
- pkg/agent/memberlist/cluster_test.go
This is a follow-up to #7448.
The change in behavor of assert.Eventually has caused to the unit test to become flaky. This change improves how the result of egress selection is validated, and resolves the flakiness issue.
It is expected that the test function can be greatly improved when we upgrade to Go 1.25 and we can start using the new testing/synctest package. Upgrading to Go 1.25 is not immediately possible because of some dependency issues.
> [Flaky unit test] Fix TestCluster_RunClusterEvents
