antrea-io/antrea

pkg/controller/networkpolicy/networkpolicy_controller.go
Along with namespace event handlers, add
logic to sync Groups and internal NP
objects.
=> Network Policy Controller sync

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
Kubernetes Nodes need to perform liveness and readiness probes which
might be an HTTP and TCP request, it requires NetworkPolicy
implementation always allow a Node access all its local Pods.
This patch appends the Node gateway IP which will be used when a Node
accesses Pods to the FromAddresses of the CompletedRule to achieve it.
Related to #52
=> Allow Node access all local Pods to perform probes

go.mod
Mark octant version 0.8.0 in go.mod.
Fixes #111
=> Fix octant version in go.mod

build/images/Dockerfile.build.ubuntu
Optimize the binaries build steps in `Dockerfile.build.ubuntu`:
1. COPY go.mod
2. Download dependencies per go.mod
3. build binaries
If the go.mod file have no change. The step-1 and step-2 will not be
excuted and use docker layer cache instead. Thus we can skip downloading
go packages repeatedly if no dependencies change. The total build time
will be reduced.
Fixes #67
=> Avoid downloading go packages repeatedly when "make build"

cmd/antrea-octant-plugin/main.go
Add a new column named "Last Heartbeat Time" for both controller
and agent on UI to show controller and agent health status.
The column should be updated every 60 seconds if controller/agent
runs fine, as a result, we can easily identify controller/agent health
status via UI with this column.
Fixes #115
=> Add lastHeartbeatTime to UI

cmd/antrea-agent/agent.go, pkg/monitor/monitor.go, pkg/monitor/querier.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
Get ovs_version from OVSDB and populate monitoring CRD
AntreaAgentInfo field Version in OVSInfo during CRD creation.
Fixes #42
=> Get and populate ovs_version

.github/workflows/update_ovs_image.yml, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/build_and_push.sh
Because this is the base image used for the Antrea image, it is good to
build and push it periodically so that Ubuntu security updates can be
picked up.
=> Update antrea/openvswitch base image periodically

.dockerignore
Otherwise the `git status --porcelain` command we run in versioning.mk
will mark the version as "dirty" on the master branch. This means that
we need to make sure that all version-controlled files are always
included in the docker context. If that proves to be an issue, we can
come up with alternative solutions. In particular, it is inconvenient to
*not* be able to ignore the .git folder...
=> Do not include dockerfiles in .dockerignore

go.mod, pkg/controller/networkpolicy/networkpolicy_controller.go
In NetworkPolicy controller, the UUIDNamespace constant does not
need to be globally scoped. This patch converts it to a locally
scoped constant within the networkpolicy package.
=> UUIDNamespace constant must be locally scoped

test/e2e/framework.go
This patch is to add label for resource in antrea-e2e test. It should be helpful for CI to get all antrea-e2e related resources with command like: ```kubectl get all -o wide -A -l 'antrea-e2e'```.
Currently, all resources are in namespace "antrea-test". But testcases using more namespaces are expected.
=> Add label for resource in antrea-e2e test

Makefile, hack/tidy-check.sh
- Omit to set the GOPROXY environment variable in Makefile
- Tell developer to use `make docker-tidy` instead `make tidy` if there is no Go installation or the 
Go version is not the expected
Fixes #142
=> Remove GOPROXY variable in Makefile

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
The mockReconciler is not thread-safe. The patch fixes it and also
changes to use a separate channel to receive deleted events in case
that there're several Reconcile calls when events are handled in
specific order, which results in multiple notification in "updated"
channel and affect the test of rule deletion.
Fixes #145
=> Fix race condition in unit test case TestDeleteRule

build/images/apache-bench/Dockerfile, build/images/apache-bench/README.md
The image includes the ApacheBench ("ab") HTTP benchmark utility program
from Apache. We actually install the entire apache2-utils package but we
only care about ApacheBench for testing. We may rename the image in the
future if appropriate.
=> Add apache-bench image for testing

pkg/agent/cniserver/server.go
This patch ensures the required working directory exist before binding
on sockets under it.
Related to https://github.com/vmware-tanzu/antrea/pull/141#issuecomment-559516591
=> Create the working directory if not exists

test/e2e/framework.go, test/e2e/providers/remote.go
Implemented the remote provider which accepts sshconfig file and kubeconfig file to run the e2e test on a remote Kubernetes cluster.
The provider accept two new flags:
- `remote.kubeconfig`: Path of the kubeconfig of the cluster in local machine
- `remote.sshconfig`: Path of the sshconfig
=> Add a new e2e provider to make test running on remote cluster

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Install Openflow entry on ingress rule table to allow the liveness probe traffic
that is sent from node to local Pods. The flow entry is installed on the ingress
rule table, matching local gateway IP as the source address, and the action is
to resubmit the packets to L2 forwarding output table.
Fixes #176
=> Allow Node probe all local Pods

.github/workflows/go.yml, .github/workflows/kind.yml
Otherwise we may not detect a situation where a PR is merged and even
though the CI was "green" for the PR, the master branch is broken. An
alternative would be to require PRs to always be up-to-date before
merging but IMO that doesn't scale very well and starts being painful
even with a few PRs a day.
This change will also ensure that the CI badge we display in the README
is accurate.
=> Also run CI jobs (Go / Kind) on push events

docs/getting-started.md
changed (built from mater) to (built from master) on the Getting Started Guide
=> typo fixed

pkg/controller/networkpolicy/networkpolicy_controller.go
While processing a NetworkPolicy rule (ingress or egress), we must
append AddressGroups to the list unique to that particular rule
instead of appending them to a global AddressGroup slice which
would incorrectly apply the rule to all AddressGroups calculated
for that NetworkPolicy.
Fixes: #161
=> Fix NetworkPolicy rules processing

Makefile, pkg/agent/util/ethtool/doc.go
- Install golint if it not exists
- Run `make lint` with env var `GOOS=linux`
Resolve #169
=> Fix broken `make lint` target

.github/workflows/integration.yml, test/integration/agent/cniserver_test.go
This required fixing yet another error in the CNI server test: when
checking for interface deletion, the test was not using the correct
network namespaces / interface names. This was going unnoticed on dev
machines when there was no "eth0" interface. However, the Github CI
worker VM seems to have an eth0 interface. When checking for container
interface deletion, the test would look for an "eth0" interface in the
root namespace (instead of the container namespace) and expect not to
find it. But because of the network configuration for the Github CI
worker VM - i.e. because of the presence of an eth0 interface - the test
was failing (for the wrong reason).
Fixes #179
=> Run integration tests as part of CI

go.mod, go.sum, test/e2e/README.md, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/performance_test.go
This CL:
- Add intra-node pods http request bench tests
- Add network policies realization bench tests
The performance bench test accepts four new flags:
- `performance.http.requests`: Number of http requests for customized scale bench test (default 0, skip customized scale test)
- `performance.http.workloads`: Number of CIDRs in the network policy (default 0, skip customized scale test)
- `performance.http.concurrency`: number of multiple requests to make at a time (default 1)
- `performance.realize.timeout`: timeout of the realization of network policies (default 5m0s)
=> Add performance bench test

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Before this change, the flow was matching on ct_state=+new+inv and
dropping all matching packets. According to the OVS documentation:
>If inv is set, only the trk flag is also set.
Which makes sense because an invalid packet is a packet whose state
cannot be determined. Therefore it seems that in its current state, the
rule can never be matched. It should be changed to match on
ct_state=+inv+trk (should be equivalent to ct_state=+inv, but I added
+trk to match the style of other flows).
=> Fix rule for INVALID packets in conntrackStateTable

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
I ran into this issue while writing documentation for the OVS pipeline
so I thought I would take care of it.
Had to revert manually because of a conflict.
This reverts commit fe0736758f6ff1506f5793b608122210a3a93ee9.
=> Revert "Allow Node access all local Pods to perform probes (#104)"

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Otherwise this flow will match L2 traffic from local Pods to the
gateway, which is harmless but unnecessary and confusing.
=> In L3 table, only match tunnelled traffic for gw dst MAC rewrite

test/e2e/fixtures.go
The e2e log dir would be like:
`/tmp/antrea-test-906161942/TestIPBlockWithExcept.Dec 9-21-51-35`, which
is not filepath-friendly to copy and paste for usage. This patches
changes to use a format like "Dec09-21-51-35" to avoid spaces in the
path.
=> Fix filepath-unfriendly e2e log directory

.github/workflows/build_master.yml, .github/workflows/integration.yml, .github/workflows/update_ovs_image.yml
Such jobs are bound to fail - as they should - when run from a fork
(since the fork does not have permission to push to the dockerhub repo).
It is a bit verbose, and the workflows are still running (i.e. a worker
VM is created) which consummes some compute resources, but I believe the
Github team is working on improving this.
This is the best way I found to do this. I believe Github is working on
a better way to skip workflows.
=> Disable workflows that push to Dockerhub for forks

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go, test/integration/ovs/ofctrl_test.go
Rewrite dst MAC with host gateway's MAC for the packets sent back from the
Endpoint located on the same Node as the sender, and not use ct_label as the
cache for dynamic learning.
Fixes #211
=> Rewrite dst MAC with host gateway's MAC

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Add ARP spoof guard flow entry after host gateway interface is created.
Fixes #200
=> Add ARP spoofing guard for host gateway port

.github/workflows/kind.yml, test/e2e/framework.go, test/e2e/networkpolicy_test.go
This PR adds an e2e network policy test on cases that include IPBlock with Except field. Such testcase is not in conformance test and helps verify #71 .
=> Add e2e network policy test: IPBlock with Except field

pkg/controller/networkpolicy/networkpolicy_controller_test.go
Add unit tests coverage for the NetworkPolicy Controller. Specifically, this PR adds unit tests for:
- NetworkPolicy event handling
- Pod event handling
- Namespace event handling
Related to: #52
=> Improve NetworkPolicy controller UT coverage

pkg/agent/openflow/pipeline.go
It has been unused since #63 was merged.
=> Remove unused serviceCache in OF client

build/yamls/antrea.yml, build/yamls/base/controller-rbac.yml, cmd/antrea-agent/main.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/main.go, pkg/monitor/monitor.go, pkg/signals/signals.go
Remove stale AntreaAgentInfo
1. Let Antrea Controller to cleanup stale AntreaAgentInfo after
removing a K8s node or starting/restarting Controller.
2. Rename monitorig CRDs.
3. Refactor code for monitoring module.
Fixes #128
=> Remove stale CRDs

.github/workflows/go.yml, .gitignore, .golangci.yml, Makefile, pkg/agent/cniserver/server_test.go, pkg/agent/openflow/pipeline.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/monitor/monitor.go, pkg/ovs/openflow/interfaces.go, test/e2e/providers/exec/docker.go, test/integration/agent/cniserver_test.go
For now we enable the following linters: misspell, gofmt, deadcode
(changes have been made in the code to fix existing issues reported by
these linters). I picked these linters because the current Antrea code
was already mostly conformant with these and I think the probability of
a false positive is close to 0. More linters can be added to the list
later.
In particular, with this change we will be able to catch typos in
comments before merging a commit.
=> Run golangci-lint as part of CI

hack/kind-linux.sh
The pattern was not specific enough and sometimes we had multiple
matches, causing the ethtool invocation to fail and preventing TX
checksum offload from being disabled properly.
Fixes #205
=> Fix grep pattern in kind-linux.sh script

README.md, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, docs/architecture.md, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go
Reasons to add GRE and STT support:
1. There is no harm to support more options.
2. So far with my tests IPSec works only for GRE (it could be due to OVS or module versions, and I am still debugging).
3. STT has best performance when NIC does not support offloading with encapsulation.
=> Add support for GRE and STT tunnels

.github/workflows/kind.yml, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/integration/agent/openflow_test.go
Add conntrackCommit table(#105) between ingressDefault table(#100) and
L2ForwardingOut(#110) table, and packets in the new connections are committed
in this table. There is no table-miss flow in this table.
Fixes #219
=> Commit new connections after NetworkPolicy check

pkg/agent/cniserver/pod_configuration.go, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
1. Change the priority of tableMiss from 80 to 0. Otherwise there would be
another flow entry with action "Normal" added by OVS automatically after
the bridge is created.
2. Change the default action of classifier table to drop packets.
Fixes #195 
=> Drop packets from unknown interfaces in classifier table

cmd/antrea-agent/agent.go, pkg/agent/cniserver/server.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/controller/networkpolicy/networkpolicy_controller.go, test/integration/agent/cniserver_test.go
Currently only Pods that have IPs are included in AppliedToGroups. It
makes a Pod's NetworkPolicies not enforced until it has IP assigned in
kube-apiserver, which always introduces a time slot that the Pod is not
isolated by NetworkPolicies created before it.
To enforce NetworkPolicies to Pods, antrea-agent doesn't need PodIPs
from kube-apiserver but the OFPort and IP from internal InterfaceCache.
This patch uses a channel to receive Pod update events from CNIServer
and notify NetworkPolicyController to reconcile rules related to the
updated Pods.
Fixes #197
=> Trigger reconciling NetworkPolicy rules upon CNI Add

.github/workflows/kind.yml, test/e2e/connectivity_test.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go
TestPodConnectivityAfterAntreaRestart destroys and recreates dataplane
which affects existing connection between components (e.g coredns and
antrea-controller) and kube-apiserver somehow and they don't receive
events stream in some time. Since it only happens on Kind cluster, it
might be related to the dataplane implementation.
Before we can resolve it, skip the test in case of tests depending on
coredns and antrea-controller failing.
Related to #244
=> Skip TestPodConnectivityAfterAntreaRestart in Kind CI

hack/generate-manifest.sh
The cp command was failing because patches/release/ has no YAML files at
the moment. I ran into this issue as I was generating the YAML manifest
for v0.2.0.
=> Fix generate-manifest.sh for release mode

.github/workflows/integration.yml, Makefile
=> Use desired version of Go in CI test-integration

pkg/apiserver/registry/networkpolicy/appliedtogroup/rest.go
AppliedToGroup was mistakenly referred to as an addressGroup.
=> Fix variable name

go.mod, hack/tidy-check.sh
We use octant@v0.8.0 instead of latest octant due to
K8s API compatibility issue. We may accidentally change the octant
version in go.mod to v0.0.0-00010101000000-000000000000 when executing command
like 'make mocks', which will cause 'go get' command failure mentioned in issue:#111.
This patch adds octant version check to tidy-checks to avoid the issue.
=> Add octant version check to tidy-check.sh

cmd/antrea-agent/agent.go, cmd/antrea-controller/controller.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/apis/clusterinformation/v1beta1/types.go, pkg/apis/clusterinformation/v1beta1/zz_generated.deepcopy.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/monitor/monitor.go, pkg/monitor/querier.go
1.And NetworkPolicy related fields (NetworkPolicyNum, AddressGroupNum, AppliedToGroupNum)
to both Controller and Agent monitoring CRDs.
2.Populate Controller NetworkPolicy related fields by information stored in the Antrea object storage.
3.Populate Agent NetworkPolicy related fields by information stored in ruleCache.
Fixes #230
=> Add NetworkPolicy information to monitoring CRDs

pkg/agent/iptables/iptables.go, test/integration/agent/iptables_test.go
The FORWARD rules managed by kube-proxy doesn't accept non masqueraded traffic explicitly, so traffic accessing NodePort service with Local externalTrafficPolicy was dropped when the default FORWARD policy was DROP.
This PR fixes it by accepting such traffic with antrea FORWARD rules. It also adds an integration test for iptables code.
Fixes #265 
Other CNI plugins like flannel and calico support it in a similar way, so there should be no concern that it breaks host security policy.
For example: flannel appends rules to allow such traffic explicitly:
```
-A FORWARD -s <POD CIDR> -j ACCEPT
-A FORWARD -d <POD CIDR> -j ACCEPT
```
=> Support NodePort service with Local externalTrafficPolicy

test/e2e/infra/vagrant/playbook/roles/master/tasks/main.yml
The directory was owned by root which prevented kubectl from using
~/.kube/cache. This became an issue for K8s 1.17.0 because of the low
burst value when throttling API discovery requests. It ended up taking a
minute to run "kubectl get -A all" on the cluster created with Vagrant.
See https://github.com/kubernetes/kubernetes/issues/86149 and
https://github.com/kubernetes/kubernetes/issues/86462.
=> Fix ownership of ~/.kube directory created in Ansible playbook

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/types.go, pkg/agent/util/net.go, pkg/agent/util/net_test.go
For a Pod interface, use "pod/<Pod-Namespace-name>/<Pod-name>" to be
the key, and "<Pod-Namespace-name>/<Pod-name>" for the prefix.
For a Node's tunnel interface, use "node/<Node-name>" to be the key,
and "<Node-name>" for the prefix.
No more remove '-' in the prefix, and no more append extra bytes to
the prefix when it is shorter than the length limit.
Also change interfaceCache to use interface key as the map key.
=> Change Pod and tunnel network interface name format

pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/apiserver/storage/interfaces.go, pkg/apiserver/storage/ram/store.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/monitor/monitor.go, pkg/monitor/querier.go
1. From Controller side, this patch populates AntreaControllerInfo
field ConnectedAgentNum by the number of watchers of internalNetworkPolicyStore.
2. From Agent side, this patch populates AntreaAgentInfo
AgentCondition typed ControllerConnectionUp. The condition status
of ControllerConnectionUp will be true only if all the three
watchers from Agent side are able to watch the corresponding
resources (NetworkPolicies, AppliedToGroups, AddressGroups).
Fixes: #257
=> Populate Controller and Agent connection information

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller-rbac.yml, ci/check-manifest.sh
API groups for CRDs  are not changed in some yaml file
and this can cause operations on CRDs fail.
This patch fixes the issue by changing them to
clusterinformation.antrea.tanzu.vmware.com.
=> Fix API groups for CRDs

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
In antrea-agent, iptables command sometimes failed with exit code 4 and
message "iptables: Resource temporarily unavailable.", which indicates
that errno EAGAIN is returned by the kernel and is mostly because
multiple iptables commands run concurrently. iptables has a lock
"/run/xtables.lock" to solve the concurrent issue and support "--wait"
option to wait for the xtables lock. However, antrea-agent runs in
container so its own xtables.lock was created and thus kube-proxy and
antrea-agent could still run iptables at the same time.
kube-proxy pod has mounted xtables.lock of hostPath, antrea-agent should
do the same to avoid concurrent iptables calls.
Fixes #287
=> Mount xtables lock to antrea-agent container

pkg/agent/openflow/client.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/apis/clusterinformation/v1beta1/types.go, pkg/monitor/monitor.go, pkg/monitor/querier.go
1.Get Openflow connection condition via function
isConnected exposed by Openflow client.
2.Get OVSDB connection condition via a dummy version query.
3.Populate both Openflow connection condition and
OVSDB connection condition to Agent monitoring CRD.
Fixes: #289
=> Get and populate OVS connection conditions

test/e2e/framework.go, test/e2e/networkpolicy_test.go
NetworkPolicy e2e test involves dns resolving and dns resolving and
service loadbalancing which relies on coredns and kube-proxy. It's
observed that the test sometimes failed on dns resolving. This PR adds
retries when testing connection to avoid flakes due to coredns and
kube-proxy data syncing delay.
Besides, it corrects out-of-date function names and comments, and
removes connection tests against pod IPs directly as they have been
covered by service tests and can extend the testing time.
=> Add retry to networkpolicy e2e test to avoid flakes

build/images/scripts/start_ovs_ipsec, go.mod, pkg/agent/cniserver/pod_configuration.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/types.go, test/e2e/basic_test.go, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/ipsec_test.go
In case of Agent restart, Nodes may have left the cluster while the
Agent was offline, and some gateway routes / tunnel ports may be
stale.
Even though stale routes might not create connectivity issue, they may
confuse users trying to troubleshoot networking issues, so it's better
to remove them.
Stale tunnel ports (either because a Node has left the cluster of
because the configuration is no longer valid) must be removed / updated
as well.
Another approach may be to use Resource Version when starting the watch
in the controller, as "delete" events would then be replayed, but that
would require us to store some state (latest Resource Version processed
by the controller) under /var/run and may make the main controller logic
more complex. Still I would be open to that approach as well. …
=> Cleanup stale gateway routes and tunnel ports on Agent startup

docs/assets/ovs-pipeline.svg, docs/ovs-pipeline.md
Some detailed documentation for the OVS pipeline, including a
description of each table. This is directed at developers and people
trying to troubleshoot issues.
It includes a SVG high-level diagram of the pipeline. We use SVG
directly so it renders better on all screens and to avoid having to
check-in a "large" PNG image that may need to be updated often.
More documentation specific to the Network Policy implementation will
follow later.
Fixes #27
=> Add documentation for Antrea's OVS pipeline

.github/workflows/build_master.yml, .github/workflows/build_tag.yml, Makefile, build/yamls/antrea-octant.yml, docs/octant-plugin-installation.md
Build and push octant-antrea-ubuntu to dockerhub,
so that users do not need to build the image while
deploying antrea-octant-plugin.
Related to : #261
=> Push image octant-antrea-ubuntu to dockerhub

pkg/apiserver/storage/ram/store.go, pkg/apiserver/storage/ram/store_test.go, pkg/apiserver/storage/ram/watch.go, pkg/apiserver/storage/ram/watch_test.go
It's easy to get a number of events buffered in watchers' channel in a
scale cluster. This patch increases the buffer size to 1000 and uses a
timeout mechanism to handle the case that a watcher can't consume
events in time. For each event, it's given 50 ms for blocking send;
watchers that can't finish in time will be terminated to guarantee no
event will be missing and the total processing time will not be
affected by a few unresponsive clients.
Fixes: #277
=> Fix events dropped due to full channel buffer 

build/images/apache-bench/Dockerfile, build/images/perftool/Dockerfile, build/images/perftool/README.md, test/e2e/performance_test.go
- Add iperf3 to the performance test image for bandwidth benchmark implementation
- Rename the image name `apache-bench` to a more generic name `perftool`
=> Add iperf3 to the performance test image

test/e2e/bandwidth_test.go
This CL added a new benchtest `BenchmarkBandwidthIntraNode` which runs the benchmark of bandwidth between pods on same node.
A test result on my laptop.
```
pkg: github.com/vmware-tanzu/antrea/test/e2e
BenchmarkBandwidthIntraNode-16    	       1	57308932970 ns/op	        44.5 Bandwidth(Gbits/sec)
```
The op-speed is meaningless in this test, we should only care bandwidth here.
=> Implement intra-node traffic bandwidth benchmark

pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, test/integration/agent/cniserver_test.go, test/integration/agent/iptables_test.go
Netns of a container might have been invalid when CNI is invoked to
do CNI Del, which could happen when container processes are terminated
by accident or they are short-running jobs. antrea-agent should try its
best-effort to clean up the networking resources as many as it can, as
the CNI spec suggests:
> Plugins should generally complete a DEL action without error even if
some resources are missing. For example, an IPAM plugin should generally
release an IP allocation and return success even if the container
network namespace no longer exists, unless that network namespace is
critical for IPAM management.
This PR improves the robustness of CNI DEL processing by not relying on
presence of netns. Instead, it deletes the host side veth to clean up
veth devices.
Besides, it unifies log …
=> Improve the robustness of CNI DEL processing

.github/workflows/kind.yml
v0.7.0 is the latest version of Kind. The default Node image for this
version of Kind is a Kubernetes v1.17.0 image.
=> Use Kind v0.7.0 for CI

.github/workflows/kind.yml, test/e2e/basic_test.go, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/ipsec_test.go
We should always use the provider name, and not rely on the "-short"
command-line option.
=> Use consistent mechanism to skip tests on Kind cluster

.github/workflows/kind.yml, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/cookie/allocator.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/round.go, test/e2e/basic_test.go, test/e2e/framework.go, test/e2e/performance_test.go, test/integration/agent/openflow_test.go
If the antrea-agent restarts, but not the antrea-ovs container, all
existing OVS flows are preserved in ovs-vswitchd. If some changes occur
while the antrea-agent is down (e.g. a Node leaves the cluster, or
Network Policies are updated), it is possible that some of the preserved
flows are now stale and should be deleted. This is why we introduced in
the past the concept of "round number / id" which we increment every
time the agent restarts (it is persisted in OVSDB on the Node), and we
encode as part of the cookie for each flow we install. The rationale for
that is that it would enable us to identify which flows are stale after
a restart: flows which are still required would receive an updated
cookie, while stale flows would still have the old cookie (with the old
round number) and we …
=> Delete stale flows on agent restart

build/images/ovs/Dockerfile, build/images/ovs/charon-logging.conf, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go
IPSec encryption works for only GRE tunnel, so changes Agent config
valiation to allow EnableIPSecTunnel only when the tunnel type is
set to GRE.
Also improve the logging config of strongSwan charon daemon.
=> Allow IPSec encryption only for GRE tunnel

build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu, build/images/scripts/install_cni
As part of the Antrea installation process (install_cni script). The
loopback plugin is required by kubelet on Linux when using the docker
container runtime.
Fixes #349
=> Install loopback plugin on Nodes if missing

build/images/codegen/Dockerfile
Added openapi-gen installation for openapi spec generation.
Since the `k8s.io/kube-openapi` does not have tags, a workable commit hash is used.
=> Update codegen image

.golangci-golint.yml, Makefile
This simplifies the Makefile a bit and means we no longer need to
install golint separately with "go get", which can cause the go.mod file
to be modified.
Fixes #170
=> Use golangci-lint to run golint

test/e2e/infra/vagrant/playbook/roles/worker/tasks/main.yml
This was done for the master role previously, but we missed the worker
role. This prevents kubectl from using ~/.kube/cache when run from a
worker, which causes performance issues.
=> Fix ownership of ~/.kube directory in Ansible playbook for worker

docs/ovs-pipeline.md, pkg/agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go
Change to use flow based tunnel for IPSec encyption as well, so OVS
flows will be the same no matter IPSec is enabled or not. A separate
tunnel port/interface is still created for each remote Node, which is
required for the OVS IPSec monitor daemon to detect the new tunnel and
create IPSec security policies for the Node using psk and remote_ip
options of the tunnel interface.
=> Still use flow based tunnel when IPSec encyption is enabled

Makefile, build/yamls/antrea-octant.yml, build/yamls/octant/base/deployment.yml, build/yamls/octant/base/kustomization.yml, build/yamls/octant/base/service.yml, build/yamls/octant/patches/dev/imagePullPolicy.yml, build/yamls/octant/patches/release/.gitignore, ci/check-manifest.sh, docs/maintainers/release.md, docs/octant-plugin-installation.md, hack/generate-manifest-octant.sh, hack/generate-manifest.sh
At the moment we have a Github workflow to upload a tagged Docker image
for Octant + the Octant Antrea plugin, for each release. This is
currently broken because of a typo in the Makefile. In addition to
fixing that typo, this change introduces support for generating a
release antrea-octant.yml manifest that can be uploaded with each
release. Despite the availability of the yaml, users will likely need to
edit the file to match their environment before they can apply it. In
the future we may want to enhance the hack/generate-manifest-octant.sh
script so that user can use a single command to deploy Octant and the
Antrea plugin:
```
./hack/generate-manifest-octant.sh --image octant-antrea-ubuntu:v0.3.0 \
--octant-accepted-hosts <X> \
--octant-listener-addr=<Y> | kubectl apply -f -
```
Fixes …
=> Create release version of antrea-octant

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, docs/architecture.md, docs/configuration.md, docs/getting-started.md, docs/ipsec-tunnel.md
Add docs/ipsec-tunnel.md that describes how to deploy Antrea with
IPSec enabled.
Add IPSec design to architecture.md.
Update docs/configration.md and add IPSec config parameters.
closes #62
=> Add user documentation and update architecture doc for IPSec

pkg/ovs/ovsconfig/ovs_client.go
Assign the default value first to make sure the address log correctly.
=> Reorder log statement to make output friendly

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
Whenever an Egress NetworkPolicy is created whose To includes
everything, create an AddressGroup which selects all Pods from
all Namespaces and set it in the match all Peer.
Fixes: #343
=> Add AddressGroup to select everything

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/apis/networking/v1beta1/sets.go
When iterating a slice and storing its items' address, must not use the
address of the loop iterator variable as it's the same address taking
different values in each loop iteration, otherwise the stored items
would eventually contain only the last item.
See https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
This patch fixes it and hardens the unit test to validate the value of
stored items, instead of their keys.
Fixes #381
=> Fix agent caching duplicate pod member

pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/networkpolicy.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/integration/agent/openflow_test.go
A policy rule will be split into multiple Openflow rules based on the
named port resolving result. Pods that have same port numbers for the
port names defined in the rule will share an Openflow rule.
Add an e2e test for the different named ports case.
Fixes #122
=> Split a policy rule into Openflow rules based on resolved ports

.github/workflows/go.yml, .github/workflows/integration.yml
This patch is to keep the UT and integration test can be passed when we
make changes for windows platform. Currently, these tests only run on
linux platform. After essential windows patches checked in, we should
also add windows platform in workflow.
=> [Windows] Add windows branch in github UT and integration test workflow

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/iptables/iptables.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route.go, test/integration/agent/cniserver_test.go, test/integration/agent/iptables_test.go, test/integration/agent/openflow_test.go, test/integration/agent/route_test.go
Add NetworkConfig struct to group user provided network configuration
parameters - trafficEncapMode, tunnelType, enableIPSecTunnel,
ipsecPSK.
Move node_config.go from pkg/agent/types/ to pkg/agent/config/.
=> Group network configuration parameters to struct NetworkConfig

cmd/antrea-agent/agent.go, cmd/antrea-controller/controller.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/controller/networkpolicy/networkpolicy_controller.go
NetworkPolicyController (of antrea-controller) is the only writer of the
antrea network policy storages and it will keep re-enqueuing failed
items until they succeed, so there's no need to have the informers
trigger all items resync, which could introduce considerable workload in
scale cluster. This patch removes it and updates the default
resyncPeriod of informer factory to 12 hours.
NodeRouterController doesn't have heavy workload and its periodical
resync could potentially fix the routes which might be broken by
external so keep it as is.
Fixes #278
=> Remove unnecessary periodical resync

pkg/controller/networkpolicy/networkpolicy_controller.go
There were M * N logs to show whether a Pod matches a NetworkPolicy if
there are M Pods and N NetworkPolicies in the cluster, which generates
log spam and hard to filter useful information in a scale cluster. This
patch changes to log matched item only.
Similarly, AddressGroup and AppliedGroups may have thousands of members,
dumping all of them in one line makes log hard to read. This patch logs
the count of members and span nodes instead.
Besides, this patch unifies the log style.
Fixes #279
=> Reduce network policy calculation log

build/images/ovs/Dockerfile, build/images/ovs/apply-patches.sh, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go
* Preserve OVS datapath flows after an agent restart
Without this patch, when the antrea-ovs container exits gracefully
(e.g. as part of a RollingUpdate for the DaemonSet), datapath flows are
deleted, which breaks existing connections. It takes 10 seconds for
exiting connections to start working again. A recent OVS patch changed
the default behavior of ovs-vswitchd so that datapath flows are no
longer deleted on exit. Because this patch is not yet available in any
released OVS version (and won't be for > 6 months), we apply it manually
when we build our base OVS Docker image.
This is a step towards non-disruptive upgrade. However, there are other
factors in play: 1) when the OVS daemons are stopped, the VXLAN device
(vxlan_sys_4789) goes away, which impacts connectivity between Nodes,
and …
=> Preserve OVS datapath flows after an agent restart

pkg/antctl/antctl.go, pkg/antctl/handlers/agentinfo.go, pkg/antctl/handlers/agentinfo_test.go, pkg/monitor/monitor.go, pkg/monitor/querier.go, pkg/monitor/testing/mock_monitor.go
Issue #275 
Output should be like this:
```
{
"metadata": {
"name": "antrea-k8s",
"selfLink": "/apis/clusterinformation.antrea.tanzu.vmware.com/v1beta1/antreaagentinfos/",
"uid": "11111111",
"resourceVersion": "11111111",
"generation": 36,
"creationTimestamp": "2020-02-04T10:50:20Z"
},
"version": "v0.3.0-dev-4452e66.dirty",
"podRef": {
"kind": "Pod",
"namespace": "kube-system",
"name": "antrea-agent-0"
},
"nodeRef": {
"kind": "Node",
"name": "node-k8s1-1"
},
"nodeSubnet": [
"192.168.1.0/24"
],
"ovsInfo": {
"version": "1.0",
"bridgeName": "br-int",
"flowTable": {
"0": 5,
"10": 7,
}
},
"networkPolicyControllerInfo": {},
"localPodNum": 2,
"agentConditions": [
{
"type": "AgentHealthy",
"status": "True",
"lastHeartbeatTime": "2020-02-04T11:25:20Z"
},
]
}
```
=> Implement antctl agent-info

pkg/agent/agent.go, pkg/agent/cniserver/server_test.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/route/route.go, pkg/agent/util/net_unix.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
This patch keeps required link info of gateway device in-memory to avoid
duplicate queries.
=> Avoid duplicate netlink queries

go.mod, go.sum, pkg/ovs/ovsconfig/default.go, pkg/ovs/ovsconfig/default_windows.go, pkg/ovs/ovsconfig/ovs_client.go, test/integration/ovs/address.go, test/integration/ovs/address_windows.go, test/integration/ovs/ovs_client_test.go
On windows platform, ovsdb-server listens on a named pipe by default.
This patch change the connection to ovsdb-server from UDS to named
pipe on windows.
=> [Windows]Connect to ovsdb-server using named pipe

ci/jenkins/README.md, ci/jenkins/jobs/projects.yaml, ci/run-k8s-e2e-tests.sh, ci/verify-sonobuoy.sh
* Add sonobuoy wrapper script to run Antrea K8s community tests
The wrapper script provides a convenient way to run the subset of K8s
community tests which are relevant to Antrea. The tests are the same as
the ones we use for CI (and maybe the Jenkins jobs could use this script
to run the tests, in order to avoid duplication?).
At the moment the script requires a working cluster, but we can provide
yet-another-script (or extend ci/kind/test-e2e-kind.sh) to take care of
1) creating an appropriate Kind cluster, and
2) running the community tests.
At the moment the script does not support running a locally-modified
version of the upstream tests, but this is something we should
investigate and consider adding in the future.
* Update README for Jenkins CI tests
The document was not updated …
=> Add sonobuoy wrapper script to run Antrea K8s community tests

cmd/antrea-agent/options.go, docs/architecture.md, pkg/agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
Check and update tun0 tunnel type after Agent starts
If the configured tunnel type changed, Agent will remove the existing
tunnel port, and create a new one with the new type.
closes #421 
Deduct ESP header size from interface MTU when IPsec is enabled
closes #417 
Add classification flow for IPsec tunnel ports
Since packets from a remote Node are still input from the Node's IPsec tunnel port, a tunnel classification flow should be added for each IPsec tunnel port; otherwise the packets will be dropped.
closes #422
=> Fix IPsec tunnel issues

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/controller/types/networkpolicy.go
Avoid repetitive conversion of LabelSelectors to Selector struct by changing the type for GroupSelector.Selector from *metav1.LabelSelector to labels.Selector.
=> Use labels.Selector in GroupSelector

ci/cluster-api/vsphere/templates/cluster.yaml, ci/cluster-api/vsphere/templates/controlplane.yaml, ci/cluster-api/vsphere/templates/machinedeployment.yaml, ci/cluster-api/vsphere/templates/namespace.yaml, ci/jenkins/ssh-config
Issue #253 
* templates files for creating workload cluster
* ssh-config template
When the ci jenkins is moved to cloud, these template files will be used for jenkins job setup.
=> Add template files for jenkins on cloud

.github/workflows/update_ovs_image.yml, build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/apply-patches.sh, build/images/ovs/build_and_push.sh, test/e2e/connectivity_test.go
* Use OVS 2.13.0
OVS 2.13 was released in February 2020. Compared to 2.11.1 (which is the
version currently in-use by Antrea), it comes with improvements to the
userspace datapath which are useful for Kind testing.
Fixes #404 
* Add TestPingLargeMTU
Before OVS 2.12.0, the conntrack implementation of the OVS userspace
datapath did not support v4/v6 fragmentation. Now that we are using OVS
2.13.0, fragmented packets are handled correctly, which is verified by
this new TestPingLargeMTU e2e test (the test used to fail when running
Antrea on a Kind cluster).
Fixes #348
=> Update OVS to 2.13.0

ci/jenkins/README.md, ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml
Issue #253 
* Implement jobs for jenkins on vmc, so the jenkins logs can be exposed to the public
* Use default value for credentials and network config
* Add job-updater, which will update jenkins jobs when code under
ci/jenkins/jobs change
* Update README file with changes
=> Update jenkins jobs for Antrea CI on VMC

go.mod, go.sum, test/integration/ovs/ofctrl_test.go
Add a context in OFSwitch instance, which is used to cancel the OpenFlow
message when the Switch is disconnected. Add timeout in both functions to
send OpenFlow message and wait for bundle reply. The implemention is in
ofnet, bump up version to leverage the fix.
Add integration test to simulate OVS restart case: remove the bridge, and
then add a new bridge with the same name.
Fixes #442
=> Cancel OpenFlow message and return error when OVS is disconnected

.github/workflows/kind.yml
To avoid having to re-build the image every time. This reduces the
amount of compute resources we use and may help with job completion
time.
=> Share Antrea Docker image between Kind e2e tests

Makefile
If 2 builds are running at the same time with latest tag first and version tag later, there may be race condition. So to avoid this, reverse their order.
=> Tag antrea image with version tag first

hack/netpol/README.md, hack/netpol/install.yml, hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/k8s_util.go
Update README with correct role and set kube-system namespace in kubectl commands
wherever necessary. Additionally, address leftover comments.
=> Update README and install yaml for netpol

hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/k8s_util.go
It seems that checking that all the Deployment Pods are in the Running phase is
not enough. The Github CI sometimes fails on the first probe (x/a -> x/a in the
DefaultDeny test) because of this.
Fixes #472
=> [Netpol] Ensure that all HTTP servers are ready before starting tests

hack/netpol/pkg/main/main.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server_test.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, test/e2e/basic_test.go, test/e2e/framework.go, test/e2e/providers/remote.go
Fixed reported issues for add/subtract by 1, error formatting and improper casing:
- Add / Subtract by 1 are replaced with increment and decrement respectively
- Changed a single usage of errors.New(fmt.Sprintf(...)) to `fmt.Errorf(...)`
- Changed variable names containing "Ip" and "Id" to have them in upper case
**Add / Sybtract by 1:**
1. hack/netpol/pkg/main/main.go:192:4: should replace failCount += 1 with failCount++
2. pkg/agent/cniserver/pod_configuration.go:152:6: should replace count += 1 with count++
3. pkg/agent/openflow/network_policy.go:824:3: should replace nClause += 1 with nClause++
4. pkg/agent/openflow/network_policy.go:828:3: should replace nClause += 1 with nClause++
5. pkg/agent/openflow/network_policy.go:832:3: should replace nClause += 1 with nClause++
6. …
=> Fixed a few issues reported by "golint"

ci/jenkins/jobs/macros.yaml
Recent ones must be excluded because they might be being used in other
builds running simultaneously.
Fixes #481
=> Exclude recent intermediate images when doing cleanup

go.mod, go.sum, test/integration/ovs/ofctrl_test.go
Use the max retry times in function `OFBridge.Connect`to avoid Agent
initialization is blocking because OVS is not connected. After the
connection is lost, OFClient retry to connect the OVS Bridge until
the new connection is setup, or the OFBridge is deleted.
The fix code is in ofnet, this change is to consume that fix.
Add a test case to check OVS could be re-connected even if it costs more
time to start than the max delay configured in the `Connect` function.
Fixes #475
=> Always retry to connect the OVS bridge in OpenFlow client after a disconnection

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml
* remove duplicated "white_list" in project.yaml
* move "ctr image tag" after "ctr image import" #491 491
* jenkins-job-validator runs on "antrea-e2e-testbed"
* disable concurrent build for a project
* remove "Throttle Concurrent Builds" restrict
=> Antrea Jenkins CI bugfix: ctr command and concurrenct build

hack/netpol/README.md, hack/netpol/images/netpol-test/Dockerfile, hack/netpol/images/netpol-test/README.md, hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/k8s_util.go, hack/netpol/pkg/utils/reachability.go, hack/netpol/test-kind.sh
This speeds up the time required to run the tests considerably (from 9
minutes to less than 4 minutes). We currently create a goroutine for
each probe, but that may become an issue if the reachability matrix
becomes too large.
We also update the netpol-test image to use ncat (from the nmap
package) instead of the Python SimpleHTTPServer. The Python server
cannot handle concurrent connections which caused the tests to be
flaky. By using ncat, we also make it possible to write network policy
tests for the SCTP protocol.
Fixes #487
=> [Netpol] Use parallel probes to verify reachability matrix

pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, test/integration/ovs/ofctrl_test.go
Expand Antrea Openflow control interface to support NAT/SNAT/DNAT functions
in conntrack.
=> Support NAT functions in Antrea

ci/jenkins/jobs/macros.yaml
The image prune operation cannot be executed in parallel. It could fail
when another build is doing it and terminate the build, ignore the
failure as dangling images will be cleaned up by another build or
following builds anyway.
=> Ignore image prune operation error

cmd/antrea-agent/agent.go, go.mod, go.sum, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/util/net_windows.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
1. Use linux and windows as suffix for OS specific functions under pkg/agent/cniserver.
2. Use OVS internal port for Pod vNIC on Windows, while using OVS port on Linux.
3. HNSEndpoint is created and attached on a Windows container to work as the vNIC.
4. kubelet calls CNI Add for both the sandbox and workload container. Only one
HNSEndpoint is created for the containers in the same Pod, and attached on all
the containers in the same Pod.
5. GARP is not needed to be sent explicitly on Windows, which could be send out by
the system automatically after an IP address is added on the network Interface.
=> [Windows] Implement Pod configuration on Windows with HNS Endpoint

cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/default.go, pkg/ovs/openflow/default_windows.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/ovsconfig/default.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/ovsconfig_test.go, test/integration/agent/openflow_test.go, test/integration/ovs/address.go, test/integration/ovs/address_windows.go, test/integration/ovs/ofctrl_test.go, test/integration/ovs/openflow_test_utils.go
On windows platform, ovs bridge listens on a named pipe for OF connection
by default. This patch:
- Change the connection to ovs from UDS to named pipe on windows.
- Add "ovsRunDir" param in config file to specify the OVS runtime dir.
=> [Windows] Connect to ovs bridge using named pipe

ci/jenkins/jobs/macros.yaml
Due to CAPV issue [1], if Cluster and VSphereCluster are deleted before
Machines, the Machines cannot be deleted. In this patch the Jenkins job
firstly deletes Machines and waits for them to disappear, then it deletes
VSphereCluster and Cluster. This deletion order is the reverse order of
the resource creation. It should minimize the chance of Cluster API
resources getting stuck in deleting state.
[1] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/761
=> CI: Wait for Machines to be Actually Deleted in Cleanup Job (#485)

docs/kind.md, test/e2e/connectivity_test.go, test/e2e/framework.go, test/e2e/providers/kind.go
We make the test framework more robust by:
* scheduling CoreDNS Pods on the Kind control-plane Node to avoid
connectivity issues to CoreDNS when restarting the Antrea Agent on
the Kind worker Node.
* ensuring that all CoreDNS Pods are restarted (on every type of
cluster, not just Kind) when all Antrea Agents are restarted
(e.g. because of an update).
Fixes #244
=> Re-enable TestPodConnectivityAfterAntreaRestart on Kind

.github/workflows/go.yml, CONTRIBUTING.md, Makefile, ci/README.md, hack/netpol/.golangci.yml, hack/netpol/Makefile, hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/networkpolicyspecbuilder.go, hack/netpol/pkg/utils/utils_test.go
We also remove the `test-fmt` target since it has been replaced by
`golangci`. It is still possible to use `make fmt` to apply `gofmt`
changes on the entire code base.
Because `golangci-lint` can only be used in the scope of a single module
(apparently), we need a separate `golangci` make target in
hack/netpol. This is probably better anyway as it helps keep the Antrea
core code and the netpol code separate, which is why they are different
modules in the first place.
=> Run linters on netpol Go code as part of CI

docs/getting-started.md
Add a note to requirements regarding the necessity of cluster-cidr flag while starting kube-proxy
during installation.
=> Add note regarding kube-proxy cluster-cidr flag

pkg/antctl/client.go, pkg/antctl/command_list.go, pkg/antctl/command_message.go, pkg/antctl/command_message_test.go
issue #506 
Turn error message into a more friendly one:
Error: NotFound: resource "resouce name" not found
=> Refactor antctl error message

docs/kind.md
Move the short cut section to the top since most users are more interested in getting a cluster up
and running quick.
=> Update Kind cluster setup doc

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml
Starting with K8s 1.18, beta.kubernetes.io/os is removed.
kubernetes.io/os is supported from K8s 1.14.
Fixes #361
=> Update beta.kubernetes.io/os to kubernetes.io/os

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml
antctl uses controller ServiceAccount token to authenticate with
controller API when running inside the Antrea controller Pod. This
commit adds the antctl role to the Controller ServiceAccount, so
antctl has all permissions to call the controller APIs for the
controller commands.
=> Add antctl role to Controller to allow antctl to run in Controller Pod

build/yamls/antrea-eks.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml
The PR adding the antrea-eks.yml manifest was merged without being
rebased first, so the new ServiceAccount used by antctl was omitted from
it.
This commit also fixes a typo in the ServiceAccount's name.
The PR adding the new ServiceAccount was merged before the PR adding the
antrea-eks.yml manifest
=> Fix Antrea EKS manifest

build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml, build/yamls/base/controller.yml, cmd/antrea-controller/controller.go, hack/update-codegen-dockerized.sh, pkg/agent/apiserver/handlers/agentinfo/handler.go, pkg/antctl/antctl.go, pkg/antctl/transform/controllerinfo/transform.go, pkg/apis/networking/v1beta1/register.go, pkg/apis/system/doc.go, pkg/apis/system/install/install.go, pkg/apis/system/v1beta1/doc.go, pkg/apis/system/v1beta1/register.go, pkg/apiserver/apiserver.go, pkg/apiserver/openapi/zz_generated.openapi.go, pkg/apiserver/registry/system/controllerinfo/rest.go, pkg/monitor/monitor.go, pkg/monitor/querier.go, pkg/monitor/testing/mock_monitor.go
Add "system" API group for APIs of exposing Antrea system information.
Add "controllerinfos" resource to the "system" API group, which
returns AntreaControllerInfo (reusing AntreaControllerInfo CRD
struct).
Add "get controller-info" antctl command that queries the
"controllerinfos" resource and prints it out.
Change "agent-info" command to "get agent-info".
Change Controller's "version" command to get AntreaControllerInfo from
the "system" API group (not from the AntreaControllerInfo CRD).
Sample output:
antctl get controller-info
{
"version": "v0.5.0-dev-0c6f1ed",
"podRef": {
"kind": "Pod",
"namespace": "kube-system",
"name": "antrea-controller-55b9bcd59f-h9ll4"
},
"nodeRef": {
"kind": "Node",
"name": "k8s2"
},
"serviceRef": {
"kind": "Service",
"name": "antrea"
}, …
=> Add Controller "system" API group and controller-info antctl command

ci/kind/kind-setup.sh, test/e2e/providers/exec/docker.go, test/e2e/providers/kind.go
For e2e tests, kind provider only supports only the default master node name ("kind-control-plane").
Fixed to run the e2e tests for any master node name, which was created from user given cluster name.
In addition, https://github.com/vmware-tanzu/antrea/blob/master/ci/kind/kind-setup.sh accepts any type of a cluster name. We should probably restrict naming convention to rfc1035/rfc1123. Otherwise, we do not align with kubernetes naming convention and following command breaks.
go test -v github.com/vmware-tanzu/antrea/test/e2e -provider=kind
Testing: Tested with cluster names such as stati_kind, statiKind, stati-kind, stati-kind01 etc.
=> Support kind provider e2e tests with arbitrary cluster name:

docs/antctl.md, docs/getting-started.md, docs/troubleshooting.md
Add a new document under docs/ with information on how to install
(instructions valid starting with release 0.5.0) and use antctl. This is
user-facing documentation and does not include information about the
antctl implementation.
We also do not include a detailed list of commands at the moment. This
list can come later if needed (can be hard to keep up-to-date), and we
can keep adding information about specific commands in
troubleshooting.md for specific debugging scenarios.
Fixes #337
=> Start documentation for antctl

.github/workflows/kind-upgrade.yml, ci/kind/test-upgrade-antrea.sh, test/e2e/basic_test.go, test/e2e/connectivity_test.go, test/e2e/framework.go, test/e2e/upgrade_test.go
The new Go test (TestUpgrade) is meant to be run through the wrapper
script ./ci/kind/test-upgrade-antrea.sh.
At the moment we test upgrade from versions 0.3.0, 0.4.0 and 0.4.1 as
part of CI, but we can modify that set as we go through Antrea
releases. We also run the test for every PR against master, which may be
a bit excessive.
Fixes #511
=> Add e2e test for upgrade scenario

pkg/agent/apiserver/handlers/agentinfo/handler.go, pkg/agent/apiserver/handlers/podinterface/handler.go, pkg/antctl/antctl.go
For example: controller-info -> controllerinfo, network-policy ->
networkpolicy, applied-to-group -> appliedtogroup.
=> Change antctl commands to follow K8s resource naming convention

pkg/apiserver/storage/interfaces.go, pkg/apiserver/storage/ram/store.go, pkg/apiserver/storage/ram/store_test.go, pkg/apiserver/storage/ram/watch.go, pkg/apiserver/storage/ram/watch_test.go, pkg/controller/networkpolicy/store/addressgroup.go, pkg/controller/networkpolicy/store/appliedtogroup.go, pkg/controller/networkpolicy/store/networkpolicy.go, pkg/controller/networkpolicy/store/util.go, pkg/controller/types/networkpolicy.go
It's observed in scale tests that antrea-controller had memory usage
peak when agents were connecting to it, which is quite greater than the
usage after agents connected it. For example, in a scale of 100k Pods,
75k NetworkPolicies, 25k Namespaces, 1k antrea-agents, it would consume
8~9GB memory at peak and lead to OOM sometimes while it only consumed
1.3GB memory when there were no agents connection and 1.5GB after 1k
Nodes connected it.
The memory should be consumed by a process in store.Watch where it lists
all items (pointers) of a kind of resource, converts them to
InternalEvent, sends them to watchers to further process. This means
that every object will be converted once regardless of whether the
watcher is interested in it or not, while the conversion is an expensive
operation in …
=> Check whether an object matches the watcher before generating init event

ci/kind/test-upgrade-antrea.sh
There seems to be some rate limiting which creates issues when running
an unauthenticated request as part of a Github workflow.
https://developer.github.com/v3/#rate-limiting
Furthermore, using "grep -q" with "curl" sometimes lead to the "(23)
Failed writing body" error being displayed when grep closes the pipe
early. Not sure exactly why since we run curl in silent mode, but I have
seen it in the workflow logs.
https://github.com/vmware-tanzu/antrea/runs/532409948
=> Do not use Github API to check tag

pkg/apis/networking/v1beta1/register.go
It leads to `antctl get appliedtogroup` failing.
=> Fix typo in register

pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/transform/addressgroup/transform.go, pkg/antctl/transform/appliedtogroup/transform.go, pkg/antctl/transform/common/transform.go, pkg/antctl/transform/networkpolicy/transform.go
Reformat the table output for antctl get commands.
1. Reorder the headers of the output.
2. Set a maximum length for all elements in tables with a const variable maxTableOutputColumnLength. If one line is not enough, then generate a summary.
3. Beautify the names of pods along with other fields.
4. Make table headers capitalized and meaningful.
Before:
```shell
name                                 rules                                                                                                                                        appliedToGroups
c4c59cfe-9160-5de5-a85b-01a58d11963e [{"direction":"In","from":{"addressGroups":["32ef631b-6817-5a18-86eb-93f4abf0467c"]},"services":[{"port":"http","protocol":"TCP"}],"to":{}}] ["c4c59cfe-9160-5de5-a85b-01a58d11963e"]
name …
```
=> Add table output formats for antctl get commands

Makefile, build/yamls/antrea-gke-node-init.yml, build/yamls/antrea-gke.yml, build/yamls/patches/gke/cniPath.yml, docs/getting-started.md, docs/gke-installation.md, hack/generate-manifest.sh
Antrea can be enabled as a CNI operating in noEncap mode
and enforcing Network Policies in GKE cluster.
This checkin enables the support. Also added details regarding
deploying and configuring antrea in GKE cluster
=> Enable Antrea in GKE cluster for Ubuntu host

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml
* disable cleanup-job's concurrency
* save capv/capi log when get-secret fails
* remove unnecessary cleanup antrea before build, since workload clusters are new.
=> CI update on cleanup-job and log saving

pkg/antctl/antctl.go, pkg/antctl/command_definition.go
Fixed #547 
Added field: aliases in commandDefinition. All commands can have aliases now.
e.g.
antctl get networkpolicy
antctl get networkpolicies
antctl get netpol
All 3 commands above return same result.
```
Print network policies in agent
Args:
name  Retrieve resource by name
Usage:
antctl get networkpolicy [name] [flags]
Aliases:
networkpolicy, networkpolicies, netpol
Examples:
Get a networkpolicy
$ antctl get networkpolicy [name]
Get the list of networkpolicy
$ antctl get networkpolicy
Flags:
-h, --help            help for networkpolicy
-o, --output string   output format: json|yaml|table (default "json")
Global Flags:
-k, --kubeconfig string   absolute path to the kubeconfig file (default "/root/.kube/config")
-t, --timeout duration    time limit of the execution of the command
-v, …
```
=> Implemented plural and short names for antctl

pkg/antctl/client.go
Return an error when failed to load in-cluster config, when kubeconfig
file is not specified, and the default path does not exist.
Segment fault is like the following:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1243750]
goroutine 1 [running]:
github.com/vmware-tanzu/antrea/pkg/antctl.(*client).resolveKubeconfig(0xc000098a80, 0xc000559c80, 0x15, 0x76, 0x0)
/home/shenj/github/antrea/pkg/antctl/client.go:68 +0x120
github.com/vmware-tanzu/antrea/pkg/antctl.(*client).resourceRequest(0xc000098a80, 0x2114ae0, 0xc000559c80, 0x1443cc0, 0x214d3a0, 0x0, 0x0)
/home/shenj/github/antrea/pkg/antctl/client.go:118 +0x50
github.com/vmware-tanzu/antrea/pkg/antctl.(*client).request(0xc000098a80, 0xc000559c80, 0x7, …
=> Fix antctl segment fault when kubeconfig cannot be resolved

hack/boilerplate/license_header.go.txt, hack/boilerplate/license_header.raw.txt, hack/update-codegen-dockerized.sh
Generated mock code are still using 2019.
Use YEAR to replace 2019 in header templates: license_header.raw.txt and
license_header.go.txt.
Command mockgen does not automatically replace variable YEAR with current year
like others do, e.g. client-gen.
Added check in update-codegen-dockerized.sh: reset file change if it is
introduced by year change.
1. filter changed files by 1 added line and 1 deleted line
2. check if diff result contains "Copyright YEAR Antrea Authors" line
3. reset the file if #2 returns true
=> Templates in hack/boilerplate: 2019 -> 2020

pkg/agent/apiserver/handlers/agentinfo/handler.go, pkg/agent/apiserver/handlers/podinterface/handler.go, pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/transform/addressgroup/transform.go, pkg/antctl/transform/appliedtogroup/transform.go, pkg/antctl/transform/common/transform.go, pkg/antctl/transform/controllerinfo/transform.go, pkg/antctl/transform/networkpolicy/transform.go
- Set table output as the default output for  commands
- Apply the table output format to `antctl get podinterface`, `antctl get controllerinfo`, `antctl get agentinfo` commands
This is a follow-up of #477 .
FIxes #541 
Before:
```shell
$ antctl get podinterface
{
"name": "nginx-6db489d4b7-vgv7v",
"InterfaceName": "patch-de-17bf25",
"IP": "192.168.2.7",
"MAC": "36:44:77:45:ee:55",
"PortUUID": "e2bc4318-5cda-4be9-ab61-8ff748db7320",
"OFPort": 80,
"ContainerID": "58e4aba280fe1696a647aa0f928071a3bfb25a9da21937dcdc05200fce39ca20",
"PodNamespace": "default"
}
$ antctl get controllerinfo
{
"version": "v0.4.0", 
"podRef": {
"kind": "Pod", 
"namespace": "kube-system", 
"name": "antrea-controller-55b9bcd59f-h9ll4"
}, 
"nodeRef": {
"kind": "Node", 
"name": "node-master"
}, 
"serviceRef": {
"kind": …
```
=> Set table output as the default output for  commands

hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/k8s_util.go
Because the same Pods are re-used to validate NetworkPolicy
implementation, there is virtually no delay between successive
tests. This means that Antrea does not always have time to properly
clean-up stale NetworkPolicies and a test can fail because of the
NetworkPolicy from the previous test. By adding a short delay (2s) every
time we update or delete a NetworkPolicy, we can bypass the issue. This
change only increases testing time by < 20% (3min -> 3min30).
This commit also changes the verbosity of some log messages to "TRACE"
to make the logs easier to navigate.
Fixes #544
=> [Netpol] Sleep between successive tests

Makefile
Tested by checking equality of sha256sum between `go build` and `go install`.
Fixes #570.
=> Add cross-compile support to `make bin`

go.mod, go.sum, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/ofctrl_group.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go, test/integration/ovs/openflow_test_utils.go
- Implemented group&bucket control interface
- Made Flow and Group interfaces as Entry
- Updated Ofnet and libopenflow deps to support group message
- Changed type alias in interfaces.go to type declaration
- Implemented multiple resubmit action
- Updated mocks
TODO: @wenyingd will base on this commit to implement group installation by bundle
=> Implement group-bucket control interface

pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, test/e2e/networkpolicy_test.go
For egress policy, if there are no "ToAddresses" and "IPBlocks", there
were no PolicyRules created, which caused the Pods not being isolated.
We must ensure there is at least one PolicyRule, this patch creates a
PolicyRule with the original services if it doesn't exist. If there are
IPBlocks or Pods that cannot resolve any named port, they will share
this PolicyRule.
The upstream test has only deny-all ingress case but not egress one,
a deny-all egress test is added to antrea e2e test.
Fixes #574
=> Fix deny-all egress NetworkPolicy case

go.mod, go.sum, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/controller/networkpolicy/store/addressgroup.go, pkg/controller/networkpolicy/store/appliedtogroup.go
In a scale of 25k Namespaces, 100k Pods, 75k NetworkPolicies, It took ~20 minutes to finish the initial computation, which could leave the cluster in a degraded state for a long time once antrea-controller is restarted.
It's profiled that the bottleneck is the Pod event handlers: addPod. For instance, in the above scale, addNetworkPolicy can finish all tasks in 9.42s, addNamespace can finish in 910ms, but addPod needs 17min. So it is actually addPod keeping producing new tasks for the workers to process. It's slow because addPod listed all AddressGroups and AppliedToGroups and checked whether they could be affected by this pod, leading to O(N * M) time complexity, where N is number of pods, M is number of groups. Further more, as multiple Pods can affect same AddressGroups or …
=> Improve antrea-controller NetworkPolicy computation performance

pkg/ovs/ovsconfig/ovs_client.go
Doing this without checking if datapath_type is different from datapath
type in given manifest like openflow protocol.
Tested by deleting antrea (with system datapath type) and redeploying
antrea with new manifest file that has netdev datapath type and added
changes to deploy tun device driver.
Antrea agent comes up with new datapath type with out any issues.
Changed to system datapath type again.
Fixes #152
=> Update datapath type if bridge br-int exists

hack/update-codegen-dockerized.sh
Such detailed output is unnecessary. Just tell if this file is reset or not is enough.
e.g.
```
+ read file
++ git diff pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
+ [[ diff --git a/pkg/ovs/ovsconfig/testing/mock_ovsconfig.go b/pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
index cd52701..588e471 100644
--- a/pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
+++ b/pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
@@ -1,4 +1,4 @@
-// Copyright 2019 Antrea Authors
+// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. == *\-\/\/\ \C\o\p\y\r\i\g\h\t\ *\ \A\n\t\r\e\a\ \A\u\t\h\o\r\s* ]]
+ git checkout HEAD -- pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
+ echo '=== …
```
=> Hide output when resetting changes introduced by YEAR

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
According to the K8s documentation, DeletedFinalStateUnknown is used
when an object was deleted but the watch deletion event was missed. In
my testing, I have observed this situation with Antrea running in Kind,
when the Antrea Controller loses connectivity to the K8s apiserver
because the Agent running on the same Node is restarted.
The code is adapted from the K8s sample controller and from K8s control
plane controllers.
Fixes #579
=> Handle DeletedFinalStateUnknown in NetworkPolicy Controller

docs/manual-installation.md
While manual run of antrea components, explicitly mention the steps to build the binaries.
=> Explicitly mention the build steps

pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/route/route_windows.go
Windows doesn't support policy-only mode. To be compatible with Linux and avoid compilation issue, add empty implementations on Windows for Interface "interfaceConfigurator" and "route.Client".
=> [Windows] Fix Interface conflict in Linux and Windows

ci/jenkins/jobs/macros.yaml
kubectl rollout may get stuck in failure if can not rollout successfully.
This patch add 5 minutes timeout for the operation to make sure CI won't
be blocked by it.
=> CI: Add timeout for kubectl rollout (#584)

README.md
Taking into account the results of http://www.polljunkie.com/poll/tzmyzz/antrea-meeting-planning/view we will keep a single meeting for all time zones, but switch from 4PM GMT to 4AM GMT. We plan to keep this rotation going for a few month at least - or until the community asks us for a different meeting time!
=> Update community meeting schedule

hack/release/prepare-assets.sh
The wrong Docker image was used because the IMG_NAME environment
variable was not set properly before generating the manifest.
Fixes #607
=> Fix prepare-assets.sh script for antrea-octant.yml

.github/workflows/go.yml, Makefile
- Compile following packages for windows:
  - antrea-cni
  - antrea-agent
- Add compile windows binaries job in Github action
=> Add windows binaries compiling job to Github action

pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/command_message.go, pkg/antctl/command_message_test.go, pkg/antctl/transform/networkpolicy/transform.go, pkg/apiserver/registry/networkpolicy/networkpolicy/rest.go
- Add "NAMESPACE" field for `antctl get networkpolicy` command
- Stop using networkpolicy UID as the element of the 'NAME' column and make this column consistent
- Update the sorting order of table output for all `antctl get` commands: Sort the table rows according to columns in order (1st col, 2nd col, 3rd col, .....).
- Add support for filtering network policies using namespace/name (When only name is specified, the namespace is set to `default` by default)
Some examples of the command:
```shell
Examples:
Get a network policy
$ antctl get netpol/networkpolicy/networkpolicies pod1 -n ns1
Get the list of network policies in a namespace
$ antctl get netpol/networkpolicy/networkpolicies -n ns1
Get the a network policy in default namespace
$ antctl get netpol/networkpolicy/networkpolicies …
```
=> Update fields for `antctl get networkpolicy` command

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/base/conf/antrea-controller.conf, build/yamls/base/controller.yml, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go, docs/configuration.md, docs/troubleshooting.md, pkg/agent/apiserver/apiserver.go, pkg/antctl/client.go, pkg/antctl/command_definition.go, pkg/antctl/command_list.go, pkg/apis/ports.go
* Use unpopular ports as antrea components' default ports
* Support overriding the ports via config files
* Support overriding the server address via "-s" for antctl
Fixes #365
=> Support configurable apiserver ports

cmd/antrea-agent/config.go, pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go, pkg/agent/openflow/cookie/allocator.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route_windows.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/agent/openflow_test.go
Use OpenFlow to implement SNAT feature on Windows, and masqurade the container IP with the NodeIP.
=> [Windows] Enable Windows Pod to access external addresses

pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/openflow/client.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/querier/querier.go, pkg/agent/querier/testing/mock_querier.go, pkg/antctl/antctl.go, pkg/ovs/ofctl/ofctl.go, pkg/ovs/openflow/ofctrl_flow.go, test/integration/agent/openflow_test.go, test/integration/ovs/ofctrl_test.go, test/integration/ovs/openflow_test_utils.go
Add agent API with path /ovsflows to return OVS flows.
Add antctl command to dump OVS flows retrieved from /ovsflows.
For now we support only dumping all flows and dumping flows of a
specified Pod. Later we will support dumping flows of a NetworkPolicy,
a remote Node, a Service, etc.
In the current implementation,  agent dumps OVS flows by executing
"ovs-ofctl dump-flows". In future we should extend openflow.Flow to
support converting a flow to a readable string directly, and we should
check or track whether a flow is realized in OVS using an more
efficient way. Then we no more need to use ovs-ofctl to dump flows.
Example outputs:
antctl get of -p coredns-xyz -n kube-system
FLOW …
=> Add agent API and antctl command to dump OVS flows

pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/apiserver/handlers/podinterface/handler.go, pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/transform/addressgroup/transform.go, pkg/antctl/transform/appliedtogroup/transform.go, pkg/antctl/transform/common/transform.go, pkg/antctl/transform/rule/transform.go, pkg/antctl/transform/version/transform.go
- Made YAML output generated by JSON output
- Removed un-needed YAML annotations
=> Use json output annotations for yaml in antctl

ci/jenkins/jobs/macros.yaml
Remove old images in CI.
* old job images will be deleted by new job.
`docker rmi` cannot delete old images like "antrea-e2e-for-pull-request-99" because `image is referenced in multiple repositories`. Builds triggered by same PR share the same image ID.
To delete these images, `--force` is needed but it may also delete images of other current builds like those triggered by `test-all`.
Since one job isn't allowed to have concurrent builds, it is safe to force delete old images of this kind of job with filter "$JOB_NAME".
=> Prune unused antrea-ubuntu images

.github/workflows/kind-upgrade.yml, .github/workflows/kind.yml
A recent update to the Github VM images has caused our Kind tests to
fail because of a pretty significant reduction in the amount of disk
space available.
Many users have reported the issue to Github:
https://github.com/actions/virtual-environments/issues/709
The recommended workaround is to run "apt-get clean" which should free
up a significant amount of space. In our case, most of the disk usage
comes from docker images and containers, and we don't have an easy way
to use the /dev/sdb1 partition (guaranteed 14GB).
According to the Github team, they have started a rollback to the old
images, but it makes sense for us to merge this workaround anyway, to
avoid disruptions in the immediate future and to potentially have more
disk space available, should we need it later.
Fixes #635
=> Free disk space in some workflows with "apt-get clean"

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/antctl.yml, pkg/agent/apiserver/apiserver.go
Antrea agent uses apiserver to interact with antctl. However, unlike the
controller, the API endpoint is exposed only locally which limits antctl
to local execution.
Additionally, we would like to reuse the listener for Prometheus metrics,
which would require external access to the API endpoint's metrics path.
Having authentication in a similar way to the controller's implementation
could help here as it will allow external exposure of the API endpoint.
Fixes: #613
=> Apply authentication to agent apiserver endpoint

pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/antctl/client.go, pkg/antctl/command_definition.go, pkg/antctl/command_message.go, pkg/antctl/command_message_test.go
- Add clear antctl error message from k8s:
Before:
```shell
$ sudo ./bin/antctl-linux get netpol --kubeconfig /etc/kubernetes/kubelet.conf
Error: Unknown error
$ sudo ./bin/antctl-linux get netpol sdf
Error: BadRequest: Please check the args for networkpolicy
```
After:
```shell
$ sudo ./bin/antctl-linux get netpol --kubeconfig /etc/kubernetes/kubelet.conf
Error: Forbidden: networkpolicies.networking.antrea.tanzu.vmware.com is forbidden: User "system:node:k8s-master" cannot list resource "networkpolicies" in API group "networking.antrea.tanzu.vmware.com" at the cluster scope
$ sudo ./bin/antctl-linux get netpol sdf
Error: an empty namespace may not be set when a resource name is provided
```
Fixes #612
=> Add clear error message for antctl

go.mod, pkg/ovs/openflow/logs.go
logrus is used in some packages of Antrea-agent then it used different format of logging.
This introduces log formatting for logrus in compliance with k8s log.
Implementation of PR: #593
Before
```
I0327 15:52:23.347943       1 agent.go:50] Starting Antrea agent (version v0.5.0-dev-14e8160.dirty)
I0327 15:52:23.348015       1 client.go:33] No kubeconfig file was specified. Falling back to in-cluster config
I0327 15:52:23.349598       1 client.go:23] No antrea kubeconfig file was specified. Falling back to in-cluster config
I0327 15:52:23.349706       1 ovs_client.go:66] Connecting to OVSDB at address /run/openvswitch/db.sock
I0327 15:52:24.350008       1 ovs_client.go:85] Not connected yet, will try again in 2s
I0327 15:52:24.351968       1 …
```
=> Compliance to k8s log format in antrea-agent pod

pkg/agent/util/iptables/iptables.go, pkg/agent/util/iptables/lock.go, pkg/agent/util/iptables/lock_test.go
We need to acquire xtables lock explicitly for iptables-restore to
prevent it from conflicting with iptables/iptables-restore which might
being called by kube-proxy. iptables supports "--wait" option and
go-iptables has enabled it. iptables-restore doesn't support the option
until 1.6.2, but it's not widely deployed yet.
Besides, this PR logs the error instead of the command when executing
iptables-restore fails.
Fixes #632
=> Acquire xtables.lock before executing iptables-restore

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/config/node_config.go, pkg/agent/interfacestore/types.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/ovs/ovs_client_test.go
Depend on Wenyingd's PR: Enable Windows Pod to access external addresses #393
Add windows platform specific operations during OVS bridge preparation:
1. Set fixed datapath_id for OVS bridge to avoid Openflow channel interruption.
2. Add default internal port/interface when creating OVS bridge.
On windows platform OVS default inteface is used to forward host traffic.
3. Move IP/MAC from uplink interface to OVS bridge.
4. Add uplink port to OVS bridge.
5. Install Openflow entries for uplink/bridge to support host networking.
=> [Windows] Prepare ovs bridge

pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_linux.go, pkg/agent/cniserver/server_windows.go
On windows platform, DNS config is passed by runtime config of CNI request.
This PR support set DNS config from DNS specified in runtime config.
DNS Capability is needed to be set in CNI config file to enable DNS config
can be passed in runtime config.
=> [Windows] Support set DNS from runtime config in CNI request

pkg/agent/agent_windows.go
Currently the cleanup function for error handing in prepareOVSBridge() is always executed due to no error check.
This patch add error check before cleanup.
=> [Windows] Check error before clean OVS bridge and HNS network

.github/workflows/kind-upgrade.yml
Old: 0.3.0, 0.4.0, 0.4.1
New: 0.4.1, 0.5.0, 0.5.1
=> Upgrade Antrea versions used for upgrade test

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml, cmd/antrea-controller/controller.go, pkg/agent/apiserver/apiserver.go, pkg/antctl/client.go, pkg/antctl/command_runtime.go, pkg/apiserver/apiserver.go
When starting the APIServer either in a agent or the controller, we generate a token file in the Pod. The antctl which runs in Pod can use this as bearer token to bypass delegation AAA.
=> Enable API Server local access with privilegedLoopbackToken

pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/querier/querier.go, pkg/agent/querier/testing/mock_querier.go, pkg/antctl/antctl.go, pkg/ovs/ofctl/ofctl.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/querier/querier.go, test/integration/agent/openflow_test.go
Look up all cached flows of a NetworkPolicy from policyRuleConjunction
and conjMatchFlowContext. Execute ovs-ofctl dump-flows to dump the
flow strings.
Add NetworkPolicy name and Namespace to NetworkPolicyController rule
cache and policyRuleConjunction to look up a NetworkPolicy and its
flows.
Fix flow match string for TCP/UDP/SCTP port and register matches.
Look up NetworkPolicies from the NetworkPolicyController cache from:
Pod -> AppliedToGroups -> Rules -> NetworkPolicies.
Revise NetworkPolicyController NetworkPolicy lookup funcs.
antctl command to get NetworkPolicies of a Pod:
antctl get netpol -p pod -n ns.
=> Support querying OVS flows of a NetworkPolicy and NetworkPolicies applied to a Pod

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, go.mod, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/apiserver/apiserver.go, pkg/agent/metrics/prometheus.go, pkg/controller/metrics/prometheus.go, pkg/util/env/env.go, pkg/util/env/env_test.go
Integrate with Prometheus monitoring solution.
Integration of the Prometheus client into Antrea controller and agent
allows the exposure of various metrics to Prometheus server.
In addition to Antrea's own set of metrics, Prometheus client will also
expose metrics which are defined by various components which are part of
the Antrea ecosystem, e.g golang, Prometheus itself etc.
=> Antrea Prometheus integration

pkg/controller/metrics/prometheus.go, pkg/controller/networkpolicy/networkpolicy_controller.go
This CL brings metrics of antrea controller events processing, includes: syncing time, processed number, and queue length.
=> Add prometheus metrics for antrea controller

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml, build/yamls/patches/ipsec/ipsecContainer.yml
This is meant as an indication to the scheduler, to improve scheduling
of workload Pods.
It should not impact the likelihood of eviction of Antrea Pods. First,
CPU utilization does not seem to be used as an eviction signal. Second,
we already use a priorityClass of system-cluster-critical /
system-node-critical, which means that they are essentially treated as
Pods with a QoS class of Guaanteed (since K8s 1.14).
We do not define CPU limits as CPU usage can be very bursty (e.g. on
start up for antrea-agent, or if there is a burst of new flows for
antrea-ovs).
I don't think we should specify memory requests, as it is impossible to
come up with a number that would work for most use cases. This is also
not required to get a QoS class of Burstable. For example, memory
footprint should be much …
=> Add default CPU resource requests for Antrea Pods in manifests

build/images/scripts/start_ovs, build/images/scripts/start_ovs_netdev, cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/ovs/ovs_client_test.go
This patch starts ovs-vswitchd with flow-restore-wait set to true and
removes the config after restoring necessary flows for the following
reasons:
1. It prevents packets from being mishandled by ovs-vswitchd in its
default fashion, which could affect existing connections' conntrack
state and cause issues like #625.
2. It prevents ovs-vswitchd from flushing or expiring previously set
datapath flows, so existing connections can achieve 0 downtime during
OVS restart. As a result, we remove the config here after restoring
necessary flows.
Fixes #625
=> Start ovs-vswitchd with flow-restore-wait

build/yamls/antrea-prometheus.yml, docs/prometheus-integration.md
Document the interoperability of Antrea controller and agents with
Prometheus monitoring server.
Add a document describing configuration changes in Antrea and Prometheus.
Also add a sample yaml file.
=> Document Prometheus configuration with Antrea

build/yamls/antrea-prometheus.yml, docs/prometheus-integration.md
The prometheus-antrea ClusterRole was not used. All the necessary
permissions are provided by the prometheus ClusterRole.
=> Remove redundant ClusterRole in Prometheus deployment instructions

pkg/agent/metrics/prometheus.go
antrea_agent_local_pod_count has not been registered and therefore
missing from Promehteus client output.
=> Register antrea_agent_local_pod_count metric

pkg/ovs/openflow/ofctrl_builder.go
It impacts the OVS flow dumping implementation.
=> Fix udp_dst and sctp_dst in flow matching string

pkg/agent/agent.go, pkg/agent/agent_linux.go, pkg/agent/agent_windows.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/types.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go
On windows platform, local IP is need to be set on tunnel interface which is used as source IP of encap packets.
=> [WIP][Windows] Set local_IP option on tunnel interface

test/e2e/antctl_test.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/performance_test.go, test/e2e/upgrade_test.go
This CL makes `podWaitForIP` more generic, e.g. get the IP address of an antrea component.
=> Add namespace parameter to `podWaitForIP`

docs/troubleshooting.md
A bearer token is required for local access now that the API is
externally accessible (in order to expose Prometheus metrics). The
instructions to connect directly to the antrea-agent API therefore
needed to be updated.
Thanks to @srikartati for pointing out this issue to me.
=> Update troubleshooting instructions for antrea-agent API

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
The return value of `GetNetworkPolicy` is not deterministic as it
constructs rules from a map. Use `ElementsMatch` to ignore the order of
rules.
Fixes #661
=> Fix flaky unit test TestAddNetworkPolicyWithMultipleRules

docs/ovs-pipeline.md, hack/netpol/pkg/main/main.go, hack/netpol/pkg/utils/networkpolicyspecbuilder.go, hack/netpol/pkg/utils/utils_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/types/networkpolicy.go, pkg/antctl/transform/rule/transform.go, pkg/util/ip/ip.go, pkg/util/ip/ip_test.go, test/integration/agent/openflow_test.go
Behavior with network policies with overlapping From/To blocks
is not as expected. Behavior changes with order change in addition of
policies, which is not expected. This is due to priority clash between
conjunctive match flows with overlapping match fields. Fixed this by
adding match flows for only diff addresses between From/To and Except
blocks, and not adding drop flows at all.
Added new package ip to compute diff CIDRs.
Added netpol test for testing cases with policies that have overlapping from/to blocks and policies with overlapping except blocks.
Fixes: #367
=> Fix network policy overlapping issue

Makefile, build/yamls/antrea-eks.yml, build/yamls/patches/eks/eksEnv.yml, ci/test-conformance-eks.sh, hack/generate-manifest.sh, pkg/agent/route/route_linux.go, pkg/util/env/env.go
When Antrea is used to enforce NetworkPolicies in EKS, an additional
iptables rule is required in the mangle table, to ensure that return
NodePort Service traffic which was load-balanced to a Pod attached to a
secondary ENI takes the correct reverse path through eth0.
This requires communicating to the Antrea Agent that it is being run in
an EKS managed cluster, which we do through an environment variable
(ANTREA_CLOUD_EKS).
Some future improvements are possible: this rule is only necessary if
NodePort is enabled in AWS VPC CNI, and in some rare cases it may be
possible for the packet mark to differ from the default value (0x80).
This patch also improves the test-conformance-eks.sh script which was
used for testing. In particular it ensures that the script can be used
on macOS.
Fixes #678
=> Fix return path for NodePort Service traffic in EKS

pkg/agent/util/iptables/iptables.go, pkg/agent/util/iptables/lock.go
When antrea-agent ran with iptables>=1.6.2, it acquired the xtables lock
explicitly before calling iptables-restore. However, iptables-restore
will try to acquire the same lock and will fail immediately if it cannot
be acquired.
To make antrea-agent work with >=1.6.2 and <1.6.2 at the same time, this
PR detects the iptables version, uses "--wait" if it's greater than or
equal to 1.6.2, or acquire the lock explicitly.
Fixes #697
=> Fix antrea-agent not working with iptables>=1.6.2

docs/ovs-pipeline.md, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go, test/integration/ovs/ofctrl_test.go
This PR introduce goto_table instruction and is a part of PR #326.
goto_table will be used In most of pipeline.
But keep resubmit in some cases.
i.e.) Resubmit packets to a previous table or the same table in learn flows.
=> Introduce goto_table instruction 

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Add OpenFlow entry to enforce packet into OVS pipeline if it is sent out from OVS bridge and to local Pods.
=> [Windows] Fix issue: NodePort service can't be accessed from local Pod

Makefile, build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.octant.ubuntu, docs/octant-plugin-installation.md
antrea-octant-plugin can be removed from image antrea-ubuntu
and other binaries can be removed from image octant-antrea-ubuntu.
This patch adds Makefile target per binary and only includes
the necessary binaries in the docker image.
Fixes: #708
=> Remove unused binaries from image

pkg/agent/config/traffic_encap_mode_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
Expected value should come before actual value while asserting equal in unit tests. Reversed order
leads to incorrect message output on unit test failures.
=> Ensure order while asserting equal

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/apiserver/storage/interfaces.go, pkg/apiserver/storage/ram/store.go, pkg/apiserver/storage/ram/store_test.go, pkg/apiserver/storage/ram/watch.go, pkg/apiserver/storage/ram/watch_test.go, pkg/controller/networkpolicy/store/addressgroup.go, pkg/controller/networkpolicy/store/addressgroup_test.go, pkg/controller/networkpolicy/store/appliedtogroup.go, pkg/controller/networkpolicy/store/appliedtogroup_test.go, pkg/controller/networkpolicy/store/networkpolicy.go, pkg/controller/networkpolicy/store/networkpolicy_test.go, test/e2e/antctl_test.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go
We must do a full sync between the NetworkPolicy cache and the latest
objects after reconnecting to antrea-controller, otherwise stale
NetworkPolicies won't be cleaned up and will cause unexpected behavior.
This PR adds a dummy Bookmark event after initial events of a new watch
so that antrea-agent can know its end and do an atomic update to cache
which can identify stale objects.
Fixes #666
=> Clean up stale NetworkPolicies after reconnection

pkg/antctl/client.go, pkg/antctl/command_list.go
The default value of `--kubeconfig` will try to use `KUBECONFIG`first. If the value is empty, then the default value would be Kubernetes recommend path.
Fixes #720
=> Support getting kubeconfig path from KUBECONFIG env variable

go.mod, pkg/agent/cniserver/server.go, pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go, pkg/cni/client.go, pkg/cni/default_windows.go
Currently, UNIX socket is used for connection between CNI client and
server. However our tests on windows show that UNIX socket may
cause Windows BSOD.
This patch replace the UNIX socket with windows named pipe to avoid
Windows machine unstable.
=> [Windows]Use windows named pipe for CNI connection

Makefile, build/images/Dockerfile.build.windows, build/images/scripts/Install-WindowsCNI.ps1, build/yamls/antrea-windows.yml, hack/windows/Clean-AntreaNetwork.ps1, hack/windows/Install-DevTools.ps1, hack/windows/Install-OVS.ps1, hack/windows/Prepare-Node.ps1, hack/windows/Prepare-ServiceInterface.ps1, hack/windows/Reset-Node.ps1, hack/windows/Uninstall-OVS.ps1
- Add docker file for antrea-agent windows docker image.
- Add deployment yaml for antrea-agent and kube-proxy on windows.
- Add OVS install script. The main tasks of script are:
- Download test OVS from a predefined location.
- Install OVS kernel driver.
- Install ovsdb-server and ovs-vswitchd as service.
- Add prepare windows node script for test. The main tasks of script are:
- Download k8s binaries from official site.
- Install kubelet as service
- Install rancher-wins as service. rancher-wins can help start
antrea-agent process on host from POD.
- Create netadapter for kube-proxy.
=> [Windows]Add antrea-agent dockerfile and deployment yaml for windows

pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_linux.go, pkg/agent/cniserver/server_windows.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go
On windows platform, each container in a Pod will generate a CNI
request. In current implementation every container have chance to
be allocated with a IP in specific time sequence. Which may cause
the Pod IP change during the creation.
This patch fixes the issue by calling IPAM plugin only when handling
CNI request from infrastructure container.
=> [Windows]Fix Pod IP changes issue during creation

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/conf/antrea-controller.conf, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, cmd/antrea-agent/agent.go, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go, docs/configuration.md, go.mod, go.sum, pkg/agent/client.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/apiserver/apiserver.go, pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/certificate/certificate.go, pkg/apiserver/certificate/certificate_test.go, pkg/k8s/client.go, test/e2e/framework.go, test/e2e/security_test.go
To support server cert verification, this PR adds an option "selfSignedCert" (defaults to true) indicating whether to use auto-generated self-signed TLS certificate.
If it's set to false, antrea-controller will read user-provided TLS certificate key pair and its CA certificate from the path "/var/run/antrea/antrea-controller-tls", expecting a secret with the keys "ca.crt", "tls.crt" and "tls.key" is mounted to that path, and will serve HTTPS requests with the TLS certificate key pair.
Otherwise it will generate self-signed TLS certificate key pair on every start.
In either way, antrea-controller will publish the CA certificate to a well-known ConfigMap "antrea-ca" and the CABundle field of APIServices backed by it.
antrea-agent will read the CA certificate from the ConfigMap "antrea-ca" …
=> Support server certificate verification

build/yamls/antrea-prometheus.yml
Current antrea-prometheus.yml uses default account for Prometheus server access.
The following replaces it with Prometheus service account.
Fixes #718
=> Add Prometheus service account in monitoring NS

.github/workflows/go.yml, .github/workflows/integration.yml
Remove 'windows' branch from github CI before merge it into 'master'
=> [Windows]Remove 'windows' branch from github CI

go.mod, go.sum, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/ofctrl_flow_test.go, pkg/ovs/openflow/ofctrl_packetout.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go
1. Add support for PacketIn and PacketOut message. The consumer should register
a reason when subscribing PacketIn message.
2. Add support for Geneve Header TLV config. The consumer should add TLV map first,
and load customized data into the registered tunnel_metadata.
=> Add support for PacketIn/PacketOut and Geneve header

pkg/agent/metrics/prometheus.go, pkg/controller/metrics/prometheus.go
Kubernetes implements a wrapper for Prometheus, providing several
additional features such as metric deprecation and stability
information.
The patch is using this wrapper to expose metrics.
This also works around breakage due to upgrade of apiserver.
Fixes #734 
Fixes #662
=> Use K8S metric wrapper

docs/antctl.md
As a viable alternative to `--kubeconfig`.
=> Mention KUBECONFIG env variable in antctl documentation

.github/workflows/upload_release_assets.yml, Makefile, build/yamls/antrea-windows.yml, build/yamls/windows/base/agent.yml, build/yamls/windows/base/conf/Run-AntreaAgent.ps1, build/yamls/windows/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-cni.conflist, build/yamls/windows/base/kustomization.yml, build/yamls/windows/patches/dev/imagePullPolicy.yml, build/yamls/windows/patches/release/.gitignore, ci/check-manifest.sh, hack/generate-manifest-windows.sh, hack/release/prepare-assets.sh
We follow the same model for antrea-windows.yml as we do for our other
YAML manifests. The YAML file can now be generated (using
hack/generate-manifest-windows.sh) in both "dev" and "release" modes,
using the appropriate container image for both.
antrea-windows.yml is added to the `make manifest` target and we verify
that it is up-to-date in CI.
The release antrea-window.yml will also automatically be uploaded as
part of release assets starting with Antrea v0.7.0.
The only notable changes in antrea-window.yml itself are that:
- the ConfigMap used by the agent DaemonSet for Windows has been
renamed to avoid conflicting with the ConfigMap used by the Linux
agent DaemonSet
- the missing enablePrometheus and apiPort conf parameters were added
to antrea-agent.conf as I don't think they were …
=> Use Kustomize to generate release antrea-windows.yml

docs/windows.md
In the document we have a step to set the Node IP used by
kubelet by editing the kubeadm-flags.env file. However, the
file only exists after "kubeadm join" completes.
This patch moves the set Node IP step after "kubeadm join".
And adds a "restart-service kubelet" operation to make the configuration
change effective.
=> [Windows] Set Node IP after `kubeadm join` complete

.github/workflows/build.yml, .github/workflows/build_tag.yml
Bash is provided by "Git for Windows"
This simplifies things as we can use the same scripts as for the Ubuntu
jobs instead of using powershell equivalents.
At the moment these jobs fails because of incorrect syntax.
=> Use bash shell for Windows Github workflow jobs

pkg/agent/openflow/pipeline.go
One of the architectures we build antctl for at release time is armv7,
which is a 32-bit architecture. Some recent changes broke that build
(invalid uint32 - int conversions) and this commit fixes it.
=> Fix 32-bit arm build of antctl

ci/jenkins/jobs/macros.yaml, test/e2e/README.md, test/e2e/infra/vagrant/push_antrea.sh
The `--prometheus` flag needs to come after the package name, or the job
fails with the following error:
```
"build .: cannot find module for path ."
```
Also fix test/e2e/infra/vagrant/push_antrea.sh script for macOS.
=> Fix Jenkins job YAML specification for e2e tests

ci/clair-scan/run.sh
Fix the code that finds out the latest Antrea version, which determines
which image we need to scan: we exclude peeled tags and release
candidate tags from the tag list.
=> Fix Antrea Docker image vulnerability scan

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Use goto_table action instead of resubmit action in the OpenFlow entries for Pod-to-external traffic.
Fix #759
=> [Windows] Use goto_table action for Pod-to-external traffic

build/images/ovs/apply-patches.sh, build/images/test/Dockerfile, go.mod, go.sum, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/route_test.go, test/integration/ovs/ofctrl_test.go
1. Add support for matching original connection info in conntrack.
2. Simplify OpenFlow actions in the control interface
3. Add support for "note" action
4. Apply OVS patch in antrea/openvswitch image to support masking in ct_nw_xx/ct_tp_xx.
5. Modify "test" image to use antrea/openvswitch:2.13.0 as the base, and
install golang 1.13 in this new image
6. Change the integration test cases "TestInitialize" to follow the output
of iptables v1.6.1 which is installed in the new "test" image.
=> Optimization on OpenFlow control interface

docs/architecture.md, docs/assets/hns_integration.svg, docs/assets/windows_external_traffic.svg, docs/windows-design.md, docs/windows.md
=> [Windows] Add Antrea Windows design doc

cmd/antrea-agent/agent.go, go.mod, pkg/agent/interfacestore/interface_cache.go, pkg/agent/metrics/prometheus.go, pkg/ovs/openflow/ofctrl_bridge.go, test/e2e/prometheus_test.go
Track Antrea agent metrics when the corresponding events happen rather
than through a callback. This is for optimizing scraping ([comment in PR#321](https://github.com/vmware-tanzu/antrea/pull/321#discussion_r402425060)) to cut down the cost of calling function callbacks for every scrape. This also removes
dependencies on certain packages that are introduced by callbacks; the latter
becomes critical in adding new metrics.
In addition, it fixes the dependency on metric types such as
NewCounterFunc, NewGuageFunc etc. and there by RawRegister, which is
being deprecated soon.
Tested locally and through existing e2e test.
Fix #752
=> Remove function callbacks for tracking Antrea agent metrics 

build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu, cmd/antrea-cni/main.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go
This patch update the antrea cni to get the supported version
for the cni pkg. It also update the host-local plugin in the Ubunut
image with version that support cni spec 0.4.0
=> Update antrea cni to work with 0.4.0 version

test/integration/agent/cniserver_test.go, test/integration/ovs/openflow_test_utils.go, test/integration/ovs/ovs_client_test.go
Since `make docker-test-integration` runs the integration tests in a
Docker image, it is reasonnable to expect that one may be able to run
these tests on macOS (Docker Desktop). This required the following 2
changes:
* OVS bridges should use the netdev datpath type, since the kernel
datapath does not seem to be available in the KyperKit VM.
* The HyperKit VM seems to enable ipip, which means that some extra
tunnel interfaces are created in the network namepsaces that our
tests create inside the Docker container. As a result our CNI
integration tests need to be "relaxed" to accomodate for these.
Fixes #783
=> Support running integration tests on macOS

pkg/agent/cniserver/interface_configuration_linux.go, test/e2e/basic_test.go
On Linux, to flush stale ARP cache of network, antrea-agent is supposed
to send gratuitous ARP packets when configuring network for a Pod.
However, the routine was broken when refactoring the
"advertiseContainerAddr" method for Windows support. The action was
executed in a new spawned goroutine within the context of "NetNS.Do",
then it was actually executed after NetNS had switched to the target
container NS and had switched back to the host NS.
This patch fixes it by executing the whole routine in a goroutine, and
fixes the ticker leak problem. It also adds an e2e test to verify there
are at least 3 ARP packets received by OVS after a Pod is up to avoid
this being broken again as not sending GARP may not lead to connectivity
test failure stably if there are no IP reuse before ARP cache …
=> Fix the issue GARP not being sent

pkg/agent/agent.go, pkg/agent/config/node_config.go, pkg/agent/querier/querier.go, pkg/agent/querier/querier_test.go, pkg/version/version.go
The PodCIDR of NodeConfig could be nil for the networkPolicyOnly
trafficEncapMode. The AgentQuerier should check nil before converting it
to string.
Besides, this patch removes the redundant field BridgeName and fixes a
typo.
Fixes #793
=> Fix antrea-agent crashing in networkPolicyOnly mode

pkg/antctl/raw/supportbundle/command.go
The `--controller-only` flag tells the supportbundle command to only collect the support bundle of the antrea controller.
=> Add `--controller-only` flag for supportbundle command

pkg/ovs/ovsctl/appctl.go, pkg/ovs/ovsctl/ofctl.go, pkg/ovs/ovsctl/ovsctl_others.go, pkg/ovs/ovsctl/ovsctl_windows.go
Use "cmd.exe" on Windows when executing OVS commands.
Use the named pipe file for ovs-vswitchd control socket in ovs-appctl command.
=> [Windows] Support OVS commands in antctl

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
Jenkins gc job must run on the same node like e2e, conformance jobs, so it can find the same kubeconfig. This also applies to job-updater job.
=> Fix kubeconfig not found issue for jenkins gc job.

.github/workflows/kind_upgrade.yml, ci/kind/test-upgrade-antrea.sh
Programmatically determine the latest bug fix release for the 2 most
recent minor versions of Antrea and use that as the base versions for
the upgrade test.
This means we will no longer need to keep the test up-to-date after each
release.
=> Improve Antrea upgrade test

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
As a node-critical Pod, antrea-agent should be tolerant of all NoExecute
taints regardless of their keys like kube-proxy and other CNIs do,
otherwise workload Pods' network won't work once antrea-agent is evicted.
Fixes #814
=> Make antrea-agent tolerant of NoExecute taints

cmd/antrea-controller/controller.go, pkg/agent/apiserver/apiserver.go
The "/healthz" API is supposed to be accessed anonymously. However,
there were unintentional subjectaccessreviews queries sent to the
Kubernetes API when kubelets were executing liveness probe for antrea
components. This patch adds "/healthz" path to AlwaysAllowPaths to avoid
unnecessary overheads to the Kubernetes API.
=> Add healthz path to AlwaysAllowPaths

build/yamls/patches/kind/startAgent.yml, hack/generate-manifest.sh
When deploying Antrea in Kind clusters, we sometimes observe that the
antrea-agent container does not become ready for a few minutes. This
seems to happen specifically when the antrea-agent starts and
establishes connections to the k8s apiserver or the Antrea Controller
before the br-phy bridge has been created. When this happens, the
creation of the br-phy bridge seems to break the existing connections,
and the container is eventually re-started after the TCP keepalive
timeout (~5 minutes with the Go HTTP library), which fixes the
issue. However, by this time, a few e2e tests have timed out and failed.
This workaround adds a small sleep (2 seconds) before starting the
antrea-agent process, which ensures that the antrea-ovs container has
enough time to create the br-phy bridge.
Fixes #801
=> Add workaround for Agent readiness probe issue in Kind clusters

pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/cniserver/server_test.go, test/e2e/basic_test.go
There was no sync-up between the IPAM cache of antrea-agent and the IPAM
plugin, the IPAM DEL could be skipped incorrectly when deleting a Pod
created before antrea-agent was restarted, leading to IP address leak.
The handling of multiple CNI DELs is idempotent. There is no need to
check in-memory cache before calling IPAM DEL.
This patches fixes the issue by removing the cache check and adds a
verification in e2e test.
Fixes #829
=> Fix IP not released after restarting antrea-agent

pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go
CmdCheck will always returns success even if validation failed.
This PS fixes it to return error as well.
=> fix CmdCheck to failed on error

pkg/agent/agent_test.go, pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/apiserver/handlers/ovsflows/handler_test.go, pkg/agent/apiserver/handlers/ovstracing/handler.go, pkg/agent/apiserver/handlers/ovstracing/handler_test.go, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_linux.go, pkg/agent/cniserver/server_test.go, pkg/agent/cniserver/server_windows.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/interfacestore/interface_cache.go, pkg/agent/interfacestore/testing/mock_interfacestore.go, pkg/agent/interfacestore/types.go, pkg/agent/util/net.go, pkg/agent/util/net_test.go, test/integration/agent/cniserver_test.go
When deleting a StatefulSet Pod with 0 second graceful period, the Pod
might be removed from the Kubernetes API very quickly and a new Pod is
created immediately, leading to kubelet processing the deletion of the
previous Pod and the add of the new Pod simultaneously, so CNI cannot
assume PodNamespace+PodName must be unique.
Previously antrea-agent computes the network device name by hashing
PodNamespace and PodName, the CNI DEL of the previous Pod could destroy
the network device of the new Pod if it's executed after the new one's
CNI ADD.
To fix it, antrea-agent must no longer use PodNamespace+PodName as the
identifier of the Pod's network device. This patches uses (sandbox)
container ID as part of the network device name, and uses container ID
as the key when caching interfaceConfig, …
=> Fix statefulset Pod recreate case

pkg/ovs/ovsconfig/default.go, pkg/ovs/ovsconfig/default_windows.go
Instead of 1 second on Linux. We have observed on some production
clusters that it sometimes takes more second for ovs-vswitch to report
the port number to OVSDB, although we are not yet sure why. Because the
wait operation actually returns when the port is available, this does
not increase execution time of CNI Add in the general case.
=> Wait for 5 seconds when getting of_port number

test/e2e/framework.go, test/e2e/security_test.go
Even though the strategy of the antrea-controller deployment is
"Recreate", the old Pod might still be in terminating state when the new
Pod is running after deleting a Pod manually[1]. We should ensure
there's only 1 Pod and it's running after restarting antrea-controller
Pod.
[1] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment.
Fixes #823
=> Fix flaky test TestUserProvidedCert

build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu
To avoid unnecessary layer and time spent on apt-get update, merge apt
install instructions into one.
Ubuntu image automatically cleans up apt cache after every install, no
need to remove "/var/cache/apt" explicitly.
=> Merge apt install instructions of dockerfile

.github/workflows/lifecycle_management.yml, docs/github-labels.md, docs/issue-management.md
We use the stale action (https://github.com/actions/stale) to take care
of issue / PR state transitions and labelling.
The action is not quite as configurable as what we had in mind when we
wrote the issue management document, so we got rid of the
`lifecycle/rotten` label. But this label was only used to indicate that
the issue was being automatically closed.
Since we do not have a very high volume of new issues at this time, or a
very large backlog, I chose some more conservative time intervals for
transitions (issue becomes stale after 180 days, and is closed after an
extra 180 days of inactivity). These can be tuned in the future.
=> Add Github workflow for issue / PR lifecycle management

ci/jenkins/README.md
Fixes #729 
- Add cloud jenkins CI job status in ci/jenkins/README.md
- Add current test matrix
=> [CI] Add cloud support matrix in Jenkins readme

ci/jenkins/README.md, ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml
Fixed issue #819
* Support /test-whole-conformance to trigger a whole conformance test
* Support daily whole conformance test
* If whole conformance test fails, Jenkins will send an email to projectantrea-dev@googlegroups.com
The timeout for whole conformance test is 2 hr.
=> Support /test-whole-conformance and daily job

ci/jenkins/jobs/projects.yaml
Whole conformance test will only appear in Github checks when triggered or skipped.
This is suggested by @tnqn that this test is only for minor PRs. So for other PRs, such failed check is confusing in Github PR page's check session although it is not required.
=> Hide whole conformance test

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/metrics/prometheus.go, test/e2e/prometheus_test.go
- Change name of networkpolicy rule metric variable
- Add support the number of networkpolicies per node
This PR is a part of #713 feature request
=> Add support for the number of networkpolicies per node

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/options.go, pkg/features/antrea_features.go
There are a number of features that are being developed and likely to be
disabled by default in their early stage.
Instead of adding a temporary config for each feature and maintaining
them separately, this patch introduces Feature Gates to toggle the
features. It will be easier to choose code branch based on FeatureGates'
"Enabled" method and to promote features to beta and GA.
Closes #846
=> Use Feature Gates to enable or disable features

test/e2e/basic_test.go, test/e2e/framework.go, test/e2e/security_test.go
The user can change gateway interface name in antrea-agent.conf. We
should not assume the interface name is always "gw0". This patch detects
the name from ConfigMap.
=> E2E Test: Detect Gateway Interface Name from ConfigMap

hack/windows/Install-OVS.ps1
Update OVS version to 2.13.1
The implementation of the Antrea Proxy(#772 ) depends on this PR.
=> [Windows] Update OVS version to 2.13.1

ci/cluster-api/vsphere/templates/cluster.yaml
This may solve vsphere-csi-controller crash issue.
e.g.
https://jenkins.antrea-ci.rocks/view/antrea-for-pull-request/job/antrea-conformance-for-pull-request/634/console
It can be seen that in conformance test, e2e plugin only tests 2 cases and fails. It fails at BeforeSuite. On workload cluster, there is a pod called vsphere-csi-controller which keeps crashing. The root cause is this syncer container failure.
=> Update capv csi syncer

build/images/scripts/install_cni_chaining
In CNI chain option, add retry to look for primary
cni config file before adding antrea config in it
Fixes #863
=> Add retries for cni conf file

README.md, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, docs/architecture.md, docs/configuration.md, docs/ipsec-tunnel.md, docs/os-issues.md, docs/ovs-pipeline.md, docs/windows.md, pkg/agent/agent.go, pkg/ovs/ovsconfig/interfaces.go
Geneve supports extensible encapsulation headers which allow Antrea to
add extra contexts to the encapsulated packets across Nodes. This is
required by the Antrea Traceflow feature (see issue #631) which is
expected to be released in Antrea 0.8.0.
When upgrading an existing K8s cluster that configured Antrea to use
VXLAN tunnel type, there are two options to handle the default tunnel
type change:
1) Edit the Antrea deployment YAML and explicitly set the
'tunnel_type" config option to 'vxlan` in 'antrea-agent.conf' of the
'antrea-config' ConfigMap. Then Antrea will keep using the VXLAN
tunnel type after upgrade.
2) Swtich to the new default tunnel type. Then after the new version
of Antrea agent starts, it will delete the old VXLAN tunnel port on the
OVS bridge and create a new tunnel port …
=> Change default tunnel type from VXLAN to Geneve

build/images/scripts/daemon_status, build/images/scripts/start_ovs, build/images/scripts/start_ovs_netdev, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
* Increase failureThreshold to 5 and timeout to 10 seconds to avoid
frequent restarts when the node is overloaded.
* Set timeoutSeconds explicitly otherwise it's defaulted to 1 second,
though it's not honored by docker CRI.
* Keep the output of probe script so that it will be appended to the
message of liveness failure event and be helpful to see the actual
problem.
For #833
=> Improve liveness probe for antrea-ovs container

build/images/scripts/start_ovs
We observed in issue #870 that ovsdb-server failed to restart with
error: "ovsdb-server: /var/run/openvswitch/ovsdb-server.pid: pidfile
check failed (No such process), aborting", until we deleted the stale
OVS PID files.
This commit deletes all stale OVS PID, UDS, and OVSDB lock files before
starting the OVS daemons.
Fixes: #870
=> Clean up stable OVS PID, UDS, and OVSDB lock files before starting OVS

cmd/antrea-agent/agent.go, go.mod, go.sum, plugins/octant/go.sum
From 0.4.1 to 0.4.5.
In version 0.4.1, no error is returned by go-iptables when running
`iptables --version` or parsing its ouput fails (during
initialization). This leads to the library not being able to correctly
detect whether the iptables version supports `--wait`, which ultimately
can lead to a deadlock for the Antrea agent.
See https://github.com/coreos/go-iptables/pull/69.
By updating the go-iptables version, we ensure that any such error will
be returned to Antrea, logged, and cause the Antrea agent to fail and
eventually restart.
It is unclear what can cause iptables version detection to fail but
because of the added logging, we will have a better shot at getting to
the root cause if it happens in production again.
Fixes #871
=> Update go-iptables library version

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/pipeline.go, test/e2e/networkpolicy_test.go, test/integration/agent/openflow_test.go
Match the protocol type as one conjunctive match flow if the port number in the
NetworkPolicy rule is not specified.
Fixes #877
=> Add support for matching NetworkPolicy rule without port number

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-controller/config.go, docs/configuration.md, docs/securing-control-plane.md, pkg/agent/client.go, pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/certificate/certificate.go, pkg/querier/querier.go, pkg/util/env/env.go, test/e2e/security_test.go
Stop using the fixed "kube-system" Namespace for the CA ConfigMap.
Also update the deployment YAML and docs/securing-control-plane.md
about the descriptions about CA ConfigMap and TLS Secret Namespace.
Fixes: #876
=> Create controller CA ConfigMap in the controller deployement Namespace

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/proposal.md, .github/ISSUE_TEMPLATE/support_request.md, docs/issue-management.md
The "kind/*" labels which are described in the contributor docs should
be used instead of the legacy ones.
=> Update default labels in Github issue templates

.github/workflows/upload_release_assets.yml, hack/release/prepare-assets.sh, plugins/octant/Makefile, plugins/octant/cmd/antrea-octant-plugin/main.go
1. Modify prepare-assets to provide pre-built antrea-octant-plugin
for different platforms in release assets.
2. Change antrea-octant-plugin to adapt to 0.13.1 octant changes.
It seems that clicking on parent navigation bar will not show content
changes but only all the child navigation bars in octant release 0.13.1,
so this patch adds child navigation bar named overview to show
both Antrea controller and agent information tables.
Fixes:#853
=> Provide pre-built antrea-octant-plugin

docs/windows-design.md, docs/windows.md
In version 0.8.0, Antrea implements Kubernetes ClusterIP Service
leveraging OVS. This patch updates the related description in
Windows documents:
- Kubernetes ClusterIP Service function is provided by Antrea instead
of kube-proxy.
- kube-proxy still provide NodePort Service.
- NetworkPolicy for service is full supported.
=> [Windows] Update documents for Antrea proxy

ci/kind/test-e2e-kind.sh, go.mod, pkg/agent/controller/networkpolicy/priority.go, pkg/agent/openflow/network_policy.go, pkg/controller/networkpolicy/networkpolicy_controller.go, test/e2e/clusternetworkpolicy_test.go, test/e2e/framework.go, test/e2e/k8s_util.go, test/e2e/reachability.go, test/e2e/utils/cnpspecbuilder.go, test/e2e/utils/networkpolicyspecbuilder.go
This PR adds 8 E2E testcases for ClusterNetworkPolicy:
Tests in this group will be performed with DEFAULT-DENY k8s network policies applied to all underlying pods. This is to verify the ALLOW action for CNP.
- testCNPAllowXBtoA (basic)
- testCNPAllowXBtoYA (tests namedPort)
- testCNPPrioirtyOverrideDefaultDeny (tests priority precedence)
Tests below will be performed without any underlying k8s network policies.
- testCNPAllowNoDefaultIsolation (basic)
- testCNPDropEgress (tests DROP action)
- testCNPPrioirtyOverride (tests ipBlock and priority reassignments/precedence)
- testCNPPriorityConflictingRule (tests priority precedence)
- testCNPRulePrioirty  (tests rule priority precedence)
=> E2E tests for ClusterNetworkPolicy

docs/network-policy.md
Provide a general overview of ClusterNetworkPolicy CRDs and list key differences between CNP and K8s NP.
=> Add documentation for ClusterNetworkPolicy

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, docs/antctl.md, docs/architecture.md, docs/configuration.md, docs/os-issues.md, docs/ovs-pipeline.md, docs/policy-only.md, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/apiserver/handlers/ovstracing/handler.go, pkg/agent/apiserver/handlers/ovstracing/handler_test.go, pkg/agent/config/node_config.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/pipeline.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/antctl/antctl.go, test/e2e/framework.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
Add "antrea-" prefix to the default names of host gateway and tunnel
interfaces.
To handle interface name changes after Antrea upgrade, or name changes
due to agent configuration changes, antrea-agent will use the discovered
interface names (from the OVS bridge) as the gateway and tunnel
interface names.
=> Change gateway and tunnel interface names to antrea-gw0 and antrea-tun0

cmd/antrea-agent/agent.go, cmd/antrea-controller/controller.go, pkg/controller/networkpolicy/networkpolicy_controller.go
crdInformerFactory is a shared Informer factory, which should not rely
on specific features. Informers specific to a feature should be
registered conditionally, so that the crdInformerFactory won't start
watching corresponding resources when the feature is disabled.
Fixes #898
=> Register ClusterNetworkPolicy Informer only if the feature is enabled

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml, build/yamls/windows/base/conf/Run-AntreaAgent.ps1, cmd/antrea-agent/agent.go, cmd/antrea-agent/main.go, cmd/antrea-controller/controller.go, cmd/antrea-controller/main.go, pkg/log/log_file.go, pkg/log/log_file_test.go
klog does not enforce max log file size limit when the log file is not
specifiec by the --log_file argument. This commit sets klog.MaxSize to
the --log_file_max_size argument value when logging to file is enabled
and --log_file is not provided.
The commit also adds a new argument --log_file_max_num to define the
max number of log files to be kept. The file number limit is enforced by
Antrea code that periodically checks the INFO log files and deletes the 
oldest files to keep at most the specified max number of log files.
Fixes: #788
=> Support log file size and number limits

go.mod
- github.com/pkg/errors v0.8.1
+ github.com/pkg/errors v0.9.1
=> Fix go.mod tidiness checking

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
Before this change:
kubectl get cnp cnp0
NAME    AGE
cnp0      49m
After this change:
kubectl get cnp cnp0
NAME   PRIORITY   AGE
cnp0     10                49m
=> Print CNP priority on kubectl get cnp cnpName output

test/e2e/antctl_test.go, test/e2e/basic_test.go, test/e2e/networkpolicy_test.go, test/e2e/security_test.go
It seems tb is used by no one in runAntctl()
=> Remove unnecessary testing.TB in runAntctl()

.github/workflows/kind.yml, build/yamls/patches/np/npRbac.yml, ci/kind/test-e2e-kind.sh, cmd/antrea-agent/options.go, hack/generate-manifest.sh, hack/netpol/test-kind.sh, test/e2e/clusternetworkpolicy_test.go
Set default tunnel type to Geneve
Set default tunnel type to Geneve for Antrea instead of VXLAN.
When running NetworkPolicy tests in Kind, we "force" the tunnel type to
VXLAN as we observe some failures with Geneve (see #897).
We also change the Github CI jobs so that CNP tests are run in their own
job. This is to address the issue above, and is also a partial
implementation of #893.
=> Set default tunnel type to geneve

pkg/controller/networkpolicy/networkpolicy_controller_test.go
The same runtime.Object list cannot be used with both the standard K8s
client and the Antrea CRD client.
=> Minor fix in networkpolicy_controller_test.go

docs/feature-gates.md, pkg/log/log_file_test.go, test/e2e/framework.go, test/e2e/traceflow_test.go
* Use more specialized asserts (which give better error messages) in
log unit tests.
* Rename restartAntreaAgentPod to restartAntreaAgentPods in e2e test
framework and simplify implementation.
* Try not to conflate "Feature Gates" with "Features" in the
documentation.
=> Some miscellaneous minor fixes

go.mod, go.sum, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/util/arping/arping_linux.go, pkg/agent/util/arping/arping_linux_test.go, plugins/octant/go.sum, test/e2e/batch_test.go, test/e2e/fixtures.go
`GratuitousArpOverIface` in "github.com/j-keck/arping" is not thread-safe as it uses global variables to keep socket and Sockaddr. When batch processing CNI ADD requests, race condition could happen and lead to FD leak and mismatch as the goroutine that sends gratuitous ARPs may close and release others' FDs by accident.
This patch implements a thread-safe `GratuitousARPOverIface` and merges creating veth pair and configuring IP address into one method to avoid creating extra threads.
Fixes #934
=> Fix FD leak and mismatch when batch processing CNI ADD

pkg/agent/agent_windows.go, pkg/ovs/ovsctl/interface.go, pkg/ovs/ovsctl/ofctl.go, pkg/ovs/ovsctl/testing/mock_ovsctl.go
Set the uplink port with configuration "no-flood", so that the ARP "normal"
flow will not forward the packets to the uplink interface.
"no-flood" config is supported only in OpenFlow10, so using the ovs command
to set it.
Fixes #865
=> [Windows] Set the uplink port with "no-flood"

docs/octant-plugin-installation.md
Since we have included antrea-octant-plugin binary
into release assets and have a separate plugin
for Traceflow for now, update octant-plugin installation
guide to address the changes.
TODO: Update the doc after merging antrea-traceflow-plugin
into antrea-octant-plugin.
Related: #901
=> Update octant-plugin installation guide

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, docs/configuration.md, docs/eks-installation.md, docs/gke-installation.md, pkg/agent/agent.go, pkg/agent/cniserver/server.go, pkg/agent/config/node_config.go, pkg/agent/util/net.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
Discover mtu of primary interface if defaultMTU param is not
set in the antrea.yaml
=> Auto discovery mtu

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Set the packet with rewrite-MAC mark if it enters OVS from bridge interface,
and targets at local Pods, so that the packet's dst MAC could be re-written
in L3Routing table with the correct value.
Fixes #947
=> [Windows] Set rewrite-MAC mark for NodePort Service packet

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/crds.yml, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/apis/ops/v1alpha1/types.go, pkg/controller/traceflow/controller.go
Complete the Traceflow CRD schema and ensure that unknown fields are not set in CRD. This PR also ensures that
Namespace/Pod and IP fields are mutually exclusive in Destination and removes validation from controller.
=> Enforce Traceflow validation at CRD schema

docs/architecture.md
Netlify (for the website) does not like "absolute" paths.
The link the NetworkPolicyOnly doc was broken even on Github.
=> Fix markdown links in architecture document

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
Add Phase as part of `kubectl get` output. In addition to that, add source-pod, destination-pod and destination-ip as wide
option output for `kubectl get -o`.
```
kubectl get tf tf1
NAME   PHASE    AGE
tf1    Failed   44s
```
```
kubectl get tf tf1 -o wide
NAME   PHASE     SOURCE-POD   DESTINATION-POD   DESTINATION-IP   AGE
tf1    Running   appdns       appserver                          4s
```
=> Add additional fields to kubectl get traceflow

Makefile, pkg/agent/metrics/prometheus.go, test/integration/agent/cniserver_test.go, test/integration/agent/openflow_test.go
Added testing for following metrics in existing integration tests:
antrea_agent_ovs_total_flow_count
antrea_agent_ovs_flow_count
antrea_agent_local_pod_count
Fixes #799
=> Enhance testing for prometheus metrics at agent

.github/workflows/go.yml, .github/workflows/integration.yml, .github/workflows/kind.yml
Go, kind, integration CI can be triggered when there's a PR or push on ipv6 branch.
=> Github Actions on ipv6 branch

pkg/agent/openflow/client.go, pkg/agent/openflow/packetin.go
SubscribePacketIn requires a receiver to pop data in ch timely, otherwise it will block all inbound messages from OVS.
This PR closes #937
=> Fix bundle_timeout issue caused by OVS PacketIn channel

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_linux.go, pkg/agent/proxy/proxier_windows.go, pkg/agent/proxy/types/types.go, test/e2e/bandwidth_test.go, test/e2e/framework.go, test/e2e/proxy_test.go, test/integration/agent/openflow_test.go
Support handle LoadBalancer Service traffic:
- Install loadbalancing OpenFlow entires for Pod to LoadBalancer
  Service traffic. The traffic handling logic is same with the
  existing logic for ClusterService.
- Install OpenFlow entires for LoadBalancer Service traffic from
  outside. The traffic is forwarded antrea gateway, and then
  kube-proxy will handle the traffic.
- Add new OpenFlow table "UplinkTable" to place OpenFlow entries
  which are used to handle packtes received from uplink port.
=> [Windows] Support LoadBalancer Service

test/e2e/batch_test.go
pgrep is provided in Ubuntu and Debian by default. pidof is provided by
the sysvinit-utils package, which is not available in Debian. Use of
pgrep will allow downstream to repackage Antrea agent into various
distributions and still re-using the E2E test.
=> Use pgrep instead of pidof in E2E test

pkg/graphviz/traceflow.go, plugins/octant/Makefile, plugins/octant/cmd/antrea-octant-plugin/antrea_info.go, plugins/octant/cmd/antrea-octant-plugin/main.go, plugins/octant/cmd/antrea-octant-plugin/overview.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
1. Enhance Traceflow graph color theme.
Before:
After:
2. Merge Antrea plugins into one plugin: Antrea Octant Plugin
- Add two tabs in the Overview page of the plugin;
- Move the original traceflow plugin page into the folder "Antrea".
3. Change the layout of Antrea Overview page
Before: Put all tabs together and show them in Overview page
After: Put all CRD forms in one page (this format fits with the default Octant Homepage)
=> Enhance Antrea-Octant-Plugin

pkg/agent/metrics/prometheus.go, pkg/agent/openflow/pipeline.go, test/e2e/prometheus_test.go
Add support for OVS flow operations metrics on node
- Number of OVS flow operations, partitioned by operations(add, modify and delete)
- Number of OVS flow operation errors, partitioned by operations(add, modify and delete)
- The latency of OVS flow operations, partitioned by operations(add, modify and delete)
This PR is a part of #713 feature request
=> Add support for OVS flow operations metrics on node

pkg/agent/agent_windows.go, pkg/agent/config/node_config.go
When initialize the agent network on Windows node, the IP
configuration of uplink interface will be moved to OVS bridge
local interface. Which will cause the routes configured on
the uplink interface are lost.
This patch saves the routes configured on the uplink interface
before the IP configuration change and adds the saved routes on
OVS bridge local interface after that.
=> [Windows] Restore lost host routes during agent initialization

pkg/agent/agent.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/networkpolicy.go, test/integration/agent/openflow_test.go
Currently in Antrea, OVS flows for NetworkPolicies are installed asynchronously. For agent restart cases however, the initial NetworkPolicy events before the Bookmark (https://github.com/vmware-tanzu/antrea/pull/704) can be processed in batch and be sent to OVS bridge in a single bundle. This PR implements this methodology.
=> Support for batch OVS flow updates

pkg/agent/controller/traceflow/traceflow_controller.go
Find the destination MAC in traceflow controller by destination IP via local cache.
Solved a TODO in traceflow. Testing accepted on local machine.
=> Add finding destination MAC by IP in traceflow

.github/workflows/go.yml, Makefile, pkg/agent/util/doc.go, pkg/agent/util/sysctl/doc.go, pkg/agent/util/winfirewall/doc.go
Ever since goccy/go-graphviz was added as a dependency, running "make
golangci" (and related targets) has been broken on macOS. This is
because goccy/go-graphviz requires cgo to be enabled and go disables it
when cross-compiling (we set GOOS to linux in "make golangci" to ensure
that files with a linux build tag are verified by the linters).
We now run "make golangci" from a macOS worker in CI to avoid breaking
this again in the future.
In the future, we should also ensure that the linters are run on
Windows-specific files.
This commit also adds a few "missing" doc.go files.
=> Fix golangci targets on macOS

test/e2e/traceflow_test.go
The test was incorrect (traffic is dropped by an ingress policy
rule). However, this only became apparent after #981 was merged and the
DMAC of the Traceflow packet started being set correctly.
=> Fix intraNodeUDPDstIPTraceflow Traceflow e2e test

pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go
OVS supports to match DSCP field in OpenFlow, and the field is shown
as "nw_tos" in OVS command line. Besides, the TOS value is shifting
the DSCP value left 2 bits.
Fixes #1003
=> Add support for matching DSCP field in the IP header

.golangci.yml, pkg/agent/agent_test.go, pkg/agent/apiserver/apiserver.go, pkg/agent/client.go, pkg/agent/cniserver/server_test.go, pkg/agent/config/traffic_encap_mode.go, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/openflow/pipeline.go, pkg/agent/util/net.go, pkg/antctl/command_definition.go, pkg/antctl/raw/supportbundle/command.go, pkg/antctl/transform/controllerinfo/transform.go, pkg/antctl/transform/rule/transform.go, pkg/apis/clusterinformation/v1beta1/types.go, pkg/apis/networking/sets.go, pkg/apis/networking/v1beta1/sets.go, pkg/apiserver/apiserver.go, pkg/apiserver/registry/system/supportbundle/rest.go, pkg/controller/networkpolicy/networkpolicy_controller.go, test/e2e/basic_test.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/performance_test.go, test/e2e/prometheus_test.go, test/e2e/providers/vagrant.go, test/e2e/security_test.go, test/e2e/supportbundle_test.go, test/integration/agent/route_test.go, test/integration/ovs/ofctrl_test.go
We enable the staticcheck and gosec linters in golangci-lint.
The most important one here is gosec, as it will be useful when
answering questions for the CII Best Practices self-certification
questionnaire (see #989).
Running these linters did not reveal any noticeable issue in the Antrea
codebase.
=> Add new linters

docs/octant-plugin-installation.md, docs/traceflow-guide.md
Add document to guide users how to
use Traceflow via Antrea UI and Kubectl.
Related: #901
=> Add Traceflow User Guide

build/yamls/antrea-prometheus.yml, docs/prometheus-integration.md, test/e2e/prometheus_test.go
- Make e2e prometheus test consistent by using querying target metadata API
This PR updates prometheus image to v2.19.3 so that we can get basename without cutting out the metrics name in our e2e test. New codes using querying target metadata API.
https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata
However, this is still experimental so I won't merge if it's a risk to use the experimental API.
=> Upgrade prometheus image to v2.19.3

.golangci.yml, cmd/antrea-cni/main.go, pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/registry/networkpolicy/addressgroup/rest.go, pkg/apiserver/registry/networkpolicy/appliedtogroup/rest.go, pkg/apiserver/registry/networkpolicy/networkpolicy/rest.go, pkg/apiserver/registry/system/controllerinfo/rest.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/traceflow/controller.go, pkg/monitor/controller.go, test/e2e/connectivity_test.go, test/e2e/framework.go, test/e2e/performance_test.go, test/e2e/providers/kind.go, test/e2e/proxy_test.go, test/e2e/reachability.go, test/e2e/traceflow_test.go, test/e2e/utils/cnpspecbuilder.go, test/e2e/utils/networkpolicyspecbuilder.go
goimports makes imports deterministic, putting them in 3 sections:
builtin, 3rd-party, local packages. It saves reviewers's effort to
comment the order of imports.
It doesn't allow imports named "v1" unless the alias name is specified
as "v1", this patch adds the parent packages of v1 packages as the
prefix of the import names.
Fixes #1038
=> Enable linter goimports to tidy imports

ci/jenkins/jobs/projects.yaml, ci/run-k8s-e2e-tests.sh, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh
This is the first step in attempt to solve #1032. Dump the sonobouy results for easier debugging of flaky failures.
=> Collect full Sonobuoy results for cloud CI jobs

pkg/agent/cniserver/server.go, pkg/antctl/raw/supportbundle/command.go, pkg/monitor/controller.go, plugins/octant/cmd/antrea-octant-plugin/antrea_info.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
1. Use resourceVersion=0 to ensure the "List" request is served from the watch
cache in kube-apiserver, but not from the remote storage. This options is
added in CNIServer.reconcile, CRD monitor in Antrea Controller, and antctl
commands.
2. The SharedInformerFactory adds resourceVersion in the request automatically,
so no needs to add this option in the requests for Node and Service/Endpoints.
Fixes #1044
=>  Use resourceVersion=0 as an option in the List request

build/yamls/antrea-aks.yml, ci/check-manifest.sh
antrea-aks.yml is not up-to-date due to a merge conflict, and because antrea-gke.yml and antrea-aks.yml are not checked by CI so they were not detected.
=> Fix aks manifest YAML not up-to-date

test/e2e/README.md, test/e2e/traceflow_test.go
workerNodeName(2) implies that the cluster has 3 Nodes
Also include a 30m timeout value in the README instructions for running
e2e tests locally, since we now largely exceed the default 10m value.
=> Fix Traceflow e2e test to work on a 2-Node cluster

build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, docs/policy-only.md, hack/generate-manifest.sh, pkg/agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/route/route_linux.go, test/integration/agent/route_test.go
Kube-Proxy is not used in these modes for pod-to-service traffic.
=> Move noEncap/Hybrid/Policy-Only mode to use Antrea-proxy

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-controller.conf
Add space for ClusterNetworkPolicy value in controller config to align with the others
=> Add space for ClusterNetworkPolicy option to align with the others

.github/workflows/update_ovs_image.yml, build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.ubuntu, build/images/base/Dockerfile, build/images/base/build_and_push.sh, build/images/ovs/Dockerfile, build/images/ovs/README.md, build/images/ovs/apply-patches.sh, build/images/ovs/build_and_push.sh, build/images/test/Dockerfile
The main reason for this update is picking up a more recent version of
glibc, as the one that ships with Ubuntu 18.04 can cause OVS to deadlock
(See #1022).
In this PR, we only update the distribution for the "main" Antrea Docker
image; other images, such as the ones we use for testing or for
deploying the Antrea Octant plugin, can be updated later if needed.
This is also a good opportunity to upgrade OVS daemons from 2.13.0 to
2.13.1, since the Docker build had to be updated anyway. For the sake of
simplicity, from now on we will only support building the base
openvswitch Docker image for OVS >= 2.13.0.
Fixes #1022
=> Use Ubuntu 20.04 as base distribution in Antrea Docker image

go.mod, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/apis/networking/sets.go, pkg/apis/networking/sets_test.go, pkg/apis/networking/v1beta1/sets.go
When a NetworkPolicy rule had ports specified and had a large AddressGroup which has tens of thousands of Pods, it took quite a little CPU time to execute groupPodsByServices in antrea-agent. And if the rule applied to Pods across all Nodes, it would lead to CPU usage burst of the cluster, affecting the healthy of the whole cluster.
This patch optimizes several key functions in the following way:
1. For groupPodsByServices, if the rule has only numbered port, it returns the result with a fast path without iterating all Pods.
2. For groupPodsByServices, reuse the slice to avoid memory reallocations in the loop.
3. For hashServices and hashGroupMemberPod, construct the string with strings.Builder instead of using the spew library.
The improvement according to benchmark:
Before:
|  Test | …
=> Optimize groupPodsByServices and hash functions

pkg/agent/client.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go
=> Wait for Antrea client to be ready before starting watches

cmd/antrea-controller/controller.go, pkg/apiserver/storage/ram/watch.go
From the default 1800s (30 mins) to 2 hours.
I believe this may be a good idea for clusters with a large number of
Nodes and a large number of NetworkPolicies. K8s documentation also
recommends using a large value in production after verifying that
clients handle watch termination gracefully.
The verbosity level of the Controller log messages in case of watch
termination is also reduced to fix #1036. Unfortunetly there is no easy
way to make these log messages more useful (e.g. by correlating the
watcher object to the client).
=> Increase watch timeout for Antrea apiserver

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, cmd/antrea-agent/agent.go, cmd/antrea-controller/controller.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/pipeline.go, pkg/controller/traceflow/controller.go, test/e2e/traceflow_test.go
Result example:
```
results:
- node: gran-k8s0-1
observations:
- action: Forwarded
component: SpoofGuard
- action: Forwarded
component: LB
pod: kube-system/antrea-octant-7cb57d66bc-vtvmz
translatedDstIP: 192.168.0.69
- action: Forwarded
component: NetworkPolicy
componentInfo: EgressRule
networkPolicy: default/allow-all
- action: Forwarded
component: Forwarding
componentInfo: Output
tunnelDstIP: 10.176.26.135
timestamp: 1595490479
```
=> Support service destination in traceflow

cmd/antrea-agent/agent.go, docs/windows.md, hack/windows/Helper.psm1, hack/windows/Start.ps1, hack/windows/Stop.ps1, pkg/agent/apiserver/apiserver.go
Currently Antrea runs antrea-agent and kube-proxy from management
Pods. But there is still need to run these two components directly
using scripts. This patch:
- Adds scripts help to install and run antrea-agent and kube-proxy.
- Supports read kubeconfig from file for antrea-agent apiserver,
which is needed when antrea-agent is running as process.
=> [Windows] Support run antrea-agent directly from scripts

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, cmd/antctl/main.go, docs/antctl.md, pkg/antctl/antctl.go, pkg/antctl/raw/traceflow/command.go, pkg/antctl/raw/traceflow/command_test.go, pkg/apis/ops/v1alpha1/types.go, pkg/apiserver/apiserver.go
Fixed #923 
antctl traceflow is on remote mode, inside controller mode and inside agent mode.
It supports yaml and json output. It can return without retrieving results.
```
$ antctl traceflow -S busybox0 -D busybox1
name: default-busybox0-to-default-busybox1
phase: Succeeded
source: default/busybox0
destination: default/busybox1
noderesults:
- node: antrea-linux-testbed7-2
role: ""
timestamp: 1595391265
observations:
- component: SpoofGuard
componentinfo: ""
action: Forwarded
pod: ""
dstmac: ""
networkpolicy: ""
ttl: 0
translatedsrcip: ""
translateddstip: ""
tunneldstip: ""
- component: Forwarding
componentinfo: Output
action: Delivered
pod: ""
dstmac: ""
networkpolicy: ""
ttl: 0
translatedsrcip: ""
translateddstip: ""
tunneldstip: ""
```
=> antctl support traceflow

hack/windows/Install-OVS.ps1
Previously we use OVS package build from OVS branch_2.13.
Now OVS 2.13.1 is officially released. We build a new OVS
package from the released version.
This patch updates the sha256sum of OVS package.
=> [Windows] Update OVS package checksum

go.mod, go.sum, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/util/net.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, plugins/octant/go.mod, plugins/octant/go.sum
1. Add a new table named IPv6 to handle IPv6 ND Solicitation,
ND advertisement and IPv6 Multicast traffic.
2. Add flows in openflow tables (spoofGuardTable, IPv6,
conntrackTable, conntrackStateTable, conntrackCommitTable,
L2ForwardingOutTable) for handling IPv6 L2 Pod networking.
=> [IPv6] Change openflow pipeline for L2 Pod networking

build/images/ovs/apply-patches.sh
It is a workaround before upstream/ovs code update in ovs-monitor-ipsec.
```
#cat /var/log/antrea/openvswitch/ovs-monitor-ipsec.log
2020-08-06T10:38:36.455Z |  17 | ovs-monitor-ipsec | INFO | Tunnel stbed7-1-5b3e08 disappeared from OVSDB
2020-08-06T10:38:36.456Z |  18 | ovs-monitor-ipsec | INFO | Tunnel stbed7-2-b2a7f3 disappeared from OVSDB
2020-08-06T10:38:36.457Z |  19 | ovs-monitor-ipsec | INFO | Refreshing StrongSwan configuration
2020-08-06T10:38:36.573Z |  2  | daemon | INFO | pid 61 died, exit status 0, exiting
2020-08-06T10:38:53.25.Z |  0  | ovs-monitor-ipsec | INFO | Restarting StrongSwan
2020-08-06T10:38:55.201Z |  2  | reconnect | INFO | unix:/var/run/openvswitch/db.sock: connecting...
2020-08-06T10:38:55.202Z |  5  | reconnect | INFO | unix:/var/run/openvswitch/db.sock: …
```
=> [IPsec] Apply a patch to upgrade Python2 code in ovs ovs-monitor-ipsec

cmd/antrea-agent/options.go
These modes work with AntreaProxy only and do not support kube-proxy
any more.
=> Check AntreaProxy must be enabled for noEncap, hybrid, policyOnly modes

Makefile, build/yamls/antrea-eks-node-init.yml, ci/test-conformance-eks.sh, docs/eks-installation.md
This is temporary solution to handle a race condition with cni chaining mode. Basically if there are existing PODs before Antrea
is installled or in case of scale out if PODs are deployed before Antrea daemonset is applied, those PODs will not be managed by Antrea and hence network policies cannot be applied to those PODs.
With eks node init, pods are restarted once antrea config is detected.
Also updated the ci script and documentation.
Fixes: #869
=> Adding EKS node init script

pkg/ovs/openflow/ofctrl_flow.go
This PR fixes an issue introduced by #1023. The change of embedded struct ofctrl.Flow to embedded pointer in ofFlow has caused the priority reassignments to not function properly. CNP reconciler updates a flow's priority by deleting the old flow and create a new one at the updated priority. After the pointer change, delFlow and addFlow point to the same flow and cause the operation to fail.
=> Fix changes in ofctrl_flow.go that breaks CNP priority re-assignment

pkg/apis/ops/v1alpha1/types.go, pkg/graphviz/traceflow.go, plugins/octant/cmd/antrea-octant-plugin/antrea_info.go, plugins/octant/cmd/antrea-octant-plugin/main.go, plugins/octant/cmd/antrea-octant-plugin/overview.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
1. Enhance the "Start New Trace" page of traceflow plugin.
2. Add support for IP and service destinations in traceflow graph.
Also update the "Traceflow Info" form.
3. Add traceflow CRD cleanup for Antrea Octant plugin.
Traceflow CRD created by Antrea Octant plugin will be automatically deleted after created for 5min.
=> [Traceflow] Add support for IP and service destination in traceflow graph

docs/securing-control-plane.md, pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/certificate/certificate.go, pkg/apiserver/certificate/certificate_test.go
Addresses issue:   #976 
Provides basic certificate rotation
Currently hard coded to rotate every year minus 1 day.
But allows it to be set for both testing, and to allow for future additions to let user specify rotation period
Provides unit test to verify rotation.
=> Support self-signed certificate rotation

pkg/agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/interfacestore/types.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/ovs/ovs_client_test.go
This patch makes it because it can greatly improve the performance for
Geneve and VXLAN tunnels by triggering GRO on the receiver.
The Linux kernel defaults to enable it for VXLAN tunnels since 4.6. [1]
[1] torvalds/linux@6ceb31c
Fixes #1048
=> Enable UDP checksum for Geneve and VXLAN tunnels

go.mod, go.sum, plugins/octant/go.sum
1. Use readable message of OpenFlow errors in the log
2. Expose a public method to support copy Flow actions in ofnet
=> Bump up ofnet version to support readable error message in ofnet

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, hack/generate-manifest.sh, pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/networkpolicy.go, test/e2e/clusternetworkpolicy_test.go, test/e2e/utils/cnpspecbuilder.go, test/integration/agent/openflow_test.go
Add support for Tiered ClusterNetworkPolicies in Antrea agent. This PR adds the following:
- Updated internal NP types in agent to support tiers
- Moved OVS table determination logic into the networkpolicy pkg
- Updated OVS pipeline to reserve separate tables for each CNP Tier
- Refactored priorityAssigner logic to minimize reassignments and support any priority distribution within a Tier
=> [CNP] Agent CNP Tier Support

.github/workflows/upload_release_assets.yml, hack/release/prepare-assets.sh
Add following files in release assets for Windows:
- antrea-agent-windows-x86_64.exe
- antrea-cni-windows-x86_64.exe
- Start.ps1: The script can be used to install antrea-agent and
start it as process manually on Windows worker node.
=> Add release assets for Windows

.github/workflows/upload_release_assets.yml
Github is reporting that the syntax introduced by
https://github.com/vmware-tanzu/antrea/pull/1061 is not correct, so the
workflow cannot run.
=> Fix YAML syntax in "Upload assets to release" workflow

.github/workflows/integration.yml, ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml
In Github Action testbed, operation on docker IPv6 is limited. So, remove integration test in Github Action and run it on Jenkins.
Signed-off-by: Zhecheng <lzhecheng@vmware.com>
=> [CI] Run integration test on Jenkins

pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/ofctrl_flow_test.go, pkg/ovs/openflow/testing/mock_openflow.go
This PR will properly fix CNP E2E test failures. It depends on PR #1065.
=> Only copy relevant fields from ofctrl.Flow in ToBuilder()

build/images/test/Dockerfile
The Github action "Integration tests" always raises a check failure "git is not available, binaries will not include git SHA" and displays it on the "Files changed" board, which is a little distracting.
This patch fixes it by adding the required git tool to the test image.
=> Fix check failure in integration test

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
The change in SCM is not enough. GHPRB needs to set ipv6 branch as white list target as well. Add white_list_target_branches field in jobs to let jenkins-integration runs in ipv6 branch only.
=> [CI] Add IPv6 branch to white list target

pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/ipam/ipam_service.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/config/node_config.go
1. Add new field Ranges in IPAMConfig for allocating
both IPv4 and IPv6 addresses.
2. Populate subnet and gateway for both IPv4 range and IPv6 range.
=> [IPv6] Change host-local IPAM configuration for IPv6

.github/workflows/upload_release_assets.yml, docs/kind.md, hack/release/prepare-assets.sh
This may help avoid issues where users try to use the default YAML
manifest on Kind clusters. Documentation is updated accordingly.
Fixes #1103
antrea-kind.yml was manually added to v0.9.0 assets
=> Add antrea-kind.yml manifest to release assets

pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
If an egress rule allows all addresses but has no named port, it doesn't need to have the "matchAllPodsPeer" in its "To" Peer which is used for named port resolving. This could avoid the transmission of the "matchAllPods" AddressGroup and the reconciliation of the relevant rules.
For instance, the following rule allows all Pods in this namespace to access 53 port of all IP Addresses.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: allow-dns
spec:
podSelector: {}
policyTypes:
- Egress
egress:
- ports:
- port: 53
protocol: TCP
- port: 53
protocol: UDP
```
Before applying this patch, a global AddressGroup that contains all Pods in all Namespaces would be created, and the rule would be converted to:
```
- appliedToGroups:
- c4c59cfe-9160-5de5-a85b-01a58d11963e
name: …
```
=> Optimize processing of egress rules that have no named port

pkg/agent/agent.go, pkg/agent/apiserver/handlers/ovstracing/handler_test.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/config/node_config.go, pkg/agent/flowexporter/connections/conntrack.go, pkg/agent/flowexporter/connections/conntrack_test.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
Replace IP slice in GatewayConfig with separate IPv4
and IPv6 fields.
=> [IPv6] Use separate fields for IPv4 and IPv6 in GatewayConfig

.github/workflows/upload_release_assets.yml
Manifest is generated by prepare-assets.sh but was not uploaded.
=> Upload antrea-aks.yml manifest automatically to release assets

go.mod, go.sum, plugins/octant/go.sum
In afero 1.2.2, the `TempFile` does not accept wildcard and thus the filename will
contain an asterisk. Windows does not allow filename to have an asterisk.
Fixes #1148.
=> Fix invalid supportbundle temporary name

Makefile, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/util/ipset/ipset.go, pkg/agent/util/iptables/iptables.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go, test/integration/agent/openflow_test.go, test/integration/agent/route_test.go, test/integration/ovs/ofctrl_test.go
1. Use IPv6 in iptables and ipset configuration.
2. Identifiy IPv6 address and configure in OpenFlow.
3. Use Node Internal address for tunnel.
=> [IPv6] Implement L3 connectivity for IPv6 traffic

pkg/agent/agent.go
For IPv6 single stack case, node.Spec.PodCIDR is
configured with IPv6 CIDR. This patch handles the case
and sets nodeConfig.PodIPv6CIDR with parsed CIDR.
=> [IPv6] Handle Spec.PodCIDR with IPv6 CIDR

docs/antctl.md, pkg/antctl/antctl.go, pkg/antctl/raw/traceflow/command.go, test/e2e/traceflow_test.go
* Add config for TCP flags in antctl traceflow
* Tell users that Pod will be set as destination when it shares the same name with a Service.
Fixes: #1126
Enhances: #1077
=> antctl traceflow improvement and bug fix

ci/jenkins/jobs/projects.yaml
ipv6 -> ${sha1}
Currently every build checks out the TOT code on vmware-tanzu/antrea ipv6 branch instead of the commit in the PR.
=> [CI][IPv6] Update integration branch

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/pipeline.go
Conversion from uint32 to string yields a string of one rune, not a
string of digits.
Fix #1162.
=> Fix uint-string conversions

pkg/apiserver/certificate/cacert_controller.go, pkg/apiserver/certificate/certificate.go, pkg/apiserver/certificate/certificate_test.go
fixes: #1152
Self signed certificates are now stored in files rather than memory. This allows for the use of dynamic certificate objects. That will automatically process the update
The caCertController is updated immediately through RunOnce, whereas the DynamicServingContent for the serving certificate can take up to one minute 
Attached is a log for an antrea controller with a fixed certificate rotation every 3 minutes. It shows that it can take up to 1 minute for the certificate to be detected, but in production, the rotation period will be closer to months.
[antrea-contoller-info.txt](https://github.com/vmware-tanzu/antrea/files/5137972/antrea-contoller-info.txt)
=> Certificate Rotatation in APIServer

pkg/agent/agent_test.go, pkg/agent/apiserver/handlers/ovstracing/handler.go, pkg/agent/apiserver/handlers/ovstracing/handler_test.go, pkg/agent/apiserver/handlers/podinterface/handler.go, pkg/agent/querier/querier.go, pkg/agent/querier/querier_test.go, pkg/agent/util/net.go, pkg/antctl/antctl.go, pkg/ovs/ovsctl/appctl.go
1. Support using IPv6 address in OVS tracing.
2. Support displaying Node's and Pod's IPv6 address in agent apiserver.
=> [IPv6] Add support for IPv6 address in antctl and agent's apiserver

Makefile, go.mod, go.sum, pkg/graphviz/traceflow.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go, plugins/octant/go.sum
Replace dependency "github.com/goccy/go-graphviz", which contains C files, with "github.com/awalterschulze/gographviz", which contains only Golang files.
Fixes #1089
=> Remove graphviz C dependencies in traceflow

plugins/octant/cmd/antrea-octant-plugin/antrea_info.go
NodeSubnet can have two values in dual stack case and
this patch enhances octant-plugin to show both subnets.
=> [IPv6] Display dual stack NodeSubnet in antrea-octant-plugin

ci/jenkins/README.md, ci/test-conformance-gke.sh
Supported cluster master versions tends to be updated periodically and originally supported versions might be invalidated. Jenkins jobs should query the latest version available before setting up the cluster.
Fixes #1169
=> Always use latest supported master version when setting up GKE cluster

cmd/antrea-agent/agent.go, pkg/agent/controller/traceflow/traceflow_controller.go
We already perform that check when a Service name is provided, but I
think we should do it as well for ClusterIP destinations. Otherwise, we
end up with an incorrect Traceflow result.
Logging this in the Agent is not ideal because you have to figure out
which logs to look at, but this is the only thing we can do right now.
=> Traceflow: check that AntreaProxy is enabled for ClusterIP destinations

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go, docs/aks-installation.md, docs/configuration.md, docs/eks-installation.md, docs/gke-installation.md, hack/generate-manifest.sh
Remove the serviceCIDR parameter for AKS, EKS, GKE clusters, as
AntreaProxy is always enabled for them and the serviceCIDR parameter
is useless.
Also update configuration.md and the cloud installation documents.
=> Update cloud deployment yamls and documentation

codecov.yaml
Exclude following files in the coverage report:
- `testing/mock_*.go`
- `*generate*.go`
- `**/*.pb.go`
- `pkg/client/**`
- `third_party/**/*`
=> Enhance code coverage report

build/images/ovs/charon-logging.conf
strongSwan logging configuration is reported as invalid in some OSes
(e.g Ubuntu 16.04) when starting the strongSwan services. It is probably
due to the strongSwan version change after the Antea Docker image is
updated to use Ubuntu 20.04. This commit fixes the strongSwan logging
configuration.
=> Fix strongSwan logging configuration

docs/network-policy.md
cidr is a sub-field of ipBlock, it must be indented.
=> Fix indent in ClusterNetworkPolicy example

pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go
This PR fixes #1181 
In NetworkPolicy reconciler, uninstallOFRule() is called in two circumstances: 
1) A NetworkPolicy rule is deleted by user, in which case it is called thru Forget(). 
2) There has been updates to the original appliedTo pods of the NetworkPolicy rules, specifically delete events. If such delete event causes a ofRule's appliedTo to become empty, that ofRule should be removed following the logic 
Reconcile(), L199 --> update(), L483 --> uninstallOFRule(), L589.
The priorityMutex of a CNP Table, which prevents concurrent priority updates within a single table, should be held at the Reconcile() and Forget() function level. Before this fix, the mutex is acquired at both Reconcile() and uninstallOFRule() in the second scenario mentioned above, causing a deadlock for that …
=> Fix deadlock caused by acquiring priorityMutex twice

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, ci/kind/test-upgrade-antrea.sh, hack/generate-manifest.sh, hack/verify-kustomize.sh
Ensure that we use the desired version of kustomize even when there is
already an installation of kustomize. This is important because in
v3.8.0, kustomize stopped using apimachinery by default and switched
to its own library (kyaml) for K8s resource YAML manipulation. Because
of this change, the generated YAMLs are different: fields within objects
may be ordered differently, and the latest kustomize generally does a
better job dropping empty fields. We set the desired version to v3.8.2.
No action should be required from Antrea developers. The next time they
run `make manifest` locally, the correct version of kustomize will be
downloaded under `./hack/.bin`.
Fixes #975
Fixes #1017
=> Use specific kustomize version when generating manifests

build/images/ovs/apply-patches.sh
Starting from version 5.7.0, strongSwan no more supports to specify a
configuration paramter with the path delimited by dots in a
configuration file. This change breaks ovs-ipsec-monitor which writes
strongSwan configuration parameters with the dotted paths.
This commit applies an ovs-monitor-ipsec patch to fix the issue, as a
workaround before the patch is merged to OVS upstream.
=> Fix strongSwan configuration file with strongSwan >= version 5.7.0

pkg/agent/apiserver/handlers/agentinfo/handler.go, pkg/agent/querier/querier.go, pkg/agent/querier/querier_test.go, pkg/antctl/command_definition_test.go, pkg/apis/clusterinformation/v1beta1/types.go, pkg/apis/clusterinformation/v1beta1/zz_generated.deepcopy.go, pkg/apiserver/openapi/zz_generated.openapi.go, pkg/controller/querier/querier.go, plugins/octant/cmd/antrea-octant-plugin/antrea_info.go
To avoid duplicate CIDRs, this patch makes a new string slice for dual stack
node subnet instead of appending agentInfo.NodeSubnet directly.
=> [IPv6] Handle dual stack NodeSubnet for monitoring CRD

ci/gh-actions/has-changes/Dockerfile, ci/gh-actions/has-changes/README.md, ci/gh-actions/has-changes/action.yml, ci/gh-actions/has-changes/entrypoint.sh
This action can be used to determine whether a "diff" includes changes
to files whose paths are not part of a provided exclusion list.
A "diff" is defined as:
* for a PR, the diff between the base SHA and the HEAD
* for a push, the diff between the last SHA that was previously pushed
to the branch and the HEAD
This action can be used to avoid running Kind tests for documentation
PRs. Unlike the "paths-ignore" option for Github workflows, we will
return a success status even when the tests are being skipped.
=> Add "Has Changes" Github action

build/images/scripts/start_ovs
=> Fix unbound variable error in start_ovs Bash script

.golangci.yml
The golangci-lint CI job which runs on macOS often times out, probably
because the VM is a bit slow. We double the timeout to see if it solves
the issue.
Fixes #1174
=> Increase golangci-lint timeout from 5m to 10m

pkg/apiserver/registry/system/supportbundle/rest.go, pkg/ovs/ovsctl/interface.go, pkg/ovs/ovsctl/ofctl.go, pkg/ovs/ovsctl/testing/mock_ovsctl.go, pkg/support/dump.go, pkg/support/dump_others.go, pkg/support/dump_windows.go
1. Add support to collect ovs/kubelet logs and host network info on Windows Node.
2. Add support to dump OpenFlow ports desc.
Fixes #1144
=> Enhancement in support bundle

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
Uses the new vmware-tanzu/antrea/ci/gh-actions/has-changes@master
action (see https://github.com/vmware-tanzu/antrea/pull/1188).
Fixes #455
=> Skip Kind tests for documentation PRs

.github/workflows/kind.yml
Since antrea proxy needs to be force enabled in policyOnly, noEncap and
hybrid modes, there is no need to run test-e2e-noencap-proxy and
test-e2e-hybrid-proxy tests.
=> Remove redundant kind tests

.github/workflows/golicense.yml, build/images/golicense/Dockerfile, build/images/golicense/README.md, ci/golicense/README.md, ci/golicense/conf.json, ci/golicense/run.sh
We add a script and a corresponding CI job to analyze the Antrea
binaries and extract their Go dependencies. I could not find any good
tool for source-based dependency analysis
(https://github.com/google/go-licenses seems to have many issues, and
fails for quite a lot of depedencies, without any possibility of manual
override). Analyzing binaries also mean that we can avoid some false
positives for transitive dependencies that end up not actually being
used by Antrea.
The CI job will help us automatically detect licensing issues (e.g. non
business-friendly license, such as GPL/LGPL) with new dependencies
before we merge a patch. With the CI integration, we can also publish a
list of the Go dependencies for the Antrea binaries with each release.
TODO: for releases, upload full dependency …
=> Add Go dependeny scan using golicense

pkg/apiserver/handlers/endpoint/handler_test.go
"handler_test.go" should be put in the same package as "handler.go".
=> Put unit tests alongside the source code

docs/network-policy.md
With the addition of namespaced Antrea NetworkPolicy, this PR adds relevant documentation.
=> Add Antrea NetworkPolicy documentation

test/e2e/connectivity_test.go, test/e2e/framework.go, test/e2e/ipsec_test.go
The tests were passing even when IPsec support was broken and the
antrea-ipsec container was crashing on start. See #1043.
We update the tests to run additional checks:
* make sure the containers do not crash after updating the YAML (with
IPsec -> without IPsec, and vice versa), by monitoring container
status for 20 seconds
* make sure a Security Association is created correctly between Nodes
when checking inter-Node Pod connectivity
An alternative solution for the first item could have been to use
minReadySeconds for the Antrea Agent DaemonSet, but I didn't want to
modify the YAML manifest.
Fixes #1043
=> Fix Antrea IPsec e2e tests

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds-rbac.yml, build/yamls/base/kustomization.yml, docs/network-policy.md
Aggregate the CRUD permissions to "admin" and "edit" ClusterRoles so that any user granted these roles may have edit permissions. In addition to this, aggregate the READ-ONLY permissions to "view" ClusterRole, so that any user granted this role may be able to view the CNP/ANP resources.
=> Aggregate CNP/ANP access to admin/edit and view ClusterRoles

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
Update ClusterNetworkPolicy and Antrea NetworkPolicy CRD yaml to take "Allow" and "Drop" actions as enum.
=> Use enums instead of regex for NP CRD actions

test/e2e/proxy_test.go
- Fix TestSessionAffinity: session affinity of the LoadBalancer service was not enabled.
- Run TestSessionAffinity in KIND tests since the OVS has been updated and the test can run now.
Fix #881.
=> Fix ingress session affinity test case

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds-rbac.yml, docs/traceflow-guide.md
Aggregate the Traceflow CRUD permissions to "admin" and "edit" ClusterRoles so that any user granted these roles may have edit permissions. In addition to this, aggregate the READ-ONLY permissions to "view" ClusterRole, so that any user granted this role may be able to view the Traceflow resources.
=> Aggregate cluster edit and view roles for Traceflow CRDs

Makefile
Add "--pull" for make ubuntu/build-ubuntu/build-windows/octant-antrea-ubuntu.
Without "--pull", images cannot be updated when "make".
Few developers will be affected if they work on antrea/openvswitch or antrea/base-ubuntu but this patch benefits the most.
=> docker build add "--pull" for "make"

go.mod, go.sum, test/integration/ovs/ofctrl_test.go
1. Bump up ofnet version to resolve a goroutine leak issue introduced
when failing to begin a Bundle.
2. Modify the integration test to ensure the case doesn't stuck at
wg.Wait().
Fixes #1234
=> Fix integration test issue with case "TestBundleErrorWhenOVSRestart"

.github/workflows/build.yml
This extends https://github.com/vmware-tanzu/antrea/pull/1189 to skip
other CI jobs for documentation PRs. In particular, the Windows Docker
build, which takes more than 20 minutes to complete. Note that once the
documentation PR is merged, the 'push' event will trigger new Docker
images to be built and uploaded to dockerhub, which should be the
desired behavior.
=> Skip Docker builds in CI for documentation PRs

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml, build/yamls/patches/dev/agentVerboseLog.yml, build/yamls/patches/dev/controllerVerboseLog.yml, docs/troubleshooting.md, hack/generate-manifest.sh
This patch enables verbose logging for antrea-agent and
antrea-controller when generate manifest. This will help in
troubleshooting with increased log level.
I felt troubleshooting info for incrementing log-level for antrea-agent and antrea-controller is lacking right now. I thought providing an antrea manifest through generate-manifest.sh with increased log-level is one way to help troubleshooting for developers/users. There could be an efficient approach instead of using antrea-conf configMap. Please comment on what you think. 
If this approach looks ok, I will update the troubleshooting doc as part of this PR.
=> Enable verbose logging through generate-manifest.sh

pkg/controller/metrics/prometheus.go
Fix #905
The summary types are tagged for deprecation, Kubernetes recommended to use histograms instead of summaries. The main advantages of histogram types are aggregation and inexpensive. In this commit, we changed three Antrea controller metrics from summary to histogram type. They are DurationAppliedToGroupSyncing, DurationAddressGroupSyncing, and DurationInternalNetworkPolicySyncing.
Did the manually test to check the type of these metrics using following commands:
1. `make`
2. `./test/e2e/infra/vagrant/push_antrea.sh --prometheus`
3. `kubectl exec -it <antrea_controller_pod> -n kube-system -- bash`
4. `TOKEN=$(cat /var/run/antrea/apiserver/loopback-client-token)`
5. `curl --insecure --header "Authorization: Bearer $TOKEN" https://127.0.0.1:10349/metrics`
Test results:
`# HELP …
=> Change prometheus metrics type from summary to histogram

hack/generate-manifest.sh
manifest generation failing in release mode as the line checking for verbose log option assumes empty string initialization (old code).
Fixed the bug in PR #1142.
=> Bug in enable verbose log patch

hack/generate-manifest.sh
Needs to replace the correct regex pattern
=> Fix bug in --np option of generate-manifest.sh

go.mod, go.sum
Bump up ofnet version to resolve an issue that publishing OVS reply messages
to a closed channel when a Bundle fails to begin.
The commit link in ofnet is https://github.com/wenyingd/ofnet/commit/57045ae085da3d8a5c50a3b3db804b4f3ace6209
Fixes #1234
=> Fix integration test issue introduced in ofnet

docs/network-flow-visibility.md, docs/traceflow-guide.md, hack/windows/Install-OVS.ps1
Fixes #1254
The SHA256 checksum verification for the OVS Windows binaries is no
longer required for security reasons, but it may be a good idea to keep
it (there is no real maintenance burden, we just need to update it
whenever the link is updated). It can help ensure that there is no issue
on our side and that the file that was uploaded to S3 by us is the
correct one. There is no burden on users. We can also remove that code
altogether.
=> Download all artifacts from https://downloads.antrea.io

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, pkg/agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/util/iptables/iptables.go, pkg/agent/util/net.go, pkg/support/dump_others.go, test/integration/agent/openflow_test.go
1. Add a config item for IPv6 Serivce CIDR if using kube-proxy to
provide Service functions.
2. Output IPv6 traffic from host gateway if its destination is a
Service address.
3. Use ct_mark to identify Service traffic and output the reply
packet to the host gateway to ensure the DNAT processing in iptables.
=> [IPv6] Add support for dual-stack when using kube-proxy for Service

build/yamls/antrea-prometheus.yml, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/prometheus_test.go
In order to troubleshoot Prometheus e2e testing issues, enable
Prometheus logging to diagnose connectivity problems between Prometheus
and Antrea components.
Also, inclode the monitoring namespace Pod logs (mainly Prometheus server)
within the test output bundle.
=> Enable debug logging on Prometheus server

.github/workflows/kind_upgrade.yml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/antctl.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, build/yamls/patches/kind/onDeleteUpdateStrategy.yml, ci/kind/test-upgrade-antrea.sh, hack/generate-manifest.sh, pkg/apis/networking/doc.go, pkg/apis/networking/install/install.go, pkg/apis/networking/register.go, pkg/apis/networking/v1beta1/conversion.go, pkg/apis/networking/v1beta1/doc.go, pkg/apis/networking/v1beta1/register.go, pkg/apiserver/apiserver.go, pkg/apiserver/certificate/cacert_controller.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/upgrade_test.go
Package networking is superseded by package controlplane in v0.9.3, to keep backward compatibility with up to two minor versions of antrea-agents, the API group should remain for two more minor releases.
This patch adds the APIs back and serves them with the same storage as controlplane API. Also, kind tests are added to make sure basic functionalities are not broken when only controller is upgraded.
Fixes #1250
=> Add legacy networking API group for backward compatibility

pkg/agent/controller/traceflow/traceflow_controller.go, pkg/controller/traceflow/controller.go, pkg/controller/traceflow/controller_test.go, test/e2e/traceflow_test.go
Check if running Traceflow requests are timeout every 1 minute.
Change the Traceflow timeout period to 2 minutes.
Deallocate DP tag after a Traceflow request succeeds or is timeout.
=> Periodically check timeout of running Traceflow requests

.github/workflows/kind.yml, ci/kind/test-e2e-kind.sh, docs/architecture.md
I have verified this workflow in https://github.com/vmware-tanzu/antrea/actions/runs/258851376.
Developers can download the logs in the artifacts dropdown menu of the check.
=> Upload test logs to Github actions when kind tests failed

ci/jenkins/README.md, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/test-conformance-eks.sh
Also fixing an issue in GKE Jenkins job description where static version is still used instead of relying on the script to fetch the latest supported master version.
=> Upgrade eksctl and its default k8s cluster version

test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/flowexporter_test.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/performance_test.go, test/e2e/proxy_test.go, test/e2e/supportbundle_test.go, test/e2e/traceflow_test.go
1. Add e2e cases for IPAM allocation in dual-stack.
2. Add e2e cases for connectivity, including same Node and different Node cases.
=> [IPv6] Extend e2e tests for dual-stack

build/yamls/antrea-prometheus.yml, docs/prometheus-integration.md, pkg/agent/metrics/prometheus.go, pkg/controller/metrics/prometheus.go
Deprecate run time info metrics that provide node name and pod name
from Antrea 0.10.0. These metrics will be removed Antrea 0.11.0. Added
deprecation policy for the Prometheus metric in Antrea documentation.
In addition, antrea-prometheus.yaml is changed to add nodename and
pod name to the instance label instead of the default IP:port. This will help
with promql queries to search for metrics on a specific node or pod.
=> Deprecate prometheus run time info metrics

docs/cookbooks/multus/README.md, docs/cookbooks/multus/assets/testbed-multus-macvlan.svg, docs/cookbooks/multus/build/cni-dhcp-daemon/Dockerfile, docs/cookbooks/multus/build/cni-dhcp-daemon/README.md, docs/cookbooks/multus/resources/dhcp-daemon.yml, docs/cookbooks/multus/resources/dhcp-server.yml, docs/cookbooks/multus/resources/macvlan-host-init.yml, docs/cookbooks/multus/resources/netAttachDef.yml, docs/cookbooks/multus/resources/test.yml, docs/cookbooks/multus/test/Vagrantfile, test/e2e/infra/vagrant/Vagrantfile
We add documentation to show how Antrea can be used with Multus: Antrea
is used as the default CNI plugin and an "arbitrary" plugin (in our
case, macvlan) can be used to attach additional interfaces to designated
Pods. Nothing is required on the Antrea side to make it work, so this is
just to show how it can be used in practice.
Fixes #368
=> Add cookbook on how to use Antrea with Multus

ci/test-elk-flow-collector.sh
After trying to reproduce ci failure for validating elk-flow-collector manifests in the last two days, found that the problem may lie in logstash readiness when Antrea starts to send flow records. Add wait for 30s for logstash to be ready.
=> [CI] Fix validating elk-flow-collector ci

pkg/agent/agent.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go
serviceCIDRDNATFlow includes a DMAC rewrite action that rewrites the
the destination MAC to the antrea-gw0 interface MAC. The action was
added for supporting NetworkPolicyOnly with kube-proxy. Since we no
longer support kube-proxy in NetworkPolicyOnly mode, this action is no
longer needed.
Fixes: #1264
=> Remove unnecessary DMAC rewrite in the Service CIDR flow

pkg/graphviz/traceflow.go
When users start a traceflow on the Antrea Octant plugin, they need to wait for several seconds before the traceflow graph finishes., which may be considered a UI bug. Also, when something's wrong with traceflow, users will see a blank graph, which is confusing. 
This patch shows status messages on traceflow graph when traceflow is running, pending or stopped for some reason. When users start a traceflow, they will see the graph showing "traceflow xxx is running" in the first seconds.
Example graphs:
1. Traceflow is running:
2. Showing error messages:
According to Octant team, the next Octant release is running into some delays and pushing into early this week. Alerts with traceflow error messages will be added after the next Octant release.
Fixes #1175
=> Add status messages for traceflow graph

pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go, pkg/agent/types/networkpolicy.go
This PR aims to fix #1093 
In cases of batch priority registration, two known states can be taken advantage of:
1) The ofPriority <-> Priority mapping is empty at the time batch registration is called, since it is only used in agent restart case.
2) All the Priorities that needs to be registered are readily available, unlike in the async reconcile case after agent starts, where each Priority registration is independent.
To utilize those two properties, the RegisterPriorities function is refactored in the following way: it first sorts and dedups the Priorities that needs to be registered. Then, starting from the highest Priority, it gets the insertionPoint of that Priority and evaluates if there are enough OpenFlow priorities left (from lowest ofPriority allowed on the table to …
=> Optimizing PriorityAssigner for batch priority registrations

build/images/scripts/start_ovs, build/images/scripts/start_ovs_netdev
This patch removes "read" permissions for "others". The idea is to
improve security for OVSDB, which notably stores the PSK in plaintext
when using IPsec.
This is not perfect, as there is a time window between creation of the
db.conf file and the call to chmod.
See full discussion in #1292
=> Restrict read permissions for OVSDB

pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
This PR is based on #926 and supersedes  #1066.
It adds the following:
- Updates pipeline.go and create Antrea Policy rules in all tiers other than default in a single table for ingress/egress
- Updates InitialOFPriority() to handle multi-tiers in a single OVS table.
- Minor improvements to priority.go
- E2E testcases for custom tiers
Closes: #917
=> Agent support for Tier CRD

docs/assets/flow_exporter.svg, docs/network-flow-visibility.md
Update the figure in flow exporter documentation
=> Update flow exporter documentation

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
This PR updates short-names for Antrea Policy CRDs as follows:
ClusterNetworkPolicy
Existing short name: cnp
New short name: acnp
NetworkPolicy
Existing short name: netpol
New short name: anp
Existing short-name "cnp" and "netpol" are deprecated in favor of new short names and shall be removed in Antrea 0.12.0
release.
=> Update short-names for Antrea NetworkPolicy CRDs

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml
apiVersion v1beta1 has been deprecated for CRDs in favor of v1.
This PR takes care of updating versions of all the CRDs available.
In addition to the version update, this PR also ensures strict schema validation for the following CRDs:
- traceflow
- clusternetworkpolicy
- networkpolicy
- externalentity
- tier
Related-Issue: #684
=> Switch CRD apiVersion to v1 from v1beta1

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller.yml, build/yamls/base/crds.yml, cmd/antrea-controller/controller.go, pkg/apiserver/apiserver.go, pkg/apiserver/handlers/webhook/validation_crd.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/validate.go
This PR adds validation for ANP CRUD via the use of a ValidatingWebhookConfiguration. Following validation is performed:
Tier DELETE
Check for referenced ANPs
ANP CREATE/UPDATE
Check if referenced Tier exists
=> Add Antrea NetworkPolicy CRD Validation web hook

test/e2e/framework.go, test/e2e/security_test.go
1. No -6 option in busybox nc
So, no need to distinguish if it is an IPv6 environment for runNetcatCommandFromTestPod()
nc
BusyBox v1.31.1 (2019-10-28 18:40:01 UTC) multi-call binary.
Usage: nc [OPTIONS] HOST PORT  - connect
nc [OPTIONS] -l -p PORT [HOST] [PORT]  - listen
-e PROG	Run PROG after connect (must be last)
-l	Listen mode, for inbound connects
-lk	With -e, provides persistent server
-p PORT	Local port
-s ADDR	Local address
-w SEC	Timeout for connects and final net reads
-i SEC	Delay interval for lines sent
-n	Don't do DNS resolution
-u	UDP mode
-v	Verbose
-o FILE	Hex dump traffic
-z	Zero-I/O mode (scanning)
2. testCert
* IPv6 address should be in "[]"
* CA bundle verification takes a long time, usually 100+ second on Kind or Jenkins. Increase interval to 20 second.
=> [IPv6] E2e bug fixes

docs/cookbooks/multus/README.md, docs/getting-started.md, docs/maintainers/getting-started-gif.md, pkg/agent/flowexporter/connections/connections.go, pkg/agent/util/sysctl/sysctl_linux.go
To show the latest version of Antrea (v0.10.0) and avoid using Kind as
the example cluster (confusing because Kind requires a different Antrea
YAML manifest).
Also fix a few typos I found over the last couple of weeks.
=> Refresh gif image in getting-started.md

pkg/agent/agent.go, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go
If MTU is too large for IPv6 environment, large packet with overhead 
IPv6ExtraOverhead, 20 is from observation of IPv4 and IPv6 packets under same situation.
=> [IPv6] adjust MTU for IPv6 overhead

.github/workflows/golicense.yml
The golicense workflow makes a lot of Github API calls and very often
runs into the limit for Github actions (1,000) which slows down the
workflow considerably and may even impact other workflows.
This enables caching for the workflow, using a hash of all the go.sum
files for the repo as the cache key, to avoid running the golicense tool
unless it is necessary. However, we always build the binary assets, as
this workflow is also meant to verify that
hack/release/prepare-assets.sh is not broken.
Fixes #1303
=> Cache licensing info about dependencies in golicense workflow

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, test/e2e/antreapolicy_test.go
This causes validation errors in ClusterNetworkPolicies when egress rules are specified. In addition to the fix to validation also
re-enable Antrea NetworkPolicy e2e tests.
=> Fix indentation of egress field in ACNP yamls

README.md, docs/antrea-network-policy.md, docs/architecture.md, docs/eks-terraform.md, docs/feature-gates.md, docs/getting-started.md, docs/ovs-pipeline.md
Add introductions and doc links of different features.
Rename cloud.md to eks-terraform.md, and network-policy.md to
antrea-network-policy.md.
=> Add introductions of features to getting-started and architecture docs

test/e2e/README.md, test/e2e/connectivity_test.go, test/e2e/fixtures.go, test/e2e/framework.go
Fixes #1226
Add log collection for antrea-agent pods when antrea is redeployed. This PR would lead to following behavioral change -  
If the user provides a log directory which was used for a previous run, existing contents (subdirectories for each test case) will be overridden.
To give overview of dir tree, running tests for TestIPSecTunnelConnectivity & TestPodConnectivityDifferentNodes (e2e) with `--logs-export-on-success` would result in the following dir tree -
```
── TestIPSecTunnelConnectivity
│   ├── beforeRedploy.Sep22-09-31-52
│   │   ├── k8s-node-master-antrea-agent-vnmwb-describe
│   │   ├── k8s-node-master-antrea-agent-vnmwb-logs
│   │   ├── k8s-node-worker-1-antrea-agent-kr9v4-describe
│   │   ├── k8s-node-worker-1-antrea-agent-kr9v4-logs
│   │   ├── …
```
=> collect all antrea-agent pod logs before redeploying antrea - e2e tests

build/images/ovs/Dockerfile, build/images/scripts/start_ovs, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
Install logrotate in the OVS Docker image.
Enhance start_ovs to run logrotate against the OVS log files in
/var/log/openvswitch/ every hour, with two flags:
--log_file_max_num and --log_file_max_size to specify the maximum
number and maximum size of log files respectively.
Update the Antrea deployment YAMLs to set the default value of
--log_file_max_num to 4, and the default value of --log_file_max_size
to 100MB.
Fixes: #1328
=> Use logrotate to rotate OVS log files

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml, docs/antctl.md, pkg/agent/apiserver/apiserver.go, pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/command_list.go, pkg/apiserver/apiserver.go, pkg/apiserver/handlers/loglevel/handler.go, pkg/log/log_level.go
Add antctl log-level command that calls controller or agent /loglevel
API to get/set the log verbosity level of controller or agent in the
runtime.
Change antctl to allow an empty response of an controller or agent
call.
=> Support get/set log verbosity level by antctl and controller/agent API

docs/security.md
At the moment, the document discusses how to restrict access from Pods
to the OVSDB file persisted on each Node's filesystem.
=> Start document with security recommendations

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
If the AntreaPolicy feature gate is not enabled on the Antrea Agent but
is enabled on the Antrea Controller (e.g. due to misconfiguration, or
Controller/Agents have not been all restarted after a configuration
change), Agent might crash with a segment fault when receiving and
processing ANP or ACNP messages from controller, so this commit adds
a check in Agent NetworkPolicyController to ingnore ANP and ACNP
messages when AntreaPolicy is not enabled.
=> Check and ignore ANP and ACNP in agent when AntreaPolicy is not enabled

.github/workflows/lifecycle_management.yml
Because of this issue: https://github.com/actions/stale/issues/173,
which is preventing the removal of the stale label when the issue
receives a new comment.
This commit also increases operations-per-run to 200, since we are
starting to have a decent amount of open issues and it seems we keep
running into the current limit (30).
=> Hardcode Github action actions/stale version to v3.0.8

.github/workflows/kind.yml, build/yamls/antrea-prometheus-rbac.yml, ci/kind/kind-setup.sh, ci/kind/validate-metrics-doc.sh, docs/code-generation.md, docs/prometheus-integration.md, hack/generate-manifest.sh, hack/make-metrics-doc.sh
Add the list of metrics which are exposed by Antrea agent and controller
in the integration doc for reference.
The metric list and descriptions added were pulled out of the metrics help strings from the code.
=> Document Antrea component metrics

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, test/e2e/antreapolicy_test.go
Update yaml to ensure appliedTo and Priority is required for ACNP as is the case with ANP. Add an e2e test to validate this
scenario.
=> Ensure appliedTo and priority is required for ACNP

docs/antrea-network-policy.md
Document available kubectl commands for Antrea NetworkPolicy CRDs and consistently use the terms ACNP and ANP as short
names.
=> Add kubectl commands to network policy docs

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, build/images/ethtool/Dockerfile, build/images/ethtool/README.md, ci/kind/config-2nodes.yml, ci/kind/config-3nodes.yml, ci/kind/kind-setup.sh, docs/kind.md
From v0.7.0 (K8s v1.17.0) to v0.9.0 (K8s v1.19.1).
In Kind v0.8.0, the default docker network for Nodes changed to "kind"
(user-defined docker bridge) instead of the default docker bridge
(docker0). Because of this, the kind-setup.sh script has to be updated
to use a different prefix ("kind-*" -> "antrea-*") when creating
additional user-defined bridges. We recommend that users of this script
delete their existing clusters and upgrade their Kind version to v0.9.0
before creating new clusters. The script should keep working with Kind
v0.7.0, but some manual clean-up of docker networks may be necessary for
existing clusters when using Antrea modes other than the default
"encap".
=> Upgrade the Kind version used for CI

go.mod, go.sum, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go
1. Bump up ofnet versions to support configuring 0 as Cookie Mask.
2. Change the implementation in OpenFlow control interface to support
setting 0 as Cookie mask.
3. Add support to set mask for matching ct_mark.
Fixes #1289
=> Add enhancement for OpenFlow control interface

test/e2e/framework.go, test/e2e/ipsec_test.go
* With OVS v2.14.0, IPsec in IPv6 envinronment is not supported.
* More user-friendly output for PodIPs.
From:
`Retrieved all Pod IPs: map[test-pod-0-upgp1ung:0xc000708960 test-pod-1-pbva9007:0xc0006ec8a0]`
To:
`Retrieved all Pod IPs: map[test-pod-0-mudzj847:IPv6: fd74:ca9b:172:16::4, IP strings: fd74:ca9b:172:16::4 test-pod-1-apcmyd30:IPv6: fd74:ca9b:172:16:1::3c, IP strings: fd74:ca9b:172:16:1::3c]`
=> [IPv6] Skip IPsec e2e test

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/types/networkpolicy.go
This PR aims to improve the efficiency of registering Antrea-native policy priorities in the OpenFlow priority space. Fundamental idea is to take advantage of the fact that, when the agent receives internal NP created for those policies, it already knows the number of absolute consecutive Priorities that needs to be registered. Those Priorities will have the same Tier and Policy priority, and consecutive rule priorities as they correspond to the 1st, 2nd, and etc. rules of the ingress/egress rule of that policy.
Thus, when registering priorities, we can break these priorities into zones (each zone of same Tier and Policy priority), and register each zone in batch. This eliminates the problematic scenario where asynchronously registering a series of priorities cause existing priorities to …
=> Register consecutive priorities in batch

plugins/octant/cmd/antrea-octant-plugin/traceflow.go
antrea-octant-plugin sets Traceflow TCP flag 2
by default for Traceflow creation.
Related: #1376
=> Set Traceflow TCP flag from antrea-octant-plugin

pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go
Use consistent function names in networkpolicy controller unittest
Other functions in the networkpolicy controller unittest use 'new' as a prefix  so getNetworkPolicyWithMultipleRules should have the same naming convention.
=> Use consistent function names in networkpolicy controller unittest

ci/jenkins/test-vmc.sh
The script in #1377 cleans up too much namespaces, including those related to CAPV (Cluster API Provider vSphere). This PR fixes this bug by adding a label filter to the current `kubectl get ns` command.
=> Add label filter for antrea-ci garbage cleanup job

ci/cluster-api/vsphere/templates/cluster.yaml, ci/jenkins/README.md, ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh
In this patch, we add a weekly Jenkins job which covers the combinations of specific OSs (CentOS 7, Photon 3) and K8S versions (v1.17.5, v1.18.2) and runs Antrea E2E, K8S Conformance and NetworkPolicy tests under each combination.
Will merge after #1240 is merged.
=> Add weekly matrix test for Antrea-CI 

test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/e2e/proxy_test.go
Read feature gate status instead of indirect checking to
determine whether a feature is enabled.
=> Retrieve featuregate status in e2e tests

build/yamls/base/agent.yml, docs/security.md, pkg/agent/route/route_linux.go
With L3 flows, Pod-to-Pod traffic will no longer go through gateway interfaces. For Pod-to-Service traffic, Linux doesn't allow sending redirect packets for NAT'd connections. Therefore, setting send_redirects is no longer needed.
For #1363
=> Cleanup: remove send_redirects sysctl configuration

test/e2e/fixtures.go, test/e2e/networkpolicy_test.go
2 upstream Network Policy tests didn't consider netmask for IPv6, this patch
is to add correct tests. When bug is fixed in latest release, these 2 tests can be deleted.
Kubernetes PR:
https://github.com/kubernetes/kubernetes/pull/93583
2 testcases
https://github.com/kubernetes/kubernetes/blob/v1.20.0-alpha.0/test/e2e/network/network_policy.go#L1365
https://github.com/kubernetes/kubernetes/blob/v1.20.0-alpha.0/test/e2e/network/network_policy.go#L1444
=> [IPv6] Add 2 Network Policy tests

pkg/ovs/openflow/ofctrl_action.go, test/integration/agent/openflow_test.go
1. Set IP protocol number according to the Service protocol type in "learn" flow.
2. Add integration test cases to ensure the flow is realized as expected.
Fixes #1395
=> Fix issue in UDP/SCTP Service flow in Antrea Proxy

.github/workflows/clair.yml, .github/workflows/go.yml, .github/workflows/golicense.yml, .github/workflows/integration.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, CONTRIBUTING.md, Makefile, build/images/Dockerfile.build.coverage, build/images/Dockerfile.build.ubuntu, build/images/Dockerfile.build.windows, build/images/Dockerfile.octant.ubuntu, build/images/codegen/Dockerfile, build/images/codegen/README.md, build/images/test/Dockerfile, ci/clair-scan/go.mod, ci/clair-scan/go.sum, docs/contributors/manual-installation.md, go.mod, hack/netpol/Makefile, hack/netpol/go.mod, hack/netpol/go.sum, hack/netpol/install.yml, hack/tidy-check.sh, hack/windows/Install-DevTools.ps1, plugins/octant/go.mod
This is long overdue since go 1.13 is no longer maintained.
I have already updated antrea/codegen:kubernetes-1.18.4 and the
generated code is not impacted by this change. No other Docker image
needs to be updated manually, they are all built / tested / pushed as
part of CI.
Not updating hack/netpol/ intentionally as this is still supposed to be
moved out of the repo in the medium-term.
Interestingly, Antrea Linux binaries are now smaller by a few MB, which
will reduce the Docker image size:
```bash
abas-a01:antrea abas$ GO=go-1.15 make bin
GOOS=linux go-1.15 build -o /Users/abas/vmware/antrea/bin  -ldflags ' -X github.com/vmware-tanzu/antrea/pkg/version.Version=v0.11.0-dev -X github.com/vmware-tanzu/antrea/pkg/version.GitSHA=fbb856fe -X …
```
=> Update from go 1.13 to go 1.15

docs/versioning.md
=> Document Antrea versioning

docs/antrea-network-policy.md
```
kubectl get tiers --sort-by=.spec.priority
NAME          PRIORITY   AGE
emergency     5          23h
securityops   50         23h
networkops    100        23h
platform      150        23h
application   250        23h
```
Related-Issue: #1388
=> Add kubectl example to sort Tiers by priority

Makefile
This PR updates the linting targets to include windows build tag. Fixes #1012
=> Extend linters to run for windows build tag. Fixes #1012

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, test/integration/agent/route_test.go
In the noEncap mode, if the cluster's Pod CIDR is routable in the Node
network, then SNAT is not required for the Pod egress traffic to the
Node or external network.
Resolves #1383
=> Add a config option to disable SNAT in the noEncap mode

build/images/scripts/start_ovs_ipsec, pkg/agent/agent.go
We cover the following cases:
* StrongSwan packages are not installed properly (that includes default
plugins): this check is enforced early on in start_ovs_ipsec; if it
fails, we will log a message and exit the container
* Missing antrea-ipsec container in antrea-agent Pod: this is fairly
unlikely unless someone is messing around with YAML manifests (and
somehow forgets that container while still defining the secret for
the PSK...); we perform this check by verifying that
/var/run/openvswitch/ovs-monitor-ipsec.pid exists
Tested both error cases manually.
Fixes #1392
=> Sanity checks for IPsec

docs/design/ovs-pipeline.md
Add the default flow to table 70.
Remove the flow of matching the global virtual MAC in table 80, which no
longer exists in the latest pipeline implementation.
=> Small updates of table 70 and 80 in ovs-pipeline.md

build/images/base/Dockerfile, build/images/scripts/install_cni, build/images/scripts/install_cni_kind, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-cni.conflist, build/yamls/offload/mellanox/antrea-crd.yml, build/yamls/patches/coverage/startAgentCov.yml, docs/configuration.md, docs/contributors/manual-installation.md, docs/design/architecture.md, docs/ovs-offload.md, test/e2e/bandwidth_test.go, test/e2e/fixtures.go, test/e2e/flowexporter_test.go, test/e2e/framework.go, test/e2e/proxy_test.go
The bandwidth plugin offered by the CNI plugin team can be used to
support ingress and egress traffic shaping for Kubernetes Pod, and
kubelet reads the bandwidth annotations on Pods and passes them as
parameters of CNI requests. To support traffic shaping in Antrea, the
bandwidth plugin should be appended to the chaining list of antrea cni
conf and its binary should be installed.
This patch does the above and adds an e2e test to ensure the integration
work as expected.
Closes #1413
=> Support Pod traffic shaping

hack/windows/Install-OVS.ps1
- Set OVS version after ovs-vswitchd started to ensure
the version can be setup during OVS installation.
- Fix log function not work issue.
Fixes:#1407
=> [Windows] Set OVS version after ovs-vswitchd started

docs/design/ovs-pipeline.md, pkg/agent/openflow/pipeline.go
After conversations with @jianjuns and @wenyingd.
Also fix some formatting issues in the OVS pipeline document, which
manifest themselves when generating the antrea.io website.
=> Improve documentation of gateway CT mark

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, docs/antrea-network-policy.md, hack/netpol/go.sum, pkg/apis/security/v1alpha1/types.go, pkg/controller/networkpolicy/validate.go
This PR add properties: name to each ingress or egreee rule of CRDs:
Add a name field at jsonPath:  .spec.ingress/egress[*].name to describe the intention of this rule
Fixes issue #1319
=> Add name of rule to CRDs

cmd/antrea-agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/route/testing/mock_route.go, pkg/agent/util/ipset/ipset.go, pkg/agent/util/iptables/iptables.go, test/integration/agent/route_test.go
For Geneve and VXLAN encapsulation packets, the request and response packets don't belong to a UDP connection so tracking them doesn't give the normal benefits of conntrack. Besides, kube-proxy may install great number of iptables rules in nat table. The first encapsulation packets of connections would have to go through all of the rules which wastes CPU and increases packet latency.
This patch installs iptables rules in raw table to skip tracking UDP encapsulation packets. The improvement is as below (tested with kube-proxy iptables mode):
- When no extra services are created, the Inter-Node Pod-to-Pod TCP_CRR can be increased from ~2600 to ~2800 TPS.
- When 4,000 services are created, the Inter-Node Pod-to-Pod TCP_CRR can be increased from ~1140 to ~2800 TPS, and the CPU usage of …
=> Do not track UDP encapsulation packets in host network

cmd/antrea-agent/agent.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/flowexporter/connections/conntrack.go, pkg/agent/flowexporter/connections/conntrack_linux.go, pkg/agent/flowexporter/connections/conntrack_linux_test.go, pkg/agent/flowexporter/connections/conntrack_ovs.go, pkg/agent/flowexporter/connections/conntrack_windows.go, pkg/agent/flowexporter/types.go, pkg/agent/openflow/pipeline.go, test/integration/agent/flowexporter_test.go
With Antrea Proxy enabled, Flow Exporter checks for ct_mark rather than
serviceCIDR for Pod-To-Service flows.
With Kube Proxy enabled, Flow Exporter ignores the duplicate
flow with ClusterIPs using podCIDR in nodeConfig for Pod-To-Service flows.
Fixes: #1369
=> Remove ServiceCIDR dependency in Flow Exporter

test/e2e/networkpolicy_test.go
@wenyingd Please remove these 2 `t.Skipf()` in your Network Policy IPv6 PR.
=> Skip 2 Network Policy testcases before Network Policy IPv6 is supported

pkg/antctl/raw/supportbundle/command.go
Make the antctl supportbundle command to support filter nodes by
Node name list or a file contains Node names.
E.g.:
```
Generate support bundles of agent on specific Nodes filtered by name list, no wildcard support
$ antctl supportbundle node_a node_b node_c
Generate support bundles of agent on specific Nodes filtered by names in a file (one Node name per line)
$ antctl supportbundle -f ~/nodenamelist
```
=> Implement antctl supportbundle Node name list support

ci/jenkins/test-vmc.sh
* "TEST SUCCESS" should appear only when test succeeds
* test_rc can be other than 0 and 1. Such result should be considered as failure.
=> [CI] Fix TEST_FAILURE judgement

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/openflow/pipeline.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/route/testing/mock_route.go, pkg/antctl/command_list.go, test/integration/agent/route_test.go
For a IPv6 cluster, the ipset of Node IPs needs to be inet6, this may introduce a few more code to maintain the NOTRACK rules. This patch removes the peer IP check to make the rule simpler and applicable to both IPv4 and IPv6.
-----------
@lzhecheng reported that the ipv6 branch would crash after rebasing on master:
```
ip6tables-restore v1.8.4 (legacy): The protocol family of set ANTREA-NODE-IP is IPv4, which is not applicable.
```
One fix is to add IPv6 family ipset if Node IP's IPv6, but I guess it would make it further from @jianjuns's expectation, so this patch removes the peer IP check to simplify it, assuming the tunnel UDP port in use won't be used for other purposes.
=> Remove peer IP check in NOTRACK rules

test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/e2e/utils/anpspecbuilder.go, test/e2e/utils/cnpspecbuilder.go, test/e2e/utils/networkpolicyspecbuilder.go
- Fixed logic flaws in policy builders, which cause logging to never actually be enabled in E2E tests
- Check the log dir on Antrea agent of the node where the ACNP appliedTo pod is scheduled on
- Moved audit logging testcase into its own subtest
=> Fix issues in E2E test for audit logging feature

docs/octant-plugin-installation.md
Update octant plugin installation guide and simplify
the steps to deploy octant and antrea-octant-plugin as a Pod.
=> Update octant plugin installation guide

docs/antrea-network-policy.md
Add `enableLogging` field to antrea-network-policy.md and describe its usage.
=> Document enableLogging field to Antrea-native policy doc.

.github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
Apparently Antrea accounts for most of the Github storage bill for the
vmware-tanzu organization. To address this, we:
* delete the Antrea docker images used as temporary artifacts at the
end of the workflow
* set a smaller retention period for all other artifacts (they are also
much smaller, so really this changed doesn't matter anywhere close to
as much as the previous one)
=> Reduce storage requirements for Github actions artifacts

pkg/apiserver/registry/networkpolicy/addressgroup/rest.go, pkg/apiserver/registry/networkpolicy/addressgroup/rest_test.go, pkg/apiserver/registry/networkpolicy/appliedtogroup/rest.go, pkg/apiserver/registry/networkpolicy/appliedtogroup/rest_test.go, pkg/apiserver/registry/networkpolicy/networkpolicy/rest.go, pkg/apiserver/registry/networkpolicy/networkpolicy/rest_test.go, pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest.go, pkg/apiserver/registry/stats/antreaclusternetworkpolicystats/rest_test.go, pkg/apiserver/registry/stats/antreanetworkpolicystats/rest.go, pkg/apiserver/registry/stats/antreanetworkpolicystats/rest_test.go, pkg/apiserver/registry/stats/networkpolicystats/rest.go, pkg/apiserver/registry/stats/networkpolicystats/rest_test.go, pkg/apiserver/registry/system/controllerinfo/rest.go, pkg/apiserver/registry/system/controllerinfo/rest_test.go
This patch makes all Antrea APIs respect label selector to fix the problem that some K8s clients get unexpected resources when labelSelector is specified.
Fixes #1432
=> Respect label selector

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, pkg/agent/flowexporter/connections/conntrack_linux_test.go
=> [IPv6] Fix issues

test/e2e/antctl_test.go
Current implementation doesn't support this e2e test in IPv6-only setup. Will support it later.
=> [IPv6] Skip TestAntctlProxy for IPv6

hack/windows/Install-OVS.ps1
This patch updates OVS installation script to:
- Set OVS services always restart on failure.
- Set ovs-vswitchd service depend on ovsdb-server service.
=> [Windows] Set OVS services always restart on failure

pkg/agent/agent.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/controller/traceflow/controller.go, pkg/ovs/openflow/interfaces.go, test/e2e/traceflow_test.go, test/integration/agent/openflow_test.go
This patch changes Traceflow dataplaneTag from tun_metadata0 to DSCP, and
removes the tunnel/encap mode restriction for inter-Node Traceflow.
This PR closes #1357
=> Use DSCP instead of tun_metadata0 in Traceflow

test/e2e/fixtures.go
Which is causing CI to fail (deadcode linter)
=> Remove unused function in e2e tests

Makefile, cmd/antrea-agent/options.go, cmd/antrea-agent/options_linux.go, cmd/antrea-agent/options_windows.go, cmd/antrea-agent/options_windows_test.go, pkg/features/antrea_features.go
During the agent config validation, checks if the enabled features are
supported on Windows, and if not fails the validation.
=> Check features not supported on Windows Nodes

pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/controller/networkpolicy/tier.go, pkg/controller/networkpolicy/validate.go, test/e2e/antreapolicy_test.go
This PR partially addresses #1362.
Scope of change:
- Add a new Tier named `baseline` which is generated by Antrea as an addition to the existing 5 pre-created tiers.
- Ensure that policy rules in the `baseline` tier will be enforced after K8s NetworkPolicies. This is done by creating the flows in the K8s Ingress/Egress default tables, below K8s default drop flow priority.
- Instead of splitting flows for default tier and other tiers in different tables, all flows in the 5 tiers enforced before K8s NetworkPolicies will be created in single table (45 for egress and 85 for ingress). This will address the performance concerns raised in https://github.com/vmware-tanzu/antrea/pull/1237#discussion_r492872510.
- Refactor the priorityAssigner to handle K8s default ingress/egress tables for the …
=> Add baseline Tier for Antrea-Native Policies

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/networkpolicy.go, pkg/agent/util/net.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/util/ip/ip.go, test/e2e/antctl_test.go, test/e2e/connectivity_test.go, test/e2e/networkpolicy_test.go, test/integration/agent/openflow_test.go
1. Add enhancement in Antrea Controller and Agent to support NetworkPolicy
in IPv6.
2. Optimize test cases to support IPv6
3. Use regex in CRD to validate IPv4 or IPv6 string
Due to absence of @wenyingd, this PR is to solve comments for PR #1272 .
=> [IPv6] Add IPv6 support for NetworkPolicy by @wenyingd

docs/windows.md, hack/windows/Clean-AntreaNetwork.ps1, hack/windows/Prepare-AntreaAgent.ps1, hack/windows/Prepare-ServiceInterface.ps1
1. Add a script `Prepare-AntreaAgent.ps1` to prepare env needed by
antrea-agent:
- Create network adapter needed by kube-proxy.
- Clean stale network resources created by antrea-agent.
2. Update Windows doc to guide how to use the script and highlight
that the script must be executed after a Windows Node is restarted.
Fixes: #1455
=> [Windows] Provide scripts/guide to prepare env needed by antrea-agent

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, pkg/agent/route/testing/mock_route.go, pkg/agent/util/iptables/iptables.go, pkg/agent/util/iptables/lock.go, pkg/agent/util/iptables/lock_test.go, test/integration/agent/cniserver_test.go, test/integration/agent/route_test.go
In large scale clusters, xtables lock may be hold by kubelet/
kube-proxy/ portmap for a long time, especially when there are many
service rules in nat table. antrea-agent may not be able to acquire the
lock in short time. If the agent blocks on the lock or quit itself, the
CNI server won't be running, causing all CNI requests to fail.  If the
Pods' restart policy is Always and there are dead Pods, container
runtime will keep retrying calling CNIs, during which portmap is called
first, leading to more xtables lock contention.
This patch makes iptables initialization error non fatal and uses a
goroutine to retry it until success. The agent will start the CNI server
anyway and handle the CNI Del requests but won't handle CNI Add requests
until the network is ready.
Fixes #1499
=> Make iptables initialization error non fatal

docs/prometheus-integration.md, pkg/agent/metrics/prometheus.go, pkg/controller/metrics/prometheus.go, test/e2e/prometheus_test.go
antrea_agent_runtime_info and antrea_controller_runtime_info are
deprecated since 0.10.0 release. Deleting them from 0.11.0 release.
=> Delete deprecated Prometheus metrics

cmd/antrea-agent/agent.go, go.mod, go.sum, pkg/agent/controller/networkpolicy/allocator.go, pkg/agent/controller/networkpolicy/allocator_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/stats/collector.go, pkg/agent/stats/collector_test.go, pkg/querier/querier.go, pkg/querier/testing/mock_querier.go, plugins/octant/go.sum
This is for services such as networkPolicy stats, flow exporter,
traceflow etc. to query networkPolicy/networkPolicyRule using
rule flow ID (also tagged as ruleOfID in pkg/agent/openflow).
We delete the rules asynchronously after a delay as the above mentioned
services would need the info of network policy rule even after its
deletion. The allocated ID (allocator.go) will not be released until the rule is deleted
from asyncRuleCache.
We provide the interface to this query in AgentNetworkPolicyInfoQuerier.
Fixes #1270
=> Add asyncRuleCache to idAllocator in Antrea Agent

build/yamls/elk-flow-collector/logstash/ipfix.yml, docs/network-flow-visibility.md, go.mod, go.sum, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, plugins/octant/go.sum
This PR will update Antrea according to go-ipfix v0.2.4 release.
Fixes #1448 and #1417
=> Upgrade to go-ipfix v0.2.4

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go
PodCIDRs can be released from deleted Nodes and allocated to new Nodes.
For server side, it won't happen that a PodCIDR is allocated to more
than one Node at any point. However, for client side, if a resync
happens to occur when there are Node creation and deletion events, the
informer will generate the events in a way that all creation events come
before deletion ones even they actually happen in the opposite order on
the server side. Therefore, a PodCIDR may appear in a new Node before
the Node that previously owns it is removed.
To ensure the stale routes, flows, and relevant cache of this podCIDR
are removed appropriately, we wait for the Node deletion event to be
processed before proceeding, or the route installation and
uninstallation operations may override or conflict with each …
=> Fix missing routes caused by Node events coming out of order

pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/packetin_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_flow.go, pkg/ovs/openflow/ofctrl_flow_test.go, pkg/ovs/openflow/testing/mock_openflow.go
This PR added 3 major changes:
1. Mirror existing Antrea NetworkPolicy drop flows with action=controller when running TF
2. Collect drop table and rule when PacketIn
3. Add dropFlag into ofFlow struct to identify if the flow contains drop action
This PR closes #1225
=> Support Antrea NetworkPolicy in Traceflow

build/images/base/Dockerfile, build/images/scripts/install_cni, build/images/scripts/install_cni_kind
To fix a performance issue that portmap performs expensive iptables
operations even no portMappings are configured.
Upstream fix: https://github.com/containernetworking/plugins/pull/509/commits/877602d6276eaabac480f589deccb41b2faccb20
Fixes #1499
=> Bump up portmap version to v0.8.7

.github/workflows/go.yml, .github/workflows/kind.yml, Makefile, build/images/Dockerfile.build.coverage, ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh, ci/kind/test-e2e-kind.sh, cmd/antctl/bincover_run_main_test.go, codecov.yaml, pkg/agent/agent.go, test/e2e/antctl_test.go, test/e2e/framework.go, test/e2e/main_test.go, test/e2e/networkpolicy_test.go
Add coverage support for conformance and antctl
This PR made the below changes:
Add coverage support for antctl:
1. generates an instrumented binary for antctl
2. if coverage is enabled, run antctl instrumented binary
antctl-coverage for antctl cmds. When the cmds finish,
generate a coverage file for antctl.
3. when all e2e tests finish, copy the antctl coverage files out.
Add coverage support for running conformance test:
1. after run conformance tests using sonobuoy on instrumented binary
for antrea-controller and antrea-agent, collect coverage files
for them and copy them to coverage directory.
=> Add coverage support for conformance and antctl

cmd/antrea-agent/agent.go, pkg/agent/controller/networkpolicy/allocator.go, pkg/agent/controller/networkpolicy/allocator_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/flowexporter/connections/conntrack_linux.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/types.go, pkg/agent/stats/collector.go, test/e2e/flowexporter_test.go, test/e2e/performance_test.go, test/integration/agent/flowexporter_test.go
Network policy info (name and namespace), both ingress and egress
policies are added.
Async rule cache in idAllocator is configured with asyncDeleteInterval that is maximum of either 5s or configured flowPollInterval in Antrea Agent.
=> Add network policy info to IPFIX flow records as part of Flow Exporter

docs/network-flow-visibility.md
As Flow Exporter supports adding network policy information,
we need to update the user doc.
=> Update the network flow visibility doc

test/e2e/bandwidth_test.go
See https://github.com/vmware-tanzu/antrea/issues/1543
=> Skip TestPodTrafficShaping on v6 clusters

.github/workflows/kind.yml, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/base/conf/antrea-controller.conf, build/yamls/windows/base/conf/antrea-agent.conf, ci/jenkins/test-vmc.sh, ci/kind/kind-setup.sh, ci/kind/test-e2e-kind.sh, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, cmd/antrea-controller/config.go, cmd/antrea-controller/options.go, docs/feature-gates.md, hack/generate-manifest.sh, pkg/agent/openflow/pipeline.go, pkg/features/antrea_features.go, test/e2e/infra/vagrant/push_antrea.sh, test/e2e/proxy_test.go, test/e2e/traceflow_test.go
* AntreaProxy
* Traceflow
* Prometheus metrics (not controlled by a feature gate but by a boolean
config parameter, which now defaults to 'true')
This change required a few modifications to some of our test scripts.
=> Graduate some features from Alpha to Beta

docs/os-issues.md, test/e2e/bandwidth_test.go, test/e2e/fixtures.go
Egress traffic shaping is not supported because of a missing Kernel
module (ifb), which is required by the bandwitdh CNI plugin.
This change also updates TestPodTrafficShaping to skip the test if some
of the required Kernel modules for traffic shaping are missing.
Fixes #1516
=> Document lack of support for Pod traffic shaping on Photon OS 3

Makefile, ci/docker-registry, ci/jenkins/jobs/macros.yaml, ci/jenkins/test-vmc.sh, ci/kind/test-e2e-kind.sh, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/performance_test.go, test/e2e/proxy_test.go
Due to rate limit of dockerhub, it is necessary to use VMware-hosted public Harbor registry (projects.registry.vmware.com) in CI. Also Use registry in e2e tests.
=> [CI] Use VMware-hosted public Harbor registry in VMC CI

test/e2e/README.md
Add details on running the e2e tests on a kind cluster
with the local Antrea image.
Felt these additional details in the documentation for dev process on kind cluster.
=> Update documentation for e2e tests on kind cluster

pkg/controller/networkpolicy/mutate.go, pkg/controller/networkpolicy/tier.go, pkg/controller/networkpolicy/validate.go, test/e2e/antreapolicy_test.go
=> Mutate empty Tier set in Antrea-native policies to default tier

pkg/agent/openflow/client.go
This PR fixes #1572 
arpResponderStaticFlow is changed to be installed only in IPv4 mode by #1518, since 'ARP uses broadcast, but IPv6 doesn't support broadcast' https://github.com/vmware-tanzu/antrea/pull/1272#discussion_r508149290.
However, IsIPv4Enabled() is determined by `c.nodeConfig.PodIPv4CIDR != nil` (pkg/agent/openflow/client.go#L827), and in `pka/agent/agent.go`, when networkpolicy-only mode is true, setting nodeConfig.PodIPv4CIDR is skipped:
```	
if i.networkConfig.TrafficEncapMode.IsNetworkPolicyOnly() {
return nil
}
// Parse all PodCIDRs first, so that we could support IPv4/IPv6 dual-stack configurations.
if node.Spec.PodCIDRs != nil {
for _, podCIDR := range node.Spec.PodCIDRs {
_, localSubnet, err := net.ParseCIDR(podCIDR)
if err != nil {
klog.Errorf("Failed to parse subnet …
```
=> Fix ARP flow not installed issue in networkpolicy-only mode

pkg/controller/networkpolicy/endpoint_querier_test.go
500ms is not long enough to ensure all computation is done.
=> Fix flaky unit test TestLargeScaleEndpointQueryManyPolicies

pkg/controller/networkpolicy/validate.go
Refactor the validate functions to standardize their signature such that new validate functions for resource events can be added
and appended to the list without much disruption to the code.
New validation functions must be in the specified signature for the corresponding CRUD event and then registered to
the respective validator of the resource.
=> Refactor validate.go for Antrea-native policy and Tier validation

build/images/scripts/start_ovs
The default value (500ms) causes a K8s upstream conformance test to fail
and may increase the risk of users reporting issues if they think
SessionAffinity is not implemented properly. Of course there is still a
delay before a learned flow is installed in the datapath flow cache and
takes effect, but the delay is at least smaller now. This delay cannot
be avoided when using the learn action.
Reducing the delay to 200ms may have an impact on performance with a
large number of datapath flows. Hopefully this impact is not
significant. There are other measures we could investigate if we notice
performance issues (e.g. reduce the max-idle delay for cached datapath
flows to reduce the size of the cache).
Fixes #1583
=> Set OVS max revalidator delay to 200ms

build/yamls/antrea-eks-node-init.yml, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh, cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/config/node_config.go, pkg/agent/openflow/client.go, pkg/agent/querier/querier.go, pkg/agent/querier/testing/mock_querier.go, pkg/agent/route/route_linux.go, pkg/support/dump_others.go
policyOnlyMode was broken since adding support for IPv6 clusters in the
code base. This is because the code used the Node's PodCIDR(s) to
determine which address family was supported, which doesn't work in
policyOnlyMode, for which IPAM is not the responsibility of Antrea.
Instead we now use the following rules:
* if there is an IPv4 PodCIDR for the Node, then v4 is supported
* otherwise, if policyOnlyMode is used and the Node's IP address
(primary, as reported by K8s) is an IPv4 address then v4 is supported
Same rules for v6.
This may not work for dual-stack, but IIRC none of the cloud services
support IPv6 / dual-stack. There are also other issues for dual-stack
support in Antrea, which themselves depend on upstream issues.
Additionally, we include the following changes:
* the …
=> Fix policyOnlyMode and cloud support for AKS & EKS

.github/workflows/kind_upgrade.yml, ci/kind/test-upgrade-antrea.sh, pkg/apis/controlplane/v1beta1/conversion.go, pkg/apis/controlplane/v1beta1/conversion_test.go, pkg/apis/controlplane/v1beta1/zz_generated.conversion.go, test/e2e/networkpolicy_test.go, test/e2e/upgrade_test.go
To be backwards compatible, AddressGroup v1beta1 must not include
PodReferences in its members, otherwise the agents that use v1beta1 will
think the members have changed and will add new IPs to the openflow
entries of relevant NetworkPolicies and delete old IPs from them, while
the old IPs and new IPs are actually the same. In current
implementation, deleting old IPs is executed after adding new IPs, so it
leads to some IPs missing in the openflow entries.
Fixes #1587
=> Remove the pod reference in v1beta1 AddressGroup

pkg/agent/agent.go, pkg/agent/agent_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, test/integration/agent/cniserver_test.go, test/integration/agent/openflow_test.go
Some of these funcs take NodeConfig attributes and OFPort constants as
input arguments, while some directly read NodeConfig or use OFPort
constants.
This commit changes all Openflow client funcs to be consistent and
do not require extra arguments for NodeConfig attributes and OFPort
constants.
=> Remove unnecessary arguments of Openflow client funcs

docs/network-flow-visibility.md
Resources required for elk-flow-collector deployment should match
the deployed version of Antrea.
There was some confusion for users who were trying FlowExporter feature using elk-flow-collector.
=> Improve network flow visibility doc

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh
This PR fixes #936.
The cloud e2e tests on Jenkins (AKS, EKS and GKE) now supports using arbitrary branch/commit of Antrea in any fork (defaults to upstream/master) for conformance test. A manual run of such test can be triggered by Jenkins admin.
Each job will now checkout the specified Antrea repo, build the Antrea image and load it to each cloud Node via ssh, before deploying corresponding Antrea yml.
All three cloud platforms have been manually tested and verified that the Antrea image run is the specified one.
Some minor changes:
- `<projectantrea-dev@googlegroups.com>` has been added to the notification list for each test job and cleanup job.
- Preview feature `Node Public IP` has been enabled in AKS for easier scp/ssh to the cluster Nodes when delivering Antrea image. …
=> Support using arbitrary Antrea image to trigger Cloud CI

docs/antctl.md, docs/antrea-network-policy.md, pkg/agent/apiserver/handlers/networkpolicy/handler.go, pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/command_definition_test.go, pkg/antctl/transform/addressgroup/transform.go, pkg/antctl/transform/appliedtogroup/transform.go, pkg/antctl/transform/controllerinfo/transform.go, pkg/antctl/transform/networkpolicy/transform.go, pkg/antctl/transform/utils.go, pkg/antctl/transform/version/transform.go, pkg/controller/networkpolicy/antreanetworkpolicy_test.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/tier.go
This PR aims to solve #1388 
- Adds an option --sort-by=effectivePriority for `antctl get networkpolicy`, which sorts the Antrea internal controlplane NetworkPolicy objects by the order in which they are evaluated.
- `antctl get networkpolicy` displays tier priority and policy priority by default
=> Add sort-by effectivePriority for antctl get networkpolicy

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Let the packets to the tunnel port go through L2ForwardingCalcTable
as well, to be consistent with other types of traffic.
Redirect packets to gateway and tunnel, as well as BUM packets to
conntrackCommitTable and bypass ingress NetworkPolicy enforcement.
=> Change L2 forwarding flows for traffic to gateway and tunnel

test/e2e/infra/vagrant/playbook/roles/common/tasks/busybox.yml, test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml
Using string comparsion may cause trouble in version check. For instance, I have `ansible 2.10.3` on my laptop and caused 
```
TASK [common : Checking that Ansible version >= '2.4.0'] ***********************
fatal: [k8s-node-master]: FAILED! => {
"assertion": "ansible_version.full >= \"2.4.0\"",
"changed": false,
"evaluated_to": false,
"msg": "Assertion failed"
}
```
when runing `./infra/vagrant/provision.sh`
=> fix ansible version check

hack/api-reference/gen-config.json, hack/api-reference/generate-api-reference.sh, hack/api-reference/template/members.tpl, hack/api-reference/template/pkg.tpl, hack/api-reference/template/type.tpl
Generated documentation is then included on the Antrea website.
The script relies on a slightly modified version of
https://github.com/ahmetb/gen-crd-api-reference-docs. It doesn't require
running an actual apiserver, instead it uses the Go source files
directly.
=> Add hack script to generare reference docs for the Antrea API

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml, ci/run-k8s-e2e-tests.sh, ci/test-conformance-eks.sh
- Add default repo url and branch parameters for cleanup jobs
- Separate test job template and cleanup job template
- Modify EKS test script to be compatible with a recent command line option change in run-k8s-e2e-test.sh
=> Fix issues in cloud CI

pkg/agent/controller/networkpolicy/allocator_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/reconciler_test.go, test/e2e/flowexporter_test.go
Changed the name from TestWorker to TestIDAllocatorWorker
Fixes #1546
=> Fix the flaky test TestWorker in idAllocator

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go
Before the commit, ofPort number is used to decide whether NetworkPolicy
ingress tables should be bypassed after l2ForwardingCalcTable - when
the output ofPort is DefaultTunOFPort or HostGatewayOFPort, the flow
will go to conntrackCommitTable and such bypass the ingress rule tables.
However, in the noEncap and networkPolicyOnly modes, the default tunnel
port is not created on the bridge, and DefaultTunOFPort can be used by
a Pod's OVS port, so the implementation might mistakenly bypass ingress
rule enforcement for traffic to the Pod.
This commit fixes the problem by letting the callers decide whether or
not to bypass ingress rule tables.
=> Fix next table decision of l2ForwardingCalcTable

test/e2e/traceflow_test.go
inter-Node Traceflow test should be skipped in Kind because of a know
issue when using Geneve with the userspace OVS datapath, However, the
logic for skipping was incorrectly added to the intra-Node test instead
of the inter-Node one.
The commit also removes comments describing the list of Traceflow test
cases: the comments were out-of-date and not convenient to keep in sync
with the actual test cases. The name of each test case should be a
sufficient description of what the test is doing.
=> Fix in Traceflow e2e test

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, test/e2e/antreapolicy_test.go, test/e2e/infra/vagrant/playbook/roles/common/tasks/docker.yml, test/e2e/networkpolicy_test.go
This PR fixes #1599. The test added would successfully collect dropped packet from AntreaNetworkPolicyStat because the agent is not crashed after the fix
=> Fix AntreaNetworkPolicyStats with drop action

pkg/agent/flowexporter/connections/conntrack.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go
This information will be useful as it is not available through
servicePortName (it contains only the port name).
Added some miscellaneous fixes that were removed as part of IPv6 branch merging with master.
PS: This is a simple change that is missing in the master too. The intermediate process added destinationServicePort as one of the correlated fields, so created PR against feature/flow-aggregator branch.
=> [Flow-aggregator]Support destination service port field in Flow Exporter

.github/workflows/build.yml, .github/workflows/build_tag.yml, .github/workflows/go.yml, .github/workflows/kind.yml, .github/workflows/upload_release_assets.yml, Makefile, build/images/flow-aggregator/Dockerfile, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/conf/flow-aggregator.conf, build/yamls/flow-aggregator/base/flow-aggregator.yml, build/yamls/flow-aggregator/base/kustomization.yml, build/yamls/flow-aggregator/patches/dev/imagePullPolicy.yml, build/yamls/flow-aggregator/patches/release/.gitignore, cmd/flow-aggregator/config.go, cmd/flow-aggregator/flow-aggregator.go, cmd/flow-aggregator/main.go, cmd/flow-aggregator/options.go, hack/generate-manifest-flow-aggregator.sh, hack/release/prepare-assets.sh, pkg/flowaggregator/flowaggregator.go
This is the first PR of flow aggregator implementation, which only contains the build system and structure of it, including the yaml files, github workflow changes and command line tools. For the main logic of flow aggregator, please take a look at this PR (https://github.com/vmware-tanzu/antrea/pull/1596).
=> [Flow-Aggregator] Implementation of flow aggregator build system and structure

pkg/agent/openflow/network_policy.go, pkg/agent/openflow/network_policy_test.go, pkg/agent/openflow/pipeline.go
When traceflow is being executed, there are other flows in metrics
tables, causing the function parseMetricFlow panic. We should filter out
all other flows.
For #1614
Depends on #1606, otherwise unit test will fail.
=> Fix metrics flow parsing error caused by traceflow flows

pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/status_controller.go, pkg/controller/stats/aggregator.go, pkg/controller/traceflow/controller.go, pkg/monitor/controller.go
Use WaitForNamedCacheSync instead of WaitForCacheSync when possible, as
recommended by the K8s documentation. This leads to code which is
slightly less verbose. When we wrote the first controllers for Antrea,
we used a version of client-go which did not have WaitForNamedCacheSync
yet.
=> Minor code cleanup in controllers

build/images/codegen/Dockerfile, hack/update-codegen-dockerized.sh
https://github.com/vmware-tanzu/antrea/pull/1420 updated the version of
Go used in the Antrea build infra from 1.13 to 1.15, including the
version of Go used in the antrea/codegen Docker image. However, an
updated codegen image was never pushed to the Dockerhub registry. It
turns out that an additional change was required in the image, caused by
a change of behavior in Go vendoring introduced in Go 1.14.
This is also the opportunity to update the version of mockgen (which
does not cause any change in the generated code).
=> Necessary change in codegen image after update to Go 1.15

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, Makefile, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea-octant.yml, build/yamls/antrea-windows.yml, build/yamls/antrea.yml, build/yamls/patches/coverage/startAgentCov.yml, build/yamls/patches/coverage/startControllerCov.yml, ci/jenkins/test-vmc.sh, ci/jenkins/test.sh, ci/kind/kind-setup.sh, ci/kind/test-e2e-kind.sh, ci/kind/test-upgrade-antrea.sh, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh, docs/kind.md, hack/generate-manifest-octant.sh, hack/generate-manifest-windows.sh, hack/generate-manifest.sh, hack/netpol/test-kind.sh, hack/release/prepare-assets.sh, test/e2e/README.md, test/e2e/infra/vagrant/push_antrea.sh
All "user-facing" images (antrea/antrea-ubuntu, antrea/antrea-windows,
antrea/octant-antrea-ubuntu) are now pulled from the VMware Harbor
distribution registry (projects.registry.vmware.com) to avoid Docker
pull rate limiting.
The YAML manifests (top-of-tree and releases) now refer to the new
registry.
This is not a complete transition from Dockerhub to Harbor. Images used
for build purposes (e.g. antrea/openvswitch) are still pulled from
Dockerhub by default. Rate limiting is not as much of an issue for these
(not user-facing, Github workflows are not subject to rate limiting, we
have workarounds for the Jenkins CI jobs). One thing to keep is mind is
that we cannot push to the VMware Harbor registry from outside of the
the VMware corporate network. This is why all images are pushed to …
=> Switch to VMware Harbor registry for Antrea Docker images

Makefile
Missing Docker tag after switching to projects.registry.vmware.com
registry.
=> Fix CI cloud scripts

Makefile, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/flow-aggregator.yml, hack/generate-manifest-flow-aggregator.sh, hack/release/prepare-assets.sh
Changes are the same as in
https://github.com/vmware-tanzu/antrea/pull/1617 but for the
antrea/flow-aggregator Docker image.
There was also a typo in the flow-aggregator YAML: the image key didn't
match the one used in generate-manifest-flow-aggregator.sh when invoking
kustomize.
=> Use VMware Harbor registry for flow-aggregator Docker image

pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/client.go, test/e2e/traceflow_test.go
This PR fixes two bugs:
1. When destination Service is set, the actual tcpFlags is set to 0 if tcpHeader exists with tcpFlags=0 or not set, which should be forced set to 2.
2. When CNP/ANP drop rule exists, Traceflow cannot generate OVS flows properly.
=> Fix wrong TCP flags and CNP flows in Antrea Traceflow

ci/jenkins/test.sh, test/e2e/basic_test.go
* In Windows test, antrea repo on master will be copied to Windows node to build.
Before, Windows node builds with wrong code possibly.
* Allocate 50 min for e2e tests
* Fix wrong spelling
=> [CI] Fix issues

docs/octant-plugin-installation.md, plugins/octant/cmd/antrea-octant-plugin/main.go
Use default location of kubeconfig (~/.kube/config) for antrea-octant-plugin
when $KUBECONFIG is not set.
=> Add default value of kubeconfig for antrea-octant-plugin

pkg/apis/ops/v1alpha1/types.go, pkg/graphviz/traceflow.go
Add destination pod name & IP in load balancing stage when destination is a service. 
Example graph:
=> Update traceflow graph message for service destinations

pkg/agent/agent_windows.go, pkg/agent/util/net_windows.go
Do not remove the NetIPAddress on br-int anymore to avoid the
"No matching MSFT_NetIPAddress objects found" issue because the
NetIPAddress may not exist on br-int.
Instead, always try to configure NetIPAddress on the interface
and ignore the "MSFT_NetIPAddress already exists" error.
Fixes: #1644
=> [Windows] Fix br-int NetIPAddress not found issue

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_test.go, pkg/agent/flowexporter/exporter/exporter.go, test/e2e/framework.go
Agent side changes for Flow Aggregator
With this PR, if FlowExporter feature is enabled and flowCollectorAddr
can be used to take in as input address for both flow aggregator and external flow collector.
We resolve the flow aggregator IP using the static DNS name: "flow-aggregator.flow-aggregator.svc".
Default for flowCollectorAddr is "flow-aggregator.flow-aggregator.svc:tcp"
In addition, modified antrea-agent base manifest to set appropriate
DNS policy.
This is dependent on PR #1596 and will be merged after it. Please look for the latest commit.
=> [Flow-Aggregator] Agent side changes for Flow Aggregator

.github/workflows/build.yml
A tiny change in github workflow to push flow aggregator image before PRs merged in the master branch. 
This is a temporary solution to unblock the e2e test PR, will remove this change later.
=> Push image of flow aggregator in feature branch

pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go
This PR is a follow-up fix for #1636 
When bumping go-ipfix to v0.4.2, several new template fields of stats are introduced. Exporting process in flow aggregator will log errors when having sanity check since field count does not match for template and data, which causes e2e tests to fail. Adding template fields of stats will solve that problem. 
Tested with @dreamtalen on this fix.
=> [Flow-Aggregator] Add template fields of stats

ci/kind/test-e2e-kind.sh, pkg/agent/flowexporter/connections/connections.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
In this commit, we add e2e tests for the flow aggregator. For these tests, we setup an environment where the flow exporters in antrea agents export flow records to the flow aggregator. The flow aggregator will run the collecting, aggregating jobs and will export records to the external IPFIX collector.
The existing "flow exporter" tests (where the agents export to the external collector directly) are replaced with "flow aggregator" tests, as we assume that the aggregator is always deployed.
Also, we removed the configuration in the agents causing flow records to only be exported from the source node since we now have the aggregator to correlate and de-duplicate flows. Related commit and PR are b44fd78, #1268.
=> [Flow-Aggregator] Add e2e tests for flow aggregator

pkg/agent/controller/networkpolicy/reconciler.go, pkg/agent/controller/networkpolicy/reconciler_test.go
The reconciler might fail to install flows due to transient OVS error. It should add the IPBlocks to the PolicyRule when it retries, in which case "update" method is called. This patch fixes it and adds an unit test for it.
Fixes #1635
=> Enhance error handling of policy reconciler

pkg/agent/flowexporter/exporter/exporter.go, pkg/flowaggregator/flowaggregator.go, test/e2e/flowaggregator_test.go
This PR is a follow-up fix for bumping go-ipfix to v0.4.2 with following changes:
- add `destinationServicePort`, `egressNetworkPolicyName` and `egressNetworkPolicyNamespace` in correlation fields
- add stats update function in flow-exporter without which the delta values are 0 (found in e2e tests)
- add network policy testing for inter Node flows
- fix bandwidth unit parsing problem
=> [Flow-Aggregator] Add correlate fields and fix e2e tests with stats and network policy

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, docs/antrea-network-policy.md, pkg/controller/networkpolicy/tier.go, pkg/controller/networkpolicy/validate.go, pkg/util/env/env.go
This PR updates the priority of Tiers created by Antrea, and space them out evenly. The current Antrea generated Tier priorities do not allow enough room for user defined Tiers to be created, for example Emergency Tier allows only 4 user created Tiers with higher priority. Since it ultimately is up to the users as to which Tiers go atop and the purpose of Antrea created Tiers is mainly that of convenience, we decided to distribute the priorities more evenly across available priority space. For example, setting the priority of the top most Tier of Emergency to a value of 50 gives enough room for admins to create their own Tier hierarchy without having to rely on Antrea created Tiers.
Summary of change:
```
Tier Name        Old Priority        Updated Priority
emergency         5 …
```
=> Update Emergency Tier's Priority to 50

ci/jenkins/README.md, ci/test-conformance-aks.sh
This will fix the AKS CI failure caused by the Sonobuoy version increase
See https://jenkins.antrea-ci.rocks/view/cloud/job/cloud-antrea-aks-conformance-net-policy/80/console
=> Use default K8s version supported by AKS for cloud CI

test/e2e/antreapolicy_test.go, test/e2e/utils/anpspecbuilder.go, test/e2e/utils/cnpspecbuilder.go
Ensure that "endPort" is not set smaller than "port" field and "port" field must be set when "endPort" field is set.
=> Add validation e2e tests for endPort

hack/update-codegen-dockerized.sh
=> Avoid concurrent Git processes when running 'make codegen'

docs/antctl.md, pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/antctl/antctl.go
When debugging traffic paths in OVS, we need to check flows in multiple tables most of the time. To make the debugging more convenient, this commit makes the `ovsflows` command accepting multiple tables instead of one.
=> Support retrieving flows of multi-tables of ovsflows command

pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go
When running manual tests on AntreaProxy by enabling AntreaProxy with
ongoing connections and checking if these connections were disrupted, I
observed some strange behavior. AntreaProxy would try to load-balance
the connection but the selected endpoint would be ignored and instead
the endpoint selected by kube-proxy would keep being used. This is good
because it means the connection wasn't disrupted. However, this behavior
is a bit surprising. It seems that because the connection was already
committed, the DNAT action invoked by AntreaProxy was ignored
altogether.
To avoid confusion in the future to people troubleshooting the OVS
pipeline, this commit adds a flow to the ConntrackState table, to bypass
AntreaProxy for established connections, even if these connections don't
have the …
=> Skip AntreaProxy LB for established connections without ServiceMark

ci/jenkins/jobs/macros.yaml
In PR #1521 , Antrea VMC CI started to use VMware-hosted Harbor registry to download images. However, this did not apply to the matrix job due to a typo in Shell script.
=> Fix: CI should use Harbor registry in matrix job

cmd/antrea-agent/options.go
It used the value in the config file to check whether FlowExporter is
enabled, which would cause problem when the feature is enabled by
default later.
=> Fix enablement check of feature FlowExporter

pkg/agent/controller/noderoute/node_route_controller_test.go
The test must wait for cache sync first, otherwise resource creation
events will be missing if the resources are created in-between list and
watch call of an informer. This is because fake clientset doesn't
support watching with resourceVersion. A watcher of fake clientset only
gets events that happen after the watcher is created.
Fixes #1562
=> Fix flaky test TestControllerWithDuplicatePodCIDR

pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_flow.go, test/e2e/bandwidth_test.go, test/e2e/basic_test.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/ipsec_test.go, test/e2e/k8s_util.go, test/e2e/networkpolicy_test.go, test/e2e/proxy_test.go, test/e2e/traceflow_test.go
* Fixed bugs in AntreaProxy IPv6 support
* HarpinIPv6 address is changed to a unique local address instead of a link local one. An automatically generated IPv6 link local address will be allocated to a device. Then, the device considers itself in the same subnet as the IPv6 link local address. As a result, traffic fails. As a reserved IP address, a unique local address works.
* ServiceLearnFlow: Use MatchLearnedSrcIPv6 and MatchLearnedDstIPv6 to replace IPv4 ones. IPv6 specific fields (NXM_NX_IPV6_SRC and NXM_NX_IPV6_DST) should be used.
* MatchTransportDst: wrong OXM_OF_XXX_DST field for IPv6. In original logic, protocol name is put into OXM field name but IPv6 protocol has "v6" in its name, which lead s to flow table addition failure.
* Modified and enabled AntreaProxy e2e tests to …
=> Bug fix in AntreaProxy IPv6 and modification of related e2e tests

go.mod, test/integration/agent/route_test.go
* Use github.com/stretchr/testify/assert assertions "correctly" to
reduce verbosity
* Skip TestIPv6RoutesAndNeighbors when IPv6 is not supported - in
particular the test was failing on macOS when using 'make
docker-test-integration'
=> Cleanup Agent integration tests

docs/prometheus-integration.md, pkg/agent/proxy/metrics/metrics.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go
Added metrics below:
- antrea_proxy_sync_proxy_rules_duration_seconds: SyncProxyRules latency
in seconds of AntreaProxy
- antrea_proxy_total_endpoints_installed: The number of Endpoints
installed by AntreaProxy
- antrea_proxy_total_endpoints_update: The cumulative number of Endpoint
updates at AntreaProxy
- antrea_proxy_total_services_installed: The number of Services installed
by AntreaProxy
- antrea_proxy_total_services_update: The cumulative number of Service
updates at AntreaProxy
=> Add metrics of Antrea Proxy

.github/workflows/build.yml, Makefile, build/images/Dockerfile.simulator.build.ubuntu, build/yamls/patches/simulator/agentNodeAffinity.yml, build/yamls/patches/simulator/antrea-agent-simulator.yml, build/yamls/patches/simulator/controllerNodeAffinity.yml, cmd/antrea-agent-simulator/main.go, cmd/antrea-agent-simulator/simulator.go, docs/antrea-agent-simulator.md, docs/maintainers/build-kubemark.md, hack/.notableofcontents, hack/generate-manifest.sh
The binary simulates an antrea-agent in pod for scale test, it works with kubemark which simulates kubelet and kube-proxy. It mainly watches networkPolicies, addressGroups and appliedToGroups.
To run simulator , please refer to docs/antrea-agent-simulator.md
=> add simulator for scale tests

pkg/agent/openflow/pipeline.go, test/integration/agent/openflow_test.go
Some flow entries are using the global vMAC as the mark when resetting dst MAC, while
others are using macRewriteMark originally. With this change, macRewriteMark is working
as the only mark.
=> Revise OVS pipeline: use macRewriteMark as the only mark to reset dst MAC

pkg/agent/util/net_windows.go, pkg/agent/util/net_windows_test.go
Hyper-V feature contains multiple components/sub-features. According to
the test, OVS requires "Microsoft-Hyper-V" feature to be enabled.
=> [Windows] Update the way to check the state of required Windows feature

Makefile
It is not always appropriate to pull the base image when building the Antrea Docker image with the "make ubuntu" target. In particular, when using a Docker registry other than docker.io, we may not want to pull the base image. Other targets already consider the "DOCKER_REGISTRY" variable and only pull the base image if the variable is not set. We do the same for the "make ubuntu" target. Other variables may be used in the future to make this decision if appropriate.
=> Conditionally pull base image for "make ubuntu" target

docs/windows.md
Provide workaround to install Hyper-V without CPU virtualization
capability check. In this way, users could deploy antrea on the
testbed without virtualization capability.
=> [Windows] Provide workaround to install Hyper-V without CPU check

ci/jenkins/test.sh
Service ovs-vswitchd depends on service ovsdb-server.
So the ovsdb-server service cannot be restarted directly
when ovs-vswitchd is running.
=> [Windows] Fix restart OVS service issue

pkg/agent/openflow/pipeline.go
Whether AntreaProxy is enabled or not, there are some common flow tables. There tables can be added to pipeline before the judgement for AntreaProxy to avoid duplicate code.
=> [Refactor] Common flow tables in pipeline

.github/workflows/build.yml, .github/workflows/go.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
Getting ready to rename default branch from "master" to "main".
By making these changes ahead of time, we ensure that workflows will not
break, including for existing PRs.
Jenkins YAML files will need to be updated right after renaming the
branch. Jenkins jobs for PRs should not be affected.
See #1675
=> Update Github workflows ahead of default branch renaming

docs/getting-started.md
docs: updated requirement of Linux Kernel version from 4.4 to 4.6 in 
getting-started.md
For AntreaProxy, the feature that requires OVS ct action to support nat has
been promoted to beta and enabled by default since v0.11. Linux kernel 4.6
is the earliest upstream version that supports it. The PR corrects the 
Linux kernel version requirement in getting-started.md.
Fixes #1652
=> Update the getting started doc about the requirements of Linux Kernel

.github/workflows/build.yml, .github/workflows/build_tag.yml, .github/workflows/clair.yml, .github/workflows/go.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, .github/workflows/update_ovs_image.yml, .github/workflows/upload_release_assets.yml, build/images/Dockerfile.octant.ubuntu, build/images/codegen/Dockerfile, build/images/ethtool/Dockerfile, build/images/perftool/Dockerfile, test/e2e/infra/vagrant/Vagrantfile
* use Ubuntu 20.04 for Antrea Octant Docker image
* use Ubuntu 20.04 for ethtool, perfitool and codegen utility Docker
images
* use Ubuntu 20.04 for K8s Nodes in Vagrant testbed
* use ubuntu-latest instead of ubuntu-18.04 for Github runners; Github
has started rolling out Ubuntu 20.04 as the default version (see
https://github.com/actions/virtual-environments/issues/1816)
=> Use Ubuntu 20.04 more consistently instead of Ubuntu 18.04

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent-simulator/simulator.go, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-controller/controller.go, pkg/k8s/client.go
antrea-agent relies either the following clientConnection or in-cluster
serviceaccount to configure the clientset that talks to apiserver.
```
clientConnection:
kubeconfig: /home/ubuntu/.kube/config
```
For in-cluster configuration the apiserver host and port are injected
by kubelet, which is normally the apiserver's service vip (e.g.
10.96.0.1). This new option allows override them by `masterOverride`.
It must be a host string, a host:port pair, or a URL to the base of the
apiserver.
For example:
```
masterOverride: 127.0.0.1:43305
```
Fixes #1684
=> antrea-agent supports overriding apiserver

pkg/util/ip/ip.go, pkg/util/ip/ip_test.go
K8s allows non standard CIDRs to be specified (e.g. 10.0.1.1/16,
fe80::7015:efff:fe9a:146b/64). However, OVS will report
OFPBMC_BAD_WILDCARDS error if using them in the OpenFlow messages.
antrea-agent has normalized IPv6 CIDRs before installing Openflows but
hasn't done it for IPv4 CIDRs. This patch fixes the IPv4 case.
Fixes #1764
=> Normalize non standard CIDRs to fix OVS error

pkg/agent/proxy/metrics/metrics.go, test/e2e/prometheus_test.go
Add explicit stability info to Antrea Proxy metrics, also add to the
Prometheus tests.
=> Add Antrea Proxy metrics to tests, add stability

build/images/scripts/install_cni, build/images/scripts/install_cni_chaining, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
The host's binary may depend on shared libraries not available in the
container image.
Additionally, if 'modprobe openvswitch' fails in the initContainer, we
use a log message to suggest to the user to try running the command on
each Kubernetes Node. While this is not ideal, the rationale is that if
the Kernel module format is not supported by the container's kmod,
loading it from the host will ensure that requirements are met and also
bypass the error as the initContainer will not attempt to load the
module if it is already loaded (normal modprobe behavior)..
Fixes #1776
=> Stop mounting the host's kmod to the Antrea initContainer

build/images/scripts/install_cni, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, docs/security.md, pkg/agent/util/net_linux.go, test/e2e/basic_test.go
This commit changes the permissions of the /var/run/antrea directory
and the CNI UNIX socket file, to disallow access from non-root users.
The /var/run/antrea directory is created on the host filesystem through
Pod volume mount, and its default permissions allow access from all
users.
=> Remove the run dir and CNI socket file permissions for non-root users

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
This PR should be merged when Antrea `master` is renamed to `main`.
=> Rename "master" to "main" branch for Jenkins jobs

.github/workflows/go.yml, .github/workflows/update_ovs_image.yml, build/images/base/Dockerfile, build/images/base/build.sh, build/images/ovs/README.md, build/images/ovs/build.sh, ci/run-k8s-e2e-tests.sh, ci/verify-sonobuoy.sh
* Download containernetworking plugins for correct architecture in the
"base" image Dockerfile. Inspired by
https://github.com/docker-library/golang/blob/master/Dockerfile-debian.template.
* Rename build_and_push.sh scripts to build.sh, and add command-line
options to tweak their behavior. In particular add '--platform' to
specifiy the target platform. Note that just providing '--platform
arm64' will not let you build an arm64 image on an amd64 build
server. However, some build servers can support multiple
architectures. This is typically the case of arm64 servers, which can
build images for both 32-bit and 64-bit arm target platforms.
* Update run-k8s-e2e-tests.sh to support arbitrary sonobuoy and
conformance images, and to install correct sonobuoy binary based on
the architecture.
* …
=> Support building Antrea docker images for arm/v7 and arm64

pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/controller/networkpolicy/store/group.go
Instead of using the UID, use the namespace/name to uniquely identify ClusterGroups and internal Group objects.
Additionally, move the IPBlock nil check for ClusterGroup processing to sync handler.
=> Use NamespacedName KeyFunc for ClusterGroups

test/e2e/antreapolicy_test.go, test/e2e/utils/anpspecbuilder.go, test/e2e/utils/cnpspecbuilder.go, test/e2e/utils/networkpolicyspecbuilder.go
This PR is based on #1396 
- Make `PodSelectorMatchExp` and `NSSelectorMatchExp` to not be pointers in np builder files
- Unify rule and spec appliedTo struct in Antrea-native policy builders
- Resolve a TODO item to test ANP and K8s NetworkPolicy with the same name/namespace.
=> E2E improvements and fixes for Antrea-native Policy

build/yamls/antrea-prometheus.yml, ci/jenkins/test.sh, pkg/agent/proxy/proxier.go, test/e2e/prometheus_test.go
* Used Harbor prom/prometheus image link
* Enabled prometheus test on IPv6 testbeds
* Fixed a bug in proxier.go that SyncProxyDurationV6 should be Observed when p.isIPv6 is true
* Refactored some code in prometheus_test.go to better support IPv6 URL
* Renamed tests in prometheus_test.go so prometheus tests have same prefix
=> [CI] Enable prometheus e2e test on dual-stack and IPv6 testbeds

ci/jenkins/jobs/macros.yaml, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh
This is the upgrade matrix compatibility test for Antrea. We want to test whether Antrea can pass all tests when upgrading under various OSs and K8S versions.
In this test, (node_num+1)/2 of all Antrea agents are using an old-versioned image (version defined by OLD_ANTREA_VERSION parameter). Other agents and the Antrea controller are using image built by latest code on master branch by default (version defined by GIT_BRANCH parameter). Then we run Antrea E2E, K8S Conformance and NetworkPolicy tests under each OS and K8S version combination.
This PR is excepted to be merged after #1705 is merged.
=> Add Antrea upgrade matrix test job

pkg/agent/controller/networkpolicy/reconciler.go, pkg/apis/controlplane/sets.go, pkg/apis/controlplane/v1beta2/sets.go, pkg/controller/networkpolicy/antreanetworkpolicy_test.go, pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/external_entity_test.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/controller/networkpolicy/store/addressgroup_test.go
This PR fixes #1807.
PR #1467 unified GroupMemberPod and GroupMember into a single struct. Before the unification, PodReference is not set for GroupMemberPods used in AddressGroups, but set for GroupMemberPods used in AppliedToGroups. In #1467, In order to identify whether a GroupMember contains Pod or EE when converting it to GroupMemberPod (for backward compatibility), PodRef was added to GroupMembers all the time instead. 
This leads to two separate issues. First issue is #1587, where agents running v1beta1 do not expect PodReference in addressGroup members. This was fixed by @tnqn thru not including podRef in addressGroup conversion function #1586. 
Second issue is #1807, where addressGroup updates do not propagate to agents once the Pod IPs are changed after Node restart. This is …
=> Fix AddressGroup memberKey not updated on pod IP update

ci/jenkins/test.sh, test/e2e/antctl_test.go, test/e2e/connectivity_test.go, test/e2e/networkpolicy_test.go, test/e2e/proxy_test.go, test/e2e/security_test.go
* antctl
- There is no need to log antctl output(stdout and stderr) when tests are successful.
It makes console output unnecessarily long.
- proxyPort should be used as value of option "--port" in runAntctProxy().
* IP and Port combination
- Use net.JoinHostPort to avoid if statement.
- Turn "%s:%d" to net.JoinHostPort(ip, port) in log info becauses it
only considers IPv4 before
- Remove old antrea-ubuntu images with "-f" in IPv6/Windows tests. "-f" is
needed because "image is referenced in multiple repositories":
- antrea/antrea-ubuntu
- projects.registry.vmware.com/antrea/antrea-ubuntu
=> [CI] Improve e2e tests and scripts

cmd/antrea-agent/agent.go, pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/testing/mock_route.go, test/integration/agent/route_test.go
Fixes #628 . 
Add a long running goroutine which periodically syncs antrea required iptables rules on linux.
If the sync call/operation fails (for example - xtables lock contention), the next attempt would occur at the next sync interval.
=> Periodic IPTables sync

cmd/antrea-agent/agent.go, pkg/agent/nodeportlocal/k8s/annotations.go, pkg/agent/nodeportlocal/k8s/controller.go, pkg/agent/nodeportlocal/npl_agent_init.go, pkg/agent/nodeportlocal/npl_agent_init_windows.go, pkg/agent/nodeportlocal/nplagent_test.go
Currently the NPLController in antrea-agent watches for all pods on the node, and exposes all pods to the external network using nodeip:nodeport.
This PR introduces pod selection/filtering for NodePortLocal based on an annotation to be provided in the Service objects. The Service objects can be of any type but `NodePort`. The proposed annotation NPLController will watch for is:
`nodeportlocal.antrea.io/enabled: "true"`
**Note**: The value "true" is case sensitive here
This makes the selection and implementation of NodePortLocal much more controlled.
=> Service annotation based pod selection for NodePortLocal

docs/prometheus-integration.md, pkg/controller/metrics/prometheus.go, pkg/controller/networkpolicy/status_controller.go
Too frequent Status updates could generate too many versions of the CRD,
that would need to be stored in etcd until the next compaction by
kube-apiserver. Too many updates could also cause fragmentation of the
database. It is useful to have access to the number of updates over time
in production clusters.
=> Add Prometheus metrics to count ANP and ACNP Status updates

.github/workflows/build.yml, .github/workflows/golicense.yml, .github/workflows/kind.yml, .github/workflows/kind_upgrade.yml
Add .hack/notableofcontents to the file list. It is frequent to update
this file in documentation PRs which add a new Markdown documentation
file, and changes to this file should not trigger expensive CI tests
(notably Kind tests).
=> Update file list used to determine if a PR is a documentation PR

hack/windows/Install-OVS.ps1
- When Hyper-V is disabled on node:
- Use netcfg tool directly to install OVS.
- Install additional powershell modules.
- Support install OVS from a local OVS zip file.
- Allow skip SHA256 hash check for OVS installation file.
=> [Windows] Enhance OVS installation script

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/base/conf/antrea-controller.conf, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-controller/config.go, cmd/antrea-controller/controller.go, pkg/agent/apiserver/apiserver.go, pkg/util/cipher/cipher.go, pkg/util/cipher/cipher_test.go, test/e2e/framework.go, test/e2e/tls_test.go
* Add options TLSCipherSuites, TLSMinVersion on Apiserver side of controller
and agent.
* Add a util module cipher to support functionality and related UT.
* Add tls e2e tests to verify Apiserver of Antrea and Antrea agent.
Signed-off-by: Zhecheng <lzhecheng@vmware.com>
=> Provide CipherSuites option between Clients and Servers

pkg/agent/nodeportlocal/nplagent_test.go
This introduces wait for informerFactory cache sync before proceeding with
object creations. Fixes #1812
=> Fix flaky test TestSvcUpdateAnnotation

.github/workflows/kind.yml, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/infra/vagrant/push_antrea.sh, test/e2e/performance_test.go
* log artifact was not uploaded with the correct name in Github CI job
for Kind e2e tests with Antrea policies enabled; as a result it was
overriding the log archive for one of the other CI jobs.
* export Flow Aggregator logs in e2e test framework in case of test
failure.
* improve push_antrea.sh script so that "standalone" Flow Aggregator
(without external Flow Collector) is supported; this is necessary to
run the e2e tests on a local Vagrant testbed.
* some e2e tests were broken on K8s 1.20 clusters after one of my
earlier changes (global rename from "master" to "control-plane" as
part of the inclusive naming inititative). Even though in K8s 1.20
Nodes are labeled with both "master" and "control-plane" roles, the
Node taint is still "node-role.kubernetes.io/master:NoSchedule", so
when …
=> Multiple fixes and small improvements for e2e tests

cmd/antrea-agent/agent.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/cniserver/server_test.go, test/integration/agent/cniserver_test.go
Network policy not working properly with ContainerD runtime.
The reason is that when creating OVS port asynchronously,
Pod update event may be sent to Network policy controller
earlier than the container interface configuration completion.
For such a case Network policy controller cannot get the IP of
the interface and the policy cannot be realized as expected.
This patch moves "send Pod update event" operation after
container OVS port and interface configuration complete.
Fixes: #1830
=> [Windows] Fix network policy not working

pkg/agent/cniserver/pod_configuration_windows.go
When working with ContainerD runtime, antrea creates OVS port
for Pod asynchronously. Lock needs to be used to prevent
concurrent modification on the same container.
=> [Windows] Lock container by ID to prevent concurrent modification

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/apis/ops/v1alpha1/types.go, test/e2e/framework.go, test/e2e/proxy_test.go, test/e2e/traceflow_test.go
This PR enhanced Traceflow e2e test and fixed 4 Traceflow IPv6 issues:
1. Failure if create Traceflow with ipHeader and ipv6Header (The type of ipHeader defined in pkg/apis/ops/v1alpha1/types.go is ipHeader. If we use this definition to create Traceflow CRD, it will always create ipHeader section. This section will be changed to *ipHeader in future.)
2. IPv6 packet is not handled by packetin.go
3. Unexpected LB observation exists in ICMPv6 Traceflow
4. Wrong ICMPv6 echo request type
=> Enhance Traceflow IPv6 e2e test and fix Traceflow IPv6 issues

pkg/agent/controller/networkpolicy/priority.go, pkg/agent/controller/networkpolicy/priority_test.go
When Antrea agent is restarted, all Antrea-native policy priorities will be registered in batch. On a specific Node, there can be a large number of Antrea-native policies of the same Tier and policy priority. Hence, the list of types.Priority to be registered can contain duplicates, but it is not correctly handled by the priorityAssigner.  Hence, the resulting ofPriority for a specific policy Priority can be inconsistent between batch registration and individual registration. This PR fixes this issue.
=> Fix not dedup Priorities in batch register

pkg/agent/openflow/pipeline.go, pkg/agent/util/net.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
When a Pod accesses a ClusterIP Service and the IP of the selected
endpoint is not in "cluster-cidr". The request packets need to be
SNAT'd after have been DNAT'd. For example, the endpoint Pod may
run in hostNetwork and the IP of the endpoint is the current
Node IP. Currently, on Windows Node antrea applies both DNAT
and SNAT in the same ct_zone. That's not supported by OVS.
In this patch, we introduce a new ct_zone to track this kind of
SNATed connection in a different ct_zone.
Fixes: #1759
=> [Windows] Fix Pod cannot access endpoints with external IP through ClusterIP Service

README.md, hack/.md_links_config.json
Add entry for "office hours" meeting, and link to Antrea team
calendar.
Also, change "project weekly meeting" to "community meeting" since
the meeting isn't weekly anymore.
=> Update meetings in README file

.github/workflows/golicense.yml, ci/golicense/run.sh
uniq only works on sorted inputs; as a result the command was not
removing duplicates as expected.
Before the fix, the dependency manifest had 975 entries and now it has
171 entries.
=> Fix incorrect use of 'uniq' in golicense run.sh script

cmd/antrea-agent/agent.go, cmd/antrea-agent/options.go, cmd/antrea-agent/options_windows.go, cmd/antrea-agent/options_windows_test.go, pkg/agent/agent.go, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/server.go, pkg/agent/flowexporter/connections/conntrack.go, pkg/ovs/ovsconfig/interfaces.go, pkg/ovs/ovsconfig/ovs_client.go, pkg/ovs/ovsconfig/testing/mock_ovsconfig.go, test/integration/agent/cniserver_test.go
'flow-restore-wait' is not set for netdev datapath
=> Avoid warning about 'flow-restore-wait' config with netdev datapath

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml, cmd/antrea-controller/controller.go, pkg/agent/apiserver/apiserver.go, pkg/controller/querier/querier.go, pkg/monitor/controller.go, test/e2e/security_test.go
This is motivated by #1837, in which the Antrea Controller got in a bad
state (presubmably because of a bug in the apiserver library), and
didn't recover. The endpoint was marked as non-Ready for the Antrea
Service, which means the APIService became broken, since the Antrea
Service has a single Endpoint (single Controller replica). With the
liveness probe, the Antrea Controller would have been restarted by
kubelet and the APIService would hopefully have recovered.
The /healthz endpoint is deprecated since K8s v1.16, so we switch to
/readyz and /livez.
=> Add liveness probe to Antrea Controller

.github/workflows/netpol_cyclonus.yml
The name was the same as for the workflow running the e2e tests on Kind,
causing results of earlier runs to be overwritten.
=> Rename Netpol Cyclonus Github workflow

pkg/agent/nodeportlocal/k8s/npl_controller.go
* keys were never deleted from the Pod IP cache
* log verbosity was too high for for add / update / delete events
* handleRemovePod was called for Pod update events when the Pod was not
selected by a Service with NPL enabled. This didn't really make sense
and led to some misleading log messages.
* controller.go file renamed to npl_controller.go so that the NPL log
messages are easier to locate in Agent logs.
=> Improvements / bug fixes in NPL Controller code

hack/windows/Helper.psm1
When starting antrea-agent directly from helper script. The agent
configurations need to be updated every time before starting
the antrea-agent process because the k8s and antrea-controller
API server may be changed after the last startup.
=> [Windows] Always update agent configs on startup

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/agent/flowexporter/exporter/exporter.go, pkg/flowaggregator/flowaggregator.go, plugins/octant/go.sum, test/e2e/framework.go
fixes #1747 and fixes #1820
The PR is for bumping go-ipfix to v0.4.3, with fixes on issue #1747, changes for IPv6 support and
exporting process and collecting process input. It also fixes issue #1820, which is about
unexpected number of warnings for destinationServicePort mismatch.
=> Move go-ipfix to v0.4.3

ci/kind/test-e2e-kind.sh, test/e2e/antreapolicy_test.go
Increase the timeout for e2e tests to 40m (previously 35m) to accommodate new tests.
=> Increase kind e2e test timeout to 40m

Makefile, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, build/yamls/base/conf/antrea-agent.conf, ci/kind/test-e2e-kind.sh, cmd/antrea-agent/agent.go, docs/feature-gates.md, hack/generate-manifest.sh, pkg/agent/proxy/endpoints.go, pkg/agent/proxy/endpointslicecache.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/features/antrea_features.go, third_party/proxy/config/config.go, third_party/proxy/endpoints.go
Support EndpointSlice in AntreaProxy, ServiceTopology is not supported in this commit
=> Support EndpointSlice in Antrea proxy

pkg/controller/networkpolicy/validate.go, test/e2e/clustergroup_test.go, test/e2e/k8s_util.go
Do not allow CG to be created with IPBlock set with either PodSelector and/or NamespaceSelector.
=> Fix CG validation

pkg/agent/nodeportlocal/k8s/annotations.go, pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_init.go, pkg/agent/nodeportlocal/npl_agent_test.go, pkg/agent/nodeportlocal/portcache/port_table.go, pkg/agent/nodeportlocal/rules/iptable_rule.go, pkg/agent/nodeportlocal/rules/rules.go, pkg/agent/nodeportlocal/rules/testing/mock_rules.go, pkg/agent/nodeportlocal/rules/types.go
Currently we delete all the iptable rules when the antrea-agent
is restarted. This commit does the following:
- Evaluates the iptable rules in the Node Port Local chain and
check if a rule is required. If a Pod got deleted while the
antrea-agent was restarting, we don't need that rule and has
to be deleted.
- The above evaluation logic also creates a cache for all the
pods retrived from the iptable rules.
- Evaluates the kubernetes Pods, and for each Pod, it checks if
its part of the above cache. If yes, only the Pod's annotations
needs to be verified. If not, a new Node port has to be allocated
and a rule has to be added.
One of the TODOs as mentioned
[here](https://github.com/vmware-tanzu/antrea/pull/1459).
=> Handle restartability for Node Port Local

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/conf/flow-aggregator.conf, build/yamls/flow-aggregator/base/flow-aggregator.yml, ci/test-elk-flow-collector.sh, cmd/antrea-agent/agent.go, cmd/antrea-agent/config.go, cmd/antrea-agent/options.go, cmd/flow-aggregator/config.go, cmd/flow-aggregator/flow-aggregator.go, cmd/flow-aggregator/options.go, go.mod, go.sum, pkg/agent/flowexporter/exporter/certificate.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/flowaggregator/certificate.go, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/util/flowexport/flowexport.go, plugins/octant/go.sum, test/e2e/framework.go
fixes #1610 
This PR aims to provide TLS support between flow exporter and flow aggregator.
Flow Aggregator generates its own CA, server certificate and key, client certificate and key. Then it distributes CA as ConfigMap, client certificate and key as Secret for Flow Exporter to use. 
It also moves go-ipfix to v0.4.4 with support for collector DNS address resolution and disabling address resolution for TLS (we will need DNS name in server certificate)
=> [Flow-Aggregator] Add security support for flow aggregator

pkg/agent/nodeportlocal/k8s/annotations.go, pkg/agent/nodeportlocal/k8s/annotations_test.go, pkg/agent/nodeportlocal/k8s/npl_controller.go
The newly added unit test (TestInitInvalidPod) was failing, for the
following reason:
* first the Pod is patched to remove the invalid annotation
* second the Pod is handled by the Controller for the first time (add /
update event handler) and the correct NPL annotation is generated,
which needs to be apply with another patch
* but, because the local cache has not been updated yet to reflect the
result of the previous patch operation, the object used in the handler
still includes the invalid annotation. This leads to the "final" Pod
object having 2 annotations (correct + invalid) instead of only 1
(correct).
The test is not always failing, as sometimes the cache is updated fast
enough.
To avoid this issue we update the Controller logic:
* patches are no longer applied during the initial …
=> Fix NPLController unit test failure

docs/contributors/eks-terraform.md, docs/os-issues.md
RedHat has removed the website and links are no longer accessible.
=> Remove coreos.com links in documentation

docs/network-flow-visibility.md, pkg/flowaggregator/flowaggregator.go
This commit updates flow visibility docs with TLS security support between flow exporter and flow aggregator. It also fixes parameter naming issue and removes hard-coded flow aggregator DNS name in generating observationDomainID.
=> Update docs for flow aggregator TLS support

.github/workflows/golicense.yml, ci/golicense/run.sh
Until now, the workflow would actually succeed even if the lichen run
failed, and one would have needed to look at the logs to detect issues.
=> Fail golicense Github workflow if license check fails

CHANGELOG.md, hack/.md_links_config.json
Github users are free to change their handle. We do not want to have to
maintain Github profile links when this happens, especially in the
CHANGELOG. Unfortunately there is no simple way to disable this specific
link pattern only for the CHANGELOG file.
=> Disable deadlink checker for Github handles

go.mod, go.sum
libOpenflow panics if a packet-in message is sent by OVS with a
NXM_NX_PKT_MARK match field. Since #1816, it is a possible situation:
Traceflow requests for the Node IP can lead to reply traffic with the
packet mark set, which are sent to the Antrea Agent as a PacketIn
message. To resolve this issue, we first switch temporarily to a patched
libOpenflow version without this issue. When the patch is ported in
upstream libOpenflow, we can remove the replace directive from go.mod.
Fixes #1878
=> Fix libOpenflow crash for some Traceflow requests

test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go
In the netpol test framework (which was extended to Antrea-native policy), the testcase execution logic was: before each testcase is run, cleanup any netpol that are in the cluster. Thus any resource created by a testcase is cleaned-up by the subsequent testcase. This has been confusing and caused unexpected behaviors when new testcases are added. This PR fixes this issue by letting the testcase itself take care of cleaning up the resources (policies, tiers, CGs) that it creates.
=> Improve Antrea-policy e2e testcase execution logic

pkg/agent/nodeportlocal/k8s/npl_controller.go
If we change nplPortRange and Antrea Agent is rebooted, rules with Node Port outside
current port range are supposed to be deleted. But we face a problem if all rules
have to be deleted from NPL chain. In that case we were skipping IPTABLES update -
because length of allNPLPorts in GetPodsAndGenRules function was getting set to zero.
Removed this length check so that even if all rules have to be deleted, the function
addRulesForNPLPorts is executed.
=> Delete IPTABLES rules for NodePortLocal when nplPortRange is updated

pkg/antctl/raw/traceflow/command.go
Output the Traceflow results, as long as there are any results returned,
so users can know the progress of the Traceflow session even the antctl
command is timeout, or the Traceflow operation fails.
Example output:
```
$antctl traceflow -S kube-system/coredns-74ff55c5b-6sz9g -D 1.2.3.4
name: kube-system-coredns-74ff55c5b-6sz9g-to-172.100.0.33-2rx5fdlg
phase: Running
source: kube-system/coredns-74ff55c5b-6sz9g
destination: 1.2.3.4
results:
- node: k8s1
timestamp: 1613590444
observations:
- component: SpoofGuard
action: Forwarded
- component: Forwarding
componentInfo: Output
action: Forwarded
Error: timeout waiting for Traceflow done
```
=> Change antctl traceflow command to output results at timeout/failure

go.mod, go.sum, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/ipfix/ipfix_set.go, pkg/ipfix/testing/mock_ipfix.go, plugins/octant/go.sum
This commit adds changes in go-ipfix v0.4.5. It modifies the set interface: add PrepareSet and ResetSet methods to support re-use of set and better unit tests. 
It also simplifies the input consumption for exporting and collecting process, which also solves the issue in the slack channel https://kubernetes.slack.com/archives/CR2J23M0X/p1613742315130500
fixes #1893
=> Move go-ipfix to v0.4.5

pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration_windows.go, pkg/agent/cniserver/server_windows.go
It's written as ContainerD only in a few windows documentation. Use
Containerd to align with the official documentation.
=> Unify the writting of containerd

pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/transform/ovstracing/transform.go
Transform the "/ovstracing API" response to []byte, and change antctl to
output the raw bytes directly for a []byte type response.
=> Fix the formatting of antctl trace-packet output

pkg/agent/agent.go, pkg/agent/util/net_linux.go, pkg/agent/util/net_windows.go, test/integration/agent/net_test.go, test/integration/agent/net_test_linux.go, test/integration/agent/net_test_windows.go
When a Node leaves a K8s cluster and joins it again later, it is likely
that it will receive a different Pod CIDR. If we simply add the new
gateway IP (first IP in the CIDR) to the host gateway interface without
removing the previous one, we have observed that it can lead to
connectivity issues. This commit ensures that all stale IPs are removed
when configuring the gateway interface on an Agent restart. Link-local
addresses are left untouched. An integration test is added for both
Linux & Windows.
Fixes #1685
=> Clean up stale IP addresses on Antrea host gateway

ci/jenkins/jobs/projects.yaml
There is a extra ")" in current trigger phrase in integration-manual job.
As a result, triggering will fail and it leads to error below:
```
Failed to compile pattern ^(?!Thanks for your PR).*/test-integration).*
java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 41
^(?!Thanks for your PR).*/test-integration).*
```
=> [CI] Fix wrong trigger phrase in integration-manual job

pkg/agent/controller/traceflow/packetin.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/apis/ops/v1alpha1/types.go, pkg/controller/traceflow/controller.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/traceflow_test.go
PR #1883 fixes a panic in libOpenflow triggered when OVS receives reply
traffic for a Traceflow request with a valid dataplane tag as the ToS
field and the Linux packet mark set. However, it should be noted that
reply packets for Traceflow requests are generally meaningless and
should be ignored. In encapMode, The Traceflow implementation should
also not timeout when a Traceflow request leaves the overlay: as soon as
the request is forwarded through the gateway port, we should consider
the request complete, and ignore any potential reply packet. So we
include the following changes:
* add a new "ForwardedOutOfOverlay" Traceflow action when a request is
forwarded out of the network managed by Antrea in encapMode. The
Controller can then mark the request as "succeeded". In theory,
something …
=> Fix Traceflow implementation for external IPs and gateway IP

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/conf/antrea-agent.conf, cmd/antrea-agent/config.go
* Default value should not be 1450 in YAML manifest: if someone just
uncomments this line, it will force the MTU to be set to 1450, as
opposed to the default behavior which is auto-discovery.
* The corresponding comment in cmd/antrea-agent/config.go was incorrect.
=> Fix misleading comments about defaultMTU config parameter

go.mod, go.sum, plugins/octant/go.sum
Replace statement is no longer needed after changes have been accepted
upstream (github.com/rakelkar/gonetsh).
=> Remove go.mod replace statement for gonetsh

docs/contributors/github-labels.md
* remove area/transit/ip
* rename area/routing to area/transit/routing
* add area/proxy, area/proxy/clusterip, area/proxy/nodeport and
area/proxy/nodeportlocal
=> A few more changes to the set of Github labels for Antrea

test/e2e/k8s_util.go
In CreateOrUpdateDeployment, the function will return when Create succeeds,
and call Update when create fails. But Create will return an empty deployment
object d, if we use d, Update will return error that resource name is empty.
=> CreateOrUpdateDeployment should use deployment to update

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml, build/yamls/base/controller.yml, cmd/antrea-controller/controller.go, pkg/agent/apiserver/apiserver.go, pkg/apiserver/certificate/certificate.go, pkg/apiserver/certificate/certificate_test.go
* Used "localhost" instead of "127.0.0.1" in antrea.yml
* Added IPv6 loopback address in alternate IPs
* Replaced some net IPs with pre-defined vars.
=> [IPv6] Use localhost and add IPv6 loopback addresses

.github/workflows/build.yml, .github/workflows/build_tag.yml
When the main branch is updated, or a new relese tag is creted, we build
and push the amd64 Antrea Docker image (renamed from
antrea/antrea-ubuntu to antrea/antrea-ubuntu-amd64), then trigger a
workflow in the private vmware-tanzu/antrea-build-infra repository which
will build the Antrea ARM images (antrea/antrea-ubuntu-arm and
antrea/antrea-ubuntu-arm64) as well as the multi-arch manifest list
(antrea/antrea-ubuntu).
As a reminder, vmware-tanzu/antrea-build-infra is private (maintainer
access only) because of security issues when using self-hosted runners
(in our case, arm64 machines) in a public repo. When / if these security
issues are addressed by Github, we will merge
vmware-tanzu/antrea-build-infra into vmware-tanzu/antrea.
See #450
=> Trigger Docker multi-arch build on pushes and releases

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/networkpolicy/status_controller_test.go, pkg/util/sets/string.go
An AddressGroup can be shared by multiple NetworkPolicies and its span
is the union of the NetworkPolicies'. The syncAddressGroup method uses
"Union" method to calculate the union set. However, the method always
create a new sets and copies the original items when traversing each
set. This performs badly when the number of the NetworkPolicies increase
and the span is big.
This patch optimizes it by using a "Merge" function to avoid above cost.
The benchmark impact is as below when there are 1000 NetworkPolicies
sharing the AddressGroup and the span is 1000 Nodes:
```
name                 old time/op    new time/op    delta
SyncAddressGroup-48     417µs ± 4%     326µs ± 4%  -21.91%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
SyncAddressGroup-48    98.9kB ± 0% …
```
=> Do not construct intermediate sets when calculating union of multiple sets

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_test.go
Also includes UT to check for namespace based pod filtering via Services.
Fixes #1926
=> Pod filtering for Services based on Namespaces in NodePortLocal

test/e2e/README.md, test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/destroy.sh, test/e2e/infra/vagrant/playbook/roles/common/tasks/enable-forwarding.yml, test/e2e/infra/vagrant/playbook/roles/common/tasks/main.yml, test/e2e/infra/vagrant/playbook/roles/control-plane/tasks/main.yml, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/coreDNS-cm.yml.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/socat-dns-proxy-tcp.service.j2, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/socat-dns-proxy-udp.service.j2, test/e2e/infra/vagrant/provision.sh
provision.sh now supports a new command-line option,
'--ip-family'. Running './provision.sh --ip-family v6' will create an
IPv6-only Kubernetes cluster, even if the host machine does not support
IPv6 itself. While the network used by Kubernetes is IPv6, the Nodes
still access the Internet over IPv4. Pods do not have access to the
Internet. I validated the cluster by running K8s conformance tests.
There will eventually be support for dual-stack clusters as well, when
kubeadm support for dual-stack matures a bit.
=> Support creating IPv6-only Vagrant-based K8s cluster

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/controller/networkpolicy/external_entity.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/util/sets/string.go, pkg/util/sets/string_test.go
Calculating symmetric difference is common in the code, while
s1.Difference(s2).Union(s2.Difference(s1)) is a little complicated,
error-prone, and always builds several unnecessary intermediate sets.
This patch adds an util function SymmetricDifference to improve it. The
benchmark impact is as below when calculating symmetric difference of
two sets each of which contains 2000 items:
```
name                    old time/op    new time/op    delta
SymmetricDifference-48    1.50ms ± 1%    0.87ms ± 3%  -42.10%  (p=0.008 n=5+5)
name                    old alloc/op   new alloc/op   delta
SymmetricDifference-48     342kB ± 0%     171kB ± 0%  -49.99%  (p=0.008 n=5+5)
name                    old allocs/op  new allocs/op  delta
SymmetricDifference-48       132 ± 0%        61 ± 0%  -53.79%  (p=0.029 …
```
=> Improve calculating symmetric difference

.github/workflows/kind.yml, Makefile, build/images/flow-aggregator/Dockerfile.coverage, build/yamls/flow-aggregator/patches/coverage/startFlowAggCov.yml, ci/jenkins/test-vmc.sh, ci/kind/test-e2e-kind.sh, cmd/flow-aggregator/bincover_run_main_test.go, hack/generate-manifest-flow-aggregator.sh, pkg/agent/flowexporter/exporter/certificate.go, test/e2e/coverage/flow-aggregator-arg-file, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
Add code coverage for flow aggregator binary when
running end-to-end tests on different platforms
(kind, jenkins, VMC etc.)
=> Add code coverage for flow aggregator

test/e2e/nodeportlocal_test.go
Otherwise a setup failure would panic and terminate all tests.
For instance: https://jenkins.antrea-ci.rocks/job/antrea-e2e-for-pull-request/2181/console
=> Do not override global testData in e2e tests

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/agent_windows.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_other.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/client_windows.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, test/integration/agent/openflow_test.go
Separate common flows and Windows only flows for SNAT.
Add a new snatTable(71) between l3ForwardingTable and l3DecTTLTable(72)
for looking up SNAT IPs of the external traffic.
Issue: #667
=> Refactor Windows SNAT flows for SNAT policy implementation

ci/jenkins/mellanox/common/common_functions.sh
Latest master multus changes the daemonset name to kube-multus-ds
instead of kube-multus-ds-amd64. Since we look for that name to
change the image to use the harbor image, the CIs started to fail.
This patch modify the name of the daemonset to match the new name.
=> Fix multus daemonset rename in mellanox-ci

pkg/agent/flowexporter/exporter/exporter.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go
The bug is because IPFIX exporting process interface in Flow Exporter is assigned with typecasted nil (typecasted to corresponding structure `ipfixExportingProcess`). This code was modified in PR #1714 . Therefore, the code comparing with `nil` breaks in exporting process initialization code of Flow Exporter. 
This PR fixes the bug along with another issue in fetching certificates that exacerbates this bug when the Flow Exporter cannot connect to the Flow Aggregator.
Fixes #1956
=> Fix the bug in Flow Exporter that cause intermittent errors in e2e tests

pkg/agent/apiserver/apiserver.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go
The agent logs will print the failure message when the connection to
the controller is timeout. Also adding HealthCheck to remind
the users of the connectivity issue.
Fixes #822
=> Improve logs when there is a timeout error

go.mod, go.sum, plugins/octant/go.sum
We merged the fix for decoding pkt_mark match to
github.com/contiv/libOpenflow, as well as a change to support matching
tun_ipv6_dst, so switch back to the upstream libOpenflow.
=> Switch to the latest commit of github.com/contiv/libOpenflow

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/controller/networkpolicy/packetin_test.go, pkg/agent/controller/traceflow/packetin.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/network_policy.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/util/net.go, pkg/apis/ops/v1alpha1/types.go, pkg/apis/security/v1alpha1/types.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_packetout.go, test/e2e/antreapolicy_test.go, test/e2e/k8s_util.go, test/e2e/reachability.go
Reject action is quite similar to the Drop action. Reject action not only drop the request packet, but also send a response to the requesting client to indicate the rejection.
1. Add `Reject` to the YAML.
2. Use register to carry more information in packet-in. Mark the packet-in need logging, rejection or other operations.
3. OpenFlow controller sends reject packet-out to the requesting client.
=> Reject action support

ci/jenkins/mellanox/jobs/00-functions.yaml, ci/jenkins/mellanox/jobs/antrea_trigger_ci.yaml, ci/jenkins/mellanox/jobs/console-text-fetcher.yaml
Previously the CI used to point to the Jenkins job console as its
context URL, and the end of that, there was a link to an HTML server
that contained the logs. As a part of logs improvement, a change to
directly point to the HTML server with the console being uploaded to
it was adopted. This was done for ease of accessing the logs, and
to avoid slow uploading times of uploading the logs from the internal
Jenkins to the Public Jenkins.
=> Change Mellanox CI logs URL to point to the HTML logs directly

.github/workflows/build.yml, .github/workflows/build_tag.yml, build/images/base/Dockerfile, build/images/base/build.sh, ci/run-k8s-e2e-tests.sh
The build/images/base/build.sh script was incorrectly using the
OVS_VERSION env variable as the tag for the intermediate cni-binaries
image. Instead, we should be using the version of the CNI binaries
packaged in the Docker image.
This is currently causing the CI build on the main branch to fail,
preventing the antrea/antrea-ubuntu:latest Docker image to be updated
automatically.
=> Fix Docker build when main branch is updated

docs/windows.md, hack/windows/Install-OVS.ps1
* Added a new option "ImportCertificate" to decide if certificate is needed.
Default is true
* Simplified certificate addition with command "Import-Certificate"
=> [Windows] Check if importing certificate is needed

ci/jenkins/mellanox/scripts/start_ci.sh
Following #1985, the `docker build` command needs to be provided with
the OVS_VERSION variable. Since hw-offload CI uses the `docker build`
command directly instead of `make build`, it started to fail. This
patch fixes this by adding the variable to the `docker build` command.
=> Add OVS_VERSION to hw-offload CI docker build

pkg/agent/controller/networkpolicy/packetin.go, pkg/ovs/openflow/ofctrl_action.go, pkg/util/ip/ip.go, pkg/util/ip/ip_test.go
The code in charge of parsing the PacketIn messages was only handling
IPv4 packets and not filling-in any information for IPv6 packets,
leading to logs with empty fields.
Fixes #1989
I ran the test successfully in an IPv6 cluster creating with Vagrant VMs:
```
=== RUN   TestAntreaPolicy/TestGroupAuditLogging
=== RUN   TestAntreaPolicy/TestGroupAuditLogging/Case=AuditLoggingBasic
I0324 16:58:27.096931   80575 entry.go:314] Creating/updating ClusterNetworkPolicy test-log-acnp-deny
I0324 16:58:40.655439   80575 entry.go:314] Deleting AntreaClusterNetworkPolicies test-log-acnp-deny
I0324 16:58:40.664245   80575 entry.go:314] Deleting test Namespace x
I0324 16:58:40.667629   80575 entry.go:314] Deleting test Namespace y
I0324 16:58:40.670239   80575 entry.go:314] Deleting test Namespace z
=== …
```
=> Fix NetworkPolicy logging for IPv6 connections

go.mod, go.sum, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/types/marks.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/agent/openflow_test.go
Add flows that set pkt_mark for egress traffic that should be SNAT'd
using a SNAT IP, including egress traffic from a local Pod to which the
Egress is applied, and traffic from a remote Node that is tunnelled to
the egress Node with the SNAT IP.
Each SNAT IP on the Node will be allocated with a unique integer ID,
which is set to the pkt_mark, and so the SNAT implementation can look
up the right SNAT IP from the pkt_mark. On Linux, SNAT will be
implemented by iptables SNAT rules; on Windows, SNAT is implemented
by OVS NAT.
#1924
=> Add OVS flows for implementing Egress

cmd/antrea-agent/agent.go, pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/connections_test.go, pkg/agent/proxy/proxier.go, pkg/agent/proxy/testing/mock_proxy.go, test/e2e/fixtures.go, test/e2e/flowaggregator_test.go, third_party/proxy/meta_proxier.go, third_party/proxy/testing/mock_proxy.go, third_party/proxy/types.go
After investigation, we found that the e2e test failure in dual stack cluster of flow aggregator is because we couldn't retrieve the service info from antrea-agent-proxier for IPv6 service address in jenkins dual stack cluster. 
In this commit, we fixed a bug in GetServiceByIP() function of dual-stack proxy. 
Also, we improved the e2e test of flow aggregator: for dual stack clusters, we will test services for both IPv4 and IPv6 clusterIP.
=> Add IPv4/v6 dual stack support in Flow aggregator

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/apis/core/v1alpha2/types.go, pkg/apis/core/v1alpha2/zz_generated.deepcopy.go, pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, pkg/controller/networkpolicy/store/group.go, pkg/controller/networkpolicy/validate.go, pkg/controller/types/group.go, test/e2e/antreapolicy_test.go, test/e2e/clustergroup_test.go, test/e2e/fixtures.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go, test/e2e/nodeportlocal_test.go, test/e2e/utils/cgspecbuilder.go
This PR adds a new `childGroups` field for ClusterGroups, which allows a ClusterGroup to select other ClusterGroups by name. The effective members of the 'parent' CG will be the union of its `childGroups`' members. Restrictions do apply:
1. `childGroups` cannot be used concurrently with selectors/ipBlock/serviceReference. A ClusterGroup can either select other CGs, or select workloads/ipBlock/Services, but not both. 
2. Currently only one level of 'nested-ness' is supported: If a ClusterGroup has `childGroups`, it cannot be selected as a `childGroup` by other CGs.
3. ClusterGroup must exist before another ClusterGroup can select it by name as its `childGroup`. A ClusterGroup cannot be deleted if it is referred by other ClusterGroup as `childGroup`.
=> Add nested ClusterGroup support

hack/netpol/pkg/utils/k8s_util.go, test/e2e/antreapolicy_test.go, test/e2e/framework.go, test/e2e/k8s_util.go, test/e2e/reachability.go
This PR fixes #1967. 
1. Change to use agnhost to test connectivity between Pods in E2E test.
2. Add UDP, SCTP test case in E2E test (Since OVS userspace conntrack doesn't support SCTP, SCTP cases will be skipped)
=> Add agnhost for E2E test

build/images/flow-aggregator/Dockerfile
Flow aggregator only needs the Golang binary and doesn't have dependencies on OVS. Changing the base image to reduce image size.
Closes https://github.com/vmware-tanzu/antrea/issues/1986.
=> Change flow-aggregator base images to reduce image size

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/flow-aggregator.yml, pkg/apiserver/certificate/cacert_controller.go, pkg/clusteridentity/clusteridentity.go, pkg/flowaggregator/certificate.go
Moving "antrea-ca" and "antrea-cluster-identity" out of deployment manifest.
Instead creating them in the code.
Fixes #1945
=> Move mutable configmaps out of deployment manifest

Makefile
`make docker-test-integration` was broken if NO_PULL was false.
```
mkdir -p /root/antrea/.coverage
===> Building Antrea Integration Test Docker image <===
docker build --pull -t antrea/test -f build/images/test/Dockerfile -build-arg OVS_VERSION=2.14.0 .
unknown shorthand flag: 'b' in -build-arg
See 'docker build --help'.
Makefile:151: recipe for target 'docker-test-integration' failed
make: *** [docker-test-integration] Error 125
```
=> Fix incorrect docker build command

docs/antctl.md, pkg/antctl/raw/traceflow/command.go, pkg/antctl/raw/traceflow/command_test.go
contribute to https://github.com/vmware-tanzu/antrea/issues/1988
=>  support ipv6 in antctl

pkg/agent/route/interfaces.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go, pkg/agent/route/testing/mock_route.go, pkg/agent/util/iptables/iptables.go, test/integration/agent/route_test.go
=> Add iptables interface for implementing Egress

.github/workflows/build.yml, .github/workflows/build_tag.yml, Makefile, build/images/flow-aggregator/Dockerfile, build/images/flow-aggregator/Dockerfile.coverage, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/flow-aggregator.yml, ci/jenkins/test-vmc.sh, ci/jenkins/test.sh, test/e2e/coverage/flow-aggregator-arg-file
Fix the error of Flow Aggregator image after PR #2004 changed the base image to scratch.
Change the image name target "flow-aggregator-ubuntu" to "flow-aggregtor-image" in Makefile since ubuntu is not relevant.
Change the base image of Flow Aggregator code coverage image to ubuntu:20.04.
=> Fix and improve the docker image building process of Flow Aggregator

Makefile, build/images/base/build.sh, build/images/ovs/build.sh, ci/jenkins/jobs/projects.yaml, ci/jenkins/test-vmc.sh, ci/jenkins/test.sh, hack/build-antrea-ubuntu-all.sh
In https://github.com/vmware-tanzu/antrea/pull/1951 we ensured that the
Github workflows would use up-to-date base Docker images by building all
images in every run and leveraging Docker caching to reduce build
times. With this new change, we do the same thing for Jenkins jobs.
See #1540
=> Ensure Jenkins CI jobs use up-to-date base Docker images

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, ci/kind/test-e2e-kind.sh, docs/antrea-network-policy.md, pkg/apis/crd/v1alpha2/types.go, pkg/apis/crd/v1alpha2/zz_generated.deepcopy.go, pkg/controller/networkpolicy/clustergroup.go, pkg/controller/networkpolicy/clustergroup_test.go, pkg/controller/networkpolicy/clusternetworkpolicy.go, pkg/controller/networkpolicy/clusternetworkpolicy_test.go, pkg/controller/networkpolicy/crd_utils.go, pkg/controller/networkpolicy/validate.go, pkg/controller/types/group.go, test/e2e/antreapolicy_test.go, test/e2e/clustergroup_test.go, test/e2e/utils/cgspecbuilder.go
This PR adds a new `ipBlocks` field for the ClusterGroup resource. It allows users to group a list of CIDRs in a ClusterGroup, instead of a single CIDR in the `ipBlock` field. For a single ClusterGroup, `ipBlock` and `ipBlocks` should not be set at the same time. Users can continue to create ClusterGroups with `ipBlock`. This field however will be deprecated in the next API upgrade for ClusterGroup. See #2008.
=> Add ability to specify a list of ipBlocks in crd/v1alpha2 ClusterGroup

build/images/base/build.sh, build/images/ovs/build.sh, ci/jenkins/test.sh, hack/build-antrea-ubuntu-all.sh
Contrary to what I was led to believe, there is indeed rate limiting for
official Ubuntu images on Dockerhub. So we use a copy from the Antrea
Harbor registry instead.
=> Use Ubuntu 20.04 image from Harbor registry for Jenkins CI

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/antctl/raw/traceflow/command.go, pkg/antctl/raw/traceflow/command_test.go, pkg/apis/crd/v1alpha1/types.go, pkg/controller/traceflow/controller.go, pkg/controller/traceflow/controller_test.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_builder.go, pkg/ovs/openflow/ofctrl_packetout.go, pkg/ovs/openflow/testing/mock_openflow.go, test/e2e/traceflow_test.go, test/integration/ovs/ofctrl_test.go
Add support of tracing live traffic. Rather than injecting a Traceflow
packet, a live traffic Traceflow will trace the real traffic between
Pods - the first packet of the first connection that matches the
Traceflow spec will be traced.
antctl traceflow command is extended to support live traffic Traceflow.
This commit also makes a few others changes to Traceflow: change
Destination (live traffic Traceflow does not require Traceflow
Destination to be provided), Packet, and Packet IPHeader in Traceflow
Spec to optional fields; add a Timeout parameter to Traceflow Spec and
antctl traceflow command to specify the timeout time of a Traceflow;
delete OVS flows added for the Traceflow after agent receives the first
captured packet of the Traceflow; support all IP protocols.
=> Support Traceflow of live traffic

pkg/agent/openflow/client.go, pkg/agent/openflow/packetin.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/testing/mock_openflow.go, test/integration/ovs/ofctrl_test.go
Before we add rate limiting mechanism in OVS, we use RateLimitingQueue for packet-in event in Antrea agent.
I have tested it using `hping3` to simulate packet flood and agent can handle packet-in under the rate limit.
=> Add rate limiting queue for packet-in

ci/jenkins/jobs/projects.yaml
When AntreaPolicy is enabled by default, antrea-e2e-for-pull-request in Jenkins need more time to avoid timeout.
For example: https://jenkins.antrea-ci.rocks/job/antrea-e2e-for-pull-request/2329/
=> Add more time for Jenkins antrea e2e test

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_test.go
includes a UT for the same.
Fixes #1910
=> Update Pod annotations for Service type change

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, cmd/antrea-agent/agent.go, pkg/agent/controller/egress/egress_controller.go, pkg/agent/controller/egress/egress_controller_test.go, pkg/agent/controller/egress/id_allocator.go, pkg/agent/controller/egress/id_allocator_test.go, pkg/agent/controller/egress/local_ip_detector.go, pkg/agent/controller/egress/local_ip_detector_linux.go, pkg/agent/controller/egress/local_ip_detector_windows.go, pkg/features/antrea_features.go, test/e2e/egress_test.go, test/e2e/framework.go
The controller watches Egress and EgressGroup API and calls openflow
client and route client to enforce an Egress.
Co-authored-by: ceclinux <ceclinux@users.noreply.github.com>
For #1924
=> Add controller to antrea-agent for implementing Egress

test/e2e/traceflow_test.go
Fixes these:
1. One of name gen in TF test for IPv6 is invalid.
2. One of name gen in TF test for IPv4 is unnecessary.
3. Add `Packet` with `IPv6Header` to `tf.Spec` in inter/intraNodeICMPDstIPLiveTraceflowIPv6 cases
=> Fix TF test name gen 

pkg/controller/networkpolicy/status_controller.go
Fix the issue when the status_controller tries to update NetworkPolicyStatus to Pending, it always assumes the policy is Antrea NetworkPolicy instead of Antrea ClusterNetworkPolicy. This will result in failures in status updates which are visible at lowest klog verbose level.
=> Fix syncHandler issue in status_controller

pkg/agent/cniserver/server.go, test/integration/agent/cniserver_test.go
As per the CNI specification for the Add command:
> If the plugin was supplied a prevResult as part of its input
configuration, it MUST handle prevResult by either passing it through,
or modifying it appropriately.
In networkPolicyOnly mode, CNI chaining is used. Antrea receives a
prevResult from the container runtime and must output it in case of
success. We do not make any changes to the result, but we may convert it
to a different CNI version format (the default one for Antrea).
Previously, Antrea would output the entire input configuration (which
does include prevResult), which would cause containerd to return an
error.
The integration test was incorrect and had to be fixed.
Fixes #2002
=> Use correct output format for CNI Add in networkPolicyOnly mode

pkg/antctl/antctl_test.go, pkg/antctl/raw/proxy/command.go, pkg/antctl/raw/traceflow/command.go
For traceflow and proxy, antctl will fail and log error when the user
enters extra postional arguments.
Before:
```
name: default-coredns-7f89b7bc75-4xzxg-to-default-coredns-7f89b7bc75-cczbd-xzfgd55x
phase: Running
source: default/coredns-7f89b7bc75-4xzxg
destination: default/coredns-7f89b7bc75-cczbd
...
```
After:
```
Error: adding extra postional arguments
```
Fixes #1915
=> Reject unsupported postional arguments for antctl

CHANGELOG.md, hack/.notableofcontents
Not sure why this wasn't caught earlier, maybe we were hitting a 429 error, which I think is possible for these Github links, and is considered a success by the deadlink checker.
=> Fix deadlink after docs/arm-support.md was removed

ci/jenkins/test.sh
NO_PULL needs to be set before invoking the Makefile to build the Docker
image on the Windows Nodes.
=> Do not pull from Dockerhub in Windows Jenkins jobs

docs/feature-gates.md
=> Document Egress feature

pkg/agent/nodeportlocal/k8s/npl_controller.go, pkg/agent/nodeportlocal/npl_agent_test.go
When Host Port is defined, use same port in NPL annotation, without
reserving port from NPL port range. Avoid adding redundant IP table
entry in NPL code.
=> Avoid allocating NPL port if Host Port is defined

pkg/agent/route/route_linux.go, test/integration/agent/route_test.go
Local out packets destined for Pods have "0x1/0x1" mark. Add a condition
that restricts the out interface to Egress's SNAT rule to filter out
those packets.
=> Avoid Egress's SNAT rules being applied to unintended traffic

pkg/ovs/openflow/ofctrl_bridge.go
Logging every packet can generate great amount of logs for NetworkPolicy
logging and rejection. Change the verbosity level to V(2).
=> Increase verbosity level of logging OVS packet_in

docs/windows.md
quick update for antrea, as a windows service
=> Update windows.md to run as a windows service (in support of containerd) 

cmd/antrea-agent/agent.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/util/ip/ip.go, test/e2e/flowaggregator_test.go
Fixes #1925 
In this PR, we implemented the logic of flowType value assignment.
We distinguished Pod-To-Pod flows and Pod-To-External flows using the podCIDRs of all nodes in the k8s cluster.
=> Add flowType field for Flow Exporter

pkg/agent/controller/networkpolicy/packetin.go, pkg/support/dump.go, pkg/support/dump_others.go, pkg/support/dump_windows.go, pkg/util/logdir/logdir.go, pkg/util/logdir/logdir_others.go, pkg/util/logdir/logdir_windows.go
On Windows Nodes the path should be /k/antrea/logs/networkpolicy/np.log
and not /var/log/antrea/networkpolicy/np.log, as decided by the log_dir
flag.
We unify the approach for support bundle and Network Policy logging.
Fixes #2050
=> Fix Network Policy logging on Windows Nodes

ci/jenkins/test.sh
Does not affect functionality but avoids polluting the logs with
misleaading error messages.
=> Minor improvements to Windows Jenkins test script

README.md
This will ensure meeting time does not fluctuate for countries
that adopt DST. Also remove conversion in local time zone as
they don't make much sense in the weeks in which countries are
switching on/off DST.
=> Switch meeting times to GMT

docs/versioning.md
The current major version number for Antrea is 1, and it is not 0
anymore.
=> Remove outdated information from versioning document

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent.yml
Starting with v1.21, Kubernetes supports default container annotation. Using "kubectl logs/exec/attach/cp" doesn't have to specify "-c antrea-agent" when troubleshooting.
=> Specify antrea-agent as the default container for kubectl cmds

ci/jenkins/mellanox/common/common_functions.sh
In hw-offload CI `go get` started to fail on recent Kubernetes version
because of a bug in go mods. This patch uses git to directly clone the
Kubernetes project source.
=> [CI] Clone Kubernetes using `git` instead of `go get`

.github/workflows/build_tag.yml
When dispatching the build workflow to the
vmware-tanzu/antrea-build-infra repository (to build the multi-arch
Antrea docker image), the docker-tag parameter was wrong (empty string
instead of the Github tag).
=> Fix typo in build_tag workflow

test/e2e/README.md
brew recently disabled `brew cask install` and switch to `brew install --cask`. 
This PR updates the readme to use the new command.
You can see others talking about the change here: https://github.com/ansible-collections/community.general/issues/1524
=> update brew install commands

pkg/agent/util/net_windows.go
The second parameter to wait.PollImmediate (the timeout) is a
time.Duration value. When using 5 as the parameter value, it is
interpreted as 5ns, and not 5s. This means that EnableHostInterface
basically never does any retry.
=> [Windows] Fix timeout value for EnableHostInterface

ci/kind/test-e2e-kind.sh, ci/kind/test-upgrade-antrea.sh
Sometimes antrea upgrade check fails when docker pulling antrea-ubuntu image because of "Error response from daemon: missing or empty Content-Length header". It happens occasionally and retry should help.
https://github.com/vmware-tanzu/antrea/runs/2305288919?check_suite_focus=true
https://github.com/vmware-tanzu/antrea/runs/2305321865?check_suite_focus=true
=> [CI] Retry docker pulling if failure when testing Antrea upgrade

pkg/agent/controller/networkpolicy/cache.go, pkg/agent/controller/networkpolicy/cache_test.go, pkg/agent/controller/networkpolicy/networkpolicy_controller.go, pkg/agent/controller/networkpolicy/networkpolicy_controller_test.go, pkg/agent/controller/networkpolicy/status_controller.go, pkg/agent/controller/networkpolicy/status_controller_test.go, test/e2e/antreapolicy_test.go
A Policy rule may have multiple AppliedToGroups, not all of which select
some workloads on the Nodes that the Policy applies to. It's by design
that an AppliedToGroup won't be sent to a Node if it doesn't select any
workload on it, so agents shouldn't require all AppliedToGroups to be
received before it can realize a rule. What's more, it may happen that
none of its AppliedToGroups is sent to a Node when the rule itself is
being evaluated on the Node if it's sent to the Node because other rules
of its parent Policy apply to it.
This patch fixes the logic by making the controller install a rule when
any of its AppliedToGroups can be populated and all of its AddressGroups
can be populated, and uninstall it when none of its AppliedToGroups can
be populated.
Fixes #2083
=> Fix Antrea-native Policy with multiple AppliedTo

pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_perf_test.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go
Fixes #2086. HostNetwork Pods should not be part of AppliedToGroups as they are not in the Pod network.
=> Do not populate HostNetwork Pods into AppliedToGroups

build/yamls/patches/hwoffload/hwOffload.yml, ci/jenkins/mellanox/scripts/start_ci.sh, hack/generate-manifest.sh
Following #1617, the default image name in the antrea.yml file changed
to use the harbor image. Although the patch includes a change in the
make file to change the image name correctly in case the image was
built, the hw-offload CI uses `docker build` to build the image, and
this made it so that the CI would not use the image it was building,
but the upstream latest image.
This patch fixes that by building the antrea manifests with the image
name being the same as the one that was built.
=> [CI] Fix image names in hw-offload CI

hack/windows/Prepare-ServiceInterface.ps1, hack/windows/Reset-Node.ps1
* Reset-Node.ps1: "rm -f" will fail because "-f" is ambiguous
* Prepare-ServiceInterface.ps1: change taskkill command to print an INFO log
instead of an ERROR log if the process does not exist, to avoid confusing
users
=> [Windows] Small improvements to PowerShell installation scripts

docs/cookbooks/multus/README.md, docs/cookbooks/multus/test/Vagrantfile
- The Ansible playbooks have changed, requiring some changes to the
Vagrantfile used to provision a testbed
- Update links to multus-cni to point to the new repo
=> Update Multus cookbook

build/yamls/elk-flow-collector/elk-flow-collector.yml, build/yamls/flow-aggregator.yml, build/yamls/flow-aggregator/base/flow-aggregator.yml
When using the FlowAggregator or the ELK reference stack on a cluster
with ARM and Windows Nodes, Pods should be scheduled on Linux AMD64
Nodes.
For the FlowAggregator, we may consider providing a multi-arch Docker
manifest with support for ARM achitectures, like we do for the the
Antrea image.
=> Add nodeSelector for FlowAggregator and ELK Pods

docs/antctl.md, pkg/agent/apiserver/handlers/ovsflows/handler.go, pkg/agent/apiserver/handlers/ovsflows/handler_test.go, pkg/antctl/antctl.go, pkg/ovs/ovsctl/interface.go, pkg/ovs/ovsctl/ofctl.go, pkg/ovs/ovsctl/testing/mock_ovsctl.go, test/integration/ovs/ofctrl_test.go, test/integration/ovs/openflow_test_utils.go
FLOW
group_id=1,type=select,bucket=bucket_id:0,weight:100,actions=load:0xac640003->NXM_NX_REG3[],load:0x35->NXM_NX_REG4[0..15],load:0x2->NXM_NX_REG4[16..18],load:0x1->NXM_NX_REG0[19],resubmit(,42),bucket=bucket_id:1,weight:100,actions=load:0xac640002->NXM_NX_REG3[],load:0x35->NXM_NX_REG4[0..15],load:0x2->NXM_NX_REG4[16..18],load:0x1->NXM_NX_REG0[19],resubmit(,42)
group_id=2,type=select,bucket=bucket_id:0,weight:100,actions=load:0xac640003->NXM_NX_REG3[],load:0x23c1->NXM_NX_REG4[0..15],load:0x2->NXM_NX_REG4[16..18],load:0x1->NXM_NX_REG0[19],resubmit(,42),bucket=bucket_id:1,weight:100,actions=load:0xac640002->NXM_NX_REG3[],load:0x23c1->NXM_NX_REG4[0..15],load:0x2->NXM_NX_REG4[16..18],load:0x1->NXM_NX_REG0[19],resubmit(,42)
=> Add agent API and antctl command to dump OVS groups

ci/jenkins/test-vmc.sh
Current "if [[ $remote ]]" is always true.
=> [CI] Function run_codecov bool judgement fix

docs/network-flow-visibility.md, test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/provision.sh, test/e2e/infra/vagrant/push_antrea.sh
Modify the provision.sh script to deploy VMs with double the
memory (4096MB). This is the required node spec for the deployment
of ELK flow collector.
This will make the consumption of the Flow Visibility feature in Antrea
simpler, by enabling deployment with one command.
Fixes #2058
=> Add ELK flow collector automation to vagrant setup

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, pkg/agent/controller/traceflow/packetin.go, pkg/agent/controller/traceflow/traceflow_controller.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/antctl/raw/traceflow/command.go, pkg/apis/crd/v1alpha1/types.go, pkg/controller/traceflow/controller.go, test/e2e/traceflow_test.go
For live-traffic Traffic, allow the source to be an IP address or not
specified (which means any source). In this case, the destination Pod
must be specified, and flows will be added on the destination Node that
match the Traceflow packet with the destination Pod's MAC in
l2ForwardingCalcTable. If a packet is dropped on the source Node or
before reaching l2ForwardingCalcTable on the destination Node, it will
not be captured.
=> Support any source or IP address source in live-traffic Traceflow

pkg/agent/openflow/pipeline.go, test/e2e/networkpolicy_test.go, test/integration/agent/openflow_test.go
This PR fixes #1976.  The miscalculation is caused by `L2ForwardingCalcTable` with rule 
> Specifically, packets to the gateway port or the tunnel port will also go to ConntrackCommitTable and bypass the NetworkPolicy ingress rule tables, as NetworkPolicy ingress rules are not enforced for these packets on the  source Node.
Therefore, these packets will not get counted in this case.
=> Fix network policy ingress policy stats

cmd/antrea-agent/agent.go, pkg/agent/agent.go, pkg/agent/route/route_linux.go, pkg/agent/util/net_linux.go, test/e2e/util.go, test/integration/agent/route_test.go
Add checks to the routeClient. The required routes will be added back if they were
deleted unexpectedly. Add IP configuration check of the gateway to the agent.
An integration test is added to verify that the route will be added back correctly.
Fixes #627
=> Verify the status of required routes gateway periodically

docs/feature-gates.md, pkg/agent/openflow/client.go, pkg/agent/openflow/pipeline.go, pkg/agent/proxy/endpoints.go, pkg/agent/proxy/proxier.go, test/e2e/proxy_test.go, test/integration/agent/openflow_test.go
For #2092
Due to the message size and the implementation of Service in AtreaProxy, the maximum Endpoint that AntreaProxy can support now is 800. If the Endpoints of Service exceed 800, the exceeding Endpoints will be ignored.
In AntreaProxy, OVS group is the key part of Service implementation. For now, Antrea is using Openflow 1.3 to communicate with OVS. In previous design, every bucket of a OVS group has five actions. Two actions for loading Endpoint IP and port to registers and resubmit action must be reserved.The other two actions for loading values to register can be moved to flows (in current patch, they are moved to table 41), and then one message can hold more bucket items. As a result, the maximum Endpoint has changed from 511 to 800. Unfortunately, to ensure AntreaProxy running …
=> Extends the Endpoints support from 500 to 800, extra ones will be dropped in AntreaProxy

pkg/agent/agent.go, pkg/agent/openflow/client.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_group.go, test/e2e/connectivity_test.go
The Group objects were not reset correctly when attempting to replay
them, leading to confusing error log messages and invalid datapath
state. We fix the implementation of Reset() for groups and we ensure
that the method is called during replay.
We also update the TestOVSFlowReplay e2e test to make sure it is more
comprehensive: instead of just checking Pod-to-Pod connectivity after a
replay, we ensure that the number of OVS flows / groups is the same
before and after a restart / replay. We confirmed that the updated test
fails when the patch is not applied.
Fixes #2127
=> Fix OVS "flow" replay for groups

ci/jenkins/jobs/projects.yaml
The e2e tests job is timeout quite frequently after 100m. The go test
timeout does not need to change: based on what I can see the tests
themselves take at most 20m to run.
=> Increase Jenkins job timeout from 100m to 120m

ci/jenkins/README.md, ci/test-conformance-aks.sh, docs/kubernetes-installers.md
The default K8s version is now v1.19.9, and Nodes default to containerd
as the container runtime. As a result we cannot use docker to load the
Antrea image anymore.
=> Update AKS conformance script

.gitignore, build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/crds.yml, test/e2e/antreapolicy_test.go
Add namespaceSelector/podSelector validations in all CRD schema.
The incorrect input of labelSelector fields that have known schema should be rejected;
In the following example, we want to create ClusterNetworkPolicy resource:
spec.appliedTo.namespaceSelector must be matchLabels or matchExpressions, 
actually in the existing version the spelling mistake ‘matchLables’ can not be checked out.
Save the CustomResourceDefinition to resourcedefinition.yaml:
`cat acnp_demo.yaml`
```yaml
apiVersion: crd.antrea.io/v1alpha1
kind: ClusterNetworkPolicy
metadata:
name: blacklist
spec:
priority: 5
tier: securityops
appliedTo:
- namespaceSelector:
matchLables:
env: dummy
ingress:
- action: Drop
```
We created it succeeded without any error.
After fixed the issue, we will get the following error message …
=> Improve Antrea-native Policy CRD schema verification

ci/run-k8s-e2e-tests.sh, ci/test-conformance-aks.sh, ci/test-conformance-eks.sh, ci/test-conformance-gke.sh
* exit with a non-zero code in ci/run-k8s-e2e-tests.sh in case of a test
failure
* exit with a zon-zero code in ci/test-conformance-aks.sh in case of a
test failure (the TEST_FAILURE variable was never set to true!)
=> Improve conformance test scripts

CONTRIBUTING.md, docs/contributors/cherry-picks.md, docs/contributors/github-labels.md, hack/.notableofcontents, hack/cherry-pick-pull.sh, hack/update-toc.sh, hack/verify-toc.sh
Just like the Kubernetes project, I think we should start asking
contributors to backport their critical bug fixes themselves when
required. The main benefit is that contributors are in a better position
to resolve possible merge conflicts than whoever is responsible for the
patch release. If the contributor cannot take care of it, a maintainer
can still step up and handle that task.
To simplify this process, we provide a script which will take care of
cherry-picking the change to the correct release branch, and will
automatically open a PR on Github, with the 'kind/cherry-pick'
label. The script is basically a copy of the one provided for
Kubernetes.
We also add documentation to guide contributors through the
cherry-picking process.
Fixes #1532
=> Add script for semi-automatic bug fix backporting

test/e2e/clustergroup_test.go, test/e2e/k8s_util.go, test/e2e/legacyclustergroup_test.go
The test was not deleting the x, y and z Namespaces.
The implementation of the Cleanup function is also modified to avoid
early exit on error, so that all resources can get a chance to be
deleted. Instead, we log any error that may occur.
=> Fix cleanup for the TestClusterGroup e2e test

site/_config.yml, site/_redirects, site/golang/antrea.html
The import path for the Antrea Go module will now be "antrea.io/antrea".
We leverage Netlify's redirect support (this is inspired by the Knative
project) to serve the necessary HTML content. It will be super easy to
add new Go modules in the future.
For now "antrea.io/antrea" points to "github.com/vmware-tanzu/antrea".
After we transfer Antrea to the new Github organization (antrea-io), we
will update the HTML file appropriately.
See #2154
=> [Website] Set up vanity import path for Antrea

pkg/apis/controlplane/types.go, pkg/apis/controlplane/v1beta1/generated.proto, pkg/apis/controlplane/v1beta1/types.go, pkg/apis/controlplane/v1beta2/generated.proto, pkg/apis/controlplane/v1beta2/types.go, pkg/apis/crd/v1alpha1/types.go, pkg/apis/crd/v1beta1/types.go, pkg/apis/system/v1beta1/types.go
Fixed some annotations that violated the golang struct annotation specification.
=> Improve the annotations of some structs in pkg/api

.github/workflows/build.yml, .github/workflows/build_tag.yml
This repo has not moved (yet), so antrea-io/antrea-build-infra is not
correct.
=> Fix incorrect update to vmware-tanzu/antrea-build-infra repo

pkg/graphviz/traceflow.go, plugins/octant/cmd/antrea-octant-plugin/main.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
1. add new tab to support live traffic UI
2. refine 'Generate Trace Graph' tab to allow user to chose from CRD list instead of input a traceflow name directly
3. refine log and alert output
Implementation as part of issue https://github.com/vmware-tanzu/antrea/issues/2030
=> add livetraffic support in octant plugin

ci/jenkins/test-vmc.sh
Previously it retried once and ignored the failures if it kept failing,
which lead to confusing logs in the following process. This patch also
adds one more retry.
For example, the following tests actually failed because of pulling images but the errors were ignored and they continued building and then failed when using the images:
https://jenkins.antrea-ci.rocks/job/antrea-e2e-for-pull-request/2494/console
https://jenkins.antrea-ci.rocks/job/antrea-networkpolicy-for-pull-request/2101/console
https://jenkins.antrea-ci.rocks/job/antrea-all-features-conformance-for-pull-request/695/console
```
20.04: Pulling from antrea/ubuntu
Digest: sha256:86ac87f73641c920fb42cc9612d4fb57b5626b56ea2a19b894d0673fd5b4f2e9
Status: Image is up to date for …
```
=> [CI] Exit immediately if building images fails

Makefile, hack/release/prepare-assets.sh
antrea-cni can be installed (by the initContainer) on systems with
incompatible system libraries. To increase portability, we build
antrea-cni without cgo by setting CG_ENABLED to 0.
Same goes for release binaries (e.g. antctl). Note that when
cross-compiling, cgo is disabled by default, so there is no change there
(e.g. antctl binary for macOS). It's only for native Linux amd64 builds
that there is an actual change.
Fixes #2095
=> Build antrea-cni binary and release binaries without cgo

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/agent-rbac.yml, pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/agent_windows.go, pkg/agent/types/annotations.go, pkg/agent/util/net_windows.go, pkg/util/env/env.go, pkg/util/env/env_test.go
To bypass Windows host network when forwarding Pod egress traffic in noencap mode, antrea-agent needs to know peer Nodes' MAC addresses so that it can configure Openflow rules which route the packets to underlay network via uplink interface directly.
To discover the MAC addresses, the PR makes each antrea-agent report its uplink's MAC address to the Node's annotation, then other agents can get it when the NodeRouteController configures route/flows to this Node.
For #2157
=> Update Node's MAC address to the Node's annotation for direct routing

build/yamls/antrea-windows.yml, build/yamls/windows/base/conf/antrea-agent.conf, docs/network-flow-visibility.md, pkg/agent/flowexporter/connections/conntrack_windows.go, pkg/flowaggregator/certificate.go
In this commit, we fix the error when running Flow Exporter on Windows node with Flow Aggregator.
There is a limitation in DNS resolution on Windows, `flow-aggregator.flow-aggregator.svc` DNS name couldn't be resolved.
The reason is because on Windows the Antrea Agent runs as a process, it uses the host's default DNS setting and the DNS resolver will not be configured to talk to the CoreDNS Service for cluster local DNS queries like`flow-aggregator.flow-aggregator.svc`.
So we require `flowCollectorAddr` could only be IP for Flow Exporter on Windows node.
For Flow Aggregator, we add IP in certicate since flow exporter on Windows node can't resolve DNS name.
Also change to use `dpctl/ct-get-limits` intead of `dpctl/ct-get-maxconns` since it returns operation not supported on Windows node.
=> Windows support for Flow Exporter with Flow Aggregator

pkg/agent/flowexporter/connections/connections.go, pkg/agent/flowexporter/connections/conntrack_linux.go, pkg/agent/flowexporter/connections/conntrack_linux_test.go, pkg/agent/flowexporter/connections/conntrack_ovs.go
In this commit, we add the parsing code of labels field for dump-conntrack command output in OVS userspace datapath situation.
This will fix the missing network policy information issue in flow records in OVS userspace datapath, like in Kind cluster.
=> Fix network policy issue in userspace datapath of Flow Exporter

pkg/agent/agent_windows.go, pkg/agent/util/net_windows.go
Receive Segment Coalescing (RSC) helps reduce host CPU utilization and increases throughput for virtual workloads by coalescing multiple TCP segments into fewer, but larger segments.
In a test environment, the throughput improvement is about 4x.  
=> [Windows] Enable RSC in the vSwitch to optimize network performance

build/images/base/Dockerfile, build/images/scripts/install_cni
Whereabouts IPAM package support for Antrea
- Required for CNF use case support.
=> whereabouts IPAM package support for Antrea

.github/workflows/kind.yml, .github/workflows/kind_upgrade.yml, .github/workflows/netpol_cyclonus.yml, ci/kind/kind-setup.sh, pkg/controller/networkpolicy/networkpolicy_controller.go, pkg/controller/networkpolicy/networkpolicy_controller_test.go, test/e2e/infra/vagrant/playbook/roles/control-plane/templates/kubeadm.conf.j2, test/e2e/networkpolicy_test.go
This PR fixes #1638.
Change the process of K8sNP -> InternalNP.
To use `endPort` in kube-apiserver, add featrue-gates flag.
=> Add K8sNP endPort support

pkg/agent/nodeportlocal/rules/iptable_rule.go, pkg/agent/route/route_linux.go, test/e2e/nodeportlocal_test.go, test/integration/agent/route_test.go
The following changes were required:
* ANTREA-NODE-PORT-LOCAL nat chain needs to be linked to OUTPUT in
addition to PREROUTING.
* For the OUTPUT case, traffic needs to be masqueraded to ensure that
the local gateway's IP is used as the source. Otherwise ARP requests may
advertise a different source IP address, in which case they will be dropped
by the SpoofGuard table in the OVS pipeline (see arp_announce sysctl
parameter). We masquerade all local traffic egressing through the gateway
for which the source IP address does not match any address assigned to
the gateway.
In addition to the above changes, we also add a new match to the NPL
iptables rules so that DNAT is only performed when the destination IP is
local.
Fixes #1923
=> Fix local access (from worker Node) to Node Port Local ports

pkg/agent/proxy/proxier.go, pkg/agent/proxy/proxier_test.go, pkg/agent/proxy/service.go, pkg/agent/proxy/types/types.go, third_party/proxy/doc.go, third_party/proxy/meta_proxier.go, third_party/proxy/service.go, third_party/proxy/types.go, third_party/proxy/util/service.go, third_party/proxy/util/utils.go
This is the following PR separated from https://github.com/antrea-io/antrea/pull/1973.
Kubernetes 1.21 add support for [dual-stack services](https://github.com/kubernetes/kubernetes/pull/91824). To support this we need to update `third_party/proxy` pkg to reflect the recent changes in the upstream kubernetes repo. Unit tests are added accordingly.
=> Add dual-stack service support

pkg/agent/nodeportlocal/rules/iptable_rule.go, test/e2e/nodeportlocal_test.go
A bug was introduced in https://github.com/antrea-io/antrea/pull/2200: I
unified some code but ended up forgetting to prepend the chain name in
the code that syncs up rules on restart. This causes the
iptables-restore command to fail, and the NPL controller to shut down.
Unfortunately this was not caught by any of the e2e tests, so I updated
one of them to ensure that similar mistakes can be avoided in the
future.
=> Fix NodePortLocal bug when syncing-up iptables rules on restart

build/yamls/antrea-windows.yml, build/yamls/windows/base/conf/antrea-agent.conf, cmd/antrea-agent/options_windows.go, cmd/antrea-agent/options_windows_test.go, pkg/agent/controller/noderoute/node_route_controller.go, pkg/agent/controller/noderoute/node_route_controller_test.go, pkg/agent/openflow/client.go, pkg/agent/openflow/client_test.go, pkg/agent/openflow/pipeline.go, pkg/agent/openflow/pipeline_other.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/openflow/testing/mock_openflow.go, pkg/agent/route/route_windows.go, pkg/agent/route/route_windows_test.go, test/integration/agent/openflow_test.go
This PR implements support for Windows Noencap mode. It also includes flow optimization to improve
Pod to Pod performance.
Noencap: If same subnet, destination MAC in OVS is set with peer Node annotation. If not, host routing will
be used to forward traffic.
Hybrid: If same subnet, same as Noencap with same subnet. If not, same as Encap mode.
Supersedes #1901
Fixes #1632
=> [Windows] NoEncap support

pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, test/e2e/flowaggregator_test.go
We need to reset set and prepare the set as a template set before sending the template record. Otherwise, the flow aggregator will crash when retrying to establish the connection to the flow collector. The bug was the missing reset set operation.
In addition, during this failure, the test is taking a long time to finish.
Fix the e2e flow aggregator test timeouts. Timeout values are quite high when the tests are failing
intermittently on dual-stack clusters.
Fix that by reducing poll timeout when checking for logs on ipfix-collector pod.
Fixes #2035
=> Fix bug in FlowAggregator when sending template set

build/yamls/elk-flow-collector/logstash/filter.rb, build/yamls/elk-flow-collector/logstash/ipfix.yml, docs/network-flow-visibility.md, pkg/agent/controller/networkpolicy/packetin.go, pkg/agent/flowexporter/connections/conntrack_connections.go, pkg/agent/flowexporter/connections/conntrack_connections_test.go, pkg/agent/flowexporter/exporter/exporter.go, pkg/agent/flowexporter/exporter/exporter_test.go, pkg/agent/flowexporter/types.go, pkg/agent/flowexporter/utils.go, pkg/flowaggregator/flowaggregator.go, test/e2e/flowaggregator_test.go
1. Add fields: network policy type, rule name to flow records of flow exporter
2. Update related unit-tests, e2e tests
3. Make necessary changes on elk-flow-collector and flow-visibility doc
Fixes #1545
=> Add network policy related metadata to flow records

ci/clair-scan/run.sh
Recently some the clair-scan CI job has been failing because of an error
during cleanup. It seems that by the time we call "docker kill", at
least one of the containers (clair) may not exist any more. Maybe the
process is crashing, but the scan does complete successfully every time
regardless... To avoid job failures, we tolerate errors when calling
"docker kill" during the cleanup phase.
=> Do not fail clair-scan if docker containers cannot be killed

test/e2e/k8s_util.go
when I ran antrea 0.13.2 with e2e:
=== RUN   TestAntreaPolicy
fixtures.go:121: Creating 'antrea-test' K8s Namespace
fixtures.go:84: Applying Antrea YAML
fixtures.go:88: Waiting for all Antrea DaemonSet Pods
fixtures.go:92: Checking CoreDNS deployment
...
fatal error: concurrent map writes
goroutine 1053 [running]:
runtime.throw(0x1b31cf4, 0x15)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0017cb388 sp=0xc0017cb358 pc=0x43a5d2
runtime.mapassign_faststr(0x18f1d40, 0xc000940ed0, 0xc000db84e8, 0x7, 0x3)
/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0017cb3f0 sp=0xc0017cb388 pc=0x4168b1
github.com/vmware-tanzu/antrea/test/e2e.(*KubernetesUtils).GetPods(0xc0006992e0, 0xc0009c6ee3, 0x1, 0x1b17f8d, 0x3, 0xc0009c6ee5, 0x1, 0x0, 0x0, 0x0, ...) …
=> add lock for podCache in case of concurrent map writes

build/yamls/antrea-aks.yml, build/yamls/antrea-eks.yml, build/yamls/antrea-gke.yml, build/yamls/antrea-ipsec.yml, build/yamls/antrea.yml, build/yamls/base/antctl.yml, build/yamls/base/controller-rbac.yml, build/yamls/base/controller.yml, build/yamls/base/kustomization.yml, cmd/antrea-controller/controller.go, docs/antctl.md, pkg/agent/apiserver/apiserver.go, pkg/agent/apiserver/handlers/featuregates/handler.go, pkg/antctl/antctl.go, pkg/antctl/command_definition.go, pkg/antctl/command_list.go, pkg/antctl/raw/featuregates/command.go, pkg/antctl/raw/helper.go, pkg/antctl/raw/proxy/command.go, pkg/antctl/raw/supportbundle/command.go, pkg/antctl/raw/traceflow/command.go, pkg/apiserver/apiserver.go, pkg/apiserver/handlers/featuregates/handler.go, pkg/apiserver/handlers/featuregates/handler_test.go, pkg/apiserver/registry/system/controllerinfo/rest_test.go, pkg/controller/querier/querier.go, pkg/features/antrea_features.go, pkg/util/env/env.go, pkg/util/env/env_test.go, test/e2e/antctl_test.go
allow user to run `antctl get featuregates` inside of agent or controller container or out of cluster to get feature gates information.
Resolves https://github.com/vmware-tanzu/antrea/issues/2010
sample cli:
```
#antctl get featuregates
Antrea Agent Feature Gates
FEATUREGATE              STATUS         VERSION
AntreaProxy              Enabled        BETA
Egress                   Disabled       ALPHA
EndpointSlice            Disabled       ALPHA
Traceflow                Enabled        BETA
FlowExporter             Disabled       ALPHA
NetworkPolicyStats       Disabled       ALPHA
NodePortLocal            Disabled       ALPHA
AntreaPolicy             Enabled        BETA
Antrea Controller Feature Gates
FEATUREGATE              STATUS         VERSION
NetworkPolicyStats       Disabled …
```
=> print featuregates via antctl

docs/maintainers/release.md, hack/release/process-changelog.go
This is a new script I wrote to simplify writing the CHANGELOG ahead of
a release. It takes care of automatically generating links for PRs and
PR authors.
=> Add Go script to process CHANGELOG files before releases

hack/netpol-generator/install-cyclonus.yml, hack/netpol-generator/test-kind.sh
It has been failing ever since we updated to a more recent version of
Kind (v0.11), which comes with a more recent version of K8s. To fix it,
we need to update to a more recent Cyclonus version.
=> Fix Cyclonus NetworkPolicy Github workflow

pkg/flowaggregator/flowaggregator.go, test/e2e/flowaggregator_test.go
This PR fixed missing correlation of `egressNetworkPolicyRuleAction` in correlate fields, which is useful for filling `egressNetworkPolicyRuleAction` in flow aggregator. 
It also removes duplication code in e2e tests caused by rebasing 
Thanks @heanlan for raising this issue.
=> [Flow Aggregator] Fix missing correlation and sanitize e2e tests

test/e2e/nodeportlocal_test.go
Looks like there could be contention if the Agent is still writing rules
for other Pods.
=> Wait for iptables lock when deleting rule in NodePortLocal e2e tests

test/e2e/framework.go
In dual-stack case, when running ping command for IPv6, the command includes "-4 <IPv4-addr>" and "-6 <IPv6-add>".
=> [CI][e2e] Fix bugs in runPingCommandFromTestPod

build/yamls/patches/sriov/sriov.yml, go.mod, go.sum, hack/generate-manifest.sh, pkg/agent/cniserver/interface_configuration_linux.go, pkg/agent/cniserver/interface_configuration_windows.go, pkg/agent/cniserver/pod_configuration.go, pkg/agent/cniserver/sriov.go, plugins/octant/go.sum
This is an initial PR to provide SR-IOV support for secondary interface:
• API support added to configure SR-IOV VFs as secondary interface.
• Depends on vendor specific NIC configuration, creation of VFs and
configuration of the SR-IOV Network Device Plugin.
• Does not configure OVS flows.
=> Add SR-IOV secondary interface support

pkg/agent/cniserver/interface_configuration_windows.go
ensureHNSNetwork may be called in parallel but the variable hnsNetwork
was not protected by lock, which could lead to data race. This patch
fixes it by initializing the variable when ifConfigurator is instantiated.
It also removes an unused variable.
=> [Windows] Fix the race condition in ifConfigurator

plugins/octant/cmd/antrea-octant-plugin/main.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
A "RUN TRACE AGAIN" option has been added to the Octant UI. The new graph's label is changed to reflect the time the trace was run again.
Fixes: #2178
Signed-off-by: Dhruv Jain <2dhruv@gmail.com>
=> Added functionality for running the same trace request again with the same parameters.

pkg/agent/config/traffic_encap_mode.go, pkg/agent/config/traffic_encap_mode_test.go, pkg/agent/openflow/pipeline_windows.go, pkg/agent/route/route_linux.go, pkg/agent/route/route_windows.go
It was confusing that antrea-agent needed to add a route to the routing
table when NeedsRoutingToPeer returns false. "Need Routing" here meant
the Node cannot reach peer Node directly and it needs routing support
from the network connecting the Nodes. To make it clear, this patch
changes the method name to "NeedsDirectRoutingToPeer" and returns true
if the Node can reach peer Node directly which indicates antrea-agent
needs to add a direct route to the routing table.
=> Improve readability of NeedsRoutingToPeer method

pkg/agent/cniserver/interface_configuration_windows.go
Cherry pick of #2253 on release-1.1.
#2253: Fix the race condition in ifConfigurator
=> Automated cherry pick of #2253: Fix the race condition in ifConfigurator

plugins/octant/cmd/antrea-octant-plugin/main.go, plugins/octant/cmd/antrea-octant-plugin/traceflow.go
After checking with the Octant developers, we need to protect the global
plugin state in case multiple client sessions are opened (e.g. multiple
tabs). While this is not a typical use case, it could potentially lead
to some data corruption.
We don't try to get fancy with the locking scheme, i.e. we don't try to
keep the size of the critical section small, as it doesn't seem to
matter much in this case. The goal is to ensure code correctness.
Note that the K8s client itself is thread-safe, and it is never updated
after initialiation.
=> Protect Traceflow state from concurrent access in Octant plugin

test/e2e/service_test.go
The curl command should use '--retry-connrefused', as refused
connections are not considered transient erros by default (and won't
cause retries otherwise).
=> Fix TestClusterIPHostAccess flakes

pkg/ovs/ovsctl/appctl.go, pkg/ovs/ovsctl/ovsctl_others.go, pkg/ovs/ovsctl/ovsctl_windows.go
Make the code more robust by removing the assumption that there is a
single ovs-vswitch control socket file in /var/run/openvswitch when
running ovs-appctl. Instead we read the ovs-vswitchd PID from the
pidfile and use the read value to determine the correct control socket
file.
While we do remove stale .ctl files in the start_ovs script, I recently
noticed that we were not doing the same thing in the start_ovs_netdev
script, leading to issues when running ovs-appctl commands in
antrea-agent. It's probably a good idea to remove stale .ctl files in
start_ovs_netdev when (re)starting OVS, but in the meantime it also
feels like a good idea to remove the assumption of a single .ctl file
from the antrea-agent code.
=> Remove assumption that there is a single ovs-vswitchd .ctl file

ci/jenkins/jobs/job-templates.yaml, ci/jenkins/jobs/projects.yaml
There's no need to clone antrea repo if it is a pending or skip job.
This PR should fasten job build speed by deleting scm related fields in
job-template.
=> [CI] Don't clone repo if pending or skip jobs

build/images/scripts/start_ovs_netdev, ci/kind/kind-setup.sh, hack/kind-fix-networking.sh, test/e2e/antreapolicy_test.go, test/e2e/fixtures.go
According to the OVS documentation:
On Linux, when a physical interface is in use by the userspace datapath,
packets received on the interface still also pass into the kernel TCP/IP
stack. This can cause surprising and incorrect behavior. You can use
"iptables" to avoid this behavior, by using it to drop received packets.
The OVS documentation suggests dropping packets in the INPUT and FORWARD
chains. However, this is not sufficient for some edge cases. For
example, when receiving a TCP RST packet, the packet will clear the
conntrack entry for the TCP connection before it can be dropped, which
can cause the "second" TCP RST packet (the one processed by OVS
userspace) to be marked as invalid when going through conntrack.
So instead we drop the packet in PREROUTING:
iptables -t raw -A …
=> Drop eth0 packets in PREROUTING on Kind Nodes

.github/workflows/cancel_workflows.yml
add a cancel workflow so when there is a new push
previous workflow will be cancelled which will help to reduce
concurrent github runner usage and reduce unnecessary waiting time.
refer to https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks
according to github page [here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run)
this file has to be in default branch first to take affect.
this is a part of issue #2014 
=> [CI]add a workflow to cancel previous running workflow

test/e2e/infra/vagrant/Vagrantfile, test/e2e/infra/vagrant/provision.sh
kubeadm dual-stack support is Beta in v1.21, so we add support for
dual-stack when setting up the reference local Vagrant cluster (for
local development). The provision.sh needs to be run with '--ip-family
dual'.
Unlike for IPv6-only clusters, Pods can still access the Internet (over
IPv4 only) and upstream DNS queries can work without needing a v6-to-v4
DNS proxy.
=> Support dual-stack Vagrant-based clusters

ci/jenkins/jobs/projects.yaml
It is frequently timing out in cleanup.
=> Increase timeout for jenkins-networkpolicy CI job

ci/jenkins/test-vmc.sh, ci/jenkins/test.sh
See #2292
We apply the workaround for all jobs run in Jenkins, as in addition to
dual-stack failures, I have also observed failures for jobs run in VMC,
which may have the same root cause.
=> Temporary workaround for e2e test memory leak

ci/kind/test-e2e-kind.sh, go.mod, go.sum, pkg/flowaggregator/flowaggregator.go, pkg/flowaggregator/flowaggregator_test.go, pkg/ipfix/ipfix_intermediate.go, pkg/ipfix/testing/mock_ipfix.go, plugins/octant/go.sum, test/e2e/flowaggregator_test.go, test/e2e/framework.go
For dual stack, each pod should have two ips (IPv4 and IPv6). This commit adds support for multiple ip indexing in flow aggregator for pod informer which will fix missing fields issue in flow record for dual stack setup.
It also fixes data record decoding issue of mismatch templates by adding two more templates for covering the cases when pod ips and original exporter ip are in different ip families.
fixes #2282
=> Fix template and fields missing issue in dual stack e2e tests

test/e2e/connectivity_test.go, test/e2e/flowaggregator_test.go, test/e2e/framework.go, test/e2e/networkpolicy_test.go
In the current flow-aggregator e2e tests, we have tests for flow types: intra-node and inter-node. This PR adds a test case for pod-to-external flow type. It takes a busybox pod as the source pod (client), a host network nginx pod as the destination (server). Server's IP will be the node's IP where it is deployed on. Let the client send requests to the server, then we generate pod-to-external flows. Finally we check the exports of IPFIX flow records.
Thanks @antoninbas 's suggestions on generating pod-to-external traffic.
=> Add flow-aggregator e2e test for pod-to-external flow type

ci/jenkins/test.sh, test/e2e/fixtures.go, test/e2e/service_test.go
* Pull necessary images for Windows Conformance tests
* Added one e2e test to test NodePort Service on Windows to replace the
one from Kubernetes conformance
=> [CI] Fix Windows conformance

cmd/antrea-controller/controller.go, pkg/controller/egress/controller.go, pkg/controller/egress/controller_test.go, pkg/controller/egress/ipallocator/allocator.go, pkg/controller/egress/ipallocator/allocator_test.go
If users don't specify EgressIP of an Egress, antrea-controller will allocate one IP from the specified ExternalIPPool if it's available.
For #2128
=> Support allocating Egress IPs from ExternalIPPools

build/images/scripts/start_ovs_netdev, go.mod, go.sum, pkg/agent/openflow/client.go, pkg/agent/openflow/meters_linux.go, pkg/agent/openflow/meters_others.go, pkg/agent/openflow/packetin.go, pkg/agent/openflow/pipeline.go, pkg/ovs/openflow/interfaces.go, pkg/ovs/openflow/ofctrl_action.go, pkg/ovs/openflow/ofctrl_bridge.go, pkg/ovs/openflow/ofctrl_meter.go, pkg/ovs/openflow/testing/mock_openflow.go, pkg/util/runtime/runtime_linux.go, plugins/octant/go.sum
Add OF meter to implement rate-limiting for packet-in messages.
1. Add meter entries during initialization: one for Traceflow packets
and one for other (NetworkPolicy-related) packets.
2. While building the flow that will trigger packet-in, use the meter
action.
3. Update libOpenflow and ofnet version, to get meter programming
support.
Since Windows OVS doesn't support OF meters, we skip OF meter related
operations for now. On Linux, for the OVS kernel datapath, kernel
version 4.18 is required for meter support (should be 4.15, but is 4.18
in practice because of an implementation bug): we add a check and
disable meters if the Linux kernel is not recent enough. This is to
avoid increasing the minimum kernel version requirement for Antrea, at
least for now.
Fixes #2069
Co-authored-by: …
=> Packet-in rate limiting with OF Meter

pkg/apis/controlplane/v1beta1/conversion.go, pkg/apis/controlplane/v1beta1/conversion_test.go
controlplane.Service couldn't be converted to v1beta1.Service directly as it has an extra field. This patch fixes it by using the auto-generated conversion function.
Fixes #2303
It may need to be backported to 0.13, 1.0, and 1.1.
=> Fix MarshalJSON error caused by incorrect conversion function

pkg/legacyapis/controlplane/v1beta1/conversion.go, pkg/legacyapis/controlplane/v1beta1/register.go
1. v1beta1.controlplane.antrea.tanzu.vmware.com used v1beta2 types by
mistake.
2. Field selectors for v1beta1.controlplane.antrea.tanzu.vmware.com
was not registered, which broke "nodeName" fieldSelector.
Fixes #2304
It may need to be backported to 1.0 and 1.1.
=> Fix wrong types and missing field selectors in legacy APIs
